package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class AL {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Água Branca", "AL"));
        lista.add(new Cidade("", "Alazão", "AL"));
        lista.add(new Cidade("", "Alecrim", "AL"));
        lista.add(new Cidade("", "Anadia", "AL"));
        lista.add(new Cidade("", "Anel", "AL"));
        lista.add(new Cidade("", "Anum Novo", "AL"));
        lista.add(new Cidade("", "Anum Velho", "AL"));
        lista.add(new Cidade("", "Arapiraca", "AL"));
        lista.add(new Cidade("", "Atalaia", "AL"));
        lista.add(new Cidade("", "Baixa da Onça", "AL"));
        lista.add(new Cidade("", "Baixa Grande", "AL"));
        lista.add(new Cidade("", "Bananeiras", "AL"));
        lista.add(new Cidade("", "Barra de Santo Antônio", "AL"));
        lista.add(new Cidade("", "Barra de São Miguel", "AL"));
        lista.add(new Cidade("", "Barra do Bonifácio", "AL"));
        lista.add(new Cidade("", "Barra Grande", "AL"));
        lista.add(new Cidade("", "Barreiras", "AL"));
        lista.add(new Cidade("", "Barro Vermelho", "AL"));
        lista.add(new Cidade("", "Batalha", "AL"));
        lista.add(new Cidade("", "Batingas", "AL"));
        lista.add(new Cidade("", "Belém", "AL"));
        lista.add(new Cidade("", "Belo Monte", "AL"));
        lista.add(new Cidade("", "Boa Sorte", "AL"));
        lista.add(new Cidade("", "Boa Vista", "AL"));
        lista.add(new Cidade("", "Boca da Mata", "AL"));
        lista.add(new Cidade("", "Bom Jardim", "AL"));
        lista.add(new Cidade("", "Bonifácio", "AL"));
        lista.add(new Cidade("", "Bonsucesso", "AL"));
        lista.add(new Cidade("", "Boqueirão", "AL"));
        lista.add(new Cidade("", "Botafogo", "AL"));
        lista.add(new Cidade("", "Branquinha", "AL"));
        lista.add(new Cidade("", "Cacimbinhas", "AL"));
        lista.add(new Cidade("", "Cajueiro", "AL"));
        lista.add(new Cidade("", "Caldeirões de Cima", "AL"));
        lista.add(new Cidade("", "Camadanta", "AL"));
        lista.add(new Cidade("", "Campestre", "AL"));
        lista.add(new Cidade("", "Campo Alegre", "AL"));
        lista.add(new Cidade("", "Campo Grande", "AL"));
        lista.add(new Cidade("", "Cana Brava", "AL"));
        lista.add(new Cidade("", "Canafístula", "AL"));
        lista.add(new Cidade("", "Canapi", "AL"));
        lista.add(new Cidade("", "Canastra", "AL"));
        lista.add(new Cidade("", "Capela", "AL"));
        lista.add(new Cidade("", "Carneiros", "AL"));
        lista.add(new Cidade("", "Carrasco", "AL"));
        lista.add(new Cidade("", "Chã Preta", "AL"));
        lista.add(new Cidade("", "Coité do Nóia", "AL"));
        lista.add(new Cidade("", "Colônia Leopoldina", "AL"));
        lista.add(new Cidade("", "Colônia Pindorama", "AL"));
        lista.add(new Cidade("", "Coqueiro Seco", "AL"));
        lista.add(new Cidade("", "Coruripe", "AL"));
        lista.add(new Cidade("", "Coruripe da Cal", "AL"));
        lista.add(new Cidade("", "Craíbas", "AL"));
        lista.add(new Cidade("", "Delmiro Gouveia", "AL"));
        lista.add(new Cidade("", "Dois Riachos", "AL"));
        lista.add(new Cidade("", "Entremontes", "AL"));
        lista.add(new Cidade("", "Estrela de Alagoas", "AL"));
        lista.add(new Cidade("", "Farrinheira", "AL"));
        lista.add(new Cidade("", "Feira Grande", "AL"));
        lista.add(new Cidade("", "Feliz Deserto", "AL"));
        lista.add(new Cidade("", "Flexeiras", "AL"));
        lista.add(new Cidade("", "Gaspar", "AL"));
        lista.add(new Cidade("", "Girau do Ponciano", "AL"));
        lista.add(new Cidade("", "Ibateguara", "AL"));
        lista.add(new Cidade("", "Igaci", "AL"));
        lista.add(new Cidade("", "Igreja Nova", "AL"));
        lista.add(new Cidade("", "Ingá", "AL"));
        lista.add(new Cidade("", "Inhapi", "AL"));
        lista.add(new Cidade("", "Jacaré dos Homens", "AL"));
        lista.add(new Cidade("", "Jacuípe", "AL"));
        lista.add(new Cidade("", "Japaratinga", "AL"));
        lista.add(new Cidade("", "Jaramataia", "AL"));
        lista.add(new Cidade("", "Jenipapo", "AL"));
        lista.add(new Cidade("", "Jequiá da Praia", "AL"));
        lista.add(new Cidade("", "Joaquim Gomes", "AL"));
        lista.add(new Cidade("", "Jundiá", "AL"));
        lista.add(new Cidade("", "Junqueiro", "AL"));
        lista.add(new Cidade("", "Lagoa da Areia", "AL"));
        lista.add(new Cidade("", "Lagoa da Canoa", "AL"));
        lista.add(new Cidade("", "Lagoa da Pedra", "AL"));
        lista.add(new Cidade("", "Lagoa Dantas", "AL"));
        lista.add(new Cidade("", "Lagoa do Caldeirão", "AL"));
        lista.add(new Cidade("", "Lagoa do Canto", "AL"));
        lista.add(new Cidade("", "Lagoa do Exú", "AL"));
        lista.add(new Cidade("", "Lagoa do Pau", "AL"));
        lista.add(new Cidade("", "Lagoa do Rancho", "AL"));
        lista.add(new Cidade("", "Lagoa Grande", "AL"));
        lista.add(new Cidade("", "Lajes do Caldeirão", "AL"));
        lista.add(new Cidade("", "Laranjal", "AL"));
        lista.add(new Cidade("", "Limoeiro de Anadia", "AL"));
        lista.add(new Cidade("", "Luziápolis", "AL"));
        lista.add(new Cidade("", "Maceió", "AL"));
        lista.add(new Cidade("", "Major Isidoro", "AL"));
        lista.add(new Cidade("", "Mar Vermelho", "AL"));
        lista.add(new Cidade("", "Maragogi", "AL"));
        lista.add(new Cidade("", "Maravilha", "AL"));
        lista.add(new Cidade("", "Marechal Deodoro", "AL"));
        lista.add(new Cidade("", "Maribondo", "AL"));
        lista.add(new Cidade("", "Massaranduba", "AL"));
        lista.add(new Cidade("", "Mata Grande", "AL"));
        lista.add(new Cidade("", "Mata Limpa", "AL"));
        lista.add(new Cidade("", "Matriz de Camaragibe", "AL"));
        lista.add(new Cidade("", "Messias", "AL"));
        lista.add(new Cidade("", "Miaí de Baixo", "AL"));
        lista.add(new Cidade("", "Miaí de Cima", "AL"));
        lista.add(new Cidade("", "Minador do Negrão", "AL"));
        lista.add(new Cidade("", "Monteirópolis", "AL"));
        lista.add(new Cidade("", "Moreira", "AL"));
        lista.add(new Cidade("", "Munguba", "AL"));
        lista.add(new Cidade("", "Murici", "AL"));
        lista.add(new Cidade("", "Novo Lino", "AL"));
        lista.add(new Cidade("", "Olho D'Água das Flores", "AL"));
        lista.add(new Cidade("", "Olho D'Água do Casado", "AL"));
        lista.add(new Cidade("", "Olho D'Água dos Dandanhas", "AL"));
        lista.add(new Cidade("", "Olho D'Água Grande", "AL"));
        lista.add(new Cidade("", "Olivença", "AL"));
        lista.add(new Cidade("", "Ouro Branco", "AL"));
        lista.add(new Cidade("", "Palestina", "AL"));
        lista.add(new Cidade("", "Palmeira de Fora", "AL"));
        lista.add(new Cidade("", "Palmeira dos Índios", "AL"));
        lista.add(new Cidade("", "Pão de Açúcar", "AL"));
        lista.add(new Cidade("", "Pariconha", "AL"));
        lista.add(new Cidade("", "Paripueira", "AL"));
        lista.add(new Cidade("", "Passo de Camaragibe", "AL"));
        lista.add(new Cidade("", "Pau D'Arco", "AL"));
        lista.add(new Cidade("", "Pau Ferro", "AL"));
        lista.add(new Cidade("", "Paulo Jacinto", "AL"));
        lista.add(new Cidade("", "Penedo", "AL"));
        lista.add(new Cidade("", "Peroba", "AL"));
        lista.add(new Cidade("", "Piaçabuçu", "AL"));
        lista.add(new Cidade("", "Pilar", "AL"));
        lista.add(new Cidade("", "Pindoba", "AL"));
        lista.add(new Cidade("", "Piranhas", "AL"));
        lista.add(new Cidade("", "Poço", "AL"));
        lista.add(new Cidade("", "Poço da Pedra de Cima", "AL"));
        lista.add(new Cidade("", "Poço das Trincheiras", "AL"));
        lista.add(new Cidade("", "Pontal de Coruripe", "AL"));
        lista.add(new Cidade("", "Porto Calvo", "AL"));
        lista.add(new Cidade("", "Porto de Pedras", "AL"));
        lista.add(new Cidade("", "Porto Real do Colégio", "AL"));
        lista.add(new Cidade("", "Poxim", "AL"));
        lista.add(new Cidade("", "Quati", "AL"));
        lista.add(new Cidade("", "Quebrangulo", "AL"));
        lista.add(new Cidade("", "Retiro", "AL"));
        lista.add(new Cidade("", "Riachão", "AL"));
        lista.add(new Cidade("", "Riacho do Sertão", "AL"));
        lista.add(new Cidade("", "Riacho Fundo de Cima", "AL"));
        lista.add(new Cidade("", "Rio dos Bichos", "AL"));
        lista.add(new Cidade("", "Rio Largo", "AL"));
        lista.add(new Cidade("", "Rocha Cavalcante", "AL"));
        lista.add(new Cidade("", "Roteiro", "AL"));
        lista.add(new Cidade("", "Santa Efigênia", "AL"));
        lista.add(new Cidade("", "Santa Luzia do Norte", "AL"));
        lista.add(new Cidade("", "Santa Terezinha", "AL"));
        lista.add(new Cidade("", "Santana do Ipanema", "AL"));
        lista.add(new Cidade("", "Santana do Mundaú", "AL"));
        lista.add(new Cidade("", "Santo Antônio", "AL"));
        lista.add(new Cidade("", "São Brás", "AL"));
        lista.add(new Cidade("", "São José da Laje", "AL"));
        lista.add(new Cidade("", "São José da Tapera", "AL"));
        lista.add(new Cidade("", "São Lourenço", "AL"));
        lista.add(new Cidade("", "São Luís do Quitunde", "AL"));
        lista.add(new Cidade("", "São Miguel dos Campos", "AL"));
        lista.add(new Cidade("", "São Miguel dos Milagres", "AL"));
        lista.add(new Cidade("", "São Sebastião", "AL"));
        lista.add(new Cidade("", "Sapucaia", "AL"));
        lista.add(new Cidade("", "Satuba", "AL"));
        lista.add(new Cidade("", "Senador Rui Palmeira", "AL"));
        lista.add(new Cidade("", "Serra da Mandioca", "AL"));
        lista.add(new Cidade("", "Serra da Massa", "AL"));
        lista.add(new Cidade("", "Serra do São José", "AL"));
        lista.add(new Cidade("", "Tabocas", "AL"));
        lista.add(new Cidade("", "Taboleiro do Pinto", "AL"));
        lista.add(new Cidade("", "Tanque D'Arca", "AL"));
        lista.add(new Cidade("", "Taquara", "AL"));
        lista.add(new Cidade("", "Taquarana", "AL"));
        lista.add(new Cidade("", "Tatuamunha", "AL"));
        lista.add(new Cidade("", "Teotônio Vilela", "AL"));
        lista.add(new Cidade("", "Traipu", "AL"));
        lista.add(new Cidade("", "União dos Palmares", "AL"));
        lista.add(new Cidade("", "Usina Camaçari", "AL"));
        lista.add(new Cidade("", "Viçosa", "AL"));
        lista.add(new Cidade("", "Vila Aparecida", "AL"));
        lista.add(new Cidade("", "Vila São Francisco", "AL"));
        return lista;
    }
}
