package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class AL {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("InqpAHHY9lx20TMWOPQQ","Água Branca","AL"));
        lista.add(new Cidade("8MkjLhgz2VD5IhQpK3lw","Alazão","AL"));
        lista.add(new Cidade("OVduw8tPcCNthLBxyLHT","Alecrim","AL"));
        lista.add(new Cidade("piwH5mnkrT1GCo8uaaKs","Anadia","AL"));
        lista.add(new Cidade("QhbR5MeFfLSMifGhY231","Anel","AL"));
        lista.add(new Cidade("JGBzGUBOsYnmfxCPslAb","Anum Novo","AL"));
        lista.add(new Cidade("TTVwgtteXt5ItJ0vd7E7","Anum Velho","AL"));
        lista.add(new Cidade("zb7xnE3MVXjtn75U93NF","Arapiraca","AL"));
        lista.add(new Cidade("O9krIRbtEFZyNHj4Zmbv","Atalaia","AL"));
        lista.add(new Cidade("4Kgso5t1Wk2fgsG1AU2G","Baixa da Onça","AL"));
        lista.add(new Cidade("80TCv5NErXk63qCgAkXP","Baixa Grande","AL"));
        lista.add(new Cidade("JdgWig1MqDgq8x5T3b3R","Bananeiras","AL"));
        lista.add(new Cidade("qSwVl25zyAQyQmmKDjh0","Barra de Santo Antônio","AL"));
        lista.add(new Cidade("o1fi9IVyFLmmM3HeOynH","Barra de São Miguel","AL"));
        lista.add(new Cidade("NnMy3S2qYGtWUnKjwrnS","Barra do Bonifácio","AL"));
        lista.add(new Cidade("XPdkKJiqBDHpytndb71x","Barra Grande","AL"));
        lista.add(new Cidade("Ptn8fU0ga4pb7EbuU5Sa","Barreiras","AL"));
        lista.add(new Cidade("vBMw54mQPd80pITIPmbF","Barro Vermelho","AL"));
        lista.add(new Cidade("UKAp5IW0BkNfQw41vbkL","Batalha","AL"));
        lista.add(new Cidade("Y6BqqkOlJaJVrPFtRwGC","Batingas","AL"));
        lista.add(new Cidade("gBT1hnAWGCvv5ahZT4Jv","Belém","AL"));
        lista.add(new Cidade("ZPjLrUsezKgq6GX47Mry","Belo Monte","AL"));
        lista.add(new Cidade("L3TymKvIyMTc9yaRFgJi","Boa Sorte","AL"));
        lista.add(new Cidade("bMdZAYwmmiduJiNC5QzQ","Boa Vista","AL"));
        lista.add(new Cidade("y7HGv2WubtrNNZDThVKP","Boca da Mata","AL"));
        lista.add(new Cidade("CfQia37ScVNVRJ7gnBkt","Bom Jardim","AL"));
        lista.add(new Cidade("Gf0vHJqwUrboRKVXs8to","Bonifácio","AL"));
        lista.add(new Cidade("uueUoifetWiaWVi4OdaZ","Bonsucesso","AL"));
        lista.add(new Cidade("IgvLBi78QBmSU5T4r3Xi","Boqueirão","AL"));
        lista.add(new Cidade("j4R8gLX4mb7fAHrkDdqR","Botafogo","AL"));
        lista.add(new Cidade("WPRIaLopXmLfHU06X599","Branquinha","AL"));
        lista.add(new Cidade("CMHjmCU4AgHVGyeK1mjk","Cacimbinhas","AL"));
        lista.add(new Cidade("tHinGFtuOh0sERBh3jsu","Cajueiro","AL"));
        lista.add(new Cidade("WSm5vgTpNo9iiwOWAE3X","Caldeirões de Cima","AL"));
        lista.add(new Cidade("oP1J1yf2teHmq0iFF2MI","Camadanta","AL"));
        lista.add(new Cidade("qU15PfsBaqAYkuCddAWh","Campestre","AL"));
        lista.add(new Cidade("JRpR9DAwJ0U1DjfKRw0U","Campo Alegre","AL"));
        lista.add(new Cidade("EFe9LEDOOS3qXnvephgh","Campo Grande","AL"));
        lista.add(new Cidade("hmamQLqo5lUHFYaPCYw0","Cana Brava","AL"));
        lista.add(new Cidade("MFMUKeCiZdR0sigt8cLT","Canafístula","AL"));
        lista.add(new Cidade("uzFbHqX5OF25j40ueA6d","Canapi","AL"));
        lista.add(new Cidade("Pp3iw68IBAa0BITCl3Q7","Canastra","AL"));
        lista.add(new Cidade("qMSzhPInIhqtdxAeks3K","Capela","AL"));
        lista.add(new Cidade("527YLsfW061kXAqGC52b","Carneiros","AL"));
        lista.add(new Cidade("yROs76ZlDUmDs5RxNda5","Carrasco","AL"));
        lista.add(new Cidade("WOmbn37804u8NCeydBFj","Chã Preta","AL"));
        lista.add(new Cidade("4hfTepHo5uh02y67pSn2","Coité do Nóia","AL"));
        lista.add(new Cidade("byLdSeRGwwaxuJwx7Oxo","Colônia Leopoldina","AL"));
        lista.add(new Cidade("IJ3Fxps59PS7d1q52k1r","Colônia Pindorama","AL"));
        lista.add(new Cidade("Uit0Om9fmo2v2GP6DmnT","Coqueiro Seco","AL"));
        lista.add(new Cidade("Aq3n0fxnQ0D1qkro1IBW","Coruripe","AL"));
        lista.add(new Cidade("NiXukFb2uoTLoeGQeVqa","Coruripe da Cal","AL"));
        lista.add(new Cidade("VSAk7HSg87PWlF6kCadz","Craíbas","AL"));
        lista.add(new Cidade("5hgA2Tufr760aZf0zIjb","Delmiro Gouveia","AL"));
        lista.add(new Cidade("0Y572JZ8fmXCJKPDx84L","Dois Riachos","AL"));
        lista.add(new Cidade("CCSwpAxpJuoHeVn3O4vD","Entremontes","AL"));
        lista.add(new Cidade("ejDzeyi1I0YwFDnhhnXm","Estrela de Alagoas","AL"));
        lista.add(new Cidade("pRNvZKU4mpNP2ABY2WiT","Farrinheira","AL"));
        lista.add(new Cidade("T1wJjpdPeZvDRIogBJDP","Feira Grande","AL"));
        lista.add(new Cidade("a4pse5hdTlKbSJsDWfaR","Feliz Deserto","AL"));
        lista.add(new Cidade("xKdCBEjA5Wk591ilDKYq","Flexeiras","AL"));
        lista.add(new Cidade("AHovsfHFvjfemrL22Ywe","Gaspar","AL"));
        lista.add(new Cidade("DKfi4LjzyXuKthfu4vPJ","Girau do Ponciano","AL"));
        lista.add(new Cidade("2QnYMExFUv2hoDWYV6SN","Ibateguara","AL"));
        lista.add(new Cidade("MlPmBOnVAh8TLvQ4ZUxm","Igaci","AL"));
        lista.add(new Cidade("qnYG85AtJBfgcT6sabFD","Igreja Nova","AL"));
        lista.add(new Cidade("MJofEKmRQWXzMd77yIWP","Ingá","AL"));
        lista.add(new Cidade("3sRyHj9FrtExFtdWtCrd","Inhapi","AL"));
        lista.add(new Cidade("xyR6tYnt50UDtu3lgFKa","Jacaré dos Homens","AL"));
        lista.add(new Cidade("KEgT8vN4ynZn9W6nZzia","Jacuípe","AL"));
        lista.add(new Cidade("OoqtJWfUNnTGzN5eQnhd","Japaratinga","AL"));
        lista.add(new Cidade("zemYFVdgApSD0KkosCox","Jaramataia","AL"));
        lista.add(new Cidade("PXqPwdoT5krU4xd361J8","Jenipapo","AL"));
        lista.add(new Cidade("26Cbyw9qfPeyqU1NZ5sa","Jequiá da Praia","AL"));
        lista.add(new Cidade("I2xxXEdqjFdG3pRg12cJ","Joaquim Gomes","AL"));
        lista.add(new Cidade("ejzdhO1QkOzex7a42s3W","Jundiá","AL"));
        lista.add(new Cidade("5F4y9pM80qN69IBbOD83","Junqueiro","AL"));
        lista.add(new Cidade("DiAaTY0aVrzU35ICetvx","Lagoa da Areia","AL"));
        lista.add(new Cidade("6oLBqgYHcBQYsMb0SXlh","Lagoa da Canoa","AL"));
        lista.add(new Cidade("JKrAaN88O8Yh2DiEqh6E","Lagoa da Pedra","AL"));
        lista.add(new Cidade("jZJztlD3RIlHSTfJ5s00","Lagoa Dantas","AL"));
        lista.add(new Cidade("VOZypfaldwMiP5uXCe3C","Lagoa do Caldeirão","AL"));
        lista.add(new Cidade("x50THJW5u30P9y4mgYgK","Lagoa do Canto","AL"));
        lista.add(new Cidade("uNZyrkGWf6tZN2KxiZrp","Lagoa do Exú","AL"));
        lista.add(new Cidade("6QdLgKvrUak4BFQDVPLC","Lagoa do Pau","AL"));
        lista.add(new Cidade("LbW3snJfAT30FT03tAnl","Lagoa do Rancho","AL"));
        lista.add(new Cidade("5FXQPPR117yiumu3fao3","Lagoa Grande","AL"));
        lista.add(new Cidade("BqmTqAl7oeQPWKZMOmYF","Lajes do Caldeirão","AL"));
        lista.add(new Cidade("zjTkpNX9vTyqZ5k9FNcj","Laranjal","AL"));
        lista.add(new Cidade("Ke3p7Joe8FssXRKCmuG0","Limoeiro de Anadia","AL"));
        lista.add(new Cidade("FxaGEB12RzItdL5f4qjQ","Luziápolis","AL"));
        lista.add(new Cidade("xm00CgghmTWlob15eppP","Maceió","AL"));
        lista.add(new Cidade("YOFJEtk2I7PAh0KgIuRp","Major Isidoro","AL"));
        lista.add(new Cidade("jAy5dAietj0Uw4xanNzl","Mar Vermelho","AL"));
        lista.add(new Cidade("lQ2lWmeRbdagWoS6Belv","Maragogi","AL"));
        lista.add(new Cidade("ParQwtnP0kh8lPYxuHXu","Maravilha","AL"));
        lista.add(new Cidade("sZ0rYDksk0dkIWegUNSG","Marechal Deodoro","AL"));
        lista.add(new Cidade("d8g2xZY6DYAh0pRkni5d","Maribondo","AL"));
        lista.add(new Cidade("qaasGNeSIj4jyGIsMcI3","Massaranduba","AL"));
        lista.add(new Cidade("RrDAmD1DPOcsCEG9H3Wp","Mata Grande","AL"));
        lista.add(new Cidade("hxjSV0uLxq9OQxXRqiwn","Mata Limpa","AL"));
        lista.add(new Cidade("oQ8r2S6jnsSuIRxrg6UM","Matriz de Camaragibe","AL"));
        lista.add(new Cidade("JV7yaxTP55hDI1105qyF","Messias","AL"));
        lista.add(new Cidade("UBngBtLNF9fnl5SfjMzm","Miaí de Baixo","AL"));
        lista.add(new Cidade("oXKIzlt2CcPxsm5hud6N","Miaí de Cima","AL"));
        lista.add(new Cidade("QmeAknnPWVjKuNZFfNXo","Minador do Negrão","AL"));
        lista.add(new Cidade("RhFBKUsUGCAlplTQklTS","Monteirópolis","AL"));
        lista.add(new Cidade("9wm4p7aHbw7bsjiFumiI","Moreira","AL"));
        lista.add(new Cidade("TYk48bFcuRe4Xq3rhMz1","Munguba","AL"));
        lista.add(new Cidade("KS4aaSA8bV7nHBcZPBmP","Murici","AL"));
        lista.add(new Cidade("qlGKiimS708Yks1RnP7P","Novo Lino","AL"));
        lista.add(new Cidade("PWbYl7uVOWDo5hk5nbOJ","Olho D'Água das Flores","AL"));
        lista.add(new Cidade("IPogeggE7hgp1bmcfsZO","Olho D'Água do Casado","AL"));
        lista.add(new Cidade("OlpV3EEf8Eh5boR1rXWU","Olho D'Água dos Dandanhas","AL"));
        lista.add(new Cidade("W0mSt1INa0XitN2SNsmE","Olho D'Água Grande","AL"));
        lista.add(new Cidade("0nKHblHnttLXk7UFHlB0","Olivença","AL"));
        lista.add(new Cidade("gs7Z4UWQfjxok3C5XjHg","Ouro Branco","AL"));
        lista.add(new Cidade("zUwtkK87j9qsM0RQwPe7","Palestina","AL"));
        lista.add(new Cidade("GzeboIrACn8drhSusNde","Palmeira de Fora","AL"));
        lista.add(new Cidade("AyHfEM95DFpvYo7Iw8WV","Palmeira dos Índios","AL"));
        lista.add(new Cidade("OQoMf0jvYDWGhURa9gs0","Pão de Açúcar","AL"));
        lista.add(new Cidade("Ev7kat0puFlfVRDtp4jx","Pariconha","AL"));
        lista.add(new Cidade("hkIlxSJykKJK649jxUyR","Paripueira","AL"));
        lista.add(new Cidade("QjAay4Nzx5ZVOo8rHKNA","Passo de Camaragibe","AL"));
        lista.add(new Cidade("kJmN7KyFsbHsjHovpyvO","Pau D'Arco","AL"));
        lista.add(new Cidade("hrcbWPXRDSn2o5PHdi85","Pau Ferro","AL"));
        lista.add(new Cidade("yIf489EGrh07htcwZNqC","Paulo Jacinto","AL"));
        lista.add(new Cidade("lByCF25XoHBhilUkREXQ","Penedo","AL"));
        lista.add(new Cidade("6tIINFURIkiAXFlKQ8kx","Peroba","AL"));
        lista.add(new Cidade("yekA5U4kBL5uvqjX1WCk","Piaçabuçu","AL"));
        lista.add(new Cidade("qEk72529gBQdxEQPUS76","Pilar","AL"));
        lista.add(new Cidade("rv4OS8AORcVCOumFvD8F","Pindoba","AL"));
        lista.add(new Cidade("67s0z2L46Jnw10hMOIlP","Piranhas","AL"));
        lista.add(new Cidade("9gWmO4bgycLswxpGX7EU","Poço","AL"));
        lista.add(new Cidade("TNK82XPeOcSd1TPaag51","Poço da Pedra de Cima","AL"));
        lista.add(new Cidade("ALaDhzfdY1HoGsWd4qcE","Poço das Trincheiras","AL"));
        lista.add(new Cidade("pAyHR9jr1Qq25sg3xJy3","Pontal de Coruripe","AL"));
        lista.add(new Cidade("yMjYp07ogXdCuoy5xpqG","Porto Calvo","AL"));
        lista.add(new Cidade("UhHGNuPdtkRnSallRyRB","Porto de Pedras","AL"));
        lista.add(new Cidade("MslOUMqhYuGBULNZCoi2","Porto Real do Colégio","AL"));
        lista.add(new Cidade("LDWNM2ZeOAFI7ule0pMv","Poxim","AL"));
        lista.add(new Cidade("CbiHukY16Tlck6XVz4eI","Quati","AL"));
        lista.add(new Cidade("xCxDbXwg7xNr81RPCQGG","Quebrangulo","AL"));
        lista.add(new Cidade("aqS1kkcM9PwZ8wveSPbO","Retiro","AL"));
        lista.add(new Cidade("cW8qTfySsN2aQvEUPPxe","Riachão","AL"));
        lista.add(new Cidade("lYlYDYw8KP7xnCXYRODk","Riacho do Sertão","AL"));
        lista.add(new Cidade("76wIHXsF6BwDxa2KDc4h","Riacho Fundo de Cima","AL"));
        lista.add(new Cidade("rEpMO3Ec7WKGMiWnQ8Lm","Rio dos Bichos","AL"));
        lista.add(new Cidade("K3XeNyWV1xhZRYbRsZcS","Rio Largo","AL"));
        lista.add(new Cidade("WyGRy5JxZqdfiTgndbZo","Rocha Cavalcante","AL"));
        lista.add(new Cidade("MxbLAzPp7TduK1itveUO","Roteiro","AL"));
        lista.add(new Cidade("lRgXT0tq1vYVjEgD21U6","Santa Efigênia","AL"));
        lista.add(new Cidade("d1FbHFLRe1fimLJhedqE","Santa Luzia do Norte","AL"));
        lista.add(new Cidade("bVor3rEsqfOfApDRVLXP","Santa Terezinha","AL"));
        lista.add(new Cidade("xDGtolBcwN9nXMhf3HEu","Santana do Ipanema","AL"));
        lista.add(new Cidade("EgePlaCwCniAqg8cRljK","Santana do Mundaú","AL"));
        lista.add(new Cidade("W559VuaSbA8d58dZED6G","Santo Antônio","AL"));
        lista.add(new Cidade("tRVXe9LXbeLSrjcxVkJt","São Brás","AL"));
        lista.add(new Cidade("jXYpZ5ZXDOvU1E9tx1Dv","São José da Laje","AL"));
        lista.add(new Cidade("ZtPRNCKlvme8kaN66k5s","São José da Tapera","AL"));
        lista.add(new Cidade("NKvMSROBvlLcPnG5I8eV","São Lourenço","AL"));
        lista.add(new Cidade("tQpvhbzHLnhNTRxQpMo5","São Luís do Quitunde","AL"));
        lista.add(new Cidade("HkYy8XZRtPzacFQrD1y3","São Miguel dos Campos","AL"));
        lista.add(new Cidade("q85GIBUX9TQgo4kmNnKA","São Miguel dos Milagres","AL"));
        lista.add(new Cidade("gn7eSEJcYCZCZt4Gn7if","São Sebastião","AL"));
        lista.add(new Cidade("CilzT23Guy90w7Q3ixju","Sapucaia","AL"));
        lista.add(new Cidade("1LpkiXF4nzvQ9hXyzAG0","Satuba","AL"));
        lista.add(new Cidade("TxZeNler8GdhtLgVikva","Senador Rui Palmeira","AL"));
        lista.add(new Cidade("xucSswLfAUFwaOD95KIa","Serra da Mandioca","AL"));
        lista.add(new Cidade("LV46FoSxsz2XYVYudgAH","Serra da Massa","AL"));
        lista.add(new Cidade("Uq9ReWDJTxVdlziUTkGF","Serra do São José","AL"));
        lista.add(new Cidade("Azou7qLTP022mWoF0lUd","Tabocas","AL"));
        lista.add(new Cidade("fxh3aBnKyU9fYzDZCLTe","Taboleiro do Pinto","AL"));
        lista.add(new Cidade("aiDikL0gGGBirVaQ6fr8","Tanque D'Arca","AL"));
        lista.add(new Cidade("6WtEajx7qxOpJ9eXsdWX","Taquara","AL"));
        lista.add(new Cidade("itAWy75yMrzFaKSQWQyV","Taquarana","AL"));
        lista.add(new Cidade("NgF26q8Q1gdKpuHWZCWd","Tatuamunha","AL"));
        lista.add(new Cidade("vyom58NhhEf2eUppFNTO","Teotônio Vilela","AL"));
        lista.add(new Cidade("VK5Lqr7rh2jXvK9HAmgY","Traipu","AL"));
        lista.add(new Cidade("ClwKZNm3YmSwnpOjnNHq","União dos Palmares","AL"));
        lista.add(new Cidade("LHKDYfOPiSZZFOAAVPQR","Usina Camaçari","AL"));
        lista.add(new Cidade("ZAuylylk7I9yZVDYPkLn","Viçosa","AL"));
        lista.add(new Cidade("JZv6ZEkzX0UwQBRddNUs","Vila Aparecida","AL"));
        lista.add(new Cidade("vdQ1PR0Cbv2XMNJhNzej","Vila São Francisco","AL"));
        return lista;
    }
}
