package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;

import br.ufms.nafmanager.model.Cidade;

public class AL {
    public static ArrayList<Cidade> getCidades() {
        ArrayList<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("InqpAHHY9lx20TMWOPQQ","Água Branca","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("8MkjLhgz2VD5IhQpK3lw","Alazão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("OVduw8tPcCNthLBxyLHT","Alecrim","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("piwH5mnkrT1GCo8uaaKs","Anadia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("QhbR5MeFfLSMifGhY231","Anel","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("JGBzGUBOsYnmfxCPslAb","Anum Novo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("TTVwgtteXt5ItJ0vd7E7","Anum Velho","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("zb7xnE3MVXjtn75U93NF","Arapiraca","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("O9krIRbtEFZyNHj4Zmbv","Atalaia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("4Kgso5t1Wk2fgsG1AU2G","Baixa da Onça","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("80TCv5NErXk63qCgAkXP","Baixa Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("JdgWig1MqDgq8x5T3b3R","Bananeiras","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qSwVl25zyAQyQmmKDjh0","Barra de Santo Antônio","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("o1fi9IVyFLmmM3HeOynH","Barra de São Miguel","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("NnMy3S2qYGtWUnKjwrnS","Barra do Bonifácio","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("XPdkKJiqBDHpytndb71x","Barra Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Ptn8fU0ga4pb7EbuU5Sa","Barreiras","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("vBMw54mQPd80pITIPmbF","Barro Vermelho","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("UKAp5IW0BkNfQw41vbkL","Batalha","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Y6BqqkOlJaJVrPFtRwGC","Batingas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("gBT1hnAWGCvv5ahZT4Jv","Belém","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ZPjLrUsezKgq6GX47Mry","Belo Monte","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("L3TymKvIyMTc9yaRFgJi","Boa Sorte","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("bMdZAYwmmiduJiNC5QzQ","Boa Vista","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("y7HGv2WubtrNNZDThVKP","Boca da Mata","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("CfQia37ScVNVRJ7gnBkt","Bom Jardim","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Gf0vHJqwUrboRKVXs8to","Bonifácio","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("uueUoifetWiaWVi4OdaZ","Bonsucesso","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("IgvLBi78QBmSU5T4r3Xi","Boqueirão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("j4R8gLX4mb7fAHrkDdqR","Botafogo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("WPRIaLopXmLfHU06X599","Branquinha","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("CMHjmCU4AgHVGyeK1mjk","Cacimbinhas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("tHinGFtuOh0sERBh3jsu","Cajueiro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("WSm5vgTpNo9iiwOWAE3X","Caldeirões de Cima","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("oP1J1yf2teHmq0iFF2MI","Camadanta","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qU15PfsBaqAYkuCddAWh","Campestre","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("JRpR9DAwJ0U1DjfKRw0U","Campo Alegre","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("EFe9LEDOOS3qXnvephgh","Campo Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("hmamQLqo5lUHFYaPCYw0","Cana Brava","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("MFMUKeCiZdR0sigt8cLT","Canafístula","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("uzFbHqX5OF25j40ueA6d","Canapi","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Pp3iw68IBAa0BITCl3Q7","Canastra","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qMSzhPInIhqtdxAeks3K","Capela","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("527YLsfW061kXAqGC52b","Carneiros","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("yROs76ZlDUmDs5RxNda5","Carrasco","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("WOmbn37804u8NCeydBFj","Chã Preta","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("4hfTepHo5uh02y67pSn2","Coité do Nóia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("byLdSeRGwwaxuJwx7Oxo","Colônia Leopoldina","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("IJ3Fxps59PS7d1q52k1r","Colônia Pindorama","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Uit0Om9fmo2v2GP6DmnT","Coqueiro Seco","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Aq3n0fxnQ0D1qkro1IBW","Coruripe","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("NiXukFb2uoTLoeGQeVqa","Coruripe da Cal","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("VSAk7HSg87PWlF6kCadz","Craíbas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("5hgA2Tufr760aZf0zIjb","Delmiro Gouveia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("0Y572JZ8fmXCJKPDx84L","Dois Riachos","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("CCSwpAxpJuoHeVn3O4vD","Entremontes","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ejDzeyi1I0YwFDnhhnXm","Estrela de Alagoas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("pRNvZKU4mpNP2ABY2WiT","Farrinheira","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("T1wJjpdPeZvDRIogBJDP","Feira Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("a4pse5hdTlKbSJsDWfaR","Feliz Deserto","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("xKdCBEjA5Wk591ilDKYq","Flexeiras","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("AHovsfHFvjfemrL22Ywe","Gaspar","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("DKfi4LjzyXuKthfu4vPJ","Girau do Ponciano","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("2QnYMExFUv2hoDWYV6SN","Ibateguara","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("MlPmBOnVAh8TLvQ4ZUxm","Igaci","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qnYG85AtJBfgcT6sabFD","Igreja Nova","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("MJofEKmRQWXzMd77yIWP","Ingá","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("3sRyHj9FrtExFtdWtCrd","Inhapi","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("xyR6tYnt50UDtu3lgFKa","Jacaré dos Homens","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("KEgT8vN4ynZn9W6nZzia","Jacuípe","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("OoqtJWfUNnTGzN5eQnhd","Japaratinga","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("zemYFVdgApSD0KkosCox","Jaramataia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("PXqPwdoT5krU4xd361J8","Jenipapo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("26Cbyw9qfPeyqU1NZ5sa","Jequiá da Praia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("I2xxXEdqjFdG3pRg12cJ","Joaquim Gomes","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ejzdhO1QkOzex7a42s3W","Jundiá","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("5F4y9pM80qN69IBbOD83","Junqueiro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("DiAaTY0aVrzU35ICetvx","Lagoa da Areia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("6oLBqgYHcBQYsMb0SXlh","Lagoa da Canoa","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("JKrAaN88O8Yh2DiEqh6E","Lagoa da Pedra","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("jZJztlD3RIlHSTfJ5s00","Lagoa Dantas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("VOZypfaldwMiP5uXCe3C","Lagoa do Caldeirão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("x50THJW5u30P9y4mgYgK","Lagoa do Canto","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("uNZyrkGWf6tZN2KxiZrp","Lagoa do Exú","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("6QdLgKvrUak4BFQDVPLC","Lagoa do Pau","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("LbW3snJfAT30FT03tAnl","Lagoa do Rancho","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("5FXQPPR117yiumu3fao3","Lagoa Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("BqmTqAl7oeQPWKZMOmYF","Lajes do Caldeirão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("zjTkpNX9vTyqZ5k9FNcj","Laranjal","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Ke3p7Joe8FssXRKCmuG0","Limoeiro de Anadia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("FxaGEB12RzItdL5f4qjQ","Luziápolis","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("xm00CgghmTWlob15eppP","Maceió","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("YOFJEtk2I7PAh0KgIuRp","Major Isidoro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("jAy5dAietj0Uw4xanNzl","Mar Vermelho","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("lQ2lWmeRbdagWoS6Belv","Maragogi","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ParQwtnP0kh8lPYxuHXu","Maravilha","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("sZ0rYDksk0dkIWegUNSG","Marechal Deodoro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("d8g2xZY6DYAh0pRkni5d","Maribondo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qaasGNeSIj4jyGIsMcI3","Massaranduba","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("RrDAmD1DPOcsCEG9H3Wp","Mata Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("hxjSV0uLxq9OQxXRqiwn","Mata Limpa","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("oQ8r2S6jnsSuIRxrg6UM","Matriz de Camaragibe","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("JV7yaxTP55hDI1105qyF","Messias","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("UBngBtLNF9fnl5SfjMzm","Miaí de Baixo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("oXKIzlt2CcPxsm5hud6N","Miaí de Cima","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("QmeAknnPWVjKuNZFfNXo","Minador do Negrão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("RhFBKUsUGCAlplTQklTS","Monteirópolis","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("9wm4p7aHbw7bsjiFumiI","Moreira","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("TYk48bFcuRe4Xq3rhMz1","Munguba","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("KS4aaSA8bV7nHBcZPBmP","Murici","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qlGKiimS708Yks1RnP7P","Novo Lino","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("PWbYl7uVOWDo5hk5nbOJ","Olho D'Água das Flores","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("IPogeggE7hgp1bmcfsZO","Olho D'Água do Casado","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("OlpV3EEf8Eh5boR1rXWU","Olho D'Água dos Dandanhas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("W0mSt1INa0XitN2SNsmE","Olho D'Água Grande","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("0nKHblHnttLXk7UFHlB0","Olivença","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("gs7Z4UWQfjxok3C5XjHg","Ouro Branco","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("zUwtkK87j9qsM0RQwPe7","Palestina","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("GzeboIrACn8drhSusNde","Palmeira de Fora","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("AyHfEM95DFpvYo7Iw8WV","Palmeira dos Índios","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("OQoMf0jvYDWGhURa9gs0","Pão de Açúcar","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Ev7kat0puFlfVRDtp4jx","Pariconha","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("hkIlxSJykKJK649jxUyR","Paripueira","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("QjAay4Nzx5ZVOo8rHKNA","Passo de Camaragibe","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("kJmN7KyFsbHsjHovpyvO","Pau D'Arco","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("hrcbWPXRDSn2o5PHdi85","Pau Ferro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("yIf489EGrh07htcwZNqC","Paulo Jacinto","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("lByCF25XoHBhilUkREXQ","Penedo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("6tIINFURIkiAXFlKQ8kx","Peroba","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("yekA5U4kBL5uvqjX1WCk","Piaçabuçu","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("qEk72529gBQdxEQPUS76","Pilar","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("rv4OS8AORcVCOumFvD8F","Pindoba","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("67s0z2L46Jnw10hMOIlP","Piranhas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("9gWmO4bgycLswxpGX7EU","Poço","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("TNK82XPeOcSd1TPaag51","Poço da Pedra de Cima","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ALaDhzfdY1HoGsWd4qcE","Poço das Trincheiras","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("pAyHR9jr1Qq25sg3xJy3","Pontal de Coruripe","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("yMjYp07ogXdCuoy5xpqG","Porto Calvo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("UhHGNuPdtkRnSallRyRB","Porto de Pedras","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("MslOUMqhYuGBULNZCoi2","Porto Real do Colégio","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("LDWNM2ZeOAFI7ule0pMv","Poxim","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("CbiHukY16Tlck6XVz4eI","Quati","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("xCxDbXwg7xNr81RPCQGG","Quebrangulo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("aqS1kkcM9PwZ8wveSPbO","Retiro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("cW8qTfySsN2aQvEUPPxe","Riachão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("lYlYDYw8KP7xnCXYRODk","Riacho do Sertão","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("76wIHXsF6BwDxa2KDc4h","Riacho Fundo de Cima","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("rEpMO3Ec7WKGMiWnQ8Lm","Rio dos Bichos","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("K3XeNyWV1xhZRYbRsZcS","Rio Largo","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("WyGRy5JxZqdfiTgndbZo","Rocha Cavalcante","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("MxbLAzPp7TduK1itveUO","Roteiro","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("lRgXT0tq1vYVjEgD21U6","Santa Efigênia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("d1FbHFLRe1fimLJhedqE","Santa Luzia do Norte","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("bVor3rEsqfOfApDRVLXP","Santa Terezinha","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("xDGtolBcwN9nXMhf3HEu","Santana do Ipanema","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("EgePlaCwCniAqg8cRljK","Santana do Mundaú","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("W559VuaSbA8d58dZED6G","Santo Antônio","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("tRVXe9LXbeLSrjcxVkJt","São Brás","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("jXYpZ5ZXDOvU1E9tx1Dv","São José da Laje","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ZtPRNCKlvme8kaN66k5s","São José da Tapera","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("NKvMSROBvlLcPnG5I8eV","São Lourenço","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("tQpvhbzHLnhNTRxQpMo5","São Luís do Quitunde","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("HkYy8XZRtPzacFQrD1y3","São Miguel dos Campos","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("q85GIBUX9TQgo4kmNnKA","São Miguel dos Milagres","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("gn7eSEJcYCZCZt4Gn7if","São Sebastião","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("CilzT23Guy90w7Q3ixju","Sapucaia","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("1LpkiXF4nzvQ9hXyzAG0","Satuba","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("TxZeNler8GdhtLgVikva","Senador Rui Palmeira","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("xucSswLfAUFwaOD95KIa","Serra da Mandioca","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("LV46FoSxsz2XYVYudgAH","Serra da Massa","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Uq9ReWDJTxVdlziUTkGF","Serra do São José","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("Azou7qLTP022mWoF0lUd","Tabocas","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("fxh3aBnKyU9fYzDZCLTe","Taboleiro do Pinto","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("aiDikL0gGGBirVaQ6fr8","Tanque D'Arca","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("6WtEajx7qxOpJ9eXsdWX","Taquara","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("itAWy75yMrzFaKSQWQyV","Taquarana","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("NgF26q8Q1gdKpuHWZCWd","Tatuamunha","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("vyom58NhhEf2eUppFNTO","Teotônio Vilela","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("VK5Lqr7rh2jXvK9HAmgY","Traipu","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ClwKZNm3YmSwnpOjnNHq","União dos Palmares","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("LHKDYfOPiSZZFOAAVPQR","Usina Camaçari","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("ZAuylylk7I9yZVDYPkLn","Viçosa","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("JZv6ZEkzX0UwQBRddNUs","Vila Aparecida","M5R8LCulJcMtwd9jH2T2", "AL"));
        lista.add(new Cidade("vdQ1PR0Cbv2XMNJhNzej","Vila São Francisco","M5R8LCulJcMtwd9jH2T2", "AL"));
        return lista;
    }
}
