package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class AM {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Agrovila São Sebastião do Caburi", "AM"));
        lista.add(new Cidade("", "Alvarães", "AM"));
        lista.add(new Cidade("", "Amatari", "AM"));
        lista.add(new Cidade("", "Amaturá", "AM"));
        lista.add(new Cidade("", "Anamã", "AM"));
        lista.add(new Cidade("", "Anori", "AM"));
        lista.add(new Cidade("", "Apuí", "AM"));
        lista.add(new Cidade("", "Araras", "AM"));
        lista.add(new Cidade("", "Ariaú", "AM"));
        lista.add(new Cidade("", "Atalaia do Norte", "AM"));
        lista.add(new Cidade("", "Augusto Montenegro", "AM"));
        lista.add(new Cidade("", "Autazes", "AM"));
        lista.add(new Cidade("", "Axinim", "AM"));
        lista.add(new Cidade("", "Badajós", "AM"));
        lista.add(new Cidade("", "Balbina", "AM"));
        lista.add(new Cidade("", "Barcelos", "AM"));
        lista.add(new Cidade("", "Barreirinha", "AM"));
        lista.add(new Cidade("", "Belém de Solimões", "AM"));
        lista.add(new Cidade("", "Benjamin Constant", "AM"));
        lista.add(new Cidade("", "Beruri", "AM"));
        lista.add(new Cidade("", "Boa Vista do Ramos", "AM"));
        lista.add(new Cidade("", "Boca do Acre", "AM"));
        lista.add(new Cidade("", "Borba", "AM"));
        lista.add(new Cidade("", "Caapiranga", "AM"));
        lista.add(new Cidade("", "Cacau Pirêra", "AM"));
        lista.add(new Cidade("", "Caiambé", "AM"));
        lista.add(new Cidade("", "Cametá", "AM"));
        lista.add(new Cidade("", "Campinas", "AM"));
        lista.add(new Cidade("", "Canumã", "AM"));
        lista.add(new Cidade("", "Canutama", "AM"));
        lista.add(new Cidade("", "Carauari", "AM"));
        lista.add(new Cidade("", "Careiro", "AM"));
        lista.add(new Cidade("", "Careiro da Várzea", "AM"));
        lista.add(new Cidade("", "Careiro Parauá", "AM"));
        lista.add(new Cidade("", "Carvoeiro", "AM"));
        lista.add(new Cidade("", "Caviana", "AM"));
        lista.add(new Cidade("", "Coari", "AM"));
        lista.add(new Cidade("", "Codajás", "AM"));
        lista.add(new Cidade("", "Cucuí", "AM"));
        lista.add(new Cidade("", "Eirunepé", "AM"));
        lista.add(new Cidade("", "Envira", "AM"));
        lista.add(new Cidade("", "Estirão do Equador", "AM"));
        lista.add(new Cidade("", "Feijoal", "AM"));
        lista.add(new Cidade("", "Floriano Peixoto", "AM"));
        lista.add(new Cidade("", "Fonte Boa", "AM"));
        lista.add(new Cidade("", "Freguesia do Andirá", "AM"));
        lista.add(new Cidade("", "Guajará", "AM"));
        lista.add(new Cidade("", "Humaitá", "AM"));
        lista.add(new Cidade("", "Iauaretê", "AM"));
        lista.add(new Cidade("", "Içanã", "AM"));
        lista.add(new Cidade("", "Ipixuna", "AM"));
        lista.add(new Cidade("", "Iranduba", "AM"));
        lista.add(new Cidade("", "Itacoatiara", "AM"));
        lista.add(new Cidade("", "Itamarati", "AM"));
        lista.add(new Cidade("", "Itapeaçu", "AM"));
        lista.add(new Cidade("", "Itapiranga", "AM"));
        lista.add(new Cidade("", "Japurá", "AM"));
        lista.add(new Cidade("", "Juruá", "AM"));
        lista.add(new Cidade("", "Jutaí", "AM"));
        lista.add(new Cidade("", "Lábrea", "AM"));
        lista.add(new Cidade("", "Lago do Jacaré", "AM"));
        lista.add(new Cidade("", "Lago do Limão", "AM"));
        lista.add(new Cidade("", "Lago Preto", "AM"));
        lista.add(new Cidade("", "Limoeiro", "AM"));
        lista.add(new Cidade("", "Manacapuru", "AM"));
        lista.add(new Cidade("", "Manaquiri", "AM"));
        lista.add(new Cidade("", "Manaus", "AM"));
        lista.add(new Cidade("", "Manicoré", "AM"));
        lista.add(new Cidade("", "Maraã", "AM"));
        lista.add(new Cidade("", "Massauari", "AM"));
        lista.add(new Cidade("", "Maués", "AM"));
        lista.add(new Cidade("", "Mocambo", "AM"));
        lista.add(new Cidade("", "Moura", "AM"));
        lista.add(new Cidade("", "Murituba", "AM"));
        lista.add(new Cidade("", "Murutinga", "AM"));
        lista.add(new Cidade("", "Nhamundá", "AM"));
        lista.add(new Cidade("", "Nova Olinda do Norte", "AM"));
        lista.add(new Cidade("", "Novo Airão", "AM"));
        lista.add(new Cidade("", "Novo Aripuanã", "AM"));
        lista.add(new Cidade("", "Novo Céu", "AM"));
        lista.add(new Cidade("", "Novo Remanso", "AM"));
        lista.add(new Cidade("", "Osório da Fonseca", "AM"));
        lista.add(new Cidade("", "Palmeiras", "AM"));
        lista.add(new Cidade("", "Paricatuba", "AM"));
        lista.add(new Cidade("", "Parintins", "AM"));
        lista.add(new Cidade("", "Pauini", "AM"));
        lista.add(new Cidade("", "Pedras", "AM"));
        lista.add(new Cidade("", "Platô do Piquiá", "AM"));
        lista.add(new Cidade("", "Presidente Figueiredo", "AM"));
        lista.add(new Cidade("", "Purupuru", "AM"));
        lista.add(new Cidade("", "Repartimento", "AM"));
        lista.add(new Cidade("", "Repartimento de Tuiué", "AM"));
        lista.add(new Cidade("", "Rio Preto da Eva", "AM"));
        lista.add(new Cidade("", "Sacambu", "AM"));
        lista.add(new Cidade("", "Santa Isabel do Rio Negro", "AM"));
        lista.add(new Cidade("", "Santa Rita", "AM"));
        lista.add(new Cidade("", "Santana", "AM"));
        lista.add(new Cidade("", "Santo Antônio do Içá", "AM"));
        lista.add(new Cidade("", "Santo Antônio do Matupi", "AM"));
        lista.add(new Cidade("", "São Felipe", "AM"));
        lista.add(new Cidade("", "São Gabriel da Cachoeira", "AM"));
        lista.add(new Cidade("", "São Paulo de Olivença", "AM"));
        lista.add(new Cidade("", "São Sebastião do Uatumã", "AM"));
        lista.add(new Cidade("", "Silves", "AM"));
        lista.add(new Cidade("", "Tabatinga", "AM"));
        lista.add(new Cidade("", "Tapauá", "AM"));
        lista.add(new Cidade("", "Tefé", "AM"));
        lista.add(new Cidade("", "Terra Nova", "AM"));
        lista.add(new Cidade("", "Tonantins", "AM"));
        lista.add(new Cidade("", "Tuiué", "AM"));
        lista.add(new Cidade("", "Uarini", "AM"));
        lista.add(new Cidade("", "Urucará", "AM"));
        lista.add(new Cidade("", "Urucurituba", "AM"));
        lista.add(new Cidade("", "Vila Amazônia", "AM"));
        lista.add(new Cidade("", "Vila Bittencourt", "AM"));
        lista.add(new Cidade("", "Vila de Campinas", "AM"));
        lista.add(new Cidade("", "Vila de Sacambu", "AM"));
        lista.add(new Cidade("", "Vila do Lago do Jacaré", "AM"));
        lista.add(new Cidade("", "Vila Lindóia", "AM"));
        lista.add(new Cidade("", "Vila Pitinga", "AM"));
        lista.add(new Cidade("", "Vila Rica de Caviana", "AM"));
        lista.add(new Cidade("", "Vila Zé Açu", "AM"));
        return lista;
    }
}
