package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class AM {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("mHqM8HHgw8i07XfhMRZj","Agrovila São Sebastião do Caburi","AM"));
        lista.add(new Cidade("cHhm1q3WheQFWSmTDCxZ","Alvarães","AM"));
        lista.add(new Cidade("6VnkcV8Tc9fZrU6LDKfI","Amatari","AM"));
        lista.add(new Cidade("ysVkPPIFC1uPP41SsTPq","Amaturá","AM"));
        lista.add(new Cidade("3vvE7BqEzNH6CGgCUUYw","Anamã","AM"));
        lista.add(new Cidade("LMsRMvnkT65vk7aYaNp2","Anori","AM"));
        lista.add(new Cidade("5IaxNNwoE7K9uWRICJWX","Apuí","AM"));
        lista.add(new Cidade("jvfDLGNQhyyQ47hEFiZj","Araras","AM"));
        lista.add(new Cidade("WpONuQE0JKeVVpFy38pz","Ariaú","AM"));
        lista.add(new Cidade("sh6WYyWYY9bhXIkBbZIb","Atalaia do Norte","AM"));
        lista.add(new Cidade("hsPIHFYaHTEtkur5v592","Augusto Montenegro","AM"));
        lista.add(new Cidade("cdTnhKWZ6n8Zf3sv4fUc","Autazes","AM"));
        lista.add(new Cidade("2xzoRlu88AVdDBqOCH4d","Axinim","AM"));
        lista.add(new Cidade("oLgrRNfwm4ax8i0mKcEo","Badajós","AM"));
        lista.add(new Cidade("AIPb3A823NMx97WjtpsB","Balbina","AM"));
        lista.add(new Cidade("RSJKhk5AdPdtIRTqK1nQ","Barcelos","AM"));
        lista.add(new Cidade("W2x31jTHOVqhgRbGoPXE","Barreirinha","AM"));
        lista.add(new Cidade("2LPmPCdnwuHdsf3LSoaY","Belém de Solimões","AM"));
        lista.add(new Cidade("Y3wYPmaDcUqSVg3ikCf0","Benjamin Constant","AM"));
        lista.add(new Cidade("tG0EnG6h8deVEpGyN6p8","Beruri","AM"));
        lista.add(new Cidade("6JJHSpHps4uw7wwb69Xy","Boa Vista do Ramos","AM"));
        lista.add(new Cidade("3OvfevSwEh9SjkAlJV8A","Boca do Acre","AM"));
        lista.add(new Cidade("6fRvoL88v8BM1ghQBiJc","Borba","AM"));
        lista.add(new Cidade("I4A1Vs9io3Hf3z8RyIlv","Caapiranga","AM"));
        lista.add(new Cidade("FFetGcV1jKRur6zy0ovY","Cacau Pirêra","AM"));
        lista.add(new Cidade("J0M9kTLiOZB7A7KI67gN","Caiambé","AM"));
        lista.add(new Cidade("ngwmEUqM1wvaemoEilHe","Cametá","AM"));
        lista.add(new Cidade("yXmUICZXS0OWkR51J52V","Campinas","AM"));
        lista.add(new Cidade("djrRkeHArBJcXFUGY4OO","Canumã","AM"));
        lista.add(new Cidade("Xy1f9gdXraKOVZpU3fud","Canutama","AM"));
        lista.add(new Cidade("6GfB0e7kvxQePd29F5mE","Carauari","AM"));
        lista.add(new Cidade("NfAeH7uXm0AapKDTjLVF","Careiro","AM"));
        lista.add(new Cidade("wT5fVS41H9MBb5Aj4FcX","Careiro da Várzea","AM"));
        lista.add(new Cidade("rM9uP0fETHTwC1JFVKjF","Careiro Parauá","AM"));
        lista.add(new Cidade("8sSeYjLSYmafNV1Gwdcw","Carvoeiro","AM"));
        lista.add(new Cidade("p8Ryt5fxacUjrduQXogi","Caviana","AM"));
        lista.add(new Cidade("jFGHM6dSZuTJRr4T5hQx","Coari","AM"));
        lista.add(new Cidade("UfE2L1ldE9IxAcmBfayQ","Codajás","AM"));
        lista.add(new Cidade("zGmuTHPiLpYxgL5i4KdD","Cucuí","AM"));
        lista.add(new Cidade("xMHSNNr09MSNBNXBhVuY","Eirunepé","AM"));
        lista.add(new Cidade("eRToOjjTt14s6KvMY9of","Envira","AM"));
        lista.add(new Cidade("6xchbe0pV0UP1mhMwOzt","Estirão do Equador","AM"));
        lista.add(new Cidade("oP1UfKRd0efF2lREhbY2","Feijoal","AM"));
        lista.add(new Cidade("li05GkLpcr286u72rnWw","Floriano Peixoto","AM"));
        lista.add(new Cidade("WrSPXLlgZMyehgcxYXQL","Fonte Boa","AM"));
        lista.add(new Cidade("8roy5s0HvWoA9gSeZWk5","Freguesia do Andirá","AM"));
        lista.add(new Cidade("35UuUd6n314FOa2nIWYT","Guajará","AM"));
        lista.add(new Cidade("3HrokxhNqBZDGKhxlUxF","Humaitá","AM"));
        lista.add(new Cidade("GoVJ2rNHdNACSVVOVuGw","Iauaretê","AM"));
        lista.add(new Cidade("afHgBSBOGKmfhkwrG6Ng","Içanã","AM"));
        lista.add(new Cidade("TH4ATnkNWaDFTqiUj9WA","Ipixuna","AM"));
        lista.add(new Cidade("iYFy1DKoMPOwwbLvqcaK","Iranduba","AM"));
        lista.add(new Cidade("yI29vtrx9ZdaPSETXyyY","Itacoatiara","AM"));
        lista.add(new Cidade("KWLNLlJyI5gRtoY8Vrr7","Itamarati","AM"));
        lista.add(new Cidade("cuEz23yzKTjpfbZJLiSD","Itapeaçu","AM"));
        lista.add(new Cidade("viEHnItFgZuiKgQCj80o","Itapiranga","AM"));
        lista.add(new Cidade("b4YEx1A0f6lD1KrDxOIo","Japurá","AM"));
        lista.add(new Cidade("qeUQe4jYppspjYR7d2ug","Juruá","AM"));
        lista.add(new Cidade("Q8cqjoUh5qOpSpQgsCB6","Jutaí","AM"));
        lista.add(new Cidade("W9X1NbQmZVKDpDyMFBL6","Lábrea","AM"));
        lista.add(new Cidade("ONRzgFn37Wi9U8kRSRM6","Lago do Jacaré","AM"));
        lista.add(new Cidade("mNLAjRO9YQr5PvLEwAzj","Lago do Limão","AM"));
        lista.add(new Cidade("VEguRAztLckX4AM2US0z","Lago Preto","AM"));
        lista.add(new Cidade("umdyRIM69X2rpGmgBaSB","Limoeiro","AM"));
        lista.add(new Cidade("OqtdsRVnddSd3Vfcm6Nf","Manacapuru","AM"));
        lista.add(new Cidade("j77FMttx6VYxA3conyiU","Manaquiri","AM"));
        lista.add(new Cidade("kQ48hKFWiDb9PS167naF","Manaus","AM"));
        lista.add(new Cidade("6NK9zPETLDi7UmPg4QAP","Manicoré","AM"));
        lista.add(new Cidade("uOEzZF4zLTLXd2igqVji","Maraã","AM"));
        lista.add(new Cidade("gIyfS8Yjlmn7nRCujhpZ","Massauari","AM"));
        lista.add(new Cidade("LGPrRyTXtpTNEHPdEPjr","Maués","AM"));
        lista.add(new Cidade("KNQZWY5GRJV6YtkEUA0M","Mocambo","AM"));
        lista.add(new Cidade("F3DLd7H6bMIEahDWcD6F","Moura","AM"));
        lista.add(new Cidade("1WoPFS0cHfncMhQG1cev","Murituba","AM"));
        lista.add(new Cidade("hxNFNvl8FM8lJpjB1m2d","Murutinga","AM"));
        lista.add(new Cidade("aHqdpdwzEH3EEJrwBY9Q","Nhamundá","AM"));
        lista.add(new Cidade("Lkzocpos8RPtieocO63o","Nova Olinda do Norte","AM"));
        lista.add(new Cidade("7Hvlra1y7jOVJDZX0g5t","Novo Airão","AM"));
        lista.add(new Cidade("hEJIjVo6kMonZxu7VKLr","Novo Aripuanã","AM"));
        lista.add(new Cidade("f1gXQVF0yXmRe4SzcMCy","Novo Céu","AM"));
        lista.add(new Cidade("atvo2kGPrtB78j3rzEQb","Novo Remanso","AM"));
        lista.add(new Cidade("8HVfaJP1DOvD3NYbRUqi","Osório da Fonseca","AM"));
        lista.add(new Cidade("sDOTfpOa2e61EFMFLw4u","Palmeiras","AM"));
        lista.add(new Cidade("9o0xky6hhETPNf5xiSOE","Paricatuba","AM"));
        lista.add(new Cidade("w9JwZYQdQYO0b8JQ8dY6","Parintins","AM"));
        lista.add(new Cidade("gRfyhRGLSfXySsDKPw6W","Pauini","AM"));
        lista.add(new Cidade("BdFPrRgFOi6BrUnYNlDB","Pedras","AM"));
        lista.add(new Cidade("gR8FlvfQxaxw9dZrx0EV","Platô do Piquiá","AM"));
        lista.add(new Cidade("eG42yqiQ2nNE8JSNxWOJ","Presidente Figueiredo","AM"));
        lista.add(new Cidade("IDTdU4rJtC29i0HDxRes","Purupuru","AM"));
        lista.add(new Cidade("1PcasHenFDs6eI897eZL","Repartimento","AM"));
        lista.add(new Cidade("9s4GLvftWij2dK0Du2Je","Repartimento de Tuiué","AM"));
        lista.add(new Cidade("zcZ3AYU5vG48VfTifHIG","Rio Preto da Eva","AM"));
        lista.add(new Cidade("3ggDme0wgX0QKMApdNe4","Sacambu","AM"));
        lista.add(new Cidade("DEfYT7tQObneMyABJNBD","Santa Isabel do Rio Negro","AM"));
        lista.add(new Cidade("zTAAPdwnNwZvsAojmZYJ","Santa Rita","AM"));
        lista.add(new Cidade("HpvfHfDqsDZ6k3k3ZbBt","Santana","AM"));
        lista.add(new Cidade("ycoaJEbSXo2h0Ss0gDUy","Santo Antônio do Içá","AM"));
        lista.add(new Cidade("MuytHP48v2hyUiHEBtWU","Santo Antônio do Matupi","AM"));
        lista.add(new Cidade("efpPWDGT5LaLxJXN7aYN","São Felipe","AM"));
        lista.add(new Cidade("xIU7RDM23LIWS7xGy8Kc","São Gabriel da Cachoeira","AM"));
        lista.add(new Cidade("YMzpWEuPh1aLGXT92inC","São Paulo de Olivença","AM"));
        lista.add(new Cidade("m9Bj6aoUvUfQJFBu01hB","São Sebastião do Uatumã","AM"));
        lista.add(new Cidade("VdZrkeLAGfCfmQ7a0lUI","Silves","AM"));
        lista.add(new Cidade("uC3lkrZCqodriLYDo9Ug","Tabatinga","AM"));
        lista.add(new Cidade("hZJ2ypYyjDFRoukx1bKV","Tapauá","AM"));
        lista.add(new Cidade("Vh3rsNUWhi03CbnFmZAE","Tefé","AM"));
        lista.add(new Cidade("R3G1IkA3xd8f4Ovdlsvj","Terra Nova","AM"));
        lista.add(new Cidade("Guo8EFqNh8rzS6h1nTox","Tonantins","AM"));
        lista.add(new Cidade("oYlsomBpCBPcbOwux9BD","Tuiué","AM"));
        lista.add(new Cidade("rf2vK3Dc6Yjd57oB6JsG","Uarini","AM"));
        lista.add(new Cidade("JfCG7SmS849wDWDqQKLa","Urucará","AM"));
        lista.add(new Cidade("ER7CM348vjL1Z5UslrVw","Urucurituba","AM"));
        lista.add(new Cidade("lGymrRa0aofoe1EY2Xuh","Vila Amazônia","AM"));
        lista.add(new Cidade("w9LQCQbuM9elIe7PpG01","Vila Bittencourt","AM"));
        lista.add(new Cidade("RKr3D82XDhYFII9NWS8d","Vila de Campinas","AM"));
        lista.add(new Cidade("BGju5ZpVq88Rt1MRKxeH","Vila de Sacambu","AM"));
        lista.add(new Cidade("XKSvbig6jq3ijNoDtJ2L","Vila do Lago do Jacaré","AM"));
        lista.add(new Cidade("25uGHMvNh4f1orF90uQm","Vila Lindóia","AM"));
        lista.add(new Cidade("RPBYaWWMsF2zDBu5P3wK","Vila Pitinga","AM"));
        lista.add(new Cidade("B0NUD7qGNsd7fW7hq0p9","Vila Rica de Caviana","AM"));
        lista.add(new Cidade("hfcn28W8YpaqmMhLh7Mb","Vila Zé Açu","AM"));
        return lista;
    }
}
