package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class AM {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("mHqM8HHgw8i07XfhMRZj","Agrovila São Sebastião do Caburi","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("cHhm1q3WheQFWSmTDCxZ","Alvarães","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("6VnkcV8Tc9fZrU6LDKfI","Amatari","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("ysVkPPIFC1uPP41SsTPq","Amaturá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("3vvE7BqEzNH6CGgCUUYw","Anamã","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("LMsRMvnkT65vk7aYaNp2","Anori","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("5IaxNNwoE7K9uWRICJWX","Apuí","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("jvfDLGNQhyyQ47hEFiZj","Araras","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("WpONuQE0JKeVVpFy38pz","Ariaú","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("sh6WYyWYY9bhXIkBbZIb","Atalaia do Norte","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("hsPIHFYaHTEtkur5v592","Augusto Montenegro","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("cdTnhKWZ6n8Zf3sv4fUc","Autazes","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("2xzoRlu88AVdDBqOCH4d","Axinim","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("oLgrRNfwm4ax8i0mKcEo","Badajós","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("AIPb3A823NMx97WjtpsB","Balbina","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("RSJKhk5AdPdtIRTqK1nQ","Barcelos","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("W2x31jTHOVqhgRbGoPXE","Barreirinha","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("2LPmPCdnwuHdsf3LSoaY","Belém de Solimões","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("Y3wYPmaDcUqSVg3ikCf0","Benjamin Constant","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("tG0EnG6h8deVEpGyN6p8","Beruri","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("6JJHSpHps4uw7wwb69Xy","Boa Vista do Ramos","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("3OvfevSwEh9SjkAlJV8A","Boca do Acre","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("6fRvoL88v8BM1ghQBiJc","Borba","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("I4A1Vs9io3Hf3z8RyIlv","Caapiranga","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("FFetGcV1jKRur6zy0ovY","Cacau Pirêra","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("J0M9kTLiOZB7A7KI67gN","Caiambé","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("ngwmEUqM1wvaemoEilHe","Cametá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("yXmUICZXS0OWkR51J52V","Campinas","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("djrRkeHArBJcXFUGY4OO","Canumã","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("Xy1f9gdXraKOVZpU3fud","Canutama","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("6GfB0e7kvxQePd29F5mE","Carauari","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("NfAeH7uXm0AapKDTjLVF","Careiro","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("wT5fVS41H9MBb5Aj4FcX","Careiro da Várzea","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("rM9uP0fETHTwC1JFVKjF","Careiro Parauá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("8sSeYjLSYmafNV1Gwdcw","Carvoeiro","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("p8Ryt5fxacUjrduQXogi","Caviana","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("jFGHM6dSZuTJRr4T5hQx","Coari","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("UfE2L1ldE9IxAcmBfayQ","Codajás","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("zGmuTHPiLpYxgL5i4KdD","Cucuí","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("xMHSNNr09MSNBNXBhVuY","Eirunepé","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("eRToOjjTt14s6KvMY9of","Envira","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("6xchbe0pV0UP1mhMwOzt","Estirão do Equador","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("oP1UfKRd0efF2lREhbY2","Feijoal","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("li05GkLpcr286u72rnWw","Floriano Peixoto","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("WrSPXLlgZMyehgcxYXQL","Fonte Boa","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("8roy5s0HvWoA9gSeZWk5","Freguesia do Andirá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("35UuUd6n314FOa2nIWYT","Guajará","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("3HrokxhNqBZDGKhxlUxF","Humaitá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("GoVJ2rNHdNACSVVOVuGw","Iauaretê","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("afHgBSBOGKmfhkwrG6Ng","Içanã","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("TH4ATnkNWaDFTqiUj9WA","Ipixuna","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("iYFy1DKoMPOwwbLvqcaK","Iranduba","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("yI29vtrx9ZdaPSETXyyY","Itacoatiara","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("KWLNLlJyI5gRtoY8Vrr7","Itamarati","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("cuEz23yzKTjpfbZJLiSD","Itapeaçu","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("viEHnItFgZuiKgQCj80o","Itapiranga","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("b4YEx1A0f6lD1KrDxOIo","Japurá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("qeUQe4jYppspjYR7d2ug","Juruá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("Q8cqjoUh5qOpSpQgsCB6","Jutaí","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("W9X1NbQmZVKDpDyMFBL6","Lábrea","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("ONRzgFn37Wi9U8kRSRM6","Lago do Jacaré","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("mNLAjRO9YQr5PvLEwAzj","Lago do Limão","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("VEguRAztLckX4AM2US0z","Lago Preto","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("umdyRIM69X2rpGmgBaSB","Limoeiro","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("OqtdsRVnddSd3Vfcm6Nf","Manacapuru","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("j77FMttx6VYxA3conyiU","Manaquiri","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("kQ48hKFWiDb9PS167naF","Manaus","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("6NK9zPETLDi7UmPg4QAP","Manicoré","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("uOEzZF4zLTLXd2igqVji","Maraã","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("gIyfS8Yjlmn7nRCujhpZ","Massauari","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("LGPrRyTXtpTNEHPdEPjr","Maués","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("KNQZWY5GRJV6YtkEUA0M","Mocambo","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("F3DLd7H6bMIEahDWcD6F","Moura","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("1WoPFS0cHfncMhQG1cev","Murituba","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("hxNFNvl8FM8lJpjB1m2d","Murutinga","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("aHqdpdwzEH3EEJrwBY9Q","Nhamundá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("Lkzocpos8RPtieocO63o","Nova Olinda do Norte","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("7Hvlra1y7jOVJDZX0g5t","Novo Airão","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("hEJIjVo6kMonZxu7VKLr","Novo Aripuanã","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("f1gXQVF0yXmRe4SzcMCy","Novo Céu","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("atvo2kGPrtB78j3rzEQb","Novo Remanso","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("8HVfaJP1DOvD3NYbRUqi","Osório da Fonseca","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("sDOTfpOa2e61EFMFLw4u","Palmeiras","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("9o0xky6hhETPNf5xiSOE","Paricatuba","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("w9JwZYQdQYO0b8JQ8dY6","Parintins","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("gRfyhRGLSfXySsDKPw6W","Pauini","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("BdFPrRgFOi6BrUnYNlDB","Pedras","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("gR8FlvfQxaxw9dZrx0EV","Platô do Piquiá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("eG42yqiQ2nNE8JSNxWOJ","Presidente Figueiredo","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("IDTdU4rJtC29i0HDxRes","Purupuru","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("1PcasHenFDs6eI897eZL","Repartimento","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("9s4GLvftWij2dK0Du2Je","Repartimento de Tuiué","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("zcZ3AYU5vG48VfTifHIG","Rio Preto da Eva","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("3ggDme0wgX0QKMApdNe4","Sacambu","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("DEfYT7tQObneMyABJNBD","Santa Isabel do Rio Negro","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("zTAAPdwnNwZvsAojmZYJ","Santa Rita","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("HpvfHfDqsDZ6k3k3ZbBt","Santana","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("ycoaJEbSXo2h0Ss0gDUy","Santo Antônio do Içá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("MuytHP48v2hyUiHEBtWU","Santo Antônio do Matupi","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("efpPWDGT5LaLxJXN7aYN","São Felipe","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("xIU7RDM23LIWS7xGy8Kc","São Gabriel da Cachoeira","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("YMzpWEuPh1aLGXT92inC","São Paulo de Olivença","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("m9Bj6aoUvUfQJFBu01hB","São Sebastião do Uatumã","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("VdZrkeLAGfCfmQ7a0lUI","Silves","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("uC3lkrZCqodriLYDo9Ug","Tabatinga","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("hZJ2ypYyjDFRoukx1bKV","Tapauá","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("Vh3rsNUWhi03CbnFmZAE","Tefé","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("R3G1IkA3xd8f4Ovdlsvj","Terra Nova","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("Guo8EFqNh8rzS6h1nTox","Tonantins","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("oYlsomBpCBPcbOwux9BD","Tuiué","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("rf2vK3Dc6Yjd57oB6JsG","Uarini","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("JfCG7SmS849wDWDqQKLa","Urucará","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("ER7CM348vjL1Z5UslrVw","Urucurituba","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("lGymrRa0aofoe1EY2Xuh","Vila Amazônia","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("w9LQCQbuM9elIe7PpG01","Vila Bittencourt","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("RKr3D82XDhYFII9NWS8d","Vila de Campinas","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("BGju5ZpVq88Rt1MRKxeH","Vila de Sacambu","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("XKSvbig6jq3ijNoDtJ2L","Vila do Lago do Jacaré","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("25uGHMvNh4f1orF90uQm","Vila Lindóia","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("RPBYaWWMsF2zDBu5P3wK","Vila Pitinga","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("B0NUD7qGNsd7fW7hq0p9","Vila Rica de Caviana","U4socdTZxzTDU8WB6fIY", "AM"));
        lista.add(new Cidade("hfcn28W8YpaqmMhLh7Mb","Vila Zé Açu","U4socdTZxzTDU8WB6fIY", "AM"));
        return lista;
    }
}
