package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class BA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista = new ArrayList<Cidade>();
        lista.add(new Cidade("N7Cj0faiMBcnLGwcIWgB","Abadia","BA"));
        lista.add(new Cidade("eTA7sbZhbqcG8jaH1Pcq","Abaíra","BA"));
        lista.add(new Cidade("sIa3g9kRj8VoqY3SMys5","Abaré","BA"));
        lista.add(new Cidade("arS8DSzLVESbGRfKAIZh","Abelhas","BA"));
        lista.add(new Cidade("rcrLkWKSisiR8kDIafGQ","Abóbora","BA"));
        lista.add(new Cidade("oHNSRQsoMrCev8NbWU06","Abrantes","BA"));
        lista.add(new Cidade("79dnR75NoeL0uIZALLYL","Acajutiba","BA"));
        lista.add(new Cidade("eDWrOA3yqrTmQIB64ur1","Açu da Torre","BA"));
        lista.add(new Cidade("zNaZJAyXHIFiTHKMhNR6","Açudina","BA"));
        lista.add(new Cidade("isO46lhvpK8GRPuB5f5e","Acupe","BA"));
        lista.add(new Cidade("XQtznOW3F4K0wn5fgVzF","Adro de São Gonçalo","BA"));
        lista.add(new Cidade("DBApF4z8kjhGrJlpm1uO","Adustina","BA"));
        lista.add(new Cidade("dRxwSh24JLO46MejFLuJ","Afligidos","BA"));
        lista.add(new Cidade("HUQJ8DP6TZjZD5yuCwbO","Afrânio Peixoto","BA"));
        lista.add(new Cidade("tYHJtnsfDL9b31Mo51h4","Água Doce","BA"));
        lista.add(new Cidade("a9MqUylnEQU2D5G3sdIt","Água Fria","BA"));
        lista.add(new Cidade("gZsE4OOg1AiyobtJ6Thz","Águas do Paulista","BA"));
        lista.add(new Cidade("zVFGd25CQhDe9SisV7d3","Aiquara","BA"));
        lista.add(new Cidade("lmfOYMwwg8c4hOlx48a1","Alagoinhas","BA"));
        lista.add(new Cidade("uNuJluad4FdgMAmoUVO7","Alcobaça","BA"));
        lista.add(new Cidade("AaBcRV78C1oXUWouNyK5","Alegre","BA"));
        lista.add(new Cidade("odbQDcz4mh48zom7yBYL","Algodão","BA"));
        lista.add(new Cidade("ufQR63NM1qA5HfOE886t","Algodões","BA"));
        lista.add(new Cidade("eVkVv0l4CWOMPhM1wRfM","Almadina","BA"));
        lista.add(new Cidade("4WzXIfY4FfAP2FrFWOpK","Alto Bonito","BA"));
        lista.add(new Cidade("eKZOCogl4rqjO6ZvDJH7","Amado Bahia","BA"));
        lista.add(new Cidade("PhemOYQgJnLHLIlnnwVm","Amaniú","BA"));
        lista.add(new Cidade("eSOHWqXwe28MGbodUH1O","Amargosa","BA"));
        lista.add(new Cidade("rTvfpMD1MqVmWn5VbNHq","Amélia Rodrigues","BA"));
        lista.add(new Cidade("rxkxbegoa7eiz3r0YBGK","América Dourada","BA"));
        lista.add(new Cidade("yCEH4uqbTFXoMYXPiBbt","Américo Alves","BA"));
        lista.add(new Cidade("OZwPWF0cQxRe2yxzOUDA","Anagé","BA"));
        lista.add(new Cidade("XG88HHAPqxysbrstnZSO","Andaraí","BA"));
        lista.add(new Cidade("d5GH8lZUFIrffADG6r8D","Andorinha","BA"));
        lista.add(new Cidade("hanm4s4HfhV5lSlZw1sK","Angical","BA"));
        lista.add(new Cidade("kuX03Mcv1CrwybMMb7tW","Angico","BA"));
        lista.add(new Cidade("gwWOCUgQvCk175FLsqrv","Anguera","BA"));
        lista.add(new Cidade("eBJZ0MhlNrS78L8bXevG","Antarí","BA"));
        lista.add(new Cidade("kM0yFrmq3zBwHXnSSPFN","Antas","BA"));
        lista.add(new Cidade("09trmsRqdrU3czAo0ICN","Antônio Cardoso","BA"));
        lista.add(new Cidade("tgGCnYSg80NKC7a8Q953","Antônio Gonçalves","BA"));
        lista.add(new Cidade("eYAJPVRmkgHkdYw5ohuI","Aporá","BA"));
        lista.add(new Cidade("k2nO4wIMjYxXNGXCUMAp","Apuarema","BA"));
        lista.add(new Cidade("FfbZ0GccfFNmqp1mARW6","Araçás","BA"));
        lista.add(new Cidade("JZIHowIGZJER6m4Ohohm","Aracatu","BA"));
        lista.add(new Cidade("UjSjmYurt3s15ZdgC4QP","Araci","BA"));
        lista.add(new Cidade("FckELb0rfBZmGOoyhi0u","Aramari","BA"));
        lista.add(new Cidade("rXFeX27ExRrqM7DMTdGE","Arapiranga","BA"));
        lista.add(new Cidade("dtwArboLkqtBYwN4SubV","Arataca","BA"));
        lista.add(new Cidade("AGwd5TXb45fJCoN4Dx8R","Aratuípe","BA"));
        lista.add(new Cidade("4VcSydFTfb977aOaDUMT","Areia Branca","BA"));
        lista.add(new Cidade("SYfGLsQmAiErAZy7ZEI8","Areias","BA"));
        lista.add(new Cidade("D9T9MeJ4dt0a35c4CGfz","Arembepe","BA"));
        lista.add(new Cidade("lnb0DXpw3iGyNnP7ba7Q","Argoim","BA"));
        lista.add(new Cidade("InuVseuxYMhGHpE9HLP6","Argolo","BA"));
        lista.add(new Cidade("aYW9A1dtIR9pPg5cXqVJ","Aribice","BA"));
        lista.add(new Cidade("bwzi8AcYpDRw3oc7plZu","Aritaguá","BA"));
        lista.add(new Cidade("9kojtY6NZq7FEYDZKpxj","Arraial D'Ajuda","BA"));
        lista.add(new Cidade("IuX6IRu3nDnSCCQNLyu1","Aurelino Leal","BA"));
        lista.add(new Cidade("El5edu5b1KB9X8GKeSJP","Baianópolis","BA"));
        lista.add(new Cidade("PjexherS8KExWI2zRPII","Baixa do Palmeira","BA"));
        lista.add(new Cidade("DJpxW2NcXQeFKKajqtcO","Baixa Grande","BA"));
        lista.add(new Cidade("mapGlTSORs6HJTq2yHuy","Baixão","BA"));
        lista.add(new Cidade("HejHfWvd99omvmWmI1vf","Baixinha","BA"));
        lista.add(new Cidade("K7kEavQ9D5JptjpniFcl","Baluarte","BA"));
        lista.add(new Cidade("WDNrKcgivsFcN91v8tfK","Bananeiras","BA"));
        lista.add(new Cidade("oUSZ1sXbWbwjQGkiJwiX","Banco Central","BA"));
        lista.add(new Cidade("ToAAFmMDwAwTqFsAEdZT","Banco da Vitória","BA"));
        lista.add(new Cidade("vWhcBH8ZSOC7hp8nL5kc","Bandeira do Almada","BA"));
        lista.add(new Cidade("8RcJKGZn5JgfeAxMoHR8","Bandeira do Colônia","BA"));
        lista.add(new Cidade("llbDlLgyWOuCzbHDj39A","Bandiaçu","BA"));
        lista.add(new Cidade("ghIDbIQ6rE7axjz0zvgZ","Banzaê","BA"));
        lista.add(new Cidade("Pgp1556cpgma3cj3HSTs","Baraúnas","BA"));
        lista.add(new Cidade("bPDw8y23vRBXv2QgPsyN","Barcelos do Sul","BA"));
        lista.add(new Cidade("sjABqlxtj8fGWjg3sDLi","Barra","BA"));
        lista.add(new Cidade("1IOddFyYVohQrgJv7Ua9","Barra Avenida","BA"));
        lista.add(new Cidade("2W6EuRYgQ5uJFx11xORB","Barra da Estiva","BA"));
        lista.add(new Cidade("dQzWoEawAWyGqUsGvuiV","Barra do Choça","BA"));
        lista.add(new Cidade("V4e9l0rCQhUNn0Pc9TVa","Barra do Mendes","BA"));
        lista.add(new Cidade("fwCVF3kPiaX96beQ9Mjx","Barra do Pojuca","BA"));
        lista.add(new Cidade("sLjA5G8i5Lcmg790Q5ze","Barra do Rocha","BA"));
        lista.add(new Cidade("uCX3ussWleTHagCwVWmj","Barra do Tarrachil","BA"));
        lista.add(new Cidade("6QEF5ahwEYyJFzmPeouX","Barra Grande","BA"));
        lista.add(new Cidade("yBfaK2K3Vy8sdwLft9qR","Barracas","BA"));
        lista.add(new Cidade("BqEehAj0LxEJ3u4fHLGm","Barreiras","BA"));
        lista.add(new Cidade("nebjVu9zn1sODjSfXqh3","Barreiros","BA"));
        lista.add(new Cidade("8OHBC4vB73WghvfHni0s","Barro Alto","BA"));
        lista.add(new Cidade("vrVy9dausXQqCaImMg2m","Barro Preto","BA"));
        lista.add(new Cidade("i1mNFsYBNe4nYwRE051S","Barro Vermelho","BA"));
        lista.add(new Cidade("ISfcLRfCmeVf7nRlNx7P","Barrocão","BA"));
        lista.add(new Cidade("32tY6VLBfpxH2ZxCCtIN","Barrocas","BA"));
        lista.add(new Cidade("gFV1GR7Sx6Tk6A6R5uK3","Barrolândia","BA"));
        lista.add(new Cidade("WvkKx0kSpzVpjMdadJfo","Bastião","BA"));
        lista.add(new Cidade("E6oxbw7wQ8G4eeM7HdMD","Bate Pé","BA"));
        lista.add(new Cidade("TaZY5s3FzzhKevakzPYi","Batinga","BA"));
        lista.add(new Cidade("hwJLrP6M5oYWcINJ0TY1","Bela Flor","BA"));
        lista.add(new Cidade("tC7FQaSAhfxKfXCLA4Ja","Bela Vista","BA"));
        lista.add(new Cidade("TAdIVEJxUWJaDEGnMU3A","Belém da Cachoeira","BA"));
        lista.add(new Cidade("pyFZesoTJutAmpPlkq9Q","Belmonte","BA"));
        lista.add(new Cidade("fbKLipGcJ7oHd8FxSMYE","Belo Campo","BA"));
        lista.add(new Cidade("RddL6aknhfcW9q1LIvss","Bem-Bom","BA"));
        lista.add(new Cidade("9Gflk7B55G4IBrrEqOjS","Bendegó","BA"));
        lista.add(new Cidade("NFlTAF3SamYLAVeUXu6I","Bento Simões","BA"));
        lista.add(new Cidade("lYkQexZO4pPBcjoDuTTL","Biritinga","BA"));
        lista.add(new Cidade("xsmG4GEYVRK0uRJOtNqE","Boa Espera","BA"));
        lista.add(new Cidade("U6X8qizX7oGxyU0PRKwi","Boa Nova","BA"));
        lista.add(new Cidade("qCpRYASHN6oR8pVTQ4sn","Boa União","BA"));
        lista.add(new Cidade("DVsTVWqcZUXOtTe1SndC","Boa Vista do Lagamar","BA"));
        lista.add(new Cidade("dfEyyERRLTinuUVBnOLc","Boa Vista do Tupim","BA"));
        lista.add(new Cidade("64HKoMB2k9eDEN2t8QOf","Boaçu","BA"));
        lista.add(new Cidade("DMCssC8PZF0NqR61IgX9","Boca do Córrego","BA"));
        lista.add(new Cidade("RVUorBaO0ylGUZAI6sLZ","Bom Jesus da Lapa","BA"));
        lista.add(new Cidade("2yunLKbAHNn8Hi6TbPiz","Bom Jesus da Serra","BA"));
        lista.add(new Cidade("sQyn9sm7S41WsTEhnC14","Bom Sossego","BA"));
        lista.add(new Cidade("kqKKU5FaPSIqgHtSSznq","Bonfim da Feira","BA"));
        lista.add(new Cidade("bTZQ1DCRWS4kgqvTnbB0","Boninal","BA"));
        lista.add(new Cidade("lI7L1uCvNwDxb6JNYWGd","Bonito","BA"));
        lista.add(new Cidade("xXqeuO7FWhsUYtsaVqrN","Boquira","BA"));
        lista.add(new Cidade("zxoCNeOYRObW79IAL1I3","Botuporã","BA"));
        lista.add(new Cidade("ypdn8JMGHywTUyOQ1IRy","Botuquara","BA"));
        lista.add(new Cidade("K6HciF5tiBuZcILwWvLX","Brejinho das Ametistas","BA"));
        lista.add(new Cidade("nJK09OlVHgGe32GhPopJ","Brejo da Serra","BA"));
        lista.add(new Cidade("67Tjml75uR87uRsv2fHx","Brejo Luíza de Brito","BA"));
        lista.add(new Cidade("JJ9jGp9G0vhqqZnD8Jh8","Brejo Novo","BA"));
        lista.add(new Cidade("BWgTCjZ0lrT16ApdA6AR","Brejões","BA"));
        lista.add(new Cidade("pRia366NW5HNudG1Q2nc","Brejolândia","BA"));
        lista.add(new Cidade("TNrz9edNf1TAskuqlWmy","Brotas de Macaúbas","BA"));
        lista.add(new Cidade("qPl02bp1ZJyMYU7vDiv7","Brumado","BA"));
        lista.add(new Cidade("3Kio4TXVXQo1ASo9Txmi","Bucuituba","BA"));
        lista.add(new Cidade("bh4qCsNNzhoI7uHHdpCi","Buerarema","BA"));
        lista.add(new Cidade("lBOUgb14HBiS2Mc5UIig","Buracica","BA"));
        lista.add(new Cidade("lm6Xn9KHERcrQ78LC3F4","Buranhém","BA"));
        lista.add(new Cidade("728ZW9RGv8xFdRjwynrG","Buril","BA"));
        lista.add(new Cidade("DSlXWepEOTfBMMbORYA7","Buritirama","BA"));
        lista.add(new Cidade("wrcLvhF52UNh22O1qCXV","Caatiba","BA"));
        lista.add(new Cidade("TZFdm1fLFp1REfE0I1Ye","Cabaceiras do Paraguaçu","BA"));
        lista.add(new Cidade("qofKRi0ZepI1iqtVjjre","Cabeceira do Jibóia","BA"));
        lista.add(new Cidade("gKubjxbHpDQJm5IjjO9O","Cabôto","BA"));
        lista.add(new Cidade("gM57PNxeiTJUOvTnYqZh","Cabrália","BA"));
        lista.add(new Cidade("qwTfhan52cFNhnZWdbax","Cacha Pregos","BA"));
        lista.add(new Cidade("c7drnhGQrip6u8DT8n7S","Cachoeira","BA"));
        lista.add(new Cidade("jarKpk3OQ5xGifiDCkZX","Cachoeira do Mato","BA"));
        lista.add(new Cidade("9b5YF9wQoWOiY80GGGyB","Caculé","BA"));
        lista.add(new Cidade("pb7qOP1c0DPsrqKrbxxg","Caém","BA"));
        lista.add(new Cidade("qV3CzXW0TzulU00CJ3Kd","Caetanos","BA"));
        lista.add(new Cidade("bLxESOMnNgGwDuScdX7y","Caeté-Açu","BA"));
        lista.add(new Cidade("LI7LkDQQpcRcu2vaMLbR","Caetité","BA"));
        lista.add(new Cidade("FLOxeuTYKrWxToPaNNJF","Cafarnaum","BA"));
        lista.add(new Cidade("LAx7nH7IoK6k0ESmIdx1","Caiçara","BA"));
        lista.add(new Cidade("Z8QaCHabJlTI1TEPCjEx","Caimbé","BA"));
        lista.add(new Cidade("b2aM2CiZAp2nvIMMIPF8","Cairu","BA"));
        lista.add(new Cidade("UI6mmXS2uphmEZByxQ8u","Caiubi","BA"));
        lista.add(new Cidade("m29u4GWd4BKRaLdTBuap","Cajuí","BA"));
        lista.add(new Cidade("PenMYujXZTbhgc9UTFS2","Caldas do Jorro","BA"));
        lista.add(new Cidade("2QfmRKEvryna0FqhSBv4","Caldeirão","BA"));
        lista.add(new Cidade("emyulx0IJIlgPAV71qi9","Caldeirão Grande","BA"));
        lista.add(new Cidade("rzXRB3i74BJbQ1jOfqcH","Caldeiras","BA"));
        lista.add(new Cidade("ASWJh0Ffq8CZK4CsIQA8","Camacan","BA"));
        lista.add(new Cidade("MmcMyPxk6z9i8AmoNzbj","Camaçari","BA"));
        lista.add(new Cidade("SO0NP5OLNPlJY4IFsfLY","Camamu","BA"));
        lista.add(new Cidade("6OavBBtXdFPF2PPz76iZ","Camassandi","BA"));
        lista.add(new Cidade("ShZ0auHr3mVF8FntZvnZ","Camirim","BA"));
        lista.add(new Cidade("IRmh6tZCfEJIniM9LK02","Campinhos","BA"));
        lista.add(new Cidade("Df5VKUgpCLDMYoiTNAVP","Campo Alegre de Lourdes","BA"));
        lista.add(new Cidade("wsrFbxbtOWcmaZGJSw1d","Campo Formoso","BA"));
        lista.add(new Cidade("ooeIsCLBpku5xuEqwMzL","Camurugi","BA"));
        lista.add(new Cidade("0YNC1EPW1BONU7SnHbSs","Cana Brava","BA"));
        lista.add(new Cidade("h1Gyk3jXzzq6fONwS1Q3","Canabravinha","BA"));
        lista.add(new Cidade("8lXFvDhM6ZgGnylFEftt","Canápolis","BA"));
        lista.add(new Cidade("CztrSOLsoZkfSGxzto02","Canarana","BA"));
        lista.add(new Cidade("KCt9uzS5Zl48LBt2LJpj","Canatiba","BA"));
        lista.add(new Cidade("IWMM0wCoNFGuk5NkBbGi","Canavieiras","BA"));
        lista.add(new Cidade("QXGY7jq0JzRXsqI8zw0D","Canché","BA"));
        lista.add(new Cidade("JnDuFqBvwR7dXEuFS72q","Candeal","BA"));
        lista.add(new Cidade("49WsXAIgS2GyTL4m4XLl","Candeias","BA"));
        lista.add(new Cidade("H68HPJ64xpMUryljQerN","Candiba","BA"));
        lista.add(new Cidade("uEwmKkwJSSyi2DtvNyGJ","Cândido Sales","BA"));
        lista.add(new Cidade("bwnEvBKAjvO06eau289d","Canoão","BA"));
        lista.add(new Cidade("lDZEnIVte9pCa911pM1v","Cansanção","BA"));
        lista.add(new Cidade("sc1wMK8b8IZ4L77506zP","Canto do Sol","BA"));
        lista.add(new Cidade("hn1ohaFbZ2hawn259V8b","Canudos","BA"));
        lista.add(new Cidade("ehrWxS3pLQXBdYhhZH6y","Capão","BA"));
        lista.add(new Cidade("fxyicHYEXPwIgmKyVUYL","Capela do Alto Alegre","BA"));
        lista.add(new Cidade("2bt29fINWLqMiH6UWRO4","Capim Grosso","BA"));
        lista.add(new Cidade("Xqv8guEJmHXBPQgE8W23","Caraguataí","BA"));
        lista.add(new Cidade("SiTT9o3LmG9nPQJQ0HU2","Caraíbas","BA"));
        lista.add(new Cidade("HzZCbhpf5BtL7mObYxxN","Caraibuna","BA"));
        lista.add(new Cidade("Al1Aq1yb22Xl0N50DTyq","Caraípe","BA"));
        lista.add(new Cidade("1o1XRNkWt8PJNbAUHT6m","Caraiva","BA"));
        lista.add(new Cidade("uq97WVFdXJymNkxMToNo","Caravelas","BA"));
        lista.add(new Cidade("fiUQ359htGaviq0ftXiw","Cardeal da Silva","BA"));
        lista.add(new Cidade("CsWeEkIa6HaVXFfEfNxN","Carinhanha","BA"));
        lista.add(new Cidade("oFR3z9FZk94LgPSMVo4B","Caripare","BA"));
        lista.add(new Cidade("Y5KDCZ3rNErH4mtB3a1M","Carnaíba do Sertão","BA"));
        lista.add(new Cidade("Sr3KO8Yqo4P9cXLwovoB","Caroba","BA"));
        lista.add(new Cidade("if7LUZTXZ7gPIZ27K01C","Carrapichel","BA"));
        lista.add(new Cidade("oOQxVSfwAxks8DVQf5n0","Casa Nova","BA"));
        lista.add(new Cidade("pPK9ngSLPDKrVytbtW1T","Castelo Novo","BA"));
        lista.add(new Cidade("4yQ5RVKUoYJNI5mew4pe","Castro Alves","BA"));
        lista.add(new Cidade("LxZD6lKX50id1m0l5pgN","Catinga do Moura","BA"));
        lista.add(new Cidade("SeoNsCjUmXPQK6aZTfwk","Catingal","BA"));
        lista.add(new Cidade("RUI17zoGUS4KJjxma9uh","Catolândia","BA"));
        lista.add(new Cidade("fP7UA6MLTgsAL0pRVpjz","Catolés","BA"));
        lista.add(new Cidade("yn7whfSMlEl0zM3m9g8c","Catolezinho","BA"));
        lista.add(new Cidade("1uM3x6wRyP3Xp9tbRS5g","Catu","BA"));
        lista.add(new Cidade("jQUDhZRHRovHSP4UgM80","Catu de Abrantes","BA"));
        lista.add(new Cidade("rUWz3r3oAApi1akwty4P","Caturama","BA"));
        lista.add(new Cidade("Gjbu7ubBYbU1JqOPCDnu","Cavunge","BA"));
        lista.add(new Cidade("tiUYyBCCjv7FYiom9PwQ","Central","BA"));
        lista.add(new Cidade("050pznBroQgDUGQx8MFo","Ceraima","BA"));
        lista.add(new Cidade("Ase2HJhQVWBu0rwgqdvL","Cercadinho","BA"));
        lista.add(new Cidade("3Hw6022XpYNFiZN7YP59","Chorrochó","BA"));
        lista.add(new Cidade("016vDKFzJKXOxL0Qyu3K","Cícero Dantas","BA"));
        lista.add(new Cidade("MPYRU9xi5KPRhgArT1Az","Cinco Rios","BA"));
        lista.add(new Cidade("zbRalTRYfcpgm8d5Hwqp","Cipó","BA"));
        lista.add(new Cidade("RydtVYPKlLDoMsPXlhr3","Coaraci","BA"));
        lista.add(new Cidade("HXEfBKTuMqYD4FZcjpF5","Cocos","BA"));
        lista.add(new Cidade("7y0tyBd4i6ZpCziiFF0M","Colônia","BA"));
        lista.add(new Cidade("2hK2ZBoeHXzTvpV724sj","Colônia do Formoso","BA"));
        lista.add(new Cidade("KL74jIoigSOEMFP2uLvs","Comércio","BA"));
        lista.add(new Cidade("Q8dTTf8C0dJYGLHVdStd","Conceição da Feira","BA"));
        lista.add(new Cidade("hvslnpfOAFcPQAVfjbVb","Conceição do Almeida","BA"));
        lista.add(new Cidade("wFoyYDKTXJZNWRdkMpqY","Conceição do Coité","BA"));
        lista.add(new Cidade("2ozzoNRTU2jnheK7LXfN","Conceição do Jacuípe","BA"));
        lista.add(new Cidade("KKq4wmb98xzSaplz88ZH","Conde","BA"));
        lista.add(new Cidade("YOXGvefZ44TwaFPifm3L","Condeúba","BA"));
        lista.add(new Cidade("W9sG4VZgrPX8Mcmbt7Fr","Contendas do Sincorá","BA"));
        lista.add(new Cidade("nT0sdxTQwQCK57Ae67Bi","Copixaba","BA"));
        lista.add(new Cidade("OiaFp1yT4pPpOfu38Dei","Coqueiros","BA"));
        lista.add(new Cidade("zqiLs3rXib84Ov6bFGDN","Coquinhos","BA"));
        lista.add(new Cidade("ZFWjV7vaq8cYc17bKRTS","Coração de Maria","BA"));
        lista.add(new Cidade("eOlJAwd2scttXRsDUunD","Cordeiros","BA"));
        lista.add(new Cidade("AmZVVt48jEHPktw6JAsE","Coribe","BA"));
        lista.add(new Cidade("I5rA5n1oEReIe0cX0tcy","Coronel João Sá","BA"));
        lista.add(new Cidade("KKY0QbHDc5jnLIi1EzGT","Correntina","BA"));
        lista.add(new Cidade("cERTbM4xPgFfvxodQntZ","Corta Mão","BA"));
        lista.add(new Cidade("0DWj9i5SffVhKQqvPuLv","Cotegipe","BA"));
        lista.add(new Cidade("gi4TzqlefRhzoaJnW2Ge","Coutos","BA"));
        lista.add(new Cidade("BBuW3gK7zixHnseUa2gK","Cravolândia","BA"));
        lista.add(new Cidade("sA3x5KG5QjvK9dWFweU8","Crisópolis","BA"));
        lista.add(new Cidade("7bFsQlnSPLNE1NUwOv3x","Cristalândia","BA"));
        lista.add(new Cidade("1j0kUEEpbVskUt13JEbx","Cristópolis","BA"));
        lista.add(new Cidade("zyDF759sKYcmVNbxuUiO","Crussaí","BA"));
        lista.add(new Cidade("LrvqFdvr2WpjrHSzuFYA","Cruz das Almas","BA"));
        lista.add(new Cidade("mzhwoUSeOZ4yyqzZnHkL","Cumuruxatiba","BA"));
        lista.add(new Cidade("FZiUohmurnNjqigIpd2N","Cunhangi","BA"));
        lista.add(new Cidade("8I6VblK57DdWZCEMDImS","Curaçá","BA"));
        lista.add(new Cidade("8s3iNURAWP8HdlFLUnOn","Curral Falso","BA"));
        lista.add(new Cidade("eoyNoCpJR5aa46dKTQK4","Dantelândia","BA"));
        lista.add(new Cidade("uJgNH0cdOCPEN5NgjCS2","Dário Meira","BA"));
        lista.add(new Cidade("Jl1p1xb3IwIBbCMu7lBO","Delfino","BA"));
        lista.add(new Cidade("BXTYXo7xXhwVeyMkJziA","Descoberto","BA"));
        lista.add(new Cidade("hfxHCapop8CM7bJOjgvn","Dias Coelho","BA"));
        lista.add(new Cidade("Uw6ctCHDKQrjuLxSNSgv","Dias D'Ávila","BA"));
        lista.add(new Cidade("ZF0kwBKjRXFkHgmyfUge","Diógenes Sampaio","BA"));
        lista.add(new Cidade("iN2dJEDKqnq7EwobEWgt","Dom Basílio","BA"));
        lista.add(new Cidade("0ePRvnowa8dhngBNHlcB","Dom Macedo Costa","BA"));
        lista.add(new Cidade("rt7puIuy5tzP2PqE06vy","Dona Maria","BA"));
        lista.add(new Cidade("5WxCt8NfjkGIiDnv5Zwv","Duas Barras do Morro","BA"));
        lista.add(new Cidade("3W9KIdoBWcStCQD2yQbs","Elísio Medrado","BA"));
        lista.add(new Cidade("AkPUr3HvQNWAyi8H4RRL","Encruzilhada","BA"));
        lista.add(new Cidade("DR8kUOL8QY1PZs0fmZM4","Engenheiro França","BA"));
        lista.add(new Cidade("mo1nROwhf10gTqbYDQPE","Engenheiro Pontes","BA"));
        lista.add(new Cidade("sdxnn1jlb10VTWeDEzeO","Entre Rios","BA"));
        lista.add(new Cidade("xZi4SjvS4sHE6j6a5SkQ","Érico Cardoso","BA"));
        lista.add(new Cidade("gBvxzkZSsOtihKt1Ir9w","Esplanada","BA"));
        lista.add(new Cidade("ebGeLaZ9bb0MTgq17eUu","Espraiado","BA"));
        lista.add(new Cidade("hajGnkxW34OOQRpADYER","Euclides da Cunha","BA"));
        lista.add(new Cidade("LT4Keu8pvuCo33SPefmN","Eunápolis","BA"));
        lista.add(new Cidade("pOKf6cCBTTmIG4gYjsV5","Fátima","BA"));
        lista.add(new Cidade("bMeeD8EyJrH252BGuokF","Feira da Mata","BA"));
        lista.add(new Cidade("3eEhKiuOS9AiIS0SLuF7","Feira de Santana","BA"));
        lista.add(new Cidade("fKDgLSs4z9xmAv0571bd","Ferradas","BA"));
        lista.add(new Cidade("0EanMpyJ9J7vN6glm2y2","Filadélfia","BA"));
        lista.add(new Cidade("sYRVjjP8I0xhtsvBwpKL","Filanésia","BA"));
        lista.add(new Cidade("bfZbCngvsDRS3RrAIBrX","Firmino Alves","BA"));
        lista.add(new Cidade("drBFalTNmwv0QzKLbY2G","Floresta Azul","BA"));
        lista.add(new Cidade("ywmlSGD7CGcjhdDRAG3p","Florestal","BA"));
        lista.add(new Cidade("WUSLTZQQyxvHyTKaGrEx","Formosa do Rio Preto","BA"));
        lista.add(new Cidade("a3oCNtV9DCq05nvmwohP","França","BA"));
        lista.add(new Cidade("B4Lbs07jSXy8g4FxuwyB","Gabiarra","BA"));
        lista.add(new Cidade("0KGXV0u9bBcVlcMtY1Jc","Galeão","BA"));
        lista.add(new Cidade("lm5kIUhPrRz30Bw2GHRs","Gamboa","BA"));
        lista.add(new Cidade("mmMc8IKR71jsTn66BchT","Gameleira da Lapa","BA"));
        lista.add(new Cidade("TEgOTx3KPQlWL0C7o8id","Gameleira do Assuruá","BA"));
        lista.add(new Cidade("zX21Fh0emHqH3atrbrR8","Gandu","BA"));
        lista.add(new Cidade("f7bgFbC6Y1BX3n6XJfLQ","Gavião","BA"));
        lista.add(new Cidade("5EepivfAU8SGDcNlXr64","Gentio do Ouro","BA"));
        lista.add(new Cidade("INv6ibCyMYb9Or9Hxhaz","Geolândia","BA"));
        lista.add(new Cidade("orN8OvujbQdWLneXCkzK","Glória","BA"));
        lista.add(new Cidade("mKLbXbVU9vLMLNLpAJAH","Gongogi","BA"));
        lista.add(new Cidade("m22s4xNDYsVlgOduphis","Governador João Durval Carneiro","BA"));
        lista.add(new Cidade("FfMz9LQdHiH6Rwj22gKs","Governador Mangabeira","BA"));
        lista.add(new Cidade("2mAHNS5vYkeRgMPnbRf9","Guaí","BA"));
        lista.add(new Cidade("e0meYAccejHSwrPkaE0G","Guajeru","BA"));
        lista.add(new Cidade("JdSUX1VYuATPxXDrEZKa","Guanambi","BA"));
        lista.add(new Cidade("zOCx8VXGishDa0hMiMkn","Guapira","BA"));
        lista.add(new Cidade("yP65aJbd9qugVRL1sTIK","Guarajuba","BA"));
        lista.add(new Cidade("Y5UUUW3gaXPcEmGW8RYw","Guaratinga","BA"));
        lista.add(new Cidade("v0mMkiShJkShfDlARLKn","Guerém","BA"));
        lista.add(new Cidade("VDtzyjyplTEpE2x6edjk","Guiné","BA"));
        lista.add(new Cidade("LB87wX7fFJHhvw6mlvRw","Guirapa","BA"));
        lista.add(new Cidade("KfwD2wYeZrWC9zJRGyLX","Gurupá Mirim","BA"));
        lista.add(new Cidade("8sh63saLHsJQaHREFBfa","Heliópolis","BA"));
        lista.add(new Cidade("C09V2FwlO3Tdy8L1b11t","Helvecia","BA"));
        lista.add(new Cidade("FfoYgx3hr6LiWYKjsOFy","Hidrolândia","BA"));
        lista.add(new Cidade("TljpTo3cnVeNfvJ67vO5","Humildes","BA"));
        lista.add(new Cidade("S04YakRiAMmRD8XFrgjP","Iaçu","BA"));
        lista.add(new Cidade("Omw1TrpBwKpJ0QKBQstx","Ibatui","BA"));
        lista.add(new Cidade("L2KnRfIAIRaa5O9j3dt2","Ibiaçu","BA"));
        lista.add(new Cidade("DUuJvOhnhJ4OjH08TEXy","Ibiajara","BA"));
        lista.add(new Cidade("g856z2DfViNq03wR1dnY","Ibiapora","BA"));
        lista.add(new Cidade("LsCJCBr8o5UPXNOcP6cz","Ibiassucê","BA"));
        lista.add(new Cidade("lebMBR9d4OAbNJ8voxfl","Ibicaraí","BA"));
        lista.add(new Cidade("cDDSnpPDcEJyDdgcMkZC","Ibicoara","BA"));
        lista.add(new Cidade("Y4jrDq1uZ3kmWmCV9M51","Ibicuí","BA"));
        lista.add(new Cidade("BprhLplSGJZY1mDFImZi","Ibipeba","BA"));
        lista.add(new Cidade("EpDpCxGa9ghVuMWcvHgD","Ibipetum","BA"));
        lista.add(new Cidade("4iOdWU4jbPSEkdfOYxIE","Ibipitanga","BA"));
        lista.add(new Cidade("UoAyiFcWBJmCjzy8nRgb","Ibiquera","BA"));
        lista.add(new Cidade("rgUaRLMC3EypkVQKrDsU","Ibiraba","BA"));
        lista.add(new Cidade("NzUClqzLTYojzQOcG0il","Ibirajá","BA"));
        lista.add(new Cidade("HuWpmztCK0pxe0luBn06","Ibiranhém","BA"));
        lista.add(new Cidade("3W90QQthoeM5OgJhWdif","Ibirapitanga","BA"));
        lista.add(new Cidade("G5VzyJ2Q1L9Ab4ckBVBb","Ibirapuã","BA"));
        lista.add(new Cidade("1YBekcaLySSltKwuSIcN","Ibirataia","BA"));
        lista.add(new Cidade("sAdXqONK11cYspPRVQ1J","Ibitiara","BA"));
        lista.add(new Cidade("25QtEM4S6vGZ24oRV3cq","Ibitiguira","BA"));
        lista.add(new Cidade("hLvd3kdTOsMtlPI6P2Sw","Ibitira","BA"));
        lista.add(new Cidade("LAttcPEJw5KbqFVUvyOJ","Ibititá","BA"));
        lista.add(new Cidade("TU5fiZg8yYPeBeFuOn29","Ibitunane","BA"));
        lista.add(new Cidade("VQSCznWv6z8lyQfO1dgO","Ibitupa","BA"));
        lista.add(new Cidade("AUtMcAAmahY7uoIJTzo9","Ibó","BA"));
        lista.add(new Cidade("DwfuEhRjMuZVyhirAqcZ","Ibotirama","BA"));
        lista.add(new Cidade("D1BVDZPVHpT0ku0LcVrG","Ichu","BA"));
        lista.add(new Cidade("CZY7fBnrcAyHeXGiy6JX","Icó","BA"));
        lista.add(new Cidade("z8mKlqSSnt3zozE3CjXu","Igaporã","BA"));
        lista.add(new Cidade("B4ZqSnYp7V8GAsOpcZL8","Igará","BA"));
        lista.add(new Cidade("VY8eAbcsEEEJljMLmBSD","Igarité","BA"));
        lista.add(new Cidade("jbq2XJn8tS6Wx5r7oJmT","Igatu","BA"));
        lista.add(new Cidade("mLWagmejez1YjzNk5TLf","Igrapiúna","BA"));
        lista.add(new Cidade("wLY28CinGYiVhTDbJX8z","Iguá","BA"));
        lista.add(new Cidade("wQdxPjbZ4LNGx9tXxLV4","Iguaí","BA"));
        lista.add(new Cidade("DZ8ai2uNNa1pXeIbmEwx","Iguaibi","BA"));
        lista.add(new Cidade("Hxu2Pbx0eYUgnfPMJFmE","Iguatemi","BA"));
        lista.add(new Cidade("6CIimjqG2CodWYYd8dvj","Iguira","BA"));
        lista.add(new Cidade("RRoGPnSQ5CfEzT7VMjpk","Iguitu","BA"));
        lista.add(new Cidade("cJ1oyjrxx5EdjcmoDcmv","Ilha de Bom Jesus dos Passos","BA"));
        lista.add(new Cidade("yHtXb0XFBYzlKqaEiNnB","Ilha de Maré","BA"));
        lista.add(new Cidade("amIzz5wB4EJKBufwgSB6","Ilha dos Frades","BA"));
        lista.add(new Cidade("8xcj9gjifVvJLAJn83WV","Ilhéus","BA"));
        lista.add(new Cidade("KcbYepzfTPBcTgZfHnT9","Imbassaí","BA"));
        lista.add(new Cidade("CbczxOcERAPu1DkTITDG","Indaí","BA"));
        lista.add(new Cidade("MSPjF5u8cntLroqiSbIL","Inema","BA"));
        lista.add(new Cidade("EIVz1Ncf32MWoMQ8KMVe","Inhambupe","BA"));
        lista.add(new Cidade("SuVBoK1arpYynXiOOKrZ","Inhata","BA"));
        lista.add(new Cidade("MYhjROBzLF5YvH5cmvdJ","Inhaúmas","BA"));
        lista.add(new Cidade("9L2e9X0LmZA0ddI1K1TE","Inhobim","BA"));
        lista.add(new Cidade("d6KdLNMwrXhdwLw6BlnQ","Inúbia","BA"));
        lista.add(new Cidade("7wRn7RldnSYATeAWG2p0","Ipanema","BA"));
        lista.add(new Cidade("hxA9KtHfeRb79659lrzh","Ipecaetá","BA"));
        lista.add(new Cidade("AmKqm3T1sUgbBlwbpnov","Ipiaú","BA"));
        lista.add(new Cidade("GFMPYm5yQVEv1n0SDZ1y","Ipirá","BA"));
        lista.add(new Cidade("frGwHBzV7P4nolCbaKdZ","Ipiúna","BA"));
        lista.add(new Cidade("BVvSQUfdBbA9Rwi9m7G4","Ipucaba","BA"));
        lista.add(new Cidade("q0zSabftTxA1n5tupINk","Ipupiara","BA"));
        lista.add(new Cidade("bQRZ1Cqm2VIiUg3oWPR7","Irajuba","BA"));
        lista.add(new Cidade("Sf1MdLZZess6o4wyr7Kd","Iramaia","BA"));
        lista.add(new Cidade("bOrsHgdydIMZDCYfJM8g","Iraporanga","BA"));
        lista.add(new Cidade("lkDIlEzmQzLVWVJ4vrex","Iraquara","BA"));
        lista.add(new Cidade("RaFhNPttwo9veNZ8Tu7y","Irará","BA"));
        lista.add(new Cidade("oj80Natmb8CjaVsm6BDW","Irecê","BA"));
        lista.add(new Cidade("Ulq4G9Iz6MGag9DOAGp6","Irundiara","BA"));
        lista.add(new Cidade("aepJDQfupmG94xpghw3h","Ita-Azul","BA"));
        lista.add(new Cidade("nr2GYdlm6YDMO3o8nCZh","Itabatã","BA"));
        lista.add(new Cidade("8B7xqOizgKDdWPSFnw75","Itabatan","BA"));
        lista.add(new Cidade("mwstQiWelbr2oHVifOzx","Itabela","BA"));
        lista.add(new Cidade("jSImgbfHaClKT773vYP0","Itaberaba","BA"));
        lista.add(new Cidade("ISrDuJevJomUzmaWJI4M","Itabuna","BA"));
        lista.add(new Cidade("NgZiIF01pMEB8NdO4Elj","Itacaré","BA"));
        lista.add(new Cidade("fuvm252iKScBuKIDX3pT","Itacava","BA"));
        lista.add(new Cidade("fPg0XGjyqLsS9A3iFh9N","Itachama","BA"));
        lista.add(new Cidade("gp7CTvBkTCJHLTjlEmoz","Itacimirim","BA"));
        lista.add(new Cidade("GYYJO0gZ5w9cucBtOOMt","Itaeté","BA"));
        lista.add(new Cidade("khc2FZrbT9JVYKSbxKch","Itagi","BA"));
        lista.add(new Cidade("mVJP1H6EJVnF5ODAleFR","Itagibá","BA"));
        lista.add(new Cidade("6B6HewU2Xn9USIK9sCqO","Itagimirim","BA"));
        lista.add(new Cidade("MvJRNegjZ7yxoW1tUNMh","Itaguaçu da Bahia","BA"));
        lista.add(new Cidade("zNgQDEwbKNgt4I5RQ995","Itaia","BA"));
        lista.add(new Cidade("FZkuH2LXj2dto8IHVVnL","Itaibó","BA"));
        lista.add(new Cidade("W4ivQsIppdvPJ4ELcnXK","Itaipu","BA"));
        lista.add(new Cidade("4ROnjYJS0YKUdRYpabEP","Itaítu","BA"));
        lista.add(new Cidade("iAcD3hRYXlbyT7XBT76O","Itajaí","BA"));
        lista.add(new Cidade("Yik5eNbxdxNLTqHpRlpc","Itaju do Colônia","BA"));
        lista.add(new Cidade("2FZDdXPOnBxHHjPsuqEw","Itajubaquara","BA"));
        lista.add(new Cidade("yb8CDQTS5Dcgg5vUUs5z","Itajuípe","BA"));
        lista.add(new Cidade("TX4x5WIQXoBqt9W5fI0U","Itajuru","BA"));
        lista.add(new Cidade("BWh2LfAPxFBMutaYX4Mw","Itamaraju","BA"));
        lista.add(new Cidade("KdS7pEWzGAYZC9lnnT3W","Itamari","BA"));
        lista.add(new Cidade("eV9mQ1akYoTM9pBDWnAy","Itambé","BA"));
        lista.add(new Cidade("zWNQ8FuILc2jyQG0EAkv","Itamira","BA"));
        lista.add(new Cidade("2XDjNVj46tafXIMlCmmJ","Itamotinga","BA"));
        lista.add(new Cidade("iubBvtr0AxAcwExik7BJ","Itanagé","BA"));
        lista.add(new Cidade("7Xhlndc8mRwpklXed1Mp","Itanagra","BA"));
        lista.add(new Cidade("zGFmIR2bbxxE69jXwtDM","Itanhém","BA"));
        lista.add(new Cidade("TLfZTrGaMOlQV21f8NAd","Itanhi","BA"));
        lista.add(new Cidade("MdWefqXbtUDBxkQL2QAM","Itaparica","BA"));
        lista.add(new Cidade("AQdzHvqVfhx9QleDfheT","Itapé","BA"));
        lista.add(new Cidade("FASfrpHsXTaUNWbJ5n3U","Itapebi","BA"));
        lista.add(new Cidade("tqei7PP30XAVd53XsB8d","Itapeipu","BA"));
        lista.add(new Cidade("SXHuPkWD4x1nLBsJIY0N","Itapetinga","BA"));
        lista.add(new Cidade("jjStRN1JWLGzcEXBSz04","Itapicuru","BA"));
        lista.add(new Cidade("ZZqkzqm64sDlMhYO8JMZ","Itapirema","BA"));
        lista.add(new Cidade("HC8ZVf8pagfCbaYPfC6l","Itapitanga","BA"));
        lista.add(new Cidade("wtVRwIRbsHJjJLfnQUnc","Itapora","BA"));
        lista.add(new Cidade("n7h2Bf6tPma91eCr9rv2","Itapura","BA"));
        lista.add(new Cidade("kxS7kR9X9UvrBHAzyBk0","Itaquara","BA"));
        lista.add(new Cidade("RNNR3GkkrBhMAgFjIKAA","Itaquaraí","BA"));
        lista.add(new Cidade("3V0kRKkVHfCAzOqo47S4","Itarantim","BA"));
        lista.add(new Cidade("GJYfvr1nTFLjuIMpBK0V","Itati","BA"));
        lista.add(new Cidade("uVFJjw9U5cKZ5rAumIMa","Itatiaia do Alto Bonito","BA"));
        lista.add(new Cidade("Qp9D7oMBc2E8QC60GjVA","Itatim","BA"));
        lista.add(new Cidade("aR1UKguQ8ITd05IDhqK0","Itatingui","BA"));
        lista.add(new Cidade("Mdpojk7Wsi3FT4CVah0I","Itiruçu","BA"));
        lista.add(new Cidade("UnYHfSadhZQyAb6YShQS","Itiúba","BA"));
        lista.add(new Cidade("a0I1T67wJ16L7thnaQ2n","Itororó","BA"));
        lista.add(new Cidade("Cfne8hpzv9s2W4ZjmlCS","Ituaçu","BA"));
        lista.add(new Cidade("oZzNS9tmKSVSxPEvVo85","Ituberá","BA"));
        lista.add(new Cidade("3bnxPtbwlG5RRjcUULpr","Itupeva","BA"));
        lista.add(new Cidade("LddKRDBcMt4pajA6JXJB","Iuiu","BA"));
        lista.add(new Cidade("U6jXOYSX6AVxQEPnhHYk","Jaborandi","BA"));
        lista.add(new Cidade("bFUoNqXVpreW6ZvdL05L","Jacaraci","BA"));
        lista.add(new Cidade("Nrdx9MoPUXbMgPsO8PQO","Jacobina","BA"));
        lista.add(new Cidade("M4swn3pZQr9foS2VYLCH","Jacu","BA"));
        lista.add(new Cidade("InZnDJ90yLQga3hswJnz","Jacuípe","BA"));
        lista.add(new Cidade("JTYOXRkZN6rwaCfOkiY1","Jacuruna","BA"));
        lista.add(new Cidade("Y9owSDhYexST4EiaFJ44","Jaguaquara","BA"));
        lista.add(new Cidade("saADumdzZ7jf3zqP3AvK","Jaguara","BA"));
        lista.add(new Cidade("af6u15l2UaSC3uwOLNZW","Jaguarari","BA"));
        lista.add(new Cidade("0PSXeWWE5va1BT1AEO2P","Jaguaripe","BA"));
        lista.add(new Cidade("VI4oSXNSnnQjAvoIukBe","Jaíba","BA"));
        lista.add(new Cidade("Ql5HuDM5MEvnCPXYLRMu","Jandaíra","BA"));
        lista.add(new Cidade("NAyig54haZJgy9rcGd2a","Japomirim","BA"));
        lista.add(new Cidade("am7J0bC2g38C3P7aiew2","Japu","BA"));
        lista.add(new Cidade("V8OQdelinoxHW7fcfiXo","Jauá","BA"));
        lista.add(new Cidade("9GR12Ej9rPXokb3CoCQZ","Jequié","BA"));
        lista.add(new Cidade("RKJ3jT5e9xyG8JvAW98b","Jeremoabo","BA"));
        lista.add(new Cidade("VfYuhnr5schTLZHAPPyV","Jiquiriçá","BA"));
        lista.add(new Cidade("3U6JxTFHQkcJvnRqnlsD","Jiribatuba","BA"));
        lista.add(new Cidade("BwSDtxzgjfW6ZlNKcsK5","Jitaúna","BA"));
        lista.add(new Cidade("1FwN1ycX2LapuSO0zEGf","João Amaro","BA"));
        lista.add(new Cidade("H5pRrYhL9D2ToMycOqiT","João Correia","BA"));
        lista.add(new Cidade("zHQjkO4QuTJP0xxHaN1u","João Dourado","BA"));
        lista.add(new Cidade("NERHWC08eMorecMbFC4O","José Gonçalves","BA"));
        lista.add(new Cidade("2crDWaiYTfWBC7Ok0fGB","Juacema","BA"));
        lista.add(new Cidade("bTmZoSEmodM6QNDv1GYQ","Juazeiro","BA"));
        lista.add(new Cidade("eeyIVGQd9nH0n5l9V3as","Jucuruçu","BA"));
        lista.add(new Cidade("nTjdHc0WvFeWyefWRFEF","Juerana","BA"));
        lista.add(new Cidade("FmKd20E3fTSxurY6wJTy","Junco","BA"));
        lista.add(new Cidade("mcPRJxEF4LKopUhmAlnU","Jupaguá","BA"));
        lista.add(new Cidade("lI2DlMU15znTokE5wjX2","Juraci","BA"));
        lista.add(new Cidade("xiUwDC5bniKX3syYrkZJ","Juremal","BA"));
        lista.add(new Cidade("UanwHfV9Sy6JnP5Xaeyi","Jussara","BA"));
        lista.add(new Cidade("L8iHd30dcKJpetjRvF2y","Jussari","BA"));
        lista.add(new Cidade("4RYCibOaNyg2AM8osuYZ","Jussiape","BA"));
        lista.add(new Cidade("v6t2EHSc82TuYC08QNqP","Km Sete","BA"));
        lista.add(new Cidade("sWmgamq13LaMaQoVMFbX","Lafaiete Coutinho","BA"));
        lista.add(new Cidade("4JRELX4N1qz2S2OzZHaB","Lagoa Clara","BA"));
        lista.add(new Cidade("2SIyLZMckC9Rg9N5MemN","Lagoa de Melquíades","BA"));
        lista.add(new Cidade("LodkN33TsLPUFqLv1iPn","Lagoa do Boi","BA"));
        lista.add(new Cidade("Zi8OQMKIy1VAzcfoFhIk","Lagoa Grande","BA"));
        lista.add(new Cidade("tW6C3uVfutUD8UkW9AUS","Lagoa José Luís","BA"));
        lista.add(new Cidade("hLZWKn2hlIRWBb9wmYCV","Lagoa Preta","BA"));
        lista.add(new Cidade("PBi3acH8jONvHun4glGw","Lagoa Real","BA"));
        lista.add(new Cidade("amwncFHSUVTB4B5w1IpS","Laje","BA"));
        lista.add(new Cidade("JCxBpmkFSDJpxjLh7KFi","Laje do Banco","BA"));
        lista.add(new Cidade("edVHTU4DuFbQ1fQt5d7D","Lajedão","BA"));
        lista.add(new Cidade("7j4ppOJesXh60rsu2TuK","Lajedinho","BA"));
        lista.add(new Cidade("tX3vw00OXzVeR4ocX8mR","Lajedo Alto","BA"));
        lista.add(new Cidade("cn8ClXOMMFZmjbm3Tx87","Lajedo do Tabocal","BA"));
        lista.add(new Cidade("DFfSdUVpAfsM2BSvxmHN","Lamarão","BA"));
        lista.add(new Cidade("NgXjmGyw6Xt3zDwDJ3IX","Lamarão do Passe","BA"));
        lista.add(new Cidade("JPrD8EBhjbOmMf3mZpjZ","Lapão","BA"));
        lista.add(new Cidade("VznI6R1ojmYUZ0Fd8zHM","Largo","BA"));
        lista.add(new Cidade("JAe8adyOyx22C6qqUnLg","Lauro de Freitas","BA"));
        lista.add(new Cidade("qh1zR3O0sc6xgRJgh3Yb","Lençóis","BA"));
        lista.add(new Cidade("JeX7BvlEz7Q0grrXqEly","Licínio de Almeida","BA"));
        lista.add(new Cidade("AEUHhJdM3OiNFHpuWWXS","Limoeiro do Bom Viver","BA"));
        lista.add(new Cidade("g8p80Kd1MSYGKomWTwLx","Livramento de Nossa Senhora","BA"));
        lista.add(new Cidade("auvOVStqjKTs16SHy2wv","Lucaia","BA"));
        lista.add(new Cidade("iZZImDvDfZbLSut2E1f5","Luís Eduardo Magalhães","BA"));
        lista.add(new Cidade("2fHAv73ksYUmGl303uVj","Luís Viana","BA"));
        lista.add(new Cidade("GVR3b4gIduv3ZLTVsz5V","Lustosa","BA"));
        lista.add(new Cidade("WqSxcxaZIL4qJr9dxqvb","Macajuba","BA"));
        lista.add(new Cidade("q9JBNBAYtiDCIvJSzkaF","Macarani","BA"));
        lista.add(new Cidade("phCl1GrnKI9c5hk7Jw7y","Macaúbas","BA"));
        lista.add(new Cidade("UWhWML52JsDwnHhb32vo","Macururé","BA"));
        lista.add(new Cidade("Ak8zLMw2vWsTUhXrlpwY","Madeira","BA"));
        lista.add(new Cidade("a67TvY1thq2w3xn9zewI","Madre de Deus","BA"));
        lista.add(new Cidade("8cfU2schbaLM1wwqZPNm","Maetinga","BA"));
        lista.add(new Cidade("kkWJtDtxGjTPaHzOzras","Maiquinique","BA"));
        lista.add(new Cidade("FiNDjx2feVGA8InTxryA","Mairi","BA"));
        lista.add(new Cidade("U5izPKxPAShqTQowjBAY","Malhada","BA"));
        lista.add(new Cidade("sTab2KphXgcOyb6cHWbs","Malhada de Pedras","BA"));
        lista.add(new Cidade("OGIkbL8u0f1Q5RL6q4fa","Mandiroba","BA"));
        lista.add(new Cidade("SieD8Bg7fWoQarKJoaYz","Mangue Seco","BA"));
        lista.add(new Cidade("ZSizhRsinLItM8f1zl4q","Maniaçu","BA"));
        lista.add(new Cidade("1e5L1rlu6ipPdeQBErMu","Maniçoba","BA"));
        lista.add(new Cidade("LZKSgPbMlzcoab2uq6XB","Manoel Vitorino","BA"));
        lista.add(new Cidade("iswIppud60Or6iu4QMaD","Mansidão","BA"));
        lista.add(new Cidade("71ZDGUy2VGlq5ftpSguz","Mantiba","BA"));
        lista.add(new Cidade("JcSdToiqWqphMKkJNSdd","Mar Grande","BA"));
        lista.add(new Cidade("A1T3JrGGsjbjbeYvAt4M","Maracás","BA"));
        lista.add(new Cidade("KAj6NY9RDKROsvH78JkH","Maragogipe","BA"));
        lista.add(new Cidade("uW9KIrnyH83ISt9FL94J","Maragogipinho","BA"));
        lista.add(new Cidade("VU4Uvv0hASMhMrw0oc02","Maraú","BA"));
        lista.add(new Cidade("rVpycvnqNDBhjZoStN34","Marcionílio Souza","BA"));
        lista.add(new Cidade("BC3DZQ5DjYXtda386Zza","Marcolino Moura","BA"));
        lista.add(new Cidade("y8zDQc1ryliKL8fIzbeA","Maria Quitéria","BA"));
        lista.add(new Cidade("Rfr011Np4i4M1RXYAUAf","Maricoabo","BA"));
        lista.add(new Cidade("lx3LGGGctM4XiuOjv8pT","Mariquita","BA"));
        lista.add(new Cidade("eWfL9PBqjgOqY93nM658","Mascote","BA"));
        lista.add(new Cidade("6iR0PRC6Sqm1WyR8DolP","Massacara","BA"));
        lista.add(new Cidade("nAXvxOKx1PX3t3dnKGzd","Massaroca","BA"));
        lista.add(new Cidade("wLRNmochMdqYh5Dt9olH","Mata da Aliança","BA"));
        lista.add(new Cidade("swyNl3kdGhlwxXylqL6O","Mata de São João","BA"));
        lista.add(new Cidade("6dIz7sDnNBtNyze7Va6x","Mataripe","BA"));
        lista.add(new Cidade("65s52ODUorBuwGx8ciIn","Matina","BA"));
        lista.add(new Cidade("wTS61GCOAse00EtohKxY","Matinha","BA"));
        lista.add(new Cidade("3oAFGzp6nM70jgMGczR3","Medeiros Neto","BA"));
        lista.add(new Cidade("16tMrOZdh50ntZKRTD0T","Menino Jesus","BA"));
        lista.add(new Cidade("o1gj5Zljbpf8z0Ahofns","Miguel Calmon","BA"));
        lista.add(new Cidade("awPbpsmYVmKpPpjI9m0q","Milagres","BA"));
        lista.add(new Cidade("3lJpbqdRlBl9CHsbgzpF","Mimoso","BA"));
        lista.add(new Cidade("bar7qNjeeiFFsryTOaXj","Minas do Espírito Santo","BA"));
        lista.add(new Cidade("Mdx6QYFTEXDdaHrjvo1K","Minas do Mimoso","BA"));
        lista.add(new Cidade("9q68jz00DHv2bPEuObvt","Mirandela","BA"));
        lista.add(new Cidade("6tg1zhqHgpB1cx0sURLA","Miranga","BA"));
        lista.add(new Cidade("nr63EMyBcChshZYRHdyP","Mirangaba","BA"));
        lista.add(new Cidade("5Rq1ebS3NimVyl7SPvMP","Mirante","BA"));
        lista.add(new Cidade("DENobngETNLyUkadvZFp","Missão de Aricobé","BA"));
        lista.add(new Cidade("SZqsTM9pWBPbmzb3CGLn","Mocambo","BA"));
        lista.add(new Cidade("u54O73K1OZEsVuf0M6FS","Mogiquiçaba","BA"));
        lista.add(new Cidade("ArP6q5uQIAOsdb5TNHvg","Monte Branco","BA"));
        lista.add(new Cidade("LzJQipmOsFELwb3AAIix","Monte Cruzeiro","BA"));
        lista.add(new Cidade("dBYClkO8plpTfhs0f3u4","Monte Gordo","BA"));
        lista.add(new Cidade("zcbrw8pOYKOkfx3mTCQx","Monte Recôncavo","BA"));
        lista.add(new Cidade("ZMWIt4fNmyRDSrQulUNl","Monte Santo","BA"));
        lista.add(new Cidade("URc2iJvS2UoLofn764ct","Morpará","BA"));
        lista.add(new Cidade("Rz18SS6mALq2Xoe9NBA5","Morrinhos","BA"));
        lista.add(new Cidade("SzAYpgN40SYOSLzMkdDA","Morro das Flores","BA"));
        lista.add(new Cidade("PPJE53h5rIP0x8GUmu6P","Morro de São Paulo","BA"));
        lista.add(new Cidade("n6pGIEg3ZuFwDoJjE8Xc","Morro do Chapéu","BA"));
        lista.add(new Cidade("G993Y0BL0MDwqOU6HfeR","Mortugaba","BA"));
        lista.add(new Cidade("iHNVAT9b5gBNHDx33l7j","Mucugê","BA"));
        lista.add(new Cidade("dKi5ipvayH1giJ8T8qiz","Mucuri","BA"));
        lista.add(new Cidade("okQsuMxr38uzr5UQecK0","Mulungu do Morro","BA"));
        lista.add(new Cidade("Z5Eq8yCwv7lSEYu7eHRR","Mundo Novo","BA"));
        lista.add(new Cidade("pl7p8BGzNTMp1EKvb0rN","Muniz Ferreira","BA"));
        lista.add(new Cidade("pMjzaFj3vGU0toFGGf8w","Muquém de São Francisco","BA"));
        lista.add(new Cidade("bXHzSTgLWCuwcUAnLPn8","Muritiba","BA"));
        lista.add(new Cidade("e11BWBEeL5C1eH2KRmod","Mutas","BA"));
        lista.add(new Cidade("4TzDGhbAHEhI3oply7s9","Mutuípe","BA"));
        lista.add(new Cidade("bNhOrjQgRs6z7PQmLe5p","Nagé","BA"));
        lista.add(new Cidade("kz4g0bcuSU2S2K6Mzeg4","Narandiba","BA"));
        lista.add(new Cidade("sRVRKvUv1i6d3yi07Vmp","Nazaré","BA"));
        lista.add(new Cidade("BAQlE8pFjmNWkVyw9FC5","Nilo Peçanha","BA"));
        lista.add(new Cidade("OS6KLWHcgOWvyTByTQ3B","Nordestina","BA"));
        lista.add(new Cidade("lQkCjiszF3gt8za63iVt","Nova Alegria","BA"));
        lista.add(new Cidade("LdxMwVD7VQrNEwDnhTTx","Nova Brasília","BA"));
        lista.add(new Cidade("SteStRhwKJxpOvd1UT8J","Nova Canaã","BA"));
        lista.add(new Cidade("Ogb4nSUbq17DJsnSBVMm","Nova Fátima","BA"));
        lista.add(new Cidade("wyik1bmBt27Wtljlpbho","Nova Ibiá","BA"));
        lista.add(new Cidade("GPLrCeLZ91tqvzExCoTG","Nova Itaipê","BA"));
        lista.add(new Cidade("zgFGETiQQVA56S6HBFGR","Nova Itarana","BA"));
        lista.add(new Cidade("XRG00H1sJutN10oiCJHt","Nova Lídice","BA"));
        lista.add(new Cidade("SeTk5hcIzppHwpoyWgs7","Nova Redenção","BA"));
        lista.add(new Cidade("aEs5Jx2ydF2KWEeJf3N5","Nova Soure","BA"));
        lista.add(new Cidade("70lwvETUGwqdKthoeJyu","Nova Viçosa","BA"));
        lista.add(new Cidade("IiQkp92HZUwn0rgLSgiw","Novo Acre","BA"));
        lista.add(new Cidade("uVVEdafbWhch99YTwdFU","Novo Horizonte","BA"));
        lista.add(new Cidade("0zctDyCiIriI1K76Q2MJ","Novo Triunfo","BA"));
        lista.add(new Cidade("868JyMwymOZmCd59jjUz","Núcleo Residencial Pilar","BA"));
        lista.add(new Cidade("q9LYxPANT5YLMwViNo4Z","Nuguaçu","BA"));
        lista.add(new Cidade("5Vh2eX0MFs8EiQS0ODf9","Olhos D'Água do Seco","BA"));
        lista.add(new Cidade("vSonPVKl5cPDDyveSwQq","Olhos D'Água do Serafim","BA"));
        lista.add(new Cidade("dPXwm35aN5tLyAd0Hxhu","Olindina","BA"));
        lista.add(new Cidade("xJeVnTRSmm9YPY7Vw0fs","Oliveira dos Brejinhos","BA"));
        lista.add(new Cidade("MK2qogJj7kWjsWJh4NFt","Olivença","BA"));
        lista.add(new Cidade("KmzvGxMhcm7ljNskldda","Onha","BA"));
        lista.add(new Cidade("Ohq8LKWgZnHfQn3ReNtx","Oriente Novo","BA"));
        lista.add(new Cidade("ggRU1SknqRszlOjQWbOH","Ouricana","BA"));
        lista.add(new Cidade("UbhumoiwUOj1CxtnvgVv","Ouriçangas","BA"));
        lista.add(new Cidade("QJojt3t3LsyPuu2QY8ea","Ouricuri do Ouro","BA"));
        lista.add(new Cidade("sEANcwMZuPby16Bg9ytF","Ourolândia","BA"));
        lista.add(new Cidade("ECRSLC8i28mTzGskmSlu","Outeiro Redondo","BA"));
        lista.add(new Cidade("br6VrtuMiccHAqjfo0l0","Paiol","BA"));
        lista.add(new Cidade("kO73rE0WN3c7mPErx1qV","Pajeú do Vento","BA"));
        lista.add(new Cidade("EjaX6Z6j9MV8CNLMH9yb","Palame","BA"));
        lista.add(new Cidade("9WGb11Q5A4NXJUvYi3NE","Palmares","BA"));
        lista.add(new Cidade("vhvFuEkYy5Xal6ibRw1X","Palmas de Monte Alto","BA"));
        lista.add(new Cidade("sHaAweEQdl3PrU8VCPRh","Palmeiras","BA"));
        lista.add(new Cidade("TWjf9FsaG3j1Tp0WhexP","Parafuso","BA"));
        lista.add(new Cidade("1gLpSLsgGQ9pOae2YvKg","Paramirim","BA"));
        lista.add(new Cidade("6OGTfh51WpX3OHTIFqUT","Parateca","BA"));
        lista.add(new Cidade("v6GsfwThGLtrG15cH8TC","Paratinga","BA"));
        lista.add(new Cidade("uDX01VZfZ5s0jLOOcO9t","Paripiranga","BA"));
        lista.add(new Cidade("zVKwoNMxBzdL3z3zePYv","Passagem dos Teixeiras","BA"));
        lista.add(new Cidade("RY41dGSoXJI0bwpKfslb","Passé","BA"));
        lista.add(new Cidade("hbUaeFB2WnMEEmxvHcjS","Pataíba","BA"));
        lista.add(new Cidade("xr002R7u00bUoKOGyH90","Patamuté","BA"));
        lista.add(new Cidade("nSc1ZjXuazwU7eWO6qmN","Pau a Pique","BA"));
        lista.add(new Cidade("WbxeMp1q0QuFVNFJqVHw","Pau Brasil","BA"));
        lista.add(new Cidade("w0D3aV2gfsOdVhvjUzkM","Paulo Afonso","BA"));
        lista.add(new Cidade("EI2pWT1yszCJxHooniOO","Pé de Serra","BA"));
        lista.add(new Cidade("r07wLSvQMYo9YgXlUhPB","Pedra Alta","BA"));
        lista.add(new Cidade("RrigbYxThFfZOTjvts8H","Pedrão","BA"));
        lista.add(new Cidade("UNwMVXFXR5nrqGfQxbSZ","Pedras Altas do Mirim","BA"));
        lista.add(new Cidade("cMyjyAUUSO2cQQ0Ks3G5","Pedro Alexandre","BA"));
        lista.add(new Cidade("SY6BDBbKO6JnrNzgzmwR","Peixe","BA"));
        lista.add(new Cidade("dG2OyFuCagOp5bDTxUho","Petim","BA"));
        lista.add(new Cidade("HE5qnmWDFq3oZwJRKcNE","Piabanha","BA"));
        lista.add(new Cidade("yxN6fhSX0FnLDlU9dP82","Piatã","BA"));
        lista.add(new Cidade("ioBZ89Lra7QCCeimmTbp","Piçarrão","BA"));
        lista.add(new Cidade("95bciIRQZ5lZfRzOcAEE","Pilão Arcado","BA"));
        lista.add(new Cidade("e9KlGXGJ2rfACutTS2PZ","Pilões","BA"));
        lista.add(new Cidade("eKvwYohxMHMV82TaxWam","Pimenteira","BA"));
        lista.add(new Cidade("Oohi4GJ81KWhCKfmWp4X","Pindaí","BA"));
        lista.add(new Cidade("lziMnBbmYPrXc339uN1p","Pindobaçu","BA"));
        lista.add(new Cidade("8tcVi8W8ZNftGM4Vtbu2","Pinga Fogo","BA"));
        lista.add(new Cidade("UuiiTPqe7nMkED6cJNOT","Pinhões","BA"));
        lista.add(new Cidade("IwoWpfEN7VrkXTnY83iC","Pintadas","BA"));
        lista.add(new Cidade("KWKYz1rT4bdh9m9D9cWQ","Piragi","BA"));
        lista.add(new Cidade("d6L26LnNdinuCwhym8v4","Piraí do Norte","BA"));
        lista.add(new Cidade("MXawYib4hcMPQUr3EGWL","Pirajá","BA"));
        lista.add(new Cidade("JBHLMGEKBpJ6J7peZPhV","Pirajuia","BA"));
        lista.add(new Cidade("Isawc0AhMOU9DKc1Eeki","Piri","BA"));
        lista.add(new Cidade("SlQMQxdi4H52MKZteDYy","Piripá","BA"));
        lista.add(new Cidade("yCCDvBwzYihUz0gA328N","Piritiba","BA"));
        lista.add(new Cidade("fng72OdM3kzW8LPxvalN","Pituba","BA"));
        lista.add(new Cidade("L452zvl3HeaGGU7KmjEN","Planaltino","BA"));
        lista.add(new Cidade("tidsVPpVEinADyiDmx6z","Planalto","BA"));
        lista.add(new Cidade("LIiYDTG1rdh1MfJ1kngU","Poço Central","BA"));
        lista.add(new Cidade("LRS349rrVNw1iRt6yTV9","Poço de Fora","BA"));
        lista.add(new Cidade("MhehYaMSAXzKscD8fd7u","Poções","BA"));
        lista.add(new Cidade("S0XCqqDLlTRYwarBZANh","Poços","BA"));
        lista.add(new Cidade("a3WZveW5qkq1jmEg4Yom","Pojuca","BA"));
        lista.add(new Cidade("IkJUMllNpyRLjyVekmqy","Polo Petroquímico de Camaçari","BA"));
        lista.add(new Cidade("4Kg5kEKfftrikiVSixnp","Ponta da Areia","BA"));
        lista.add(new Cidade("iHCLiy5pu38fkkanizvV","Ponto Novo","BA"));
        lista.add(new Cidade("wymplCKdzGqPQYO17LRZ","Porto Novo","BA"));
        lista.add(new Cidade("NASlFWK79EtaD3A1e3VC","Porto Sauípe","BA"));
        lista.add(new Cidade("vrnIvP5Ou1dmoF11WVuM","Porto Seguro","BA"));
        lista.add(new Cidade("ciFyGW1vnjqP5UMwUnuv","Posto da Mata","BA"));
        lista.add(new Cidade("S4LtF1JgmcpbvM0sKpdx","Potiraguá","BA"));
        lista.add(new Cidade("p67dmrfQC9Eqrczl5Rs2","Poxim do Sul","BA"));
        lista.add(new Cidade("tWKa27UUgpfYSpX7lAKa","Prado","BA"));
        lista.add(new Cidade("tnokaLs1gNmiJMLpM9uy","Pradoso","BA"));
        lista.add(new Cidade("lM1ayepfSxFe6fS0dW1b","Praia do Forte","BA"));
        lista.add(new Cidade("ui1b2cKGNvUhypsXFYj6","Presidente Dutra","BA"));
        lista.add(new Cidade("wPnldwo5ZLSphsrGSHqL","Presidente Jânio Quadros","BA"));
        lista.add(new Cidade("CwygpPVoTIAXg4uo08Tx","Presidente Tancredo Neves","BA"));
        lista.add(new Cidade("SsjEJGLvIpELHmO7sBGA","Prevenido","BA"));
        lista.add(new Cidade("OinVvcUKW4yHVaPCUcUA","Quaraçu","BA"));
        lista.add(new Cidade("Lc08dmUJCeJySDKylbWa","Queimadas","BA"));
        lista.add(new Cidade("9NIqf5FVayL5E6sZolQf","Quijingue","BA"));
        lista.add(new Cidade("AOeXDK16olrbCo5ajg5M","Quixabá","BA"));
        lista.add(new Cidade("ZZg61Q3k8eo4H4ccdC7q","Quixabeira","BA"));
        lista.add(new Cidade("nPVsfxfmq8JXpXf8ts1J","Rafael Jambeiro","BA"));
        lista.add(new Cidade("T2I8ze0mqIRUXpOOM9TM","Rancho das Mães","BA"));
        lista.add(new Cidade("5BTss74uemQdjkUxXkWl","Raspador","BA"));
        lista.add(new Cidade("mxrw2z9itMCfVFs3wJg0","Recife","BA"));
        lista.add(new Cidade("H8VeY5N1BPe57K5kenuQ","Remanso","BA"));
        lista.add(new Cidade("AQusXrtdTXoTIan2iLxL","Remédios","BA"));
        lista.add(new Cidade("2tOF5ny9ehJEzPFYcXwA","Retirolândia","BA"));
        lista.add(new Cidade("asR3CVIjtrdTMxlWp9Zq","Riachão das Neves","BA"));
        lista.add(new Cidade("vQV0yAy071963MOjgAYt","Riachão do Jacuípe","BA"));
        lista.add(new Cidade("BUQMY2WCJHMegYFwk3Uy","Riachão do Utinga","BA"));
        lista.add(new Cidade("hBpAfgmW7pvLjNOoh8tK","Riacho da Guia","BA"));
        lista.add(new Cidade("43YrejJwJgZYuHbw6K4r","Riacho de Santana","BA"));
        lista.add(new Cidade("QP86EJjMaTu7KQKaC7fC","Riacho Seco","BA"));
        lista.add(new Cidade("kIQt1hSovjpfYjCmmQid","Ribeira do Amparo","BA"));
        lista.add(new Cidade("OgCWwO2uqK0j5aYFQPvt","Ribeira do Pombal","BA"));
        lista.add(new Cidade("24NuIHrrCLqPs5Irwzjn","Ribeirão do Largo","BA"));
        lista.add(new Cidade("lYCBZUHU0QzjkvRmXo3r","Ribeirão do Salto","BA"));
        lista.add(new Cidade("qjZD9OOQacJqkI2o0Ynm","Rio da Dona","BA"));
        lista.add(new Cidade("FUcgunyS0E7S5HIE2Ja3","Rio de Contas","BA"));
        lista.add(new Cidade("4yC068sfTm7Q8Pr9QLST","Rio do Antônio","BA"));
        lista.add(new Cidade("MWqN9AoxwqPr8XaqpEUU","Rio do Braço","BA"));
        lista.add(new Cidade("LZSHsWCQeMTcwvYITo7a","Rio do Meio","BA"));
        lista.add(new Cidade("RNJkqXv45m3TImKQeOlf","Rio do Pires","BA"));
        lista.add(new Cidade("MrUSdwhbZGrC8HyIOebO","Rio Fundo","BA"));
        lista.add(new Cidade("hM6Tv5UfpvMAoRwRUhb3","Rio Real","BA"));
        lista.add(new Cidade("TlnSPidEIzHav1dwLY9v","Roda Velha","BA"));
        lista.add(new Cidade("884kl5eQVJ3EX24EZaXM","Rodelas","BA"));
        lista.add(new Cidade("MtgJVHQOCtJtuRaf25KE","Rosário","BA"));
        lista.add(new Cidade("9SO5vcalcrAA884hd8Ci","Ruy Barbosa","BA"));
        lista.add(new Cidade("urQ7g3WlVOs75ysGV36g","Saldanha","BA"));
        lista.add(new Cidade("RtafCaxaTcHwvjtczUtZ","Salgadália","BA"));
        lista.add(new Cidade("FNHUQbdH74FRmHY1rnp7","Salinas da Margarida","BA"));
        lista.add(new Cidade("cXpmjj11kt53HSEiOlad","Salobrinho","BA"));
        lista.add(new Cidade("fcbvjp2eWcmdmvdhdPy0","Salobro","BA"));
        lista.add(new Cidade("ePmXhe5pYd5rPyaLbhyd","Salvador","BA"));
        lista.add(new Cidade("vmOelNmh021EAmBeuniZ","Sambaíba","BA"));
        lista.add(new Cidade("GBaWsRB3WpvwbrOZYDSq","Santa Bárbara","BA"));
        lista.add(new Cidade("mIdqTKYueX4DlLxnIVju","Santa Brígida","BA"));
        lista.add(new Cidade("mdq1OllTWXnAEQIMJgsN","Santa Cruz Cabrália","BA"));
        lista.add(new Cidade("wUovYNsNYJWhAtRoEr7F","Santa Cruz da Vitória","BA"));
        lista.add(new Cidade("DGyatrqxJrpY0Y8YQBp3","Santa Inês","BA"));
        lista.add(new Cidade("ebNibw4enfCCUjEslnWG","Santa Luzia","BA"));
        lista.add(new Cidade("cnlZheBGiw8zQ9wYn4y1","Santa Maria da Vitória","BA"));
        lista.add(new Cidade("duJm3WCGzNhhnRHoNqQR","Santa Rita de Cássia","BA"));
        lista.add(new Cidade("1kdRJVJMa3Ej1JdswoxP","Santa Teresinha","BA"));
        lista.add(new Cidade("JUF7CNeW8ZZUYDakvN0m","Santaluz","BA"));
        lista.add(new Cidade("79pdVyzE8xeDLHYxMkix","Santana","BA"));
        lista.add(new Cidade("EGT6lbvfqwJhG2Ono65H","Santana do Sobrado","BA"));
        lista.add(new Cidade("qZtVhFFw3srVLKmnJakK","Santanópolis","BA"));
        lista.add(new Cidade("CKMmdPYPhQVUFbMdSHX8","Santiago do Iguapé","BA"));
        lista.add(new Cidade("IGIZVQOimVUIUu7IVCXi","Santo Amaro","BA"));
        lista.add(new Cidade("ADkZ8TPj4yDO27XzGqPG","Santo Antônio","BA"));
        lista.add(new Cidade("fQxODDCLilJEaaXZCm0d","Santo Antônio de Barcelona","BA"));
        lista.add(new Cidade("E4HVwN3TGTTvec9PZOny","Santo Antônio de Jesus","BA"));
        lista.add(new Cidade("ng5bDosv2xTDE6TbV2Gt","Santo Estevão","BA"));
        lista.add(new Cidade("IoAEYqDpEvNs8BisJcI2","Santo Inácio","BA"));
        lista.add(new Cidade("b1YiQD0zYPeqecvcl5kI","São Desidério","BA"));
        lista.add(new Cidade("urKr0bxNGeBuqnOW74Na","São Domingos","BA"));
        lista.add(new Cidade("0E4chI3cl2W4JWPw3Gb2","São Felipe","BA"));
        lista.add(new Cidade("krxeQDrWT8fmz3PNDI0t","São Félix","BA"));
        lista.add(new Cidade("VzTOcKLQIH7H8yYZoYdC","São Félix do Coribe","BA"));
        lista.add(new Cidade("lvQcCGPak7GXxfBaMd88","São Francisco do Conde","BA"));
        lista.add(new Cidade("u3TVy9UNIWhUBYSblFar","São Gabriel","BA"));
        lista.add(new Cidade("TH7MDGRQ9IG2EZdrdRh5","São Gonçalo dos Campos","BA"));
        lista.add(new Cidade("Ppo1JSzv9ifkUwtBwYWr","São João","BA"));
        lista.add(new Cidade("GL2yhFak4aWcbF2FL3k1","São João da Fortaleza","BA"));
        lista.add(new Cidade("alw8TKUXV8S5ZOZXAmZu","São João da Vitória","BA"));
        lista.add(new Cidade("VWSaj1N0KCJmlxrlYFHz","São José da Vitória","BA"));
        lista.add(new Cidade("BirI7AlKeU8coQWWHRXu","São José do Colônia","BA"));
        lista.add(new Cidade("oxm1oeJ1ssws7h2S2qNC","São José do Jacuípe","BA"));
        lista.add(new Cidade("0aN1H7wFC2nIUFNeasLv","São José do Prado","BA"));
        lista.add(new Cidade("GrA2ZYWm9KeupzkH7JSp","São José do Rio Grande","BA"));
        lista.add(new Cidade("Sv6kRKBwLcrfGxuVcjnH","São Miguel das Matas","BA"));
        lista.add(new Cidade("iYGu7DQ4lEFZTloSJaSj","São Paulinho","BA"));
        lista.add(new Cidade("eq3twTiaOEV4NPj7NV2d","São Roque do Paraguaçu","BA"));
        lista.add(new Cidade("MiHkgf930QNWkdE1UZfZ","São Sebastião","BA"));
        lista.add(new Cidade("ckwtc5ISP6uDTAH3i1E5","São Sebastião do Passe","BA"));
        lista.add(new Cidade("KOics9wyiWz6fTtsrsyx","São Timóteo","BA"));
        lista.add(new Cidade("aCmWyb8A86cMILDDXr7q","Sapeaçu","BA"));
        lista.add(new Cidade("ZFtv7PxvwDNTmPvublss","Sátiro Dias","BA"));
        lista.add(new Cidade("zeVXJ18LMQXXEPWNXUwb","Saubara","BA"));
        lista.add(new Cidade("5ScTeGurUOMAA7XoobCw","Saudável","BA"));
        lista.add(new Cidade("uuqcXZSX72wtceo5oEfN","Saúde","BA"));
        lista.add(new Cidade("s64800Gv2cVcEcwhlmHk","Seabra","BA"));
        lista.add(new Cidade("BBI2jBxCHT6Kg63bFvrr","Sebastião Laranjeiras","BA"));
        lista.add(new Cidade("FeblRDhqpRYseSZACe79","Senhor do Bonfim","BA"));
        lista.add(new Cidade("fcD4u5jxxZ5MvmqDfnpK","Sento Sé","BA"));
        lista.add(new Cidade("hGu0dZCjJ0D4rtTi3tqB","Sergi","BA"));
        lista.add(new Cidade("vRA0antAJgufc6lvh6sB","Serra da Canabrava","BA"));
        lista.add(new Cidade("aT2qIH7kviUKtlohJeBo","Serra do CEM","BA"));
        lista.add(new Cidade("rfu14EwzFbKwYamEjCPT","Serra do Ramalho","BA"));
        lista.add(new Cidade("OhqTIjJCCAjGahLfjpln","Serra do São Francisco","BA"));
        lista.add(new Cidade("kO0zbiw4lBlRKKchyAiz","Serra Dourada","BA"));
        lista.add(new Cidade("Ww9ww4apNxb01ykfiGad","Serra Grande","BA"));
        lista.add(new Cidade("dtyIk8ieKiQ2REfUsDFt","Serra Preta","BA"));
        lista.add(new Cidade("UZ7SJ9BuMtGYwWQwu8cE","Serrana","BA"));
        lista.add(new Cidade("KxDqoTO9Bjsgs7f0TRy0","Serrinha","BA"));
        lista.add(new Cidade("DWuNa29NliLuxP6ZLEhQ","Serrolândia","BA"));
        lista.add(new Cidade("8G6C337nue4T2QWxV8zH","Simões Filho","BA"));
        lista.add(new Cidade("B7gwqSjPw6lZRNTVjFeL","Sítio da Baraúna","BA"));
        lista.add(new Cidade("dIQhWF8Xs1iSqOQYw083","Sítio do Mato","BA"));
        lista.add(new Cidade("RCSzmW7squJn8XFd1mAK","Sítio do Meio","BA"));
        lista.add(new Cidade("zlshj4ZWU5g9KK0f6w8H","Sítio do Quinto","BA"));
        lista.add(new Cidade("qiEWIs97Ro8DSh5L46XD","Sítio Grande","BA"));
        lista.add(new Cidade("HOlD5pEa2McENIq93FAL","Sítio Novo","BA"));
        lista.add(new Cidade("0ryiI0pqEnfsmV0QOud6","Soares","BA"));
        lista.add(new Cidade("fDRZVqkXOqfAGsXxJmag","Sobradinho","BA"));
        lista.add(new Cidade("xmIEq4Eev8p0azox8VMy","Souto Soares","BA"));
        lista.add(new Cidade("nZ1Afjd7G6YwRtPTKwid","Subaúma","BA"));
        lista.add(new Cidade("A021RbZ8kKM816EjhoXz","Sussuarana","BA"));
        lista.add(new Cidade("ORp3mToO31TNdfnxMnu8","Tabocas do Brejo Velho","BA"));
        lista.add(new Cidade("uBxkbSCCOQcegJ4bRLlM","Taboleiro do Castro","BA"));
        lista.add(new Cidade("u0gVA3thUDQwYjyRIPAL","Taboquinhas","BA"));
        lista.add(new Cidade("WAoPZAX1uzNt55Asjp6S","Taguá","BA"));
        lista.add(new Cidade("i5F6FRXih9iSCE50MQkY","Tamburil","BA"));
        lista.add(new Cidade("IoA8bNsVIqjvx7DCSUnv","Tanhaçu","BA"));
        lista.add(new Cidade("V2emtVcv0tOpUObS2NnA","Tanque Novo","BA"));
        lista.add(new Cidade("yTf4f6rxFNFJtSz9BwG1","Tanquinho","BA"));
        lista.add(new Cidade("eK6smjfPH5ZlRTwJTso1","Tanquinho do Poço","BA"));
        lista.add(new Cidade("V4vNqkQNhONGbJGzPuSu","Taperoá","BA"));
        lista.add(new Cidade("iCPCgeQPa0IqRkNvBM1b","Tapiraípe","BA"));
        lista.add(new Cidade("xk8iyEUMS634It60q3gK","Tapirama","BA"));
        lista.add(new Cidade("vTtxLEKa1yILDhGhobgK","Tapiramutá","BA"));
        lista.add(new Cidade("TNqpDs7YXxlE4SaC9FJz","Tapiranga","BA"));
        lista.add(new Cidade("XucxNs5KsgLzw3gaNrfr","Tapúia","BA"));
        lista.add(new Cidade("4NTxJ7wrdgsdJMDEvB7s","Taquarendi","BA"));
        lista.add(new Cidade("nAWJtOGQFD9HSahGxFVE","Taquarinha","BA"));
        lista.add(new Cidade("vQn849veezzs7DBzc9CS","Tartaruga","BA"));
        lista.add(new Cidade("sKQO3oiA9sfIV4r3oJBr","Tauapé","BA"));
        lista.add(new Cidade("mDkqZl0ToFkoBuD6x8uq","Teixeira de Freitas","BA"));
        lista.add(new Cidade("mA9pJOZkUiGhcPej70it","Teodoro Sampaio","BA"));
        lista.add(new Cidade("EYhKD3nrMbX8rxdlcvcs","Teofilândia","BA"));
        lista.add(new Cidade("y64RenIGW2oAKgEQsJis","Teolândia","BA"));
        lista.add(new Cidade("OQaHDMdbpc4id57VDwDb","Terra Nova","BA"));
        lista.add(new Cidade("Ws0s5fzfaWHlvM0MRbIT","Tijuaçú","BA"));
        lista.add(new Cidade("ABPuH3qnhwt9OqgVkArr","Tiquaruçu","BA"));
        lista.add(new Cidade("KYk6vRjv9T39CfQYUeSs","Tracupa","BA"));
        lista.add(new Cidade("Bf4dLcKMFwFUnk3AngQF","Trancoso","BA"));
        lista.add(new Cidade("bAsMJucYNtx8Z7fN8Mxl","Tremedal","BA"));
        lista.add(new Cidade("tLpZmczvGxi3cazesooY","Triunfo do Sincorá","BA"));
        lista.add(new Cidade("6mR1JBrooKayEvrbdyF6","Tucano","BA"));
        lista.add(new Cidade("CE5doMy5ho8YHd0iR3u1","Uauá","BA"));
        lista.add(new Cidade("GAZfslCD78rH0nnOA0ke","Ubaíra","BA"));
        lista.add(new Cidade("nH0CF1tFUwtm5FsfhVVe","Ubaitaba","BA"));
        lista.add(new Cidade("CyJSvux1su6ZWlzGlIj2","Ubatã","BA"));
        lista.add(new Cidade("OtUUOPOOueKALtAIz6Uj","Ubiracaba","BA"));
        lista.add(new Cidade("ZWEAG37ArmcaMtZakiNw","Ubiraitá","BA"));
        lista.add(new Cidade("VfS7cPUztLuahEciLyLs","Uibaí","BA"));
        lista.add(new Cidade("MR451Gc16iVIfM74S0fr","Umburanas","BA"));
        lista.add(new Cidade("DwVcZi3xN1YGsDdj5XHx","Umbuzeiro","BA"));
        lista.add(new Cidade("nVFcA8Jb2SsW1eCrAYsJ","Una","BA"));
        lista.add(new Cidade("ohWC6Gg4Vycdnk0OUY0u","Urandi","BA"));
        lista.add(new Cidade("VBAgZ3Mczhd5IzSRdAeJ","Uruçuca","BA"));
        lista.add(new Cidade("G1Rej7IjEZeTkcHaHGsJ","Utinga","BA"));
        lista.add(new Cidade("P9cBx3YV4YXCWnK4Betf","Vale Verde","BA"));
        lista.add(new Cidade("K8Z9s9lJ7LCe9AvlFQ9k","Valença","BA"));
        lista.add(new Cidade("xauHNPrC0j2S3iJde4sD","Valente","BA"));
        lista.add(new Cidade("zOoOK4VdGDkbdcxdtLP6","Valilândia","BA"));
        lista.add(new Cidade("g4OvNw6AzXBcdYdURNrK","Várzea da Roça","BA"));
        lista.add(new Cidade("H1th16Ik6YElk2Bi6AWe","Várzea do Caldas","BA"));
        lista.add(new Cidade("0wZiXGmjFcD8kjcHMOi7","Várzea do Cerco","BA"));
        lista.add(new Cidade("0b34L3FnWDq0ummNHcCk","Várzea do Poço","BA"));
        lista.add(new Cidade("BbjheuyX0rXsLrxIeZ1g","Varzea Grande","BA"));
        lista.add(new Cidade("04mzKpvK3zpfwqMOFC01","Várzea Nova","BA"));
        lista.add(new Cidade("zxKFsHsghkZwgltJeVCH","Várzeas","BA"));
        lista.add(new Cidade("VodwezFjGauLUapy0YE4","Varzedo","BA"));
        lista.add(new Cidade("06RcJ9QndwNSeUwysO4E","Velha Boipeba","BA"));
        lista.add(new Cidade("B9XgbI4XBeG5IaiXMsvU","Ventura","BA"));
        lista.add(new Cidade("J2tyIUpoWG3EPp7ecxUH","Vera Cruz","BA"));
        lista.add(new Cidade("SyRDMYo15DsQn9Wbahqj","Vereda","BA"));
        lista.add(new Cidade("ZLYNH8KsR8WVpbdB0aT7","Veredinha","BA"));
        lista.add(new Cidade("lAeEj2VWiphuT3YtpBa8","Vila do Café","BA"));
        lista.add(new Cidade("s5GLwMTgwmTA7R0jKHcJ","Vitória da Conquista","BA"));
        lista.add(new Cidade("39ClV0upl6i9AIymKwC2","Volta da Serra","BA"));
        lista.add(new Cidade("x2aOrhA9HiT2T4SZyEwf","Volta Grande","BA"));
        lista.add(new Cidade("puritZLBJfqOkyEPFWbL","Wagner","BA"));
        lista.add(new Cidade("HpfTpTxvzkO3hAcnL0l1","Wanderley","BA"));
        lista.add(new Cidade("2mxnUOOhvemi2uIaydAz","Wenceslau Guimarães","BA"));
        lista.add(new Cidade("ReQBtWWhZE7QJmYmdxCI","Xique-Xique","BA"));
        return lista;
    }
}
