package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class BA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Abadia", "BA"));
        lista.add(new Cidade("", "Abaíra", "BA"));
        lista.add(new Cidade("", "Abaré", "BA"));
        lista.add(new Cidade("", "Abelhas", "BA"));
        lista.add(new Cidade("", "Abóbora", "BA"));
        lista.add(new Cidade("", "Abrantes", "BA"));
        lista.add(new Cidade("", "Acajutiba", "BA"));
        lista.add(new Cidade("", "Açu da Torre", "BA"));
        lista.add(new Cidade("", "Açudina", "BA"));
        lista.add(new Cidade("", "Acupe", "BA"));
        lista.add(new Cidade("", "Adro de São Gonçalo", "BA"));
        lista.add(new Cidade("", "Adustina", "BA"));
        lista.add(new Cidade("", "Afligidos", "BA"));
        lista.add(new Cidade("", "Afrânio Peixoto", "BA"));
        lista.add(new Cidade("", "Água Doce", "BA"));
        lista.add(new Cidade("", "Água Fria", "BA"));
        lista.add(new Cidade("", "Águas do Paulista", "BA"));
        lista.add(new Cidade("", "Aiquara", "BA"));
        lista.add(new Cidade("", "Alagoinhas", "BA"));
        lista.add(new Cidade("", "Alcobaça", "BA"));
        lista.add(new Cidade("", "Alegre", "BA"));
        lista.add(new Cidade("", "Algodão", "BA"));
        lista.add(new Cidade("", "Algodões", "BA"));
        lista.add(new Cidade("", "Almadina", "BA"));
        lista.add(new Cidade("", "Alto Bonito", "BA"));
        lista.add(new Cidade("", "Amado Bahia", "BA"));
        lista.add(new Cidade("", "Amaniú", "BA"));
        lista.add(new Cidade("", "Amargosa", "BA"));
        lista.add(new Cidade("", "Amélia Rodrigues", "BA"));
        lista.add(new Cidade("", "América Dourada", "BA"));
        lista.add(new Cidade("", "Américo Alves", "BA"));
        lista.add(new Cidade("", "Anagé", "BA"));
        lista.add(new Cidade("", "Andaraí", "BA"));
        lista.add(new Cidade("", "Andorinha", "BA"));
        lista.add(new Cidade("", "Angical", "BA"));
        lista.add(new Cidade("", "Angico", "BA"));
        lista.add(new Cidade("", "Anguera", "BA"));
        lista.add(new Cidade("", "Antarí", "BA"));
        lista.add(new Cidade("", "Antas", "BA"));
        lista.add(new Cidade("", "Antônio Cardoso", "BA"));
        lista.add(new Cidade("", "Antônio Gonçalves", "BA"));
        lista.add(new Cidade("", "Aporá", "BA"));
        lista.add(new Cidade("", "Apuarema", "BA"));
        lista.add(new Cidade("", "Araçás", "BA"));
        lista.add(new Cidade("", "Aracatu", "BA"));
        lista.add(new Cidade("", "Araci", "BA"));
        lista.add(new Cidade("", "Aramari", "BA"));
        lista.add(new Cidade("", "Arapiranga", "BA"));
        lista.add(new Cidade("", "Arataca", "BA"));
        lista.add(new Cidade("", "Aratuípe", "BA"));
        lista.add(new Cidade("", "Areia Branca", "BA"));
        lista.add(new Cidade("", "Areias", "BA"));
        lista.add(new Cidade("", "Arembepe", "BA"));
        lista.add(new Cidade("", "Argoim", "BA"));
        lista.add(new Cidade("", "Argolo", "BA"));
        lista.add(new Cidade("", "Aribice", "BA"));
        lista.add(new Cidade("", "Aritaguá", "BA"));
        lista.add(new Cidade("", "Arraial D'Ajuda", "BA"));
        lista.add(new Cidade("", "Aurelino Leal", "BA"));
        lista.add(new Cidade("", "Baianópolis", "BA"));
        lista.add(new Cidade("", "Baixa do Palmeira", "BA"));
        lista.add(new Cidade("", "Baixa Grande", "BA"));
        lista.add(new Cidade("", "Baixão", "BA"));
        lista.add(new Cidade("", "Baixinha", "BA"));
        lista.add(new Cidade("", "Baluarte", "BA"));
        lista.add(new Cidade("", "Bananeiras", "BA"));
        lista.add(new Cidade("", "Banco Central", "BA"));
        lista.add(new Cidade("", "Banco da Vitória", "BA"));
        lista.add(new Cidade("", "Bandeira do Almada", "BA"));
        lista.add(new Cidade("", "Bandeira do Colônia", "BA"));
        lista.add(new Cidade("", "Bandiaçu", "BA"));
        lista.add(new Cidade("", "Banzaê", "BA"));
        lista.add(new Cidade("", "Baraúnas", "BA"));
        lista.add(new Cidade("", "Barcelos do Sul", "BA"));
        lista.add(new Cidade("", "Barra", "BA"));
        lista.add(new Cidade("", "Barra Avenida", "BA"));
        lista.add(new Cidade("", "Barra da Estiva", "BA"));
        lista.add(new Cidade("", "Barra do Choça", "BA"));
        lista.add(new Cidade("", "Barra do Mendes", "BA"));
        lista.add(new Cidade("", "Barra do Pojuca", "BA"));
        lista.add(new Cidade("", "Barra do Rocha", "BA"));
        lista.add(new Cidade("", "Barra do Tarrachil", "BA"));
        lista.add(new Cidade("", "Barra Grande", "BA"));
        lista.add(new Cidade("", "Barracas", "BA"));
        lista.add(new Cidade("", "Barreiras", "BA"));
        lista.add(new Cidade("", "Barreiros", "BA"));
        lista.add(new Cidade("", "Barro Alto", "BA"));
        lista.add(new Cidade("", "Barro Preto", "BA"));
        lista.add(new Cidade("", "Barro Vermelho", "BA"));
        lista.add(new Cidade("", "Barrocão", "BA"));
        lista.add(new Cidade("", "Barrocas", "BA"));
        lista.add(new Cidade("", "Barrolândia", "BA"));
        lista.add(new Cidade("", "Bastião", "BA"));
        lista.add(new Cidade("", "Bate Pé", "BA"));
        lista.add(new Cidade("", "Batinga", "BA"));
        lista.add(new Cidade("", "Bela Flor", "BA"));
        lista.add(new Cidade("", "Bela Vista", "BA"));
        lista.add(new Cidade("", "Belém da Cachoeira", "BA"));
        lista.add(new Cidade("", "Belmonte", "BA"));
        lista.add(new Cidade("", "Belo Campo", "BA"));
        lista.add(new Cidade("", "Bem-Bom", "BA"));
        lista.add(new Cidade("", "Bendegó", "BA"));
        lista.add(new Cidade("", "Bento Simões", "BA"));
        lista.add(new Cidade("", "Biritinga", "BA"));
        lista.add(new Cidade("", "Boa Espera", "BA"));
        lista.add(new Cidade("", "Boa Nova", "BA"));
        lista.add(new Cidade("", "Boa União", "BA"));
        lista.add(new Cidade("", "Boa Vista do Lagamar", "BA"));
        lista.add(new Cidade("", "Boa Vista do Tupim", "BA"));
        lista.add(new Cidade("", "Boaçu", "BA"));
        lista.add(new Cidade("", "Boca do Córrego", "BA"));
        lista.add(new Cidade("", "Bom Jesus da Lapa", "BA"));
        lista.add(new Cidade("", "Bom Jesus da Serra", "BA"));
        lista.add(new Cidade("", "Bom Sossego", "BA"));
        lista.add(new Cidade("", "Bonfim da Feira", "BA"));
        lista.add(new Cidade("", "Boninal", "BA"));
        lista.add(new Cidade("", "Bonito", "BA"));
        lista.add(new Cidade("", "Boquira", "BA"));
        lista.add(new Cidade("", "Botuporã", "BA"));
        lista.add(new Cidade("", "Botuquara", "BA"));
        lista.add(new Cidade("", "Brejinho das Ametistas", "BA"));
        lista.add(new Cidade("", "Brejo da Serra", "BA"));
        lista.add(new Cidade("", "Brejo Luíza de Brito", "BA"));
        lista.add(new Cidade("", "Brejo Novo", "BA"));
        lista.add(new Cidade("", "Brejões", "BA"));
        lista.add(new Cidade("", "Brejolândia", "BA"));
        lista.add(new Cidade("", "Brotas de Macaúbas", "BA"));
        lista.add(new Cidade("", "Brumado", "BA"));
        lista.add(new Cidade("", "Bucuituba", "BA"));
        lista.add(new Cidade("", "Buerarema", "BA"));
        lista.add(new Cidade("", "Buracica", "BA"));
        lista.add(new Cidade("", "Buranhém", "BA"));
        lista.add(new Cidade("", "Buril", "BA"));
        lista.add(new Cidade("", "Buritirama", "BA"));
        lista.add(new Cidade("", "Caatiba", "BA"));
        lista.add(new Cidade("", "Cabaceiras do Paraguaçu", "BA"));
        lista.add(new Cidade("", "Cabeceira do Jibóia", "BA"));
        lista.add(new Cidade("", "Cabôto", "BA"));
        lista.add(new Cidade("", "Cabrália", "BA"));
        lista.add(new Cidade("", "Cacha Pregos", "BA"));
        lista.add(new Cidade("", "Cachoeira", "BA"));
        lista.add(new Cidade("", "Cachoeira do Mato", "BA"));
        lista.add(new Cidade("", "Caculé", "BA"));
        lista.add(new Cidade("", "Caém", "BA"));
        lista.add(new Cidade("", "Caetanos", "BA"));
        lista.add(new Cidade("", "Caeté-Açu", "BA"));
        lista.add(new Cidade("", "Caetité", "BA"));
        lista.add(new Cidade("", "Cafarnaum", "BA"));
        lista.add(new Cidade("", "Caiçara", "BA"));
        lista.add(new Cidade("", "Caimbé", "BA"));
        lista.add(new Cidade("", "Cairu", "BA"));
        lista.add(new Cidade("", "Caiubi", "BA"));
        lista.add(new Cidade("", "Cajuí", "BA"));
        lista.add(new Cidade("", "Caldas do Jorro", "BA"));
        lista.add(new Cidade("", "Caldeirão", "BA"));
        lista.add(new Cidade("", "Caldeirão Grande", "BA"));
        lista.add(new Cidade("", "Caldeiras", "BA"));
        lista.add(new Cidade("", "Camacan", "BA"));
        lista.add(new Cidade("", "Camaçari", "BA"));
        lista.add(new Cidade("", "Camamu", "BA"));
        lista.add(new Cidade("", "Camassandi", "BA"));
        lista.add(new Cidade("", "Camirim", "BA"));
        lista.add(new Cidade("", "Campinhos", "BA"));
        lista.add(new Cidade("", "Campo Alegre de Lourdes", "BA"));
        lista.add(new Cidade("", "Campo Formoso", "BA"));
        lista.add(new Cidade("", "Camurugi", "BA"));
        lista.add(new Cidade("", "Cana Brava", "BA"));
        lista.add(new Cidade("", "Canabravinha", "BA"));
        lista.add(new Cidade("", "Canápolis", "BA"));
        lista.add(new Cidade("", "Canarana", "BA"));
        lista.add(new Cidade("", "Canatiba", "BA"));
        lista.add(new Cidade("", "Canavieiras", "BA"));
        lista.add(new Cidade("", "Canché", "BA"));
        lista.add(new Cidade("", "Candeal", "BA"));
        lista.add(new Cidade("", "Candeias", "BA"));
        lista.add(new Cidade("", "Candiba", "BA"));
        lista.add(new Cidade("", "Cândido Sales", "BA"));
        lista.add(new Cidade("", "Canoão", "BA"));
        lista.add(new Cidade("", "Cansanção", "BA"));
        lista.add(new Cidade("", "Canto do Sol", "BA"));
        lista.add(new Cidade("", "Canudos", "BA"));
        lista.add(new Cidade("", "Capão", "BA"));
        lista.add(new Cidade("", "Capela do Alto Alegre", "BA"));
        lista.add(new Cidade("", "Capim Grosso", "BA"));
        lista.add(new Cidade("", "Caraguataí", "BA"));
        lista.add(new Cidade("", "Caraíbas", "BA"));
        lista.add(new Cidade("", "Caraibuna", "BA"));
        lista.add(new Cidade("", "Caraípe", "BA"));
        lista.add(new Cidade("", "Caraiva", "BA"));
        lista.add(new Cidade("", "Caravelas", "BA"));
        lista.add(new Cidade("", "Cardeal da Silva", "BA"));
        lista.add(new Cidade("", "Carinhanha", "BA"));
        lista.add(new Cidade("", "Caripare", "BA"));
        lista.add(new Cidade("", "Carnaíba do Sertão", "BA"));
        lista.add(new Cidade("", "Caroba", "BA"));
        lista.add(new Cidade("", "Carrapichel", "BA"));
        lista.add(new Cidade("", "Casa Nova", "BA"));
        lista.add(new Cidade("", "Castelo Novo", "BA"));
        lista.add(new Cidade("", "Castro Alves", "BA"));
        lista.add(new Cidade("", "Catinga do Moura", "BA"));
        lista.add(new Cidade("", "Catingal", "BA"));
        lista.add(new Cidade("", "Catolândia", "BA"));
        lista.add(new Cidade("", "Catolés", "BA"));
        lista.add(new Cidade("", "Catolezinho", "BA"));
        lista.add(new Cidade("", "Catu", "BA"));
        lista.add(new Cidade("", "Catu de Abrantes", "BA"));
        lista.add(new Cidade("", "Caturama", "BA"));
        lista.add(new Cidade("", "Cavunge", "BA"));
        lista.add(new Cidade("", "Central", "BA"));
        lista.add(new Cidade("", "Ceraima", "BA"));
        lista.add(new Cidade("", "Cercadinho", "BA"));
        lista.add(new Cidade("", "Chorrochó", "BA"));
        lista.add(new Cidade("", "Cícero Dantas", "BA"));
        lista.add(new Cidade("", "Cinco Rios", "BA"));
        lista.add(new Cidade("", "Cipó", "BA"));
        lista.add(new Cidade("", "Coaraci", "BA"));
        lista.add(new Cidade("", "Cocos", "BA"));
        lista.add(new Cidade("", "Colônia", "BA"));
        lista.add(new Cidade("", "Colônia do Formoso", "BA"));
        lista.add(new Cidade("", "Comércio", "BA"));
        lista.add(new Cidade("", "Conceição da Feira", "BA"));
        lista.add(new Cidade("", "Conceição do Almeida", "BA"));
        lista.add(new Cidade("", "Conceição do Coité", "BA"));
        lista.add(new Cidade("", "Conceição do Jacuípe", "BA"));
        lista.add(new Cidade("", "Conde", "BA"));
        lista.add(new Cidade("", "Condeúba", "BA"));
        lista.add(new Cidade("", "Contendas do Sincorá", "BA"));
        lista.add(new Cidade("", "Copixaba", "BA"));
        lista.add(new Cidade("", "Coqueiros", "BA"));
        lista.add(new Cidade("", "Coquinhos", "BA"));
        lista.add(new Cidade("", "Coração de Maria", "BA"));
        lista.add(new Cidade("", "Cordeiros", "BA"));
        lista.add(new Cidade("", "Coribe", "BA"));
        lista.add(new Cidade("", "Coronel João Sá", "BA"));
        lista.add(new Cidade("", "Correntina", "BA"));
        lista.add(new Cidade("", "Corta Mão", "BA"));
        lista.add(new Cidade("", "Cotegipe", "BA"));
        lista.add(new Cidade("", "Coutos", "BA"));
        lista.add(new Cidade("", "Cravolândia", "BA"));
        lista.add(new Cidade("", "Crisópolis", "BA"));
        lista.add(new Cidade("", "Cristalândia", "BA"));
        lista.add(new Cidade("", "Cristópolis", "BA"));
        lista.add(new Cidade("", "Crussaí", "BA"));
        lista.add(new Cidade("", "Cruz das Almas", "BA"));
        lista.add(new Cidade("", "Cumuruxatiba", "BA"));
        lista.add(new Cidade("", "Cunhangi", "BA"));
        lista.add(new Cidade("", "Curaçá", "BA"));
        lista.add(new Cidade("", "Curral Falso", "BA"));
        lista.add(new Cidade("", "Dantelândia", "BA"));
        lista.add(new Cidade("", "Dário Meira", "BA"));
        lista.add(new Cidade("", "Delfino", "BA"));
        lista.add(new Cidade("", "Descoberto", "BA"));
        lista.add(new Cidade("", "Dias Coelho", "BA"));
        lista.add(new Cidade("", "Dias D'Ávila", "BA"));
        lista.add(new Cidade("", "Diógenes Sampaio", "BA"));
        lista.add(new Cidade("", "Dom Basílio", "BA"));
        lista.add(new Cidade("", "Dom Macedo Costa", "BA"));
        lista.add(new Cidade("", "Dona Maria", "BA"));
        lista.add(new Cidade("", "Duas Barras do Morro", "BA"));
        lista.add(new Cidade("", "Elísio Medrado", "BA"));
        lista.add(new Cidade("", "Encruzilhada", "BA"));
        lista.add(new Cidade("", "Engenheiro França", "BA"));
        lista.add(new Cidade("", "Engenheiro Pontes", "BA"));
        lista.add(new Cidade("", "Entre Rios", "BA"));
        lista.add(new Cidade("", "Érico Cardoso", "BA"));
        lista.add(new Cidade("", "Esplanada", "BA"));
        lista.add(new Cidade("", "Espraiado", "BA"));
        lista.add(new Cidade("", "Euclides da Cunha", "BA"));
        lista.add(new Cidade("", "Eunápolis", "BA"));
        lista.add(new Cidade("", "Fátima", "BA"));
        lista.add(new Cidade("", "Feira da Mata", "BA"));
        lista.add(new Cidade("", "Feira de Santana", "BA"));
        lista.add(new Cidade("", "Ferradas", "BA"));
        lista.add(new Cidade("", "Filadélfia", "BA"));
        lista.add(new Cidade("", "Filanésia", "BA"));
        lista.add(new Cidade("", "Firmino Alves", "BA"));
        lista.add(new Cidade("", "Floresta Azul", "BA"));
        lista.add(new Cidade("", "Florestal", "BA"));
        lista.add(new Cidade("", "Formosa do Rio Preto", "BA"));
        lista.add(new Cidade("", "França", "BA"));
        lista.add(new Cidade("", "Gabiarra", "BA"));
        lista.add(new Cidade("", "Galeão", "BA"));
        lista.add(new Cidade("", "Gamboa", "BA"));
        lista.add(new Cidade("", "Gameleira da Lapa", "BA"));
        lista.add(new Cidade("", "Gameleira do Assuruá", "BA"));
        lista.add(new Cidade("", "Gandu", "BA"));
        lista.add(new Cidade("", "Gavião", "BA"));
        lista.add(new Cidade("", "Gentio do Ouro", "BA"));
        lista.add(new Cidade("", "Geolândia", "BA"));
        lista.add(new Cidade("", "Glória", "BA"));
        lista.add(new Cidade("", "Gongogi", "BA"));
        lista.add(new Cidade("", "Governador João Durval Carneiro", "BA"));
        lista.add(new Cidade("", "Governador Mangabeira", "BA"));
        lista.add(new Cidade("", "Guaí", "BA"));
        lista.add(new Cidade("", "Guajeru", "BA"));
        lista.add(new Cidade("", "Guanambi", "BA"));
        lista.add(new Cidade("", "Guapira", "BA"));
        lista.add(new Cidade("", "Guarajuba", "BA"));
        lista.add(new Cidade("", "Guaratinga", "BA"));
        lista.add(new Cidade("", "Guerém", "BA"));
        lista.add(new Cidade("", "Guiné", "BA"));
        lista.add(new Cidade("", "Guirapa", "BA"));
        lista.add(new Cidade("", "Gurupá Mirim", "BA"));
        lista.add(new Cidade("", "Heliópolis", "BA"));
        lista.add(new Cidade("", "Helvecia", "BA"));
        lista.add(new Cidade("", "Hidrolândia", "BA"));
        lista.add(new Cidade("", "Humildes", "BA"));
        lista.add(new Cidade("", "Iaçu", "BA"));
        lista.add(new Cidade("", "Ibatui", "BA"));
        lista.add(new Cidade("", "Ibiaçu", "BA"));
        lista.add(new Cidade("", "Ibiajara", "BA"));
        lista.add(new Cidade("", "Ibiapora", "BA"));
        lista.add(new Cidade("", "Ibiassucê", "BA"));
        lista.add(new Cidade("", "Ibicaraí", "BA"));
        lista.add(new Cidade("", "Ibicoara", "BA"));
        lista.add(new Cidade("", "Ibicuí", "BA"));
        lista.add(new Cidade("", "Ibipeba", "BA"));
        lista.add(new Cidade("", "Ibipetum", "BA"));
        lista.add(new Cidade("", "Ibipitanga", "BA"));
        lista.add(new Cidade("", "Ibiquera", "BA"));
        lista.add(new Cidade("", "Ibiraba", "BA"));
        lista.add(new Cidade("", "Ibirajá", "BA"));
        lista.add(new Cidade("", "Ibiranhém", "BA"));
        lista.add(new Cidade("", "Ibirapitanga", "BA"));
        lista.add(new Cidade("", "Ibirapuã", "BA"));
        lista.add(new Cidade("", "Ibirataia", "BA"));
        lista.add(new Cidade("", "Ibitiara", "BA"));
        lista.add(new Cidade("", "Ibitiguira", "BA"));
        lista.add(new Cidade("", "Ibitira", "BA"));
        lista.add(new Cidade("", "Ibititá", "BA"));
        lista.add(new Cidade("", "Ibitunane", "BA"));
        lista.add(new Cidade("", "Ibitupa", "BA"));
        lista.add(new Cidade("", "Ibó", "BA"));
        lista.add(new Cidade("", "Ibotirama", "BA"));
        lista.add(new Cidade("", "Ichu", "BA"));
        lista.add(new Cidade("", "Icó", "BA"));
        lista.add(new Cidade("", "Igaporã", "BA"));
        lista.add(new Cidade("", "Igará", "BA"));
        lista.add(new Cidade("", "Igarité", "BA"));
        lista.add(new Cidade("", "Igatu", "BA"));
        lista.add(new Cidade("", "Igrapiúna", "BA"));
        lista.add(new Cidade("", "Iguá", "BA"));
        lista.add(new Cidade("", "Iguaí", "BA"));
        lista.add(new Cidade("", "Iguaibi", "BA"));
        lista.add(new Cidade("", "Iguatemi", "BA"));
        lista.add(new Cidade("", "Iguira", "BA"));
        lista.add(new Cidade("", "Iguitu", "BA"));
        lista.add(new Cidade("", "Ilha de Bom Jesus dos Passos", "BA"));
        lista.add(new Cidade("", "Ilha de Maré", "BA"));
        lista.add(new Cidade("", "Ilha dos Frades", "BA"));
        lista.add(new Cidade("", "Ilhéus", "BA"));
        lista.add(new Cidade("", "Imbassaí", "BA"));
        lista.add(new Cidade("", "Indaí", "BA"));
        lista.add(new Cidade("", "Inema", "BA"));
        lista.add(new Cidade("", "Inhambupe", "BA"));
        lista.add(new Cidade("", "Inhata", "BA"));
        lista.add(new Cidade("", "Inhaúmas", "BA"));
        lista.add(new Cidade("", "Inhobim", "BA"));
        lista.add(new Cidade("", "Inúbia", "BA"));
        lista.add(new Cidade("", "Ipanema", "BA"));
        lista.add(new Cidade("", "Ipecaetá", "BA"));
        lista.add(new Cidade("", "Ipiaú", "BA"));
        lista.add(new Cidade("", "Ipirá", "BA"));
        lista.add(new Cidade("", "Ipiúna", "BA"));
        lista.add(new Cidade("", "Ipucaba", "BA"));
        lista.add(new Cidade("", "Ipupiara", "BA"));
        lista.add(new Cidade("", "Irajuba", "BA"));
        lista.add(new Cidade("", "Iramaia", "BA"));
        lista.add(new Cidade("", "Iraporanga", "BA"));
        lista.add(new Cidade("", "Iraquara", "BA"));
        lista.add(new Cidade("", "Irará", "BA"));
        lista.add(new Cidade("", "Irecê", "BA"));
        lista.add(new Cidade("", "Irundiara", "BA"));
        lista.add(new Cidade("", "Ita-Azul", "BA"));
        lista.add(new Cidade("", "Itabatã", "BA"));
        lista.add(new Cidade("", "Itabatan", "BA"));
        lista.add(new Cidade("", "Itabela", "BA"));
        lista.add(new Cidade("", "Itaberaba", "BA"));
        lista.add(new Cidade("", "Itabuna", "BA"));
        lista.add(new Cidade("", "Itacaré", "BA"));
        lista.add(new Cidade("", "Itacava", "BA"));
        lista.add(new Cidade("", "Itachama", "BA"));
        lista.add(new Cidade("", "Itacimirim", "BA"));
        lista.add(new Cidade("", "Itaeté", "BA"));
        lista.add(new Cidade("", "Itagi", "BA"));
        lista.add(new Cidade("", "Itagibá", "BA"));
        lista.add(new Cidade("", "Itagimirim", "BA"));
        lista.add(new Cidade("", "Itaguaçu da Bahia", "BA"));
        lista.add(new Cidade("", "Itaia", "BA"));
        lista.add(new Cidade("", "Itaibó", "BA"));
        lista.add(new Cidade("", "Itaipu", "BA"));
        lista.add(new Cidade("", "Itaítu", "BA"));
        lista.add(new Cidade("", "Itajaí", "BA"));
        lista.add(new Cidade("", "Itaju do Colônia", "BA"));
        lista.add(new Cidade("", "Itajubaquara", "BA"));
        lista.add(new Cidade("", "Itajuípe", "BA"));
        lista.add(new Cidade("", "Itajuru", "BA"));
        lista.add(new Cidade("", "Itamaraju", "BA"));
        lista.add(new Cidade("", "Itamari", "BA"));
        lista.add(new Cidade("", "Itambé", "BA"));
        lista.add(new Cidade("", "Itamira", "BA"));
        lista.add(new Cidade("", "Itamotinga", "BA"));
        lista.add(new Cidade("", "Itanagé", "BA"));
        lista.add(new Cidade("", "Itanagra", "BA"));
        lista.add(new Cidade("", "Itanhém", "BA"));
        lista.add(new Cidade("", "Itanhi", "BA"));
        lista.add(new Cidade("", "Itaparica", "BA"));
        lista.add(new Cidade("", "Itapé", "BA"));
        lista.add(new Cidade("", "Itapebi", "BA"));
        lista.add(new Cidade("", "Itapeipu", "BA"));
        lista.add(new Cidade("", "Itapetinga", "BA"));
        lista.add(new Cidade("", "Itapicuru", "BA"));
        lista.add(new Cidade("", "Itapirema", "BA"));
        lista.add(new Cidade("", "Itapitanga", "BA"));
        lista.add(new Cidade("", "Itapora", "BA"));
        lista.add(new Cidade("", "Itapura", "BA"));
        lista.add(new Cidade("", "Itaquara", "BA"));
        lista.add(new Cidade("", "Itaquaraí", "BA"));
        lista.add(new Cidade("", "Itarantim", "BA"));
        lista.add(new Cidade("", "Itati", "BA"));
        lista.add(new Cidade("", "Itatiaia do Alto Bonito", "BA"));
        lista.add(new Cidade("", "Itatim", "BA"));
        lista.add(new Cidade("", "Itatingui", "BA"));
        lista.add(new Cidade("", "Itiruçu", "BA"));
        lista.add(new Cidade("", "Itiúba", "BA"));
        lista.add(new Cidade("", "Itororó", "BA"));
        lista.add(new Cidade("", "Ituaçu", "BA"));
        lista.add(new Cidade("", "Ituberá", "BA"));
        lista.add(new Cidade("", "Itupeva", "BA"));
        lista.add(new Cidade("", "Iuiu", "BA"));
        lista.add(new Cidade("", "Jaborandi", "BA"));
        lista.add(new Cidade("", "Jacaraci", "BA"));
        lista.add(new Cidade("", "Jacobina", "BA"));
        lista.add(new Cidade("", "Jacu", "BA"));
        lista.add(new Cidade("", "Jacuípe", "BA"));
        lista.add(new Cidade("", "Jacuruna", "BA"));
        lista.add(new Cidade("", "Jaguaquara", "BA"));
        lista.add(new Cidade("", "Jaguara", "BA"));
        lista.add(new Cidade("", "Jaguarari", "BA"));
        lista.add(new Cidade("", "Jaguaripe", "BA"));
        lista.add(new Cidade("", "Jaíba", "BA"));
        lista.add(new Cidade("", "Jandaíra", "BA"));
        lista.add(new Cidade("", "Japomirim", "BA"));
        lista.add(new Cidade("", "Japu", "BA"));
        lista.add(new Cidade("", "Jauá", "BA"));
        lista.add(new Cidade("", "Jequié", "BA"));
        lista.add(new Cidade("", "Jeremoabo", "BA"));
        lista.add(new Cidade("", "Jiquiriçá", "BA"));
        lista.add(new Cidade("", "Jiribatuba", "BA"));
        lista.add(new Cidade("", "Jitaúna", "BA"));
        lista.add(new Cidade("", "João Amaro", "BA"));
        lista.add(new Cidade("", "João Correia", "BA"));
        lista.add(new Cidade("", "João Dourado", "BA"));
        lista.add(new Cidade("", "José Gonçalves", "BA"));
        lista.add(new Cidade("", "Juacema", "BA"));
        lista.add(new Cidade("", "Juazeiro", "BA"));
        lista.add(new Cidade("", "Jucuruçu", "BA"));
        lista.add(new Cidade("", "Juerana", "BA"));
        lista.add(new Cidade("", "Junco", "BA"));
        lista.add(new Cidade("", "Jupaguá", "BA"));
        lista.add(new Cidade("", "Juraci", "BA"));
        lista.add(new Cidade("", "Juremal", "BA"));
        lista.add(new Cidade("", "Jussara", "BA"));
        lista.add(new Cidade("", "Jussari", "BA"));
        lista.add(new Cidade("", "Jussiape", "BA"));
        lista.add(new Cidade("", "Km Sete", "BA"));
        lista.add(new Cidade("", "Lafaiete Coutinho", "BA"));
        lista.add(new Cidade("", "Lagoa Clara", "BA"));
        lista.add(new Cidade("", "Lagoa de Melquíades", "BA"));
        lista.add(new Cidade("", "Lagoa do Boi", "BA"));
        lista.add(new Cidade("", "Lagoa Grande", "BA"));
        lista.add(new Cidade("", "Lagoa José Luís", "BA"));
        lista.add(new Cidade("", "Lagoa Preta", "BA"));
        lista.add(new Cidade("", "Lagoa Real", "BA"));
        lista.add(new Cidade("", "Laje", "BA"));
        lista.add(new Cidade("", "Laje do Banco", "BA"));
        lista.add(new Cidade("", "Lajedão", "BA"));
        lista.add(new Cidade("", "Lajedinho", "BA"));
        lista.add(new Cidade("", "Lajedo Alto", "BA"));
        lista.add(new Cidade("", "Lajedo do Tabocal", "BA"));
        lista.add(new Cidade("", "Lamarão", "BA"));
        lista.add(new Cidade("", "Lamarão do Passe", "BA"));
        lista.add(new Cidade("", "Lapão", "BA"));
        lista.add(new Cidade("", "Largo", "BA"));
        lista.add(new Cidade("", "Lauro de Freitas", "BA"));
        lista.add(new Cidade("", "Lençóis", "BA"));
        lista.add(new Cidade("", "Licínio de Almeida", "BA"));
        lista.add(new Cidade("", "Limoeiro do Bom Viver", "BA"));
        lista.add(new Cidade("", "Livramento de Nossa Senhora", "BA"));
        lista.add(new Cidade("", "Lucaia", "BA"));
        lista.add(new Cidade("", "Luís Eduardo Magalhães", "BA"));
        lista.add(new Cidade("", "Luís Viana", "BA"));
        lista.add(new Cidade("", "Lustosa", "BA"));
        lista.add(new Cidade("", "Macajuba", "BA"));
        lista.add(new Cidade("", "Macarani", "BA"));
        lista.add(new Cidade("", "Macaúbas", "BA"));
        lista.add(new Cidade("", "Macururé", "BA"));
        lista.add(new Cidade("", "Madeira", "BA"));
        lista.add(new Cidade("", "Madre de Deus", "BA"));
        lista.add(new Cidade("", "Maetinga", "BA"));
        lista.add(new Cidade("", "Maiquinique", "BA"));
        lista.add(new Cidade("", "Mairi", "BA"));
        lista.add(new Cidade("", "Malhada", "BA"));
        lista.add(new Cidade("", "Malhada de Pedras", "BA"));
        lista.add(new Cidade("", "Mandiroba", "BA"));
        lista.add(new Cidade("", "Mangue Seco", "BA"));
        lista.add(new Cidade("", "Maniaçu", "BA"));
        lista.add(new Cidade("", "Maniçoba", "BA"));
        lista.add(new Cidade("", "Manoel Vitorino", "BA"));
        lista.add(new Cidade("", "Mansidão", "BA"));
        lista.add(new Cidade("", "Mantiba", "BA"));
        lista.add(new Cidade("", "Mar Grande", "BA"));
        lista.add(new Cidade("", "Maracás", "BA"));
        lista.add(new Cidade("", "Maragogipe", "BA"));
        lista.add(new Cidade("", "Maragogipinho", "BA"));
        lista.add(new Cidade("", "Maraú", "BA"));
        lista.add(new Cidade("", "Marcionílio Souza", "BA"));
        lista.add(new Cidade("", "Marcolino Moura", "BA"));
        lista.add(new Cidade("", "Maria Quitéria", "BA"));
        lista.add(new Cidade("", "Maricoabo", "BA"));
        lista.add(new Cidade("", "Mariquita", "BA"));
        lista.add(new Cidade("", "Mascote", "BA"));
        lista.add(new Cidade("", "Massacara", "BA"));
        lista.add(new Cidade("", "Massaroca", "BA"));
        lista.add(new Cidade("", "Mata da Aliança", "BA"));
        lista.add(new Cidade("", "Mata de São João", "BA"));
        lista.add(new Cidade("", "Mataripe", "BA"));
        lista.add(new Cidade("", "Matina", "BA"));
        lista.add(new Cidade("", "Matinha", "BA"));
        lista.add(new Cidade("", "Medeiros Neto", "BA"));
        lista.add(new Cidade("", "Menino Jesus", "BA"));
        lista.add(new Cidade("", "Miguel Calmon", "BA"));
        lista.add(new Cidade("", "Milagres", "BA"));
        lista.add(new Cidade("", "Mimoso", "BA"));
        lista.add(new Cidade("", "Minas do Espírito Santo", "BA"));
        lista.add(new Cidade("", "Minas do Mimoso", "BA"));
        lista.add(new Cidade("", "Mirandela", "BA"));
        lista.add(new Cidade("", "Miranga", "BA"));
        lista.add(new Cidade("", "Mirangaba", "BA"));
        lista.add(new Cidade("", "Mirante", "BA"));
        lista.add(new Cidade("", "Missão de Aricobé", "BA"));
        lista.add(new Cidade("", "Mocambo", "BA"));
        lista.add(new Cidade("", "Mogiquiçaba", "BA"));
        lista.add(new Cidade("", "Monte Branco", "BA"));
        lista.add(new Cidade("", "Monte Cruzeiro", "BA"));
        lista.add(new Cidade("", "Monte Gordo", "BA"));
        lista.add(new Cidade("", "Monte Recôncavo", "BA"));
        lista.add(new Cidade("", "Monte Santo", "BA"));
        lista.add(new Cidade("", "Morpará", "BA"));
        lista.add(new Cidade("", "Morrinhos", "BA"));
        lista.add(new Cidade("", "Morro das Flores", "BA"));
        lista.add(new Cidade("", "Morro de São Paulo", "BA"));
        lista.add(new Cidade("", "Morro do Chapéu", "BA"));
        lista.add(new Cidade("", "Mortugaba", "BA"));
        lista.add(new Cidade("", "Mucugê", "BA"));
        lista.add(new Cidade("", "Mucuri", "BA"));
        lista.add(new Cidade("", "Mulungu do Morro", "BA"));
        lista.add(new Cidade("", "Mundo Novo", "BA"));
        lista.add(new Cidade("", "Muniz Ferreira", "BA"));
        lista.add(new Cidade("", "Muquém de São Francisco", "BA"));
        lista.add(new Cidade("", "Muritiba", "BA"));
        lista.add(new Cidade("", "Mutas", "BA"));
        lista.add(new Cidade("", "Mutuípe", "BA"));
        lista.add(new Cidade("", "Nagé", "BA"));
        lista.add(new Cidade("", "Narandiba", "BA"));
        lista.add(new Cidade("", "Nazaré", "BA"));
        lista.add(new Cidade("", "Nilo Peçanha", "BA"));
        lista.add(new Cidade("", "Nordestina", "BA"));
        lista.add(new Cidade("", "Nova Alegria", "BA"));
        lista.add(new Cidade("", "Nova Brasília", "BA"));
        lista.add(new Cidade("", "Nova Canaã", "BA"));
        lista.add(new Cidade("", "Nova Fátima", "BA"));
        lista.add(new Cidade("", "Nova Ibiá", "BA"));
        lista.add(new Cidade("", "Nova Itaipê", "BA"));
        lista.add(new Cidade("", "Nova Itarana", "BA"));
        lista.add(new Cidade("", "Nova Lídice", "BA"));
        lista.add(new Cidade("", "Nova Redenção", "BA"));
        lista.add(new Cidade("", "Nova Soure", "BA"));
        lista.add(new Cidade("", "Nova Viçosa", "BA"));
        lista.add(new Cidade("", "Novo Acre", "BA"));
        lista.add(new Cidade("", "Novo Horizonte", "BA"));
        lista.add(new Cidade("", "Novo Triunfo", "BA"));
        lista.add(new Cidade("", "Núcleo Residencial Pilar", "BA"));
        lista.add(new Cidade("", "Nuguaçu", "BA"));
        lista.add(new Cidade("", "Olhos D'Água do Seco", "BA"));
        lista.add(new Cidade("", "Olhos D'Água do Serafim", "BA"));
        lista.add(new Cidade("", "Olindina", "BA"));
        lista.add(new Cidade("", "Oliveira dos Brejinhos", "BA"));
        lista.add(new Cidade("", "Olivença", "BA"));
        lista.add(new Cidade("", "Onha", "BA"));
        lista.add(new Cidade("", "Oriente Novo", "BA"));
        lista.add(new Cidade("", "Ouricana", "BA"));
        lista.add(new Cidade("", "Ouriçangas", "BA"));
        lista.add(new Cidade("", "Ouricuri do Ouro", "BA"));
        lista.add(new Cidade("", "Ourolândia", "BA"));
        lista.add(new Cidade("", "Outeiro Redondo", "BA"));
        lista.add(new Cidade("", "Paiol", "BA"));
        lista.add(new Cidade("", "Pajeú do Vento", "BA"));
        lista.add(new Cidade("", "Palame", "BA"));
        lista.add(new Cidade("", "Palmares", "BA"));
        lista.add(new Cidade("", "Palmas de Monte Alto", "BA"));
        lista.add(new Cidade("", "Palmeiras", "BA"));
        lista.add(new Cidade("", "Parafuso", "BA"));
        lista.add(new Cidade("", "Paramirim", "BA"));
        lista.add(new Cidade("", "Parateca", "BA"));
        lista.add(new Cidade("", "Paratinga", "BA"));
        lista.add(new Cidade("", "Paripiranga", "BA"));
        lista.add(new Cidade("", "Passagem dos Teixeiras", "BA"));
        lista.add(new Cidade("", "Passé", "BA"));
        lista.add(new Cidade("", "Pataíba", "BA"));
        lista.add(new Cidade("", "Patamuté", "BA"));
        lista.add(new Cidade("", "Pau a Pique", "BA"));
        lista.add(new Cidade("", "Pau Brasil", "BA"));
        lista.add(new Cidade("", "Paulo Afonso", "BA"));
        lista.add(new Cidade("", "Pé de Serra", "BA"));
        lista.add(new Cidade("", "Pedra Alta", "BA"));
        lista.add(new Cidade("", "Pedrão", "BA"));
        lista.add(new Cidade("", "Pedras Altas do Mirim", "BA"));
        lista.add(new Cidade("", "Pedro Alexandre", "BA"));
        lista.add(new Cidade("", "Peixe", "BA"));
        lista.add(new Cidade("", "Petim", "BA"));
        lista.add(new Cidade("", "Piabanha", "BA"));
        lista.add(new Cidade("", "Piatã", "BA"));
        lista.add(new Cidade("", "Piçarrão", "BA"));
        lista.add(new Cidade("", "Pilão Arcado", "BA"));
        lista.add(new Cidade("", "Pilões", "BA"));
        lista.add(new Cidade("", "Pimenteira", "BA"));
        lista.add(new Cidade("", "Pindaí", "BA"));
        lista.add(new Cidade("", "Pindobaçu", "BA"));
        lista.add(new Cidade("", "Pinga Fogo", "BA"));
        lista.add(new Cidade("", "Pinhões", "BA"));
        lista.add(new Cidade("", "Pintadas", "BA"));
        lista.add(new Cidade("", "Piragi", "BA"));
        lista.add(new Cidade("", "Piraí do Norte", "BA"));
        lista.add(new Cidade("", "Pirajá", "BA"));
        lista.add(new Cidade("", "Pirajuia", "BA"));
        lista.add(new Cidade("", "Piri", "BA"));
        lista.add(new Cidade("", "Piripá", "BA"));
        lista.add(new Cidade("", "Piritiba", "BA"));
        lista.add(new Cidade("", "Pituba", "BA"));
        lista.add(new Cidade("", "Planaltino", "BA"));
        lista.add(new Cidade("", "Planalto", "BA"));
        lista.add(new Cidade("", "Poço Central", "BA"));
        lista.add(new Cidade("", "Poço de Fora", "BA"));
        lista.add(new Cidade("", "Poções", "BA"));
        lista.add(new Cidade("", "Poços", "BA"));
        lista.add(new Cidade("", "Pojuca", "BA"));
        lista.add(new Cidade("", "Polo Petroquímico de Camaçari", "BA"));
        lista.add(new Cidade("", "Ponta da Areia", "BA"));
        lista.add(new Cidade("", "Ponto Novo", "BA"));
        lista.add(new Cidade("", "Porto Novo", "BA"));
        lista.add(new Cidade("", "Porto Sauípe", "BA"));
        lista.add(new Cidade("", "Porto Seguro", "BA"));
        lista.add(new Cidade("", "Posto da Mata", "BA"));
        lista.add(new Cidade("", "Potiraguá", "BA"));
        lista.add(new Cidade("", "Poxim do Sul", "BA"));
        lista.add(new Cidade("", "Prado", "BA"));
        lista.add(new Cidade("", "Pradoso", "BA"));
        lista.add(new Cidade("", "Praia do Forte", "BA"));
        lista.add(new Cidade("", "Presidente Dutra", "BA"));
        lista.add(new Cidade("", "Presidente Jânio Quadros", "BA"));
        lista.add(new Cidade("", "Presidente Tancredo Neves", "BA"));
        lista.add(new Cidade("", "Prevenido", "BA"));
        lista.add(new Cidade("", "Quaraçu", "BA"));
        lista.add(new Cidade("", "Queimadas", "BA"));
        lista.add(new Cidade("", "Quijingue", "BA"));
        lista.add(new Cidade("", "Quixabá", "BA"));
        lista.add(new Cidade("", "Quixabeira", "BA"));
        lista.add(new Cidade("", "Rafael Jambeiro", "BA"));
        lista.add(new Cidade("", "Rancho das Mães", "BA"));
        lista.add(new Cidade("", "Raspador", "BA"));
        lista.add(new Cidade("", "Recife", "BA"));
        lista.add(new Cidade("", "Remanso", "BA"));
        lista.add(new Cidade("", "Remédios", "BA"));
        lista.add(new Cidade("", "Retirolândia", "BA"));
        lista.add(new Cidade("", "Riachão das Neves", "BA"));
        lista.add(new Cidade("", "Riachão do Jacuípe", "BA"));
        lista.add(new Cidade("", "Riachão do Utinga", "BA"));
        lista.add(new Cidade("", "Riacho da Guia", "BA"));
        lista.add(new Cidade("", "Riacho de Santana", "BA"));
        lista.add(new Cidade("", "Riacho Seco", "BA"));
        lista.add(new Cidade("", "Ribeira do Amparo", "BA"));
        lista.add(new Cidade("", "Ribeira do Pombal", "BA"));
        lista.add(new Cidade("", "Ribeirão do Largo", "BA"));
        lista.add(new Cidade("", "Ribeirão do Salto", "BA"));
        lista.add(new Cidade("", "Rio da Dona", "BA"));
        lista.add(new Cidade("", "Rio de Contas", "BA"));
        lista.add(new Cidade("", "Rio do Antônio", "BA"));
        lista.add(new Cidade("", "Rio do Braço", "BA"));
        lista.add(new Cidade("", "Rio do Meio", "BA"));
        lista.add(new Cidade("", "Rio do Pires", "BA"));
        lista.add(new Cidade("", "Rio Fundo", "BA"));
        lista.add(new Cidade("", "Rio Real", "BA"));
        lista.add(new Cidade("", "Roda Velha", "BA"));
        lista.add(new Cidade("", "Rodelas", "BA"));
        lista.add(new Cidade("", "Rosário", "BA"));
        lista.add(new Cidade("", "Ruy Barbosa", "BA"));
        lista.add(new Cidade("", "Saldanha", "BA"));
        lista.add(new Cidade("", "Salgadália", "BA"));
        lista.add(new Cidade("", "Salinas da Margarida", "BA"));
        lista.add(new Cidade("", "Salobrinho", "BA"));
        lista.add(new Cidade("", "Salobro", "BA"));
        lista.add(new Cidade("", "Salvador", "BA"));
        lista.add(new Cidade("", "Sambaíba", "BA"));
        lista.add(new Cidade("", "Santa Bárbara", "BA"));
        lista.add(new Cidade("", "Santa Brígida", "BA"));
        lista.add(new Cidade("", "Santa Cruz Cabrália", "BA"));
        lista.add(new Cidade("", "Santa Cruz da Vitória", "BA"));
        lista.add(new Cidade("", "Santa Inês", "BA"));
        lista.add(new Cidade("", "Santa Luzia", "BA"));
        lista.add(new Cidade("", "Santa Maria da Vitória", "BA"));
        lista.add(new Cidade("", "Santa Rita de Cássia", "BA"));
        lista.add(new Cidade("", "Santa Teresinha", "BA"));
        lista.add(new Cidade("", "Santaluz", "BA"));
        lista.add(new Cidade("", "Santana", "BA"));
        lista.add(new Cidade("", "Santana do Sobrado", "BA"));
        lista.add(new Cidade("", "Santanópolis", "BA"));
        lista.add(new Cidade("", "Santiago do Iguapé", "BA"));
        lista.add(new Cidade("", "Santo Amaro", "BA"));
        lista.add(new Cidade("", "Santo Antônio", "BA"));
        lista.add(new Cidade("", "Santo Antônio de Barcelona", "BA"));
        lista.add(new Cidade("", "Santo Antônio de Jesus", "BA"));
        lista.add(new Cidade("", "Santo Estevão", "BA"));
        lista.add(new Cidade("", "Santo Inácio", "BA"));
        lista.add(new Cidade("", "São Desidério", "BA"));
        lista.add(new Cidade("", "São Domingos", "BA"));
        lista.add(new Cidade("", "São Felipe", "BA"));
        lista.add(new Cidade("", "São Félix", "BA"));
        lista.add(new Cidade("", "São Félix do Coribe", "BA"));
        lista.add(new Cidade("", "São Francisco do Conde", "BA"));
        lista.add(new Cidade("", "São Gabriel", "BA"));
        lista.add(new Cidade("", "São Gonçalo dos Campos", "BA"));
        lista.add(new Cidade("", "São João", "BA"));
        lista.add(new Cidade("", "São João da Fortaleza", "BA"));
        lista.add(new Cidade("", "São João da Vitória", "BA"));
        lista.add(new Cidade("", "São José da Vitória", "BA"));
        lista.add(new Cidade("", "São José do Colônia", "BA"));
        lista.add(new Cidade("", "São José do Jacuípe", "BA"));
        lista.add(new Cidade("", "São José do Prado", "BA"));
        lista.add(new Cidade("", "São José do Rio Grande", "BA"));
        lista.add(new Cidade("", "São Miguel das Matas", "BA"));
        lista.add(new Cidade("", "São Paulinho", "BA"));
        lista.add(new Cidade("", "São Roque do Paraguaçu", "BA"));
        lista.add(new Cidade("", "São Sebastião", "BA"));
        lista.add(new Cidade("", "São Sebastião do Passe", "BA"));
        lista.add(new Cidade("", "São Timóteo", "BA"));
        lista.add(new Cidade("", "Sapeaçu", "BA"));
        lista.add(new Cidade("", "Sátiro Dias", "BA"));
        lista.add(new Cidade("", "Saubara", "BA"));
        lista.add(new Cidade("", "Saudável", "BA"));
        lista.add(new Cidade("", "Saúde", "BA"));
        lista.add(new Cidade("", "Seabra", "BA"));
        lista.add(new Cidade("", "Sebastião Laranjeiras", "BA"));
        lista.add(new Cidade("", "Senhor do Bonfim", "BA"));
        lista.add(new Cidade("", "Sento Sé", "BA"));
        lista.add(new Cidade("", "Sergi", "BA"));
        lista.add(new Cidade("", "Serra da Canabrava", "BA"));
        lista.add(new Cidade("", "Serra do CEM", "BA"));
        lista.add(new Cidade("", "Serra do Ramalho", "BA"));
        lista.add(new Cidade("", "Serra do São Francisco", "BA"));
        lista.add(new Cidade("", "Serra Dourada", "BA"));
        lista.add(new Cidade("", "Serra Grande", "BA"));
        lista.add(new Cidade("", "Serra Preta", "BA"));
        lista.add(new Cidade("", "Serrana", "BA"));
        lista.add(new Cidade("", "Serrinha", "BA"));
        lista.add(new Cidade("", "Serrolândia", "BA"));
        lista.add(new Cidade("", "Simões Filho", "BA"));
        lista.add(new Cidade("", "Sítio da Baraúna", "BA"));
        lista.add(new Cidade("", "Sítio do Mato", "BA"));
        lista.add(new Cidade("", "Sítio do Meio", "BA"));
        lista.add(new Cidade("", "Sítio do Quinto", "BA"));
        lista.add(new Cidade("", "Sítio Grande", "BA"));
        lista.add(new Cidade("", "Sítio Novo", "BA"));
        lista.add(new Cidade("", "Soares", "BA"));
        lista.add(new Cidade("", "Sobradinho", "BA"));
        lista.add(new Cidade("", "Souto Soares", "BA"));
        lista.add(new Cidade("", "Subaúma", "BA"));
        lista.add(new Cidade("", "Sussuarana", "BA"));
        lista.add(new Cidade("", "Tabocas do Brejo Velho", "BA"));
        lista.add(new Cidade("", "Taboleiro do Castro", "BA"));
        lista.add(new Cidade("", "Taboquinhas", "BA"));
        lista.add(new Cidade("", "Taguá", "BA"));
        lista.add(new Cidade("", "Tamburil", "BA"));
        lista.add(new Cidade("", "Tanhaçu", "BA"));
        lista.add(new Cidade("", "Tanque Novo", "BA"));
        lista.add(new Cidade("", "Tanquinho", "BA"));
        lista.add(new Cidade("", "Tanquinho do Poço", "BA"));
        lista.add(new Cidade("", "Taperoá", "BA"));
        lista.add(new Cidade("", "Tapiraípe", "BA"));
        lista.add(new Cidade("", "Tapirama", "BA"));
        lista.add(new Cidade("", "Tapiramutá", "BA"));
        lista.add(new Cidade("", "Tapiranga", "BA"));
        lista.add(new Cidade("", "Tapúia", "BA"));
        lista.add(new Cidade("", "Taquarendi", "BA"));
        lista.add(new Cidade("", "Taquarinha", "BA"));
        lista.add(new Cidade("", "Tartaruga", "BA"));
        lista.add(new Cidade("", "Tauapé", "BA"));
        lista.add(new Cidade("", "Teixeira de Freitas", "BA"));
        lista.add(new Cidade("", "Teodoro Sampaio", "BA"));
        lista.add(new Cidade("", "Teofilândia", "BA"));
        lista.add(new Cidade("", "Teolândia", "BA"));
        lista.add(new Cidade("", "Terra Nova", "BA"));
        lista.add(new Cidade("", "Tijuaçú", "BA"));
        lista.add(new Cidade("", "Tiquaruçu", "BA"));
        lista.add(new Cidade("", "Tracupa", "BA"));
        lista.add(new Cidade("", "Trancoso", "BA"));
        lista.add(new Cidade("", "Tremedal", "BA"));
        lista.add(new Cidade("", "Triunfo do Sincorá", "BA"));
        lista.add(new Cidade("", "Tucano", "BA"));
        lista.add(new Cidade("", "Uauá", "BA"));
        lista.add(new Cidade("", "Ubaíra", "BA"));
        lista.add(new Cidade("", "Ubaitaba", "BA"));
        lista.add(new Cidade("", "Ubatã", "BA"));
        lista.add(new Cidade("", "Ubiracaba", "BA"));
        lista.add(new Cidade("", "Ubiraitá", "BA"));
        lista.add(new Cidade("", "Uibaí", "BA"));
        lista.add(new Cidade("", "Umburanas", "BA"));
        lista.add(new Cidade("", "Umbuzeiro", "BA"));
        lista.add(new Cidade("", "Una", "BA"));
        lista.add(new Cidade("", "Urandi", "BA"));
        lista.add(new Cidade("", "Uruçuca", "BA"));
        lista.add(new Cidade("", "Utinga", "BA"));
        lista.add(new Cidade("", "Vale Verde", "BA"));
        lista.add(new Cidade("", "Valença", "BA"));
        lista.add(new Cidade("", "Valente", "BA"));
        lista.add(new Cidade("", "Valilândia", "BA"));
        lista.add(new Cidade("", "Várzea da Roça", "BA"));
        lista.add(new Cidade("", "Várzea do Caldas", "BA"));
        lista.add(new Cidade("", "Várzea do Cerco", "BA"));
        lista.add(new Cidade("", "Várzea do Poço", "BA"));
        lista.add(new Cidade("", "Varzea Grande", "BA"));
        lista.add(new Cidade("", "Várzea Nova", "BA"));
        lista.add(new Cidade("", "Várzeas", "BA"));
        lista.add(new Cidade("", "Varzedo", "BA"));
        lista.add(new Cidade("", "Velha Boipeba", "BA"));
        lista.add(new Cidade("", "Ventura", "BA"));
        lista.add(new Cidade("", "Vera Cruz", "BA"));
        lista.add(new Cidade("", "Vereda", "BA"));
        lista.add(new Cidade("", "Veredinha", "BA"));
        lista.add(new Cidade("", "Vila do Café", "BA"));
        lista.add(new Cidade("", "Vitória da Conquista", "BA"));
        lista.add(new Cidade("", "Volta da Serra", "BA"));
        lista.add(new Cidade("", "Volta Grande", "BA"));
        lista.add(new Cidade("", "Wagner", "BA"));
        lista.add(new Cidade("", "Wanderley", "BA"));
        lista.add(new Cidade("", "Wenceslau Guimarães", "BA"));
        lista.add(new Cidade("", "Xique-Xique", "BA"));
        return lista;
    }
}
