package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class CE {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("lOHASyJwWcxwNap0bFpX","Abaiara","CE"));
        lista.add(new Cidade("PgzWycklaBqL2liYunPQ","Abílio Martins","CE"));
        lista.add(new Cidade("XvQNY0gqO4WQYsvpXvTF","Acarape","CE"));
        lista.add(new Cidade("jExhLrgNpXO6lyrOZY1Z","Acaraú","CE"));
        lista.add(new Cidade("RQfyKwOQS3qZBddUCMio","Acopiara","CE"));
        lista.add(new Cidade("PU6Dq7Vsv8naSu1skOyx","Açude dos Pinheiros","CE"));
        lista.add(new Cidade("5DsJ4ciw6vaGMULAxkCo","Açudinho","CE"));
        lista.add(new Cidade("nW0NW9xZEhaueJVkDAgv","Açudinho dos Costas","CE"));
        lista.add(new Cidade("OeBtJCqsZHKEoF8KUoVp","Adrianópolis","CE"));
        lista.add(new Cidade("L7lAPpFZdn3hmholjUED","Água Fria","CE"));
        lista.add(new Cidade("srnNTHqay16fYhP1Xd1e","Água Verde","CE"));
        lista.add(new Cidade("RDvb9z7LpPTPYcIqPoeX","Aguaí","CE"));
        lista.add(new Cidade("N7w4mPenEpSEOYdlTcgw","Águas Belas","CE"));
        lista.add(new Cidade("n0pt1nSTarD9TXV8ABcJ","Aiuá","CE"));
        lista.add(new Cidade("r8oItP7w0nu7wOTzkDkL","Aiuaba","CE"));
        lista.add(new Cidade("5IR1QGRsHMebqoupjgP8","Alagoinha","CE"));
        lista.add(new Cidade("HQYngAt3nqijy52FwHOZ","Alazans","CE"));
        lista.add(new Cidade("yvr1qqwpHw7beAk6q6NP","Alcântaras","CE"));
        lista.add(new Cidade("rjCztWNzCcunQAHcfZC2","Algodões","CE"));
        lista.add(new Cidade("CtoNU2jOwPnt8f1IHLHw","Almofala","CE"));
        lista.add(new Cidade("iMSliGoKYvk2t7NU1Uuc","Altaneira","CE"));
        lista.add(new Cidade("v3PqzfSdgwMKvM7gx29x","Alto Lindo","CE"));
        lista.add(new Cidade("0pwoJ5OPnFR72uWBKuAF","Alto Santo","CE"));
        lista.add(new Cidade("kZC5xvAEkoY61Hs0aJW9","Amanaiara","CE"));
        lista.add(new Cidade("gUaWkfhcdd7myPKEts7w","Amanari","CE"));
        lista.add(new Cidade("7JL54Zmyrrh6okMKugbp","Amaniutuba","CE"));
        lista.add(new Cidade("6FnOVkgbF365fvNaEJIN","Amarelas","CE"));
        lista.add(new Cidade("21TyeAsPLjLKtoPvM2xs","Amaro","CE"));
        lista.add(new Cidade("83V2kjDLDPgi6DFb8XyA","América","CE"));
        lista.add(new Cidade("CYZbyVO82DpnQ3lLQrTa","Amontada","CE"));
        lista.add(new Cidade("ZytQTDX97gqusHxNt94L","Anauá","CE"));
        lista.add(new Cidade("GTOhbKXIEzVbZAddgV0h","Anil","CE"));
        lista.add(new Cidade("xThZyiWBsGNs3fzElfK7","Aningás","CE"));
        lista.add(new Cidade("MmOmU09m5yrfqTEcNXMb","Anjinhos","CE"));
        lista.add(new Cidade("T1mcVBBWFOvnAeYAcvIo","Antonina do Norte","CE"));
        lista.add(new Cidade("QknOp1dekD3QuWQIB7oO","Antônio Bezerra","CE"));
        lista.add(new Cidade("JemM9RGGPWy9WNDUQnzt","Antônio Diogo","CE"));
        lista.add(new Cidade("v6c5K2P1dFa8Yg3qWH0B","Antônio Marques","CE"));
        lista.add(new Cidade("V47IN6EfsKLIhyHzXfAK","Aprazível","CE"));
        lista.add(new Cidade("SDY6QrQkyeaQvnyIpao2","Apuiarés","CE"));
        lista.add(new Cidade("6QJ0ohKOu90lGI8BMioF","Aquinópolis","CE"));
        lista.add(new Cidade("6WLu3gmiYblruiyvxmDu","Aquiraz","CE"));
        lista.add(new Cidade("jfztemxrsHck5TyA0ItU","Araçás","CE"));
        lista.add(new Cidade("8Gj0XQooEhqtFzddYZPC","Aracati","CE"));
        lista.add(new Cidade("ix9E62FVQOUIC74l8wXa","Aracatiaçu","CE"));
        lista.add(new Cidade("UxVuofFJ1buVeOP5gDay","Aracatiara","CE"));
        lista.add(new Cidade("svItU22JDb5B6LPXLamp","Aracoiaba","CE"));
        lista.add(new Cidade("9QtqGo4U62c3m55t2cVU","Arajara","CE"));
        lista.add(new Cidade("iLaKrg4M5VaePXeDahvP","Aranaú","CE"));
        lista.add(new Cidade("i6LimXRShXsMdgMA2roi","Arapá","CE"));
        lista.add(new Cidade("Mug0I2UaclBF3WIiW8tU","Arapari","CE"));
        lista.add(new Cidade("Ee3AEb0jaAO72vbbFnEe","Araporanga","CE"));
        lista.add(new Cidade("otj1BkfRAtaruUAa8HT6","Araquém","CE"));
        lista.add(new Cidade("m4mJhT9n3GrNC1vzjbsA","Ararendá","CE"));
        lista.add(new Cidade("Ip8vv4M4YI9iXXq1bccI","Araripe","CE"));
        lista.add(new Cidade("FTANjgN9rLSRAWI2wvn5","Arariús","CE"));
        lista.add(new Cidade("oY62gBOBU3fGAqCr8HU5","Aratama","CE"));
        lista.add(new Cidade("QzWKizTfm55BnMAcaRA7","Araticum","CE"));
        lista.add(new Cidade("qlxj1GBb3MVLldAZ03DL","Aratuba","CE"));
        lista.add(new Cidade("4vHgecDTgdsuNsSldpLV","Areial","CE"));
        lista.add(new Cidade("dWsqjyaS4zk3yTOZduXe","Areré","CE"));
        lista.add(new Cidade("beYshlF04lS2IJn3KfHw","Ariscos dos Marianos","CE"));
        lista.add(new Cidade("Gm3gAZDC1rrL6hbRN39G","Arneiroz","CE"));
        lista.add(new Cidade("xIyKHZ7liOtEJjHoRztN","Aroeiras","CE"));
        lista.add(new Cidade("2J2FbsWh4DyHyW3BC3XU","Arrojado","CE"));
        lista.add(new Cidade("eF2efQeTyoUwGj09JdEb","Aruaru","CE"));
        lista.add(new Cidade("AwQLYC7e2Mu9Nzj8PEpV","Assaré","CE"));
        lista.add(new Cidade("6Ae0mXf5GxYjG4Wd1eRd","Assis","CE"));
        lista.add(new Cidade("l8ArytBqhASma4DPictU","Assunção","CE"));
        lista.add(new Cidade("vgD7SG348a12ziDg61kO","Aurora","CE"));
        lista.add(new Cidade("mDRhgPbJlfG1WKNuOG9M","Baixa Fria","CE"));
        lista.add(new Cidade("imZsInGdNIOHC0I3KcRL","Baixa Grande","CE"));
        lista.add(new Cidade("ryQcy3garyAqo2ypiaSb","Baixio","CE"));
        lista.add(new Cidade("j4Mp6zBwV0zP8mmagT57","Baixio da Donana","CE"));
        lista.add(new Cidade("PATQyuj9nKfLvUQdJ7Cr","Baixio das Palmeiras","CE"));
        lista.add(new Cidade("cjcvkzsYlABCfohL2NkZ","Baleia","CE"));
        lista.add(new Cidade("pwhrcAE1Tf9GooIS1vJH","Balseiros","CE"));
        lista.add(new Cidade("O48r7xz69nHha6qKrn3V","Banabuiú","CE"));
        lista.add(new Cidade("SqguXZpGg00BG6AwBhH0","Bandeira","CE"));
        lista.add(new Cidade("2S6lWZKj024uOXpq2wMl","Baracho","CE"));
        lista.add(new Cidade("9YBlIyiyRN17eU099lfw","Barão de Aquiraz","CE"));
        lista.add(new Cidade("6XlWzf5F5ahE5e1odYGz","Barbada","CE"));
        lista.add(new Cidade("9kwcKTOzsieSeokJZmes","Barbalha","CE"));
        lista.add(new Cidade("WfXDy0IaaZSd7btogEAE","Barra","CE"));
        lista.add(new Cidade("FMCpvU2bcLN5AI0MqxIg","Barra do Ingá","CE"));
        lista.add(new Cidade("6d9NTHlBePoPh3zMhfX6","Barra do Sotero","CE"));
        lista.add(new Cidade("ZFnsRoWp4Mdl2f2lQk6Y","Barra Nova","CE"));
        lista.add(new Cidade("5KdcKHrmEBqXRgyKXrO9","Barreira","CE"));
        lista.add(new Cidade("Yox72PVvCF2w6XTrRz24","Barreira dos Vianas","CE"));
        lista.add(new Cidade("vCeLmlIuz3riZT8BB2cK","Barreiras","CE"));
        lista.add(new Cidade("OtEacaCI8syPRgAy5E4b","Barreiros","CE"));
        lista.add(new Cidade("8RLaJctaD7CMchCqLWyB","Barrento","CE"));
        lista.add(new Cidade("aCJ3xP7eraFOjpQ61LxW","Barrinha","CE"));
        lista.add(new Cidade("hsxL4KZycnFpUnCSITyH","Barro","CE"));
        lista.add(new Cidade("29trZXDkfIzIR8odrkk5","Barro Alto","CE"));
        lista.add(new Cidade("KZFxuMvJ4Zg33nZ1IFKl","Barroquinha","CE"));
        lista.add(new Cidade("RdbNA29k52RjOei9YBfx","Bastiões","CE"));
        lista.add(new Cidade("XlS7KncXyRw1fVThLwOn","Baturité","CE"));
        lista.add(new Cidade("Xdbu6mYrU3jTsvHuBVYp","Baú","CE"));
        lista.add(new Cidade("IPqgZUWN3iQpWMOSSa7L","Beberibe","CE"));
        lista.add(new Cidade("4RxAorNpQ23d2GX8Rxqa","Bela Cruz","CE"));
        lista.add(new Cidade("RPOem4TwxqXHQ7SyinR8","Bela Vista","CE"));
        lista.add(new Cidade("Rq8gUe2jZe8yoJKW11yz","Belém","CE"));
        lista.add(new Cidade("hI4662bA6snTU82YBz6m","Belmonte","CE"));
        lista.add(new Cidade("lDhGTI05LocCk25AOIKj","Betânia","CE"));
        lista.add(new Cidade("luDavPBxHfuAdlpDLexT","Bilheira","CE"));
        lista.add(new Cidade("6IaNqAqpkhjH3rwiYjod","Bitupitá","CE"));
        lista.add(new Cidade("Nq7P8azyz5TR4c25RIry","Bixopa","CE"));
        lista.add(new Cidade("lbrfr15urzwOC9iXBrDj","Boa Água","CE"));
        lista.add(new Cidade("mJfshdV765DdOkw8thOL","Boa Esperança","CE"));
        lista.add(new Cidade("MAdQXsp2iMSeBqx3kBRt","Boa Viagem","CE"));
        lista.add(new Cidade("3jN4ljnyMfNPhNtRwDXg","Boa Vista","CE"));
        lista.add(new Cidade("AHs9LH1h65IgGWn23gXf","Boa Vista do Caxitoré","CE"));
        lista.add(new Cidade("LsbkAznftuqe1CPhtiWL","Bom Princípio","CE"));
        lista.add(new Cidade("va17kIHF26W6BJiGra0O","Bonfim","CE"));
        lista.add(new Cidade("ZtAOXk7cdraUydZExt8F","Bonhu","CE"));
        lista.add(new Cidade("uAnfrxLp0pqE8YKhPrjU","Bonito","CE"));
        lista.add(new Cidade("yEMiAtxm6esVNNSaGhu6","Boqueirão","CE"));
        lista.add(new Cidade("CIiFok5b1W7iwrhqbDhU","Borges","CE"));
        lista.add(new Cidade("xtfdG8mAHhx2tHsW1bzi","Brejinho","CE"));
        lista.add(new Cidade("86tYqF9JY0ZznMo9bD0U","Brejo Grande","CE"));
        lista.add(new Cidade("BMvWQQkfnzsqSC7O0sif","Brejo Santo","CE"));
        lista.add(new Cidade("l6490ZOIf38gR8CieJSw","Brotas","CE"));
        lista.add(new Cidade("3ifTVygOPq0IIcZsTMDA","Buritizal","CE"));
        lista.add(new Cidade("yPOh3XHKv5s0zeoehLHP","Buritizinho","CE"));
        lista.add(new Cidade("03AECvJGtF39AgLvC9qk","Cabreiro","CE"));
        lista.add(new Cidade("kkEcdEzAEBnMufJ0prWY","Cachoeira","CE"));
        lista.add(new Cidade("lftedx4za7RPmlsmI6Xf","Cachoeira de Fora","CE"));
        lista.add(new Cidade("SeKqkvfu2J0wSidz8uxe","Cachoeira Grande","CE"));
        lista.add(new Cidade("m7KMP7WfICDrBgm1TP22","Cacimba Nova","CE"));
        lista.add(new Cidade("xdWcfAoiFeHec9lYziyM","Cacimbas","CE"));
        lista.add(new Cidade("WkNa4Fiy4ZKrqPbRF2sx","Caiçara","CE"));
        lista.add(new Cidade("puXoFtfD6XLCGuhGLuHO","Caiçarinha","CE"));
        lista.add(new Cidade("cd6bFVNkFt3Q6nj9ZNXt","Caio Prado","CE"));
        lista.add(new Cidade("4gLsz8UiPFyLWzN4P7WE","Caioca","CE"));
        lista.add(new Cidade("E9GEsUDyBueg6GRCFL8m","Caipu","CE"));
        lista.add(new Cidade("qdbnwkHGswfSHRTKLNeE","Cajazeiras","CE"));
        lista.add(new Cidade("Vv3znbySXxVNIXE1Ko4a","Cajueiro","CE"));
        lista.add(new Cidade("VuVehx10KfDtosCaPr2x","Calabaça","CE"));
        lista.add(new Cidade("SCIjccGhNF5jUWOIcdLo","Caldas","CE"));
        lista.add(new Cidade("T1CD7aX5D1ZUbpMs6xEB","Caldeirão","CE"));
        lista.add(new Cidade("j3l6xt9ZVejaRgwR9E7t","Califórnia","CE"));
        lista.add(new Cidade("wN2Mvt1ntG43QIy7Uaf8","Camará","CE"));
        lista.add(new Cidade("IUdyznmI9yeSyP8OfoLm","Camboas","CE"));
        lista.add(new Cidade("SQA59UAl6u0KaMntZ2mj","Camilos","CE"));
        lista.add(new Cidade("eDuww8XA0tRpFYNbkUvJ","Camocim","CE"));
        lista.add(new Cidade("P3cqLLuiVi2b9IaGmlIZ","Campanário","CE"));
        lista.add(new Cidade("xYXyMiKw6oA56yY0glL9","Campestre","CE"));
        lista.add(new Cidade("9t5Ys78cT0SQBQMmdBRd","Campo Alegre","CE"));
        lista.add(new Cidade("ys6Zgct7QEE0txmyB2SK","Campos","CE"));
        lista.add(new Cidade("9ZFTGJAZSBPO5OVOBAZs","Campos Belos","CE"));
        lista.add(new Cidade("IBVh9c9uRfa7ZATNDO13","Campos Sales","CE"));
        lista.add(new Cidade("19D0gAtXdttX9iVSv0AI","Canaan","CE"));
        lista.add(new Cidade("44obX0j7CmibclbzmBz5","Canafistula","CE"));
        lista.add(new Cidade("IVmDu5cOjwo2MkCeDcIT","Canaúna","CE"));
        lista.add(new Cidade("CJ2tvDHC0J4JZJe3Ig2B","Cangati","CE"));
        lista.add(new Cidade("r6W8e3OQXEOjdRlFiMU4","Canindé","CE"));
        lista.add(new Cidade("Rsmkl6nFUNyp0hvLeNna","Canindezinho","CE"));
        lista.add(new Cidade("hQweIkdDO67voGRpRfoO","Canta Galo","CE"));
        lista.add(new Cidade("RY5nRAnGfuCGRDRaBuR8","Capim de Roça","CE"));
        lista.add(new Cidade("iWUqeD7wmpAHCMlDGVO4","Capistrano","CE"));
        lista.add(new Cidade("swQsTpdrRy1Z4SWes2Hb","Capitão Mor","CE"));
        lista.add(new Cidade("MRv6qlAhKdrvKmoryTGJ","Capitão Pedro Sampaio","CE"));
        lista.add(new Cidade("Os001xUaHh0b7lmKOh56","Caponga","CE"));
        lista.add(new Cidade("IGHiGWZRswXwTu8NtWMl","Caponga da Bernarda","CE"));
        lista.add(new Cidade("greYdwucTIAkKpZqj0vA","Caponguinha","CE"));
        lista.add(new Cidade("KKd9dqdaqtaVfVTRRVRk","Caracará","CE"));
        lista.add(new Cidade("noOjv4Bzzq1HGS2aHxcL","Caridade","CE"));
        lista.add(new Cidade("RZVY1oQEzDhTTqouLPVy","Cariré","CE"));
        lista.add(new Cidade("2Y54UNxpkdVcCLEB0Zvt","Caririaçu","CE"));
        lista.add(new Cidade("S3rG5KFR6J2wixjFZgGf","Cariús","CE"));
        lista.add(new Cidade("Rg3SE65pEas94TW7fiYS","Cariutaba","CE"));
        lista.add(new Cidade("G8X9FTsvjytFVa7UzXbz","Carmelópolis","CE"));
        lista.add(new Cidade("80eyaYiBSwyGh6mMAewi","Carnaúba","CE"));
        lista.add(new Cidade("nscl2FLkVsyWGPIS4dpd","Carnaubal","CE"));
        lista.add(new Cidade("SWYHBq5yuq6cIL7sjgvQ","Carnaúbas","CE"));
        lista.add(new Cidade("6oACMlkfotwwnU1xGtjR","Carnaubinha","CE"));
        lista.add(new Cidade("MpZt2fmxWINawNTgjP8r","Carquejo","CE"));
        lista.add(new Cidade("iH0suboH4nDQUoLmZZTv","Carrapateiras","CE"));
        lista.add(new Cidade("E36p7jXfqZHTgbYfgBF7","Caruataí","CE"));
        lista.add(new Cidade("DKvalD8vZ00uJ87FHUEd","Carvalho","CE"));
        lista.add(new Cidade("879oWY4p8AxLF6EybxqA","Carvoeiro","CE"));
        lista.add(new Cidade("I83JUge49OYcqvV8mIGN","Cascavel","CE"));
        lista.add(new Cidade("7BZh8OhflNKgA2J7xzlb","Castanhão","CE"));
        lista.add(new Cidade("DebVRFmlCpdJoNkNcRYb","Catarina","CE"));
        lista.add(new Cidade("dmSV3W4I3Yo0gsbgajeZ","Catolé","CE"));
        lista.add(new Cidade("8vu12SxcWlfIUlSQvWPT","Catolé da Pista","CE"));
        lista.add(new Cidade("Kn69Udxr1dB4QrCcDfDb","Catuana","CE"));
        lista.add(new Cidade("kAZlhguJ85TnbdOYBCHK","Catunda","CE"));
        lista.add(new Cidade("3efLIfZ7QkLiPZvVpMi2","Caucaia","CE"));
        lista.add(new Cidade("3IY2HnKEWOYbactakBbn","Caxitoré","CE"));
        lista.add(new Cidade("3jw1TW5ZhtaFRH6nBcvb","Cedro","CE"));
        lista.add(new Cidade("TMFKFFL78kJJRxFypzIh","Cemoaba","CE"));
        lista.add(new Cidade("aLvG03g7CuzXzUQPbVJ9","Chaval","CE"));
        lista.add(new Cidade("rbtx62WPb7kQrv1Yr7t2","Chile","CE"));
        lista.add(new Cidade("NSU7TX9ekzdKTq4azdIr","Choró","CE"));
        lista.add(new Cidade("piEb9xURyQxZT03rfEXn","Chorozinho","CE"));
        lista.add(new Cidade("rJzgxBBtWLLBpjre7A9c","Cipó","CE"));
        lista.add(new Cidade("ihbpFUCSRnDWCoTOOMkI","Cipó dos Anjos","CE"));
        lista.add(new Cidade("OlD9P6PyApO9NFOHCSc4","Cococi","CE"));
        lista.add(new Cidade("nfRB9rU5aCyx30fp5CTa","Codiá","CE"));
        lista.add(new Cidade("DUZAcAQL1gf77wgfPTMo","Coité","CE"));
        lista.add(new Cidade("GIbfOunj3wFpRHsY13f2","Colina","CE"));
        lista.add(new Cidade("L5NRLDngX1LtTYgymamV","Conceição","CE"));
        lista.add(new Cidade("1sVtlfvJUyGxQxtQPMe6","Coreaú","CE"));
        lista.add(new Cidade("UjbrpCpgKSRqDBwlTEwJ","Córrego","CE"));
        lista.add(new Cidade("vxcSzCc1nDSEZAHioUJx","Córrego dos Fernandes","CE"));
        lista.add(new Cidade("fqagh1VxcU26g4pw08Ot","Corrente","CE"));
        lista.add(new Cidade("7XHhJKgFQHVti6pXJCSg","Crateús","CE"));
        lista.add(new Cidade("dzJl1dQSp5bW0wdFr1gS","Crato","CE"));
        lista.add(new Cidade("nATQ8yQKeOGhTNfGisSQ","Crioulos","CE"));
        lista.add(new Cidade("pmOLxd2PCUuBb5ekqneJ","Cristais","CE"));
        lista.add(new Cidade("j7CWAacBZWLdyRl7SkS2","Croatá","CE"));
        lista.add(new Cidade("vfOv62kHvtwGycqbpHrz","Cruxati","CE"));
        lista.add(new Cidade("uufSOYYl06FZuV6g30hz","Cruz","CE"));
        lista.add(new Cidade("teo4KTHg88lODWj94Rcx","Cruz de Pedra","CE"));
        lista.add(new Cidade("daY5Hnfu910892SX57zz","Cruzeirinho","CE"));
        lista.add(new Cidade("6daOV4MXlagz409UjZwz","Cuncas","CE"));
        lista.add(new Cidade("cQ0WzPyJt1qwcYha4hAh","Curatis","CE"));
        lista.add(new Cidade("WhYPfd72gFJE5CMLgCTP","Curral Velho","CE"));
        lista.add(new Cidade("9mYTzrUsp1AD2HuwhAlC","Curupira","CE"));
        lista.add(new Cidade("328abloFuluZ1zvkIZJS","Custódio","CE"));
        lista.add(new Cidade("4Fsy2cF1SI93nmK6GYwu","Damião Carneiro","CE"));
        lista.add(new Cidade("koRLOiHl2qxhuws1vMut","Daniel de Queirós","CE"));
        lista.add(new Cidade("2mKcyp7sTBHLaPi4WG3K","Delmiro Gouveia","CE"));
        lista.add(new Cidade("AwTXnyWuMDrGbErqt1dr","Deputado Irapuan Pinheiro","CE"));
        lista.add(new Cidade("8GMCmIkK36shglLECIMi","Deserto","CE"));
        lista.add(new Cidade("ozcHHFwrIyvsX54tDsef","Dom Leme","CE"));
        lista.add(new Cidade("LFhcZrjg8cwoThx7w7LM","Dom Maurício","CE"));
        lista.add(new Cidade("4sqr0m3zYhyQ6iKQFCau","Dom Quintino","CE"));
        lista.add(new Cidade("d4gXoFtKAEJjkZEKBEbH","Domingos da Costa","CE"));
        lista.add(new Cidade("S4o3WZRzPbg7ZjaAhnJE","Donato","CE"));
        lista.add(new Cidade("Hyh1VundKf9wSiWYo7K3","Dourado","CE"));
        lista.add(new Cidade("NW3suCC373nLlzvdGrio","Ebron","CE"));
        lista.add(new Cidade("7uOWrWTBwJkPkh4Fcnn4","Ema","CE"));
        lista.add(new Cidade("O3FrHK7DyElCGKMACrAa","Ematuba","CE"));
        lista.add(new Cidade("tiAGgKQbx9Jytyh5ZtKf","Encantado","CE"));
        lista.add(new Cidade("wisXzQjLhTJyNNzlTtvN","Engenheiro João Tomé","CE"));
        lista.add(new Cidade("LJTabQutcPT1iRSqA7I3","Engenheiro José Lopes","CE"));
        lista.add(new Cidade("YnMieUgQcRBrjyIJvZ3G","Engenho Velho","CE"));
        lista.add(new Cidade("mHntlMUnFlSbqlEC3yLj","Ererê","CE"));
        lista.add(new Cidade("Nm0rOZAoE7CuQUs5Zrmw","Espacinha","CE"));
        lista.add(new Cidade("mjzSY7DsWUWocszzILBv","Esperança","CE"));
        lista.add(new Cidade("xo5ZwZ8ttuAO8gE73Azg","Estrela","CE"));
        lista.add(new Cidade("0lNIKNPH2G4iFpVsxcox","Eusébio","CE"));
        lista.add(new Cidade("BDBBJkeunAAgmCr5QFaK","Faísca","CE"));
        lista.add(new Cidade("3xGy7qxfcSjbA1NPAsff","Farias Brito","CE"));
        lista.add(new Cidade("R0gpEmfIvFYTfXfUEu5m","Fátima","CE"));
        lista.add(new Cidade("fcDJeG7qtWXP4PlMTFyD","Faveira","CE"));
        lista.add(new Cidade("oDuuHHY3Py5ZScyTcrDJ","Feiticeiro","CE"));
        lista.add(new Cidade("bNL59on7aoiT3ZJfLME8","Feitosa","CE"));
        lista.add(new Cidade("FBNf5B6pMoncMHO6AadE","Felipe","CE"));
        lista.add(new Cidade("tcHDPb9SnQdFpwgSeRtj","Felizardo","CE"));
        lista.add(new Cidade("hzEDJMFvMb8BEB6L6bUN","Flamengo","CE"));
        lista.add(new Cidade("n2r9ihnuZN7Au39NBOkW","Flores","CE"));
        lista.add(new Cidade("1cl4qfoip8YdDHfXSNcE","Forquilha","CE"));
        lista.add(new Cidade("I5nt88WIuAFyctT2IXor","Fortaleza","CE"));
        lista.add(new Cidade("5SO2TyghsohcnJc0e83O","Fortim","CE"));
        lista.add(new Cidade("g8tq2Qx7OlaD615R10mY","Frecheirinha","CE"));
        lista.add(new Cidade("mYTuOsaihRBi1NCWBXvJ","Gadelha","CE"));
        lista.add(new Cidade("ew2sB3v61bEpDgVSkApf","Gado","CE"));
        lista.add(new Cidade("8nqgTOhbj7hvy3N3KOUv","Gado dos Rodrigues","CE"));
        lista.add(new Cidade("7YfSVLrrio3CgokazQrG","Gameleira de São Sebastião","CE"));
        lista.add(new Cidade("jG275Hy7ZGXUvz94NnDi","Garças","CE"));
        lista.add(new Cidade("qEQawS4lClyRbT7rfMpC","Gavião","CE"));
        lista.add(new Cidade("PHeDliA0MX5SFNKsySBF","Gázea","CE"));
        lista.add(new Cidade("SEP3T1oyjx0DFQr7LvD8","General Sampaio","CE"));
        lista.add(new Cidade("1n4JTQ4chUPQRyrH2TFa","General Tibúrcio","CE"));
        lista.add(new Cidade("TcilMV3jNEfBLAtzfbtT","Gereraú","CE"));
        lista.add(new Cidade("32yonGyVIyFpWhCMV2Dh","Giqui","CE"));
        lista.add(new Cidade("KAM2FcaaZ1ZoZix25Vkc","Girau","CE"));
        lista.add(new Cidade("0SaoI6VLdAdZwBBd4UXd","Graça","CE"));
        lista.add(new Cidade("8TcjpYSwBecvCEohDgnP","Grande Basílio","CE"));
        lista.add(new Cidade("LjfvA4IR91dreYyFcBjo","Granja","CE"));
        lista.add(new Cidade("YJ7FJ4oQnVwmgDmFWetn","Granjeiro","CE"));
        lista.add(new Cidade("TnC7VP7LqtSpGjJkBeLE","Groairas","CE"));
        lista.add(new Cidade("SzDXDO3k594yVs2Rr01U","Guaiúba","CE"));
        lista.add(new Cidade("qGHVi4o0loppchRHvCkq","Guajiru","CE"));
        lista.add(new Cidade("ziDukfPxS2HSgO8U2kTj","Guanacés","CE"));
        lista.add(new Cidade("yrMd58GY3lbyAY0PuO7x","Guaraciaba do Norte","CE"));
        lista.add(new Cidade("UH1d1ptLgLhqzl1P160b","Guaramiranga","CE"));
        lista.add(new Cidade("tR5s4SZVSX8k1RECmm4S","Guararu","CE"));
        lista.add(new Cidade("wuVzXWIxu3PzW1Q6Oj2D","Guassi","CE"));
        lista.add(new Cidade("yuqojqhPElbBCO9QzKmP","Guassossé","CE"));
        lista.add(new Cidade("U71XWDS3fYp5vNZteIKO","Guassussê","CE"));
        lista.add(new Cidade("AMgF4QbiItBPN5aDYrSR","Guia","CE"));
        lista.add(new Cidade("9gxNxUnuPkMpJnpsytKQ","Guriú","CE"));
        lista.add(new Cidade("daJxlytrsbfuIju2zheF","Hidrolândia","CE"));
        lista.add(new Cidade("0SXkwIpeuA5Z3kX8rYvh","Holanda","CE"));
        lista.add(new Cidade("1XnQnyBTYNseKhVhfU2w","Horizonte","CE"));
        lista.add(new Cidade("Q2FWdhUR9f62008fvwZl","Iapi","CE"));
        lista.add(new Cidade("vkYbJu2CNNYu2Ha7qCa6","Iara","CE"));
        lista.add(new Cidade("sE6qsSwCeWknm2oFccSe","Ibaretama","CE"));
        lista.add(new Cidade("SXiQfwGaSOLxuDbl0VAc","Ibiapaba","CE"));
        lista.add(new Cidade("zFO5T7Yg1g1M3oPFPEiY","Ibiapina","CE"));
        lista.add(new Cidade("GDUIuHdkLvXX1DSFX5B8","Ibicatu","CE"));
        lista.add(new Cidade("TIMHmEjBfEysoETD2D8I","Ibicuã","CE"));
        lista.add(new Cidade("a0xTYPD2NL86bHuXIRce","Ibicuitaba","CE"));
        lista.add(new Cidade("Pz1fp687zLZIOrImn8Fa","Ibicuitinga","CE"));
        lista.add(new Cidade("qlfk3IQlLGc6ml8oJTiX","Iborepi","CE"));
        lista.add(new Cidade("KWAJSuX88TXdz1GvRCYY","Ibuaçu","CE"));
        lista.add(new Cidade("q3kriRx7pHwB93KhXL9K","Ibuguaçu","CE"));
        lista.add(new Cidade("tZ29sVPZdDKHFoTuMytf","Icapuí","CE"));
        lista.add(new Cidade("AeMFUJ0xQy6c5ka9Hwx0","Icaraí","CE"));
        lista.add(new Cidade("HgrItDfo1HSrBI45VRw1","Icó","CE"));
        lista.add(new Cidade("rnm8ClTWropE93vH1gsz","Icozinho","CE"));
        lista.add(new Cidade("vzHnHEJ7iLluPFfHvr6R","Ideal","CE"));
        lista.add(new Cidade("saDFpujCEwTv0kQ0lCjm","Igaroi","CE"));
        lista.add(new Cidade("02U5Eo6fsfGYRPRIfzQO","Iguaçu","CE"));
        lista.add(new Cidade("ztAa4L0tsUYESOHCrZcN","Iguatu","CE"));
        lista.add(new Cidade("TInkUzwOPI43bv52v9gY","Independência","CE"));
        lista.add(new Cidade("r8xpIrcds7Lnauak8a9b","Ingazeiras","CE"));
        lista.add(new Cidade("YEG7tSo89pUkjnx8N4ae","Inhamuns","CE"));
        lista.add(new Cidade("Q71bNuwQjXSW7t6Bc0ZP","Inhuçu","CE"));
        lista.add(new Cidade("w4vsp1GBquYj1i7KBBfj","Inhuporanga","CE"));
        lista.add(new Cidade("IineSGtKZQK00WzuGxOw","Ipaguaçú","CE"));
        lista.add(new Cidade("Xp87nAfAy27IqPsm8S5Z","Ipaporanga","CE"));
        lista.add(new Cidade("SiGx78O79e48HcIL3QvR","Ipaumirim","CE"));
        lista.add(new Cidade("bcx3uIcavIJMA57MiGDy","Ipiranga","CE"));
        lista.add(new Cidade("brr70AzgjCr3ASGzxt82","Ipu","CE"));
        lista.add(new Cidade("AM6eDGlrWCHpg5vRvusE","Ipueiras","CE"));
        lista.add(new Cidade("fYlk7k4J4vMqtt48MWkH","Ipueiras dos Gomes","CE"));
        lista.add(new Cidade("103ltU69SBNAkH9Pqr6d","Iracema","CE"));
        lista.add(new Cidade("UCu7Ru00NaDFSIb5yz9n","Irajá","CE"));
        lista.add(new Cidade("wG99Pn97eQKMQhXom4cf","Irapuã","CE"));
        lista.add(new Cidade("1OTCj5X7u4GZNJVpQdDD","Iratinga","CE"));
        lista.add(new Cidade("LeUdnX5GY00SKn8K1FSe","Irauçuba","CE"));
        lista.add(new Cidade("FjlX55dBQb5BKCUr4rkr","Isidoro","CE"));
        lista.add(new Cidade("ZFXkwvtdIn9buQ1S2LXU","Itacima","CE"));
        lista.add(new Cidade("TRLPCaY6AC9YznARYn0T","Itacolomy","CE"));
        lista.add(new Cidade("BQJS66eVMKkTUNntbjc5","Itaguá","CE"));
        lista.add(new Cidade("SeRaEvWpuF1t2AEikpqk","Itaguaruna","CE"));
        lista.add(new Cidade("HfvimuuwBCO3p4GxQwBZ","Itaiçaba","CE"));
        lista.add(new Cidade("aIb5ZYeKzvvIVQ6uEW4P","Itaipaba","CE"));
        lista.add(new Cidade("GiI4lOsJTD3HBpUP8Qq7","Itaitinga","CE"));
        lista.add(new Cidade("GiLIyisMuiHJg8cFXU6M","Itamaracá","CE"));
        lista.add(new Cidade("nnXLckJ2zEp0UQWftIEU","Itans","CE"));
        lista.add(new Cidade("l4O0jr7gQtJofowvpHy4","Itapajé","CE"));
        lista.add(new Cidade("8fhPm0HgEpENYOaKzdvu","Itapebussu","CE"));
        lista.add(new Cidade("57LwD3tSCubpz2EOB2AE","Itapeim","CE"));
        lista.add(new Cidade("awSXG35f03FKs1UQyNaX","Itapipoca","CE"));
        lista.add(new Cidade("mP3tiDTu5VPmVBLfdNN0","Itapiúna","CE"));
        lista.add(new Cidade("Mmo3MIFtCVXr5R3vcXfw","Itapó","CE"));
        lista.add(new Cidade("XYYOsp8Uz4eXI6SijaK3","Itarema","CE"));
        lista.add(new Cidade("mcjwfQ3vftAdNUq6B9bZ","Itatira","CE"));
        lista.add(new Cidade("F0rklGbrQNN8U7PXPmPF","Jaburuna","CE"));
        lista.add(new Cidade("aArQ8MYUhyvbjlZiFUMx","Jacampari","CE"));
        lista.add(new Cidade("qUnxNIRBLVOMxX5vooWe","Jacarecoara","CE"));
        lista.add(new Cidade("HbjCBjuvTDwLuZfWUM5G","Jacaúna","CE"));
        lista.add(new Cidade("KGqucNWzKv1JZvZKFq6T","Jaguarão","CE"));
        lista.add(new Cidade("PBhj12HD12O1Mb2yQsbk","Jaguaretama","CE"));
        lista.add(new Cidade("wrvCQsfIRr0YASCJlxzG","Jaguaribara","CE"));
        lista.add(new Cidade("dn7bWfjG1FOJbkgkpFkP","Jaguaribe","CE"));
        lista.add(new Cidade("kQVVmD8srarxtWCTmLEm","Jaguaruana","CE"));
        lista.add(new Cidade("EjXpfCDB8fZ8EPbB8kJM","Jaibaras","CE"));
        lista.add(new Cidade("7dORbriLFeRCO7W6xJDf","Jamacaru","CE"));
        lista.add(new Cidade("n3EmNLWaq4DFaM9ZjzK1","Jandrangoeira","CE"));
        lista.add(new Cidade("KTOu1CfYG6QiIGEx01aA","Jardim","CE"));
        lista.add(new Cidade("4jvXRGExozS3QmNftZ0p","Jardimirim","CE"));
        lista.add(new Cidade("tPa9b0JM7zwHWQUhTb9x","Jati","CE"));
        lista.add(new Cidade("JqoUY8aq6OSVpSy1tAJM","Jenipapeiro","CE"));
        lista.add(new Cidade("tS79IScsyl3bErVsFdST","Jijoca de Jericoacoara","CE"));
        lista.add(new Cidade("YgvgvfsxnJQ5M4XEmJyP","João Cordeiro","CE"));
        lista.add(new Cidade("P1ZdcgknaxhglG0ok7Uj","Jordão","CE"));
        lista.add(new Cidade("zgU4J0ipU0XKPR2WWwva","José de Alencar","CE"));
        lista.add(new Cidade("iDcBlSIrJSz9oE5Uq0PN","Juá","CE"));
        lista.add(new Cidade("8MnMZD9VmOZUsjRsFaNH","Juatama","CE"));
        lista.add(new Cidade("fCi7z8E1ybXkIM4ujzPh","Juazeiro de Baixo","CE"));
        lista.add(new Cidade("HTFzgame8fW2Ajp40c4D","Juazeiro do Norte","CE"));
        lista.add(new Cidade("OO8SaFFGdhUAjgngFzAD","Jubaia","CE"));
        lista.add(new Cidade("MT0MbfucGvAVnbsfPd7B","Jucá","CE"));
        lista.add(new Cidade("UFXyXLHMzmpKgd5xOctT","Jucás","CE"));
        lista.add(new Cidade("TmkpQUh5tZsSrxqPfn8O","Jurema","CE"));
        lista.add(new Cidade("BJCl3qbXAWHiZ5YnQE2z","Juritianha","CE"));
        lista.add(new Cidade("pUHs9hp0iTJTzr423YLk","Justiniano Serpa","CE"));
        lista.add(new Cidade("VcV5mllEGUEifxyHnkYu","Lacerda","CE"));
        lista.add(new Cidade("AGWpYCHUfM0qIihuMAEp","Ladeira Grande","CE"));
        lista.add(new Cidade("rKJUOhPrnZ0qbTOTCUtE","Lages","CE"));
        lista.add(new Cidade("B3gg5oB1HZ1i2PDpQ9Ac","Lagoa da Cruz","CE"));
        lista.add(new Cidade("1vGOHNfDD1GldURw2ju9","Lagoa das Pedras","CE"));
        lista.add(new Cidade("r4OIMtK9bCVBy8qIYKnO","Lagoa de São João","CE"));
        lista.add(new Cidade("ERR04muAuZN9Glktcl3q","Lagoa do Barro","CE"));
        lista.add(new Cidade("7gWe5zlesNsfJMDIYmCx","Lagoa do Carneiro","CE"));
        lista.add(new Cidade("hDYEgLAqUJVdV2fht6t4","Lagoa do Juvenal","CE"));
        lista.add(new Cidade("HTFWwSukyTq09y9khayM","Lagoa do Mato","CE"));
        lista.add(new Cidade("tKYeYdax4TwBZHnSOYWP","Lagoa dos Crioulos","CE"));
        lista.add(new Cidade("Md608uwnLntbZn4VC5VZ","Lagoa Grande","CE"));
        lista.add(new Cidade("tOfiOIXM2anwY1CjoTcT","Lagoinha","CE"));
        lista.add(new Cidade("4q4wHkuzbhvmiFwxOqqL","Lambedouro","CE"));
        lista.add(new Cidade("AMSDk0lpSoWDY5zyLnp6","Lameiro","CE"));
        lista.add(new Cidade("5TgA76m2gQEfcJYAeAig","Lapa","CE"));
        lista.add(new Cidade("STwaXJq4WBzW0PhWbwaL","Laranjeiras","CE"));
        lista.add(new Cidade("AdaP7ztZrUkPieC1Gu4Z","Lavras da Mangabeira","CE"));
        lista.add(new Cidade("hseMrWfPCjmkHk4sBTTK","Lima Campos","CE"));
        lista.add(new Cidade("78ZSDfVCDZURZUXY7hib","Limoeiro do Norte","CE"));
        lista.add(new Cidade("05CKjcRyoZFbNtvQASON","Lisieux","CE"));
        lista.add(new Cidade("B4Ac1pyCOws1onkLHSuQ","Livramento","CE"));
        lista.add(new Cidade("pxiEfTxl419IpcBryz5t","Logradouro","CE"));
        lista.add(new Cidade("DlaW92T5pifh0JqCZSVM","Macambira","CE"));
        lista.add(new Cidade("bgezZ89HT2Zr8IzJkQR7","Macaóca","CE"));
        lista.add(new Cidade("VDktgwnNaXyGEY3HeAXL","Macaraú","CE"));
        lista.add(new Cidade("LSfwku96qSenxscFLgDF","Maceió","CE"));
        lista.add(new Cidade("y4nBp5L5B3iaVwbfZeNz","Madalena","CE"));
        lista.add(new Cidade("kMkkew8ocG3zuikws5NU","Major Simplício","CE"));
        lista.add(new Cidade("a2mgAE9w8061Fq5QV6Dg","Majorlândia","CE"));
        lista.add(new Cidade("940JnBc8eRlgXIIN32wx","Malhada","CE"));
        lista.add(new Cidade("vK6OPJ9dQWlA92aBdHrO","Malhada Grande","CE"));
        lista.add(new Cidade("9EXNOccoewcfU25cvPl7","Mangabeira","CE"));
        lista.add(new Cidade("F7YhVHpa97eyt8NLT1IV","Manibu","CE"));
        lista.add(new Cidade("ImkOJHqvHNV4LmBokdOe","Manituba","CE"));
        lista.add(new Cidade("aPprTkeRYvruBnuCwkiz","Manoel Correia","CE"));
        lista.add(new Cidade("4CXlxozhX0YvAsLIswDi","Manoel Guedes","CE"));
        lista.add(new Cidade("lbmXM5AJvLLgKdE8D06X","Mapuá","CE"));
        lista.add(new Cidade("5kdQjCFtp5yrvjvXhyl6","Maracanaú","CE"));
        lista.add(new Cidade("wo8E2X0YPMMBzZtPSglz","Maraguá","CE"));
        lista.add(new Cidade("nPsqBP7DjmRTf2oPYSfB","Maranguape","CE"));
        lista.add(new Cidade("VLbtznMiyPalkD331fvo","Mararupá","CE"));
        lista.add(new Cidade("VSncwxd3IVD5YQPc7uvq","Maratoã","CE"));
        lista.add(new Cidade("nN0JpAJGmk1qGWE6jMpe","Maravilha","CE"));
        lista.add(new Cidade("5QQTUggc6bFRjzlswcfc","Marco","CE"));
        lista.add(new Cidade("GJcIEn4TEidMFtGfsQRE","Marinheiros","CE"));
        lista.add(new Cidade("gwEn4YWp0fDnEF0BFoB1","Marrecas","CE"));
        lista.add(new Cidade("pxQ544XrqkIFLHuaH9qc","Marrocos","CE"));
        lista.add(new Cidade("waGdefvlGchRF4mfjKGh","Marruás","CE"));
        lista.add(new Cidade("9NUGI28ddL4qlyY3pCdF","Martinópole","CE"));
        lista.add(new Cidade("uOX7OeMOFNGCPKIqFLu2","Martinslândia","CE"));
        lista.add(new Cidade("oWg8FtjzbVeIweihhUYy","Massapê","CE"));
        lista.add(new Cidade("MXWSKqITzh63d3U0TACp","Mata Fresca","CE"));
        lista.add(new Cidade("CMYunpU8yxc0a2bXG0lH","Matias","CE"));
        lista.add(new Cidade("XAndGiFjCT218eEqfvP2","Matriz","CE"));
        lista.add(new Cidade("YIsbS44Alzyj2oUchPC8","Mauriti","CE"));
        lista.add(new Cidade("9X96n2LvwGBXF2SLKQlj","Mel","CE"));
        lista.add(new Cidade("9jhBIddR6uwIvQfd9f2b","Meruoca","CE"));
        lista.add(new Cidade("ZGVNf5sx07F7YDa53fgg","Messejana","CE"));
        lista.add(new Cidade("1tPKpRbrAKxJtYSluwC9","Miguel Xavier","CE"));
        lista.add(new Cidade("nL2SmAm1yrE9Gz52aVjI","Milagres","CE"));
        lista.add(new Cidade("6lgA3w6t2eOQ1bqFNdGq","Milhã","CE"));
        lista.add(new Cidade("Gf4cTG9Sf8ampV8fxgal","Milton Belo","CE"));
        lista.add(new Cidade("rteLFRq9rlaN0bW7cf4T","Mineirolândia","CE"));
        lista.add(new Cidade("laqbrnhTEgQgDsDn3c4x","Miragem","CE"));
        lista.add(new Cidade("CGG77tk77Z8ShwjCJuD8","Miraíma","CE"));
        lista.add(new Cidade("58Icu7hhGYBV7TjWJVD6","Mirambé","CE"));
        lista.add(new Cidade("ctHaQKsoplWITp1WyAlj","Miranda","CE"));
        lista.add(new Cidade("uy9pkxaT6QBzty0VdmCe","Missão Nova","CE"));
        lista.add(new Cidade("EqDKYy3YVV8Jgj02SXgN","Missão Velha","CE"));
        lista.add(new Cidade("NgUoyoUUZU70GQapkrDA","Missi","CE"));
        lista.add(new Cidade("7q8gr36Id4XynH9pZQp0","Mocambo","CE"));
        lista.add(new Cidade("0gzAw03WClj8f0ZdukBx","Moitas","CE"));
        lista.add(new Cidade("gXRHTnGDqTYtjwf029gd","Mombaça","CE"));
        lista.add(new Cidade("fxnKe3AjizUiDytBBA1Q","Mondubim","CE"));
        lista.add(new Cidade("4wysMsVKBg6DmtGhGy2V","Monguba","CE"));
        lista.add(new Cidade("AwcPDgkm22WQ9CFOGTB3","Monsenhor Tabosa","CE"));
        lista.add(new Cidade("G2ghyCrmMi17VzkSX8un","Monte Alegre","CE"));
        lista.add(new Cidade("ECD1ilwE7rGA5sz3ZHkF","Monte Alverne","CE"));
        lista.add(new Cidade("ikCsE0PdDRLdHeqg90NO","Monte Castelo","CE"));
        lista.add(new Cidade("ISZKeITqTY9X8rkVKxdc","Monte Grave","CE"));
        lista.add(new Cidade("PExIoq0z9CgHEpyVV1cX","Monte Sion","CE"));
        lista.add(new Cidade("H9n7YdP0RWemnJcDLSNk","Montenebo","CE"));
        lista.add(new Cidade("IQDmStJ1ky4RsSGgB7F9","Morada Nova","CE"));
        lista.add(new Cidade("EKxYtb8rYGRmA98LMUfa","Moraújo","CE"));
        lista.add(new Cidade("LLPWH3xQZ2lxd72cfvQ5","Morrinhos","CE"));
        lista.add(new Cidade("MltFHL3hAnkHefxGARO1","Morrinhos Novos","CE"));
        lista.add(new Cidade("vXYYVFR810NZQnbvxXvC","Morro Branco","CE"));
        lista.add(new Cidade("BoQnWRvemGhX3xG6oUCq","Mosquito","CE"));
        lista.add(new Cidade("sLCnri9cUG6LKcjxgotS","Mucambo","CE"));
        lista.add(new Cidade("3ARHff61PuyYfQRv4q2h","Mulungu","CE"));
        lista.add(new Cidade("cLRp5DvjgtW8cLBZLXXD","Mumbaba","CE"));
        lista.add(new Cidade("aAgFucIsfPP1NpfIkIc5","Mundau","CE"));
        lista.add(new Cidade("lxfGjbtLwib4m48SkQdU","Mundaú","CE"));
        lista.add(new Cidade("meXYpaw6sCaZiNYi7zxe","Munguba","CE"));
        lista.add(new Cidade("UzWcJyrUvbXNWbZgXZT2","Muribeca","CE"));
        lista.add(new Cidade("IvHqbPPItPS0cEpHC6lz","Muriti","CE"));
        lista.add(new Cidade("cSLoVpD5mhF03lra7oR0","Mutambeiras","CE"));
        lista.add(new Cidade("A92sSpfR2KexT3ACdpvN","Naraniu","CE"));
        lista.add(new Cidade("chEe7PWlK9tizpdc2nsO","Nascente","CE"));
        lista.add(new Cidade("6y1Srd6gDiZFU8Kx1Yey","Nenenlândia","CE"));
        lista.add(new Cidade("i2SuhF6rHC7S53Tn6vp9","Nossa Senhora do Livramento","CE"));
        lista.add(new Cidade("tHpHlZik3smDV08EnSgI","Nova Betânia","CE"));
        lista.add(new Cidade("L5eQWbWz2epbOG6b5BLL","Nova Fátima","CE"));
        lista.add(new Cidade("imAugNDSEsJcbdPyeOmJ","Nova Floresta","CE"));
        lista.add(new Cidade("VxyodI6u90dnQM011sWS","Nova Olinda","CE"));
        lista.add(new Cidade("5XnH68USncqZ5z8NvtvE","Nova Russas","CE"));
        lista.add(new Cidade("h51VYxnpnp0smXhFUt5v","Nova Santa Cruz","CE"));
        lista.add(new Cidade("eFUhsPUza0wTp19Vx7lP","Nova Veneza","CE"));
        lista.add(new Cidade("eUhceORTMyyCZ0GDYFGB","Nova Vida","CE"));
        lista.add(new Cidade("EtuOLSvoSJcy14nd1nhN","Novo Assis","CE"));
        lista.add(new Cidade("N51NzVpjNIPE2L7Jntbf","Novo Horizonte","CE"));
        lista.add(new Cidade("2ia6eJCRcCCFbCSD5SWY","Novo Oriente","CE"));
        lista.add(new Cidade("P3ygN1li7kRt8ufNyG2C","Núcleo Colonial Pio XII","CE"));
        lista.add(new Cidade("detUSBR909V7wS7kKvFq","Ocara","CE"));
        lista.add(new Cidade("NJ7zFfn5PZxHtoUdGH72","Oiticica","CE"));
        lista.add(new Cidade("qUKcwodZs3hjhEcPsepd","Olho D'Água","CE"));
        lista.add(new Cidade("FaAdwzBf7eoh2mybUSkL","Olho D'água do Bezerril","CE"));
        lista.add(new Cidade("bhRLlrzXw9BmsaISzAtZ","Olho-D'Água","CE"));
        lista.add(new Cidade("NfzwHFVcqzu9NzuS3xVq","Olho-D'Água da Bica","CE"));
        lista.add(new Cidade("FovRTLthsTuckJNRIGzn","Oliveiras","CE"));
        lista.add(new Cidade("z2dqXW5RtgqxNFESoi3z","Orós","CE"));
        lista.add(new Cidade("wTXbTLcRmKxTpYHQk6mH","Pacajus","CE"));
        lista.add(new Cidade("LHYX9mm1o9K7wiarhYIw","Pacatuba","CE"));
        lista.add(new Cidade("CwQwDWCelv7XYbUPt3Z6","Pacoti","CE"));
        lista.add(new Cidade("DpyKhEjYcgOe1qO89aE7","Pacujá","CE"));
        lista.add(new Cidade("Wp51GHWDRmu5kXV0oSaA","Padre Cícero","CE"));
        lista.add(new Cidade("hg5neXV8Mp7VGREfcGZS","Padre Linhares","CE"));
        lista.add(new Cidade("JIW1VdOkQutl0P1OariI","Padre Vieira","CE"));
        lista.add(new Cidade("dKDJE9LbIeMMCFBj4YHg","Pai João","CE"));
        lista.add(new Cidade("kHDHHg1Ok1vaOGdixuWO","Pajeú","CE"));
        lista.add(new Cidade("jYtOm93STBBRYMnRPw8g","Palestina","CE"));
        lista.add(new Cidade("dqNbjMJ2PrjPfzVJr7vk","Palestina do Norte","CE"));
        lista.add(new Cidade("8zHieN0vU12EiyYF0E8I","Palhano","CE"));
        lista.add(new Cidade("j3NF3OcZiJsXdDlNT8s5","Palmácia","CE"));
        lista.add(new Cidade("FqBjymAe7xuFflvO8oHC","Palmatória","CE"));
        lista.add(new Cidade("4e6PIOA99cEw6umA71Ep","Panacuí","CE"));
        lista.add(new Cidade("QOufidd4Yh0EwGvRrFh3","Papara","CE"));
        lista.add(new Cidade("2HyYdoopM7zgFsb1x6P5","Paracuá","CE"));
        lista.add(new Cidade("HUqPF9yyikG2rxqqgdrG","Paracuru","CE"));
        lista.add(new Cidade("1Upj7mPQZCoz3eKUIlrt","Paraipaba","CE"));
        lista.add(new Cidade("MeDkwGLulP4g59G9LEX1","Paraiso","CE"));
        lista.add(new Cidade("3XyBsm024NeyKABAGuIU","Parajuru","CE"));
        lista.add(new Cidade("GFYT2XfWpdXRFqoL01nY","Parambu","CE"));
        lista.add(new Cidade("Ip2jY0DjYDZ0haHxheIs","Paramoti","CE"));
        lista.add(new Cidade("aig8cvKxnGb0NmGM3r55","Parangaba","CE"));
        lista.add(new Cidade("JU404RP9zHyay4CEwhmw","Parapuí","CE"));
        lista.add(new Cidade("I3879Yg0nnFBnFGu6Dr4","Parazinho","CE"));
        lista.add(new Cidade("1izGS6oYypJMgLvqHHCF","Paripueira","CE"));
        lista.add(new Cidade("LSgQqG38XrY64Mns429N","Pascoal","CE"));
        lista.add(new Cidade("LlDcLNDIpcGzZ8DqdNfl","Passagem","CE"));
        lista.add(new Cidade("SgcKZzneXpFqipr8W6TJ","Passagem Funda","CE"));
        lista.add(new Cidade("M9bXuT2IhePWZGkWNiyB","Pasta","CE"));
        lista.add(new Cidade("hy7W18C0LFjPsn0nm6k7","Patacas","CE"));
        lista.add(new Cidade("MKMzV42zvqqJKwDT3Ok3","Patos","CE"));
        lista.add(new Cidade("j41waEB3h3CDYTeW4NCm","Patos dos Liberatos","CE"));
        lista.add(new Cidade("YNhMSy9P3THbwyVFiW2p","Patriarca","CE"));
        lista.add(new Cidade("VzElOpnQlVC1j7aBXTET","Paus Branco","CE"));
        lista.add(new Cidade("kx7s9IpkoJ8wA5CshuqJ","Paus Brancos","CE"));
        lista.add(new Cidade("plEbbtl8BwB68U12Adlj","Pavuna","CE"));
        lista.add(new Cidade("1OGzey1CSyRCgWOrSxML","Pecém","CE"));
        lista.add(new Cidade("QZrP94bxpi2X7tU3jFSe","Pedra Branca","CE"));
        lista.add(new Cidade("FTKlHxMaBoilkNwfgxOU","Pedra de Fogo","CE"));
        lista.add(new Cidade("EAuNezyePwjXd2UCTzgM","Pedra e Cal","CE"));
        lista.add(new Cidade("yyGMXXiWYuTaPjeB9xeu","Pedras","CE"));
        lista.add(new Cidade("WgF2ONEE6takuJiGbvyz","Pedras Brancas","CE"));
        lista.add(new Cidade("CnthASFSHmL94kvlxMwb","Pedrinhas","CE"));
        lista.add(new Cidade("i419rRc4cUdJjGBJN8J7","Peixe","CE"));
        lista.add(new Cidade("aI2eQlRME9s5WW5V8Htq","Peixe Gordo","CE"));
        lista.add(new Cidade("3nym9SIgCr696kNYOQ53","Penaforte","CE"));
        lista.add(new Cidade("CadmzW5FQ6Bcof75mF6a","Penedo","CE"));
        lista.add(new Cidade("x4fN4uGOFtelUOjn7nqk","Pentecoste","CE"));
        lista.add(new Cidade("kW6POhQxngVMm3J5oW0U","Pereiro","CE"));
        lista.add(new Cidade("fxjQn3fGiGIeSxvfxy82","Pernambuquinho","CE"));
        lista.add(new Cidade("7tOm2WueKYGqJ4MaexEz","Pessoa Anta","CE"));
        lista.add(new Cidade("uopUOFVSalaFLEekTin2","Pindoguaba","CE"));
        lista.add(new Cidade("jacKZ6oeGeAHM7mdrO0v","Pindoretama","CE"));
        lista.add(new Cidade("ZO4LxHRBCuPWVtwy45el","Pio X","CE"));
        lista.add(new Cidade("UCN8cAMHwloKzyCwaDPz","Piquet Carneiro","CE"));
        lista.add(new Cidade("N0QvTxWjxVKKVc74hs3p","Pirabibu","CE"));
        lista.add(new Cidade("pS4pPInhjkCTXilFlSlG","Pirangi","CE"));
        lista.add(new Cidade("CVkiYYx39eUI2faORjGz","Pires Ferreira","CE"));
        lista.add(new Cidade("LHfJo06xVquCr3NLesb6","Pitombeira","CE"));
        lista.add(new Cidade("hdYvweRbvITuuYrPxt5U","Pitombeiras","CE"));
        lista.add(new Cidade("AFzloYKG8Wf0PBzM6lll","Plácido Martins","CE"));
        lista.add(new Cidade("bXLNaRK9zIGH8s2B1f7V","Planalto","CE"));
        lista.add(new Cidade("BQAgF9ZMzb8XZrrxKN6d","Poço","CE"));
        lista.add(new Cidade("U1VSfDgwwSVpMXpoHyLU","Poço Comprido","CE"));
        lista.add(new Cidade("TmXBNJZeasSy86MawCdz","Poço da Onça","CE"));
        lista.add(new Cidade("VuOL1zTsHtaOTMXLZ4dB","Poço Doce","CE"));
        lista.add(new Cidade("4g1zH0qGgNZHKmYBbO1U","Poço Grande","CE"));
        lista.add(new Cidade("xt0bn5O9yRcfQ5fmzNr2","Poço Verde","CE"));
        lista.add(new Cidade("yCLVRRBN68NRNoWQuXs3","Ponta da Serra","CE"));
        lista.add(new Cidade("fKRbSdqgAjebRzMNJQjt","Poranga","CE"));
        lista.add(new Cidade("8vHkP97DmbUCcU8vTKiG","Porfirio Sampaio","CE"));
        lista.add(new Cidade("APIkfEwjD4aPCLvM9rZV","Porteiras","CE"));
        lista.add(new Cidade("oBOyYqIodyYHJVVT1iFJ","Potengi","CE"));
        lista.add(new Cidade("9Q9esdJ7DD6px7FdA3MZ","Poti","CE"));
        lista.add(new Cidade("cAF77QcxjdCgsa5BoVoF","Potiretama","CE"));
        lista.add(new Cidade("JM1BcRHq8qSodMrCF4WN","Prata","CE"));
        lista.add(new Cidade("MdnEaJ9Fjz24Xy1Gyj6L","Pratiús","CE"));
        lista.add(new Cidade("VhoAFWATCexxP5NjhgpK","Prefeita Suely Pinheiro","CE"));
        lista.add(new Cidade("Uf8KsocR0nXVBLPArwWC","Prudente de Morais","CE"));
        lista.add(new Cidade("yLveZzb0NYnJodScS8ZK","Quatiguaba","CE"));
        lista.add(new Cidade("xYayONcWrggj0RJ3yBwr","Queimados","CE"));
        lista.add(new Cidade("1sENMuKTI4m8UI8QS6td","Quimami","CE"));
        lista.add(new Cidade("W1jaYJM4nN7QVQjyDsbn","Quincoé","CE"));
        lista.add(new Cidade("RuniEpkCVzZedh9Zzvoi","Quincuncá","CE"));
        lista.add(new Cidade("PDHTS36Dsf7WTQUQ8MYw","Quitaiús","CE"));
        lista.add(new Cidade("dnWdV8v1j5oifFdTKq5t","Quiterianópolis","CE"));
        lista.add(new Cidade("jrts3v4H74iOk93DLEpH","Quixadá","CE"));
        lista.add(new Cidade("BR47Q72JF1bpn6GtIJ0a","Quixariú","CE"));
        lista.add(new Cidade("dTSGyXXPQNlFx9K3hQNu","Quixelô","CE"));
        lista.add(new Cidade("1nxR6CjSAHnIFWPcpGY0","Quixeramobim","CE"));
        lista.add(new Cidade("k64BRumvfwMYnYj3RovT","Quixeré","CE"));
        lista.add(new Cidade("5yM6ZNa9pPa4vjINXAiI","Rafael Arruda","CE"));
        lista.add(new Cidade("XHI1ThePQg9s79zGq0ja","Raimundo Martins","CE"));
        lista.add(new Cidade("0q4qvkaVfeY6EHbNWExc","Ramadinha","CE"));
        lista.add(new Cidade("EotcmdTw2P8feWD7M7ZI","Realejo","CE"));
        lista.add(new Cidade("5dX6fehh4EmYbg37CImh","Recanto","CE"));
        lista.add(new Cidade("Wlv2DEDdpS6NP6AJH9DW","Redenção","CE"));
        lista.add(new Cidade("D2BrRkRVlZ54I8vzED59","Repartição","CE"));
        lista.add(new Cidade("RAECN8IJzQEp7K3kXzLb","Reriutaba","CE"));
        lista.add(new Cidade("V1DU0wxSN8vcV5C4oTpN","Retiro","CE"));
        lista.add(new Cidade("CzsG5xn4BPxpcqaIzFPq","Riachão","CE"));
        lista.add(new Cidade("vUooVbba6U32KA9fFShC","Riacho Grande","CE"));
        lista.add(new Cidade("vwZNvJI6WndvrsF68uUd","Riacho Verde","CE"));
        lista.add(new Cidade("WkpuezugakCRkEcYM48E","Riacho Vermelho","CE"));
        lista.add(new Cidade("CbQvZYyvemqPGZ7AO3zt","Rinaré","CE"));
        lista.add(new Cidade("D4uzvjioOOLN4ZRDKhV9","Roldão","CE"));
        lista.add(new Cidade("MjqaCuSL9ap1EEOMzYFz","Rosário","CE"));
        lista.add(new Cidade("jLJeDZUdF2B3OOYUV71m","Russas","CE"));
        lista.add(new Cidade("f46VnLjlZ1C4W3TS8Vx7","Sabiaguaba","CE"));
        lista.add(new Cidade("wKbcLPEsvJ6HnPSKgYtZ","Saboeiro","CE"));
        lista.add(new Cidade("BaRB5Zc2Fp96dyo6XWM8","Sacramento","CE"));
        lista.add(new Cidade("raoF4Pq69MxnqhCAEzWs","Salão","CE"));
        lista.add(new Cidade("Y3UAMgeiGLFKEZdjB5iT","Salgado dos Machados","CE"));
        lista.add(new Cidade("Autuww3Sx6PNMxsRDFJF","Salgado dos Mendes","CE"));
        lista.add(new Cidade("By2zqtY7A7jbB3TIc4CF","Salitre","CE"));
        lista.add(new Cidade("pY40mKoQe8gJvWa71Kx5","Sambaíba","CE"));
        lista.add(new Cidade("dtMH2GeGZPxJWJGBtmnF","Santa Ana","CE"));
        lista.add(new Cidade("9SgN1feKPd1UV95uT3rp","Santa Cruz do Banabuiú","CE"));
        lista.add(new Cidade("F8rwLWhpDvJengvwuZ5P","Santa Fé","CE"));
        lista.add(new Cidade("2l1wpvS1jfDfXooVnvCl","Santa Felícia","CE"));
        lista.add(new Cidade("zc6G5eF91S5MeFrnDLf0","Santa Luzia","CE"));
        lista.add(new Cidade("198Bx4uCyVcfsnFdrV6i","Santa Quitéria","CE"));
        lista.add(new Cidade("N8ZXLmqRHDD1lVEdBJHL","Santa Rita","CE"));
        lista.add(new Cidade("JwZoHxKVOeM54ElvNsaQ","Santa Rosa","CE"));
        lista.add(new Cidade("m0mKkUeE2La5sxRTJaPt","Santa Tereza","CE"));
        lista.add(new Cidade("Psvu4abKEqveXWKgBEDj","Santana","CE"));
        lista.add(new Cidade("tjWK7XpA5CBRcSAAE7cI","Santana do Acaraú","CE"));
        lista.add(new Cidade("5pI7JZTFkjXOfR5AGKKK","Santana do Cariri","CE"));
        lista.add(new Cidade("r7tTuEzBQwXPI4sLIq7Z","Santarém","CE"));
        lista.add(new Cidade("EApj3PkurbowZyRR5xJL","Santo André","CE"));
        lista.add(new Cidade("xwMWGEKxhT8vHeIySURy","Santo Antônio","CE"));
        lista.add(new Cidade("XV8qy5F4XNxn1q5FfEIz","Santo Antônio da Pindoba","CE"));
        lista.add(new Cidade("suNt5ZdWv6KkCrAfLJAe","Santo Antônio dos Fernandes","CE"));
        lista.add(new Cidade("wmRndAzckjIJON8JYkHw","São Bartolomeu","CE"));
        lista.add(new Cidade("7eWTtMDQo2bRM8oHNBew","São Benedito","CE"));
        lista.add(new Cidade("rNqyzsFF0E2W7ChpLB0y","São Bernardo","CE"));
        lista.add(new Cidade("BM9sBfXhahQRUhMV8X3a","São Domingos","CE"));
        lista.add(new Cidade("1M49E4KQErx5LeZzVASA","São Felipe","CE"));
        lista.add(new Cidade("jXSdGWi8iY9VnvFNl40G","São Francisco","CE"));
        lista.add(new Cidade("72qHDEcqGfd7rJZLTUZy","São Gonçalo do Amarante","CE"));
        lista.add(new Cidade("8WfXwwWHWvXCr14COGoi","São Gonçalo do Umari","CE"));
        lista.add(new Cidade("oxZBNKT5Ye9IhVRqOJvm","São João","CE"));
        lista.add(new Cidade("exn06Lux64Flb9tKqBcZ","São João de Deus","CE"));
        lista.add(new Cidade("3DrZK9jX7PRc1jQa4Omw","São João do Amanari","CE"));
        lista.add(new Cidade("4UCDdJhN5cqKkqQWcouV","São João do Jaguaribe","CE"));
        lista.add(new Cidade("f9emorfxvZNVZWC1cOZ6","São João dos Queiroz","CE"));
        lista.add(new Cidade("bXKU9QsJ8eZUk8FhvxgD","São Joaquim","CE"));
        lista.add(new Cidade("VqVFOKE9kig4lmRj0qvE","São Joaquim do Salgado","CE"));
        lista.add(new Cidade("1igEXX1sLenLvrF99FpB","São José","CE"));
        lista.add(new Cidade("y1rYmlvKMDK294BCsh6G","São José das Lontras","CE"));
        lista.add(new Cidade("Roon0HU6JJQowF56NzrL","São José de Solonópole","CE"));
        lista.add(new Cidade("RlUa8iPESebvGf3J8h6b","São José do Lagamar","CE"));
        lista.add(new Cidade("Um9IlSIyoc70QdLjJwQs","São José do Torto","CE"));
        lista.add(new Cidade("jLAhlPs7at3mp3K3Ej8Y","São Luís do Curu","CE"));
        lista.add(new Cidade("EKRIx26IEyeSuhPxrOsf","São Miguel","CE"));
        lista.add(new Cidade("LbUEJlyEVMqCzpARyLOf","São Paulinho","CE"));
        lista.add(new Cidade("HLd2XO5Ob2xcfZkfJ0SI","São Pedro","CE"));
        lista.add(new Cidade("votSIaWl0ffgzdPzKoj7","São Pedro do Gavião","CE"));
        lista.add(new Cidade("CJ78dGDA49ueru9oBpUi","São Pedro do Norte","CE"));
        lista.add(new Cidade("XIGC2qMTT2oVpkR2ld46","São Raimundo","CE"));
        lista.add(new Cidade("KOm9bpR393IomdHlNuEe","São Romão","CE"));
        lista.add(new Cidade("EakQpFGamk6xr16qngw2","São Roque","CE"));
        lista.add(new Cidade("glSyWz6Rj7LbxDdAHCBW","São Sebastião","CE"));
        lista.add(new Cidade("6X9YQR7eNPbnWmTpJlTw","São Tomé","CE"));
        lista.add(new Cidade("Rq57Yov2xildS4rMJ8a0","São Vicente","CE"));
        lista.add(new Cidade("FNnhEh8B2iGXgbi273WO","Sapo","CE"));
        lista.add(new Cidade("umBdeGt2Oz7WVZjIvoPq","Sapupara","CE"));
        lista.add(new Cidade("SUvNhq0pE3GOOknS8yOK","Saquinho","CE"));
        lista.add(new Cidade("uTaoTG6FIKoEFEjxrHiL","Sebastião de Abreu","CE"));
        lista.add(new Cidade("TJS2CpIyYaEpZxI289lp","Senador Carlos Jereissati","CE"));
        lista.add(new Cidade("k5aXDJJPVCcnE42DQh62","Senador Pompeu","CE"));
        lista.add(new Cidade("ay6OaAQyHGGOgVHaiWJ0","Senador Sá","CE"));
        lista.add(new Cidade("W1KB83V6nJHsQplJeiEV","Sereno de Cima","CE"));
        lista.add(new Cidade("QGfbBx7CM4LPrfxtU7iy","Serra do Félix","CE"));
        lista.add(new Cidade("FdKEYbj7QOGX4AAfTTfa","Serragem","CE"));
        lista.add(new Cidade("61qurwGVgjX5Ki5JLdSD","Serrota","CE"));
        lista.add(new Cidade("S2Sqo7032qcsDmNYKsn4","Serrote","CE"));
        lista.add(new Cidade("JN4WHfChf03xoCVrAyyS","Serrote do Meio","CE"));
        lista.add(new Cidade("lzQiBpjcN5MG5QqAcwUA","Simão","CE"));
        lista.add(new Cidade("fKtwBesWdBfM40L8taiL","Sitiá","CE"));
        lista.add(new Cidade("GHmP49et9bOPPgMHcTzE","Sítio Alegre","CE"));
        lista.add(new Cidade("lbvHSzQR6PWRwLt69LLa","Sítios Novos","CE"));
        lista.add(new Cidade("5locTBNMm1EbmO8KFrZW","Siupê","CE"));
        lista.add(new Cidade("OwmiNxPd0nHUJ7Ozmaic","Sobral","CE"));
        lista.add(new Cidade("qV4Xawm0O8iqmOBSgdZQ","Soledade","CE"));
        lista.add(new Cidade("YZaXHTz142cejM95rnhO","Solidão","CE"));
        lista.add(new Cidade("bG7zQB1BHHYhR8Bawieu","Solonópole","CE"));
        lista.add(new Cidade("mIiJIR9RFr1jT7w7ce9W","Suassurana","CE"));
        lista.add(new Cidade("aLOjF7h8mYredMWRjnsj","Sucatinga","CE"));
        lista.add(new Cidade("aJB559Nm46VMg5trw70l","Sucesso","CE"));
        lista.add(new Cidade("gQ27NfGBiGGLarthYeab","Sussuanha","CE"));
        lista.add(new Cidade("QjpHnw2Ei5gkTog6OMDI","Tabainha","CE"));
        lista.add(new Cidade("4t7d9qaQrU9Gw4JkVoBe","Taboleiro","CE"));
        lista.add(new Cidade("9fDu6HTyYY6i1oBCPZ7W","Tabuleiro do Norte","CE"));
        lista.add(new Cidade("rC0liLVXr3BawExMnq3g","Taíba","CE"));
        lista.add(new Cidade("nKRKyLwdAWMtbQHXcAXb","Tamboril","CE"));
        lista.add(new Cidade("K9sZdpsN7TvArqr9rDUz","Tangente","CE"));
        lista.add(new Cidade("KoAYWeAq8KCnOUYvFn7T","Tanques","CE"));
        lista.add(new Cidade("JUo64J2FD6JVdRjPJZ8U","Tapera","CE"));
        lista.add(new Cidade("ykTGBv4amDNMqOSAwo1J","Taperuaba","CE"));
        lista.add(new Cidade("ST7u6poaPN5HAexJoidH","Tapuiara","CE"));
        lista.add(new Cidade("YHw5mbRT1ArG9TZXJGCj","Tapuio","CE"));
        lista.add(new Cidade("DpV6G0ocVvZ4UQkPOFnm","Targinos","CE"));
        lista.add(new Cidade("Wam8XK3VtYoyBRzk4oM1","Tarrafas","CE"));
        lista.add(new Cidade("aWG321ptCKXa2VeoleHg","Tauá","CE"));
        lista.add(new Cidade("CQPz47c0A4SjKTRATDzV","Tejuçuoca","CE"));
        lista.add(new Cidade("Peu6Px6ngMAC5QnccBaC","Tianguá","CE"));
        lista.add(new Cidade("BOIwX1mnaN4s8HgEKFb0","Timbaúba dos Marinheiros","CE"));
        lista.add(new Cidade("9SHMWPOVKghDzFF0skRx","Timonha","CE"));
        lista.add(new Cidade("RNl5RdxM8KP5tOc43OeW","Tipi","CE"));
        lista.add(new Cidade("G2NQFzupJk5O3gq4SBM2","Tomé","CE"));
        lista.add(new Cidade("XFfg7M30WIgvBGJ7JPBE","Trairi","CE"));
        lista.add(new Cidade("8j3OxIIUYnSWQH4wM68r","Trapiá","CE"));
        lista.add(new Cidade("ZwmU4MYaEEryY5bKNFAS","Triângulo","CE"));
        lista.add(new Cidade("9fVMREeREiKbwe5QI0Ss","Trici","CE"));
        lista.add(new Cidade("ynmAt7d7tPSVfsji4fN3","Triunfo","CE"));
        lista.add(new Cidade("Spo21d41ftx6F9tKdzQ9","Tróia","CE"));
        lista.add(new Cidade("6WFPRRkbztwEo7mjWWRP","Trussu","CE"));
        lista.add(new Cidade("19alxveL3rgV5LKMVKV9","Tucunduba","CE"));
        lista.add(new Cidade("CtqB7k2eDoadZCDyknWo","Tucuns","CE"));
        lista.add(new Cidade("EttK4cr1GWRZXM9pTMHP","Tuína","CE"));
        lista.add(new Cidade("qkgIuEyAoqUp1RcTFick","Tururu","CE"));
        lista.add(new Cidade("GN07eVUFJBejHW4CkXJu","Ubajara","CE"));
        lista.add(new Cidade("1505rrQSU6Gzorc9VoSx","Ubaúna","CE"));
        lista.add(new Cidade("jG5gPZMYLdGUFYzfOqbj","Ubiraçu","CE"));
        lista.add(new Cidade("wkuQQ9sVWmbyoFaQmi9b","Uiraponga","CE"));
        lista.add(new Cidade("WcLEsvjBm4TGD3CbTDET","Umari","CE"));
        lista.add(new Cidade("1SVJw0ZElU16YvQRvtSI","Umarituba","CE"));
        lista.add(new Cidade("4Zd5ytUYYIoAE6heKnHI","Umarizeiras","CE"));
        lista.add(new Cidade("IcHqYEShhQZn2RlX1AD3","Umburanas","CE"));
        lista.add(new Cidade("u7q10eU2TYr4KE8nk1mV","Umirim","CE"));
        lista.add(new Cidade("cJLCKw6NDXumkPAyZvg8","União","CE"));
        lista.add(new Cidade("kNpmxXYBDS3bTjhYpVrb","Uruburetama","CE"));
        lista.add(new Cidade("cP3lVLKxOHOJ4N3vz7IL","Uruoca","CE"));
        lista.add(new Cidade("bHWrVC1yRcGzCKdO6Hqg","Uruquê","CE"));
        lista.add(new Cidade("zXIHegArQi0U9bMAObVY","Varjota","CE"));
        lista.add(new Cidade("7l1ZVgdLyOu1hSZUbYWM","Várzea","CE"));
        lista.add(new Cidade("EcKFti5MlL7bIQAbNRze","Várzea Alegre","CE"));
        lista.add(new Cidade("MsQXWYmI59VB5Z334E4L","Várzea da Onça","CE"));
        lista.add(new Cidade("aj5QVxwcEntbBRUYrSfw","Várzea da Volta","CE"));
        lista.add(new Cidade("vtSaTEAMZtBdNebkPSt2","Várzea do Gilo","CE"));
        lista.add(new Cidade("WGCI6zqdTSqihpyBW7EZ","Várzea dos Espinhos","CE"));
        lista.add(new Cidade("rLQWy3QFFkLXrvDcPHFQ","Vazantes","CE"));
        lista.add(new Cidade("6oUkwTlFYPRAnfqvH9ki","Vazente do Curú","CE"));
        lista.add(new Cidade("DFqSDEsjtnhtaEsNyVji","Velame","CE"));
        lista.add(new Cidade("5h7AsxPtWCMujlEVkouT","Ventura","CE"));
        lista.add(new Cidade("ahMnLqaGINzWb1lsVRsf","Vertentes do Lagedo","CE"));
        lista.add(new Cidade("b7nLRRNroxgtjrR2ZZFY","Viçosa","CE"));
        lista.add(new Cidade("i7uesoe2ZrBckXZwzepE","Viçosa do Ceará","CE"));
        lista.add(new Cidade("Znws67zeg5R3jgsY2uzG","Video","CE"));
        lista.add(new Cidade("3NIVNg24scpeceCmyQO3","Vila Soares","CE"));
        lista.add(new Cidade("Y1DovEP22VU0CcqfM3j1","Vista Alegre","CE"));
        return lista;
    }
}
