package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class CE {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Abaiara", "CE"));
        lista.add(new Cidade("", "Abílio Martins", "CE"));
        lista.add(new Cidade("", "Acarape", "CE"));
        lista.add(new Cidade("", "Acaraú", "CE"));
        lista.add(new Cidade("", "Acopiara", "CE"));
        lista.add(new Cidade("", "Açude dos Pinheiros", "CE"));
        lista.add(new Cidade("", "Açudinho", "CE"));
        lista.add(new Cidade("", "Açudinho dos Costas", "CE"));
        lista.add(new Cidade("", "Adrianópolis", "CE"));
        lista.add(new Cidade("", "Água Fria", "CE"));
        lista.add(new Cidade("", "Água Verde", "CE"));
        lista.add(new Cidade("", "Aguaí", "CE"));
        lista.add(new Cidade("", "Águas Belas", "CE"));
        lista.add(new Cidade("", "Aiuá", "CE"));
        lista.add(new Cidade("", "Aiuaba", "CE"));
        lista.add(new Cidade("", "Alagoinha", "CE"));
        lista.add(new Cidade("", "Alazans", "CE"));
        lista.add(new Cidade("", "Alcântaras", "CE"));
        lista.add(new Cidade("", "Algodões", "CE"));
        lista.add(new Cidade("", "Almofala", "CE"));
        lista.add(new Cidade("", "Altaneira", "CE"));
        lista.add(new Cidade("", "Alto Lindo", "CE"));
        lista.add(new Cidade("", "Alto Santo", "CE"));
        lista.add(new Cidade("", "Amanaiara", "CE"));
        lista.add(new Cidade("", "Amanari", "CE"));
        lista.add(new Cidade("", "Amaniutuba", "CE"));
        lista.add(new Cidade("", "Amarelas", "CE"));
        lista.add(new Cidade("", "Amaro", "CE"));
        lista.add(new Cidade("", "América", "CE"));
        lista.add(new Cidade("", "Amontada", "CE"));
        lista.add(new Cidade("", "Anauá", "CE"));
        lista.add(new Cidade("", "Anil", "CE"));
        lista.add(new Cidade("", "Aningás", "CE"));
        lista.add(new Cidade("", "Anjinhos", "CE"));
        lista.add(new Cidade("", "Antonina do Norte", "CE"));
        lista.add(new Cidade("", "Antônio Bezerra", "CE"));
        lista.add(new Cidade("", "Antônio Diogo", "CE"));
        lista.add(new Cidade("", "Antônio Marques", "CE"));
        lista.add(new Cidade("", "Aprazível", "CE"));
        lista.add(new Cidade("", "Apuiarés", "CE"));
        lista.add(new Cidade("", "Aquinópolis", "CE"));
        lista.add(new Cidade("", "Aquiraz", "CE"));
        lista.add(new Cidade("", "Araçás", "CE"));
        lista.add(new Cidade("", "Aracati", "CE"));
        lista.add(new Cidade("", "Aracatiaçu", "CE"));
        lista.add(new Cidade("", "Aracatiara", "CE"));
        lista.add(new Cidade("", "Aracoiaba", "CE"));
        lista.add(new Cidade("", "Arajara", "CE"));
        lista.add(new Cidade("", "Aranaú", "CE"));
        lista.add(new Cidade("", "Arapá", "CE"));
        lista.add(new Cidade("", "Arapari", "CE"));
        lista.add(new Cidade("", "Araporanga", "CE"));
        lista.add(new Cidade("", "Araquém", "CE"));
        lista.add(new Cidade("", "Ararendá", "CE"));
        lista.add(new Cidade("", "Araripe", "CE"));
        lista.add(new Cidade("", "Arariús", "CE"));
        lista.add(new Cidade("", "Aratama", "CE"));
        lista.add(new Cidade("", "Araticum", "CE"));
        lista.add(new Cidade("", "Aratuba", "CE"));
        lista.add(new Cidade("", "Areial", "CE"));
        lista.add(new Cidade("", "Areré", "CE"));
        lista.add(new Cidade("", "Ariscos dos Marianos", "CE"));
        lista.add(new Cidade("", "Arneiroz", "CE"));
        lista.add(new Cidade("", "Aroeiras", "CE"));
        lista.add(new Cidade("", "Arrojado", "CE"));
        lista.add(new Cidade("", "Aruaru", "CE"));
        lista.add(new Cidade("", "Assaré", "CE"));
        lista.add(new Cidade("", "Assis", "CE"));
        lista.add(new Cidade("", "Assunção", "CE"));
        lista.add(new Cidade("", "Aurora", "CE"));
        lista.add(new Cidade("", "Baixa Fria", "CE"));
        lista.add(new Cidade("", "Baixa Grande", "CE"));
        lista.add(new Cidade("", "Baixio", "CE"));
        lista.add(new Cidade("", "Baixio da Donana", "CE"));
        lista.add(new Cidade("", "Baixio das Palmeiras", "CE"));
        lista.add(new Cidade("", "Baleia", "CE"));
        lista.add(new Cidade("", "Balseiros", "CE"));
        lista.add(new Cidade("", "Banabuiú", "CE"));
        lista.add(new Cidade("", "Bandeira", "CE"));
        lista.add(new Cidade("", "Baracho", "CE"));
        lista.add(new Cidade("", "Barão de Aquiraz", "CE"));
        lista.add(new Cidade("", "Barbada", "CE"));
        lista.add(new Cidade("", "Barbalha", "CE"));
        lista.add(new Cidade("", "Barra", "CE"));
        lista.add(new Cidade("", "Barra do Ingá", "CE"));
        lista.add(new Cidade("", "Barra do Sotero", "CE"));
        lista.add(new Cidade("", "Barra Nova", "CE"));
        lista.add(new Cidade("", "Barreira", "CE"));
        lista.add(new Cidade("", "Barreira dos Vianas", "CE"));
        lista.add(new Cidade("", "Barreiras", "CE"));
        lista.add(new Cidade("", "Barreiros", "CE"));
        lista.add(new Cidade("", "Barrento", "CE"));
        lista.add(new Cidade("", "Barrinha", "CE"));
        lista.add(new Cidade("", "Barro", "CE"));
        lista.add(new Cidade("", "Barro Alto", "CE"));
        lista.add(new Cidade("", "Barroquinha", "CE"));
        lista.add(new Cidade("", "Bastiões", "CE"));
        lista.add(new Cidade("", "Baturité", "CE"));
        lista.add(new Cidade("", "Baú", "CE"));
        lista.add(new Cidade("", "Beberibe", "CE"));
        lista.add(new Cidade("", "Bela Cruz", "CE"));
        lista.add(new Cidade("", "Bela Vista", "CE"));
        lista.add(new Cidade("", "Belém", "CE"));
        lista.add(new Cidade("", "Belmonte", "CE"));
        lista.add(new Cidade("", "Betânia", "CE"));
        lista.add(new Cidade("", "Bilheira", "CE"));
        lista.add(new Cidade("", "Bitupitá", "CE"));
        lista.add(new Cidade("", "Bixopa", "CE"));
        lista.add(new Cidade("", "Boa Água", "CE"));
        lista.add(new Cidade("", "Boa Esperança", "CE"));
        lista.add(new Cidade("", "Boa Viagem", "CE"));
        lista.add(new Cidade("", "Boa Vista", "CE"));
        lista.add(new Cidade("", "Boa Vista do Caxitoré", "CE"));
        lista.add(new Cidade("", "Bom Princípio", "CE"));
        lista.add(new Cidade("", "Bonfim", "CE"));
        lista.add(new Cidade("", "Bonhu", "CE"));
        lista.add(new Cidade("", "Bonito", "CE"));
        lista.add(new Cidade("", "Boqueirão", "CE"));
        lista.add(new Cidade("", "Borges", "CE"));
        lista.add(new Cidade("", "Brejinho", "CE"));
        lista.add(new Cidade("", "Brejo Grande", "CE"));
        lista.add(new Cidade("", "Brejo Santo", "CE"));
        lista.add(new Cidade("", "Brotas", "CE"));
        lista.add(new Cidade("", "Buritizal", "CE"));
        lista.add(new Cidade("", "Buritizinho", "CE"));
        lista.add(new Cidade("", "Cabreiro", "CE"));
        lista.add(new Cidade("", "Cachoeira", "CE"));
        lista.add(new Cidade("", "Cachoeira de Fora", "CE"));
        lista.add(new Cidade("", "Cachoeira Grande", "CE"));
        lista.add(new Cidade("", "Cacimba Nova", "CE"));
        lista.add(new Cidade("", "Cacimbas", "CE"));
        lista.add(new Cidade("", "Caiçara", "CE"));
        lista.add(new Cidade("", "Caiçarinha", "CE"));
        lista.add(new Cidade("", "Caio Prado", "CE"));
        lista.add(new Cidade("", "Caioca", "CE"));
        lista.add(new Cidade("", "Caipu", "CE"));
        lista.add(new Cidade("", "Cajazeiras", "CE"));
        lista.add(new Cidade("", "Cajueiro", "CE"));
        lista.add(new Cidade("", "Calabaça", "CE"));
        lista.add(new Cidade("", "Caldas", "CE"));
        lista.add(new Cidade("", "Caldeirão", "CE"));
        lista.add(new Cidade("", "Califórnia", "CE"));
        lista.add(new Cidade("", "Camará", "CE"));
        lista.add(new Cidade("", "Camboas", "CE"));
        lista.add(new Cidade("", "Camilos", "CE"));
        lista.add(new Cidade("", "Camocim", "CE"));
        lista.add(new Cidade("", "Campanário", "CE"));
        lista.add(new Cidade("", "Campestre", "CE"));
        lista.add(new Cidade("", "Campo Alegre", "CE"));
        lista.add(new Cidade("", "Campos", "CE"));
        lista.add(new Cidade("", "Campos Belos", "CE"));
        lista.add(new Cidade("", "Campos Sales", "CE"));
        lista.add(new Cidade("", "Canaan", "CE"));
        lista.add(new Cidade("", "Canafistula", "CE"));
        lista.add(new Cidade("", "Canaúna", "CE"));
        lista.add(new Cidade("", "Cangati", "CE"));
        lista.add(new Cidade("", "Canindé", "CE"));
        lista.add(new Cidade("", "Canindezinho", "CE"));
        lista.add(new Cidade("", "Canta Galo", "CE"));
        lista.add(new Cidade("", "Capim de Roça", "CE"));
        lista.add(new Cidade("", "Capistrano", "CE"));
        lista.add(new Cidade("", "Capitão Mor", "CE"));
        lista.add(new Cidade("", "Capitão Pedro Sampaio", "CE"));
        lista.add(new Cidade("", "Caponga", "CE"));
        lista.add(new Cidade("", "Caponga da Bernarda", "CE"));
        lista.add(new Cidade("", "Caponguinha", "CE"));
        lista.add(new Cidade("", "Caracará", "CE"));
        lista.add(new Cidade("", "Caridade", "CE"));
        lista.add(new Cidade("", "Cariré", "CE"));
        lista.add(new Cidade("", "Caririaçu", "CE"));
        lista.add(new Cidade("", "Cariús", "CE"));
        lista.add(new Cidade("", "Cariutaba", "CE"));
        lista.add(new Cidade("", "Carmelópolis", "CE"));
        lista.add(new Cidade("", "Carnaúba", "CE"));
        lista.add(new Cidade("", "Carnaubal", "CE"));
        lista.add(new Cidade("", "Carnaúbas", "CE"));
        lista.add(new Cidade("", "Carnaubinha", "CE"));
        lista.add(new Cidade("", "Carquejo", "CE"));
        lista.add(new Cidade("", "Carrapateiras", "CE"));
        lista.add(new Cidade("", "Caruataí", "CE"));
        lista.add(new Cidade("", "Carvalho", "CE"));
        lista.add(new Cidade("", "Carvoeiro", "CE"));
        lista.add(new Cidade("", "Cascavel", "CE"));
        lista.add(new Cidade("", "Castanhão", "CE"));
        lista.add(new Cidade("", "Catarina", "CE"));
        lista.add(new Cidade("", "Catolé", "CE"));
        lista.add(new Cidade("", "Catolé da Pista", "CE"));
        lista.add(new Cidade("", "Catuana", "CE"));
        lista.add(new Cidade("", "Catunda", "CE"));
        lista.add(new Cidade("", "Caucaia", "CE"));
        lista.add(new Cidade("", "Caxitoré", "CE"));
        lista.add(new Cidade("", "Cedro", "CE"));
        lista.add(new Cidade("", "Cemoaba", "CE"));
        lista.add(new Cidade("", "Chaval", "CE"));
        lista.add(new Cidade("", "Chile", "CE"));
        lista.add(new Cidade("", "Choró", "CE"));
        lista.add(new Cidade("", "Chorozinho", "CE"));
        lista.add(new Cidade("", "Cipó", "CE"));
        lista.add(new Cidade("", "Cipó dos Anjos", "CE"));
        lista.add(new Cidade("", "Cococi", "CE"));
        lista.add(new Cidade("", "Codiá", "CE"));
        lista.add(new Cidade("", "Coité", "CE"));
        lista.add(new Cidade("", "Colina", "CE"));
        lista.add(new Cidade("", "Conceição", "CE"));
        lista.add(new Cidade("", "Coreaú", "CE"));
        lista.add(new Cidade("", "Córrego", "CE"));
        lista.add(new Cidade("", "Córrego dos Fernandes", "CE"));
        lista.add(new Cidade("", "Corrente", "CE"));
        lista.add(new Cidade("", "Crateús", "CE"));
        lista.add(new Cidade("", "Crato", "CE"));
        lista.add(new Cidade("", "Crioulos", "CE"));
        lista.add(new Cidade("", "Cristais", "CE"));
        lista.add(new Cidade("", "Croatá", "CE"));
        lista.add(new Cidade("", "Cruxati", "CE"));
        lista.add(new Cidade("", "Cruz", "CE"));
        lista.add(new Cidade("", "Cruz de Pedra", "CE"));
        lista.add(new Cidade("", "Cruzeirinho", "CE"));
        lista.add(new Cidade("", "Cuncas", "CE"));
        lista.add(new Cidade("", "Curatis", "CE"));
        lista.add(new Cidade("", "Curral Velho", "CE"));
        lista.add(new Cidade("", "Curupira", "CE"));
        lista.add(new Cidade("", "Custódio", "CE"));
        lista.add(new Cidade("", "Damião Carneiro", "CE"));
        lista.add(new Cidade("", "Daniel de Queirós", "CE"));
        lista.add(new Cidade("", "Delmiro Gouveia", "CE"));
        lista.add(new Cidade("", "Deputado Irapuan Pinheiro", "CE"));
        lista.add(new Cidade("", "Deserto", "CE"));
        lista.add(new Cidade("", "Dom Leme", "CE"));
        lista.add(new Cidade("", "Dom Maurício", "CE"));
        lista.add(new Cidade("", "Dom Quintino", "CE"));
        lista.add(new Cidade("", "Domingos da Costa", "CE"));
        lista.add(new Cidade("", "Donato", "CE"));
        lista.add(new Cidade("", "Dourado", "CE"));
        lista.add(new Cidade("", "Ebron", "CE"));
        lista.add(new Cidade("", "Ema", "CE"));
        lista.add(new Cidade("", "Ematuba", "CE"));
        lista.add(new Cidade("", "Encantado", "CE"));
        lista.add(new Cidade("", "Engenheiro João Tomé", "CE"));
        lista.add(new Cidade("", "Engenheiro José Lopes", "CE"));
        lista.add(new Cidade("", "Engenho Velho", "CE"));
        lista.add(new Cidade("", "Ererê", "CE"));
        lista.add(new Cidade("", "Espacinha", "CE"));
        lista.add(new Cidade("", "Esperança", "CE"));
        lista.add(new Cidade("", "Estrela", "CE"));
        lista.add(new Cidade("", "Eusébio", "CE"));
        lista.add(new Cidade("", "Faísca", "CE"));
        lista.add(new Cidade("", "Farias Brito", "CE"));
        lista.add(new Cidade("", "Fátima", "CE"));
        lista.add(new Cidade("", "Faveira", "CE"));
        lista.add(new Cidade("", "Feiticeiro", "CE"));
        lista.add(new Cidade("", "Feitosa", "CE"));
        lista.add(new Cidade("", "Felipe", "CE"));
        lista.add(new Cidade("", "Felizardo", "CE"));
        lista.add(new Cidade("", "Flamengo", "CE"));
        lista.add(new Cidade("", "Flores", "CE"));
        lista.add(new Cidade("", "Forquilha", "CE"));
        lista.add(new Cidade("", "Fortaleza", "CE"));
        lista.add(new Cidade("", "Fortim", "CE"));
        lista.add(new Cidade("", "Frecheirinha", "CE"));
        lista.add(new Cidade("", "Gadelha", "CE"));
        lista.add(new Cidade("", "Gado", "CE"));
        lista.add(new Cidade("", "Gado dos Rodrigues", "CE"));
        lista.add(new Cidade("", "Gameleira de São Sebastião", "CE"));
        lista.add(new Cidade("", "Garças", "CE"));
        lista.add(new Cidade("", "Gavião", "CE"));
        lista.add(new Cidade("", "Gázea", "CE"));
        lista.add(new Cidade("", "General Sampaio", "CE"));
        lista.add(new Cidade("", "General Tibúrcio", "CE"));
        lista.add(new Cidade("", "Gereraú", "CE"));
        lista.add(new Cidade("", "Giqui", "CE"));
        lista.add(new Cidade("", "Girau", "CE"));
        lista.add(new Cidade("", "Graça", "CE"));
        lista.add(new Cidade("", "Grande Basílio", "CE"));
        lista.add(new Cidade("", "Granja", "CE"));
        lista.add(new Cidade("", "Granjeiro", "CE"));
        lista.add(new Cidade("", "Groairas", "CE"));
        lista.add(new Cidade("", "Guaiúba", "CE"));
        lista.add(new Cidade("", "Guajiru", "CE"));
        lista.add(new Cidade("", "Guanacés", "CE"));
        lista.add(new Cidade("", "Guaraciaba do Norte", "CE"));
        lista.add(new Cidade("", "Guaramiranga", "CE"));
        lista.add(new Cidade("", "Guararu", "CE"));
        lista.add(new Cidade("", "Guassi", "CE"));
        lista.add(new Cidade("", "Guassossé", "CE"));
        lista.add(new Cidade("", "Guassussê", "CE"));
        lista.add(new Cidade("", "Guia", "CE"));
        lista.add(new Cidade("", "Guriú", "CE"));
        lista.add(new Cidade("", "Hidrolândia", "CE"));
        lista.add(new Cidade("", "Holanda", "CE"));
        lista.add(new Cidade("", "Horizonte", "CE"));
        lista.add(new Cidade("", "Iapi", "CE"));
        lista.add(new Cidade("", "Iara", "CE"));
        lista.add(new Cidade("", "Ibaretama", "CE"));
        lista.add(new Cidade("", "Ibiapaba", "CE"));
        lista.add(new Cidade("", "Ibiapina", "CE"));
        lista.add(new Cidade("", "Ibicatu", "CE"));
        lista.add(new Cidade("", "Ibicuã", "CE"));
        lista.add(new Cidade("", "Ibicuitaba", "CE"));
        lista.add(new Cidade("", "Ibicuitinga", "CE"));
        lista.add(new Cidade("", "Iborepi", "CE"));
        lista.add(new Cidade("", "Ibuaçu", "CE"));
        lista.add(new Cidade("", "Ibuguaçu", "CE"));
        lista.add(new Cidade("", "Icapuí", "CE"));
        lista.add(new Cidade("", "Icaraí", "CE"));
        lista.add(new Cidade("", "Icó", "CE"));
        lista.add(new Cidade("", "Icozinho", "CE"));
        lista.add(new Cidade("", "Ideal", "CE"));
        lista.add(new Cidade("", "Igaroi", "CE"));
        lista.add(new Cidade("", "Iguaçu", "CE"));
        lista.add(new Cidade("", "Iguatu", "CE"));
        lista.add(new Cidade("", "Independência", "CE"));
        lista.add(new Cidade("", "Ingazeiras", "CE"));
        lista.add(new Cidade("", "Inhamuns", "CE"));
        lista.add(new Cidade("", "Inhuçu", "CE"));
        lista.add(new Cidade("", "Inhuporanga", "CE"));
        lista.add(new Cidade("", "Ipaguaçú", "CE"));
        lista.add(new Cidade("", "Ipaporanga", "CE"));
        lista.add(new Cidade("", "Ipaumirim", "CE"));
        lista.add(new Cidade("", "Ipiranga", "CE"));
        lista.add(new Cidade("", "Ipu", "CE"));
        lista.add(new Cidade("", "Ipueiras", "CE"));
        lista.add(new Cidade("", "Ipueiras dos Gomes", "CE"));
        lista.add(new Cidade("", "Iracema", "CE"));
        lista.add(new Cidade("", "Irajá", "CE"));
        lista.add(new Cidade("", "Irapuã", "CE"));
        lista.add(new Cidade("", "Iratinga", "CE"));
        lista.add(new Cidade("", "Irauçuba", "CE"));
        lista.add(new Cidade("", "Isidoro", "CE"));
        lista.add(new Cidade("", "Itacima", "CE"));
        lista.add(new Cidade("", "Itacolomy", "CE"));
        lista.add(new Cidade("", "Itaguá", "CE"));
        lista.add(new Cidade("", "Itaguaruna", "CE"));
        lista.add(new Cidade("", "Itaiçaba", "CE"));
        lista.add(new Cidade("", "Itaipaba", "CE"));
        lista.add(new Cidade("", "Itaitinga", "CE"));
        lista.add(new Cidade("", "Itamaracá", "CE"));
        lista.add(new Cidade("", "Itans", "CE"));
        lista.add(new Cidade("", "Itapajé", "CE"));
        lista.add(new Cidade("", "Itapebussu", "CE"));
        lista.add(new Cidade("", "Itapeim", "CE"));
        lista.add(new Cidade("", "Itapipoca", "CE"));
        lista.add(new Cidade("", "Itapiúna", "CE"));
        lista.add(new Cidade("", "Itapó", "CE"));
        lista.add(new Cidade("", "Itarema", "CE"));
        lista.add(new Cidade("", "Itatira", "CE"));
        lista.add(new Cidade("", "Jaburuna", "CE"));
        lista.add(new Cidade("", "Jacampari", "CE"));
        lista.add(new Cidade("", "Jacarecoara", "CE"));
        lista.add(new Cidade("", "Jacaúna", "CE"));
        lista.add(new Cidade("", "Jaguarão", "CE"));
        lista.add(new Cidade("", "Jaguaretama", "CE"));
        lista.add(new Cidade("", "Jaguaribara", "CE"));
        lista.add(new Cidade("", "Jaguaribe", "CE"));
        lista.add(new Cidade("", "Jaguaruana", "CE"));
        lista.add(new Cidade("", "Jaibaras", "CE"));
        lista.add(new Cidade("", "Jamacaru", "CE"));
        lista.add(new Cidade("", "Jandrangoeira", "CE"));
        lista.add(new Cidade("", "Jardim", "CE"));
        lista.add(new Cidade("", "Jardimirim", "CE"));
        lista.add(new Cidade("", "Jati", "CE"));
        lista.add(new Cidade("", "Jenipapeiro", "CE"));
        lista.add(new Cidade("", "Jijoca de Jericoacoara", "CE"));
        lista.add(new Cidade("", "João Cordeiro", "CE"));
        lista.add(new Cidade("", "Jordão", "CE"));
        lista.add(new Cidade("", "José de Alencar", "CE"));
        lista.add(new Cidade("", "Juá", "CE"));
        lista.add(new Cidade("", "Juatama", "CE"));
        lista.add(new Cidade("", "Juazeiro de Baixo", "CE"));
        lista.add(new Cidade("", "Juazeiro do Norte", "CE"));
        lista.add(new Cidade("", "Jubaia", "CE"));
        lista.add(new Cidade("", "Jucá", "CE"));
        lista.add(new Cidade("", "Jucás", "CE"));
        lista.add(new Cidade("", "Jurema", "CE"));
        lista.add(new Cidade("", "Juritianha", "CE"));
        lista.add(new Cidade("", "Justiniano Serpa", "CE"));
        lista.add(new Cidade("", "Lacerda", "CE"));
        lista.add(new Cidade("", "Ladeira Grande", "CE"));
        lista.add(new Cidade("", "Lages", "CE"));
        lista.add(new Cidade("", "Lagoa da Cruz", "CE"));
        lista.add(new Cidade("", "Lagoa das Pedras", "CE"));
        lista.add(new Cidade("", "Lagoa de São João", "CE"));
        lista.add(new Cidade("", "Lagoa do Barro", "CE"));
        lista.add(new Cidade("", "Lagoa do Carneiro", "CE"));
        lista.add(new Cidade("", "Lagoa do Juvenal", "CE"));
        lista.add(new Cidade("", "Lagoa do Mato", "CE"));
        lista.add(new Cidade("", "Lagoa dos Crioulos", "CE"));
        lista.add(new Cidade("", "Lagoa Grande", "CE"));
        lista.add(new Cidade("", "Lagoinha", "CE"));
        lista.add(new Cidade("", "Lambedouro", "CE"));
        lista.add(new Cidade("", "Lameiro", "CE"));
        lista.add(new Cidade("", "Lapa", "CE"));
        lista.add(new Cidade("", "Laranjeiras", "CE"));
        lista.add(new Cidade("", "Lavras da Mangabeira", "CE"));
        lista.add(new Cidade("", "Lima Campos", "CE"));
        lista.add(new Cidade("", "Limoeiro do Norte", "CE"));
        lista.add(new Cidade("", "Lisieux", "CE"));
        lista.add(new Cidade("", "Livramento", "CE"));
        lista.add(new Cidade("", "Logradouro", "CE"));
        lista.add(new Cidade("", "Macambira", "CE"));
        lista.add(new Cidade("", "Macaóca", "CE"));
        lista.add(new Cidade("", "Macaraú", "CE"));
        lista.add(new Cidade("", "Maceió", "CE"));
        lista.add(new Cidade("", "Madalena", "CE"));
        lista.add(new Cidade("", "Major Simplício", "CE"));
        lista.add(new Cidade("", "Majorlândia", "CE"));
        lista.add(new Cidade("", "Malhada", "CE"));
        lista.add(new Cidade("", "Malhada Grande", "CE"));
        lista.add(new Cidade("", "Mangabeira", "CE"));
        lista.add(new Cidade("", "Manibu", "CE"));
        lista.add(new Cidade("", "Manituba", "CE"));
        lista.add(new Cidade("", "Manoel Correia", "CE"));
        lista.add(new Cidade("", "Manoel Guedes", "CE"));
        lista.add(new Cidade("", "Mapuá", "CE"));
        lista.add(new Cidade("", "Maracanaú", "CE"));
        lista.add(new Cidade("", "Maraguá", "CE"));
        lista.add(new Cidade("", "Maranguape", "CE"));
        lista.add(new Cidade("", "Mararupá", "CE"));
        lista.add(new Cidade("", "Maratoã", "CE"));
        lista.add(new Cidade("", "Maravilha", "CE"));
        lista.add(new Cidade("", "Marco", "CE"));
        lista.add(new Cidade("", "Marinheiros", "CE"));
        lista.add(new Cidade("", "Marrecas", "CE"));
        lista.add(new Cidade("", "Marrocos", "CE"));
        lista.add(new Cidade("", "Marruás", "CE"));
        lista.add(new Cidade("", "Martinópole", "CE"));
        lista.add(new Cidade("", "Martinslândia", "CE"));
        lista.add(new Cidade("", "Massapê", "CE"));
        lista.add(new Cidade("", "Mata Fresca", "CE"));
        lista.add(new Cidade("", "Matias", "CE"));
        lista.add(new Cidade("", "Matriz", "CE"));
        lista.add(new Cidade("", "Mauriti", "CE"));
        lista.add(new Cidade("", "Mel", "CE"));
        lista.add(new Cidade("", "Meruoca", "CE"));
        lista.add(new Cidade("", "Messejana", "CE"));
        lista.add(new Cidade("", "Miguel Xavier", "CE"));
        lista.add(new Cidade("", "Milagres", "CE"));
        lista.add(new Cidade("", "Milhã", "CE"));
        lista.add(new Cidade("", "Milton Belo", "CE"));
        lista.add(new Cidade("", "Mineirolândia", "CE"));
        lista.add(new Cidade("", "Miragem", "CE"));
        lista.add(new Cidade("", "Miraíma", "CE"));
        lista.add(new Cidade("", "Mirambé", "CE"));
        lista.add(new Cidade("", "Miranda", "CE"));
        lista.add(new Cidade("", "Missão Nova", "CE"));
        lista.add(new Cidade("", "Missão Velha", "CE"));
        lista.add(new Cidade("", "Missi", "CE"));
        lista.add(new Cidade("", "Mocambo", "CE"));
        lista.add(new Cidade("", "Moitas", "CE"));
        lista.add(new Cidade("", "Mombaça", "CE"));
        lista.add(new Cidade("", "Mondubim", "CE"));
        lista.add(new Cidade("", "Monguba", "CE"));
        lista.add(new Cidade("", "Monsenhor Tabosa", "CE"));
        lista.add(new Cidade("", "Monte Alegre", "CE"));
        lista.add(new Cidade("", "Monte Alverne", "CE"));
        lista.add(new Cidade("", "Monte Castelo", "CE"));
        lista.add(new Cidade("", "Monte Grave", "CE"));
        lista.add(new Cidade("", "Monte Sion", "CE"));
        lista.add(new Cidade("", "Montenebo", "CE"));
        lista.add(new Cidade("", "Morada Nova", "CE"));
        lista.add(new Cidade("", "Moraújo", "CE"));
        lista.add(new Cidade("", "Morrinhos", "CE"));
        lista.add(new Cidade("", "Morrinhos Novos", "CE"));
        lista.add(new Cidade("", "Morro Branco", "CE"));
        lista.add(new Cidade("", "Mosquito", "CE"));
        lista.add(new Cidade("", "Mucambo", "CE"));
        lista.add(new Cidade("", "Mulungu", "CE"));
        lista.add(new Cidade("", "Mumbaba", "CE"));
        lista.add(new Cidade("", "Mundau", "CE"));
        lista.add(new Cidade("", "Mundaú", "CE"));
        lista.add(new Cidade("", "Munguba", "CE"));
        lista.add(new Cidade("", "Muribeca", "CE"));
        lista.add(new Cidade("", "Muriti", "CE"));
        lista.add(new Cidade("", "Mutambeiras", "CE"));
        lista.add(new Cidade("", "Naraniu", "CE"));
        lista.add(new Cidade("", "Nascente", "CE"));
        lista.add(new Cidade("", "Nenenlândia", "CE"));
        lista.add(new Cidade("", "Nossa Senhora do Livramento", "CE"));
        lista.add(new Cidade("", "Nova Betânia", "CE"));
        lista.add(new Cidade("", "Nova Fátima", "CE"));
        lista.add(new Cidade("", "Nova Floresta", "CE"));
        lista.add(new Cidade("", "Nova Olinda", "CE"));
        lista.add(new Cidade("", "Nova Russas", "CE"));
        lista.add(new Cidade("", "Nova Santa Cruz", "CE"));
        lista.add(new Cidade("", "Nova Veneza", "CE"));
        lista.add(new Cidade("", "Nova Vida", "CE"));
        lista.add(new Cidade("", "Novo Assis", "CE"));
        lista.add(new Cidade("", "Novo Horizonte", "CE"));
        lista.add(new Cidade("", "Novo Oriente", "CE"));
        lista.add(new Cidade("", "Núcleo Colonial Pio XII", "CE"));
        lista.add(new Cidade("", "Ocara", "CE"));
        lista.add(new Cidade("", "Oiticica", "CE"));
        lista.add(new Cidade("", "Olho D'Água", "CE"));
        lista.add(new Cidade("", "Olho D'água do Bezerril", "CE"));
        lista.add(new Cidade("", "Olho-D'Água", "CE"));
        lista.add(new Cidade("", "Olho-D'Água da Bica", "CE"));
        lista.add(new Cidade("", "Oliveiras", "CE"));
        lista.add(new Cidade("", "Orós", "CE"));
        lista.add(new Cidade("", "Pacajus", "CE"));
        lista.add(new Cidade("", "Pacatuba", "CE"));
        lista.add(new Cidade("", "Pacoti", "CE"));
        lista.add(new Cidade("", "Pacujá", "CE"));
        lista.add(new Cidade("", "Padre Cícero", "CE"));
        lista.add(new Cidade("", "Padre Linhares", "CE"));
        lista.add(new Cidade("", "Padre Vieira", "CE"));
        lista.add(new Cidade("", "Pai João", "CE"));
        lista.add(new Cidade("", "Pajeú", "CE"));
        lista.add(new Cidade("", "Palestina", "CE"));
        lista.add(new Cidade("", "Palestina do Norte", "CE"));
        lista.add(new Cidade("", "Palhano", "CE"));
        lista.add(new Cidade("", "Palmácia", "CE"));
        lista.add(new Cidade("", "Palmatória", "CE"));
        lista.add(new Cidade("", "Panacuí", "CE"));
        lista.add(new Cidade("", "Papara", "CE"));
        lista.add(new Cidade("", "Paracuá", "CE"));
        lista.add(new Cidade("", "Paracuru", "CE"));
        lista.add(new Cidade("", "Paraipaba", "CE"));
        lista.add(new Cidade("", "Paraiso", "CE"));
        lista.add(new Cidade("", "Parajuru", "CE"));
        lista.add(new Cidade("", "Parambu", "CE"));
        lista.add(new Cidade("", "Paramoti", "CE"));
        lista.add(new Cidade("", "Parangaba", "CE"));
        lista.add(new Cidade("", "Parapuí", "CE"));
        lista.add(new Cidade("", "Parazinho", "CE"));
        lista.add(new Cidade("", "Paripueira", "CE"));
        lista.add(new Cidade("", "Pascoal", "CE"));
        lista.add(new Cidade("", "Passagem", "CE"));
        lista.add(new Cidade("", "Passagem Funda", "CE"));
        lista.add(new Cidade("", "Pasta", "CE"));
        lista.add(new Cidade("", "Patacas", "CE"));
        lista.add(new Cidade("", "Patos", "CE"));
        lista.add(new Cidade("", "Patos dos Liberatos", "CE"));
        lista.add(new Cidade("", "Patriarca", "CE"));
        lista.add(new Cidade("", "Paus Branco", "CE"));
        lista.add(new Cidade("", "Paus Brancos", "CE"));
        lista.add(new Cidade("", "Pavuna", "CE"));
        lista.add(new Cidade("", "Pecém", "CE"));
        lista.add(new Cidade("", "Pedra Branca", "CE"));
        lista.add(new Cidade("", "Pedra de Fogo", "CE"));
        lista.add(new Cidade("", "Pedra e Cal", "CE"));
        lista.add(new Cidade("", "Pedras", "CE"));
        lista.add(new Cidade("", "Pedras Brancas", "CE"));
        lista.add(new Cidade("", "Pedrinhas", "CE"));
        lista.add(new Cidade("", "Peixe", "CE"));
        lista.add(new Cidade("", "Peixe Gordo", "CE"));
        lista.add(new Cidade("", "Penaforte", "CE"));
        lista.add(new Cidade("", "Penedo", "CE"));
        lista.add(new Cidade("", "Pentecoste", "CE"));
        lista.add(new Cidade("", "Pereiro", "CE"));
        lista.add(new Cidade("", "Pernambuquinho", "CE"));
        lista.add(new Cidade("", "Pessoa Anta", "CE"));
        lista.add(new Cidade("", "Pindoguaba", "CE"));
        lista.add(new Cidade("", "Pindoretama", "CE"));
        lista.add(new Cidade("", "Pio X", "CE"));
        lista.add(new Cidade("", "Piquet Carneiro", "CE"));
        lista.add(new Cidade("", "Pirabibu", "CE"));
        lista.add(new Cidade("", "Pirangi", "CE"));
        lista.add(new Cidade("", "Pires Ferreira", "CE"));
        lista.add(new Cidade("", "Pitombeira", "CE"));
        lista.add(new Cidade("", "Pitombeiras", "CE"));
        lista.add(new Cidade("", "Plácido Martins", "CE"));
        lista.add(new Cidade("", "Planalto", "CE"));
        lista.add(new Cidade("", "Poço", "CE"));
        lista.add(new Cidade("", "Poço Comprido", "CE"));
        lista.add(new Cidade("", "Poço da Onça", "CE"));
        lista.add(new Cidade("", "Poço Doce", "CE"));
        lista.add(new Cidade("", "Poço Grande", "CE"));
        lista.add(new Cidade("", "Poço Verde", "CE"));
        lista.add(new Cidade("", "Ponta da Serra", "CE"));
        lista.add(new Cidade("", "Poranga", "CE"));
        lista.add(new Cidade("", "Porfirio Sampaio", "CE"));
        lista.add(new Cidade("", "Porteiras", "CE"));
        lista.add(new Cidade("", "Potengi", "CE"));
        lista.add(new Cidade("", "Poti", "CE"));
        lista.add(new Cidade("", "Potiretama", "CE"));
        lista.add(new Cidade("", "Prata", "CE"));
        lista.add(new Cidade("", "Pratiús", "CE"));
        lista.add(new Cidade("", "Prefeita Suely Pinheiro", "CE"));
        lista.add(new Cidade("", "Prudente de Morais", "CE"));
        lista.add(new Cidade("", "Quatiguaba", "CE"));
        lista.add(new Cidade("", "Queimados", "CE"));
        lista.add(new Cidade("", "Quimami", "CE"));
        lista.add(new Cidade("", "Quincoé", "CE"));
        lista.add(new Cidade("", "Quincuncá", "CE"));
        lista.add(new Cidade("", "Quitaiús", "CE"));
        lista.add(new Cidade("", "Quiterianópolis", "CE"));
        lista.add(new Cidade("", "Quixadá", "CE"));
        lista.add(new Cidade("", "Quixariú", "CE"));
        lista.add(new Cidade("", "Quixelô", "CE"));
        lista.add(new Cidade("", "Quixeramobim", "CE"));
        lista.add(new Cidade("", "Quixeré", "CE"));
        lista.add(new Cidade("", "Rafael Arruda", "CE"));
        lista.add(new Cidade("", "Raimundo Martins", "CE"));
        lista.add(new Cidade("", "Ramadinha", "CE"));
        lista.add(new Cidade("", "Realejo", "CE"));
        lista.add(new Cidade("", "Recanto", "CE"));
        lista.add(new Cidade("", "Redenção", "CE"));
        lista.add(new Cidade("", "Repartição", "CE"));
        lista.add(new Cidade("", "Reriutaba", "CE"));
        lista.add(new Cidade("", "Retiro", "CE"));
        lista.add(new Cidade("", "Riachão", "CE"));
        lista.add(new Cidade("", "Riacho Grande", "CE"));
        lista.add(new Cidade("", "Riacho Verde", "CE"));
        lista.add(new Cidade("", "Riacho Vermelho", "CE"));
        lista.add(new Cidade("", "Rinaré", "CE"));
        lista.add(new Cidade("", "Roldão", "CE"));
        lista.add(new Cidade("", "Rosário", "CE"));
        lista.add(new Cidade("", "Russas", "CE"));
        lista.add(new Cidade("", "Sabiaguaba", "CE"));
        lista.add(new Cidade("", "Saboeiro", "CE"));
        lista.add(new Cidade("", "Sacramento", "CE"));
        lista.add(new Cidade("", "Salão", "CE"));
        lista.add(new Cidade("", "Salgado dos Machados", "CE"));
        lista.add(new Cidade("", "Salgado dos Mendes", "CE"));
        lista.add(new Cidade("", "Salitre", "CE"));
        lista.add(new Cidade("", "Sambaíba", "CE"));
        lista.add(new Cidade("", "Santa Ana", "CE"));
        lista.add(new Cidade("", "Santa Cruz do Banabuiú", "CE"));
        lista.add(new Cidade("", "Santa Fé", "CE"));
        lista.add(new Cidade("", "Santa Felícia", "CE"));
        lista.add(new Cidade("", "Santa Luzia", "CE"));
        lista.add(new Cidade("", "Santa Quitéria", "CE"));
        lista.add(new Cidade("", "Santa Rita", "CE"));
        lista.add(new Cidade("", "Santa Rosa", "CE"));
        lista.add(new Cidade("", "Santa Tereza", "CE"));
        lista.add(new Cidade("", "Santana", "CE"));
        lista.add(new Cidade("", "Santana do Acaraú", "CE"));
        lista.add(new Cidade("", "Santana do Cariri", "CE"));
        lista.add(new Cidade("", "Santarém", "CE"));
        lista.add(new Cidade("", "Santo André", "CE"));
        lista.add(new Cidade("", "Santo Antônio", "CE"));
        lista.add(new Cidade("", "Santo Antônio da Pindoba", "CE"));
        lista.add(new Cidade("", "Santo Antônio dos Fernandes", "CE"));
        lista.add(new Cidade("", "São Bartolomeu", "CE"));
        lista.add(new Cidade("", "São Benedito", "CE"));
        lista.add(new Cidade("", "São Bernardo", "CE"));
        lista.add(new Cidade("", "São Domingos", "CE"));
        lista.add(new Cidade("", "São Felipe", "CE"));
        lista.add(new Cidade("", "São Francisco", "CE"));
        lista.add(new Cidade("", "São Gonçalo do Amarante", "CE"));
        lista.add(new Cidade("", "São Gonçalo do Umari", "CE"));
        lista.add(new Cidade("", "São João", "CE"));
        lista.add(new Cidade("", "São João de Deus", "CE"));
        lista.add(new Cidade("", "São João do Amanari", "CE"));
        lista.add(new Cidade("", "São João do Jaguaribe", "CE"));
        lista.add(new Cidade("", "São João dos Queiroz", "CE"));
        lista.add(new Cidade("", "São Joaquim", "CE"));
        lista.add(new Cidade("", "São Joaquim do Salgado", "CE"));
        lista.add(new Cidade("", "São José", "CE"));
        lista.add(new Cidade("", "São José das Lontras", "CE"));
        lista.add(new Cidade("", "São José de Solonópole", "CE"));
        lista.add(new Cidade("", "São José do Lagamar", "CE"));
        lista.add(new Cidade("", "São José do Torto", "CE"));
        lista.add(new Cidade("", "São Luís do Curu", "CE"));
        lista.add(new Cidade("", "São Miguel", "CE"));
        lista.add(new Cidade("", "São Paulinho", "CE"));
        lista.add(new Cidade("", "São Pedro", "CE"));
        lista.add(new Cidade("", "São Pedro do Gavião", "CE"));
        lista.add(new Cidade("", "São Pedro do Norte", "CE"));
        lista.add(new Cidade("", "São Raimundo", "CE"));
        lista.add(new Cidade("", "São Romão", "CE"));
        lista.add(new Cidade("", "São Roque", "CE"));
        lista.add(new Cidade("", "São Sebastião", "CE"));
        lista.add(new Cidade("", "São Tomé", "CE"));
        lista.add(new Cidade("", "São Vicente", "CE"));
        lista.add(new Cidade("", "Sapo", "CE"));
        lista.add(new Cidade("", "Sapupara", "CE"));
        lista.add(new Cidade("", "Saquinho", "CE"));
        lista.add(new Cidade("", "Sebastião de Abreu", "CE"));
        lista.add(new Cidade("", "Senador Carlos Jereissati", "CE"));
        lista.add(new Cidade("", "Senador Pompeu", "CE"));
        lista.add(new Cidade("", "Senador Sá", "CE"));
        lista.add(new Cidade("", "Sereno de Cima", "CE"));
        lista.add(new Cidade("", "Serra do Félix", "CE"));
        lista.add(new Cidade("", "Serragem", "CE"));
        lista.add(new Cidade("", "Serrota", "CE"));
        lista.add(new Cidade("", "Serrote", "CE"));
        lista.add(new Cidade("", "Serrote do Meio", "CE"));
        lista.add(new Cidade("", "Simão", "CE"));
        lista.add(new Cidade("", "Sitiá", "CE"));
        lista.add(new Cidade("", "Sítio Alegre", "CE"));
        lista.add(new Cidade("", "Sítios Novos", "CE"));
        lista.add(new Cidade("", "Siupê", "CE"));
        lista.add(new Cidade("", "Sobral", "CE"));
        lista.add(new Cidade("", "Soledade", "CE"));
        lista.add(new Cidade("", "Solidão", "CE"));
        lista.add(new Cidade("", "Solonópole", "CE"));
        lista.add(new Cidade("", "Suassurana", "CE"));
        lista.add(new Cidade("", "Sucatinga", "CE"));
        lista.add(new Cidade("", "Sucesso", "CE"));
        lista.add(new Cidade("", "Sussuanha", "CE"));
        lista.add(new Cidade("", "Tabainha", "CE"));
        lista.add(new Cidade("", "Taboleiro", "CE"));
        lista.add(new Cidade("", "Tabuleiro do Norte", "CE"));
        lista.add(new Cidade("", "Taíba", "CE"));
        lista.add(new Cidade("", "Tamboril", "CE"));
        lista.add(new Cidade("", "Tangente", "CE"));
        lista.add(new Cidade("", "Tanques", "CE"));
        lista.add(new Cidade("", "Tapera", "CE"));
        lista.add(new Cidade("", "Taperuaba", "CE"));
        lista.add(new Cidade("", "Tapuiara", "CE"));
        lista.add(new Cidade("", "Tapuio", "CE"));
        lista.add(new Cidade("", "Targinos", "CE"));
        lista.add(new Cidade("", "Tarrafas", "CE"));
        lista.add(new Cidade("", "Tauá", "CE"));
        lista.add(new Cidade("", "Tejuçuoca", "CE"));
        lista.add(new Cidade("", "Tianguá", "CE"));
        lista.add(new Cidade("", "Timbaúba dos Marinheiros", "CE"));
        lista.add(new Cidade("", "Timonha", "CE"));
        lista.add(new Cidade("", "Tipi", "CE"));
        lista.add(new Cidade("", "Tomé", "CE"));
        lista.add(new Cidade("", "Trairi", "CE"));
        lista.add(new Cidade("", "Trapiá", "CE"));
        lista.add(new Cidade("", "Triângulo", "CE"));
        lista.add(new Cidade("", "Trici", "CE"));
        lista.add(new Cidade("", "Triunfo", "CE"));
        lista.add(new Cidade("", "Tróia", "CE"));
        lista.add(new Cidade("", "Trussu", "CE"));
        lista.add(new Cidade("", "Tucunduba", "CE"));
        lista.add(new Cidade("", "Tucuns", "CE"));
        lista.add(new Cidade("", "Tuína", "CE"));
        lista.add(new Cidade("", "Tururu", "CE"));
        lista.add(new Cidade("", "Ubajara", "CE"));
        lista.add(new Cidade("", "Ubaúna", "CE"));
        lista.add(new Cidade("", "Ubiraçu", "CE"));
        lista.add(new Cidade("", "Uiraponga", "CE"));
        lista.add(new Cidade("", "Umari", "CE"));
        lista.add(new Cidade("", "Umarituba", "CE"));
        lista.add(new Cidade("", "Umarizeiras", "CE"));
        lista.add(new Cidade("", "Umburanas", "CE"));
        lista.add(new Cidade("", "Umirim", "CE"));
        lista.add(new Cidade("", "União", "CE"));
        lista.add(new Cidade("", "Uruburetama", "CE"));
        lista.add(new Cidade("", "Uruoca", "CE"));
        lista.add(new Cidade("", "Uruquê", "CE"));
        lista.add(new Cidade("", "Varjota", "CE"));
        lista.add(new Cidade("", "Várzea", "CE"));
        lista.add(new Cidade("", "Várzea Alegre", "CE"));
        lista.add(new Cidade("", "Várzea da Onça", "CE"));
        lista.add(new Cidade("", "Várzea da Volta", "CE"));
        lista.add(new Cidade("", "Várzea do Gilo", "CE"));
        lista.add(new Cidade("", "Várzea dos Espinhos", "CE"));
        lista.add(new Cidade("", "Vazantes", "CE"));
        lista.add(new Cidade("", "Vazente do Curú", "CE"));
        lista.add(new Cidade("", "Velame", "CE"));
        lista.add(new Cidade("", "Ventura", "CE"));
        lista.add(new Cidade("", "Vertentes do Lagedo", "CE"));
        lista.add(new Cidade("", "Viçosa", "CE"));
        lista.add(new Cidade("", "Viçosa do Ceará", "CE"));
        lista.add(new Cidade("", "Video", "CE"));
        lista.add(new Cidade("", "Vila Soares", "CE"));
        lista.add(new Cidade("", "Vista Alegre", "CE"));
        return lista;
    }
}
