package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class CE {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("lOHASyJwWcxwNap0bFpX","Abaiara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PgzWycklaBqL2liYunPQ","Abílio Martins","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XvQNY0gqO4WQYsvpXvTF","Acarape","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jExhLrgNpXO6lyrOZY1Z","Acaraú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RQfyKwOQS3qZBddUCMio","Acopiara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PU6Dq7Vsv8naSu1skOyx","Açude dos Pinheiros","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5DsJ4ciw6vaGMULAxkCo","Açudinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nW0NW9xZEhaueJVkDAgv","Açudinho dos Costas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("OeBtJCqsZHKEoF8KUoVp","Adrianópolis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("L7lAPpFZdn3hmholjUED","Água Fria","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("srnNTHqay16fYhP1Xd1e","Água Verde","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RDvb9z7LpPTPYcIqPoeX","Aguaí","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("N7w4mPenEpSEOYdlTcgw","Águas Belas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("n0pt1nSTarD9TXV8ABcJ","Aiuá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("r8oItP7w0nu7wOTzkDkL","Aiuaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5IR1QGRsHMebqoupjgP8","Alagoinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HQYngAt3nqijy52FwHOZ","Alazans","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yvr1qqwpHw7beAk6q6NP","Alcântaras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rjCztWNzCcunQAHcfZC2","Algodões","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CtoNU2jOwPnt8f1IHLHw","Almofala","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("iMSliGoKYvk2t7NU1Uuc","Altaneira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("v3PqzfSdgwMKvM7gx29x","Alto Lindo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("0pwoJ5OPnFR72uWBKuAF","Alto Santo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kZC5xvAEkoY61Hs0aJW9","Amanaiara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("gUaWkfhcdd7myPKEts7w","Amanari","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7JL54Zmyrrh6okMKugbp","Amaniutuba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6FnOVkgbF365fvNaEJIN","Amarelas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("21TyeAsPLjLKtoPvM2xs","Amaro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("83V2kjDLDPgi6DFb8XyA","América","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CYZbyVO82DpnQ3lLQrTa","Amontada","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZytQTDX97gqusHxNt94L","Anauá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GTOhbKXIEzVbZAddgV0h","Anil","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xThZyiWBsGNs3fzElfK7","Aningás","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MmOmU09m5yrfqTEcNXMb","Anjinhos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("T1mcVBBWFOvnAeYAcvIo","Antonina do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("QknOp1dekD3QuWQIB7oO","Antônio Bezerra","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JemM9RGGPWy9WNDUQnzt","Antônio Diogo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("v6c5K2P1dFa8Yg3qWH0B","Antônio Marques","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("V47IN6EfsKLIhyHzXfAK","Aprazível","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SDY6QrQkyeaQvnyIpao2","Apuiarés","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6QJ0ohKOu90lGI8BMioF","Aquinópolis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6WLu3gmiYblruiyvxmDu","Aquiraz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jfztemxrsHck5TyA0ItU","Araçás","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8Gj0XQooEhqtFzddYZPC","Aracati","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ix9E62FVQOUIC74l8wXa","Aracatiaçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UxVuofFJ1buVeOP5gDay","Aracatiara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("svItU22JDb5B6LPXLamp","Aracoiaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9QtqGo4U62c3m55t2cVU","Arajara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("iLaKrg4M5VaePXeDahvP","Aranaú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("i6LimXRShXsMdgMA2roi","Arapá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Mug0I2UaclBF3WIiW8tU","Arapari","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Ee3AEb0jaAO72vbbFnEe","Araporanga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("otj1BkfRAtaruUAa8HT6","Araquém","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("m4mJhT9n3GrNC1vzjbsA","Ararendá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Ip8vv4M4YI9iXXq1bccI","Araripe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FTANjgN9rLSRAWI2wvn5","Arariús","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("oY62gBOBU3fGAqCr8HU5","Aratama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("QzWKizTfm55BnMAcaRA7","Araticum","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qlxj1GBb3MVLldAZ03DL","Aratuba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4vHgecDTgdsuNsSldpLV","Areial","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dWsqjyaS4zk3yTOZduXe","Areré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("beYshlF04lS2IJn3KfHw","Ariscos dos Marianos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Gm3gAZDC1rrL6hbRN39G","Arneiroz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xIyKHZ7liOtEJjHoRztN","Aroeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2J2FbsWh4DyHyW3BC3XU","Arrojado","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("eF2efQeTyoUwGj09JdEb","Aruaru","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AwQLYC7e2Mu9Nzj8PEpV","Assaré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6Ae0mXf5GxYjG4Wd1eRd","Assis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("l8ArytBqhASma4DPictU","Assunção","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vgD7SG348a12ziDg61kO","Aurora","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mDRhgPbJlfG1WKNuOG9M","Baixa Fria","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("imZsInGdNIOHC0I3KcRL","Baixa Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ryQcy3garyAqo2ypiaSb","Baixio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("j4Mp6zBwV0zP8mmagT57","Baixio da Donana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PATQyuj9nKfLvUQdJ7Cr","Baixio das Palmeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cjcvkzsYlABCfohL2NkZ","Baleia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pwhrcAE1Tf9GooIS1vJH","Balseiros","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("O48r7xz69nHha6qKrn3V","Banabuiú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SqguXZpGg00BG6AwBhH0","Bandeira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2S6lWZKj024uOXpq2wMl","Baracho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9YBlIyiyRN17eU099lfw","Barão de Aquiraz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6XlWzf5F5ahE5e1odYGz","Barbada","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9kwcKTOzsieSeokJZmes","Barbalha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WfXDy0IaaZSd7btogEAE","Barra","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FMCpvU2bcLN5AI0MqxIg","Barra do Ingá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6d9NTHlBePoPh3zMhfX6","Barra do Sotero","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZFnsRoWp4Mdl2f2lQk6Y","Barra Nova","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5KdcKHrmEBqXRgyKXrO9","Barreira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Yox72PVvCF2w6XTrRz24","Barreira dos Vianas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vCeLmlIuz3riZT8BB2cK","Barreiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("OtEacaCI8syPRgAy5E4b","Barreiros","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8RLaJctaD7CMchCqLWyB","Barrento","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aCJ3xP7eraFOjpQ61LxW","Barrinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hsxL4KZycnFpUnCSITyH","Barro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("29trZXDkfIzIR8odrkk5","Barro Alto","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KZFxuMvJ4Zg33nZ1IFKl","Barroquinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RdbNA29k52RjOei9YBfx","Bastiões","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XlS7KncXyRw1fVThLwOn","Baturité","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Xdbu6mYrU3jTsvHuBVYp","Baú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IPqgZUWN3iQpWMOSSa7L","Beberibe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4RxAorNpQ23d2GX8Rxqa","Bela Cruz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RPOem4TwxqXHQ7SyinR8","Bela Vista","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Rq8gUe2jZe8yoJKW11yz","Belém","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hI4662bA6snTU82YBz6m","Belmonte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lDhGTI05LocCk25AOIKj","Betânia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("luDavPBxHfuAdlpDLexT","Bilheira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6IaNqAqpkhjH3rwiYjod","Bitupitá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Nq7P8azyz5TR4c25RIry","Bixopa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lbrfr15urzwOC9iXBrDj","Boa Água","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mJfshdV765DdOkw8thOL","Boa Esperança","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MAdQXsp2iMSeBqx3kBRt","Boa Viagem","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3jN4ljnyMfNPhNtRwDXg","Boa Vista","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AHs9LH1h65IgGWn23gXf","Boa Vista do Caxitoré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LsbkAznftuqe1CPhtiWL","Bom Princípio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("va17kIHF26W6BJiGra0O","Bonfim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZtAOXk7cdraUydZExt8F","Bonhu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("uAnfrxLp0pqE8YKhPrjU","Bonito","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yEMiAtxm6esVNNSaGhu6","Boqueirão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CIiFok5b1W7iwrhqbDhU","Borges","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xtfdG8mAHhx2tHsW1bzi","Brejinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("86tYqF9JY0ZznMo9bD0U","Brejo Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BMvWQQkfnzsqSC7O0sif","Brejo Santo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("l6490ZOIf38gR8CieJSw","Brotas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3ifTVygOPq0IIcZsTMDA","Buritizal","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yPOh3XHKv5s0zeoehLHP","Buritizinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("03AECvJGtF39AgLvC9qk","Cabreiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kkEcdEzAEBnMufJ0prWY","Cachoeira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lftedx4za7RPmlsmI6Xf","Cachoeira de Fora","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SeKqkvfu2J0wSidz8uxe","Cachoeira Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("m7KMP7WfICDrBgm1TP22","Cacimba Nova","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xdWcfAoiFeHec9lYziyM","Cacimbas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WkNa4Fiy4ZKrqPbRF2sx","Caiçara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("puXoFtfD6XLCGuhGLuHO","Caiçarinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cd6bFVNkFt3Q6nj9ZNXt","Caio Prado","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4gLsz8UiPFyLWzN4P7WE","Caioca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("E9GEsUDyBueg6GRCFL8m","Caipu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qdbnwkHGswfSHRTKLNeE","Cajazeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Vv3znbySXxVNIXE1Ko4a","Cajueiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VuVehx10KfDtosCaPr2x","Calabaça","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SCIjccGhNF5jUWOIcdLo","Caldas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("T1CD7aX5D1ZUbpMs6xEB","Caldeirão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("j3l6xt9ZVejaRgwR9E7t","Califórnia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wN2Mvt1ntG43QIy7Uaf8","Camará","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IUdyznmI9yeSyP8OfoLm","Camboas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SQA59UAl6u0KaMntZ2mj","Camilos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("eDuww8XA0tRpFYNbkUvJ","Camocim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("P3cqLLuiVi2b9IaGmlIZ","Campanário","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xYXyMiKw6oA56yY0glL9","Campestre","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9t5Ys78cT0SQBQMmdBRd","Campo Alegre","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ys6Zgct7QEE0txmyB2SK","Campos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9ZFTGJAZSBPO5OVOBAZs","Campos Belos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IBVh9c9uRfa7ZATNDO13","Campos Sales","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("19D0gAtXdttX9iVSv0AI","Canaan","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("44obX0j7CmibclbzmBz5","Canafistula","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IVmDu5cOjwo2MkCeDcIT","Canaúna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CJ2tvDHC0J4JZJe3Ig2B","Cangati","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("r6W8e3OQXEOjdRlFiMU4","Canindé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Rsmkl6nFUNyp0hvLeNna","Canindezinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hQweIkdDO67voGRpRfoO","Canta Galo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RY5nRAnGfuCGRDRaBuR8","Capim de Roça","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("iWUqeD7wmpAHCMlDGVO4","Capistrano","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("swQsTpdrRy1Z4SWes2Hb","Capitão Mor","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MRv6qlAhKdrvKmoryTGJ","Capitão Pedro Sampaio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Os001xUaHh0b7lmKOh56","Caponga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IGHiGWZRswXwTu8NtWMl","Caponga da Bernarda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("greYdwucTIAkKpZqj0vA","Caponguinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KKd9dqdaqtaVfVTRRVRk","Caracará","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("noOjv4Bzzq1HGS2aHxcL","Caridade","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RZVY1oQEzDhTTqouLPVy","Cariré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2Y54UNxpkdVcCLEB0Zvt","Caririaçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("S3rG5KFR6J2wixjFZgGf","Cariús","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Rg3SE65pEas94TW7fiYS","Cariutaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("G8X9FTsvjytFVa7UzXbz","Carmelópolis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("80eyaYiBSwyGh6mMAewi","Carnaúba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nscl2FLkVsyWGPIS4dpd","Carnaubal","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SWYHBq5yuq6cIL7sjgvQ","Carnaúbas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6oACMlkfotwwnU1xGtjR","Carnaubinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MpZt2fmxWINawNTgjP8r","Carquejo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("iH0suboH4nDQUoLmZZTv","Carrapateiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("E36p7jXfqZHTgbYfgBF7","Caruataí","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DKvalD8vZ00uJ87FHUEd","Carvalho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("879oWY4p8AxLF6EybxqA","Carvoeiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("I83JUge49OYcqvV8mIGN","Cascavel","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7BZh8OhflNKgA2J7xzlb","Castanhão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DebVRFmlCpdJoNkNcRYb","Catarina","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dmSV3W4I3Yo0gsbgajeZ","Catolé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8vu12SxcWlfIUlSQvWPT","Catolé da Pista","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Kn69Udxr1dB4QrCcDfDb","Catuana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kAZlhguJ85TnbdOYBCHK","Catunda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3efLIfZ7QkLiPZvVpMi2","Caucaia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3IY2HnKEWOYbactakBbn","Caxitoré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3jw1TW5ZhtaFRH6nBcvb","Cedro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TMFKFFL78kJJRxFypzIh","Cemoaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aLvG03g7CuzXzUQPbVJ9","Chaval","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rbtx62WPb7kQrv1Yr7t2","Chile","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("NSU7TX9ekzdKTq4azdIr","Choró","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("piEb9xURyQxZT03rfEXn","Chorozinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rJzgxBBtWLLBpjre7A9c","Cipó","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ihbpFUCSRnDWCoTOOMkI","Cipó dos Anjos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("OlD9P6PyApO9NFOHCSc4","Cococi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nfRB9rU5aCyx30fp5CTa","Codiá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DUZAcAQL1gf77wgfPTMo","Coité","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GIbfOunj3wFpRHsY13f2","Colina","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("L5NRLDngX1LtTYgymamV","Conceição","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1sVtlfvJUyGxQxtQPMe6","Coreaú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UjbrpCpgKSRqDBwlTEwJ","Córrego","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vxcSzCc1nDSEZAHioUJx","Córrego dos Fernandes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fqagh1VxcU26g4pw08Ot","Corrente","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7XHhJKgFQHVti6pXJCSg","Crateús","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dzJl1dQSp5bW0wdFr1gS","Crato","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nATQ8yQKeOGhTNfGisSQ","Crioulos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pmOLxd2PCUuBb5ekqneJ","Cristais","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("j7CWAacBZWLdyRl7SkS2","Croatá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vfOv62kHvtwGycqbpHrz","Cruxati","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("uufSOYYl06FZuV6g30hz","Cruz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("teo4KTHg88lODWj94Rcx","Cruz de Pedra","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("daY5Hnfu910892SX57zz","Cruzeirinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6daOV4MXlagz409UjZwz","Cuncas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cQ0WzPyJt1qwcYha4hAh","Curatis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WhYPfd72gFJE5CMLgCTP","Curral Velho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9mYTzrUsp1AD2HuwhAlC","Curupira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("328abloFuluZ1zvkIZJS","Custódio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4Fsy2cF1SI93nmK6GYwu","Damião Carneiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("koRLOiHl2qxhuws1vMut","Daniel de Queirós","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2mKcyp7sTBHLaPi4WG3K","Delmiro Gouveia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AwTXnyWuMDrGbErqt1dr","Deputado Irapuan Pinheiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8GMCmIkK36shglLECIMi","Deserto","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ozcHHFwrIyvsX54tDsef","Dom Leme","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LFhcZrjg8cwoThx7w7LM","Dom Maurício","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4sqr0m3zYhyQ6iKQFCau","Dom Quintino","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("d4gXoFtKAEJjkZEKBEbH","Domingos da Costa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("S4o3WZRzPbg7ZjaAhnJE","Donato","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Hyh1VundKf9wSiWYo7K3","Dourado","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("NW3suCC373nLlzvdGrio","Ebron","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7uOWrWTBwJkPkh4Fcnn4","Ema","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("O3FrHK7DyElCGKMACrAa","Ematuba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tiAGgKQbx9Jytyh5ZtKf","Encantado","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wisXzQjLhTJyNNzlTtvN","Engenheiro João Tomé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LJTabQutcPT1iRSqA7I3","Engenheiro José Lopes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YnMieUgQcRBrjyIJvZ3G","Engenho Velho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mHntlMUnFlSbqlEC3yLj","Ererê","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Nm0rOZAoE7CuQUs5Zrmw","Espacinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mjzSY7DsWUWocszzILBv","Esperança","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xo5ZwZ8ttuAO8gE73Azg","Estrela","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("0lNIKNPH2G4iFpVsxcox","Eusébio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BDBBJkeunAAgmCr5QFaK","Faísca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3xGy7qxfcSjbA1NPAsff","Farias Brito","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("R0gpEmfIvFYTfXfUEu5m","Fátima","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fcDJeG7qtWXP4PlMTFyD","Faveira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("oDuuHHY3Py5ZScyTcrDJ","Feiticeiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bNL59on7aoiT3ZJfLME8","Feitosa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FBNf5B6pMoncMHO6AadE","Felipe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tcHDPb9SnQdFpwgSeRtj","Felizardo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hzEDJMFvMb8BEB6L6bUN","Flamengo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("n2r9ihnuZN7Au39NBOkW","Flores","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1cl4qfoip8YdDHfXSNcE","Forquilha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("I5nt88WIuAFyctT2IXor","Fortaleza","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5SO2TyghsohcnJc0e83O","Fortim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("g8tq2Qx7OlaD615R10mY","Frecheirinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mYTuOsaihRBi1NCWBXvJ","Gadelha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ew2sB3v61bEpDgVSkApf","Gado","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8nqgTOhbj7hvy3N3KOUv","Gado dos Rodrigues","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7YfSVLrrio3CgokazQrG","Gameleira de São Sebastião","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jG275Hy7ZGXUvz94NnDi","Garças","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qEQawS4lClyRbT7rfMpC","Gavião","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PHeDliA0MX5SFNKsySBF","Gázea","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SEP3T1oyjx0DFQr7LvD8","General Sampaio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1n4JTQ4chUPQRyrH2TFa","General Tibúrcio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TcilMV3jNEfBLAtzfbtT","Gereraú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("32yonGyVIyFpWhCMV2Dh","Giqui","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KAM2FcaaZ1ZoZix25Vkc","Girau","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("0SaoI6VLdAdZwBBd4UXd","Graça","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8TcjpYSwBecvCEohDgnP","Grande Basílio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LjfvA4IR91dreYyFcBjo","Granja","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YJ7FJ4oQnVwmgDmFWetn","Granjeiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TnC7VP7LqtSpGjJkBeLE","Groairas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SzDXDO3k594yVs2Rr01U","Guaiúba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qGHVi4o0loppchRHvCkq","Guajiru","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ziDukfPxS2HSgO8U2kTj","Guanacés","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yrMd58GY3lbyAY0PuO7x","Guaraciaba do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UH1d1ptLgLhqzl1P160b","Guaramiranga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tR5s4SZVSX8k1RECmm4S","Guararu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wuVzXWIxu3PzW1Q6Oj2D","Guassi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yuqojqhPElbBCO9QzKmP","Guassossé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("U71XWDS3fYp5vNZteIKO","Guassussê","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AMgF4QbiItBPN5aDYrSR","Guia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9gxNxUnuPkMpJnpsytKQ","Guriú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("daJxlytrsbfuIju2zheF","Hidrolândia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("0SXkwIpeuA5Z3kX8rYvh","Holanda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1XnQnyBTYNseKhVhfU2w","Horizonte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Q2FWdhUR9f62008fvwZl","Iapi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vkYbJu2CNNYu2Ha7qCa6","Iara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("sE6qsSwCeWknm2oFccSe","Ibaretama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SXiQfwGaSOLxuDbl0VAc","Ibiapaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("zFO5T7Yg1g1M3oPFPEiY","Ibiapina","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GDUIuHdkLvXX1DSFX5B8","Ibicatu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TIMHmEjBfEysoETD2D8I","Ibicuã","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("a0xTYPD2NL86bHuXIRce","Ibicuitaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Pz1fp687zLZIOrImn8Fa","Ibicuitinga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qlfk3IQlLGc6ml8oJTiX","Iborepi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KWAJSuX88TXdz1GvRCYY","Ibuaçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("q3kriRx7pHwB93KhXL9K","Ibuguaçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tZ29sVPZdDKHFoTuMytf","Icapuí","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AeMFUJ0xQy6c5ka9Hwx0","Icaraí","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HgrItDfo1HSrBI45VRw1","Icó","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rnm8ClTWropE93vH1gsz","Icozinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vzHnHEJ7iLluPFfHvr6R","Ideal","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("saDFpujCEwTv0kQ0lCjm","Igaroi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("02U5Eo6fsfGYRPRIfzQO","Iguaçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ztAa4L0tsUYESOHCrZcN","Iguatu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TInkUzwOPI43bv52v9gY","Independência","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("r8xpIrcds7Lnauak8a9b","Ingazeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YEG7tSo89pUkjnx8N4ae","Inhamuns","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Q71bNuwQjXSW7t6Bc0ZP","Inhuçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("w4vsp1GBquYj1i7KBBfj","Inhuporanga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IineSGtKZQK00WzuGxOw","Ipaguaçú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Xp87nAfAy27IqPsm8S5Z","Ipaporanga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SiGx78O79e48HcIL3QvR","Ipaumirim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bcx3uIcavIJMA57MiGDy","Ipiranga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("brr70AzgjCr3ASGzxt82","Ipu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AM6eDGlrWCHpg5vRvusE","Ipueiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fYlk7k4J4vMqtt48MWkH","Ipueiras dos Gomes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("103ltU69SBNAkH9Pqr6d","Iracema","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UCu7Ru00NaDFSIb5yz9n","Irajá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wG99Pn97eQKMQhXom4cf","Irapuã","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1OTCj5X7u4GZNJVpQdDD","Iratinga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LeUdnX5GY00SKn8K1FSe","Irauçuba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FjlX55dBQb5BKCUr4rkr","Isidoro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZFXkwvtdIn9buQ1S2LXU","Itacima","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TRLPCaY6AC9YznARYn0T","Itacolomy","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BQJS66eVMKkTUNntbjc5","Itaguá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SeRaEvWpuF1t2AEikpqk","Itaguaruna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HfvimuuwBCO3p4GxQwBZ","Itaiçaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aIb5ZYeKzvvIVQ6uEW4P","Itaipaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GiI4lOsJTD3HBpUP8Qq7","Itaitinga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GiLIyisMuiHJg8cFXU6M","Itamaracá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nnXLckJ2zEp0UQWftIEU","Itans","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("l4O0jr7gQtJofowvpHy4","Itapajé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8fhPm0HgEpENYOaKzdvu","Itapebussu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("57LwD3tSCubpz2EOB2AE","Itapeim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("awSXG35f03FKs1UQyNaX","Itapipoca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mP3tiDTu5VPmVBLfdNN0","Itapiúna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Mmo3MIFtCVXr5R3vcXfw","Itapó","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XYYOsp8Uz4eXI6SijaK3","Itarema","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mcjwfQ3vftAdNUq6B9bZ","Itatira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("F0rklGbrQNN8U7PXPmPF","Jaburuna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aArQ8MYUhyvbjlZiFUMx","Jacampari","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qUnxNIRBLVOMxX5vooWe","Jacarecoara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HbjCBjuvTDwLuZfWUM5G","Jacaúna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KGqucNWzKv1JZvZKFq6T","Jaguarão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PBhj12HD12O1Mb2yQsbk","Jaguaretama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wrvCQsfIRr0YASCJlxzG","Jaguaribara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dn7bWfjG1FOJbkgkpFkP","Jaguaribe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kQVVmD8srarxtWCTmLEm","Jaguaruana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EjXpfCDB8fZ8EPbB8kJM","Jaibaras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7dORbriLFeRCO7W6xJDf","Jamacaru","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("n3EmNLWaq4DFaM9ZjzK1","Jandrangoeira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KTOu1CfYG6QiIGEx01aA","Jardim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4jvXRGExozS3QmNftZ0p","Jardimirim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tPa9b0JM7zwHWQUhTb9x","Jati","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JqoUY8aq6OSVpSy1tAJM","Jenipapeiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tS79IScsyl3bErVsFdST","Jijoca de Jericoacoara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YgvgvfsxnJQ5M4XEmJyP","João Cordeiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("P1ZdcgknaxhglG0ok7Uj","Jordão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("zgU4J0ipU0XKPR2WWwva","José de Alencar","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("iDcBlSIrJSz9oE5Uq0PN","Juá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8MnMZD9VmOZUsjRsFaNH","Juatama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fCi7z8E1ybXkIM4ujzPh","Juazeiro de Baixo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HTFzgame8fW2Ajp40c4D","Juazeiro do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("OO8SaFFGdhUAjgngFzAD","Jubaia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MT0MbfucGvAVnbsfPd7B","Jucá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UFXyXLHMzmpKgd5xOctT","Jucás","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TmkpQUh5tZsSrxqPfn8O","Jurema","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BJCl3qbXAWHiZ5YnQE2z","Juritianha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pUHs9hp0iTJTzr423YLk","Justiniano Serpa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VcV5mllEGUEifxyHnkYu","Lacerda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AGWpYCHUfM0qIihuMAEp","Ladeira Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rKJUOhPrnZ0qbTOTCUtE","Lages","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("B3gg5oB1HZ1i2PDpQ9Ac","Lagoa da Cruz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1vGOHNfDD1GldURw2ju9","Lagoa das Pedras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("r4OIMtK9bCVBy8qIYKnO","Lagoa de São João","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ERR04muAuZN9Glktcl3q","Lagoa do Barro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7gWe5zlesNsfJMDIYmCx","Lagoa do Carneiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hDYEgLAqUJVdV2fht6t4","Lagoa do Juvenal","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HTFWwSukyTq09y9khayM","Lagoa do Mato","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tKYeYdax4TwBZHnSOYWP","Lagoa dos Crioulos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Md608uwnLntbZn4VC5VZ","Lagoa Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tOfiOIXM2anwY1CjoTcT","Lagoinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4q4wHkuzbhvmiFwxOqqL","Lambedouro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AMSDk0lpSoWDY5zyLnp6","Lameiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5TgA76m2gQEfcJYAeAig","Lapa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("STwaXJq4WBzW0PhWbwaL","Laranjeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AdaP7ztZrUkPieC1Gu4Z","Lavras da Mangabeira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hseMrWfPCjmkHk4sBTTK","Lima Campos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("78ZSDfVCDZURZUXY7hib","Limoeiro do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("05CKjcRyoZFbNtvQASON","Lisieux","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("B4Ac1pyCOws1onkLHSuQ","Livramento","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pxiEfTxl419IpcBryz5t","Logradouro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DlaW92T5pifh0JqCZSVM","Macambira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bgezZ89HT2Zr8IzJkQR7","Macaóca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VDktgwnNaXyGEY3HeAXL","Macaraú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LSfwku96qSenxscFLgDF","Maceió","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("y4nBp5L5B3iaVwbfZeNz","Madalena","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kMkkew8ocG3zuikws5NU","Major Simplício","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("a2mgAE9w8061Fq5QV6Dg","Majorlândia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("940JnBc8eRlgXIIN32wx","Malhada","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vK6OPJ9dQWlA92aBdHrO","Malhada Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9EXNOccoewcfU25cvPl7","Mangabeira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("F7YhVHpa97eyt8NLT1IV","Manibu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ImkOJHqvHNV4LmBokdOe","Manituba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aPprTkeRYvruBnuCwkiz","Manoel Correia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4CXlxozhX0YvAsLIswDi","Manoel Guedes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lbmXM5AJvLLgKdE8D06X","Mapuá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5kdQjCFtp5yrvjvXhyl6","Maracanaú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wo8E2X0YPMMBzZtPSglz","Maraguá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nPsqBP7DjmRTf2oPYSfB","Maranguape","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VLbtznMiyPalkD331fvo","Mararupá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VSncwxd3IVD5YQPc7uvq","Maratoã","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nN0JpAJGmk1qGWE6jMpe","Maravilha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5QQTUggc6bFRjzlswcfc","Marco","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GJcIEn4TEidMFtGfsQRE","Marinheiros","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("gwEn4YWp0fDnEF0BFoB1","Marrecas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pxQ544XrqkIFLHuaH9qc","Marrocos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("waGdefvlGchRF4mfjKGh","Marruás","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9NUGI28ddL4qlyY3pCdF","Martinópole","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("uOX7OeMOFNGCPKIqFLu2","Martinslândia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("oWg8FtjzbVeIweihhUYy","Massapê","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MXWSKqITzh63d3U0TACp","Mata Fresca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CMYunpU8yxc0a2bXG0lH","Matias","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XAndGiFjCT218eEqfvP2","Matriz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YIsbS44Alzyj2oUchPC8","Mauriti","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9X96n2LvwGBXF2SLKQlj","Mel","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9jhBIddR6uwIvQfd9f2b","Meruoca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZGVNf5sx07F7YDa53fgg","Messejana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1tPKpRbrAKxJtYSluwC9","Miguel Xavier","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nL2SmAm1yrE9Gz52aVjI","Milagres","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6lgA3w6t2eOQ1bqFNdGq","Milhã","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Gf4cTG9Sf8ampV8fxgal","Milton Belo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rteLFRq9rlaN0bW7cf4T","Mineirolândia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("laqbrnhTEgQgDsDn3c4x","Miragem","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CGG77tk77Z8ShwjCJuD8","Miraíma","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("58Icu7hhGYBV7TjWJVD6","Mirambé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ctHaQKsoplWITp1WyAlj","Miranda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("uy9pkxaT6QBzty0VdmCe","Missão Nova","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EqDKYy3YVV8Jgj02SXgN","Missão Velha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("NgUoyoUUZU70GQapkrDA","Missi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7q8gr36Id4XynH9pZQp0","Mocambo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("0gzAw03WClj8f0ZdukBx","Moitas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("gXRHTnGDqTYtjwf029gd","Mombaça","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fxnKe3AjizUiDytBBA1Q","Mondubim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4wysMsVKBg6DmtGhGy2V","Monguba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AwcPDgkm22WQ9CFOGTB3","Monsenhor Tabosa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("G2ghyCrmMi17VzkSX8un","Monte Alegre","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ECD1ilwE7rGA5sz3ZHkF","Monte Alverne","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ikCsE0PdDRLdHeqg90NO","Monte Castelo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ISZKeITqTY9X8rkVKxdc","Monte Grave","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PExIoq0z9CgHEpyVV1cX","Monte Sion","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("H9n7YdP0RWemnJcDLSNk","Montenebo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IQDmStJ1ky4RsSGgB7F9","Morada Nova","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EKxYtb8rYGRmA98LMUfa","Moraújo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LLPWH3xQZ2lxd72cfvQ5","Morrinhos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MltFHL3hAnkHefxGARO1","Morrinhos Novos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vXYYVFR810NZQnbvxXvC","Morro Branco","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BoQnWRvemGhX3xG6oUCq","Mosquito","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("sLCnri9cUG6LKcjxgotS","Mucambo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3ARHff61PuyYfQRv4q2h","Mulungu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cLRp5DvjgtW8cLBZLXXD","Mumbaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aAgFucIsfPP1NpfIkIc5","Mundau","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lxfGjbtLwib4m48SkQdU","Mundaú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("meXYpaw6sCaZiNYi7zxe","Munguba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UzWcJyrUvbXNWbZgXZT2","Muribeca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IvHqbPPItPS0cEpHC6lz","Muriti","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cSLoVpD5mhF03lra7oR0","Mutambeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("A92sSpfR2KexT3ACdpvN","Naraniu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("chEe7PWlK9tizpdc2nsO","Nascente","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6y1Srd6gDiZFU8Kx1Yey","Nenenlândia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("i2SuhF6rHC7S53Tn6vp9","Nossa Senhora do Livramento","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tHpHlZik3smDV08EnSgI","Nova Betânia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("L5eQWbWz2epbOG6b5BLL","Nova Fátima","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("imAugNDSEsJcbdPyeOmJ","Nova Floresta","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VxyodI6u90dnQM011sWS","Nova Olinda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5XnH68USncqZ5z8NvtvE","Nova Russas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("h51VYxnpnp0smXhFUt5v","Nova Santa Cruz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("eFUhsPUza0wTp19Vx7lP","Nova Veneza","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("eUhceORTMyyCZ0GDYFGB","Nova Vida","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EtuOLSvoSJcy14nd1nhN","Novo Assis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("N51NzVpjNIPE2L7Jntbf","Novo Horizonte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2ia6eJCRcCCFbCSD5SWY","Novo Oriente","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("P3ygN1li7kRt8ufNyG2C","Núcleo Colonial Pio XII","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("detUSBR909V7wS7kKvFq","Ocara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("NJ7zFfn5PZxHtoUdGH72","Oiticica","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qUKcwodZs3hjhEcPsepd","Olho D'Água","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FaAdwzBf7eoh2mybUSkL","Olho D'água do Bezerril","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bhRLlrzXw9BmsaISzAtZ","Olho-D'Água","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("NfzwHFVcqzu9NzuS3xVq","Olho-D'Água da Bica","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FovRTLthsTuckJNRIGzn","Oliveiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("z2dqXW5RtgqxNFESoi3z","Orós","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wTXbTLcRmKxTpYHQk6mH","Pacajus","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LHYX9mm1o9K7wiarhYIw","Pacatuba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CwQwDWCelv7XYbUPt3Z6","Pacoti","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DpyKhEjYcgOe1qO89aE7","Pacujá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Wp51GHWDRmu5kXV0oSaA","Padre Cícero","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hg5neXV8Mp7VGREfcGZS","Padre Linhares","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JIW1VdOkQutl0P1OariI","Padre Vieira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dKDJE9LbIeMMCFBj4YHg","Pai João","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kHDHHg1Ok1vaOGdixuWO","Pajeú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jYtOm93STBBRYMnRPw8g","Palestina","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dqNbjMJ2PrjPfzVJr7vk","Palestina do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8zHieN0vU12EiyYF0E8I","Palhano","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("j3NF3OcZiJsXdDlNT8s5","Palmácia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FqBjymAe7xuFflvO8oHC","Palmatória","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4e6PIOA99cEw6umA71Ep","Panacuí","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("QOufidd4Yh0EwGvRrFh3","Papara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2HyYdoopM7zgFsb1x6P5","Paracuá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HUqPF9yyikG2rxqqgdrG","Paracuru","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1Upj7mPQZCoz3eKUIlrt","Paraipaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MeDkwGLulP4g59G9LEX1","Paraiso","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3XyBsm024NeyKABAGuIU","Parajuru","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GFYT2XfWpdXRFqoL01nY","Parambu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Ip2jY0DjYDZ0haHxheIs","Paramoti","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aig8cvKxnGb0NmGM3r55","Parangaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JU404RP9zHyay4CEwhmw","Parapuí","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("I3879Yg0nnFBnFGu6Dr4","Parazinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1izGS6oYypJMgLvqHHCF","Paripueira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LSgQqG38XrY64Mns429N","Pascoal","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LlDcLNDIpcGzZ8DqdNfl","Passagem","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SgcKZzneXpFqipr8W6TJ","Passagem Funda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("M9bXuT2IhePWZGkWNiyB","Pasta","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hy7W18C0LFjPsn0nm6k7","Patacas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MKMzV42zvqqJKwDT3Ok3","Patos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("j41waEB3h3CDYTeW4NCm","Patos dos Liberatos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YNhMSy9P3THbwyVFiW2p","Patriarca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VzElOpnQlVC1j7aBXTET","Paus Branco","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kx7s9IpkoJ8wA5CshuqJ","Paus Brancos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("plEbbtl8BwB68U12Adlj","Pavuna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1OGzey1CSyRCgWOrSxML","Pecém","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("QZrP94bxpi2X7tU3jFSe","Pedra Branca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FTKlHxMaBoilkNwfgxOU","Pedra de Fogo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EAuNezyePwjXd2UCTzgM","Pedra e Cal","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yyGMXXiWYuTaPjeB9xeu","Pedras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WgF2ONEE6takuJiGbvyz","Pedras Brancas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CnthASFSHmL94kvlxMwb","Pedrinhas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("i419rRc4cUdJjGBJN8J7","Peixe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aI2eQlRME9s5WW5V8Htq","Peixe Gordo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3nym9SIgCr696kNYOQ53","Penaforte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CadmzW5FQ6Bcof75mF6a","Penedo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("x4fN4uGOFtelUOjn7nqk","Pentecoste","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kW6POhQxngVMm3J5oW0U","Pereiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fxjQn3fGiGIeSxvfxy82","Pernambuquinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7tOm2WueKYGqJ4MaexEz","Pessoa Anta","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("uopUOFVSalaFLEekTin2","Pindoguaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jacKZ6oeGeAHM7mdrO0v","Pindoretama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZO4LxHRBCuPWVtwy45el","Pio X","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("UCN8cAMHwloKzyCwaDPz","Piquet Carneiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("N0QvTxWjxVKKVc74hs3p","Pirabibu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pS4pPInhjkCTXilFlSlG","Pirangi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CVkiYYx39eUI2faORjGz","Pires Ferreira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LHfJo06xVquCr3NLesb6","Pitombeira","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("hdYvweRbvITuuYrPxt5U","Pitombeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("AFzloYKG8Wf0PBzM6lll","Plácido Martins","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bXLNaRK9zIGH8s2B1f7V","Planalto","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BQAgF9ZMzb8XZrrxKN6d","Poço","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("U1VSfDgwwSVpMXpoHyLU","Poço Comprido","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TmXBNJZeasSy86MawCdz","Poço da Onça","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VuOL1zTsHtaOTMXLZ4dB","Poço Doce","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4g1zH0qGgNZHKmYBbO1U","Poço Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xt0bn5O9yRcfQ5fmzNr2","Poço Verde","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yCLVRRBN68NRNoWQuXs3","Ponta da Serra","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fKRbSdqgAjebRzMNJQjt","Poranga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8vHkP97DmbUCcU8vTKiG","Porfirio Sampaio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("APIkfEwjD4aPCLvM9rZV","Porteiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("oBOyYqIodyYHJVVT1iFJ","Potengi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9Q9esdJ7DD6px7FdA3MZ","Poti","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cAF77QcxjdCgsa5BoVoF","Potiretama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JM1BcRHq8qSodMrCF4WN","Prata","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MdnEaJ9Fjz24Xy1Gyj6L","Pratiús","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VhoAFWATCexxP5NjhgpK","Prefeita Suely Pinheiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Uf8KsocR0nXVBLPArwWC","Prudente de Morais","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("yLveZzb0NYnJodScS8ZK","Quatiguaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xYayONcWrggj0RJ3yBwr","Queimados","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1sENMuKTI4m8UI8QS6td","Quimami","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("W1jaYJM4nN7QVQjyDsbn","Quincoé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RuniEpkCVzZedh9Zzvoi","Quincuncá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("PDHTS36Dsf7WTQUQ8MYw","Quitaiús","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dnWdV8v1j5oifFdTKq5t","Quiterianópolis","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jrts3v4H74iOk93DLEpH","Quixadá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BR47Q72JF1bpn6GtIJ0a","Quixariú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dTSGyXXPQNlFx9K3hQNu","Quixelô","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1nxR6CjSAHnIFWPcpGY0","Quixeramobim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("k64BRumvfwMYnYj3RovT","Quixeré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5yM6ZNa9pPa4vjINXAiI","Rafael Arruda","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XHI1ThePQg9s79zGq0ja","Raimundo Martins","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("0q4qvkaVfeY6EHbNWExc","Ramadinha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EotcmdTw2P8feWD7M7ZI","Realejo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5dX6fehh4EmYbg37CImh","Recanto","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Wlv2DEDdpS6NP6AJH9DW","Redenção","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("D2BrRkRVlZ54I8vzED59","Repartição","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RAECN8IJzQEp7K3kXzLb","Reriutaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("V1DU0wxSN8vcV5C4oTpN","Retiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CzsG5xn4BPxpcqaIzFPq","Riachão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vUooVbba6U32KA9fFShC","Riacho Grande","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vwZNvJI6WndvrsF68uUd","Riacho Verde","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WkpuezugakCRkEcYM48E","Riacho Vermelho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CbQvZYyvemqPGZ7AO3zt","Rinaré","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("D4uzvjioOOLN4ZRDKhV9","Roldão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MjqaCuSL9ap1EEOMzYFz","Rosário","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jLJeDZUdF2B3OOYUV71m","Russas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("f46VnLjlZ1C4W3TS8Vx7","Sabiaguaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wKbcLPEsvJ6HnPSKgYtZ","Saboeiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BaRB5Zc2Fp96dyo6XWM8","Sacramento","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("raoF4Pq69MxnqhCAEzWs","Salão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Y3UAMgeiGLFKEZdjB5iT","Salgado dos Machados","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Autuww3Sx6PNMxsRDFJF","Salgado dos Mendes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("By2zqtY7A7jbB3TIc4CF","Salitre","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("pY40mKoQe8gJvWa71Kx5","Sambaíba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("dtMH2GeGZPxJWJGBtmnF","Santa Ana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9SgN1feKPd1UV95uT3rp","Santa Cruz do Banabuiú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("F8rwLWhpDvJengvwuZ5P","Santa Fé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("2l1wpvS1jfDfXooVnvCl","Santa Felícia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("zc6G5eF91S5MeFrnDLf0","Santa Luzia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("198Bx4uCyVcfsnFdrV6i","Santa Quitéria","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("N8ZXLmqRHDD1lVEdBJHL","Santa Rita","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JwZoHxKVOeM54ElvNsaQ","Santa Rosa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("m0mKkUeE2La5sxRTJaPt","Santa Tereza","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Psvu4abKEqveXWKgBEDj","Santana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("tjWK7XpA5CBRcSAAE7cI","Santana do Acaraú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5pI7JZTFkjXOfR5AGKKK","Santana do Cariri","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("r7tTuEzBQwXPI4sLIq7Z","Santarém","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EApj3PkurbowZyRR5xJL","Santo André","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("xwMWGEKxhT8vHeIySURy","Santo Antônio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XV8qy5F4XNxn1q5FfEIz","Santo Antônio da Pindoba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("suNt5ZdWv6KkCrAfLJAe","Santo Antônio dos Fernandes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wmRndAzckjIJON8JYkHw","São Bartolomeu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7eWTtMDQo2bRM8oHNBew","São Benedito","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rNqyzsFF0E2W7ChpLB0y","São Bernardo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BM9sBfXhahQRUhMV8X3a","São Domingos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1M49E4KQErx5LeZzVASA","São Felipe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jXSdGWi8iY9VnvFNl40G","São Francisco","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("72qHDEcqGfd7rJZLTUZy","São Gonçalo do Amarante","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8WfXwwWHWvXCr14COGoi","São Gonçalo do Umari","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("oxZBNKT5Ye9IhVRqOJvm","São João","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("exn06Lux64Flb9tKqBcZ","São João de Deus","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3DrZK9jX7PRc1jQa4Omw","São João do Amanari","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4UCDdJhN5cqKkqQWcouV","São João do Jaguaribe","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("f9emorfxvZNVZWC1cOZ6","São João dos Queiroz","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bXKU9QsJ8eZUk8FhvxgD","São Joaquim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("VqVFOKE9kig4lmRj0qvE","São Joaquim do Salgado","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1igEXX1sLenLvrF99FpB","São José","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("y1rYmlvKMDK294BCsh6G","São José das Lontras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Roon0HU6JJQowF56NzrL","São José de Solonópole","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RlUa8iPESebvGf3J8h6b","São José do Lagamar","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Um9IlSIyoc70QdLjJwQs","São José do Torto","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jLAhlPs7at3mp3K3Ej8Y","São Luís do Curu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EKRIx26IEyeSuhPxrOsf","São Miguel","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("LbUEJlyEVMqCzpARyLOf","São Paulinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("HLd2XO5Ob2xcfZkfJ0SI","São Pedro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("votSIaWl0ffgzdPzKoj7","São Pedro do Gavião","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CJ78dGDA49ueru9oBpUi","São Pedro do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XIGC2qMTT2oVpkR2ld46","São Raimundo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KOm9bpR393IomdHlNuEe","São Romão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EakQpFGamk6xr16qngw2","São Roque","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("glSyWz6Rj7LbxDdAHCBW","São Sebastião","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6X9YQR7eNPbnWmTpJlTw","São Tomé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Rq57Yov2xildS4rMJ8a0","São Vicente","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FNnhEh8B2iGXgbi273WO","Sapo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("umBdeGt2Oz7WVZjIvoPq","Sapupara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("SUvNhq0pE3GOOknS8yOK","Saquinho","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("uTaoTG6FIKoEFEjxrHiL","Sebastião de Abreu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("TJS2CpIyYaEpZxI289lp","Senador Carlos Jereissati","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("k5aXDJJPVCcnE42DQh62","Senador Pompeu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ay6OaAQyHGGOgVHaiWJ0","Senador Sá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("W1KB83V6nJHsQplJeiEV","Sereno de Cima","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("QGfbBx7CM4LPrfxtU7iy","Serra do Félix","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("FdKEYbj7QOGX4AAfTTfa","Serragem","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("61qurwGVgjX5Ki5JLdSD","Serrota","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("S2Sqo7032qcsDmNYKsn4","Serrote","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JN4WHfChf03xoCVrAyyS","Serrote do Meio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lzQiBpjcN5MG5QqAcwUA","Simão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("fKtwBesWdBfM40L8taiL","Sitiá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GHmP49et9bOPPgMHcTzE","Sítio Alegre","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("lbvHSzQR6PWRwLt69LLa","Sítios Novos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5locTBNMm1EbmO8KFrZW","Siupê","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("OwmiNxPd0nHUJ7Ozmaic","Sobral","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qV4Xawm0O8iqmOBSgdZQ","Soledade","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YZaXHTz142cejM95rnhO","Solidão","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bG7zQB1BHHYhR8Bawieu","Solonópole","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("mIiJIR9RFr1jT7w7ce9W","Suassurana","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aLOjF7h8mYredMWRjnsj","Sucatinga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aJB559Nm46VMg5trw70l","Sucesso","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("gQ27NfGBiGGLarthYeab","Sussuanha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("QjpHnw2Ei5gkTog6OMDI","Tabainha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4t7d9qaQrU9Gw4JkVoBe","Taboleiro","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9fDu6HTyYY6i1oBCPZ7W","Tabuleiro do Norte","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rC0liLVXr3BawExMnq3g","Taíba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("nKRKyLwdAWMtbQHXcAXb","Tamboril","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("K9sZdpsN7TvArqr9rDUz","Tangente","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("KoAYWeAq8KCnOUYvFn7T","Tanques","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("JUo64J2FD6JVdRjPJZ8U","Tapera","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ykTGBv4amDNMqOSAwo1J","Taperuaba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ST7u6poaPN5HAexJoidH","Tapuiara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("YHw5mbRT1ArG9TZXJGCj","Tapuio","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DpV6G0ocVvZ4UQkPOFnm","Targinos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Wam8XK3VtYoyBRzk4oM1","Tarrafas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aWG321ptCKXa2VeoleHg","Tauá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CQPz47c0A4SjKTRATDzV","Tejuçuoca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Peu6Px6ngMAC5QnccBaC","Tianguá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("BOIwX1mnaN4s8HgEKFb0","Timbaúba dos Marinheiros","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9SHMWPOVKghDzFF0skRx","Timonha","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("RNl5RdxM8KP5tOc43OeW","Tipi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("G2NQFzupJk5O3gq4SBM2","Tomé","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("XFfg7M30WIgvBGJ7JPBE","Trairi","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("8j3OxIIUYnSWQH4wM68r","Trapiá","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ZwmU4MYaEEryY5bKNFAS","Triângulo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("9fVMREeREiKbwe5QI0Ss","Trici","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ynmAt7d7tPSVfsji4fN3","Triunfo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Spo21d41ftx6F9tKdzQ9","Tróia","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6WFPRRkbztwEo7mjWWRP","Trussu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("19alxveL3rgV5LKMVKV9","Tucunduba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("CtqB7k2eDoadZCDyknWo","Tucuns","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EttK4cr1GWRZXM9pTMHP","Tuína","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("qkgIuEyAoqUp1RcTFick","Tururu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("GN07eVUFJBejHW4CkXJu","Ubajara","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1505rrQSU6Gzorc9VoSx","Ubaúna","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("jG5gPZMYLdGUFYzfOqbj","Ubiraçu","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("wkuQQ9sVWmbyoFaQmi9b","Uiraponga","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WcLEsvjBm4TGD3CbTDET","Umari","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("1SVJw0ZElU16YvQRvtSI","Umarituba","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("4Zd5ytUYYIoAE6heKnHI","Umarizeiras","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("IcHqYEShhQZn2RlX1AD3","Umburanas","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("u7q10eU2TYr4KE8nk1mV","Umirim","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cJLCKw6NDXumkPAyZvg8","União","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("kNpmxXYBDS3bTjhYpVrb","Uruburetama","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("cP3lVLKxOHOJ4N3vz7IL","Uruoca","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("bHWrVC1yRcGzCKdO6Hqg","Uruquê","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("zXIHegArQi0U9bMAObVY","Varjota","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("7l1ZVgdLyOu1hSZUbYWM","Várzea","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("EcKFti5MlL7bIQAbNRze","Várzea Alegre","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("MsQXWYmI59VB5Z334E4L","Várzea da Onça","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("aj5QVxwcEntbBRUYrSfw","Várzea da Volta","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("vtSaTEAMZtBdNebkPSt2","Várzea do Gilo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("WGCI6zqdTSqihpyBW7EZ","Várzea dos Espinhos","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("rLQWy3QFFkLXrvDcPHFQ","Vazantes","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("6oUkwTlFYPRAnfqvH9ki","Vazente do Curú","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("DFqSDEsjtnhtaEsNyVji","Velame","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("5h7AsxPtWCMujlEVkouT","Ventura","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("ahMnLqaGINzWb1lsVRsf","Vertentes do Lagedo","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("b7nLRRNroxgtjrR2ZZFY","Viçosa","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("i7uesoe2ZrBckXZwzepE","Viçosa do Ceará","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Znws67zeg5R3jgsY2uzG","Video","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("3NIVNg24scpeceCmyQO3","Vila Soares","19LMXJKf2gQhrwvFKpCG", "CE"));
        lista.add(new Cidade("Y1DovEP22VU0CcqfM3j1","Vista Alegre","19LMXJKf2gQhrwvFKpCG", "CE"));
        return lista;
    }
}
