package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class ES {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Acioli", "ES"));
        lista.add(new Cidade("", "Afonso Cláudio", "ES"));
        lista.add(new Cidade("", "Aghá", "ES"));
        lista.add(new Cidade("", "Água Doce do Norte", "ES"));
        lista.add(new Cidade("", "Águia Branca", "ES"));
        lista.add(new Cidade("", "Airituba", "ES"));
        lista.add(new Cidade("", "Alegre", "ES"));
        lista.add(new Cidade("", "Alfredo Chaves", "ES"));
        lista.add(new Cidade("", "Alto Calçado ", "ES"));
        lista.add(new Cidade("", "Alto Caldeirão", "ES"));
        lista.add(new Cidade("", "Alto Castelinho", "ES"));
        lista.add(new Cidade("", "Alto Mutum Preto", "ES"));
        lista.add(new Cidade("", "Alto Norte", "ES"));
        lista.add(new Cidade("", "Alto Rio Novo", "ES"));
        lista.add(new Cidade("", "Alto Santa Maria", "ES"));
        lista.add(new Cidade("", "Anchieta", "ES"));
        lista.add(new Cidade("", "Ângelo Frechiani", "ES"));
        lista.add(new Cidade("", "Anutiba", "ES"));
        lista.add(new Cidade("", "Apiacá", "ES"));
        lista.add(new Cidade("", "Araçatiba", "ES"));
        lista.add(new Cidade("", "Aracê ", "ES"));
        lista.add(new Cidade("", "Aracruz", "ES"));
        lista.add(new Cidade("", "Aracui", "ES"));
        lista.add(new Cidade("", "Araguaia", "ES"));
        lista.add(new Cidade("", "Araraí ", "ES"));
        lista.add(new Cidade("", "Argolas", "ES"));
        lista.add(new Cidade("", "Atílio Vivácqua", "ES"));
        lista.add(new Cidade("", "Baía Nova", "ES"));
        lista.add(new Cidade("", "Baixo Guandu", "ES"));
        lista.add(new Cidade("", "Barra de Novo Brasil", "ES"));
        lista.add(new Cidade("", "Barra de São Francisco", "ES"));
        lista.add(new Cidade("", "Barra do Riacho", "ES"));
        lista.add(new Cidade("", "Barra do Sahy", "ES"));
        lista.add(new Cidade("", "Barra Nova", "ES"));
        lista.add(new Cidade("", "Barra Seca", "ES"));
        lista.add(new Cidade("", "Baunilha", "ES"));
        lista.add(new Cidade("", "Bebedouro", "ES"));
        lista.add(new Cidade("", "Boa Esperança", "ES"));
        lista.add(new Cidade("", "Boapaba", "ES"));
        lista.add(new Cidade("", "Bom Jesus do Norte", "ES"));
        lista.add(new Cidade("", "Bonsucesso", "ES"));
        lista.add(new Cidade("", "Braço do Rio", "ES"));
        lista.add(new Cidade("", "Brejetuba", "ES"));
        lista.add(new Cidade("", "Burarama ", "ES"));
        lista.add(new Cidade("", "Cachoeirinha de Itaúna", "ES"));
        lista.add(new Cidade("", "Cachoeiro de Itapemirim", "ES"));
        lista.add(new Cidade("", "Café", "ES"));
        lista.add(new Cidade("", "Calogi", "ES"));
        lista.add(new Cidade("", "Câmara ", "ES"));
        lista.add(new Cidade("", "Carapina", "ES"));
        lista.add(new Cidade("", "Cariacica", "ES"));
        lista.add(new Cidade("", "Castelo", "ES"));
        lista.add(new Cidade("", "Celina ", "ES"));
        lista.add(new Cidade("", "Colatina", "ES"));
        lista.add(new Cidade("", "Conceição da Barra", "ES"));
        lista.add(new Cidade("", "Conceição do Castelo", "ES"));
        lista.add(new Cidade("", "Conceição do Muqui", "ES"));
        lista.add(new Cidade("", "Conduru ", "ES"));
        lista.add(new Cidade("", "Córrego dos Monos ", "ES"));
        lista.add(new Cidade("", "Córrego Moacyr Ávidos", "ES"));
        lista.add(new Cidade("", "Cotaxé", "ES"));
        lista.add(new Cidade("", "Coutinho ", "ES"));
        lista.add(new Cidade("", "Cristal do Norte", "ES"));
        lista.add(new Cidade("", "Crubixá", "ES"));
        lista.add(new Cidade("", "Desengano", "ES"));
        lista.add(new Cidade("", "Divino de São Lourenço", "ES"));
        lista.add(new Cidade("", "Divino Espírito Santo", "ES"));
        lista.add(new Cidade("", "Djalma Coutinho", "ES"));
        lista.add(new Cidade("", "Domingos Martins", "ES"));
        lista.add(new Cidade("", "Dona América", "ES"));
        lista.add(new Cidade("", "Dores do Rio Preto", "ES"));
        lista.add(new Cidade("", "Duas Barras", "ES"));
        lista.add(new Cidade("", "Ecoporanga", "ES"));
        lista.add(new Cidade("", "Estrela do Norte", "ES"));
        lista.add(new Cidade("", "Farias", "ES"));
        lista.add(new Cidade("", "Fartura", "ES"));
        lista.add(new Cidade("", "Fazenda Guandu ", "ES"));
        lista.add(new Cidade("", "Fundão", "ES"));
        lista.add(new Cidade("", "Garrafão", "ES"));
        lista.add(new Cidade("", "Gironda", "ES"));
        lista.add(new Cidade("", "Goiabeiras", "ES"));
        lista.add(new Cidade("", "Governador Lacerda de Aguiar", "ES"));
        lista.add(new Cidade("", "Governador Lindenberg", "ES"));
        lista.add(new Cidade("", "Graça Aranha", "ES"));
        lista.add(new Cidade("", "Gruta ", "ES"));
        lista.add(new Cidade("", "Guaçuí", "ES"));
        lista.add(new Cidade("", "Guarapari", "ES"));
        lista.add(new Cidade("", "Guararema", "ES"));
        lista.add(new Cidade("", "Ibatiba", "ES"));
        lista.add(new Cidade("", "Ibicaba", "ES"));
        lista.add(new Cidade("", "Ibiraçu", "ES"));
        lista.add(new Cidade("", "Ibitirama", "ES"));
        lista.add(new Cidade("", "Ibitiruí", "ES"));
        lista.add(new Cidade("", "Ibituba", "ES"));
        lista.add(new Cidade("", "Iconha", "ES"));
        lista.add(new Cidade("", "Imburana", "ES"));
        lista.add(new Cidade("", "Iriritiba", "ES"));
        lista.add(new Cidade("", "Irundi", "ES"));
        lista.add(new Cidade("", "Irupi", "ES"));
        lista.add(new Cidade("", "Isabel ", "ES"));
        lista.add(new Cidade("", "Itabaiana", "ES"));
        lista.add(new Cidade("", "Itaçu", "ES"));
        lista.add(new Cidade("", "Itaguaçu", "ES"));
        lista.add(new Cidade("", "Itaicí ", "ES"));
        lista.add(new Cidade("", "Itaimbé", "ES"));
        lista.add(new Cidade("", "Itaipava ", "ES"));
        lista.add(new Cidade("", "Itamira", "ES"));
        lista.add(new Cidade("", "Itaóca ", "ES"));
        lista.add(new Cidade("", "Itapecoá", "ES"));
        lista.add(new Cidade("", "Itapemirim", "ES"));
        lista.add(new Cidade("", "Itaperuna", "ES"));
        lista.add(new Cidade("", "Itapina", "ES"));
        lista.add(new Cidade("", "Itaquari", "ES"));
        lista.add(new Cidade("", "Itarana", "ES"));
        lista.add(new Cidade("", "Itaúnas", "ES"));
        lista.add(new Cidade("", "Itauninhas", "ES"));
        lista.add(new Cidade("", "Iúna", "ES"));
        lista.add(new Cidade("", "Jabaquara", "ES"));
        lista.add(new Cidade("", "Jacaraipe", "ES"));
        lista.add(new Cidade("", "Jaciguá ", "ES"));
        lista.add(new Cidade("", "Jacupemba", "ES"));
        lista.add(new Cidade("", "Jaguaré", "ES"));
        lista.add(new Cidade("", "Jerônimo Monteiro", "ES"));
        lista.add(new Cidade("", "Joaçuba", "ES"));
        lista.add(new Cidade("", "João Neiva", "ES"));
        lista.add(new Cidade("", "Joatuba ", "ES"));
        lista.add(new Cidade("", "José Carlos", "ES"));
        lista.add(new Cidade("", "Jurama", "ES"));
        lista.add(new Cidade("", "Lajinha", "ES"));
        lista.add(new Cidade("", "Laranja da Terra", "ES"));
        lista.add(new Cidade("", "Limoeiro", "ES"));
        lista.add(new Cidade("", "Linhares", "ES"));
        lista.add(new Cidade("", "Mangaraí", "ES"));
        lista.add(new Cidade("", "Mantenópolis", "ES"));
        lista.add(new Cidade("", "Marataízes", "ES"));
        lista.add(new Cidade("", "Marechal Floriano", "ES"));
        lista.add(new Cidade("", "Marilândia", "ES"));
        lista.add(new Cidade("", "Matilde", "ES"));
        lista.add(new Cidade("", "Melgaço", "ES"));
        lista.add(new Cidade("", "Menino Jesus", "ES"));
        lista.add(new Cidade("", "Mimoso do Sul", "ES"));
        lista.add(new Cidade("", "Montanha", "ES"));
        lista.add(new Cidade("", "Monte Carmelo do Rio Novo", "ES"));
        lista.add(new Cidade("", "Monte Pio", "ES"));
        lista.add(new Cidade("", "Monte Sinai", "ES"));
        lista.add(new Cidade("", "Morello", "ES"));
        lista.add(new Cidade("", "Morro Grande", "ES"));
        lista.add(new Cidade("", "Mucurici", "ES"));
        lista.add(new Cidade("", "Mundo Novo", "ES"));
        lista.add(new Cidade("", "Muniz Freire", "ES"));
        lista.add(new Cidade("", "Muqui", "ES"));
        lista.add(new Cidade("", "Nestor Gomes", "ES"));
        lista.add(new Cidade("", "Nossa Senhora das Graças", "ES"));
        lista.add(new Cidade("", "Nossa Senhora de Fátima", "ES"));
        lista.add(new Cidade("", "Nova Almeida", "ES"));
        lista.add(new Cidade("", "Nova Venécia", "ES"));
        lista.add(new Cidade("", "Nova Verona", "ES"));
        lista.add(new Cidade("", "Novo Brasil", "ES"));
        lista.add(new Cidade("", "Novo Horizonte", "ES"));
        lista.add(new Cidade("", "Pacotuba ", "ES"));
        lista.add(new Cidade("", "Paineiras", "ES"));
        lista.add(new Cidade("", "Palmeira", "ES"));
        lista.add(new Cidade("", "Palmerino", "ES"));
        lista.add(new Cidade("", "Pancas", "ES"));
        lista.add(new Cidade("", "Paraju ", "ES"));
        lista.add(new Cidade("", "Paulista", "ES"));
        lista.add(new Cidade("", "Pedro Canário", "ES"));
        lista.add(new Cidade("", "Pendanga", "ES"));
        lista.add(new Cidade("", "Pequiá", "ES"));
        lista.add(new Cidade("", "Piaçu ", "ES"));
        lista.add(new Cidade("", "Pinheiros", "ES"));
        lista.add(new Cidade("", "Piracema", "ES"));
        lista.add(new Cidade("", "Piúma", "ES"));
        lista.add(new Cidade("", "Pontal do Ipiranga", "ES"));
        lista.add(new Cidade("", "Ponte de Itabapoana", "ES"));
        lista.add(new Cidade("", "Ponto Belo", "ES"));
        lista.add(new Cidade("", "Pontões", "ES"));
        lista.add(new Cidade("", "Porangá", "ES"));
        lista.add(new Cidade("", "Povoação", "ES"));
        lista.add(new Cidade("", "Praia do Coqueiral", "ES"));
        lista.add(new Cidade("", "Praia Grande", "ES"));
        lista.add(new Cidade("", "Presidente Kennedy", "ES"));
        lista.add(new Cidade("", "Princesa", "ES"));
        lista.add(new Cidade("", "Prosperidade", "ES"));
        lista.add(new Cidade("", "Queimado", "ES"));
        lista.add(new Cidade("", "Quilômetro 14 do Mutum", "ES"));
        lista.add(new Cidade("", "Regência", "ES"));
        lista.add(new Cidade("", "Riacho", "ES"));
        lista.add(new Cidade("", "Ribeirão do Cristo", "ES"));
        lista.add(new Cidade("", "Rio Bananal", "ES"));
        lista.add(new Cidade("", "Rio Calçado", "ES"));
        lista.add(new Cidade("", "Rio Muqui", "ES"));
        lista.add(new Cidade("", "Rio Novo do Sul", "ES"));
        lista.add(new Cidade("", "Rio Preto", "ES"));
        lista.add(new Cidade("", "Rio Quartel", "ES"));
        lista.add(new Cidade("", "Rive ", "ES"));
        lista.add(new Cidade("", "Sagrada Família", "ES"));
        lista.add(new Cidade("", "Santa Angélica", "ES"));
        lista.add(new Cidade("", "Santa Cruz", "ES"));
        lista.add(new Cidade("", "Santa Cruz de Irupi", "ES"));
        lista.add(new Cidade("", "Santa Júlia", "ES"));
        lista.add(new Cidade("", "Santa Leopoldina", "ES"));
        lista.add(new Cidade("", "Santa Luzia de Mantenópolis", "ES"));
        lista.add(new Cidade("", "Santa Luzia do Azul", "ES"));
        lista.add(new Cidade("", "Santa Luzia do Norte", "ES"));
        lista.add(new Cidade("", "Santa Maria de Jetibá", "ES"));
        lista.add(new Cidade("", "Santa Maria de Marechal", "ES"));
        lista.add(new Cidade("", "Santa Marta ", "ES"));
        lista.add(new Cidade("", "Santa Teresa", "ES"));
        lista.add(new Cidade("", "Santa Terezinha", "ES"));
        lista.add(new Cidade("", "Santíssima Trindade", "ES"));
        lista.add(new Cidade("", "Santo Agostinho", "ES"));
        lista.add(new Cidade("", "Santo Antônio", "ES"));
        lista.add(new Cidade("", "Santo Antônio do Canaã", "ES"));
        lista.add(new Cidade("", "Santo Antônio do Muqui", "ES"));
        lista.add(new Cidade("", "Santo Antônio do Pousalegre", "ES"));
        lista.add(new Cidade("", "Santo Antônio do Quinze", "ES"));
        lista.add(new Cidade("", "São Domingos do Norte", "ES"));
        lista.add(new Cidade("", "São Francisco", "ES"));
        lista.add(new Cidade("", "São Francisco Xavier do Guandu", "ES"));
        lista.add(new Cidade("", "São Gabriel da Palha", "ES"));
        lista.add(new Cidade("", "São Geraldo", "ES"));
        lista.add(new Cidade("", "São Jacinto", "ES"));
        lista.add(new Cidade("", "São João de Petrópolis", "ES"));
        lista.add(new Cidade("", "São João de Viçosa", "ES"));
        lista.add(new Cidade("", "São João do Norte", "ES"));
        lista.add(new Cidade("", "São João do Príncipe", "ES"));
        lista.add(new Cidade("", "São João do Sobrado", "ES"));
        lista.add(new Cidade("", "São Jorge da Barra Seca", "ES"));
        lista.add(new Cidade("", "São Jorge do Oliveira", "ES"));
        lista.add(new Cidade("", "São Jorge do Tiradentes", "ES"));
        lista.add(new Cidade("", "São José das Torres", "ES"));
        lista.add(new Cidade("", "São José de Fruteiras", "ES"));
        lista.add(new Cidade("", "São José de Mantenópolis", "ES"));
        lista.add(new Cidade("", "São José do Calçado", "ES"));
        lista.add(new Cidade("", "São José do Sobradinho", "ES"));
        lista.add(new Cidade("", "São Mateus", "ES"));
        lista.add(new Cidade("", "São Miguel do Caparaó", "ES"));
        lista.add(new Cidade("", "São Pedro", "ES"));
        lista.add(new Cidade("", "São Pedro de Itabapoana", "ES"));
        lista.add(new Cidade("", "São Pedro de Rates ", "ES"));
        lista.add(new Cidade("", "São Rafael", "ES"));
        lista.add(new Cidade("", "São Raimundo da Pedra Menina", "ES"));
        lista.add(new Cidade("", "São Roque do Canaã", "ES"));
        lista.add(new Cidade("", "São Tiago", "ES"));
        lista.add(new Cidade("", "São Vicente", "ES"));
        lista.add(new Cidade("", "Sapucaia", "ES"));
        lista.add(new Cidade("", "Serra", "ES"));
        lista.add(new Cidade("", "Serra Pelada", "ES"));
        lista.add(new Cidade("", "Sobreiro", "ES"));
        lista.add(new Cidade("", "Sooretama", "ES"));
        lista.add(new Cidade("", "Timbuí", "ES"));
        lista.add(new Cidade("", "Todos os Santos", "ES"));
        lista.add(new Cidade("", "Urânia", "ES"));
        lista.add(new Cidade("", "Vargem Alta", "ES"));
        lista.add(new Cidade("", "Vargem Grande do Soturno ", "ES"));
        lista.add(new Cidade("", "Venda Nova do Imigrante", "ES"));
        lista.add(new Cidade("", "Viana", "ES"));
        lista.add(new Cidade("", "Vieira Machado", "ES"));
        lista.add(new Cidade("", "Vila Guaraná", "ES"));
        lista.add(new Cidade("", "Vila Nelita", "ES"));
        lista.add(new Cidade("", "Vila Nova de Bananal", "ES"));
        lista.add(new Cidade("", "Vila Pavão", "ES"));
        lista.add(new Cidade("", "Vila Valério", "ES"));
        lista.add(new Cidade("", "Vila Velha", "ES"));
        lista.add(new Cidade("", "Vila Verde", "ES"));
        lista.add(new Cidade("", "Vinhático", "ES"));
        lista.add(new Cidade("", "Vinte e Cinco de Julho", "ES"));
        lista.add(new Cidade("", "Vitória", "ES"));

        return lista;
    }
}
