package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class GO {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("H0pfESKXeFWPpfugVrsf","Abadia de Goiás","GO"));
        lista.add(new Cidade("vYqr8BVAfv9Ystoh51Pj","Abadiânia","GO"));
        lista.add(new Cidade("N0jjE1VK1OZUu0h70CPI","Acreúna","GO"));
        lista.add(new Cidade("va0FhFTnXwOpQlVIp4SI","Adelândia","GO"));
        lista.add(new Cidade("1GX3Epxbv2rorp4Q8PEe","Água Fria de Goiás","GO"));
        lista.add(new Cidade("ADRxebAJK26qO2bmZojT","Água Limpa","GO"));
        lista.add(new Cidade("CK1s2kl2pYcnTZB60PRM","Águas Lindas de Goiás","GO"));
        lista.add(new Cidade("IoZwP3hMFy5P6zkQKTf3","Alexânia","GO"));
        lista.add(new Cidade("02kV4lenmNjqjPEkzhqX","Aloândia","GO"));
        lista.add(new Cidade("Q1ZLLtEIxbRTk1UtUj4m","Alto Alvorada","GO"));
        lista.add(new Cidade("nBsgb5xQybRMeXCTbYLc","Alto Horizonte","GO"));
        lista.add(new Cidade("7YpsW01EJGWe0ydhiIOY","Alto Paraíso de Goiás","GO"));
        lista.add(new Cidade("Jia7aJ0Cwq2La276kk4j","Alvorada do Norte","GO"));
        lista.add(new Cidade("ewC4V3f7Qf48xGgkwV5N","Amaralina","GO"));
        lista.add(new Cidade("lZKxGoEIqFBZUraKfeCx","Americano do Brasil","GO"));
        lista.add(new Cidade("iiQu3hGqYvCYDTNKSBUt","Amorinópolis","GO"));
        lista.add(new Cidade("zyvFD8PJgzwNGJlDkMyD","Anápolis","GO"));
        lista.add(new Cidade("42nU4n2v839Td23GnN5d","Anhangüera","GO"));
        lista.add(new Cidade("QfAmWEuZASn5ONcXSIk5","Anicuns","GO"));
        lista.add(new Cidade("uaN7Vnh2J5UbXRiH8N6P","Aparecida","GO"));
        lista.add(new Cidade("0JUjmOxZguaQzNvgaXQI","Aparecida de Goiânia","GO"));
        lista.add(new Cidade("62lxtvBVQmShOMDojf5c","Aparecida de Goiás","GO"));
        lista.add(new Cidade("8zxb2TXsO9FbKwaiF497","Aparecida do Rio Claro","GO"));
        lista.add(new Cidade("dnUdQ7L6n1esJoL8hd1o","Aparecida do Rio Doce","GO"));
        lista.add(new Cidade("M6gS28nUHVYSxcWOoyd5","Aporé","GO"));
        lista.add(new Cidade("gVAkcwNX9UggPigHg3tB","Araçu","GO"));
        lista.add(new Cidade("2UzfwDvgG3DkaKK8bwZT","Aragarças","GO"));
        lista.add(new Cidade("e9usgHcJL3KBRsHigcMV","Aragoiânia","GO"));
        lista.add(new Cidade("viODxvkftewHUSk6WY3A","Araguapaz","GO"));
        lista.add(new Cidade("3MYcBZ20TRftfV1k6z8E","Arantina","GO"));
        lista.add(new Cidade("R8PcGnq5WOhHrToS57HL","Arenópolis","GO"));
        lista.add(new Cidade("Ex7XV6ZcX83Rel4BwYM7","Aruanã","GO"));
        lista.add(new Cidade("xU1HQYoRXmDiRA3aaJ25","Aurilândia","GO"));
        lista.add(new Cidade("yAHZfWArP74BxICv26wv","Auriverde","GO"));
        lista.add(new Cidade("OWynhie6PuRUFYaCdzCp","Avelinópolis","GO"));
        lista.add(new Cidade("MaiFTAgAtrafxpZhxiaD","Bacilândia","GO"));
        lista.add(new Cidade("m89HodzI3lZ6wrHhoPyb","Baliza","GO"));
        lista.add(new Cidade("M7lJfGtOC7hHujeJwCeF","Bandeirantes","GO"));
        lista.add(new Cidade("BW9vwfbEn25PFr30VglY","Barbosilândia","GO"));
        lista.add(new Cidade("5PHA58R4tIFHSWhnCm7m","Barro Alto","GO"));
        lista.add(new Cidade("nwHKoUoeJTyQigPTl2Bv","Bela Vista de Goiás","GO"));
        lista.add(new Cidade("Y8qV1hC9j8bqGrPvBaZH","Bezerra","GO"));
        lista.add(new Cidade("2TeqSwDdwpxZyiGfGBkt","Bom Jardim de Goiás","GO"));
        lista.add(new Cidade("nQD6zFkkO1myGcV45s7O","Bom Jesus","GO"));
        lista.add(new Cidade("HrrVcW2kOiiMeRg0xGyu","Bonfinópolis","GO"));
        lista.add(new Cidade("Z4r3HIALpxWhGXjSMHpX","Bonópolis","GO"));
        lista.add(new Cidade("BrHESfK8Cv0j61NsHrou","Brazabrantes","GO"));
        lista.add(new Cidade("Vn4MxS23BURiNn92eqr7","Britânia","GO"));
        lista.add(new Cidade("pczOsqaToQUM72DoLU7X","Buenolândia","GO"));
        lista.add(new Cidade("TF9jxXnAewdX6R0nD0GT","Buriti Alegre","GO"));
        lista.add(new Cidade("nxzY0L3tlcTDXay0Mbsx","Buriti de Goiás","GO"));
        lista.add(new Cidade("1iVX88v1BqmNUZRkdxnS","Buritinópolis","GO"));
        lista.add(new Cidade("BnLaAHqAoXCBg1X05c3y","Cabeceiras","GO"));
        lista.add(new Cidade("XgQx0H2TGSOJRfVucHvS","Cachoeira Alta","GO"));
        lista.add(new Cidade("vcgG2XFeFL053e0f2r3b","Cachoeira de Goiás","GO"));
        lista.add(new Cidade("ZwfsCAEKoB4DnMzDq8Ux","Cachoeira Dourada","GO"));
        lista.add(new Cidade("h6vxIHmfw6k7jd0vMJXg","Caçu","GO"));
        lista.add(new Cidade("XpoavIGTyzqfbblZwlTv","Caiapônia","GO"));
        lista.add(new Cidade("zIVsSW5ShJOlLj7LOXJr","Caiçara","GO"));
        lista.add(new Cidade("7555Gu4Uk2t864iS0mEH","Calcilândia","GO"));
        lista.add(new Cidade("6GY9AORcop329OkEs5El","Caldas Novas","GO"));
        lista.add(new Cidade("fKOLkPIgVD8y9BEhbxG9","Caldazinha","GO"));
        lista.add(new Cidade("bvPrkkdbmrLnlv5uE1iO","Calixto","GO"));
        lista.add(new Cidade("LF4X7TEVDKOH5lL5JB6p","Campestre de Goiás","GO"));
        lista.add(new Cidade("Xo7vLzmm76Z0YzDIQmtU","Campinaçu","GO"));
        lista.add(new Cidade("0fTNz6S8OqeynIsisojw","Campinorte","GO"));
        lista.add(new Cidade("C5vpV4bVZAwaRiTFKScE","Campo Alegre de Goiás","GO"));
        lista.add(new Cidade("MmHeVzEME2H2dxpoWRUI","Campo Limpo","GO"));
        lista.add(new Cidade("H2jEM21aG7KaOtnv425W","Campo Limpo de Goiás","GO"));
        lista.add(new Cidade("HTs1Nm2ephsNSrJxEGrk","Campo Lindo","GO"));
        lista.add(new Cidade("3xzs8r8o9qBSEjShpVgK","Campolândia","GO"));
        lista.add(new Cidade("Idnv91PqxWcZuVuhES7f","Campos Belos","GO"));
        lista.add(new Cidade("zq3RSOyO4qwDdTYGBXlK","Campos Verdes","GO"));
        lista.add(new Cidade("GOwD91EZhZwRXIVRN7Cs","Cana Brava","GO"));
        lista.add(new Cidade("0u7UVxmjDPOk2HRP7TZr","Canadá","GO"));
        lista.add(new Cidade("JdLKLYHFYMuxGgN0k2XV","Capelinha","GO"));
        lista.add(new Cidade("6PVFPVpRPdhta6LXq9ko","Caraíba","GO"));
        lista.add(new Cidade("WnHFswtgqB9OjBEbJQwk","Carmo do Rio Verde","GO"));
        lista.add(new Cidade("xIlO0ncebILzlTTOkauN","Castelândia","GO"));
        lista.add(new Cidade("LN0bPhi09YyyMNf5dgef","Castrinópolis","GO"));
        lista.add(new Cidade("7S4UayWY052sT7GhSRUL","Catalão","GO"));
        lista.add(new Cidade("qjH3tB1RzXKwDz4Hzahb","Caturaí","GO"));
        lista.add(new Cidade("B6Ip0QYCNZtswzySHY3Z","Cavalcante","GO"));
        lista.add(new Cidade("efOxHBs3f3kBvtrhnA8e","Cavalheiro","GO"));
        lista.add(new Cidade("TloZAmcPTAGSbyKQ67vT","Cebrasa","GO"));
        lista.add(new Cidade("lVrenJ0K4xgFiTbHzknZ","Ceres","GO"));
        lista.add(new Cidade("cw3Dgn7fH2p8oCO2vl41","Cezarina","GO"));
        lista.add(new Cidade("FAFtJUAwhvzM7H3fhBJS","Chapadão do Céu","GO"));
        lista.add(new Cidade("befPS5SZ0nnwIUbiIsKn","Choupana","GO"));
        lista.add(new Cidade("JX52SSI1TtIbfd8AY87Z","Cibele","GO"));
        lista.add(new Cidade("jhBslh8K7YMzGwKBW5Ns","Cidade Eclética","GO"));
        lista.add(new Cidade("kuSQcQ0Be7VfQezkVl3D","Cidade Ocidental","GO"));
        lista.add(new Cidade("ztfnoVo4QYBBzhkzCuyR","Cirilândia","GO"));
        lista.add(new Cidade("ARhJ0h0ByRu3HHsK3aYH","Claudinápolis","GO"));
        lista.add(new Cidade("wSgg0hJkmXxFsU9yGiXw","Cocalzinho de Goiás","GO"));
        lista.add(new Cidade("u5f7pQppv53dd9TCMx8Z","Colinaçu","GO"));
        lista.add(new Cidade("rY8AumFJJsmE7r1W6h0f","Colinas do Sul","GO"));
        lista.add(new Cidade("eZGr5K1Zys1rG81oTqO6","Córrego do Ouro","GO"));
        lista.add(new Cidade("c8cCFIGkTP8nHtJbAe2K","Córrego Rico","GO"));
        lista.add(new Cidade("4qew89ICZjmC1I63r7Oq","Corumbá de Goiás","GO"));
        lista.add(new Cidade("1svcUxMmhDLlRIftTRsP","Corumbaíba","GO"));
        lista.add(new Cidade("pLFCN8OMRei0rX5pfLbZ","Cristalina","GO"));
        lista.add(new Cidade("VQzHIV9DS5rUCUc83rPG","Cristianópolis","GO"));
        lista.add(new Cidade("bFocilQJKJ5wARYkBuvG","Crixás","GO"));
        lista.add(new Cidade("GyDhlZx0E2yMRLs03sP5","Cromínia","GO"));
        lista.add(new Cidade("R0Q9OD1EWyMdq8kGK7YC","Cruzeiro do Norte","GO"));
        lista.add(new Cidade("7RY2rcVYgsbUJZCSfx1c","Cumari","GO"));
        lista.add(new Cidade("Mo0l9ypmGufgpYjBGqlF","Damianópolis","GO"));
        lista.add(new Cidade("W6d2iSMlsBzvVFVu1p18","Damolândia","GO"));
        lista.add(new Cidade("7w1AxGsN2Yuv6l1ow7cb","Davidópolis","GO"));
        lista.add(new Cidade("0JBA7UjY3NzFJ06EJSrR","Davinópolis","GO"));
        lista.add(new Cidade("Pl2pObcePTE9jod8SauT","Diolândia","GO"));
        lista.add(new Cidade("YapgwAMB8b1bJHmnsDrN","Diorama","GO"));
        lista.add(new Cidade("Pd3TVpjfGF1r1X00Baki","Divinópolis de Goiás","GO"));
        lista.add(new Cidade("91zuKyiwHKYJzFbewQmV","Domiciano Ribeiro","GO"));
        lista.add(new Cidade("JIGwJdf4GheveifAs1ei","Doverlândia","GO"));
        lista.add(new Cidade("h8aZJz2NBCORLzZYQgE2","Edealina","GO"));
        lista.add(new Cidade("mM2R4PJPNn9e2L4cv5HM","Edéia","GO"));
        lista.add(new Cidade("PebETSdCFXq6bRj8bxrY","Edilândia","GO"));
        lista.add(new Cidade("UeJWwMavZaAAEywBnCc9","Estrela do Norte","GO"));
        lista.add(new Cidade("KNuVJS5HLpttleEy64hV","Faina","GO"));
        lista.add(new Cidade("z1JpKIEUbyHBHiITtZ2w","Fazenda Nova","GO"));
        lista.add(new Cidade("n99e05be8rSdJWYzmlGA","Firminópolis","GO"));
        lista.add(new Cidade("fCCzs6p9FjFkGtx62ks5","Flores de Goiás","GO"));
        lista.add(new Cidade("fOVk8Dsk6aTlz89UdOS7","Formosa","GO"));
        lista.add(new Cidade("x9S56IbCRKfX8Dz1Sdh3","Formoso","GO"));
        lista.add(new Cidade("ZLzm8ZXkPbgqZlRhqgxk","Forte","GO"));
        lista.add(new Cidade("XFhvaW3ZNwzyID6dc58q","Gameleira de Goiás","GO"));
        lista.add(new Cidade("GhZ2RBjepWBbCl80PN2D","Geriaçu","GO"));
        lista.add(new Cidade("HAP4X61Rnwg8Rm3W5gGg","Girassol","GO"));
        lista.add(new Cidade("2dLnIU4s6WYc8Sl39AwZ","Goialândia","GO"));
        lista.add(new Cidade("7d9sZ14LlXWnI7PpVHnS","Goianápolis","GO"));
        lista.add(new Cidade("fN4M9HzTvtXckvRqyNVA","Goiandira","GO"));
        lista.add(new Cidade("2WeTkpwQ7TAtAYJ4cbaV","Goianésia","GO"));
        lista.add(new Cidade("ubaJVYvMJfQEMZS4c3Gl","Goiânia","GO"));
        lista.add(new Cidade("3ITvKlJkr4o57oG3ASWg","Goianira","GO"));
        lista.add(new Cidade("8hxEJmiiPYRMrpeeg6Hz","Goiás","GO"));
        lista.add(new Cidade("e33orkE9JnUOvh7nPYmT","Goiatuba","GO"));
        lista.add(new Cidade("4dOm1M0Sws1Tlp6IZbna","Gouvelândia","GO"));
        lista.add(new Cidade("8ArG3e7GK4d4s0Ac7nB9","Guapó","GO"));
        lista.add(new Cidade("HZADdYRNBJdl34N837mW","Guaraíta","GO"));
        lista.add(new Cidade("XipbEFGFLbejGc3EaQmt","Guarani de Goiás","GO"));
        lista.add(new Cidade("2vTfT9MQxvfeaCAHDP2N","Guarinos","GO"));
        lista.add(new Cidade("wMVWA6NzmWFxVFa1qorU","Heitoraí","GO"));
        lista.add(new Cidade("2CiJnJ7mln6s0zi3mNbC","Hidrolândia","GO"));
        lista.add(new Cidade("70vruM8jIxoSPS3vOQ6l","Hidrolina","GO"));
        lista.add(new Cidade("5Ju3z4fzNbhLZs9yCNMM","Iaciara","GO"));
        lista.add(new Cidade("LMXJ73fl7zPyGsXevzIK","Inaciolândia","GO"));
        lista.add(new Cidade("ZBIZT12j32TCHq175O1r","Indiara","GO"));
        lista.add(new Cidade("d43MG45jufOB36kRX70c","Inhumas","GO"));
        lista.add(new Cidade("aZb2kzwfYjkamXEMLRrc","Interlândia","GO"));
        lista.add(new Cidade("jZUmKAWtPQ2gZBNQZG9D","Ipameri","GO"));
        lista.add(new Cidade("Sq9I65cKKbzlg7wZHIx9","Ipiranga de Goiás","GO"));
        lista.add(new Cidade("FePiM7QzKxoW83mQBhWk","Iporá","GO"));
        lista.add(new Cidade("zvQRBLbBfLrsrv3o8Ji8","Israelândia","GO"));
        lista.add(new Cidade("nYPE3DmpvFYUhSBeq2sM","Itaberaí","GO"));
        lista.add(new Cidade("kLl7ZN84pIgc8y8Qs8Ye","Itaguaçu","GO"));
        lista.add(new Cidade("xJWiL7GWR2u7ZIwbv1iI","Itaguari","GO"));
        lista.add(new Cidade("T7DjDz1Pcn041LUqp7qG","Itaguaru","GO"));
        lista.add(new Cidade("B8VWDz1s2V70REZBbcpj","Itajá","GO"));
        lista.add(new Cidade("z6rqFi7KQooGt2JxDfYd","Itapaci","GO"));
        lista.add(new Cidade("qjiLoRldSuLmsR8nPdXJ","Itapirapuã","GO"));
        lista.add(new Cidade("rZv5P0Cwemk6neUEYxO4","Itapuranga","GO"));
        lista.add(new Cidade("6TTu9mD0HQ40LGPR1RVF","Itarumã","GO"));
        lista.add(new Cidade("6PmaYqbt9Lhg3N8nIWFm","Itauçu","GO"));
        lista.add(new Cidade("zmbXFsHxNH6y0jsdLB3t","Itumbiara","GO"));
        lista.add(new Cidade("mlnZzuL4rvBY7vqdeII7","Ivolândia","GO"));
        lista.add(new Cidade("kBNRGSj05NW19oe4bhTw","Jacilândia","GO"));
        lista.add(new Cidade("GH3TAnPPjWMwGmBME2U0","Jandaia","GO"));
        lista.add(new Cidade("4golkrwoPlglOau0kvVt","Jaraguá","GO"));
        lista.add(new Cidade("uFWfeSYkeqDMcKoEmCUQ","Jardim ABC de Goiás","GO"));
        lista.add(new Cidade("4cQnDF1Ad9MOmPfPSBO5","Jataí","GO"));
        lista.add(new Cidade("GHJpP0wyR95yBcCIWlkX","Jaupaci","GO"));
        lista.add(new Cidade("KgoumWhnyLAGJjjEQWD7","Jeroaquara","GO"));
        lista.add(new Cidade("wPO59MI5c1iM1W6HrcHQ","Jesúpolis","GO"));
        lista.add(new Cidade("tpChRZMCr6la9JSht6us","JK","GO"));
        lista.add(new Cidade("pDO9ujsBoDCNOo6Rxrw6","Joanápolis","GO"));
        lista.add(new Cidade("NwmNP3RfFM2IQJOKJSg9","Joviânia","GO"));
        lista.add(new Cidade("NzSVna9yMDnDmVGxNERp","Juscelândia","GO"));
        lista.add(new Cidade("OS67Iava0cZVD3YzBtDd","Juscelino Kubitschek","GO"));
        lista.add(new Cidade("eJ5oW4ryzvDyEevMQ9uz","Jussara","GO"));
        lista.add(new Cidade("BLtobMnKDQ0PcV5Amtem","Lagoa do Bauzinho","GO"));
        lista.add(new Cidade("QUcLLVg7rtQDm9ceARxv","Lagoa Santa","GO"));
        lista.add(new Cidade("rzv62LlvohEV3fpv0ELU","Lagolândia","GO"));
        lista.add(new Cidade("WMl5alj2xaTwUisRwrXM","Leopoldo de Bulhões","GO"));
        lista.add(new Cidade("8qFlbJbT7WeRUyhONpsg","Lucilândia","GO"));
        lista.add(new Cidade("qxMcmi59Ml6lUmhz9n6y","Luiz Alves","GO"));
        lista.add(new Cidade("oy3WFKUJv0LNOMfBCAgq","Luziânia","GO"));
        lista.add(new Cidade("ktppW2WPQblF3yuJKZ9l","Mairipotaba","GO"));
        lista.add(new Cidade("KKSxY2Sz4e9QN6t8Cise","Mambaí","GO"));
        lista.add(new Cidade("xtvh6McOm3EFuhyKLoPH","Mara Rosa","GO"));
        lista.add(new Cidade("4suufK2nyRg2IEIFhjGT","Marcianópolis","GO"));
        lista.add(new Cidade("FE94UanI6l6FpfNfbYDy","Marzagão","GO"));
        lista.add(new Cidade("fk2FS77WS3umsNfsG2HK","Matrinchã","GO"));
        lista.add(new Cidade("dccjXVVRcZlhB0zAEoXJ","Maurilândia","GO"));
        lista.add(new Cidade("YGflbtPC4pHEL9zyiDXY","Meia Ponte","GO"));
        lista.add(new Cidade("1jKVgiZTWuIuzzA3PQ4s","Messianópolis","GO"));
        lista.add(new Cidade("GtxRjCFP61EqjkXKzPux","Mimoso de Goiás","GO"));
        lista.add(new Cidade("zKd0xUuQ2NnHuxZfCTZD","Minaçu","GO"));
        lista.add(new Cidade("Z5dwczRS7xHVRsxXoV3V","Mineiros","GO"));
        lista.add(new Cidade("eRa3dNYzBLs1NGxEzFTH","Moiporá","GO"));
        lista.add(new Cidade("6G4FNLEsDI9CoKGDxC0t","Monte Alegre de Goiás","GO"));
        lista.add(new Cidade("c13CGH75jmJbDY96p9D3","Montes Claros de Goiás","GO"));
        lista.add(new Cidade("kt6sWi0dsYPXYyVfrESx","Montividiu","GO"));
        lista.add(new Cidade("lzHT4BgFlOfFw8BDOG8U","Montividiu do Norte","GO"));
        lista.add(new Cidade("E3MRBmux8J7T0LcbNlWi","Morrinhos","GO"));
        lista.add(new Cidade("2mChSAO0LtWUTe5HD5Xn","Morro Agudo de Goiás","GO"));
        lista.add(new Cidade("nBSZiYIHXmBB0V9ApnZY","Mossâmedes","GO"));
        lista.add(new Cidade("y5R0kRedUsSJDO9fCeny","Mozarlândia","GO"));
        lista.add(new Cidade("ulBuPP9XazLnRRnvn3tL","Mundo Novo","GO"));
        lista.add(new Cidade("oAyG5Hfh3w5Tl05fKzYX","Mutunópolis","GO"));
        lista.add(new Cidade("TZCRYWsOuvN7EooGBIsN","Natinópolis","GO"));
        lista.add(new Cidade("qf2T7Vr12OffPtyQcSSG","Nazário","GO"));
        lista.add(new Cidade("t2gfagymiRRFu3quHd3V","Nerópolis","GO"));
        lista.add(new Cidade("te1YUd6c5BZWwZyuD8wO","Niquelândia","GO"));
        lista.add(new Cidade("4FCvBjfZq449fn3vWnKn","Nova América","GO"));
        lista.add(new Cidade("uWXJfNuvClgXMBJ7sKcp","Nova Aurora","GO"));
        lista.add(new Cidade("wOOuD7BXwdQrAaU6pkY8","Nova Crixás","GO"));
        lista.add(new Cidade("jQ6ec3avk8gDm01Nx84Z","Nova Fátima","GO"));
        lista.add(new Cidade("sn1Kv9QGMUyopPByHB9r","Nova Glória","GO"));
        lista.add(new Cidade("4LE7CZYatKPkzXjwOYjp","Nova Iguaçu de Goiás","GO"));
        lista.add(new Cidade("EDhtIIUNkYj7dKPtgyr0","Nova Roma","GO"));
        lista.add(new Cidade("ssqL62EoyAzmDdjSCai7","Nova Veneza","GO"));
        lista.add(new Cidade("DeBiK0tKWo6TuVQcnlaV","Novo Brasil","GO"));
        lista.add(new Cidade("inURvaiNO27XCHPcJpk1","Novo Gama","GO"));
        lista.add(new Cidade("DzJTQRAyu3khpRuLNULL","Novo Goiás","GO"));
        lista.add(new Cidade("PvGmm8duNue37JhPk8A9","Novo Planalto","GO"));
        lista.add(new Cidade("eZCdPtoIDy8Ej1qHSKL6","Olaria do Angico","GO"));
        lista.add(new Cidade("prFLPEC7VWpYxAYTPyDt","Olhos D'Água","GO"));
        lista.add(new Cidade("7oJ4LOJLGfH9mmad24eK","Orizona","GO"));
        lista.add(new Cidade("4VinLYdFfKx9tqFBUnyc","Ouro Verde de Goiás","GO"));
        lista.add(new Cidade("5jujttulJocSBVPVuHJU","Ouroana","GO"));
        lista.add(new Cidade("55Fh9VolvLoU7xWPcMh4","Ouvidor","GO"));
        lista.add(new Cidade("JQSNT1pBues2Dutz78Eo","Padre Bernardo","GO"));
        lista.add(new Cidade("7AiW7ZQqahiToL8VA93S","Palestina de Goiás","GO"));
        lista.add(new Cidade("XqHsnykHQvCWDoUVH3ey","Palmeiras de Goiás","GO"));
        lista.add(new Cidade("qSXDPxZgeIGLL7aaUMvM","Palmelo","GO"));
        lista.add(new Cidade("qkAxzb92kw8F3Tv6muFd","Palminópolis","GO"));
        lista.add(new Cidade("Ld0pT5dgqM533Ru969IT","Panamá","GO"));
        lista.add(new Cidade("Tx7jWIlBBXi2V2uNz1ja","Paranaiguara","GO"));
        lista.add(new Cidade("YEinN5UamqP3GeDUUK4M","Paraúna","GO"));
        lista.add(new Cidade("LEBIxej8lVcQdf7hQxO7","Pedra Branca","GO"));
        lista.add(new Cidade("nbJ5hxSad15zWg6vzbbp","Perolândia","GO"));
        lista.add(new Cidade("elaWu0dfzzr0dxsoLZCZ","Petrolina de Goiás","GO"));
        lista.add(new Cidade("YsojfDpNUzl52aSmm2k7","Pilar de Goiás","GO"));
        lista.add(new Cidade("cFcq6UXO6Y5OuWVOx58v","Piloândia","GO"));
        lista.add(new Cidade("hWWvYv8XxR1uHupDyM3x","Piracanjuba","GO"));
        lista.add(new Cidade("SxasnJXgcb4XTKcPes0X","Piranhas","GO"));
        lista.add(new Cidade("U1FV82OISTL49LipuTZG","Pirenópolis","GO"));
        lista.add(new Cidade("qSJA69qWvTXL4J9XBBDR","Pires Belo","GO"));
        lista.add(new Cidade("FHKub9XIZTUl4uDspu5E","Pires do Rio","GO"));
        lista.add(new Cidade("K37nCFXirVITbwwcsgZm","Planalmira","GO"));
        lista.add(new Cidade("hoBoKhFGg4XiL2snt81v","Planaltina","GO"));
        lista.add(new Cidade("kqU36P9JER6ZuMwG8anw","Pontalina","GO"));
        lista.add(new Cidade("3AVovXuSHTqp6CqdD44F","Porangatu","GO"));
        lista.add(new Cidade("OhKqC2WLC52CgEKXBUFI","Porteirão","GO"));
        lista.add(new Cidade("fQebhNMjkkKkOPU3spwx","Portelândia","GO"));
        lista.add(new Cidade("qfUoKig8JFUuIoP3BtaT","Posse","GO"));
        lista.add(new Cidade("ye8Tucv2IF85AtzqrdAo","Posse D'Abadia","GO"));
        lista.add(new Cidade("xx0j1xhDnuujguppO6kT","Posselândia","GO"));
        lista.add(new Cidade("FOy9xGPgwbZAmRp3H8nq","Prata","GO"));
        lista.add(new Cidade("xsmVqJJRgKtut3NTLJSG","Professor Jamil","GO"));
        lista.add(new Cidade("R9lNajHS0TukpfZdNMXN","Quirinópolis","GO"));
        lista.add(new Cidade("HsWDzbty8ZfK0ol2Z7wM","Registro do Araguaia","GO"));
        lista.add(new Cidade("Hz57rcFzTLCMLAjiS06Y","Rialma","GO"));
        lista.add(new Cidade("0PzkcWMaFqknFbM9PPi5","Rianápolis","GO"));
        lista.add(new Cidade("gAQy0N3bcPYwH6yDPmhg","Rio Quente","GO"));
        lista.add(new Cidade("UOEXJXa65KHq26Ysa0h4","Rio Verde","GO"));
        lista.add(new Cidade("Y5ZTaZWk4wqv2SlSOmYj","Riverlândia","GO"));
        lista.add(new Cidade("YcGztvziMVohFoxi9Enb","Rosalândia","GO"));
        lista.add(new Cidade("vhbeBIA7Oieus87mGOBF","Rubiataba","GO"));
        lista.add(new Cidade("sUgcmYibuuDBaN24GuQV","Sanclerlândia","GO"));
        lista.add(new Cidade("wrxVzMbsbumEp0l1GmMA","Santa Bárbara de Goiás","GO"));
        lista.add(new Cidade("DfT0pM6E5fIOxsmpLIOz","Santa Cruz das Lajes","GO"));
        lista.add(new Cidade("bVRKeZX6xxHcaLJ0TeRu","Santa Cruz de Goiás","GO"));
        lista.add(new Cidade("mhNN4cf8EtqTXKOwo2On","Santa Fé de Goiás","GO"));
        lista.add(new Cidade("2Z9ZnbooQ6phFX9jMUvd","Santa Helena de Goiás","GO"));
        lista.add(new Cidade("Jd2imrTvWPRfZXqxxO66","Santa Isabel","GO"));
        lista.add(new Cidade("bIlBiuL80gTaCAAZdBZU","Santa Maria","GO"));
        lista.add(new Cidade("4ErQ21DOMshJ3sVnsUyx","Santa Rita do Araguaia","GO"));
        lista.add(new Cidade("j2C8bRCOYl9WxIfDJhSO","Santa Rita do Novo Destino","GO"));
        lista.add(new Cidade("qnNB3AH5BpIKRZ0p6ldE","Santa Rosa","GO"));
        lista.add(new Cidade("S9bcXh3x0LPkDQKmFrvs","Santa Rosa de Goiás","GO"));
        lista.add(new Cidade("ZP55BUl6JQjliR4AA4bS","Santa Tereza de Goiás","GO"));
        lista.add(new Cidade("At1y1r9EymuBijhRCCLe","Santa Terezinha de Goiás","GO"));
        lista.add(new Cidade("Q4w7raw94ZX5ZzPiNsD1","Santo Antônio da Barra","GO"));
        lista.add(new Cidade("KIfZKYtI6XfKYwbUILmP","Santo Antônio da Esperança","GO"));
        lista.add(new Cidade("wamjMhZJTKQxbL5bE61P","Santo Antônio de Goiás","GO"));
        lista.add(new Cidade("IJZBDcmzj659ub3O2tkR","Santo Antônio do Descoberto","GO"));
        lista.add(new Cidade("dimql7YQMf7CeZbyTbjm","Santo Antônio do Rio Verde","GO"));
        lista.add(new Cidade("DaH1GWbMzzvpNcDfenFd","São Domingos","GO"));
        lista.add(new Cidade("KtWZ6cu2dj8kJ8jasAwZ","São Francisco de Goiás","GO"));
        lista.add(new Cidade("Os9pvI7KZUnHaZ68ka7E","São Gabriel de Goiás","GO"));
        lista.add(new Cidade("Iy9RoumMoOm3ZejUpxBI","São João","GO"));
        lista.add(new Cidade("k7ABQCHUshtNqR7RRq7y","São João da Paraúna","GO"));
        lista.add(new Cidade("JLDBdMxEuN1b4A0FpsV1","São João D'Aliança","GO"));
        lista.add(new Cidade("BMn4kcD86TpIe0YwsNZq","São Jorge","GO"));
        lista.add(new Cidade("I44hOrCzT5VgPUnasgjl","São Luís de Montes Belos","GO"));
        lista.add(new Cidade("EKqNtPHUCD2Vvr8fZ5sa","São Luiz do Norte","GO"));
        lista.add(new Cidade("2qCHn57RqK9smNOSRoiI","São Luiz do Tocantins","GO"));
        lista.add(new Cidade("EaNu2zZHuHkY4g1o4sWk","São Miguel do Araguaia","GO"));
        lista.add(new Cidade("DU9Oz1SovUkhs7lK8gYg","São Miguel do Passa Quatro","GO"));
        lista.add(new Cidade("3ZcBtrM7F61Xngziw3TY","São Patrício","GO"));
        lista.add(new Cidade("pnD3w3zqr6VfpzKkJd2t","São Sebastião do Rio Claro","GO"));
        lista.add(new Cidade("zbLr1wCEBHsXeTXHnsLh","São Simão","GO"));
        lista.add(new Cidade("c0SI1QA9Hi2omnJW4nTk","São Vicente","GO"));
        lista.add(new Cidade("h3uwrXl9o1MUxWFrRnNX","Sapé","GO"));
        lista.add(new Cidade("LdExXHLrEiuG8OX1GB9e","Sarandi","GO"));
        lista.add(new Cidade("h7NmNlBYmK8RlPabJyiF","Senador Canedo","GO"));
        lista.add(new Cidade("xLRQI7JazTtQ6QSLQdCZ","Serra Dourada","GO"));
        lista.add(new Cidade("eolkzEzu7yrPMUY0DcJm","Serranópolis","GO"));
        lista.add(new Cidade("OpS4VCWwvGUKmiX9RAkW","Silvânia","GO"));
        lista.add(new Cidade("uEmU9oLyDRJF1T6anmid","Simolândia","GO"));
        lista.add(new Cidade("VxofyeKTc4uZyb652Fn2","Sítio D'Abadia","GO"));
        lista.add(new Cidade("Dj1nrdDm3ZmtQF2EQc9f","Sousânia","GO"));
        lista.add(new Cidade("kbkkArQ5j5EClH9fWdLY","Souzalândia","GO"));
        lista.add(new Cidade("rNusQ8a5tRbONBd0byI3","Taquaral de Goiás","GO"));
        lista.add(new Cidade("MtA90ayveoTQ9zZXBy2J","Taveira","GO"));
        lista.add(new Cidade("x2uN1IgwGhRqJ0UQxWRS","Teresina de Goiás","GO"));
        lista.add(new Cidade("PHlo4AnMTSXlP11TOar7","Terezópolis de Goiás","GO"));
        lista.add(new Cidade("6tidl6gzGz3b1djcuKKQ","Três Ranchos","GO"));
        lista.add(new Cidade("BkSFd9XNfQ6zwUJ7SjSn","Trevo do José Rosário","GO"));
        lista.add(new Cidade("G26nfJgPmDSF1Dn8ulD0","Trindade","GO"));
        lista.add(new Cidade("cBcYwNPH8clxz2X132a1","Trombas","GO"));
        lista.add(new Cidade("FUP0tb2y9JcbSt7wtNR2","Tupiracaba","GO"));
        lista.add(new Cidade("Rfpb2cdabmdn52gaDgPT","Turvânia","GO"));
        lista.add(new Cidade("89UgeqmgwYju3VaQHGqC","Turvelândia","GO"));
        lista.add(new Cidade("L4cFdZxqYJu8QslCnNNQ","Uirapuru","GO"));
        lista.add(new Cidade("MWQwz9RK2mhv7aBFMkep","Uruaçu","GO"));
        lista.add(new Cidade("a8XncBk5skozSELGLqGn","Uruana","GO"));
        lista.add(new Cidade("aVnjs2KYBPKAJSNDTQwv","Uruita","GO"));
        lista.add(new Cidade("pzWhwLgmhDTL1QseAdIG","Urutaí","GO"));
        lista.add(new Cidade("pimQB6t0AUaVp3xhvLcp","Uvá","GO"));
        lista.add(new Cidade("tZjY7lvFRVfCz7ef04rY","Valdelândia","GO"));
        lista.add(new Cidade("ZHN9GtlnmUG3HZcKxqZL","Valparaíso de Goiás","GO"));
        lista.add(new Cidade("n1RPUIzqbC73hvZdshGX","Varjão","GO"));
        lista.add(new Cidade("W5vWfmefMGAfmoYXQ5SX","Vazante","GO"));
        lista.add(new Cidade("187poCJqcJyFqb11Ktgf","Vianópolis","GO"));
        lista.add(new Cidade("68PH5krKC44XifuWIei1","Vicentinópolis","GO"));
        lista.add(new Cidade("AYMp8ZQ96sSAzyhIaja4","Vila Boa","GO"));
        lista.add(new Cidade("JFvkJgkkfJOtqshLXryv","Vila Propício","GO"));
        lista.add(new Cidade("DKQKbZfyUJx1HqKdBb3W","Vila Sertaneja","GO"));

        return lista;
    }
}
