package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class GO {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Abadia de Goiás", "GO"));
        lista.add(new Cidade("", "Abadiânia", "GO"));
        lista.add(new Cidade("", "Acreúna", "GO"));
        lista.add(new Cidade("", "Adelândia", "GO"));
        lista.add(new Cidade("", "Água Fria de Goiás", "GO"));
        lista.add(new Cidade("", "Água Limpa", "GO"));
        lista.add(new Cidade("", "Águas Lindas de Goiás", "GO"));
        lista.add(new Cidade("", "Alexânia", "GO"));
        lista.add(new Cidade("", "Aloândia", "GO"));
        lista.add(new Cidade("", "Alto Alvorada", "GO"));
        lista.add(new Cidade("", "Alto Horizonte", "GO"));
        lista.add(new Cidade("", "Alto Paraíso de Goiás", "GO"));
        lista.add(new Cidade("", "Alvorada do Norte", "GO"));
        lista.add(new Cidade("", "Amaralina", "GO"));
        lista.add(new Cidade("", "Americano do Brasil", "GO"));
        lista.add(new Cidade("", "Amorinópolis", "GO"));
        lista.add(new Cidade("", "Anápolis", "GO"));
        lista.add(new Cidade("", "Anhangüera", "GO"));
        lista.add(new Cidade("", "Anicuns", "GO"));
        lista.add(new Cidade("", "Aparecida", "GO"));
        lista.add(new Cidade("", "Aparecida de Goiânia", "GO"));
        lista.add(new Cidade("", "Aparecida de Goiás", "GO"));
        lista.add(new Cidade("", "Aparecida do Rio Claro", "GO"));
        lista.add(new Cidade("", "Aparecida do Rio Doce", "GO"));
        lista.add(new Cidade("", "Aporé", "GO"));
        lista.add(new Cidade("", "Araçu", "GO"));
        lista.add(new Cidade("", "Aragarças", "GO"));
        lista.add(new Cidade("", "Aragoiânia", "GO"));
        lista.add(new Cidade("", "Araguapaz", "GO"));
        lista.add(new Cidade("", "Arantina", "GO"));
        lista.add(new Cidade("", "Arenópolis", "GO"));
        lista.add(new Cidade("", "Aruanã", "GO"));
        lista.add(new Cidade("", "Aurilândia", "GO"));
        lista.add(new Cidade("", "Auriverde", "GO"));
        lista.add(new Cidade("", "Avelinópolis", "GO"));
        lista.add(new Cidade("", "Bacilândia", "GO"));
        lista.add(new Cidade("", "Baliza", "GO"));
        lista.add(new Cidade("", "Bandeirantes", "GO"));
        lista.add(new Cidade("", "Barbosilândia", "GO"));
        lista.add(new Cidade("", "Barro Alto", "GO"));
        lista.add(new Cidade("", "Bela Vista de Goiás", "GO"));
        lista.add(new Cidade("", "Bezerra", "GO"));
        lista.add(new Cidade("", "Bom Jardim de Goiás", "GO"));
        lista.add(new Cidade("", "Bom Jesus", "GO"));
        lista.add(new Cidade("", "Bonfinópolis", "GO"));
        lista.add(new Cidade("", "Bonópolis", "GO"));
        lista.add(new Cidade("", "Brazabrantes", "GO"));
        lista.add(new Cidade("", "Britânia", "GO"));
        lista.add(new Cidade("", "Buenolândia", "GO"));
        lista.add(new Cidade("", "Buriti Alegre", "GO"));
        lista.add(new Cidade("", "Buriti de Goiás", "GO"));
        lista.add(new Cidade("", "Buritinópolis", "GO"));
        lista.add(new Cidade("", "Cabeceiras", "GO"));
        lista.add(new Cidade("", "Cachoeira Alta", "GO"));
        lista.add(new Cidade("", "Cachoeira de Goiás", "GO"));
        lista.add(new Cidade("", "Cachoeira Dourada", "GO"));
        lista.add(new Cidade("", "Caçu", "GO"));
        lista.add(new Cidade("", "Caiapônia", "GO"));
        lista.add(new Cidade("", "Caiçara", "GO"));
        lista.add(new Cidade("", "Calcilândia", "GO"));
        lista.add(new Cidade("", "Caldas Novas", "GO"));
        lista.add(new Cidade("", "Caldazinha", "GO"));
        lista.add(new Cidade("", "Calixto", "GO"));
        lista.add(new Cidade("", "Campestre de Goiás", "GO"));
        lista.add(new Cidade("", "Campinaçu", "GO"));
        lista.add(new Cidade("", "Campinorte", "GO"));
        lista.add(new Cidade("", "Campo Alegre de Goiás", "GO"));
        lista.add(new Cidade("", "Campo Limpo", "GO"));
        lista.add(new Cidade("", "Campo Limpo de Goiás", "GO"));
        lista.add(new Cidade("", "Campo Lindo", "GO"));
        lista.add(new Cidade("", "Campolândia", "GO"));
        lista.add(new Cidade("", "Campos Belos", "GO"));
        lista.add(new Cidade("", "Campos Verdes", "GO"));
        lista.add(new Cidade("", "Cana Brava", "GO"));
        lista.add(new Cidade("", "Canadá", "GO"));
        lista.add(new Cidade("", "Capelinha", "GO"));
        lista.add(new Cidade("", "Caraíba", "GO"));
        lista.add(new Cidade("", "Carmo do Rio Verde", "GO"));
        lista.add(new Cidade("", "Castelândia", "GO"));
        lista.add(new Cidade("", "Castrinópolis", "GO"));
        lista.add(new Cidade("", "Catalão", "GO"));
        lista.add(new Cidade("", "Caturaí", "GO"));
        lista.add(new Cidade("", "Cavalcante", "GO"));
        lista.add(new Cidade("", "Cavalheiro", "GO"));
        lista.add(new Cidade("", "Cebrasa", "GO"));
        lista.add(new Cidade("", "Ceres", "GO"));
        lista.add(new Cidade("", "Cezarina", "GO"));
        lista.add(new Cidade("", "Chapadão do Céu", "GO"));
        lista.add(new Cidade("", "Choupana", "GO"));
        lista.add(new Cidade("", "Cibele", "GO"));
        lista.add(new Cidade("", "Cidade Eclética", "GO"));
        lista.add(new Cidade("", "Cidade Ocidental", "GO"));
        lista.add(new Cidade("", "Cirilândia", "GO"));
        lista.add(new Cidade("", "Claudinápolis", "GO"));
        lista.add(new Cidade("", "Cocalzinho de Goiás", "GO"));
        lista.add(new Cidade("", "Colinaçu", "GO"));
        lista.add(new Cidade("", "Colinas do Sul", "GO"));
        lista.add(new Cidade("", "Córrego do Ouro", "GO"));
        lista.add(new Cidade("", "Córrego Rico", "GO"));
        lista.add(new Cidade("", "Corumbá de Goiás", "GO"));
        lista.add(new Cidade("", "Corumbaíba", "GO"));
        lista.add(new Cidade("", "Cristalina", "GO"));
        lista.add(new Cidade("", "Cristianópolis", "GO"));
        lista.add(new Cidade("", "Crixás", "GO"));
        lista.add(new Cidade("", "Cromínia", "GO"));
        lista.add(new Cidade("", "Cruzeiro do Norte", "GO"));
        lista.add(new Cidade("", "Cumari", "GO"));
        lista.add(new Cidade("", "Damianópolis", "GO"));
        lista.add(new Cidade("", "Damolândia", "GO"));
        lista.add(new Cidade("", "Davidópolis", "GO"));
        lista.add(new Cidade("", "Davinópolis", "GO"));
        lista.add(new Cidade("", "Diolândia", "GO"));
        lista.add(new Cidade("", "Diorama", "GO"));
        lista.add(new Cidade("", "Divinópolis de Goiás", "GO"));
        lista.add(new Cidade("", "Domiciano Ribeiro", "GO"));
        lista.add(new Cidade("", "Doverlândia", "GO"));
        lista.add(new Cidade("", "Edealina", "GO"));
        lista.add(new Cidade("", "Edéia", "GO"));
        lista.add(new Cidade("", "Edilândia", "GO"));
        lista.add(new Cidade("", "Estrela do Norte", "GO"));
        lista.add(new Cidade("", "Faina", "GO"));
        lista.add(new Cidade("", "Fazenda Nova", "GO"));
        lista.add(new Cidade("", "Firminópolis", "GO"));
        lista.add(new Cidade("", "Flores de Goiás", "GO"));
        lista.add(new Cidade("", "Formosa", "GO"));
        lista.add(new Cidade("", "Formoso", "GO"));
        lista.add(new Cidade("", "Forte", "GO"));
        lista.add(new Cidade("", "Gameleira de Goiás", "GO"));
        lista.add(new Cidade("", "Geriaçu", "GO"));
        lista.add(new Cidade("", "Girassol", "GO"));
        lista.add(new Cidade("", "Goialândia", "GO"));
        lista.add(new Cidade("", "Goianápolis", "GO"));
        lista.add(new Cidade("", "Goiandira", "GO"));
        lista.add(new Cidade("", "Goianésia", "GO"));
        lista.add(new Cidade("", "Goiânia", "GO"));
        lista.add(new Cidade("", "Goianira", "GO"));
        lista.add(new Cidade("", "Goiás", "GO"));
        lista.add(new Cidade("", "Goiatuba", "GO"));
        lista.add(new Cidade("", "Gouvelândia", "GO"));
        lista.add(new Cidade("", "Guapó", "GO"));
        lista.add(new Cidade("", "Guaraíta", "GO"));
        lista.add(new Cidade("", "Guarani de Goiás", "GO"));
        lista.add(new Cidade("", "Guarinos", "GO"));
        lista.add(new Cidade("", "Heitoraí", "GO"));
        lista.add(new Cidade("", "Hidrolândia", "GO"));
        lista.add(new Cidade("", "Hidrolina", "GO"));
        lista.add(new Cidade("", "Iaciara", "GO"));
        lista.add(new Cidade("", "Inaciolândia", "GO"));
        lista.add(new Cidade("", "Indiara", "GO"));
        lista.add(new Cidade("", "Inhumas", "GO"));
        lista.add(new Cidade("", "Interlândia", "GO"));
        lista.add(new Cidade("", "Ipameri", "GO"));
        lista.add(new Cidade("", "Ipiranga de Goiás", "GO"));
        lista.add(new Cidade("", "Iporá", "GO"));
        lista.add(new Cidade("", "Israelândia", "GO"));
        lista.add(new Cidade("", "Itaberaí", "GO"));
        lista.add(new Cidade("", "Itaguaçu", "GO"));
        lista.add(new Cidade("", "Itaguari", "GO"));
        lista.add(new Cidade("", "Itaguaru", "GO"));
        lista.add(new Cidade("", "Itajá", "GO"));
        lista.add(new Cidade("", "Itapaci", "GO"));
        lista.add(new Cidade("", "Itapirapuã", "GO"));
        lista.add(new Cidade("", "Itapuranga", "GO"));
        lista.add(new Cidade("", "Itarumã", "GO"));
        lista.add(new Cidade("", "Itauçu", "GO"));
        lista.add(new Cidade("", "Itumbiara", "GO"));
        lista.add(new Cidade("", "Ivolândia", "GO"));
        lista.add(new Cidade("", "Jacilândia", "GO"));
        lista.add(new Cidade("", "Jandaia", "GO"));
        lista.add(new Cidade("", "Jaraguá", "GO"));
        lista.add(new Cidade("", "Jardim ABC de Goiás", "GO"));
        lista.add(new Cidade("", "Jataí", "GO"));
        lista.add(new Cidade("", "Jaupaci", "GO"));
        lista.add(new Cidade("", "Jeroaquara", "GO"));
        lista.add(new Cidade("", "Jesúpolis", "GO"));
        lista.add(new Cidade("", "JK", "GO"));
        lista.add(new Cidade("", "Joanápolis", "GO"));
        lista.add(new Cidade("", "Joviânia", "GO"));
        lista.add(new Cidade("", "Juscelândia", "GO"));
        lista.add(new Cidade("", "Juscelino Kubitschek", "GO"));
        lista.add(new Cidade("", "Jussara", "GO"));
        lista.add(new Cidade("", "Lagoa do Bauzinho", "GO"));
        lista.add(new Cidade("", "Lagoa Santa", "GO"));
        lista.add(new Cidade("", "Lagolândia", "GO"));
        lista.add(new Cidade("", "Leopoldo de Bulhões", "GO"));
        lista.add(new Cidade("", "Lucilândia", "GO"));
        lista.add(new Cidade("", "Luiz Alves", "GO"));
        lista.add(new Cidade("", "Luziânia", "GO"));
        lista.add(new Cidade("", "Mairipotaba", "GO"));
        lista.add(new Cidade("", "Mambaí", "GO"));
        lista.add(new Cidade("", "Mara Rosa", "GO"));
        lista.add(new Cidade("", "Marcianópolis", "GO"));
        lista.add(new Cidade("", "Marzagão", "GO"));
        lista.add(new Cidade("", "Matrinchã", "GO"));
        lista.add(new Cidade("", "Maurilândia", "GO"));
        lista.add(new Cidade("", "Meia Ponte", "GO"));
        lista.add(new Cidade("", "Messianópolis", "GO"));
        lista.add(new Cidade("", "Mimoso de Goiás", "GO"));
        lista.add(new Cidade("", "Minaçu", "GO"));
        lista.add(new Cidade("", "Mineiros", "GO"));
        lista.add(new Cidade("", "Moiporá", "GO"));
        lista.add(new Cidade("", "Monte Alegre de Goiás", "GO"));
        lista.add(new Cidade("", "Montes Claros de Goiás", "GO"));
        lista.add(new Cidade("", "Montividiu", "GO"));
        lista.add(new Cidade("", "Montividiu do Norte", "GO"));
        lista.add(new Cidade("", "Morrinhos", "GO"));
        lista.add(new Cidade("", "Morro Agudo de Goiás", "GO"));
        lista.add(new Cidade("", "Mossâmedes", "GO"));
        lista.add(new Cidade("", "Mozarlândia", "GO"));
        lista.add(new Cidade("", "Mundo Novo", "GO"));
        lista.add(new Cidade("", "Mutunópolis", "GO"));
        lista.add(new Cidade("", "Natinópolis", "GO"));
        lista.add(new Cidade("", "Nazário", "GO"));
        lista.add(new Cidade("", "Nerópolis", "GO"));
        lista.add(new Cidade("", "Niquelândia", "GO"));
        lista.add(new Cidade("", "Nova América", "GO"));
        lista.add(new Cidade("", "Nova Aurora", "GO"));
        lista.add(new Cidade("", "Nova Crixás", "GO"));
        lista.add(new Cidade("", "Nova Fátima", "GO"));
        lista.add(new Cidade("", "Nova Glória", "GO"));
        lista.add(new Cidade("", "Nova Iguaçu de Goiás", "GO"));
        lista.add(new Cidade("", "Nova Roma", "GO"));
        lista.add(new Cidade("", "Nova Veneza", "GO"));
        lista.add(new Cidade("", "Novo Brasil", "GO"));
        lista.add(new Cidade("", "Novo Gama", "GO"));
        lista.add(new Cidade("", "Novo Goiás", "GO"));
        lista.add(new Cidade("", "Novo Planalto", "GO"));
        lista.add(new Cidade("", "Olaria do Angico", "GO"));
        lista.add(new Cidade("", "Olhos D'Água", "GO"));
        lista.add(new Cidade("", "Orizona", "GO"));
        lista.add(new Cidade("", "Ouro Verde de Goiás", "GO"));
        lista.add(new Cidade("", "Ouroana", "GO"));
        lista.add(new Cidade("", "Ouvidor", "GO"));
        lista.add(new Cidade("", "Padre Bernardo", "GO"));
        lista.add(new Cidade("", "Palestina de Goiás", "GO"));
        lista.add(new Cidade("", "Palmeiras de Goiás", "GO"));
        lista.add(new Cidade("", "Palmelo", "GO"));
        lista.add(new Cidade("", "Palminópolis", "GO"));
        lista.add(new Cidade("", "Panamá", "GO"));
        lista.add(new Cidade("", "Paranaiguara", "GO"));
        lista.add(new Cidade("", "Paraúna", "GO"));
        lista.add(new Cidade("", "Pedra Branca", "GO"));
        lista.add(new Cidade("", "Perolândia", "GO"));
        lista.add(new Cidade("", "Petrolina de Goiás", "GO"));
        lista.add(new Cidade("", "Pilar de Goiás", "GO"));
        lista.add(new Cidade("", "Piloândia", "GO"));
        lista.add(new Cidade("", "Piracanjuba", "GO"));
        lista.add(new Cidade("", "Piranhas", "GO"));
        lista.add(new Cidade("", "Pirenópolis", "GO"));
        lista.add(new Cidade("", "Pires Belo", "GO"));
        lista.add(new Cidade("", "Pires do Rio", "GO"));
        lista.add(new Cidade("", "Planalmira", "GO"));
        lista.add(new Cidade("", "Planaltina", "GO"));
        lista.add(new Cidade("", "Pontalina", "GO"));
        lista.add(new Cidade("", "Porangatu", "GO"));
        lista.add(new Cidade("", "Porteirão", "GO"));
        lista.add(new Cidade("", "Portelândia", "GO"));
        lista.add(new Cidade("", "Posse", "GO"));
        lista.add(new Cidade("", "Posse D'Abadia", "GO"));
        lista.add(new Cidade("", "Posselândia", "GO"));
        lista.add(new Cidade("", "Prata", "GO"));
        lista.add(new Cidade("", "Professor Jamil", "GO"));
        lista.add(new Cidade("", "Quirinópolis", "GO"));
        lista.add(new Cidade("", "Registro do Araguaia", "GO"));
        lista.add(new Cidade("", "Rialma", "GO"));
        lista.add(new Cidade("", "Rianápolis", "GO"));
        lista.add(new Cidade("", "Rio Quente", "GO"));
        lista.add(new Cidade("", "Rio Verde", "GO"));
        lista.add(new Cidade("", "Riverlândia", "GO"));
        lista.add(new Cidade("", "Rosalândia", "GO"));
        lista.add(new Cidade("", "Rubiataba", "GO"));
        lista.add(new Cidade("", "Sanclerlândia", "GO"));
        lista.add(new Cidade("", "Santa Bárbara de Goiás", "GO"));
        lista.add(new Cidade("", "Santa Cruz das Lajes", "GO"));
        lista.add(new Cidade("", "Santa Cruz de Goiás", "GO"));
        lista.add(new Cidade("", "Santa Fé de Goiás", "GO"));
        lista.add(new Cidade("", "Santa Helena de Goiás", "GO"));
        lista.add(new Cidade("", "Santa Isabel", "GO"));
        lista.add(new Cidade("", "Santa Maria", "GO"));
        lista.add(new Cidade("", "Santa Rita do Araguaia", "GO"));
        lista.add(new Cidade("", "Santa Rita do Novo Destino", "GO"));
        lista.add(new Cidade("", "Santa Rosa", "GO"));
        lista.add(new Cidade("", "Santa Rosa de Goiás", "GO"));
        lista.add(new Cidade("", "Santa Tereza de Goiás", "GO"));
        lista.add(new Cidade("", "Santa Terezinha de Goiás", "GO"));
        lista.add(new Cidade("", "Santo Antônio da Barra", "GO"));
        lista.add(new Cidade("", "Santo Antônio da Esperança", "GO"));
        lista.add(new Cidade("", "Santo Antônio de Goiás", "GO"));
        lista.add(new Cidade("", "Santo Antônio do Descoberto", "GO"));
        lista.add(new Cidade("", "Santo Antônio do Rio Verde", "GO"));
        lista.add(new Cidade("", "São Domingos", "GO"));
        lista.add(new Cidade("", "São Francisco de Goiás", "GO"));
        lista.add(new Cidade("", "São Gabriel de Goiás", "GO"));
        lista.add(new Cidade("", "São João", "GO"));
        lista.add(new Cidade("", "São João da Paraúna", "GO"));
        lista.add(new Cidade("", "São João D'Aliança", "GO"));
        lista.add(new Cidade("", "São Jorge", "GO"));
        lista.add(new Cidade("", "São Luís de Montes Belos", "GO"));
        lista.add(new Cidade("", "São Luiz do Norte", "GO"));
        lista.add(new Cidade("", "São Luiz do Tocantins", "GO"));
        lista.add(new Cidade("", "São Miguel do Araguaia", "GO"));
        lista.add(new Cidade("", "São Miguel do Passa Quatro", "GO"));
        lista.add(new Cidade("", "São Patrício", "GO"));
        lista.add(new Cidade("", "São Sebastião do Rio Claro", "GO"));
        lista.add(new Cidade("", "São Simão", "GO"));
        lista.add(new Cidade("", "São Vicente", "GO"));
        lista.add(new Cidade("", "Sapé", "GO"));
        lista.add(new Cidade("", "Sarandi", "GO"));
        lista.add(new Cidade("", "Senador Canedo", "GO"));
        lista.add(new Cidade("", "Serra Dourada", "GO"));
        lista.add(new Cidade("", "Serranópolis", "GO"));
        lista.add(new Cidade("", "Silvânia", "GO"));
        lista.add(new Cidade("", "Simolândia", "GO"));
        lista.add(new Cidade("", "Sítio D'Abadia", "GO"));
        lista.add(new Cidade("", "Sousânia", "GO"));
        lista.add(new Cidade("", "Souzalândia", "GO"));
        lista.add(new Cidade("", "Taquaral de Goiás", "GO"));
        lista.add(new Cidade("", "Taveira", "GO"));
        lista.add(new Cidade("", "Teresina de Goiás", "GO"));
        lista.add(new Cidade("", "Terezópolis de Goiás", "GO"));
        lista.add(new Cidade("", "Três Ranchos", "GO"));
        lista.add(new Cidade("", "Trevo do José Rosário", "GO"));
        lista.add(new Cidade("", "Trindade", "GO"));
        lista.add(new Cidade("", "Trombas", "GO"));
        lista.add(new Cidade("", "Tupiracaba", "GO"));
        lista.add(new Cidade("", "Turvânia", "GO"));
        lista.add(new Cidade("", "Turvelândia", "GO"));
        lista.add(new Cidade("", "Uirapuru", "GO"));
        lista.add(new Cidade("", "Uruaçu", "GO"));
        lista.add(new Cidade("", "Uruana", "GO"));
        lista.add(new Cidade("", "Uruita", "GO"));
        lista.add(new Cidade("", "Urutaí", "GO"));
        lista.add(new Cidade("", "Uvá", "GO"));
        lista.add(new Cidade("", "Valdelândia", "GO"));
        lista.add(new Cidade("", "Valparaíso de Goiás", "GO"));
        lista.add(new Cidade("", "Varjão", "GO"));
        lista.add(new Cidade("", "Vazante", "GO"));
        lista.add(new Cidade("", "Vianópolis", "GO"));
        lista.add(new Cidade("", "Vicentinópolis", "GO"));
        lista.add(new Cidade("", "Vila Boa", "GO"));
        lista.add(new Cidade("", "Vila Propício", "GO"));
        lista.add(new Cidade("", "Vila Sertaneja", "GO"));
        return lista;
    }
}
