package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("btXLim5xbr2mUKw53G2Q", "Açailândia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("KHPvXQ0Ym0443Qyk6rYV", "Afonso Cunha","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Y6qdEDcdET4iVv4O1XZK", "Água Doce do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("bHldHYrBiNUjGtqZ3gvX", "Alcântara","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("IebBSBnSjw6R0zqZKOm6", "Aldeias Altas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("eGvFy51W4EIlREmYPhMx", "Altamira do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("aqCygdLIvgTwLAGPY0Eb", "Alto Alegre do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("fW7ysCCEptL6Tpnwwvph", "Alto Alegre do Pindaré","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("1t25HUtpYoSSWTQ2RaiG", "Alto Parnaíba","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("OJ4sCDgClG2KzML2aiAh", "Amapá do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("zSwCOwL24jsNaaJdKjs5", "Amarante do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("FM46DRcaggKmWWKNHBWk", "Anajatuba","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("u9vuuc1MiQHKTL8kKkhP", "Anapurus","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MulAZRrQ07yEbZEqqzmT", "Anil","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("fSgsPSkenSIiMGH0AaOb", "Apicum-Açu","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("IIy8kEXQBwJz0qmyt5Rk", "Araguanã","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("UWx9zQbh1zNleOe6tUdB", "Araióses","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ATmM8lY5RL5YMwmmWhmr", "Arame","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("3hwy5e8inmfQ98Bf3Po6", "Arari","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("bCkCrLAQedHPfei3564g", "Aurizona","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("jiy8ubDK84nKumkos2JA", "Axixá","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("SGWsTTtjN9yaTieMSISV", "Bacabal","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("5jI1CinwLnXlaiCoHkpr", "Bacabeira","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("pINwCXS2nfKiYvZKnD6w", "Bacatuba","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("C3DozaBzr8A47JrO2Yc3", "Bacuri","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("nTlDvGzzDHQo2WAQxxA1", "Bacurituba","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("SeIlnCUmfnpC8k4goBFQ", "Balsas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("2uFpDg2mIrl8nWHThzd7", "Barão de Grajaú","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("PzG4WmPZh1RevDsacPG9", "Barão de Tromai","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("NTWM0bVF65mAOvhlrpKo", "Barra do Corda","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("FqsP4SmxrRPwsnGpzNCq", "Barreirinhas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("CRvTD7moWeGBlEHBbFUL", "Barro Duro","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7IQ5YzNKd8Ec3T1RqwFh", "Bela Vista do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("z8Z0TwAZeP8sZVyEqOXC", "Belágua","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("erTSFZiIuaGbEN1WpXUK", "Benedito Leite","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7FQv9oBuCxAVztLEYZYu", "Bequimão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("yzzxRwdbQlKt8J4i6Wdp", "Bernardo do Mearim","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("SOVA9FSJnW8MVF40uvhC", "Boa Vista do Gurupi","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("OD4lWRzs3UrQ1xPysLmt", "Boa Vista do Pindaré","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Wloku077oWjt8JPndoWP", "Bom Jardim","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("PssitdXvpr9pVEUN3mcV", "Bom Jesus das Selvas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("NyCXPp4uBdqPb3X5QEfw", "Bom Lugar","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("iqejkjrDjYd5p24e5r1f", "Bonfim do Arari","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("mELWjIZcGm6f7ZtZtld6", "Brejo","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ttWPoITD7xhnynmimzcB", "Brejo de Areia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("pg3YCB481LQqq298aO75", "Brejo de São Félix","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("v3r8UEqzGKt5rNeRp0SR", "Buriti","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("GDV1nTfuf7dWLLm9guNX", "Buriti Bravo","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("lW8jilRyP8QpNB49uwo0", "Buriti Cortado","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ITiy0zr8Cc3cbYaah0mZ", "Buriticupu","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("kSXzTdr1QDueFANLr3Iq", "Buritirana","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("u4M0OYm9s5VcxLhaZGeX", "Cachoeira Grande","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("6nIhQPu1Ykhh4oa6rcGL", "Cajapió","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("HufpftB3CLTCBLd35Pow", "Cajari","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("uGTeroocY7otXtcwRIco", "Campestre do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("yitMKqK0eaYewwtYn7g5", "Cândido Mendes","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("moC1eVlVC9qZGNPV9hzV", "Cantanhede","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("wiKYLro4oapdCyaMLt88", "Capinzal do Norte","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("850Ve7TKtICYR3gjEp3D", "Caraíba do Norte","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("EPLn9jIqcZVzMUHlUSTn", "Carolina","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("RrxJl2uTagcSNmQZGLu6", "Carutapera","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("tP1H9ZiYVk51WcjDsEUr", "Caxias","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("tJdIkGrUfLMqEOiK1F5K", "Cedral","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Nb5vVy072XTMEffYNaez", "Central do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("16yLCqSdNYWG5LyvFORO", "Centro do Guilherme","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("IvQcwYH3Pwbad2ITlGlO", "Centro Novo do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("rwEDYwPUADmdUNhoUZu4", "Chapadinha","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("pYwff7WZw42CGsCu7wUR", "Cidelândia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("x3swuIKQ7bV8g20kKF2Z", "Codó","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("RGVrOVpLzgbEJ64MiAvu", "Codozinho","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Je0cBvljAouW2VwgFgKp", "Coelho Neto","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ixCF27G3qXKEVEMhK2jG", "Colinas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("O8V9s6uuLlPqjQJXUVFo", "Conceição do Lago-Açu","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("TTOYOqOxghRLE2wTf7XP", "Coroatá","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("z4hhggrzAdIkDHRoJFQZ", "Curupa","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("NMJsSTZvdYJfB6BFtUcx", "Cururupu","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("2RWxqYkQfvFBHYLVj7fS", "Curva Grande","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Qk5qM7Zuwu43TdX2mgn0", "Custódio Lima","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("sxGwdUpZH0orulvUBgeC", "Davinópolis","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("m2yXAe0fxZeqtK7ea8C1", "Dom Pedro","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("FIHFbpl05mdKVhoouLW0", "Duque Bacelar","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Revcwit0IYpnfpxtV5Mp", "Esperantinópolis","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ETQKKgeknkPugdsChbLn", "Estandarte","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("0ulsm9X5v86PPQiIOjNq", "Estreito","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("s7aYN4I6CwXAgrgy7318", "Feira Nova do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("D4X2PuQFkA5CrRaTqeQE", "Fernando Falcão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("bqMCLceoygUuP1HA5TSr", "Formosa da Serra Negra","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("1UgfEvfu3cMj7JhAP134", "Fortaleza dos Nogueiras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("SyP4NctiOTBzVTvJl8qm", "Fortuna","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Rq0HUkK9TeU1I90wTf5C", "Frecheiras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("b5A9h3YW90Mw0gK7vHUg", "Godofredo Viana","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("s0ebn7KDQan7WwQaRvtE", "Gonçalves Dias","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Abp7MzoXJIAEKHGKmg6B", "Governador Archer","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("SfoxWWFKPsVZmkay7Ulk", "Governador Edson Lobão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("uZ7AjfAkfebt9Q6tjL3w", "Governador Eugênio Barros","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("FyG94CQs5dTGpUbHE80R", "Governador Luiz Rocha","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ZeBb93fDTOQHy5eGjtts", "Governador Newton Bello","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("0Y9x3DktjUYpUKcOoACt", "Governador Nunes Freire","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("wixo8aKsrr8Soe9R1YgV", "Graça Aranha","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("GDVUKZX3jHD9rIq4Dbsn", "Grajaú","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("wuaDmJZzcrQ7zTb2JMK5", "Guimarães","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ok0ffkpQln8N4yadq3AA", "Humberto de Campos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("L2Mu6scrFHHtrZ8fJghJ", "Ibipira","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("e8GEsdgl27wWL2YiFKZG", "Icatu","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("jV0EEOVfwhFkLIiwxqCT", "Igarapé do Meio","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("82fJMbZyu1aHlCNhBYJz", "Igarapé Grande","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("z2aw9mrSnCWM2IJEdqG3", "Imperatriz","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("O1HH2keg7NL5DqzcEfKO", "Itaipava do Grajaú","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("a1Br1JU4lg8Yd1a0R1x8", "Itamataré","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("sF7XID8B3JRTdF9p7lVd", "Itapecuru Mirim","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("F5KnZLEHfrBxa5hoxlrh", "Itapera","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("LSuT2I0nUVZAQXQ6YFdU", "Itinga do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("pOx8buswz1ThUTrJYERI", "Jatobá","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("OSqOsB6S6yFSzRQZLAUc", "Jenipapo dos Vieiras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("zH9pPo4nuPftR8Ezymx0", "João Lisboa","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("sBjE07qRedjSOEOEvlSY", "Joselândia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("GA3bqRJaJqrlsgB279ma", "Junco do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("V3lbcJFmqH0Z9ral7exF", "Lago da Pedra","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("CcEIqvKcxZhDEvWTgYYA", "Lago do Junco","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("yBeiSRuCO0vQkhUV2iqI", "Lago dos Rodrigues","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("C9gWhcNvTEOpNdq70pe5", "Lago Verde","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("HXNcFx0UxafUb8f2KKHS", "Lagoa do Mato","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("o3wcNTwSE3m2S7H9C4xY", "Lagoa Grande do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("jWF8okqM7Joo4GyCfKG7", "Lajeado Novo","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("GSHks6YsYDexNEwUZ6R3", "Lapela","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("LuYtRvZaNS5F93KvV3O5", "Leandro","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("SPhCQkHkeb5mGHPhAPe5", "Lima Campos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("B3DXlSD2i5G6Nur1orN0", "Loreto","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("tt2SUMHm25XSFgaFKzwx", "Luís Domingues","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("CMoDtZdd1QERTdCsZpji", "Magalhães de Almeida","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("uBDWQC9a9t5VouqGRzVw", "Maioba","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MrLAAD0Dzas3Zc9o8LER", "Maracaçumé","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("j7SGX0ve0YwpbOtvNiHy", "Marajá do Sena","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("TLJNf8D3QDzoy9SkRk9v", "Maranhãozinho","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ngvdoTL9fkaxpjMcznWG", "Marianópolis","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("zP90vLa6BqaelSeRL1pm", "Mata","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("5MtZm2NfZADwCi6pjI7Q", "Mata Roma","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("1AmF5jEoCfdjLzTAbI2D", "Matinha","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("P6Gn2w2mthp6RCxkVdoD", "Matões","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("W9nwiZFlrL80xO6Uzzmp", "Matões do Norte","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("eSfxW2QToTydPHS45NRg", "Milagres do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("hE8zBmM7AwQP70iissY5", "Mirador","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("r7pRwMZppBYkxI90K0cZ", "Miranda do Norte","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7nWqAs6p6Sm87Z82ICJt", "Mirinzal","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("HTdLcpxmQ7das0UE6k4x", "Monção","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("uIa5DNopSLsUSKpneO2x", "Montes Altos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("OiKfhQDf8azcq0K3dnJx", "Morros","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("n4legrexmX4KpmxzBZyl", "Nina Rodrigues","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("nFgVswiW29aV3chvY7q5", "Nova Colinas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("USGrT7ll2rfcy2d9zPfK", "Nova Iorque","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("hzyKZ343VeMZHsu4RVDs", "Nova Olinda do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("2KHEj5Jx5zcNnpZKhXiq", "Olho D'Água das Cunhãs","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("sW8EMvKf1TaprMb9BRdr", "Olinda Nova do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("zKyXfTMUZ1V4goahz4VY", "Paço do Lumiar","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7o51tp6YvpbCTDHS0aDL", "Palmeirândia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("sS7ehnomOLHlYgMLDGTr", "Papagaio","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("EVgLRFZKieFyAgdmMS9F", "Paraibano","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("5SS6lJT6LNtLLfgL6KEt", "Parnarama","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("OOPdAFVT6nqvi8CZccNC", "Passagem Franca","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("6u1iGgQQe47Bdh8BNM0p", "Pastos Bons","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("0MISgQQXG0pkNFvNYzhe", "Paulino Neves","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("P9EHXjLS3nEpRiNo1QIc", "Paulo Ramos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MXiqzxbgiAw6pKfMzgev", "Pedreiras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Cgrr2uGofYKNLuvlVtR6", "Pedro do Rosário","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("dOegyU3UjraL5Gsy36eg", "Penalva","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("wVriuscVtx9EYk54UFCM", "Peri Mirim","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("exKTamTPZ61vlrR5mruV", "Peritoró","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Qm2cCaj8TvWKmGKmF4wA", "Pimentel","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("33cRo9nPLK7tO0DX9IJC", "Pindaré Mirim","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("mdJDJbSOEUPue2QnEaHi", "Pinheiro","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("unOkpDTimBSBv407SLvw", "Pio XII","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("bQuejjebiRFfiqs4FoCf", "Pirapemas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("EwjbeGERTG7Sw160KJW6", "Poção de Pedras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("3unhQ39aMOWIgxTm8zpZ", "Porto das Gabarras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7Kih5wS8sxMBmfRwVSLT", "Porto Franco","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("pzxz9PEdiNtzcKso3nsB", "Porto Rico do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Yz4DL44yCvceyx6yT6Ro", "Presidente Dutra","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MnGvDT20aqwUPJtHffxD", "Presidente Juscelino","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7nyIJbi4TMBMbSYTd1FL", "Presidente Médici","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("EQqRYiTc4n0HbevcUXss", "Presidente Sarney","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Y54dFgVNaVYOQmEfTJMJ", "Presidente Vargas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MG3gjD15gnsQbP34bNWt", "Primeira Cruz","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("JCfOKBVPPyjpcvOoxTMw", "Raposa","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Rckt9MZpD06ldIliygat", "Resplandes","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ZqZB6sJEVwEiBvc4rxUL", "Riachão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Waz5V3dYqQEkqkw1Z93x", "Ribamar Fiquene","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("K3Vl0ivvDbO9jhRJsqpG", "Ribeirão Azul","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("QBx0vwt4snYVqh3G4pFl", "Rocado","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("gda2enI488E5CYDYIMZU", "Roque","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("HCdXK28HRq4a5Dorz4m2", "Rosário","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("mNdwsfUKKhZse92GxKuV", "Sambaíba","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("RI5wEdKfDZW4dkf4c4VD", "Santa Filomena do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("KYeyMH5uV0L2V2e1soTF", "Santa Helena","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("7Z7wcryypVJPvX4tLUpW", "Santa Inês","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ntvZTqXT3nOAtYxHcSIE", "Santa Luzia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ynTY2lcLnWvqkZTqLGq4", "Santa Luzia do Paruá","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("cCTJ26cf4lDYmRPKSgqM", "Santa Quitéria do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("oXOa9sddmhOA7FDfchKO", "Santa Rita","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("lyglHZNxxqfbqwR31jnb", "Santana do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("aeCVyb4pGKFWPj3wuOz1", "Santo Amaro","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("opEk5AbntjG6EDL723Bf", "Santo Antônio dos Lopes","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ooom3AAYr6D88sL7hb5Z", "São Benedito do Rio Preto","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MVDcTmzsDxdaPNbZY5al", "São Bento","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("UHw6W6l9rdspiZr3j9sO", "São Bernardo","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("gYCKURel0GMaJsxlRARr", "São Domingos do Azeitão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("loRtyrE1cPg9Bhls9ryy", "São Domingos do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("y4TTwNYZvPSZL3Q7p6Af", "São Félix de Balsas","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("RdEDk6LI6gj6efBaRhjd", "São Francisco do Brejão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("5jwP2tHdvh9ZgHP2kVbL", "São Francisco do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("Wsdh2afKhZaL6leuE4Ci", "São João Batista","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("FBCDJ9o3zJ2O7nhg5c0x", "São João de Cortes","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("S7duZjTekuXKhSZYQKBA", "São João do Carú","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("UbasHcZQUB6BwHNEb0r7", "São João do Paraíso","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("y0WwwsZ5Xfe8H7BuIV1f", "São João do Sóter","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("p94vULWgXZn2Av9YEWC3", "São João dos Patos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("42nqX2ItgsAeG7hyhGW4", "São Joaquim dos Melos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("tu0PKzLwZYlChJIGBQkq", "São José de Ribamar","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ryarHi8vNG4qIdgBzEoH", "São José dos Basílios","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("29fRn6YlbUUwT2R9Xwp7", "São Luís","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("HtUKTH0k5OgvHqkUm4si", "São Luís Gonzaga do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("mpReJeKqFOSPZlJ3HztD", "São Mateus do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("P0mRxnx3YIfNZ5dJxKFb", "São Pedro da Água Branca","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("x7cStWfQvS9w9hGyofnx", "São Pedro dos Crentes","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("mqFWZju2xnEIvvpcQQ27", "São Raimundo das Mangabeiras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("tifC1FKiU6jCDeS1tTTD", "São Raimundo de Codó","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("b7yNLwvAOKa8S3OQiKHs", "São Raimundo do Doca Bezerra","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("oxda9es4kViDFpVW0lCe", "São Roberto","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("gGrUbu9vcjHh6w6OhpGd", "São Vicente Ferrer","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("eStqafLtBnK5bCQKbsKg", "Satubinha","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("v3odZOplx6FakBA50H80", "Senador Alexandre Costa","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("AG7FAjH4BfIUHSjAF2iq", "Senador La Rocque","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("ah8gcQC6zwXrzVTHQpni", "Serrano do Maranhão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("39muUM0ZfEIusNHS26m6", "Sítio Novo","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("zkWsjRm1tE0IKYw4sL3n", "Sucupira do Norte","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("03kB6OO8YQHCnyP1K2Ql", "Sucupira do Riachão","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("eIgL1ANkpCpCClEKj2PB", "Tasso Fragoso","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("vwX1lBXgVWHgBVcXX33n", "Timbiras","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("guGmYChHpETx2BRdS9Ev", "Timon","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("VWjgmtgfTgfNFxuH5fED", "Trizidela do Vale","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("6ME147y0paWMwHo59eOP", "Tufilândia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("3ZQuEVT6ShpnJJKdAaAf", "Tuntum","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("RuWIHPIU3hcW095lXpms", "Turiaçu","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("kxb8LtMktEs9pY4bb9Tc", "Turilândia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("W1XqFNLKUhhpdbNQS4iC", "Tutóia","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("iNJZXb06zpfRwDBrhncM", "Urbano Santos","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("g5EumbxYZ5IZ9ppyCZTH", "Vargem Grande","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("uvDvfiQvB4uGDisd18ab", "Viana","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("M5q7d1Veeq3ZhPeVfTr2", "Vila Nova dos Martírios","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("MBQrzxvmEF7mMW3MFWKN", "Vitória do Mearim","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("3CqIlTwnb0OMS647iWAj", "Vitorino Freire","pHJjtnzuXeDQ7bqmJItp", "MA"));
        lista.add(new Cidade("5rLeNOUoUlmuVkKsqz6J", "Zé Doca","pHJjtnzuXeDQ7bqmJItp", "MA"));

        return lista;
    }
}
