package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("btXLim5xbr2mUKw53G2Q", "Açailândia", "MA"));
        lista.add(new Cidade("KHPvXQ0Ym0443Qyk6rYV", "Afonso Cunha", "MA"));
        lista.add(new Cidade("Y6qdEDcdET4iVv4O1XZK", "Água Doce do Maranhão", "MA"));
        lista.add(new Cidade("bHldHYrBiNUjGtqZ3gvX", "Alcântara", "MA"));
        lista.add(new Cidade("IebBSBnSjw6R0zqZKOm6", "Aldeias Altas", "MA"));
        lista.add(new Cidade("eGvFy51W4EIlREmYPhMx", "Altamira do Maranhão", "MA"));
        lista.add(new Cidade("aqCygdLIvgTwLAGPY0Eb", "Alto Alegre do Maranhão", "MA"));
        lista.add(new Cidade("fW7ysCCEptL6Tpnwwvph", "Alto Alegre do Pindaré", "MA"));
        lista.add(new Cidade("1t25HUtpYoSSWTQ2RaiG", "Alto Parnaíba", "MA"));
        lista.add(new Cidade("OJ4sCDgClG2KzML2aiAh", "Amapá do Maranhão", "MA"));
        lista.add(new Cidade("zSwCOwL24jsNaaJdKjs5", "Amarante do Maranhão", "MA"));
        lista.add(new Cidade("FM46DRcaggKmWWKNHBWk", "Anajatuba", "MA"));
        lista.add(new Cidade("u9vuuc1MiQHKTL8kKkhP", "Anapurus", "MA"));
        lista.add(new Cidade("MulAZRrQ07yEbZEqqzmT", "Anil", "MA"));
        lista.add(new Cidade("fSgsPSkenSIiMGH0AaOb", "Apicum-Açu", "MA"));
        lista.add(new Cidade("IIy8kEXQBwJz0qmyt5Rk", "Araguanã", "MA"));
        lista.add(new Cidade("UWx9zQbh1zNleOe6tUdB", "Araióses", "MA"));
        lista.add(new Cidade("ATmM8lY5RL5YMwmmWhmr", "Arame", "MA"));
        lista.add(new Cidade("3hwy5e8inmfQ98Bf3Po6", "Arari", "MA"));
        lista.add(new Cidade("bCkCrLAQedHPfei3564g", "Aurizona", "MA"));
        lista.add(new Cidade("jiy8ubDK84nKumkos2JA", "Axixá", "MA"));
        lista.add(new Cidade("SGWsTTtjN9yaTieMSISV", "Bacabal", "MA"));
        lista.add(new Cidade("5jI1CinwLnXlaiCoHkpr", "Bacabeira", "MA"));
        lista.add(new Cidade("pINwCXS2nfKiYvZKnD6w", "Bacatuba", "MA"));
        lista.add(new Cidade("C3DozaBzr8A47JrO2Yc3", "Bacuri", "MA"));
        lista.add(new Cidade("nTlDvGzzDHQo2WAQxxA1", "Bacurituba", "MA"));
        lista.add(new Cidade("SeIlnCUmfnpC8k4goBFQ", "Balsas", "MA"));
        lista.add(new Cidade("2uFpDg2mIrl8nWHThzd7", "Barão de Grajaú", "MA"));
        lista.add(new Cidade("PzG4WmPZh1RevDsacPG9", "Barão de Tromai", "MA"));
        lista.add(new Cidade("NTWM0bVF65mAOvhlrpKo", "Barra do Corda", "MA"));
        lista.add(new Cidade("FqsP4SmxrRPwsnGpzNCq", "Barreirinhas", "MA"));
        lista.add(new Cidade("CRvTD7moWeGBlEHBbFUL", "Barro Duro", "MA"));
        lista.add(new Cidade("7IQ5YzNKd8Ec3T1RqwFh", "Bela Vista do Maranhão", "MA"));
        lista.add(new Cidade("z8Z0TwAZeP8sZVyEqOXC", "Belágua", "MA"));
        lista.add(new Cidade("erTSFZiIuaGbEN1WpXUK", "Benedito Leite", "MA"));
        lista.add(new Cidade("7FQv9oBuCxAVztLEYZYu", "Bequimão", "MA"));
        lista.add(new Cidade("yzzxRwdbQlKt8J4i6Wdp", "Bernardo do Mearim", "MA"));
        lista.add(new Cidade("SOVA9FSJnW8MVF40uvhC", "Boa Vista do Gurupi", "MA"));
        lista.add(new Cidade("OD4lWRzs3UrQ1xPysLmt", "Boa Vista do Pindaré", "MA"));
        lista.add(new Cidade("Wloku077oWjt8JPndoWP", "Bom Jardim", "MA"));
        lista.add(new Cidade("PssitdXvpr9pVEUN3mcV", "Bom Jesus das Selvas", "MA"));
        lista.add(new Cidade("NyCXPp4uBdqPb3X5QEfw", "Bom Lugar", "MA"));
        lista.add(new Cidade("iqejkjrDjYd5p24e5r1f", "Bonfim do Arari", "MA"));
        lista.add(new Cidade("mELWjIZcGm6f7ZtZtld6", "Brejo", "MA"));
        lista.add(new Cidade("ttWPoITD7xhnynmimzcB", "Brejo de Areia", "MA"));
        lista.add(new Cidade("pg3YCB481LQqq298aO75", "Brejo de São Félix", "MA"));
        lista.add(new Cidade("v3r8UEqzGKt5rNeRp0SR", "Buriti", "MA"));
        lista.add(new Cidade("GDV1nTfuf7dWLLm9guNX", "Buriti Bravo", "MA"));
        lista.add(new Cidade("lW8jilRyP8QpNB49uwo0", "Buriti Cortado", "MA"));
        lista.add(new Cidade("ITiy0zr8Cc3cbYaah0mZ", "Buriticupu", "MA"));
        lista.add(new Cidade("kSXzTdr1QDueFANLr3Iq", "Buritirana", "MA"));
        lista.add(new Cidade("u4M0OYm9s5VcxLhaZGeX", "Cachoeira Grande", "MA"));
        lista.add(new Cidade("6nIhQPu1Ykhh4oa6rcGL", "Cajapió", "MA"));
        lista.add(new Cidade("HufpftB3CLTCBLd35Pow", "Cajari", "MA"));
        lista.add(new Cidade("uGTeroocY7otXtcwRIco", "Campestre do Maranhão", "MA"));
        lista.add(new Cidade("yitMKqK0eaYewwtYn7g5", "Cândido Mendes", "MA"));
        lista.add(new Cidade("moC1eVlVC9qZGNPV9hzV", "Cantanhede", "MA"));
        lista.add(new Cidade("wiKYLro4oapdCyaMLt88", "Capinzal do Norte", "MA"));
        lista.add(new Cidade("850Ve7TKtICYR3gjEp3D", "Caraíba do Norte", "MA"));
        lista.add(new Cidade("EPLn9jIqcZVzMUHlUSTn", "Carolina", "MA"));
        lista.add(new Cidade("RrxJl2uTagcSNmQZGLu6", "Carutapera", "MA"));
        lista.add(new Cidade("tP1H9ZiYVk51WcjDsEUr", "Caxias", "MA"));
        lista.add(new Cidade("tJdIkGrUfLMqEOiK1F5K", "Cedral", "MA"));
        lista.add(new Cidade("Nb5vVy072XTMEffYNaez", "Central do Maranhão", "MA"));
        lista.add(new Cidade("16yLCqSdNYWG5LyvFORO", "Centro do Guilherme", "MA"));
        lista.add(new Cidade("IvQcwYH3Pwbad2ITlGlO", "Centro Novo do Maranhão", "MA"));
        lista.add(new Cidade("rwEDYwPUADmdUNhoUZu4", "Chapadinha", "MA"));
        lista.add(new Cidade("pYwff7WZw42CGsCu7wUR", "Cidelândia", "MA"));
        lista.add(new Cidade("x3swuIKQ7bV8g20kKF2Z", "Codó", "MA"));
        lista.add(new Cidade("RGVrOVpLzgbEJ64MiAvu", "Codozinho", "MA"));
        lista.add(new Cidade("Je0cBvljAouW2VwgFgKp", "Coelho Neto", "MA"));
        lista.add(new Cidade("ixCF27G3qXKEVEMhK2jG", "Colinas", "MA"));
        lista.add(new Cidade("O8V9s6uuLlPqjQJXUVFo", "Conceição do Lago-Açu", "MA"));
        lista.add(new Cidade("TTOYOqOxghRLE2wTf7XP", "Coroatá", "MA"));
        lista.add(new Cidade("z4hhggrzAdIkDHRoJFQZ", "Curupa", "MA"));
        lista.add(new Cidade("NMJsSTZvdYJfB6BFtUcx", "Cururupu", "MA"));
        lista.add(new Cidade("2RWxqYkQfvFBHYLVj7fS", "Curva Grande", "MA"));
        lista.add(new Cidade("Qk5qM7Zuwu43TdX2mgn0", "Custódio Lima", "MA"));
        lista.add(new Cidade("sxGwdUpZH0orulvUBgeC", "Davinópolis", "MA"));
        lista.add(new Cidade("m2yXAe0fxZeqtK7ea8C1", "Dom Pedro", "MA"));
        lista.add(new Cidade("FIHFbpl05mdKVhoouLW0", "Duque Bacelar", "MA"));
        lista.add(new Cidade("Revcwit0IYpnfpxtV5Mp", "Esperantinópolis", "MA"));
        lista.add(new Cidade("ETQKKgeknkPugdsChbLn", "Estandarte", "MA"));
        lista.add(new Cidade("0ulsm9X5v86PPQiIOjNq", "Estreito", "MA"));
        lista.add(new Cidade("s7aYN4I6CwXAgrgy7318", "Feira Nova do Maranhão", "MA"));
        lista.add(new Cidade("D4X2PuQFkA5CrRaTqeQE", "Fernando Falcão", "MA"));
        lista.add(new Cidade("bqMCLceoygUuP1HA5TSr", "Formosa da Serra Negra", "MA"));
        lista.add(new Cidade("1UgfEvfu3cMj7JhAP134", "Fortaleza dos Nogueiras", "MA"));
        lista.add(new Cidade("SyP4NctiOTBzVTvJl8qm", "Fortuna", "MA"));
        lista.add(new Cidade("Rq0HUkK9TeU1I90wTf5C", "Frecheiras", "MA"));
        lista.add(new Cidade("b5A9h3YW90Mw0gK7vHUg", "Godofredo Viana", "MA"));
        lista.add(new Cidade("s0ebn7KDQan7WwQaRvtE", "Gonçalves Dias", "MA"));
        lista.add(new Cidade("Abp7MzoXJIAEKHGKmg6B", "Governador Archer", "MA"));
        lista.add(new Cidade("SfoxWWFKPsVZmkay7Ulk", "Governador Edson Lobão", "MA"));
        lista.add(new Cidade("uZ7AjfAkfebt9Q6tjL3w", "Governador Eugênio Barros", "MA"));
        lista.add(new Cidade("FyG94CQs5dTGpUbHE80R", "Governador Luiz Rocha", "MA"));
        lista.add(new Cidade("ZeBb93fDTOQHy5eGjtts", "Governador Newton Bello", "MA"));
        lista.add(new Cidade("0Y9x3DktjUYpUKcOoACt", "Governador Nunes Freire", "MA"));
        lista.add(new Cidade("wixo8aKsrr8Soe9R1YgV", "Graça Aranha", "MA"));
        lista.add(new Cidade("GDVUKZX3jHD9rIq4Dbsn", "Grajaú", "MA"));
        lista.add(new Cidade("wuaDmJZzcrQ7zTb2JMK5", "Guimarães", "MA"));
        lista.add(new Cidade("ok0ffkpQln8N4yadq3AA", "Humberto de Campos", "MA"));
        lista.add(new Cidade("L2Mu6scrFHHtrZ8fJghJ", "Ibipira", "MA"));
        lista.add(new Cidade("e8GEsdgl27wWL2YiFKZG", "Icatu", "MA"));
        lista.add(new Cidade("jV0EEOVfwhFkLIiwxqCT", "Igarapé do Meio", "MA"));
        lista.add(new Cidade("82fJMbZyu1aHlCNhBYJz", "Igarapé Grande", "MA"));
        lista.add(new Cidade("z2aw9mrSnCWM2IJEdqG3", "Imperatriz", "MA"));
        lista.add(new Cidade("O1HH2keg7NL5DqzcEfKO", "Itaipava do Grajaú", "MA"));
        lista.add(new Cidade("a1Br1JU4lg8Yd1a0R1x8", "Itamataré", "MA"));
        lista.add(new Cidade("sF7XID8B3JRTdF9p7lVd", "Itapecuru Mirim", "MA"));
        lista.add(new Cidade("F5KnZLEHfrBxa5hoxlrh", "Itapera", "MA"));
        lista.add(new Cidade("LSuT2I0nUVZAQXQ6YFdU", "Itinga do Maranhão", "MA"));
        lista.add(new Cidade("pOx8buswz1ThUTrJYERI", "Jatobá", "MA"));
        lista.add(new Cidade("OSqOsB6S6yFSzRQZLAUc", "Jenipapo dos Vieiras", "MA"));
        lista.add(new Cidade("zH9pPo4nuPftR8Ezymx0", "João Lisboa", "MA"));
        lista.add(new Cidade("sBjE07qRedjSOEOEvlSY", "Joselândia", "MA"));
        lista.add(new Cidade("GA3bqRJaJqrlsgB279ma", "Junco do Maranhão", "MA"));
        lista.add(new Cidade("V3lbcJFmqH0Z9ral7exF", "Lago da Pedra", "MA"));
        lista.add(new Cidade("CcEIqvKcxZhDEvWTgYYA", "Lago do Junco", "MA"));
        lista.add(new Cidade("yBeiSRuCO0vQkhUV2iqI", "Lago dos Rodrigues", "MA"));
        lista.add(new Cidade("C9gWhcNvTEOpNdq70pe5", "Lago Verde", "MA"));
        lista.add(new Cidade("HXNcFx0UxafUb8f2KKHS", "Lagoa do Mato", "MA"));
        lista.add(new Cidade("o3wcNTwSE3m2S7H9C4xY", "Lagoa Grande do Maranhão", "MA"));
        lista.add(new Cidade("jWF8okqM7Joo4GyCfKG7", "Lajeado Novo", "MA"));
        lista.add(new Cidade("GSHks6YsYDexNEwUZ6R3", "Lapela", "MA"));
        lista.add(new Cidade("LuYtRvZaNS5F93KvV3O5", "Leandro", "MA"));
        lista.add(new Cidade("SPhCQkHkeb5mGHPhAPe5", "Lima Campos", "MA"));
        lista.add(new Cidade("B3DXlSD2i5G6Nur1orN0", "Loreto", "MA"));
        lista.add(new Cidade("tt2SUMHm25XSFgaFKzwx", "Luís Domingues", "MA"));
        lista.add(new Cidade("CMoDtZdd1QERTdCsZpji", "Magalhães de Almeida", "MA"));
        lista.add(new Cidade("uBDWQC9a9t5VouqGRzVw", "Maioba", "MA"));
        lista.add(new Cidade("MrLAAD0Dzas3Zc9o8LER", "Maracaçumé", "MA"));
        lista.add(new Cidade("j7SGX0ve0YwpbOtvNiHy", "Marajá do Sena", "MA"));
        lista.add(new Cidade("TLJNf8D3QDzoy9SkRk9v", "Maranhãozinho", "MA"));
        lista.add(new Cidade("ngvdoTL9fkaxpjMcznWG", "Marianópolis", "MA"));
        lista.add(new Cidade("zP90vLa6BqaelSeRL1pm", "Mata", "MA"));
        lista.add(new Cidade("5MtZm2NfZADwCi6pjI7Q", "Mata Roma", "MA"));
        lista.add(new Cidade("1AmF5jEoCfdjLzTAbI2D", "Matinha", "MA"));
        lista.add(new Cidade("P6Gn2w2mthp6RCxkVdoD", "Matões", "MA"));
        lista.add(new Cidade("W9nwiZFlrL80xO6Uzzmp", "Matões do Norte", "MA"));
        lista.add(new Cidade("eSfxW2QToTydPHS45NRg", "Milagres do Maranhão", "MA"));
        lista.add(new Cidade("hE8zBmM7AwQP70iissY5", "Mirador", "MA"));
        lista.add(new Cidade("r7pRwMZppBYkxI90K0cZ", "Miranda do Norte", "MA"));
        lista.add(new Cidade("7nWqAs6p6Sm87Z82ICJt", "Mirinzal", "MA"));
        lista.add(new Cidade("HTdLcpxmQ7das0UE6k4x", "Monção", "MA"));
        lista.add(new Cidade("uIa5DNopSLsUSKpneO2x", "Montes Altos", "MA"));
        lista.add(new Cidade("OiKfhQDf8azcq0K3dnJx", "Morros", "MA"));
        lista.add(new Cidade("n4legrexmX4KpmxzBZyl", "Nina Rodrigues", "MA"));
        lista.add(new Cidade("nFgVswiW29aV3chvY7q5", "Nova Colinas", "MA"));
        lista.add(new Cidade("USGrT7ll2rfcy2d9zPfK", "Nova Iorque", "MA"));
        lista.add(new Cidade("hzyKZ343VeMZHsu4RVDs", "Nova Olinda do Maranhão", "MA"));
        lista.add(new Cidade("2KHEj5Jx5zcNnpZKhXiq", "Olho D'Água das Cunhãs", "MA"));
        lista.add(new Cidade("sW8EMvKf1TaprMb9BRdr", "Olinda Nova do Maranhão", "MA"));
        lista.add(new Cidade("zKyXfTMUZ1V4goahz4VY", "Paço do Lumiar", "MA"));
        lista.add(new Cidade("7o51tp6YvpbCTDHS0aDL", "Palmeirândia", "MA"));
        lista.add(new Cidade("sS7ehnomOLHlYgMLDGTr", "Papagaio", "MA"));
        lista.add(new Cidade("EVgLRFZKieFyAgdmMS9F", "Paraibano", "MA"));
        lista.add(new Cidade("5SS6lJT6LNtLLfgL6KEt", "Parnarama", "MA"));
        lista.add(new Cidade("OOPdAFVT6nqvi8CZccNC", "Passagem Franca", "MA"));
        lista.add(new Cidade("6u1iGgQQe47Bdh8BNM0p", "Pastos Bons", "MA"));
        lista.add(new Cidade("0MISgQQXG0pkNFvNYzhe", "Paulino Neves", "MA"));
        lista.add(new Cidade("P9EHXjLS3nEpRiNo1QIc", "Paulo Ramos", "MA"));
        lista.add(new Cidade("MXiqzxbgiAw6pKfMzgev", "Pedreiras", "MA"));
        lista.add(new Cidade("Cgrr2uGofYKNLuvlVtR6", "Pedro do Rosário", "MA"));
        lista.add(new Cidade("dOegyU3UjraL5Gsy36eg", "Penalva", "MA"));
        lista.add(new Cidade("wVriuscVtx9EYk54UFCM", "Peri Mirim", "MA"));
        lista.add(new Cidade("exKTamTPZ61vlrR5mruV", "Peritoró", "MA"));
        lista.add(new Cidade("Qm2cCaj8TvWKmGKmF4wA", "Pimentel", "MA"));
        lista.add(new Cidade("33cRo9nPLK7tO0DX9IJC", "Pindaré Mirim", "MA"));
        lista.add(new Cidade("mdJDJbSOEUPue2QnEaHi", "Pinheiro", "MA"));
        lista.add(new Cidade("unOkpDTimBSBv407SLvw", "Pio XII", "MA"));
        lista.add(new Cidade("bQuejjebiRFfiqs4FoCf", "Pirapemas", "MA"));
        lista.add(new Cidade("EwjbeGERTG7Sw160KJW6", "Poção de Pedras", "MA"));
        lista.add(new Cidade("3unhQ39aMOWIgxTm8zpZ", "Porto das Gabarras", "MA"));
        lista.add(new Cidade("7Kih5wS8sxMBmfRwVSLT", "Porto Franco", "MA"));
        lista.add(new Cidade("pzxz9PEdiNtzcKso3nsB", "Porto Rico do Maranhão", "MA"));
        lista.add(new Cidade("Yz4DL44yCvceyx6yT6Ro", "Presidente Dutra", "MA"));
        lista.add(new Cidade("MnGvDT20aqwUPJtHffxD", "Presidente Juscelino", "MA"));
        lista.add(new Cidade("7nyIJbi4TMBMbSYTd1FL", "Presidente Médici", "MA"));
        lista.add(new Cidade("EQqRYiTc4n0HbevcUXss", "Presidente Sarney", "MA"));
        lista.add(new Cidade("Y54dFgVNaVYOQmEfTJMJ", "Presidente Vargas", "MA"));
        lista.add(new Cidade("MG3gjD15gnsQbP34bNWt", "Primeira Cruz", "MA"));
        lista.add(new Cidade("JCfOKBVPPyjpcvOoxTMw", "Raposa", "MA"));
        lista.add(new Cidade("Rckt9MZpD06ldIliygat", "Resplandes", "MA"));
        lista.add(new Cidade("ZqZB6sJEVwEiBvc4rxUL", "Riachão", "MA"));
        lista.add(new Cidade("Waz5V3dYqQEkqkw1Z93x", "Ribamar Fiquene", "MA"));
        lista.add(new Cidade("K3Vl0ivvDbO9jhRJsqpG", "Ribeirão Azul", "MA"));
        lista.add(new Cidade("QBx0vwt4snYVqh3G4pFl", "Rocado", "MA"));
        lista.add(new Cidade("gda2enI488E5CYDYIMZU", "Roque", "MA"));
        lista.add(new Cidade("HCdXK28HRq4a5Dorz4m2", "Rosário", "MA"));
        lista.add(new Cidade("mNdwsfUKKhZse92GxKuV", "Sambaíba", "MA"));
        lista.add(new Cidade("RI5wEdKfDZW4dkf4c4VD", "Santa Filomena do Maranhão", "MA"));
        lista.add(new Cidade("KYeyMH5uV0L2V2e1soTF", "Santa Helena", "MA"));
        lista.add(new Cidade("7Z7wcryypVJPvX4tLUpW", "Santa Inês", "MA"));
        lista.add(new Cidade("ntvZTqXT3nOAtYxHcSIE", "Santa Luzia", "MA"));
        lista.add(new Cidade("ynTY2lcLnWvqkZTqLGq4", "Santa Luzia do Paruá", "MA"));
        lista.add(new Cidade("cCTJ26cf4lDYmRPKSgqM", "Santa Quitéria do Maranhão", "MA"));
        lista.add(new Cidade("oXOa9sddmhOA7FDfchKO", "Santa Rita", "MA"));
        lista.add(new Cidade("lyglHZNxxqfbqwR31jnb", "Santana do Maranhão", "MA"));
        lista.add(new Cidade("aeCVyb4pGKFWPj3wuOz1", "Santo Amaro", "MA"));
        lista.add(new Cidade("opEk5AbntjG6EDL723Bf", "Santo Antônio dos Lopes", "MA"));
        lista.add(new Cidade("ooom3AAYr6D88sL7hb5Z", "São Benedito do Rio Preto", "MA"));
        lista.add(new Cidade("MVDcTmzsDxdaPNbZY5al", "São Bento", "MA"));
        lista.add(new Cidade("UHw6W6l9rdspiZr3j9sO", "São Bernardo", "MA"));
        lista.add(new Cidade("gYCKURel0GMaJsxlRARr", "São Domingos do Azeitão", "MA"));
        lista.add(new Cidade("loRtyrE1cPg9Bhls9ryy", "São Domingos do Maranhão", "MA"));
        lista.add(new Cidade("y4TTwNYZvPSZL3Q7p6Af", "São Félix de Balsas", "MA"));
        lista.add(new Cidade("RdEDk6LI6gj6efBaRhjd", "São Francisco do Brejão", "MA"));
        lista.add(new Cidade("5jwP2tHdvh9ZgHP2kVbL", "São Francisco do Maranhão", "MA"));
        lista.add(new Cidade("Wsdh2afKhZaL6leuE4Ci", "São João Batista", "MA"));
        lista.add(new Cidade("FBCDJ9o3zJ2O7nhg5c0x", "São João de Cortes", "MA"));
        lista.add(new Cidade("S7duZjTekuXKhSZYQKBA", "São João do Carú", "MA"));
        lista.add(new Cidade("UbasHcZQUB6BwHNEb0r7", "São João do Paraíso", "MA"));
        lista.add(new Cidade("y0WwwsZ5Xfe8H7BuIV1f", "São João do Sóter", "MA"));
        lista.add(new Cidade("p94vULWgXZn2Av9YEWC3", "São João dos Patos", "MA"));
        lista.add(new Cidade("42nqX2ItgsAeG7hyhGW4", "São Joaquim dos Melos", "MA"));
        lista.add(new Cidade("tu0PKzLwZYlChJIGBQkq", "São José de Ribamar", "MA"));
        lista.add(new Cidade("ryarHi8vNG4qIdgBzEoH", "São José dos Basílios", "MA"));
        lista.add(new Cidade("29fRn6YlbUUwT2R9Xwp7", "São Luís", "MA"));
        lista.add(new Cidade("HtUKTH0k5OgvHqkUm4si", "São Luís Gonzaga do Maranhão", "MA"));
        lista.add(new Cidade("mpReJeKqFOSPZlJ3HztD", "São Mateus do Maranhão", "MA"));
        lista.add(new Cidade("P0mRxnx3YIfNZ5dJxKFb", "São Pedro da Água Branca", "MA"));
        lista.add(new Cidade("x7cStWfQvS9w9hGyofnx", "São Pedro dos Crentes", "MA"));
        lista.add(new Cidade("mqFWZju2xnEIvvpcQQ27", "São Raimundo das Mangabeiras", "MA"));
        lista.add(new Cidade("tifC1FKiU6jCDeS1tTTD", "São Raimundo de Codó", "MA"));
        lista.add(new Cidade("b7yNLwvAOKa8S3OQiKHs", "São Raimundo do Doca Bezerra", "MA"));
        lista.add(new Cidade("oxda9es4kViDFpVW0lCe", "São Roberto", "MA"));
        lista.add(new Cidade("gGrUbu9vcjHh6w6OhpGd", "São Vicente Ferrer", "MA"));
        lista.add(new Cidade("eStqafLtBnK5bCQKbsKg", "Satubinha", "MA"));
        lista.add(new Cidade("v3odZOplx6FakBA50H80", "Senador Alexandre Costa", "MA"));
        lista.add(new Cidade("AG7FAjH4BfIUHSjAF2iq", "Senador La Rocque", "MA"));
        lista.add(new Cidade("ah8gcQC6zwXrzVTHQpni", "Serrano do Maranhão", "MA"));
        lista.add(new Cidade("39muUM0ZfEIusNHS26m6", "Sítio Novo", "MA"));
        lista.add(new Cidade("zkWsjRm1tE0IKYw4sL3n", "Sucupira do Norte", "MA"));
        lista.add(new Cidade("03kB6OO8YQHCnyP1K2Ql", "Sucupira do Riachão", "MA"));
        lista.add(new Cidade("eIgL1ANkpCpCClEKj2PB", "Tasso Fragoso", "MA"));
        lista.add(new Cidade("vwX1lBXgVWHgBVcXX33n", "Timbiras", "MA"));
        lista.add(new Cidade("guGmYChHpETx2BRdS9Ev", "Timon", "MA"));
        lista.add(new Cidade("VWjgmtgfTgfNFxuH5fED", "Trizidela do Vale", "MA"));
        lista.add(new Cidade("6ME147y0paWMwHo59eOP", "Tufilândia", "MA"));
        lista.add(new Cidade("3ZQuEVT6ShpnJJKdAaAf", "Tuntum", "MA"));
        lista.add(new Cidade("RuWIHPIU3hcW095lXpms", "Turiaçu", "MA"));
        lista.add(new Cidade("kxb8LtMktEs9pY4bb9Tc", "Turilândia", "MA"));
        lista.add(new Cidade("W1XqFNLKUhhpdbNQS4iC", "Tutóia", "MA"));
        lista.add(new Cidade("iNJZXb06zpfRwDBrhncM", "Urbano Santos", "MA"));
        lista.add(new Cidade("g5EumbxYZ5IZ9ppyCZTH", "Vargem Grande", "MA"));
        lista.add(new Cidade("uvDvfiQvB4uGDisd18ab", "Viana", "MA"));
        lista.add(new Cidade("M5q7d1Veeq3ZhPeVfTr2", "Vila Nova dos Martírios", "MA"));
        lista.add(new Cidade("MBQrzxvmEF7mMW3MFWKN", "Vitória do Mearim", "MA"));
        lista.add(new Cidade("3CqIlTwnb0OMS647iWAj", "Vitorino Freire", "MA"));
        lista.add(new Cidade("5rLeNOUoUlmuVkKsqz6J", "Zé Doca", "MA"));

        return lista;
    }
}
