package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Açailândia", "MA"));
        lista.add(new Cidade("", "Afonso Cunha", "MA"));
        lista.add(new Cidade("", "Água Doce do Maranhão", "MA"));
        lista.add(new Cidade("", "Alcântara", "MA"));
        lista.add(new Cidade("", "Aldeias Altas", "MA"));
        lista.add(new Cidade("", "Altamira do Maranhão", "MA"));
        lista.add(new Cidade("", "Alto Alegre do Maranhão", "MA"));
        lista.add(new Cidade("", "Alto Alegre do Pindaré", "MA"));
        lista.add(new Cidade("", "Alto Parnaíba", "MA"));
        lista.add(new Cidade("", "Amapá do Maranhão", "MA"));
        lista.add(new Cidade("", "Amarante do Maranhão", "MA"));
        lista.add(new Cidade("", "Anajatuba", "MA"));
        lista.add(new Cidade("", "Anapurus", "MA"));
        lista.add(new Cidade("", "Anil", "MA"));
        lista.add(new Cidade("", "Apicum-Açu", "MA"));
        lista.add(new Cidade("", "Araguanã", "MA"));
        lista.add(new Cidade("", "Araióses", "MA"));
        lista.add(new Cidade("", "Arame", "MA"));
        lista.add(new Cidade("", "Arari", "MA"));
        lista.add(new Cidade("", "Aurizona", "MA"));
        lista.add(new Cidade("", "Axixá", "MA"));
        lista.add(new Cidade("", "Bacabal", "MA"));
        lista.add(new Cidade("", "Bacabeira", "MA"));
        lista.add(new Cidade("", "Bacatuba", "MA"));
        lista.add(new Cidade("", "Bacuri", "MA"));
        lista.add(new Cidade("", "Bacurituba", "MA"));
        lista.add(new Cidade("", "Balsas", "MA"));
        lista.add(new Cidade("", "Barão de Grajaú", "MA"));
        lista.add(new Cidade("", "Barão de Tromai", "MA"));
        lista.add(new Cidade("", "Barra do Corda", "MA"));
        lista.add(new Cidade("", "Barreirinhas", "MA"));
        lista.add(new Cidade("", "Barro Duro", "MA"));
        lista.add(new Cidade("", "Bela Vista do Maranhão", "MA"));
        lista.add(new Cidade("", "Belágua", "MA"));
        lista.add(new Cidade("", "Benedito Leite", "MA"));
        lista.add(new Cidade("", "Bequimão", "MA"));
        lista.add(new Cidade("", "Bernardo do Mearim", "MA"));
        lista.add(new Cidade("", "Boa Vista do Gurupi", "MA"));
        lista.add(new Cidade("", "Boa Vista do Pindaré", "MA"));
        lista.add(new Cidade("", "Bom Jardim", "MA"));
        lista.add(new Cidade("", "Bom Jesus das Selvas", "MA"));
        lista.add(new Cidade("", "Bom Lugar", "MA"));
        lista.add(new Cidade("", "Bonfim do Arari", "MA"));
        lista.add(new Cidade("", "Brejo", "MA"));
        lista.add(new Cidade("", "Brejo de Areia", "MA"));
        lista.add(new Cidade("", "Brejo de São Félix", "MA"));
        lista.add(new Cidade("", "Buriti", "MA"));
        lista.add(new Cidade("", "Buriti Bravo", "MA"));
        lista.add(new Cidade("", "Buriti Cortado", "MA"));
        lista.add(new Cidade("", "Buriticupu", "MA"));
        lista.add(new Cidade("", "Buritirana", "MA"));
        lista.add(new Cidade("", "Cachoeira Grande", "MA"));
        lista.add(new Cidade("", "Cajapió", "MA"));
        lista.add(new Cidade("", "Cajari", "MA"));
        lista.add(new Cidade("", "Campestre do Maranhão", "MA"));
        lista.add(new Cidade("", "Cândido Mendes", "MA"));
        lista.add(new Cidade("", "Cantanhede", "MA"));
        lista.add(new Cidade("", "Capinzal do Norte", "MA"));
        lista.add(new Cidade("", "Caraíba do Norte", "MA"));
        lista.add(new Cidade("", "Carolina", "MA"));
        lista.add(new Cidade("", "Carutapera", "MA"));
        lista.add(new Cidade("", "Caxias", "MA"));
        lista.add(new Cidade("", "Cedral", "MA"));
        lista.add(new Cidade("", "Central do Maranhão", "MA"));
        lista.add(new Cidade("", "Centro do Guilherme", "MA"));
        lista.add(new Cidade("", "Centro Novo do Maranhão", "MA"));
        lista.add(new Cidade("", "Chapadinha", "MA"));
        lista.add(new Cidade("", "Cidelândia", "MA"));
        lista.add(new Cidade("", "Codó", "MA"));
        lista.add(new Cidade("", "Codozinho", "MA"));
        lista.add(new Cidade("", "Coelho Neto", "MA"));
        lista.add(new Cidade("", "Colinas", "MA"));
        lista.add(new Cidade("", "Conceição do Lago-Açu", "MA"));
        lista.add(new Cidade("", "Coroatá", "MA"));
        lista.add(new Cidade("", "Curupa", "MA"));
        lista.add(new Cidade("", "Cururupu", "MA"));
        lista.add(new Cidade("", "Curva Grande", "MA"));
        lista.add(new Cidade("", "Custódio Lima", "MA"));
        lista.add(new Cidade("", "Davinópolis", "MA"));
        lista.add(new Cidade("", "Dom Pedro", "MA"));
        lista.add(new Cidade("", "Duque Bacelar", "MA"));
        lista.add(new Cidade("", "Esperantinópolis", "MA"));
        lista.add(new Cidade("", "Estandarte", "MA"));
        lista.add(new Cidade("", "Estreito", "MA"));
        lista.add(new Cidade("", "Feira Nova do Maranhão", "MA"));
        lista.add(new Cidade("", "Fernando Falcão", "MA"));
        lista.add(new Cidade("", "Formosa da Serra Negra", "MA"));
        lista.add(new Cidade("", "Fortaleza dos Nogueiras", "MA"));
        lista.add(new Cidade("", "Fortuna", "MA"));
        lista.add(new Cidade("", "Frecheiras", "MA"));
        lista.add(new Cidade("", "Godofredo Viana", "MA"));
        lista.add(new Cidade("", "Gonçalves Dias", "MA"));
        lista.add(new Cidade("", "Governador Archer", "MA"));
        lista.add(new Cidade("", "Governador Edson Lobão", "MA"));
        lista.add(new Cidade("", "Governador Eugênio Barros", "MA"));
        lista.add(new Cidade("", "Governador Luiz Rocha", "MA"));
        lista.add(new Cidade("", "Governador Newton Bello", "MA"));
        lista.add(new Cidade("", "Governador Nunes Freire", "MA"));
        lista.add(new Cidade("", "Graça Aranha", "MA"));
        lista.add(new Cidade("", "Grajaú", "MA"));
        lista.add(new Cidade("", "Guimarães", "MA"));
        lista.add(new Cidade("", "Humberto de Campos", "MA"));
        lista.add(new Cidade("", "Ibipira", "MA"));
        lista.add(new Cidade("", "Icatu", "MA"));
        lista.add(new Cidade("", "Igarapé do Meio", "MA"));
        lista.add(new Cidade("", "Igarapé Grande", "MA"));
        lista.add(new Cidade("", "Imperatriz", "MA"));
        lista.add(new Cidade("", "Itaipava do Grajaú", "MA"));
        lista.add(new Cidade("", "Itamataré", "MA"));
        lista.add(new Cidade("", "Itapecuru Mirim", "MA"));
        lista.add(new Cidade("", "Itapera", "MA"));
        lista.add(new Cidade("", "Itinga do Maranhão", "MA"));
        lista.add(new Cidade("", "Jatobá", "MA"));
        lista.add(new Cidade("", "Jenipapo dos Vieiras", "MA"));
        lista.add(new Cidade("", "João Lisboa", "MA"));
        lista.add(new Cidade("", "Joselândia", "MA"));
        lista.add(new Cidade("", "Junco do Maranhão", "MA"));
        lista.add(new Cidade("", "Lago da Pedra", "MA"));
        lista.add(new Cidade("", "Lago do Junco", "MA"));
        lista.add(new Cidade("", "Lago dos Rodrigues", "MA"));
        lista.add(new Cidade("", "Lago Verde", "MA"));
        lista.add(new Cidade("", "Lagoa do Mato", "MA"));
        lista.add(new Cidade("", "Lagoa Grande do Maranhão", "MA"));
        lista.add(new Cidade("", "Lajeado Novo", "MA"));
        lista.add(new Cidade("", "Lapela", "MA"));
        lista.add(new Cidade("", "Leandro", "MA"));
        lista.add(new Cidade("", "Lima Campos", "MA"));
        lista.add(new Cidade("", "Loreto", "MA"));
        lista.add(new Cidade("", "Luís Domingues", "MA"));
        lista.add(new Cidade("", "Magalhães de Almeida", "MA"));
        lista.add(new Cidade("", "Maioba", "MA"));
        lista.add(new Cidade("", "Maracaçumé", "MA"));
        lista.add(new Cidade("", "Marajá do Sena", "MA"));
        lista.add(new Cidade("", "Maranhãozinho", "MA"));
        lista.add(new Cidade("", "Marianópolis", "MA"));
        lista.add(new Cidade("", "Mata", "MA"));
        lista.add(new Cidade("", "Mata Roma", "MA"));
        lista.add(new Cidade("", "Matinha", "MA"));
        lista.add(new Cidade("", "Matões", "MA"));
        lista.add(new Cidade("", "Matões do Norte", "MA"));
        lista.add(new Cidade("", "Milagres do Maranhão", "MA"));
        lista.add(new Cidade("", "Mirador", "MA"));
        lista.add(new Cidade("", "Miranda do Norte", "MA"));
        lista.add(new Cidade("", "Mirinzal", "MA"));
        lista.add(new Cidade("", "Monção", "MA"));
        lista.add(new Cidade("", "Montes Altos", "MA"));
        lista.add(new Cidade("", "Morros", "MA"));
        lista.add(new Cidade("", "Nina Rodrigues", "MA"));
        lista.add(new Cidade("", "Nova Colinas", "MA"));
        lista.add(new Cidade("", "Nova Iorque", "MA"));
        lista.add(new Cidade("", "Nova Olinda do Maranhão", "MA"));
        lista.add(new Cidade("", "Olho D'Água das Cunhãs", "MA"));
        lista.add(new Cidade("", "Olinda Nova do Maranhão", "MA"));
        lista.add(new Cidade("", "Paço do Lumiar", "MA"));
        lista.add(new Cidade("", "Palmeirândia", "MA"));
        lista.add(new Cidade("", "Papagaio", "MA"));
        lista.add(new Cidade("", "Paraibano", "MA"));
        lista.add(new Cidade("", "Parnarama", "MA"));
        lista.add(new Cidade("", "Passagem Franca", "MA"));
        lista.add(new Cidade("", "Pastos Bons", "MA"));
        lista.add(new Cidade("", "Paulino Neves", "MA"));
        lista.add(new Cidade("", "Paulo Ramos", "MA"));
        lista.add(new Cidade("", "Pedreiras", "MA"));
        lista.add(new Cidade("", "Pedro do Rosário", "MA"));
        lista.add(new Cidade("", "Penalva", "MA"));
        lista.add(new Cidade("", "Peri Mirim", "MA"));
        lista.add(new Cidade("", "Peritoró", "MA"));
        lista.add(new Cidade("", "Pimentel", "MA"));
        lista.add(new Cidade("", "Pindaré Mirim", "MA"));
        lista.add(new Cidade("", "Pinheiro", "MA"));
        lista.add(new Cidade("", "Pio XII", "MA"));
        lista.add(new Cidade("", "Pirapemas", "MA"));
        lista.add(new Cidade("", "Poção de Pedras", "MA"));
        lista.add(new Cidade("", "Porto das Gabarras", "MA"));
        lista.add(new Cidade("", "Porto Franco", "MA"));
        lista.add(new Cidade("", "Porto Rico do Maranhão", "MA"));
        lista.add(new Cidade("", "Presidente Dutra", "MA"));
        lista.add(new Cidade("", "Presidente Juscelino", "MA"));
        lista.add(new Cidade("", "Presidente Médici", "MA"));
        lista.add(new Cidade("", "Presidente Sarney", "MA"));
        lista.add(new Cidade("", "Presidente Vargas", "MA"));
        lista.add(new Cidade("", "Primeira Cruz", "MA"));
        lista.add(new Cidade("", "Raposa", "MA"));
        lista.add(new Cidade("", "Resplandes", "MA"));
        lista.add(new Cidade("", "Riachão", "MA"));
        lista.add(new Cidade("", "Ribamar Fiquene", "MA"));
        lista.add(new Cidade("", "Ribeirão Azul", "MA"));
        lista.add(new Cidade("", "Rocado", "MA"));
        lista.add(new Cidade("", "Roque", "MA"));
        lista.add(new Cidade("", "Rosário", "MA"));
        lista.add(new Cidade("", "Sambaíba", "MA"));
        lista.add(new Cidade("", "Santa Filomena do Maranhão", "MA"));
        lista.add(new Cidade("", "Santa Helena", "MA"));
        lista.add(new Cidade("", "Santa Inês", "MA"));
        lista.add(new Cidade("", "Santa Luzia", "MA"));
        lista.add(new Cidade("", "Santa Luzia do Paruá", "MA"));
        lista.add(new Cidade("", "Santa Quitéria do Maranhão", "MA"));
        lista.add(new Cidade("", "Santa Rita", "MA"));
        lista.add(new Cidade("", "Santana do Maranhão", "MA"));
        lista.add(new Cidade("", "Santo Amaro", "MA"));
        lista.add(new Cidade("", "Santo Antônio dos Lopes", "MA"));
        lista.add(new Cidade("", "São Benedito do Rio Preto", "MA"));
        lista.add(new Cidade("", "São Bento", "MA"));
        lista.add(new Cidade("", "São Bernardo", "MA"));
        lista.add(new Cidade("", "São Domingos do Azeitão", "MA"));
        lista.add(new Cidade("", "São Domingos do Maranhão", "MA"));
        lista.add(new Cidade("", "São Félix de Balsas", "MA"));
        lista.add(new Cidade("", "São Francisco do Brejão", "MA"));
        lista.add(new Cidade("", "São Francisco do Maranhão", "MA"));
        lista.add(new Cidade("", "São João Batista", "MA"));
        lista.add(new Cidade("", "São João de Cortes", "MA"));
        lista.add(new Cidade("", "São João do Carú", "MA"));
        lista.add(new Cidade("", "São João do Paraíso", "MA"));
        lista.add(new Cidade("", "São João do Sóter", "MA"));
        lista.add(new Cidade("", "São João dos Patos", "MA"));
        lista.add(new Cidade("", "São Joaquim dos Melos", "MA"));
        lista.add(new Cidade("", "São José de Ribamar", "MA"));
        lista.add(new Cidade("", "São José dos Basílios", "MA"));
        lista.add(new Cidade("", "São Luís", "MA"));
        lista.add(new Cidade("", "São Luís Gonzaga do Maranhão", "MA"));
        lista.add(new Cidade("", "São Mateus do Maranhão", "MA"));
        lista.add(new Cidade("", "São Pedro da Água Branca", "MA"));
        lista.add(new Cidade("", "São Pedro dos Crentes", "MA"));
        lista.add(new Cidade("", "São Raimundo das Mangabeiras", "MA"));
        lista.add(new Cidade("", "São Raimundo de Codó", "MA"));
        lista.add(new Cidade("", "São Raimundo do Doca Bezerra", "MA"));
        lista.add(new Cidade("", "São Roberto", "MA"));
        lista.add(new Cidade("", "São Vicente Ferrer", "MA"));
        lista.add(new Cidade("", "Satubinha", "MA"));
        lista.add(new Cidade("", "Senador Alexandre Costa", "MA"));
        lista.add(new Cidade("", "Senador La Rocque", "MA"));
        lista.add(new Cidade("", "Serrano do Maranhão", "MA"));
        lista.add(new Cidade("", "Sítio Novo", "MA"));
        lista.add(new Cidade("", "Sucupira do Norte", "MA"));
        lista.add(new Cidade("", "Sucupira do Riachão", "MA"));
        lista.add(new Cidade("", "Tasso Fragoso", "MA"));
        lista.add(new Cidade("", "Timbiras", "MA"));
        lista.add(new Cidade("", "Timon", "MA"));
        lista.add(new Cidade("", "Trizidela do Vale", "MA"));
        lista.add(new Cidade("", "Tufilândia", "MA"));
        lista.add(new Cidade("", "Tuntum", "MA"));
        lista.add(new Cidade("", "Turiaçu", "MA"));
        lista.add(new Cidade("", "Turilândia", "MA"));
        lista.add(new Cidade("", "Tutóia", "MA"));
        lista.add(new Cidade("", "Urbano Santos", "MA"));
        lista.add(new Cidade("", "Vargem Grande", "MA"));
        lista.add(new Cidade("", "Viana", "MA"));
        lista.add(new Cidade("", "Vila Nova dos Martírios", "MA"));
        lista.add(new Cidade("", "Vitória do Mearim", "MA"));
        lista.add(new Cidade("", "Vitorino Freire", "MA"));
        lista.add(new Cidade("", "Zé Doca", "MA"));
        return lista;
    }
}
