package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MG {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Abadia dos Dourados", "MG"));
        lista.add(new Cidade("", "Abaeté", "MG"));
        lista.add(new Cidade("", "Abaeté dos Mendes", "MG"));
        lista.add(new Cidade("", "Abaíba", "MG"));
        lista.add(new Cidade("", "Abre Campo", "MG"));
        lista.add(new Cidade("", "Abreus", "MG"));
        lista.add(new Cidade("", "Acaiaca", "MG"));
        lista.add(new Cidade("", "Açucena", "MG"));
        lista.add(new Cidade("", "Acuruí", "MG"));
        lista.add(new Cidade("", "Adão Colares", "MG"));
        lista.add(new Cidade("", "Água Boa", "MG"));
        lista.add(new Cidade("", "Água Branca de Minas", "MG"));
        lista.add(new Cidade("", "Água Comprida", "MG"));
        lista.add(new Cidade("", "Água Santa de Minas", "MG"));
        lista.add(new Cidade("", "Água Viva", "MG"));
        lista.add(new Cidade("", "Aguanil", "MG"));
        lista.add(new Cidade("", "Águas de Araxá", "MG"));
        lista.add(new Cidade("", "Águas de Contendas", "MG"));
        lista.add(new Cidade("", "Águas Férreas", "MG"));
        lista.add(new Cidade("", "Águas Formosas", "MG"));
        lista.add(new Cidade("", "Águas Vermelhas", "MG"));
        lista.add(new Cidade("", "Aimorés", "MG"));
        lista.add(new Cidade("", "Aiuruoca", "MG"));
        lista.add(new Cidade("", "Alagoa", "MG"));
        lista.add(new Cidade("", "Albertina", "MG"));
        lista.add(new Cidade("", "Alberto Isaacson", "MG"));
        lista.add(new Cidade("", "Albertos", "MG"));
        lista.add(new Cidade("", "Aldeia", "MG"));
        lista.add(new Cidade("", "Alegre", "MG"));
        lista.add(new Cidade("", "Alegria", "MG"));
        lista.add(new Cidade("", "Além Paraíba", "MG"));
        lista.add(new Cidade("", "Alexandrita", "MG"));
        lista.add(new Cidade("", "Alfenas", "MG"));
        lista.add(new Cidade("", "Alfredo Vasconcelos", "MG"));
        lista.add(new Cidade("", "Almeida", "MG"));
        lista.add(new Cidade("", "Almeidas", "MG"));
        lista.add(new Cidade("", "Almenara", "MG"));
        lista.add(new Cidade("", "Alpercata", "MG"));
        lista.add(new Cidade("", "Alpinópolis", "MG"));
        lista.add(new Cidade("", "Alterosa", "MG"));
        lista.add(new Cidade("", "Alto Belo", "MG"));
        lista.add(new Cidade("", "Alto Caparaó", "MG"));
        lista.add(new Cidade("", "Alto Capim", "MG"));
        lista.add(new Cidade("", "Alto de Santa Helena", "MG"));
        lista.add(new Cidade("", "Alto Jequitibá", "MG"));
        lista.add(new Cidade("", "Alto Maranhão", "MG"));
        lista.add(new Cidade("", "Alto Rio Doce", "MG"));
        lista.add(new Cidade("", "Altolândia", "MG"));
        lista.add(new Cidade("", "Alvação", "MG"));
        lista.add(new Cidade("", "Alvarenga", "MG"));
        lista.add(new Cidade("", "Alvinópolis", "MG"));
        lista.add(new Cidade("", "Alvorada", "MG"));
        lista.add(new Cidade("", "Alvorada de Minas", "MG"));
        lista.add(new Cidade("", "Amanda", "MG"));
        lista.add(new Cidade("", "Amanhece", "MG"));
        lista.add(new Cidade("", "Amarantina", "MG"));
        lista.add(new Cidade("", "Amparo da Serra", "MG"));
        lista.add(new Cidade("", "Andiroba", "MG"));
        lista.add(new Cidade("", "Andradas", "MG"));
        lista.add(new Cidade("", "Andrelândia", "MG"));
        lista.add(new Cidade("", "Andrequicé", "MG"));
        lista.add(new Cidade("", "Angaturama", "MG"));
        lista.add(new Cidade("", "Angelândia", "MG"));
        lista.add(new Cidade("", "Angicos de Minas", "MG"));
        lista.add(new Cidade("", "Angueretá", "MG"));
        lista.add(new Cidade("", "Angustura", "MG"));
        lista.add(new Cidade("", "Antônio Carlos", "MG"));
        lista.add(new Cidade("", "Antônio Dias", "MG"));
        lista.add(new Cidade("", "Antônio dos Santos", "MG"));
        lista.add(new Cidade("", "Antônio Ferreira", "MG"));
        lista.add(new Cidade("", "Antônio Pereira", "MG"));
        lista.add(new Cidade("", "Antônio Prado de Minas", "MG"));
        lista.add(new Cidade("", "Antunes", "MG"));
        lista.add(new Cidade("", "Aparecida de Minas", "MG"));
        lista.add(new Cidade("", "Aparecida do Mundo Novo", "MG"));
        lista.add(new Cidade("", "Araçaí", "MG"));
        lista.add(new Cidade("", "Araçaji de Minas", "MG"));
        lista.add(new Cidade("", "Aracati de Minas", "MG"));
        lista.add(new Cidade("", "Aracitaba", "MG"));
        lista.add(new Cidade("", "Araçuaí", "MG"));
        lista.add(new Cidade("", "Araguari", "MG"));
        lista.add(new Cidade("", "Aramirim", "MG"));
        lista.add(new Cidade("", "Aranha", "MG"));
        lista.add(new Cidade("", "Arantina", "MG"));
        lista.add(new Cidade("", "Araponga", "MG"));
        lista.add(new Cidade("", "Araporã", "MG"));
        lista.add(new Cidade("", "Arapuá", "MG"));
        lista.add(new Cidade("", "Araújos", "MG"));
        lista.add(new Cidade("", "Araúna", "MG"));
        lista.add(new Cidade("", "Araxá", "MG"));
        lista.add(new Cidade("", "Arcângelo", "MG"));
        lista.add(new Cidade("", "Arceburgo", "MG"));
        lista.add(new Cidade("", "Arcos", "MG"));
        lista.add(new Cidade("", "Areado", "MG"));
        lista.add(new Cidade("", "Argenita", "MG"));
        lista.add(new Cidade("", "Argirita", "MG"));
        lista.add(new Cidade("", "Aricanduva", "MG"));
        lista.add(new Cidade("", "Arinos", "MG"));
        lista.add(new Cidade("", "Aristides Batista", "MG"));
        lista.add(new Cidade("", "Ascenção", "MG"));
        lista.add(new Cidade("", "Assaraí", "MG"));
        lista.add(new Cidade("", "Astolfo Dutra", "MG"));
        lista.add(new Cidade("", "Ataléia", "MG"));
        lista.add(new Cidade("", "Augusto de Lima", "MG"));
        lista.add(new Cidade("", "Avaí do Jacinto", "MG"));
        lista.add(new Cidade("", "Azurita", "MG"));
        lista.add(new Cidade("", "Babilônia", "MG"));
        lista.add(new Cidade("", "Bação", "MG"));
        lista.add(new Cidade("", "Baependi", "MG"));
        lista.add(new Cidade("", "Baguari", "MG"));
        lista.add(new Cidade("", "Baiões", "MG"));
        lista.add(new Cidade("", "Baixa", "MG"));
        lista.add(new Cidade("", "Baixa Quente", "MG"));
        lista.add(new Cidade("", "Balbinópolis", "MG"));
        lista.add(new Cidade("", "Baldim", "MG"));
        lista.add(new Cidade("", "Bambuí", "MG"));
        lista.add(new Cidade("", "Bandeira", "MG"));
        lista.add(new Cidade("", "Bandeira do Sul", "MG"));
        lista.add(new Cidade("", "Bandeirantes", "MG"));
        lista.add(new Cidade("", "Barão de Cocais", "MG"));
        lista.add(new Cidade("", "Barão de Monte Alto", "MG"));
        lista.add(new Cidade("", "Barbacena", "MG"));
        lista.add(new Cidade("", "Barra Alegre", "MG"));
        lista.add(new Cidade("", "Barra da Figueira", "MG"));
        lista.add(new Cidade("", "Barra do Ariranha", "MG"));
        lista.add(new Cidade("", "Barra do Cuieté", "MG"));
        lista.add(new Cidade("", "Barra Feliz", "MG"));
        lista.add(new Cidade("", "Barra Longa", "MG"));
        lista.add(new Cidade("", "Barranco Alto", "MG"));
        lista.add(new Cidade("", "Barreiro", "MG"));
        lista.add(new Cidade("", "Barreiro Branco", "MG"));
        lista.add(new Cidade("", "Barreiro da Raiz", "MG"));
        lista.add(new Cidade("", "Barreiro do Rio Verde", "MG"));
        lista.add(new Cidade("", "Barretos de Alvinópolis", "MG"));
        lista.add(new Cidade("", "Barrocão", "MG"));
        lista.add(new Cidade("", "Barroso", "MG"));
        lista.add(new Cidade("", "Baú", "MG"));
        lista.add(new Cidade("", "Bela Vista de Minas", "MG"));
        lista.add(new Cidade("", "Belisário", "MG"));
        lista.add(new Cidade("", "Belmiro Braga", "MG"));
        lista.add(new Cidade("", "Belo Horizonte", "MG"));
        lista.add(new Cidade("", "Belo Oriente", "MG"));
        lista.add(new Cidade("", "Belo Vale", "MG"));
        lista.add(new Cidade("", "Beltrão", "MG"));
        lista.add(new Cidade("", "Bentópolis de Minas", "MG"));
        lista.add(new Cidade("", "Berilo", "MG"));
        lista.add(new Cidade("", "Berizal", "MG"));
        lista.add(new Cidade("", "Bertópolis", "MG"));
        lista.add(new Cidade("", "Betim", "MG"));
        lista.add(new Cidade("", "Bias Fortes", "MG"));
        lista.add(new Cidade("", "Bicas", "MG"));
        lista.add(new Cidade("", "Bicuíba", "MG"));
        lista.add(new Cidade("", "Biquinhas", "MG"));
        lista.add(new Cidade("", "Bituri", "MG"));
        lista.add(new Cidade("", "Boa Esperança", "MG"));
        lista.add(new Cidade("", "Boa Família", "MG"));
        lista.add(new Cidade("", "Boa União de Itabirinha", "MG"));
        lista.add(new Cidade("", "Boa Vista de Minas", "MG"));
        lista.add(new Cidade("", "Boa Vista de Santa Maria", "MG"));
        lista.add(new Cidade("", "Bocaina de Minas", "MG"));
        lista.add(new Cidade("", "Bocaiúva", "MG"));
        lista.add(new Cidade("", "Bom Despacho", "MG"));
        lista.add(new Cidade("", "Bom Jardim das Pedras", "MG"));
        lista.add(new Cidade("", "Bom Jardim de Minas", "MG"));
        lista.add(new Cidade("", "Bom Jesus da Cachoeira", "MG"));
        lista.add(new Cidade("", "Bom Jesus da Penha", "MG"));
        lista.add(new Cidade("", "Bom Jesus de Angicos", "MG"));
        lista.add(new Cidade("", "Bom Jesus de Cardosos", "MG"));
        lista.add(new Cidade("", "Bom Jesus do Amparo", "MG"));
        lista.add(new Cidade("", "Bom Jesus do Divino", "MG"));
        lista.add(new Cidade("", "Bom Jesus do Galho", "MG"));
        lista.add(new Cidade("", "Bom Jesus do Madeira", "MG"));
        lista.add(new Cidade("", "Bom Jesus do Prata", "MG"));
        lista.add(new Cidade("", "Bom Pastor", "MG"));
        lista.add(new Cidade("", "Bom Repouso", "MG"));
        lista.add(new Cidade("", "Bom Retiro", "MG"));
        lista.add(new Cidade("", "Bom Sucesso", "MG"));
        lista.add(new Cidade("", "Bom Sucesso de Patos", "MG"));
        lista.add(new Cidade("", "Bonança", "MG"));
        lista.add(new Cidade("", "Bonfim", "MG"));
        lista.add(new Cidade("", "Bonfim da Barra", "MG"));
        lista.add(new Cidade("", "Bonfinópolis de Minas", "MG"));
        lista.add(new Cidade("", "Bonito de Minas", "MG"));
        lista.add(new Cidade("", "Borba Gato", "MG"));
        lista.add(new Cidade("", "Borda da Mata", "MG"));
        lista.add(new Cidade("", "Botelhos", "MG"));
        lista.add(new Cidade("", "Boticão", "MG"));
        lista.add(new Cidade("", "Botumirim", "MG"));
        lista.add(new Cidade("", "Brás Pires", "MG"));
        lista.add(new Cidade("", "Brasilândia de Minas", "MG"));
        lista.add(new Cidade("", "Brasília de Minas", "MG"));
        lista.add(new Cidade("", "Braúnas", "MG"));
        lista.add(new Cidade("", "Brazópolis", "MG"));
        lista.add(new Cidade("", "Brejaúba", "MG"));
        lista.add(new Cidade("", "Brejaubinha", "MG"));
        lista.add(new Cidade("", "Brejo Bonito", "MG"));
        lista.add(new Cidade("", "Brejo do Amparo", "MG"));
        lista.add(new Cidade("", "Brejo Mata Fome", "MG"));
        lista.add(new Cidade("", "Brumadinho", "MG"));
        lista.add(new Cidade("", "Brumal", "MG"));
        lista.add(new Cidade("", "Buarque de Macedo", "MG"));
        lista.add(new Cidade("", "Bueno", "MG"));
        lista.add(new Cidade("", "Bueno Brandão", "MG"));
        lista.add(new Cidade("", "Buenópolis", "MG"));
        lista.add(new Cidade("", "Bugre", "MG"));
        lista.add(new Cidade("", "Buritis", "MG"));
        lista.add(new Cidade("", "Buritizeiro", "MG"));
        lista.add(new Cidade("", "Caatinga", "MG"));
        lista.add(new Cidade("", "Cabeceira Grande", "MG"));
        lista.add(new Cidade("", "Cabo Verde", "MG"));
        lista.add(new Cidade("", "Caburu", "MG"));
        lista.add(new Cidade("", "Caçaratiba", "MG"));
        lista.add(new Cidade("", "Caçarema", "MG"));
        lista.add(new Cidade("", "Cachoeira Alegre", "MG"));
        lista.add(new Cidade("", "Cachoeira da Prata", "MG"));
        lista.add(new Cidade("", "Cachoeira de Minas", "MG"));
        lista.add(new Cidade("", "Cachoeira de Pajeú", "MG"));
        lista.add(new Cidade("", "Cachoeira de Santa Cruz", "MG"));
        lista.add(new Cidade("", "Cachoeira do Aranã", "MG"));
        lista.add(new Cidade("", "Cachoeira do Brumado", "MG"));
        lista.add(new Cidade("", "Cachoeira do Campo", "MG"));
        lista.add(new Cidade("", "Cachoeira do Manteiga", "MG"));
        lista.add(new Cidade("", "Cachoeira do Vale", "MG"));
        lista.add(new Cidade("", "Cachoeira dos Antunes", "MG"));
        lista.add(new Cidade("", "Cachoeira Dourada", "MG"));
        lista.add(new Cidade("", "Cachoeirinha", "MG"));
        lista.add(new Cidade("", "Caetano Lopes", "MG"));
        lista.add(new Cidade("", "Caetanópolis", "MG"));
        lista.add(new Cidade("", "Caeté", "MG"));
        lista.add(new Cidade("", "Cafemirim", "MG"));
        lista.add(new Cidade("", "Caiana", "MG"));
        lista.add(new Cidade("", "Caiapó", "MG"));
        lista.add(new Cidade("", "Cajuri", "MG"));
        lista.add(new Cidade("", "Caldas", "MG"));
        lista.add(new Cidade("", "Calixto", "MG"));
        lista.add(new Cidade("", "Camacho", "MG"));
        lista.add(new Cidade("", "Camanducaia", "MG"));
        lista.add(new Cidade("", "Camargos", "MG"));
        lista.add(new Cidade("", "Cambuí", "MG"));
        lista.add(new Cidade("", "Cambuquira", "MG"));
        lista.add(new Cidade("", "Campanário", "MG"));
        lista.add(new Cidade("", "Campanha", "MG"));
        lista.add(new Cidade("", "Campestre", "MG"));
        lista.add(new Cidade("", "Campestrinho", "MG"));
        lista.add(new Cidade("", "Campina Verde", "MG"));
        lista.add(new Cidade("", "Campo Alegre", "MG"));
        lista.add(new Cidade("", "Campo Alegre de Minas", "MG"));
        lista.add(new Cidade("", "Campo Azul", "MG"));
        lista.add(new Cidade("", "Campo Belo", "MG"));
        lista.add(new Cidade("", "Campo do Meio", "MG"));
        lista.add(new Cidade("", "Campo Florido", "MG"));
        lista.add(new Cidade("", "Campo Redondo", "MG"));
        lista.add(new Cidade("", "Campolide", "MG"));
        lista.add(new Cidade("", "Campos Altos", "MG"));
        lista.add(new Cidade("", "Campos Gerais", "MG"));
        lista.add(new Cidade("", "Cana Verde", "MG"));
        lista.add(new Cidade("", "Canaã", "MG"));
        lista.add(new Cidade("", "Canabrava", "MG"));
        lista.add(new Cidade("", "Canápolis", "MG"));
        lista.add(new Cidade("", "Canastrão", "MG"));
        lista.add(new Cidade("", "Candeias", "MG"));
        lista.add(new Cidade("", "Canoeiros", "MG"));
        lista.add(new Cidade("", "Cantagalo", "MG"));
        lista.add(new Cidade("", "Caparaó", "MG"));
        lista.add(new Cidade("", "Capela Nova", "MG"));
        lista.add(new Cidade("", "Capelinha", "MG"));
        lista.add(new Cidade("", "Capetinga", "MG"));
        lista.add(new Cidade("", "Capim Branco", "MG"));
        lista.add(new Cidade("", "Capinópolis", "MG"));
        lista.add(new Cidade("", "Capitânia", "MG"));
        lista.add(new Cidade("", "Capitão Andrade", "MG"));
        lista.add(new Cidade("", "Capitão Enéas", "MG"));
        lista.add(new Cidade("", "Capitólio", "MG"));
        lista.add(new Cidade("", "Caputira", "MG"));
        lista.add(new Cidade("", "Caraí", "MG"));
        lista.add(new Cidade("", "Caranaíba", "MG"));
        lista.add(new Cidade("", "Carandaí", "MG"));
        lista.add(new Cidade("", "Carangola", "MG"));
        lista.add(new Cidade("", "Caratinga", "MG"));
        lista.add(new Cidade("", "Carbonita", "MG"));
        lista.add(new Cidade("", "Careaçu", "MG"));
        lista.add(new Cidade("", "Carioca", "MG"));
        lista.add(new Cidade("", "Carlos Alves", "MG"));
        lista.add(new Cidade("", "Carlos Chagas", "MG"));
        lista.add(new Cidade("", "Carmésia", "MG"));
        lista.add(new Cidade("", "Carmo da Cachoeira", "MG"));
        lista.add(new Cidade("", "Carmo da Mata", "MG"));
        lista.add(new Cidade("", "Carmo de Minas", "MG"));
        lista.add(new Cidade("", "Carmo do Cajuru", "MG"));
        lista.add(new Cidade("", "Carmo do Paranaíba", "MG"));
        lista.add(new Cidade("", "Carmo do Rio Claro", "MG"));
        lista.add(new Cidade("", "Carmópolis de Minas", "MG"));
        lista.add(new Cidade("", "Carneirinho", "MG"));
        lista.add(new Cidade("", "Carrancas", "MG"));
        lista.add(new Cidade("", "Carvalho de Brito", "MG"));
        lista.add(new Cidade("", "Carvalhópolis", "MG"));
        lista.add(new Cidade("", "Carvalhos", "MG"));
        lista.add(new Cidade("", "Casa Grande", "MG"));
        lista.add(new Cidade("", "Cascalho Rico", "MG"));
        lista.add(new Cidade("", "Cássia", "MG"));
        lista.add(new Cidade("", "Cataguarino", "MG"));
        lista.add(new Cidade("", "Cataguases", "MG"));
        lista.add(new Cidade("", "Catajás", "MG"));
        lista.add(new Cidade("", "Catas Altas", "MG"));
        lista.add(new Cidade("", "Catas Altas da Noruega", "MG"));
        lista.add(new Cidade("", "Catiara", "MG"));
        lista.add(new Cidade("", "Catuji", "MG"));
        lista.add(new Cidade("", "Catuné", "MG"));
        lista.add(new Cidade("", "Catuni", "MG"));
        lista.add(new Cidade("", "Catuti", "MG"));
        lista.add(new Cidade("", "Caxambu", "MG"));
        lista.add(new Cidade("", "Cedro do Abaeté", "MG"));
        lista.add(new Cidade("", "Centenário", "MG"));
        lista.add(new Cidade("", "Central de Minas", "MG"));
        lista.add(new Cidade("", "Central de Santa Helena", "MG"));
        lista.add(new Cidade("", "Centralina", "MG"));
        lista.add(new Cidade("", "Cervo", "MG"));
        lista.add(new Cidade("", "Chácara", "MG"));
        lista.add(new Cidade("", "Chalé", "MG"));
        lista.add(new Cidade("", "Chapada de Minas", "MG"));
        lista.add(new Cidade("", "Chapada do Norte", "MG"));
        lista.add(new Cidade("", "Chapada Gaúcha", "MG"));
        lista.add(new Cidade("", "Chapéu D'Uvas", "MG"));
        lista.add(new Cidade("", "Chaves", "MG"));
        lista.add(new Cidade("", "Chaveslândia", "MG"));
        lista.add(new Cidade("", "Chiador", "MG"));
        lista.add(new Cidade("", "Chonim", "MG"));
        lista.add(new Cidade("", "Chonin de Baixo", "MG"));
        lista.add(new Cidade("", "Chumbo", "MG"));
        lista.add(new Cidade("", "Cipotânea", "MG"));
        lista.add(new Cidade("", "Cisneiros", "MG"));
        lista.add(new Cidade("", "Claraval", "MG"));
        lista.add(new Cidade("", "Claro de Minas", "MG"));
        lista.add(new Cidade("", "Claro dos Poções", "MG"));
        lista.add(new Cidade("", "Cláudio", "MG"));
        lista.add(new Cidade("", "Cláudio Manuel", "MG"));
        lista.add(new Cidade("", "Cocais", "MG"));
        lista.add(new Cidade("", "Coco", "MG"));
        lista.add(new Cidade("", "Coimbra", "MG"));
        lista.add(new Cidade("", "Coluna", "MG"));
        lista.add(new Cidade("", "Comendador Gomes", "MG"));
        lista.add(new Cidade("", "Comercinho", "MG"));
        lista.add(new Cidade("", "Comunidade Colônia Padre Damião", "MG"));
        lista.add(new Cidade("", "Conceição da Aparecida", "MG"));
        lista.add(new Cidade("", "Conceição da Barra de Minas", "MG"));
        lista.add(new Cidade("", "Conceição da Boa Vista", "MG"));
        lista.add(new Cidade("", "Conceição da Brejaúba", "MG"));
        lista.add(new Cidade("", "Conceição da Ibitipoca", "MG"));
        lista.add(new Cidade("", "Conceição das Alagoas", "MG"));
        lista.add(new Cidade("", "Conceição das Pedras", "MG"));
        lista.add(new Cidade("", "Conceição de Ipanema", "MG"));
        lista.add(new Cidade("", "Conceição de Itaguá", "MG"));
        lista.add(new Cidade("", "Conceição de Minas", "MG"));
        lista.add(new Cidade("", "Conceição de Piracicaba", "MG"));
        lista.add(new Cidade("", "Conceição de Tronqueiras", "MG"));
        lista.add(new Cidade("", "Conceição do Capim", "MG"));
        lista.add(new Cidade("", "Conceição do Formoso", "MG"));
        lista.add(new Cidade("", "Conceição do Mato Dentro", "MG"));
        lista.add(new Cidade("", "Conceição do Pará", "MG"));
        lista.add(new Cidade("", "Conceição do Rio Acima", "MG"));
        lista.add(new Cidade("", "Conceição do Rio Verde", "MG"));
        lista.add(new Cidade("", "Conceição dos Ouros", "MG"));
        lista.add(new Cidade("", "Concórdia de Mucuri", "MG"));
        lista.add(new Cidade("", "Condado do Norte", "MG"));
        lista.add(new Cidade("", "Cônego João Pio", "MG"));
        lista.add(new Cidade("", "Cônego Marinho", "MG"));
        lista.add(new Cidade("", "Confins", "MG"));
        lista.add(new Cidade("", "Congonhal", "MG"));
        lista.add(new Cidade("", "Congonhas", "MG"));
        lista.add(new Cidade("", "Congonhas do Norte", "MG"));
        lista.add(new Cidade("", "Conquista", "MG"));
        lista.add(new Cidade("", "Conselheiro Lafaiete", "MG"));
        lista.add(new Cidade("", "Conselheiro Mata", "MG"));
        lista.add(new Cidade("", "Conselheiro Pena", "MG"));
        lista.add(new Cidade("", "Consolação", "MG"));
        lista.add(new Cidade("", "Contagem", "MG"));
        lista.add(new Cidade("", "Contrato", "MG"));
        lista.add(new Cidade("", "Contria", "MG"));
        lista.add(new Cidade("", "Coqueiral", "MG"));
        lista.add(new Cidade("", "Coração de Jesus", "MG"));
        lista.add(new Cidade("", "Cordeiro de Minas", "MG"));
        lista.add(new Cidade("", "Cordisburgo", "MG"));
        lista.add(new Cidade("", "Cordislândia", "MG"));
        lista.add(new Cidade("", "Corinto", "MG"));
        lista.add(new Cidade("", "Coroaci", "MG"));
        lista.add(new Cidade("", "Coromandel", "MG"));
        lista.add(new Cidade("", "Coronel Fabriciano", "MG"));
        lista.add(new Cidade("", "Coronel Murta", "MG"));
        lista.add(new Cidade("", "Coronel Pacheco", "MG"));
        lista.add(new Cidade("", "Coronel Xavier Chaves", "MG"));
        lista.add(new Cidade("", "Córrego Danta", "MG"));
        lista.add(new Cidade("", "Córrego do Barro", "MG"));
        lista.add(new Cidade("", "Córrego do Bom Jesus", "MG"));
        lista.add(new Cidade("", "Córrego do Ouro", "MG"));
        lista.add(new Cidade("", "Córrego dos Bernardes", "MG"));
        lista.add(new Cidade("", "Córrego dos Borges", "MG"));
        lista.add(new Cidade("", "Córrego dos Melquíades", "MG"));
        lista.add(new Cidade("", "Córrego Fundo", "MG"));
        lista.add(new Cidade("", "Córrego Novo", "MG"));
        lista.add(new Cidade("", "Córregos", "MG"));
        lista.add(new Cidade("", "Correia de Almeida", "MG"));
        lista.add(new Cidade("", "Correntinho", "MG"));
        lista.add(new Cidade("", "Costa Sena", "MG"));
        lista.add(new Cidade("", "Costas", "MG"));
        lista.add(new Cidade("", "Costas da Mantiqueira", "MG"));
        lista.add(new Cidade("", "Couto de Magalhães de Minas", "MG"));
        lista.add(new Cidade("", "Crisólia", "MG"));
        lista.add(new Cidade("", "Crisólita", "MG"));
        lista.add(new Cidade("", "Crispim Jaques", "MG"));
        lista.add(new Cidade("", "Cristais", "MG"));
        lista.add(new Cidade("", "Cristália", "MG"));
        lista.add(new Cidade("", "Cristiano Otoni", "MG"));
        lista.add(new Cidade("", "Cristina", "MG"));
        lista.add(new Cidade("", "Crucilândia", "MG"));
        lista.add(new Cidade("", "Cruzeiro da Fortaleza", "MG"));
        lista.add(new Cidade("", "Cruzeiro dos Peixotos", "MG"));
        lista.add(new Cidade("", "Cruzília", "MG"));
        lista.add(new Cidade("", "Cruzinha", "MG"));
        lista.add(new Cidade("", "Cubas", "MG"));
        lista.add(new Cidade("", "Cuité Velho", "MG"));
        lista.add(new Cidade("", "Cuparaque", "MG"));
        lista.add(new Cidade("", "Curimataí", "MG"));
        lista.add(new Cidade("", "Curral de Dentro", "MG"));
        lista.add(new Cidade("", "Curral Novo de Minas", "MG"));
        lista.add(new Cidade("", "Curvelo", "MG"));
        lista.add(new Cidade("", "Datas", "MG"));
        lista.add(new Cidade("", "Delfim Moreira", "MG"));
        lista.add(new Cidade("", "Delfinópolis", "MG"));
        lista.add(new Cidade("", "Delta", "MG"));
        lista.add(new Cidade("", "Deputado Augusto Clementino", "MG"));
        lista.add(new Cidade("", "Derribadinha", "MG"));
        lista.add(new Cidade("", "Descoberto", "MG"));
        lista.add(new Cidade("", "Desembargador Otoni", "MG"));
        lista.add(new Cidade("", "Desemboque", "MG"));
        lista.add(new Cidade("", "Desterro de Entre Rios", "MG"));
        lista.add(new Cidade("", "Desterro do Melo", "MG"));
        lista.add(new Cidade("", "Diamante de Ubá", "MG"));
        lista.add(new Cidade("", "Diamantina", "MG"));
        lista.add(new Cidade("", "Dias", "MG"));
        lista.add(new Cidade("", "Dias Tavares", "MG"));
        lista.add(new Cidade("", "Diogo de Vasconcelos", "MG"));
        lista.add(new Cidade("", "Dionísio", "MG"));
        lista.add(new Cidade("", "Divinésia", "MG"));
        lista.add(new Cidade("", "Divino", "MG"));
        lista.add(new Cidade("", "Divino das Laranjeiras", "MG"));
        lista.add(new Cidade("", "Divino de Virgolândia", "MG"));
        lista.add(new Cidade("", "Divino Espírito Santo", "MG"));
        lista.add(new Cidade("", "Divinolândia de Minas", "MG"));
        lista.add(new Cidade("", "Divinópolis", "MG"));
        lista.add(new Cidade("", "Divisa Alegre", "MG"));
        lista.add(new Cidade("", "Divisa Nova", "MG"));
        lista.add(new Cidade("", "Divisópolis", "MG"));
        lista.add(new Cidade("", "Dois de Abril", "MG"));
        lista.add(new Cidade("", "Dom Bosco", "MG"));
        lista.add(new Cidade("", "Dom Cavati", "MG"));
        lista.add(new Cidade("", "Dom Corrêa", "MG"));
        lista.add(new Cidade("", "Dom Joaquim", "MG"));
        lista.add(new Cidade("", "Dom Lara", "MG"));
        lista.add(new Cidade("", "Dom Modesto", "MG"));
        lista.add(new Cidade("", "Dom Silvério", "MG"));
        lista.add(new Cidade("", "Dom Viçoso", "MG"));
        lista.add(new Cidade("", "Dona Euzébia", "MG"));
        lista.add(new Cidade("", "Dores da Vitória", "MG"));
        lista.add(new Cidade("", "Dores de Campos", "MG"));
        lista.add(new Cidade("", "Dores de Guanhães", "MG"));
        lista.add(new Cidade("", "Dores do Indaiá", "MG"));
        lista.add(new Cidade("", "Dores do Paraibuna", "MG"));
        lista.add(new Cidade("", "Dores do Turvo", "MG"));
        lista.add(new Cidade("", "Doresópolis", "MG"));
        lista.add(new Cidade("", "Douradinho", "MG"));
        lista.add(new Cidade("", "Douradoquara", "MG"));
        lista.add(new Cidade("", "Doutor Campolina", "MG"));
        lista.add(new Cidade("", "Doutor Lund", "MG"));
        lista.add(new Cidade("", "Durandé", "MG"));
        lista.add(new Cidade("", "Edgard Melo", "MG"));
        lista.add(new Cidade("", "Elói Mendes", "MG"));
        lista.add(new Cidade("", "Emboabas", "MG"));
        lista.add(new Cidade("", "Engenheiro Caldas", "MG"));
        lista.add(new Cidade("", "Engenheiro Correia", "MG"));
        lista.add(new Cidade("", "Engenheiro Dolabela", "MG"));
        lista.add(new Cidade("", "Engenheiro Navarro", "MG"));
        lista.add(new Cidade("", "Engenheiro Schnoor", "MG"));
        lista.add(new Cidade("", "Engenho", "MG"));
        lista.add(new Cidade("", "Engenho do Ribeiro", "MG"));
        lista.add(new Cidade("", "Engenho Novo", "MG"));
        lista.add(new Cidade("", "Entre Folhas", "MG"));
        lista.add(new Cidade("", "Entre Rios de Minas", "MG"));
        lista.add(new Cidade("", "Epaminondas Otoni", "MG"));
        lista.add(new Cidade("", "Era Nova", "MG"));
        lista.add(new Cidade("", "Ermidinha", "MG"));
        lista.add(new Cidade("", "Ervália", "MG"));
        lista.add(new Cidade("", "Esmeraldas", "MG"));
        lista.add(new Cidade("", "Esmeraldas de Ferros", "MG"));
        lista.add(new Cidade("", "Espera Feliz", "MG"));
        lista.add(new Cidade("", "Espinosa", "MG"));
        lista.add(new Cidade("", "Espírito Santo do Dourado", "MG"));
        lista.add(new Cidade("", "Esteios", "MG"));
        lista.add(new Cidade("", "Estevão de Araújo", "MG"));
        lista.add(new Cidade("", "Estiva", "MG"));
        lista.add(new Cidade("", "Estrela da Barra", "MG"));
        lista.add(new Cidade("", "Estrela Dalva", "MG"));
        lista.add(new Cidade("", "Estrela de Jordânia", "MG"));
        lista.add(new Cidade("", "Estrela do Indaiá", "MG"));
        lista.add(new Cidade("", "Estrela do Sul", "MG"));
        lista.add(new Cidade("", "Eugenópolis", "MG"));
        lista.add(new Cidade("", "Euxenita", "MG"));
        lista.add(new Cidade("", "Ewbank da Câmara", "MG"));
        lista.add(new Cidade("", "Expedicionário Alício", "MG"));
        lista.add(new Cidade("", "Extração", "MG"));
        lista.add(new Cidade("", "Extrema", "MG"));
        lista.add(new Cidade("", "Fama", "MG"));
        lista.add(new Cidade("", "Faria", "MG"));
        lista.add(new Cidade("", "Faria Lemos", "MG"));
        lista.add(new Cidade("", "Farias", "MG"));
        lista.add(new Cidade("", "Fechados", "MG"));
        lista.add(new Cidade("", "Felicina", "MG"));
        lista.add(new Cidade("", "Felício dos Santos", "MG"));
        lista.add(new Cidade("", "Felisburgo", "MG"));
        lista.add(new Cidade("", "Felixlândia", "MG"));
        lista.add(new Cidade("", "Fernandes Tourinho", "MG"));
        lista.add(new Cidade("", "Fernão Dias", "MG"));
        lista.add(new Cidade("", "Ferreiras", "MG"));
        lista.add(new Cidade("", "Ferreirópolis", "MG"));
        lista.add(new Cidade("", "Ferros", "MG"));
        lista.add(new Cidade("", "Ferruginha", "MG"));
        lista.add(new Cidade("", "Fervedouro", "MG"));
        lista.add(new Cidade("", "Fidalgo", "MG"));
        lista.add(new Cidade("", "Fidelândia", "MG"));
        lista.add(new Cidade("", "Flor de Minas", "MG"));
        lista.add(new Cidade("", "Florália", "MG"));
        lista.add(new Cidade("", "Floresta", "MG"));
        lista.add(new Cidade("", "Florestal", "MG"));
        lista.add(new Cidade("", "Florestina", "MG"));
        lista.add(new Cidade("", "Fonseca", "MG"));
        lista.add(new Cidade("", "Formiga", "MG"));
        lista.add(new Cidade("", "Formoso", "MG"));
        lista.add(new Cidade("", "Fortaleza de Minas", "MG"));
        lista.add(new Cidade("", "Fortuna de Minas", "MG"));
        lista.add(new Cidade("", "Francisco Badaró", "MG"));
        lista.add(new Cidade("", "Francisco Dumont", "MG"));
        lista.add(new Cidade("", "Francisco Sá", "MG"));
        lista.add(new Cidade("", "Franciscópolis", "MG"));
        lista.add(new Cidade("", "Frei Eustáquio", "MG"));
        lista.add(new Cidade("", "Frei Gaspar", "MG"));
        lista.add(new Cidade("", "Frei Inocêncio", "MG"));
        lista.add(new Cidade("", "Frei Lagonegro", "MG"));
        lista.add(new Cidade("", "Frei Orlando", "MG"));
        lista.add(new Cidade("", "Frei Serafim", "MG"));
        lista.add(new Cidade("", "Freire Cardoso", "MG"));
        lista.add(new Cidade("", "Fronteira", "MG"));
        lista.add(new Cidade("", "Fronteira dos Vales", "MG"));
        lista.add(new Cidade("", "Fruta de Leite", "MG"));
        lista.add(new Cidade("", "Frutal", "MG"));
        lista.add(new Cidade("", "Funchal", "MG"));
        lista.add(new Cidade("", "Funilândia", "MG"));
        lista.add(new Cidade("", "Furquim", "MG"));
        lista.add(new Cidade("", "Gagé", "MG"));
        lista.add(new Cidade("", "Galego", "MG"));
        lista.add(new Cidade("", "Galena", "MG"));
        lista.add(new Cidade("", "Galiléia", "MG"));
        lista.add(new Cidade("", "Gama", "MG"));
        lista.add(new Cidade("", "Gameleiras", "MG"));
        lista.add(new Cidade("", "Garapuava", "MG"));
        lista.add(new Cidade("", "Gaspar Lopes", "MG"));
        lista.add(new Cidade("", "Gavião", "MG"));
        lista.add(new Cidade("", "Glaucilândia", "MG"));
        lista.add(new Cidade("", "Glaura", "MG"));
        lista.add(new Cidade("", "Glória de Cataguases", "MG"));
        lista.add(new Cidade("", "Glucínio", "MG"));
        lista.add(new Cidade("", "Goiabal", "MG"));
        lista.add(new Cidade("", "Goiabeira", "MG"));
        lista.add(new Cidade("", "Goiaminas", "MG"));
        lista.add(new Cidade("", "Goianá", "MG"));
        lista.add(new Cidade("", "Goianases", "MG"));
        lista.add(new Cidade("", "Gonçalves", "MG"));
        lista.add(new Cidade("", "Gonzaga", "MG"));
        lista.add(new Cidade("", "Gororós", "MG"));
        lista.add(new Cidade("", "Gorutuba", "MG"));
        lista.add(new Cidade("", "Gouveia", "MG"));
        lista.add(new Cidade("", "Governador Valadares", "MG"));
        lista.add(new Cidade("", "Gramínea", "MG"));
        lista.add(new Cidade("", "Granada", "MG"));
        lista.add(new Cidade("", "Grão Mogol", "MG"));
        lista.add(new Cidade("", "Grota", "MG"));
        lista.add(new Cidade("", "Grupiara", "MG"));
        lista.add(new Cidade("", "Guaicui", "MG"));
        lista.add(new Cidade("", "Guaipava", "MG"));
        lista.add(new Cidade("", "Guanhães", "MG"));
        lista.add(new Cidade("", "Guapé", "MG"));
        lista.add(new Cidade("", "Guaraciaba", "MG"));
        lista.add(new Cidade("", "Guaraciama", "MG"));
        lista.add(new Cidade("", "Guaranésia", "MG"));
        lista.add(new Cidade("", "Guarani", "MG"));
        lista.add(new Cidade("", "Guaranilândia", "MG"));
        lista.add(new Cidade("", "Guarará", "MG"));
        lista.add(new Cidade("", "Guarataia", "MG"));
        lista.add(new Cidade("", "Guarda dos Ferreiros", "MG"));
        lista.add(new Cidade("", "Guarda-Mor", "MG"));
        lista.add(new Cidade("", "Guardinha", "MG"));
        lista.add(new Cidade("", "Guaxima", "MG"));
        lista.add(new Cidade("", "Guaxupé", "MG"));
        lista.add(new Cidade("", "Guidoval", "MG"));
        lista.add(new Cidade("", "Guimarânia", "MG"));
        lista.add(new Cidade("", "Guinda", "MG"));
        lista.add(new Cidade("", "Guiricema", "MG"));
        lista.add(new Cidade("", "Gurinhatã", "MG"));
        lista.add(new Cidade("", "Heliodora", "MG"));
        lista.add(new Cidade("", "Hematita", "MG"));
        lista.add(new Cidade("", "Hermilo Alves", "MG"));
        lista.add(new Cidade("", "Honorópolis", "MG"));
        lista.add(new Cidade("", "Humaitá", "MG"));
        lista.add(new Cidade("", "Iapu", "MG"));
        lista.add(new Cidade("", "Ibertioga", "MG"));
        lista.add(new Cidade("", "Ibiá", "MG"));
        lista.add(new Cidade("", "Ibiaí", "MG"));
        lista.add(new Cidade("", "Ibiracatu", "MG"));
        lista.add(new Cidade("", "Ibiraci", "MG"));
        lista.add(new Cidade("", "Ibirité", "MG"));
        lista.add(new Cidade("", "Ibitira", "MG"));
        lista.add(new Cidade("", "Ibitiúra de Minas", "MG"));
        lista.add(new Cidade("", "Ibituruna", "MG"));
        lista.add(new Cidade("", "Icaraí de Minas", "MG"));
        lista.add(new Cidade("", "Igarapé", "MG"));
        lista.add(new Cidade("", "Igaratinga", "MG"));
        lista.add(new Cidade("", "Iguatama", "MG"));
        lista.add(new Cidade("", "Ijaci", "MG"));
        lista.add(new Cidade("", "Ilha do Rio Doce", "MG"));
        lista.add(new Cidade("", "Ilhéus do Prata", "MG"));
        lista.add(new Cidade("", "Ilicínea", "MG"));
        lista.add(new Cidade("", "Imbé de Minas", "MG"));
        lista.add(new Cidade("", "Inconfidentes", "MG"));
        lista.add(new Cidade("", "Indaiabira", "MG"));
        lista.add(new Cidade("", "Independência", "MG"));
        lista.add(new Cidade("", "Indianópolis", "MG"));
        lista.add(new Cidade("", "Ingaí", "MG"));
        lista.add(new Cidade("", "Inhaí", "MG"));
        lista.add(new Cidade("", "Inhapim", "MG"));
        lista.add(new Cidade("", "Inhaúma", "MG"));
        lista.add(new Cidade("", "Inimutaba", "MG"));
        lista.add(new Cidade("", "Ipaba", "MG"));
        lista.add(new Cidade("", "Ipanema", "MG"));
        lista.add(new Cidade("", "Ipatinga", "MG"));
        lista.add(new Cidade("", "Ipiaçu", "MG"));
        lista.add(new Cidade("", "Ipoema", "MG"));
        lista.add(new Cidade("", "Ipuiúna", "MG"));
        lista.add(new Cidade("", "Iraí de Minas", "MG"));
        lista.add(new Cidade("", "Itabira", "MG"));
        lista.add(new Cidade("", "Itabirinha", "MG"));
        lista.add(new Cidade("", "Itabirito", "MG"));
        lista.add(new Cidade("", "Itaboca", "MG"));
        lista.add(new Cidade("", "Itacambira", "MG"));
        lista.add(new Cidade("", "Itacarambi", "MG"));
        lista.add(new Cidade("", "Itaci", "MG"));
        lista.add(new Cidade("", "Itacolomi", "MG"));
        lista.add(new Cidade("", "Itaguara", "MG"));
        lista.add(new Cidade("", "Itaim", "MG"));
        lista.add(new Cidade("", "Itaipé", "MG"));
        lista.add(new Cidade("", "Itajubá", "MG"));
        lista.add(new Cidade("", "Itajutiba", "MG"));
        lista.add(new Cidade("", "Itamarandiba", "MG"));
        lista.add(new Cidade("", "Itamarati", "MG"));
        lista.add(new Cidade("", "Itamarati de Minas", "MG"));
        lista.add(new Cidade("", "Itambacuri", "MG"));
        lista.add(new Cidade("", "Itambé do Mato Dentro", "MG"));
        lista.add(new Cidade("", "Itamirim", "MG"));
        lista.add(new Cidade("", "Itamogi", "MG"));
        lista.add(new Cidade("", "Itamonte", "MG"));
        lista.add(new Cidade("", "Itamuri", "MG"));
        lista.add(new Cidade("", "Itanhandu", "MG"));
        lista.add(new Cidade("", "Itanhomi", "MG"));
        lista.add(new Cidade("", "Itaobim", "MG"));
        lista.add(new Cidade("", "Itapagipe", "MG"));
        lista.add(new Cidade("", "Itapanhoacanga", "MG"));
        lista.add(new Cidade("", "Itapecerica", "MG"));
        lista.add(new Cidade("", "Itapeva", "MG"));
        lista.add(new Cidade("", "Itapiru", "MG"));
        lista.add(new Cidade("", "Itapirucu", "MG"));
        lista.add(new Cidade("", "Itatiaiuçu", "MG"));
        lista.add(new Cidade("", "Itaú de Minas", "MG"));
        lista.add(new Cidade("", "Itaúna", "MG"));
        lista.add(new Cidade("", "Itauninha", "MG"));
        lista.add(new Cidade("", "Itaverava", "MG"));
        lista.add(new Cidade("", "Itererê", "MG"));
        lista.add(new Cidade("", "Itinga", "MG"));
        lista.add(new Cidade("", "Itira", "MG"));
        lista.add(new Cidade("", "Itueta", "MG"));
        lista.add(new Cidade("", "Ituí", "MG"));
        lista.add(new Cidade("", "Ituiutaba", "MG"));
        lista.add(new Cidade("", "Itumirim", "MG"));
        lista.add(new Cidade("", "Iturama", "MG"));
        lista.add(new Cidade("", "Itutinga", "MG"));
        lista.add(new Cidade("", "Jaboticatubas", "MG"));
        lista.add(new Cidade("", "Jacarandira", "MG"));
        lista.add(new Cidade("", "Jacaré", "MG"));
        lista.add(new Cidade("", "Jacinto", "MG"));
        lista.add(new Cidade("", "Jacu das Piranhas", "MG"));
        lista.add(new Cidade("", "Jacuí", "MG"));
        lista.add(new Cidade("", "Jacutinga", "MG"));
        lista.add(new Cidade("", "Jaguara", "MG"));
        lista.add(new Cidade("", "Jaguaraçu", "MG"));
        lista.add(new Cidade("", "Jaguarão", "MG"));
        lista.add(new Cidade("", "Jaguaritira", "MG"));
        lista.add(new Cidade("", "Jaíba", "MG"));
        lista.add(new Cidade("", "Jampruca", "MG"));
        lista.add(new Cidade("", "Janaúba", "MG"));
        lista.add(new Cidade("", "Januária", "MG"));
        lista.add(new Cidade("", "Japaraíba", "MG"));
        lista.add(new Cidade("", "Japonvar", "MG"));
        lista.add(new Cidade("", "Jardinésia", "MG"));
        lista.add(new Cidade("", "Jeceaba", "MG"));
        lista.add(new Cidade("", "Jenipapo de Minas", "MG"));
        lista.add(new Cidade("", "Jequeri", "MG"));
        lista.add(new Cidade("", "Jequitaí", "MG"));
        lista.add(new Cidade("", "Jequitibá", "MG"));
        lista.add(new Cidade("", "Jequitinhonha", "MG"));
        lista.add(new Cidade("", "Jesuânia", "MG"));
        lista.add(new Cidade("", "JK", "MG"));
        lista.add(new Cidade("", "Joaíma", "MG"));
        lista.add(new Cidade("", "Joanésia", "MG"));
        lista.add(new Cidade("", "João Monlevade", "MG"));
        lista.add(new Cidade("", "João Pinheiro", "MG"));
        lista.add(new Cidade("", "Joaquim Felício", "MG"));
        lista.add(new Cidade("", "Jordânia", "MG"));
        lista.add(new Cidade("", "José Gonçalves de Minas", "MG"));
        lista.add(new Cidade("", "José Raydan", "MG"));
        lista.add(new Cidade("", "Joselândia", "MG"));
        lista.add(new Cidade("", "Josenópolis", "MG"));
        lista.add(new Cidade("", "Juatuba", "MG"));
        lista.add(new Cidade("", "Jubaí", "MG"));
        lista.add(new Cidade("", "Juiraçu", "MG"));
        lista.add(new Cidade("", "Juiz de Fora", "MG"));
        lista.add(new Cidade("", "Junco de Minas", "MG"));
        lista.add(new Cidade("", "Juramento", "MG"));
        lista.add(new Cidade("", "Juréia", "MG"));
        lista.add(new Cidade("", "Juruaia", "MG"));
        lista.add(new Cidade("", "Jurumirim", "MG"));
        lista.add(new Cidade("", "Justinópolis", "MG"));
        lista.add(new Cidade("", "Juvenília", "MG"));
        lista.add(new Cidade("", "Lacerdina", "MG"));
        lista.add(new Cidade("", "Lacerdinha", "MG"));
        lista.add(new Cidade("", "Ladainha", "MG"));
        lista.add(new Cidade("", "Lagamar", "MG"));
        lista.add(new Cidade("", "Lagoa Bonita", "MG"));
        lista.add(new Cidade("", "Lagoa da Prata", "MG"));
        lista.add(new Cidade("", "Lagoa dos Patos", "MG"));
        lista.add(new Cidade("", "Lagoa Dourada", "MG"));
        lista.add(new Cidade("", "Lagoa Formosa", "MG"));
        lista.add(new Cidade("", "Lagoa Grande", "MG"));
        lista.add(new Cidade("", "Lagoa Grande de Minas Novas", "MG"));
        lista.add(new Cidade("", "Lagoa Santa", "MG"));
        lista.add(new Cidade("", "Lagoa Seca", "MG"));
        lista.add(new Cidade("", "Lajinha", "MG"));
        lista.add(new Cidade("", "Lambari", "MG"));
        lista.add(new Cidade("", "Lamim", "MG"));
        lista.add(new Cidade("", "Lamounier", "MG"));
        lista.add(new Cidade("", "Lapinha", "MG"));
        lista.add(new Cidade("", "Laranjal", "MG"));
        lista.add(new Cidade("", "Laranjeiras de Caldas", "MG"));
        lista.add(new Cidade("", "Lassance", "MG"));
        lista.add(new Cidade("", "Lavras", "MG"));
        lista.add(new Cidade("", "Lavras Novas", "MG"));
        lista.add(new Cidade("", "Leandro Ferreira", "MG"));
        lista.add(new Cidade("", "Leme do Prado", "MG"));
        lista.add(new Cidade("", "Leopoldina", "MG"));
        lista.add(new Cidade("", "Levinópolis", "MG"));
        lista.add(new Cidade("", "Liberdade", "MG"));
        lista.add(new Cidade("", "Lima Duarte", "MG"));
        lista.add(new Cidade("", "Limeira de Mantena", "MG"));
        lista.add(new Cidade("", "Limeira do Oeste", "MG"));
        lista.add(new Cidade("", "Lobo Leite", "MG"));
        lista.add(new Cidade("", "Lontra", "MG"));
        lista.add(new Cidade("", "Lufa", "MG"));
        lista.add(new Cidade("", "Luisburgo", "MG"));
        lista.add(new Cidade("", "Luislândia", "MG"));
        lista.add(new Cidade("", "Luiz Pires de Minas", "MG"));
        lista.add(new Cidade("", "Luizlândia do Oeste", "MG"));
        lista.add(new Cidade("", "Luminárias", "MG"));
        lista.add(new Cidade("", "Luminosa", "MG"));
        lista.add(new Cidade("", "Luz", "MG"));
        lista.add(new Cidade("", "Macaia", "MG"));
        lista.add(new Cidade("", "Machacalis", "MG"));
        lista.add(new Cidade("", "Machado", "MG"));
        lista.add(new Cidade("", "Macuco", "MG"));
        lista.add(new Cidade("", "Macuco de Minas", "MG"));
        lista.add(new Cidade("", "Madre de Deus de Minas", "MG"));
        lista.add(new Cidade("", "Mãe dos Homens", "MG"));
        lista.add(new Cidade("", "Major Ezequiel", "MG"));
        lista.add(new Cidade("", "Major Porto", "MG"));
        lista.add(new Cidade("", "Malacacheta", "MG"));
        lista.add(new Cidade("", "Mamonas", "MG"));
        lista.add(new Cidade("", "Manga", "MG"));
        lista.add(new Cidade("", "Manhuaçu", "MG"));
        lista.add(new Cidade("", "Manhumirim", "MG"));
        lista.add(new Cidade("", "Mantena", "MG"));
        lista.add(new Cidade("", "Mantiqueira", "MG"));
        lista.add(new Cidade("", "Mantiqueira do Palmital", "MG"));
        lista.add(new Cidade("", "Mar de Espanha", "MG"));
        lista.add(new Cidade("", "Marambainha", "MG"));
        lista.add(new Cidade("", "Maravilhas", "MG"));
        lista.add(new Cidade("", "Maria da Fé", "MG"));
        lista.add(new Cidade("", "Mariana", "MG"));
        lista.add(new Cidade("", "Marilac", "MG"));
        lista.add(new Cidade("", "Marilândia", "MG"));
        lista.add(new Cidade("", "Mário Campos", "MG"));
        lista.add(new Cidade("", "Maripá de Minas", "MG"));
        lista.add(new Cidade("", "Marliéria", "MG"));
        lista.add(new Cidade("", "Marmelópolis", "MG"));
        lista.add(new Cidade("", "Martinésia", "MG"));
        lista.add(new Cidade("", "Martinho Campos", "MG"));
        lista.add(new Cidade("", "Martins Guimarães", "MG"));
        lista.add(new Cidade("", "Martins Soares", "MG"));
        lista.add(new Cidade("", "Mata Verde", "MG"));
        lista.add(new Cidade("", "Materlândia", "MG"));
        lista.add(new Cidade("", "Mateus Leme", "MG"));
        lista.add(new Cidade("", "Mathias Lobato", "MG"));
        lista.add(new Cidade("", "Matias Barbosa", "MG"));
        lista.add(new Cidade("", "Matias Cardoso", "MG"));
        lista.add(new Cidade("", "Matipó", "MG"));
        lista.add(new Cidade("", "Mato Verde", "MG"));
        lista.add(new Cidade("", "Matozinhos", "MG"));
        lista.add(new Cidade("", "Matutina", "MG"));
        lista.add(new Cidade("", "Medeiros", "MG"));
        lista.add(new Cidade("", "Medina", "MG"));
        lista.add(new Cidade("", "Melo Viana", "MG"));
        lista.add(new Cidade("", "Mendanha", "MG"));
        lista.add(new Cidade("", "Mendes Pimentel", "MG"));
        lista.add(new Cidade("", "Mendonça", "MG"));
        lista.add(new Cidade("", "Mercês", "MG"));
        lista.add(new Cidade("", "Mercês de Água Limpa", "MG"));
        lista.add(new Cidade("", "Mesquita", "MG"));
        lista.add(new Cidade("", "Mestre Caetano", "MG"));
        lista.add(new Cidade("", "Miguel Burnier", "MG"));
        lista.add(new Cidade("", "Milagre", "MG"));
        lista.add(new Cidade("", "Milho Verde", "MG"));
        lista.add(new Cidade("", "Minas Novas", "MG"));
        lista.add(new Cidade("", "Minduri", "MG"));
        lista.add(new Cidade("", "Mirabela", "MG"));
        lista.add(new Cidade("", "Miradouro", "MG"));
        lista.add(new Cidade("", "Miragaia", "MG"));
        lista.add(new Cidade("", "Miraí", "MG"));
        lista.add(new Cidade("", "Miralta", "MG"));
        lista.add(new Cidade("", "Mirantão", "MG"));
        lista.add(new Cidade("", "Miraporanga", "MG"));
        lista.add(new Cidade("", "Miravânia", "MG"));
        lista.add(new Cidade("", "Missionário", "MG"));
        lista.add(new Cidade("", "Mocambeiro", "MG"));
        lista.add(new Cidade("", "Mocambinho", "MG"));
        lista.add(new Cidade("", "Moeda", "MG"));
        lista.add(new Cidade("", "Moema", "MG"));
        lista.add(new Cidade("", "Monjolinho de Minas", "MG"));
        lista.add(new Cidade("", "Monjolos", "MG"));
        lista.add(new Cidade("", "Monsenhor Horta", "MG"));
        lista.add(new Cidade("", "Monsenhor Isidro", "MG"));
        lista.add(new Cidade("", "Monsenhor João Alexandre", "MG"));
        lista.add(new Cidade("", "Monsenhor Paulo", "MG"));
        lista.add(new Cidade("", "Montalvânia", "MG"));
        lista.add(new Cidade("", "Monte Alegre de Minas", "MG"));
        lista.add(new Cidade("", "Monte Azul", "MG"));
        lista.add(new Cidade("", "Monte Belo", "MG"));
        lista.add(new Cidade("", "Monte Carmelo", "MG"));
        lista.add(new Cidade("", "Monte Celeste", "MG"));
        lista.add(new Cidade("", "Monte Formoso", "MG"));
        lista.add(new Cidade("", "Monte Rei", "MG"));
        lista.add(new Cidade("", "Monte Santo de Minas", "MG"));
        lista.add(new Cidade("", "Monte Sião", "MG"));
        lista.add(new Cidade("", "Monte Verde", "MG"));
        lista.add(new Cidade("", "Montes Claros", "MG"));
        lista.add(new Cidade("", "Montezuma", "MG"));
        lista.add(new Cidade("", "Morada Nova de Minas", "MG"));
        lista.add(new Cidade("", "Morro", "MG"));
        lista.add(new Cidade("", "Morro da Garça", "MG"));
        lista.add(new Cidade("", "Morro do Ferro", "MG"));
        lista.add(new Cidade("", "Morro do Pilar", "MG"));
        lista.add(new Cidade("", "Morro Vermelho", "MG"));
        lista.add(new Cidade("", "Mucuri", "MG"));
        lista.add(new Cidade("", "Mundo Novo de Minas", "MG"));
        lista.add(new Cidade("", "Munhoz", "MG"));
        lista.add(new Cidade("", "Muquém", "MG"));
        lista.add(new Cidade("", "Muriaé", "MG"));
        lista.add(new Cidade("", "Mutum", "MG"));
        lista.add(new Cidade("", "Muzambinho", "MG"));
        lista.add(new Cidade("", "Nacip Raydan", "MG"));
        lista.add(new Cidade("", "Nanuque", "MG"));
        lista.add(new Cidade("", "Naque", "MG"));
        lista.add(new Cidade("", "Naque-Nanuque", "MG"));
        lista.add(new Cidade("", "Natalândia", "MG"));
        lista.add(new Cidade("", "Natércia", "MG"));
        lista.add(new Cidade("", "Nazaré de Minas", "MG"));
        lista.add(new Cidade("", "Nazareno", "MG"));
        lista.add(new Cidade("", "Nelson de Sena", "MG"));
        lista.add(new Cidade("", "Neolândia", "MG"));
        lista.add(new Cidade("", "Nepomuceno", "MG"));
        lista.add(new Cidade("", "Nhandutiba", "MG"));
        lista.add(new Cidade("", "Nicolândia", "MG"));
        lista.add(new Cidade("", "Ninheira", "MG"));
        lista.add(new Cidade("", "Nova Belém", "MG"));
        lista.add(new Cidade("", "Nova Era", "MG"));
        lista.add(new Cidade("", "Nova Esperança", "MG"));
        lista.add(new Cidade("", "Nova Lima", "MG"));
        lista.add(new Cidade("", "Nova Minda", "MG"));
        lista.add(new Cidade("", "Nova Módica", "MG"));
        lista.add(new Cidade("", "Nova Ponte", "MG"));
        lista.add(new Cidade("", "Nova Porteirinha", "MG"));
        lista.add(new Cidade("", "Nova Resende", "MG"));
        lista.add(new Cidade("", "Nova Santa Luzia", "MG"));
        lista.add(new Cidade("", "Nova Serrana", "MG"));
        lista.add(new Cidade("", "Nova União", "MG"));
        lista.add(new Cidade("", "Novilhona", "MG"));
        lista.add(new Cidade("", "Novo Cruzeiro", "MG"));
        lista.add(new Cidade("", "Novo Horizonte", "MG"));
        lista.add(new Cidade("", "Novo Oriente de Minas", "MG"));
        lista.add(new Cidade("", "Novorizonte", "MG"));
        lista.add(new Cidade("", "Ocidente", "MG"));
        lista.add(new Cidade("", "Olaria", "MG"));
        lista.add(new Cidade("", "Olegário Maciel", "MG"));
        lista.add(new Cidade("", "Olhos D'Água", "MG"));
        lista.add(new Cidade("", "Olhos Dágua", "MG"));
        lista.add(new Cidade("", "Olhos D'Água do Oeste", "MG"));
        lista.add(new Cidade("", "Olímpio Campos", "MG"));
        lista.add(new Cidade("", "Olímpio Noronha", "MG"));
        lista.add(new Cidade("", "Oliveira", "MG"));
        lista.add(new Cidade("", "Oliveira Fortes", "MG"));
        lista.add(new Cidade("", "Onça de Pitangui", "MG"));
        lista.add(new Cidade("", "Oratórios", "MG"));
        lista.add(new Cidade("", "Orizânia", "MG"));
        lista.add(new Cidade("", "Ouro Branco", "MG"));
        lista.add(new Cidade("", "Ouro Fino", "MG"));
        lista.add(new Cidade("", "Ouro Preto", "MG"));
        lista.add(new Cidade("", "Ouro Verde de Minas", "MG"));
        lista.add(new Cidade("", "Paciência", "MG"));
        lista.add(new Cidade("", "Padre Brito", "MG"));
        lista.add(new Cidade("", "Padre Carvalho", "MG"));
        lista.add(new Cidade("", "Padre Felisberto", "MG"));
        lista.add(new Cidade("", "Padre Fialho", "MG"));
        lista.add(new Cidade("", "Padre João Afonso", "MG"));
        lista.add(new Cidade("", "Padre Júlio Maria", "MG"));
        lista.add(new Cidade("", "Padre Paraíso", "MG"));
        lista.add(new Cidade("", "Padre Pinto", "MG"));
        lista.add(new Cidade("", "Padre Viegas", "MG"));
        lista.add(new Cidade("", "Pai Pedro", "MG"));
        lista.add(new Cidade("", "Paineiras", "MG"));
        lista.add(new Cidade("", "Pains", "MG"));
        lista.add(new Cidade("", "Paiolinho", "MG"));
        lista.add(new Cidade("", "Paiva", "MG"));
        lista.add(new Cidade("", "Palma", "MG"));
        lista.add(new Cidade("", "Palmeiral", "MG"));
        lista.add(new Cidade("", "Palmeiras do Manhuaçu", "MG"));
        lista.add(new Cidade("", "Palmeirinha", "MG"));
        lista.add(new Cidade("", "Palmital de Minas", "MG"));
        lista.add(new Cidade("", "Palmital dos Carvalhos", "MG"));
        lista.add(new Cidade("", "Palmópolis", "MG"));
        lista.add(new Cidade("", "Panorâmica", "MG"));
        lista.add(new Cidade("", "Pântano", "MG"));
        lista.add(new Cidade("", "Papagaios", "MG"));
        lista.add(new Cidade("", "Pará de Minas", "MG"));
        lista.add(new Cidade("", "Paracatu", "MG"));
        lista.add(new Cidade("", "Paraguaçu", "MG"));
        lista.add(new Cidade("", "Paraguai", "MG"));
        lista.add(new Cidade("", "Paraíso Garcia", "MG"));
        lista.add(new Cidade("", "Paraisópolis", "MG"));
        lista.add(new Cidade("", "Paraopeba", "MG"));
        lista.add(new Cidade("", "Paredão de Minas", "MG"));
        lista.add(new Cidade("", "Parque Durval de Barros", "MG"));
        lista.add(new Cidade("", "Parque Industrial", "MG"));
        lista.add(new Cidade("", "Passa Dez", "MG"));
        lista.add(new Cidade("", "Passa Quatro", "MG"));
        lista.add(new Cidade("", "Passa Tempo", "MG"));
        lista.add(new Cidade("", "Passa Vinte", "MG"));
        lista.add(new Cidade("", "Passabém", "MG"));
        lista.add(new Cidade("", "Passagem de Mariana", "MG"));
        lista.add(new Cidade("", "Passos", "MG"));
        lista.add(new Cidade("", "Patis", "MG"));
        lista.add(new Cidade("", "Patos de Minas", "MG"));
        lista.add(new Cidade("", "Patrimônio", "MG"));
        lista.add(new Cidade("", "Patrocínio", "MG"));
        lista.add(new Cidade("", "Patrocínio de Caratinga", "MG"));
        lista.add(new Cidade("", "Patrocínio do Muriaé", "MG"));
        lista.add(new Cidade("", "Paula Cândido", "MG"));
        lista.add(new Cidade("", "Paula Lima", "MG"));
        lista.add(new Cidade("", "Paulistas", "MG"));
        lista.add(new Cidade("", "Pavão", "MG"));
        lista.add(new Cidade("", "Pé do Morro", "MG"));
        lista.add(new Cidade("", "Peçanha", "MG"));
        lista.add(new Cidade("", "Pedra Azul", "MG"));
        lista.add(new Cidade("", "Pedra Bonita", "MG"));
        lista.add(new Cidade("", "Pedra Corrida", "MG"));
        lista.add(new Cidade("", "Pedra do Anta", "MG"));
        lista.add(new Cidade("", "Pedra do Indaiá", "MG"));
        lista.add(new Cidade("", "Pedra do Sino", "MG"));
        lista.add(new Cidade("", "Pedra Dourada", "MG"));
        lista.add(new Cidade("", "Pedra Grande", "MG"));
        lista.add(new Cidade("", "Pedra Menina", "MG"));
        lista.add(new Cidade("", "Pedralva", "MG"));
        lista.add(new Cidade("", "Pedras de Maria da Cruz", "MG"));
        lista.add(new Cidade("", "Pedras de Marilândia", "MG"));
        lista.add(new Cidade("", "Pedrinópolis", "MG"));
        lista.add(new Cidade("", "Pedro Leopoldo", "MG"));
        lista.add(new Cidade("", "Pedro Lessa", "MG"));
        lista.add(new Cidade("", "Pedro Teixeira", "MG"));
        lista.add(new Cidade("", "Pedro Versiani", "MG"));
        lista.add(new Cidade("", "Penédia", "MG"));
        lista.add(new Cidade("", "Penha de França", "MG"));
        lista.add(new Cidade("", "Penha do Capim", "MG"));
        lista.add(new Cidade("", "Penha do Cassiano", "MG"));
        lista.add(new Cidade("", "Penha do Norte", "MG"));
        lista.add(new Cidade("", "Penha Longa", "MG"));
        lista.add(new Cidade("", "Penido", "MG"));
        lista.add(new Cidade("", "Pequeri", "MG"));
        lista.add(new Cidade("", "Pequi", "MG"));
        lista.add(new Cidade("", "Perdigão", "MG"));
        lista.add(new Cidade("", "Perdilândia", "MG"));
        lista.add(new Cidade("", "Perdizes", "MG"));
        lista.add(new Cidade("", "Perdões", "MG"));
        lista.add(new Cidade("", "Pereirinhas", "MG"));
        lista.add(new Cidade("", "Periquito", "MG"));
        lista.add(new Cidade("", "Perpétuo Socorro", "MG"));
        lista.add(new Cidade("", "Pescador", "MG"));
        lista.add(new Cidade("", "Petúnia", "MG"));
        lista.add(new Cidade("", "Piacatuba", "MG"));
        lista.add(new Cidade("", "Pião", "MG"));
        lista.add(new Cidade("", "Piau", "MG"));
        lista.add(new Cidade("", "Pic Sagarana", "MG"));
        lista.add(new Cidade("", "Piedade de Caratinga", "MG"));
        lista.add(new Cidade("", "Piedade de Ponte Nova", "MG"));
        lista.add(new Cidade("", "Piedade do Paraopeba", "MG"));
        lista.add(new Cidade("", "Piedade do Rio Grande", "MG"));
        lista.add(new Cidade("", "Piedade dos Gerais", "MG"));
        lista.add(new Cidade("", "Pilar", "MG"));
        lista.add(new Cidade("", "Pimenta", "MG"));
        lista.add(new Cidade("", "Pindaíbas", "MG"));
        lista.add(new Cidade("", "Pingo-D'Água", "MG"));
        lista.add(new Cidade("", "Pinheirinhos", "MG"));
        lista.add(new Cidade("", "Pinheiro de Minas", "MG"));
        lista.add(new Cidade("", "Pinheiro Grosso", "MG"));
        lista.add(new Cidade("", "Pinheiros Altos", "MG"));
        lista.add(new Cidade("", "Pinhotiba", "MG"));
        lista.add(new Cidade("", "Pintópolis", "MG"));
        lista.add(new Cidade("", "Pintos Negreiros", "MG"));
        lista.add(new Cidade("", "Piracaiba", "MG"));
        lista.add(new Cidade("", "Piracema", "MG"));
        lista.add(new Cidade("", "Pirajuba", "MG"));
        lista.add(new Cidade("", "Piranga", "MG"));
        lista.add(new Cidade("", "Piranguçu", "MG"));
        lista.add(new Cidade("", "Piranguinho", "MG"));
        lista.add(new Cidade("", "Piranguita", "MG"));
        lista.add(new Cidade("", "Pirapanema", "MG"));
        lista.add(new Cidade("", "Pirapetinga", "MG"));
        lista.add(new Cidade("", "Pirapitinga", "MG"));
        lista.add(new Cidade("", "Pirapora", "MG"));
        lista.add(new Cidade("", "Piraúba", "MG"));
        lista.add(new Cidade("", "Piscamba", "MG"));
        lista.add(new Cidade("", "Pitangui", "MG"));
        lista.add(new Cidade("", "Pitarana", "MG"));
        lista.add(new Cidade("", "Piumhi", "MG"));
        lista.add(new Cidade("", "Planalto de Minas", "MG"));
        lista.add(new Cidade("", "Planura", "MG"));
        lista.add(new Cidade("", "Plautino Soares", "MG"));
        lista.add(new Cidade("", "Poaia", "MG"));
        lista.add(new Cidade("", "Poço Fundo", "MG"));
        lista.add(new Cidade("", "Poções de Paineiras", "MG"));
        lista.add(new Cidade("", "Poços de Caldas", "MG"));
        lista.add(new Cidade("", "Pocrane", "MG"));
        lista.add(new Cidade("", "Pompéu", "MG"));
        lista.add(new Cidade("", "Poncianos", "MG"));
        lista.add(new Cidade("", "Pontalete", "MG"));
        lista.add(new Cidade("", "Ponte Alta", "MG"));
        lista.add(new Cidade("", "Ponte Alta de Minas", "MG"));
        lista.add(new Cidade("", "Ponte do Cosme", "MG"));
        lista.add(new Cidade("", "Ponte do Silva", "MG"));
        lista.add(new Cidade("", "Ponte dos Ciganos", "MG"));
        lista.add(new Cidade("", "Ponte Firme", "MG"));
        lista.add(new Cidade("", "Ponte Nova", "MG"));
        lista.add(new Cidade("", "Ponte Segura", "MG"));
        lista.add(new Cidade("", "Pontevila", "MG"));
        lista.add(new Cidade("", "Ponto Chique", "MG"));
        lista.add(new Cidade("", "Ponto Chique do Martelo", "MG"));
        lista.add(new Cidade("", "Ponto do Marambaia", "MG"));
        lista.add(new Cidade("", "Ponto dos Volantes", "MG"));
        lista.add(new Cidade("", "Porteirinha", "MG"));
        lista.add(new Cidade("", "Porto Agrário", "MG"));
        lista.add(new Cidade("", "Porto das Flores", "MG"));
        lista.add(new Cidade("", "Porto dos Mendes", "MG"));
        lista.add(new Cidade("", "Porto Firme", "MG"));
        lista.add(new Cidade("", "Posses", "MG"));
        lista.add(new Cidade("", "Poté", "MG"));
        lista.add(new Cidade("", "Pouso Alegre", "MG"));
        lista.add(new Cidade("", "Pouso Alto", "MG"));
        lista.add(new Cidade("", "Povoado Pouso Alegre", "MG"));
        lista.add(new Cidade("", "Prados", "MG"));
        lista.add(new Cidade("", "Prata", "MG"));
        lista.add(new Cidade("", "Prata de Lajinha", "MG"));
        lista.add(new Cidade("", "Pratápolis", "MG"));
        lista.add(new Cidade("", "Pratinha", "MG"));
        lista.add(new Cidade("", "Presidente Bernardes", "MG"));
        lista.add(new Cidade("", "Presidente Juscelino", "MG"));
        lista.add(new Cidade("", "Presidente Kubitschek", "MG"));
        lista.add(new Cidade("", "Presidente Olegário", "MG"));
        lista.add(new Cidade("", "Presidente Pena", "MG"));
        lista.add(new Cidade("", "Professor Sperber", "MG"));
        lista.add(new Cidade("", "Providência", "MG"));
        lista.add(new Cidade("", "Prudente de Morais", "MG"));
        lista.add(new Cidade("", "Quartel de São João", "MG"));
        lista.add(new Cidade("", "Quartel do Sacramento", "MG"));
        lista.add(new Cidade("", "Quartel Geral", "MG"));
        lista.add(new Cidade("", "Quatituba", "MG"));
        lista.add(new Cidade("", "Queixada", "MG"));
        lista.add(new Cidade("", "Queluzita", "MG"));
        lista.add(new Cidade("", "Queluzito", "MG"));
        lista.add(new Cidade("", "Quem-Quem", "MG"));
        lista.add(new Cidade("", "Quilombo", "MG"));
        lista.add(new Cidade("", "Quilombo Nossa Senhora do Rosário", "MG"));
        lista.add(new Cidade("", "Quintinos", "MG"));
        lista.add(new Cidade("", "Rancharia e Tenda", "MG"));
        lista.add(new Cidade("", "Rancho Novo", "MG"));
        lista.add(new Cidade("", "Raposos", "MG"));
        lista.add(new Cidade("", "Raul Soares", "MG"));
        lista.add(new Cidade("", "Ravena", "MG"));
        lista.add(new Cidade("", "Realeza", "MG"));
        lista.add(new Cidade("", "Recreio", "MG"));
        lista.add(new Cidade("", "Reduto", "MG"));
        lista.add(new Cidade("", "Resende Costa", "MG"));
        lista.add(new Cidade("", "Resplendor", "MG"));
        lista.add(new Cidade("", "Ressaquinha", "MG"));
        lista.add(new Cidade("", "Retiro", "MG"));
        lista.add(new Cidade("", "Retiro Velho", "MG"));
        lista.add(new Cidade("", "Riachinho", "MG"));
        lista.add(new Cidade("", "Riacho da Cruz", "MG"));
        lista.add(new Cidade("", "Riacho dos Machados", "MG"));
        lista.add(new Cidade("", "Ribeirão da Folha", "MG"));
        lista.add(new Cidade("", "Ribeirão das Neves", "MG"));
        lista.add(new Cidade("", "Ribeirão de São Domingos", "MG"));
        lista.add(new Cidade("", "Ribeirão Vermelho", "MG"));
        lista.add(new Cidade("", "Ribeiro Junqueira", "MG"));
        lista.add(new Cidade("", "Ribeiros", "MG"));
        lista.add(new Cidade("", "Rio Acima", "MG"));
        lista.add(new Cidade("", "Rio Casca", "MG"));
        lista.add(new Cidade("", "Rio das Mortes", "MG"));
        lista.add(new Cidade("", "Rio do Prado", "MG"));
        lista.add(new Cidade("", "Rio Doce", "MG"));
        lista.add(new Cidade("", "Rio Espera", "MG"));
        lista.add(new Cidade("", "Rio Manso", "MG"));
        lista.add(new Cidade("", "Rio Melo", "MG"));
        lista.add(new Cidade("", "Rio Novo", "MG"));
        lista.add(new Cidade("", "Rio Paranaíba", "MG"));
        lista.add(new Cidade("", "Rio Pardo de Minas", "MG"));
        lista.add(new Cidade("", "Rio Piracicaba", "MG"));
        lista.add(new Cidade("", "Rio Pomba", "MG"));
        lista.add(new Cidade("", "Rio Pretinho", "MG"));
        lista.add(new Cidade("", "Rio Preto", "MG"));
        lista.add(new Cidade("", "Rio Vermelho", "MG"));
        lista.add(new Cidade("", "Ripas", "MG"));
        lista.add(new Cidade("", "Ritápolis", "MG"));
        lista.add(new Cidade("", "Roça Grande", "MG"));
        lista.add(new Cidade("", "Roças Novas", "MG"));
        lista.add(new Cidade("", "Rochedo de Minas", "MG"));
        lista.add(new Cidade("", "Rodeador", "MG"));
        lista.add(new Cidade("", "Rodeiro", "MG"));
        lista.add(new Cidade("", "Rodrigo Silva", "MG"));
        lista.add(new Cidade("", "Romaria", "MG"));
        lista.add(new Cidade("", "Rosário da Limeira", "MG"));
        lista.add(new Cidade("", "Rosário de Minas", "MG"));
        lista.add(new Cidade("", "Rosário do Pontal", "MG"));
        lista.add(new Cidade("", "Roseiral", "MG"));
        lista.add(new Cidade("", "Rubelita", "MG"));
        lista.add(new Cidade("", "Rubim", "MG"));
        lista.add(new Cidade("", "Ruralminas", "MG"));
        lista.add(new Cidade("", "Sabará", "MG"));
        lista.add(new Cidade("", "Sabinópolis", "MG"));
        lista.add(new Cidade("", "Sacramento", "MG"));
        lista.add(new Cidade("", "Salinas", "MG"));
        lista.add(new Cidade("", "Salitre de Minas", "MG"));
        lista.add(new Cidade("", "Salto da Divisa", "MG"));
        lista.add(new Cidade("", "Sanatório Santa Fé", "MG"));
        lista.add(new Cidade("", "Santa Bárbara", "MG"));
        lista.add(new Cidade("", "Santa Bárbara do Leste", "MG"));
        lista.add(new Cidade("", "Santa Bárbara do Monte Verde", "MG"));
        lista.add(new Cidade("", "Santa Bárbara do Tugúrio", "MG"));
        lista.add(new Cidade("", "Santa Cruz da Aparecida", "MG"));
        lista.add(new Cidade("", "Santa Cruz de Botumirim", "MG"));
        lista.add(new Cidade("", "Santa Cruz de Minas", "MG"));
        lista.add(new Cidade("", "Santa Cruz de Salinas", "MG"));
        lista.add(new Cidade("", "Santa Cruz do Escalvado", "MG"));
        lista.add(new Cidade("", "Santa Cruz do Prata", "MG"));
        lista.add(new Cidade("", "Santa da Pedra", "MG"));
        lista.add(new Cidade("", "Santa Efigênia de Minas", "MG"));
        lista.add(new Cidade("", "Santa Fé de Minas", "MG"));
        lista.add(new Cidade("", "Santa Filomena", "MG"));
        lista.add(new Cidade("", "Santa Helena de Minas", "MG"));
        lista.add(new Cidade("", "Santa Izabel", "MG"));
        lista.add(new Cidade("", "Santa Juliana", "MG"));
        lista.add(new Cidade("", "Santa Luzia", "MG"));
        lista.add(new Cidade("", "Santa Luzia da Serra", "MG"));
        lista.add(new Cidade("", "Santa Luzia de Caratinga", "MG"));
        lista.add(new Cidade("", "Santa Luzia dos Barros", "MG"));
        lista.add(new Cidade("", "Santa Margarida", "MG"));
        lista.add(new Cidade("", "Santa Maria de Itabira", "MG"));
        lista.add(new Cidade("", "Santa Maria do Baixio", "MG"));
        lista.add(new Cidade("", "Santa Maria do Salto", "MG"));
        lista.add(new Cidade("", "Santa Maria do Suaçuí", "MG"));
        lista.add(new Cidade("", "Santa Quitéria", "MG"));
        lista.add(new Cidade("", "Santa Rita", "MG"));
        lista.add(new Cidade("", "Santa Rita da Estrela", "MG"));
        lista.add(new Cidade("", "Santa Rita de Caldas", "MG"));
        lista.add(new Cidade("", "Santa Rita de Jacutinga", "MG"));
        lista.add(new Cidade("", "Santa Rita de Minas", "MG"));
        lista.add(new Cidade("", "Santa Rita de Ouro Preto", "MG"));
        lista.add(new Cidade("", "Santa Rita do Cedro", "MG"));
        lista.add(new Cidade("", "Santa Rita do Ibitipoca", "MG"));
        lista.add(new Cidade("", "Santa Rita do Itueto", "MG"));
        lista.add(new Cidade("", "Santa Rita do Rio do Peixe", "MG"));
        lista.add(new Cidade("", "Santa Rita do Sapucaí", "MG"));
        lista.add(new Cidade("", "Santa Rita Durão", "MG"));
        lista.add(new Cidade("", "Santa Rosa da Serra", "MG"));
        lista.add(new Cidade("", "Santa Rosa de Lima", "MG"));
        lista.add(new Cidade("", "Santa Rosa dos Dourados", "MG"));
        lista.add(new Cidade("", "Santa Teresa do Bonito", "MG"));
        lista.add(new Cidade("", "Santa Terezinha de Minas", "MG"));
        lista.add(new Cidade("", "Santa Vitória", "MG"));
        lista.add(new Cidade("", "Santa Vitória de Cocais dos Arrudas", "MG"));
        lista.add(new Cidade("", "Santana da Serra", "MG"));
        lista.add(new Cidade("", "Santana da Vargem", "MG"));
        lista.add(new Cidade("", "Santana de Caldas", "MG"));
        lista.add(new Cidade("", "Santana de Cataguases", "MG"));
        lista.add(new Cidade("", "Santana de Patos", "MG"));
        lista.add(new Cidade("", "Santana de Pirapama", "MG"));
        lista.add(new Cidade("", "Santana do Alfié", "MG"));
        lista.add(new Cidade("", "Santana do Araçuaí", "MG"));
        lista.add(new Cidade("", "Santana do Campestre", "MG"));
        lista.add(new Cidade("", "Santana do Capivari", "MG"));
        lista.add(new Cidade("", "Santana do Deserto", "MG"));
        lista.add(new Cidade("", "Santana do Garambéu", "MG"));
        lista.add(new Cidade("", "Santana do Jacaré", "MG"));
        lista.add(new Cidade("", "Santana do Manhuaçu", "MG"));
        lista.add(new Cidade("", "Santana do Paraíso", "MG"));
        lista.add(new Cidade("", "Santana do Paraopeba", "MG"));
        lista.add(new Cidade("", "Santana do Riacho", "MG"));
        lista.add(new Cidade("", "Santana do Tabuleiro", "MG"));
        lista.add(new Cidade("", "Santana dos Montes", "MG"));
        lista.add(new Cidade("", "Santo Amaro", "MG"));
        lista.add(new Cidade("", "Santo Antônio da Boa Vista", "MG"));
        lista.add(new Cidade("", "Santo Antônio da Fortaleza", "MG"));
        lista.add(new Cidade("", "Santo Antônio da Vargem Alegre", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Amparo", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Aventureiro", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Boqueirão", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Cruzeiro", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Glória", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Grama", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Itambé", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Jacinto", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Leite", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Monte", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Mucuri", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Norte", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Pirapetinga", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Pontal", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Porto", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Retiro", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Rio Abaixo", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Rio Grande", "MG"));
        lista.add(new Cidade("", "Santo Antônio do Salto", "MG"));
        lista.add(new Cidade("", "Santo Antônio dos Araújos", "MG"));
        lista.add(new Cidade("", "Santo Antônio dos Campos", "MG"));
        lista.add(new Cidade("", "Santo Hilário", "MG"));
        lista.add(new Cidade("", "Santo Hipólito", "MG"));
        lista.add(new Cidade("", "Santos Dumont", "MG"));
        lista.add(new Cidade("", "São Bartolomeu", "MG"));
        lista.add(new Cidade("", "São Bartolomeu de Sem Peixe", "MG"));
        lista.add(new Cidade("", "São Benedito", "MG"));
        lista.add(new Cidade("", "São Bento Abade", "MG"));
        lista.add(new Cidade("", "São Bento de Caldas", "MG"));
        lista.add(new Cidade("", "São Brás do Suaçuí", "MG"));
        lista.add(new Cidade("", "São Braz", "MG"));
        lista.add(new Cidade("", "São Cândido", "MG"));
        lista.add(new Cidade("", "São Domingos", "MG"));
        lista.add(new Cidade("", "São Domingos da Bocaina", "MG"));
        lista.add(new Cidade("", "São Domingos das Dores", "MG"));
        lista.add(new Cidade("", "São Domingos do Prata", "MG"));
        lista.add(new Cidade("", "São Félix de Minas", "MG"));
        lista.add(new Cidade("", "São Francisco", "MG"));
        lista.add(new Cidade("", "São Francisco de Paula", "MG"));
        lista.add(new Cidade("", "São Francisco de Sales", "MG"));
        lista.add(new Cidade("", "São Francisco do Glória", "MG"));
        lista.add(new Cidade("", "São Francisco do Humaitá", "MG"));
        lista.add(new Cidade("", "São Geraldo", "MG"));
        lista.add(new Cidade("", "São Geraldo da Piedade", "MG"));
        lista.add(new Cidade("", "São Geraldo de Tumiritinga", "MG"));
        lista.add(new Cidade("", "São Geraldo do Baguari", "MG"));
        lista.add(new Cidade("", "São Geraldo do Baixio", "MG"));
        lista.add(new Cidade("", "São Gonçalo de Botelhos", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Abaeté", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Brandão", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Monte", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Pará", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Rio Abaixo", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Rio das Pedras", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Rio Preto", "MG"));
        lista.add(new Cidade("", "São Gonçalo do Sapucaí", "MG"));
        lista.add(new Cidade("", "São Gotardo", "MG"));
        lista.add(new Cidade("", "São Jerônimo dos Poções", "MG"));
        lista.add(new Cidade("", "São João Batista do Glória", "MG"));
        lista.add(new Cidade("", "São João da Chapada", "MG"));
        lista.add(new Cidade("", "São João da Lagoa", "MG"));
        lista.add(new Cidade("", "São João da Mata", "MG"));
        lista.add(new Cidade("", "São João da Ponte", "MG"));
        lista.add(new Cidade("", "São João da Sapucaia", "MG"));
        lista.add(new Cidade("", "São João da Serra", "MG"));
        lista.add(new Cidade("", "São João da Serra Negra", "MG"));
        lista.add(new Cidade("", "São João da Vereda", "MG"));
        lista.add(new Cidade("", "São João das Missões", "MG"));
        lista.add(new Cidade("", "São João Del Rei", "MG"));
        lista.add(new Cidade("", "São João do Bonito", "MG"));
        lista.add(new Cidade("", "São João do Jacutinga", "MG"));
        lista.add(new Cidade("", "São João do Manhuaçu", "MG"));
        lista.add(new Cidade("", "São João do Manteninha", "MG"));
        lista.add(new Cidade("", "São João do Oriente", "MG"));
        lista.add(new Cidade("", "São João do Pacuí", "MG"));
        lista.add(new Cidade("", "São João do Paraíso", "MG"));
        lista.add(new Cidade("", "São João do Vacaria", "MG"));
        lista.add(new Cidade("", "São João Evangelista", "MG"));
        lista.add(new Cidade("", "São João Nepomuceno", "MG"));
        lista.add(new Cidade("", "São Joaquim", "MG"));
        lista.add(new Cidade("", "São Joaquim de Bicas", "MG"));
        lista.add(new Cidade("", "São José da Barra", "MG"));
        lista.add(new Cidade("", "São José da Bela Vista", "MG"));
        lista.add(new Cidade("", "São José da Figueira", "MG"));
        lista.add(new Cidade("", "São José da Lapa", "MG"));
        lista.add(new Cidade("", "São José da Pedra Menina", "MG"));
        lista.add(new Cidade("", "São José da Safira", "MG"));
        lista.add(new Cidade("", "São José da Varginha", "MG"));
        lista.add(new Cidade("", "São José do Acácio", "MG"));
        lista.add(new Cidade("", "São José do Alegre", "MG"));
        lista.add(new Cidade("", "São José do Barreiro", "MG"));
        lista.add(new Cidade("", "São José do Batatal", "MG"));
        lista.add(new Cidade("", "São José do Buriti", "MG"));
        lista.add(new Cidade("", "São José do Divino", "MG"));
        lista.add(new Cidade("", "São José do Goiabal", "MG"));
        lista.add(new Cidade("", "São José do Itueto", "MG"));
        lista.add(new Cidade("", "São José do Jacaré", "MG"));
        lista.add(new Cidade("", "São José do Jacuri", "MG"));
        lista.add(new Cidade("", "São José do Mantimento", "MG"));
        lista.add(new Cidade("", "São José do Mato Dentro", "MG"));
        lista.add(new Cidade("", "São José do Pântano", "MG"));
        lista.add(new Cidade("", "São José do Paraopeba", "MG"));
        lista.add(new Cidade("", "São José do Rio Manso", "MG"));
        lista.add(new Cidade("", "São José do Triunfo", "MG"));
        lista.add(new Cidade("", "São José dos Lopes", "MG"));
        lista.add(new Cidade("", "São José dos Salgados", "MG"));
        lista.add(new Cidade("", "São Judas Tadeu de Minas", "MG"));
        lista.add(new Cidade("", "São Lourenço", "MG"));
        lista.add(new Cidade("", "São Manoel do Boi", "MG"));
        lista.add(new Cidade("", "São Manoel do Guaiaçu", "MG"));
        lista.add(new Cidade("", "São Mateus de Minas", "MG"));
        lista.add(new Cidade("", "São Miguel do Anta", "MG"));
        lista.add(new Cidade("", "São Miguel do Cajuru", "MG"));
        lista.add(new Cidade("", "São Pedro da Garça", "MG"));
        lista.add(new Cidade("", "São Pedro da União", "MG"));
        lista.add(new Cidade("", "São Pedro das Tabocas", "MG"));
        lista.add(new Cidade("", "São Pedro de Caldas", "MG"));
        lista.add(new Cidade("", "São Pedro do Avaí", "MG"));
        lista.add(new Cidade("", "São Pedro do Glória", "MG"));
        lista.add(new Cidade("", "São Pedro do Jequitinhonha", "MG"));
        lista.add(new Cidade("", "São Pedro do Passa Três", "MG"));
        lista.add(new Cidade("", "São Pedro do Suaçuí", "MG"));
        lista.add(new Cidade("", "São Pedro dos Ferros", "MG"));
        lista.add(new Cidade("", "São Roberto", "MG"));
        lista.add(new Cidade("", "São Romão", "MG"));
        lista.add(new Cidade("", "São Roque de Minas", "MG"));
        lista.add(new Cidade("", "São Sebastião", "MG"));
        lista.add(new Cidade("", "São Sebastião da Barra", "MG"));
        lista.add(new Cidade("", "São Sebastião da Bela Vista", "MG"));
        lista.add(new Cidade("", "São Sebastião da Vala", "MG"));
        lista.add(new Cidade("", "São Sebastião da Vargem Alegre", "MG"));
        lista.add(new Cidade("", "São Sebastião da Vitória", "MG"));
        lista.add(new Cidade("", "São Sebastião de Braúnas", "MG"));
        lista.add(new Cidade("", "São Sebastião do Anta", "MG"));
        lista.add(new Cidade("", "São Sebastião do Baixio", "MG"));
        lista.add(new Cidade("", "São Sebastião do Barreado", "MG"));
        lista.add(new Cidade("", "São Sebastião do Barreiro", "MG"));
        lista.add(new Cidade("", "São Sebastião do Bonsucesso", "MG"));
        lista.add(new Cidade("", "São Sebastião do Bugre", "MG"));
        lista.add(new Cidade("", "São Sebastião do Gil", "MG"));
        lista.add(new Cidade("", "São Sebastião do Maranhão", "MG"));
        lista.add(new Cidade("", "São Sebastião do Óculo", "MG"));
        lista.add(new Cidade("", "São Sebastião do Oeste", "MG"));
        lista.add(new Cidade("", "São Sebastião do Paraíso", "MG"));
        lista.add(new Cidade("", "São Sebastião do Pontal", "MG"));
        lista.add(new Cidade("", "São Sebastião do Rio Preto", "MG"));
        lista.add(new Cidade("", "São Sebastião do Rio Verde", "MG"));
        lista.add(new Cidade("", "São Sebastião do Sacramento", "MG"));
        lista.add(new Cidade("", "São Sebastião do Soberbo", "MG"));
        lista.add(new Cidade("", "São Sebastião dos Poções", "MG"));
        lista.add(new Cidade("", "São Sebastião dos Robertos", "MG"));
        lista.add(new Cidade("", "São Sebastião dos Torres", "MG"));
        lista.add(new Cidade("", "São Thomé das Letras", "MG"));
        lista.add(new Cidade("", "São Tiago", "MG"));
        lista.add(new Cidade("", "São Tomás de Aquino", "MG"));
        lista.add(new Cidade("", "São Vicente", "MG"));
        lista.add(new Cidade("", "São Vicente da Estrela", "MG"));
        lista.add(new Cidade("", "São Vicente de Minas", "MG"));
        lista.add(new Cidade("", "São Vicente de Paula", "MG"));
        lista.add(new Cidade("", "São Vicente do Grama", "MG"));
        lista.add(new Cidade("", "São Vicente do Rio Doce", "MG"));
        lista.add(new Cidade("", "São Vítor", "MG"));
        lista.add(new Cidade("", "Sapucaí", "MG"));
        lista.add(new Cidade("", "Sapucaia", "MG"));
        lista.add(new Cidade("", "Sapucaia de Guanhães", "MG"));
        lista.add(new Cidade("", "Sapucaia do Norte", "MG"));
        lista.add(new Cidade("", "Sapucaí-Mirim", "MG"));
        lista.add(new Cidade("", "Sarandira", "MG"));
        lista.add(new Cidade("", "Sardoá", "MG"));
        lista.add(new Cidade("", "Sarzedo", "MG"));
        lista.add(new Cidade("", "Saudade", "MG"));
        lista.add(new Cidade("", "Sem Peixe", "MG"));
        lista.add(new Cidade("", "Senador Amaral", "MG"));
        lista.add(new Cidade("", "Senador Cortes", "MG"));
        lista.add(new Cidade("", "Senador Firmino", "MG"));
        lista.add(new Cidade("", "Senador José Bento", "MG"));
        lista.add(new Cidade("", "Senador Melo Viana", "MG"));
        lista.add(new Cidade("", "Senador Modestino Gonçalves", "MG"));
        lista.add(new Cidade("", "Senador Mourão", "MG"));
        lista.add(new Cidade("", "Senhora da Glória", "MG"));
        lista.add(new Cidade("", "Senhora da Penha", "MG"));
        lista.add(new Cidade("", "Senhora das Dores", "MG"));
        lista.add(new Cidade("", "Senhora de Oliveira", "MG"));
        lista.add(new Cidade("", "Senhora do Carmo", "MG"));
        lista.add(new Cidade("", "Senhora do Porto", "MG"));
        lista.add(new Cidade("", "Senhora dos Remédios", "MG"));
        lista.add(new Cidade("", "Sereno", "MG"));
        lista.add(new Cidade("", "Sericita", "MG"));
        lista.add(new Cidade("", "Seritinga", "MG"));
        lista.add(new Cidade("", "Serra Azul", "MG"));
        lista.add(new Cidade("", "Serra Azul de Minas", "MG"));
        lista.add(new Cidade("", "Serra Bonita", "MG"));
        lista.add(new Cidade("", "Serra da Canastra", "MG"));
        lista.add(new Cidade("", "Serra da Saudade", "MG"));
        lista.add(new Cidade("", "Serra das Araras", "MG"));
        lista.add(new Cidade("", "Serra do Camapuã", "MG"));
        lista.add(new Cidade("", "Serra do Cipó", "MG"));
        lista.add(new Cidade("", "Serra do Salitre", "MG"));
        lista.add(new Cidade("", "Serra dos Aimorés", "MG"));
        lista.add(new Cidade("", "Serra dos Lemes", "MG"));
        lista.add(new Cidade("", "Serra Nova", "MG"));
        lista.add(new Cidade("", "Serrania", "MG"));
        lista.add(new Cidade("", "Serranópolis de Minas", "MG"));
        lista.add(new Cidade("", "Serranos", "MG"));
        lista.add(new Cidade("", "Serro", "MG"));
        lista.add(new Cidade("", "Sertãozinho", "MG"));
        lista.add(new Cidade("", "Sete Cachoeiras", "MG"));
        lista.add(new Cidade("", "Sete Lagoas", "MG"));
        lista.add(new Cidade("", "Setubinha", "MG"));
        lista.add(new Cidade("", "Silva Campos", "MG"));
        lista.add(new Cidade("", "Silva Xavier", "MG"));
        lista.add(new Cidade("", "Silvano", "MG"));
        lista.add(new Cidade("", "Silveira Carvalho", "MG"));
        lista.add(new Cidade("", "Silveirânia", "MG"));
        lista.add(new Cidade("", "Silvestre", "MG"));
        lista.add(new Cidade("", "Silvianópolis", "MG"));
        lista.add(new Cidade("", "Simão Campos", "MG"));
        lista.add(new Cidade("", "Simão Pereira", "MG"));
        lista.add(new Cidade("", "Simonésia", "MG"));
        lista.add(new Cidade("", "Sobral Pinto", "MG"));
        lista.add(new Cidade("", "Sobrália", "MG"));
        lista.add(new Cidade("", "Soledade de Minas", "MG"));
        lista.add(new Cidade("", "Sopa", "MG"));
        lista.add(new Cidade("", "Sucanga", "MG"));
        lista.add(new Cidade("", "Sumaré I", "MG"));
        lista.add(new Cidade("", "Tabajara", "MG"));
        lista.add(new Cidade("", "Tabaúna", "MG"));
        lista.add(new Cidade("", "Tabuão", "MG"));
        lista.add(new Cidade("", "Tabuleiro", "MG"));
        lista.add(new Cidade("", "Tabuleiro do Mato Dentro", "MG"));
        lista.add(new Cidade("", "Taiobeiras", "MG"));
        lista.add(new Cidade("", "Taparuba", "MG"));
        lista.add(new Cidade("", "Tapira", "MG"));
        lista.add(new Cidade("", "Tapiraí", "MG"));
        lista.add(new Cidade("", "Tapuirama", "MG"));
        lista.add(new Cidade("", "Taquaraçu de Minas", "MG"));
        lista.add(new Cidade("", "Taquaral de Guanhães", "MG"));
        lista.add(new Cidade("", "Taruaçu", "MG"));
        lista.add(new Cidade("", "Tarumirim", "MG"));
        lista.add(new Cidade("", "Tebas", "MG"));
        lista.add(new Cidade("", "Teixeiras", "MG"));
        lista.add(new Cidade("", "Tejuco", "MG"));
        lista.add(new Cidade("", "Teófilo Otoni", "MG"));
        lista.add(new Cidade("", "Terra Branca", "MG"));
        lista.add(new Cidade("", "Timóteo", "MG"));
        lista.add(new Cidade("", "Tiradentes", "MG"));
        lista.add(new Cidade("", "Tiros", "MG"));
        lista.add(new Cidade("", "Tobati", "MG"));
        lista.add(new Cidade("", "Tocandira", "MG"));
        lista.add(new Cidade("", "Tocantins", "MG"));
        lista.add(new Cidade("", "Tocos do Moji", "MG"));
        lista.add(new Cidade("", "Toledo", "MG"));
        lista.add(new Cidade("", "Toledos", "MG"));
        lista.add(new Cidade("", "Tomás Gonzaga", "MG"));
        lista.add(new Cidade("", "Tombos", "MG"));
        lista.add(new Cidade("", "Topázio", "MG"));
        lista.add(new Cidade("", "Torneiros", "MG"));
        lista.add(new Cidade("", "Torreões", "MG"));
        lista.add(new Cidade("", "Três Barras da Estrada Real", "MG"));
        lista.add(new Cidade("", "Três Corações", "MG"));
        lista.add(new Cidade("", "Três Ilhas", "MG"));
        lista.add(new Cidade("", "Três Marias", "MG"));
        lista.add(new Cidade("", "Três Pontas", "MG"));
        lista.add(new Cidade("", "Trimonte", "MG"));
        lista.add(new Cidade("", "Tuiutinga", "MG"));
        lista.add(new Cidade("", "Tumiritinga", "MG"));
        lista.add(new Cidade("", "Tupaciguara", "MG"));
        lista.add(new Cidade("", "Tuparecê", "MG"));
        lista.add(new Cidade("", "Turmalina", "MG"));
        lista.add(new Cidade("", "Turvolândia", "MG"));
        lista.add(new Cidade("", "Ubá", "MG"));
        lista.add(new Cidade("", "Ubaí", "MG"));
        lista.add(new Cidade("", "Ubaporanga", "MG"));
        lista.add(new Cidade("", "Ubari", "MG"));
        lista.add(new Cidade("", "Uberaba", "MG"));
        lista.add(new Cidade("", "Uberlândia", "MG"));
        lista.add(new Cidade("", "Umburatiba", "MG"));
        lista.add(new Cidade("", "Umbuzeiro", "MG"));
        lista.add(new Cidade("", "Unaí", "MG"));
        lista.add(new Cidade("", "União de Minas", "MG"));
        lista.add(new Cidade("", "Uruana de Minas", "MG"));
        lista.add(new Cidade("", "Urucânia", "MG"));
        lista.add(new Cidade("", "Urucuia", "MG"));
        lista.add(new Cidade("", "Usina Monte Alegre", "MG"));
        lista.add(new Cidade("", "Vai-Volta", "MG"));
        lista.add(new Cidade("", "Valadares", "MG"));
        lista.add(new Cidade("", "Valão", "MG"));
        lista.add(new Cidade("", "Vale Verde de Minas", "MG"));
        lista.add(new Cidade("", "Valo Fundo", "MG"));
        lista.add(new Cidade("", "Vardiero", "MG"));
        lista.add(new Cidade("", "Vargem Alegre", "MG"));
        lista.add(new Cidade("", "Vargem Bonita", "MG"));
        lista.add(new Cidade("", "Vargem Grande da Serra", "MG"));
        lista.add(new Cidade("", "Vargem Grande do Bom Jesus", "MG"));
        lista.add(new Cidade("", "Vargem Grande do Rio Pardo", "MG"));
        lista.add(new Cidade("", "Vargem Linda", "MG"));
        lista.add(new Cidade("", "Varginha", "MG"));
        lista.add(new Cidade("", "Varjão de Minas", "MG"));
        lista.add(new Cidade("", "Várzea da Palma", "MG"));
        lista.add(new Cidade("", "Varzelândia", "MG"));
        lista.add(new Cidade("", "Vau-Açu", "MG"));
        lista.add(new Cidade("", "Vazante", "MG"));
        lista.add(new Cidade("", "Vera Cruz de Minas", "MG"));
        lista.add(new Cidade("", "Verdelândia", "MG"));
        lista.add(new Cidade("", "Vereda do Paraíso", "MG"));
        lista.add(new Cidade("", "Veredas", "MG"));
        lista.add(new Cidade("", "Veredinha", "MG"));
        lista.add(new Cidade("", "Veríssimo", "MG"));
        lista.add(new Cidade("", "Vermelho", "MG"));
        lista.add(new Cidade("", "Vermelho Novo", "MG"));
        lista.add(new Cidade("", "Vermelho Velho", "MG"));
        lista.add(new Cidade("", "Vespasiano", "MG"));
        lista.add(new Cidade("", "Viçosa", "MG"));
        lista.add(new Cidade("", "Vieiras", "MG"));
        lista.add(new Cidade("", "Vila Acari", "MG"));
        lista.add(new Cidade("", "Vila Bem-Querer", "MG"));
        lista.add(new Cidade("", "Vila Bom Jesus", "MG"));
        lista.add(new Cidade("", "Vila Bom Jesus de Minas", "MG"));
        lista.add(new Cidade("", "Vila Costina", "MG"));
        lista.add(new Cidade("", "Vila de Fátima", "MG"));
        lista.add(new Cidade("", "Vila Nova de Minas", "MG"));
        lista.add(new Cidade("", "Vila Nova dos Poções", "MG"));
        lista.add(new Cidade("", "Vila Nova Floresta", "MG"));
        lista.add(new Cidade("", "Vila Pereira", "MG"));
        lista.add(new Cidade("", "Vilanova", "MG"));
        lista.add(new Cidade("", "Vilas Boas", "MG"));
        lista.add(new Cidade("", "Vinte Alqueires", "MG"));
        lista.add(new Cidade("", "Virgem da Lapa", "MG"));
        lista.add(new Cidade("", "Virgínia", "MG"));
        lista.add(new Cidade("", "Virginópolis", "MG"));
        lista.add(new Cidade("", "Virgolândia", "MG"));
        lista.add(new Cidade("", "Visconde do Rio Branco", "MG"));
        lista.add(new Cidade("", "Vista Alegre", "MG"));
        lista.add(new Cidade("", "Vitorinos", "MG"));
        lista.add(new Cidade("", "Volta Grande", "MG"));
        lista.add(new Cidade("", "Wenceslau Braz", "MG"));
        lista.add(new Cidade("", "Zelândia", "MG"));
        lista.add(new Cidade("", "Zito Soares", "MG"));
        return lista;
    }
}
