package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MS {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista = new ArrayList<Cidade>();
        lista.add(new Cidade("2U1vKIx7i8yBtIPcGJu7","Água Boa","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Kbxb5pygkryT6iQDcHDe","Água Clara","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("sBaZQbt8CxCSnhScZwtU","Albuquerque","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Erd5uGoQPWh3dGxFBtCi","Alcinópolis","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("F1mw7DdYABlMIxd9Ottm","Alto Sucuriú","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("afTQxzrsUp8tKnMvt3js","Amambaí","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("9GKkUsKEV1bV0txY6yuc","Amandina ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("WEDl95mvNNZ3AXWC0AVn","Amolar","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("T6hx2Tix7Gt7Ait55IFI","Anastácio","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("uu4fQqmKFL8iPW3AOLau","Anaurilândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("ChfPDZpX4jfIPNUkuVN6","Angélica","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("ZsffkXtcBEdJGzJwmwP2","Anhandui ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("4YyAmye2CcvG5djCrFRV","Antônio João","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("8lEZej3QekbAj3JIkh1r","Aparecida do Taboado","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("I7yEmTFjPHsFc8YM1Kyv","Aquidauana","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("PdiOkTUfD5NsM5w4pd8N","Aral Moreira","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("mBKfEpZd2WfhcgjuOKNL","Arapuã ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("HTb4AOvmhrFVhHZ7Qxeq","Areado","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("h1uKuIfuP86yesC2Vyuo","Árvore Grande","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("EA86cuWMpF069x3XpV1L","Baianópolis","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("bkkbkCSRZarurwj8vUDh","Bálsamo","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("KL6IGtSDyqffkrOYIPmU","Bandeirantes","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("uTK43W7Sl9COA6Xxk8nW","Bataguassu","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("dViWGPvQOibtUBavzF9k","Batayporã","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("4SwaMTbYmUzdfwyYg4FA","Baús","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("NcHhWUnFCRyFDIVYcW6q","Bela Alvorada","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("aDZ28pyTyVtSuRZdISOl","Bela Vista","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kwp797rMNhDK1OL8yWxq","Bocajá","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("GoQwuJMKYOFECDKt3J1o","Bodoquena","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("9bYaUgOjSvJBkk0oiqq2","Bom Fim","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("6FigzD4RWpdsGdDF0Lrc","Bonito","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("mbx4wCxWE0eHwlv8uy09","Boqueirão","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("uyrUqVkRyfNlHfMOt9IQ","Brasilândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("B7vohy8Juh0SgYdg7QWj","Caarapó","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("YmkIxTzO1JCoIc9nOXEd","Cabeceira do Apá ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("dXvZq5o6w00EndKXZR27","Cachoeira","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("usumeCfARgUkoAAn6Q4u","Camapuã","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("lH7ZBhN0ulCnSCtcueEz","Camisão","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("PRIu6wprGJh8l1fq0S8P","Campestre","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("ifk5BVur0yPQemC3qcvh","Campo Grande","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("RYuBRGrU0o4i2FsoqMOo","Capão Seco","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("HUaQhP0bBtfZTuD4FU66","Caracol","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("5Mo9nOzPHTHBCkyxse02","Carumbé","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("BVRa1sEluOS5IY2GuUcW","Cassilândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("W7XbozY92eRPPz2Dswgv","Chapadão do Sul","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("aheaVUJxyG5r3m7WUwW3","Cipolândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("6Zt7IBhVJijEfklqoqgV","Coimbra","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("75jfIcP6KOrvkjFE5K2M","Congonhas ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("DkPmwXJ2NWHcWlBxZyEI","Corguinho","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("B7cSI6Bddl0HC1Z6U8Bd","Coronel Sapucaia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("0ytR1jvyvnO29NBYFjTe","Corumbá","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("XSwE3MvYjEwuMg9kcamd","Costa Rica","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("cHhda8vk3Pr8O0O6kDRt","Coxim","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("5ugIdKwo1292KsZzqORe","Cristalina ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("E8bJOTpFjduN48gwzkQd","Cruzaltina ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("oLvzG54YHbhNo7VKgfeU","Culturama ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("0MsG6qVbYwJss8vxjeYa","Cupins","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("2C0cLSprVLiEKIre73ZI","Debrasa","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("0eS2TYJJjnZNLlpSzHou","Deodápolis","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("psLINCofcadDp13NYtbi","Dois Irmãos do Buriti","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("5buzJrLk9Zb1peZVvKZx","Douradina","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("DbOt832HcjEORRQQHF2L","Dourados","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Ta7gz4A8qmItJ5CE5i4y","Eldorado","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("pB5YvtnrjhnoArJvfLzI","Fátima do Sul","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("IZHfynqd2Hhsqwh0XFnw","Figueirão","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("oQJ4XqTGvncuoGlESNLm","Garcias","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("63zVnMqYIYxGKkgYJzXj","Glória de Dourados","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("DxlfVfWEXvyYYSqrpMFl","Guaçu","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Gsm9DnbBkhbYM7lktq8d","Guaçulândia ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("nc8scQ63yFpb1HY9pDZq","Guadalupe do Alto Paraná","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("ebwR4r3K9E4WKthT55cu","Guia Lopes da Laguna","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("aNaC7AW1WomtHfXqyzS1","Iguatemi","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("C6UJrWvWN0TkCzFdA6rh","Ilha Comprida","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("tSvn5fHuR7PyaAyNtSrQ","Ilha Grande","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("KWXYYXhvh9oUSnpCOOyz","Indaiá do Sul","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("E7WncSpFSZgETbW5KVvr","Indaiá Grande","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kbbHG3u3iYoIK4WbRODZ","Indápolis ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("0y9DExWDLL1EDDoqK4Lm","Inocência","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("F0Xr9xaKp18PUAzS6dhd","Ipezal ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("i5Pgs19RT1Pq0sQfokUP","Itahum ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("ScBp6Di4GiWLBVAz9UzW","Itaporã","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("2YATv0X6QmkxgRmunMxg","Itaquiraí","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("6aRX86yKm8CJZcTXgH0d","Ivinhema","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("0yVjbcjFmdegoVqtVFbT","Jabuti","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("vhYolVLZeAmxrPjEwMuX","Jacareí","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("ZGQRHPQf14FENogvD0i8","Japorã","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("PRtkvAEDBVIxviuTrB3l","Jaraguari","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("dJfqAyeQWKN5NmlehwMH","Jardim","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("GtNRmeUdaIwxl6iRAHoL","Jateí","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("3PLV4cdVgG7HhTRtacV7","Jauru","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("2gB1lTzc6BPPAuZHW79l","Juscelândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("nWxKHGl9vbMOnxmpaEk3","Jutí","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("uLZRAX1I985D5aSxGcPy","Ladário","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("V8qGj6wbO8uM5FmJU7uW","Lagoa Bonita ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("zHGwZwMf1vlo9bJgNaw1","Laguna Carapã","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("6TaSFy9Mv2RbHGceBaxm","Maracaju","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("366UfpKabJJJlKMtOwmk","Miranda","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("mRoMP2BvEmzdhraiIqwd","Montese ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("NhAXto3FoJ12CTcVFLfF","Morangas","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("P5GyGZHfFLP0LMUojzmV","Morraria do Sul","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("as0sTuSnj8hfcPE0Yzs1","Morumbi","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("dlguxl88YKykEPwxSLy8","Mundo Novo","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("58XLdRL7wi3WfFSGSds2","Naviraí","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("hEdWZXVZ0YBxwlrovyri","Nhecolândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("05miNebCwIISd79fxtLG","Nioaque","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("RLEkSVUuoaBdYHQ74nMW","Nossa Senhora de Fátima","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("fuT5x5kyUxVO9bFq7KYU","Nova Alvorada do Sul","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("jSFT8dFtt1IDVDpHKhd1","Nova América ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("hJx31DnMP9mAdJpsB6Jk","Nova Andradina","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("t9AfImTiCU8oOHz3NMbN","Nova Casa Verde ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("bNWEXP6BNBTGvZKuWGr8","Nova Esperança","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kU3Af8kwGKOA3kUwPyfT","Nova Jales","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("oaldflo9uN3qLVD7OjsE","Novo Horizonte do Sul","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("X3OmisG66X3vOovnysee","Oriente","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("WxwpNiHUVgtnYuomzR8k","Paiaguás","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("USgWpELqLyNwMJUqZcmb","Palmeiras ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("6ryOuE77IknGbmBuEzEu","Pana","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("78LxiQhqfJMnBaLzRM1C","Panambi","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("RGfYT6VdthqMV7Uz0kX3","Paraíso das Águas","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("XYwS9yytD6UAtRxgRau2","Paranaíba","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("tWTU7DhVRzrBrajRGEFK","Paranhos","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("LqRQ2BvYFF3jriAP0RrH","Pedro Gomes","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("5qzoz9bNCqZdCFKMy3V3","Picadinha","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("pJ1CkpzXXtLzWRTNOEZH","Pirapora ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Mjz6SAd1h0uDinCAHiWB","Piraputanga","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("1dECQaUdWbaqrb0YGdqH","Ponta Porã","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("TYIzB69ZoRorJSynP0Kk","Ponte Vermelha","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("4gTFzuAUNmv9mvph22dY","Pontinha do Cocho","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("mLzbvVdwaSdZdp4f75we","Porto Esperança","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Ust5THZY9jIBZm11OTuP","Porto Murtinho","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("rOhuooS1PeBkSGmgQ3vQ","Porto Vilma ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("KuN7vMzQsoULkqRnuBvm","Porto XV de Novembro ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("7CH4iayRLYfsY2fqeC1f","Presidente Castelo","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("1iASnvOZdV4qwVaacnqp","Prudêncio Thomaz ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("GGpl4BxxGkLqJXVmWHfU","Quebra Côco","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kTaImXUg1EpUxnuHsIr7","Quebracho","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("QFr1eZriIHkbgvjiSR5c","Ribas do Rio Pardo","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Y1dWFK6OIKI1gAWlz6Ra","Rio Brilhante","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("NFxEyzDl1W6cQ0xECknK","Rio Negro","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kz9qu7QTgXUbzFIDjlWp","Rio Verde de Mato Grosso","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("44kIsEOluH1Pl7ipsevr","Rochedinho ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("sAKLi2g6w7qhERXHu2t9","Rochedo","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("hrLHwpAZtZ8oCythceSX","Sanga Puitã ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("pf1FDoFkraAMb0Y2P242","Santa Rita do Pardo","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("DLbjmcmz5uTTtwxQg3sT","Santa Terezinha","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("Q1vr1BqyG2iWWkSGlA5o","São Gabriel do Oeste","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("xlNQBIcslaWNAsyrD5fN","São João do Apore","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("6QLSikMCnUaNfXcrH8G6","São José","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("W8OwYf4NhAXe1mkktZP5","São José do Sucuriú","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("zZhthsKONHhNfYg7p8fn","São Pedro","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("B0sYWBFIR3hsFamrpk79","São Pedro ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("sFrwnYlszuLKx477g03D","São Romão","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("uERHnUNWw0y1ePWyWM3S","Selvíria","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("lwR0QOy6XjJfxtNBuxal","Sete Quedas","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("KHeyS2Ju1P63g42ULMpP","Sidrolândia","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("cHSlWwLeGZXbn1JJnMyh","Sonora","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("jAcPAf7Uuf9May4EJ98G","Tacuru","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("D1vzH8rCNHVHVXhmpDXn","Tamandaré","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("oMEKEE3jBxetg6W66sMe","Taquari","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("nSxhcaemU3UEAx4ZPqXC","Taquarussu","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kzTZ0U09ou47te5vO9UX","Taunay","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("V0J82WAQKz11VtIEdBeO","Terenos","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("b7gfBhV6uHZpFAhUH8ij","Três Lagoas","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("0pzhPV3KPxDqYP6K8pkO","Velhacaria","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("osLYFZ0rmGoKft7hA9AB","Vicentina","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("kGtNDvaYNDlYc1y0fIF6","Vila Formosa","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("1Et5qqszcAvUrSH4sjHL","Vila Marques ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("w8Te5nykwsyOuq72uSLJ","Vila Rica","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("4hPNF0YJdp1hKYftrF80","Vila União ","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("2Z0OD1KhUQ1QikMhcPd1","Vila Vargas","82bo5VcIUDbVhAiiWKE0", "MS"));
        lista.add(new Cidade("oIo0O01fTAttD0ur8lUm","Vista Alegre ","82bo5VcIUDbVhAiiWKE0", "MS"));

        return lista;
    }
}
