package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MS {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista = new ArrayList<Cidade>();
        lista.add(new Cidade("2U1vKIx7i8yBtIPcGJu7","Água Boa","MS"));
        lista.add(new Cidade("Kbxb5pygkryT6iQDcHDe","Água Clara","MS"));
        lista.add(new Cidade("sBaZQbt8CxCSnhScZwtU","Albuquerque","MS"));
        lista.add(new Cidade("Erd5uGoQPWh3dGxFBtCi","Alcinópolis","MS"));
        lista.add(new Cidade("F1mw7DdYABlMIxd9Ottm","Alto Sucuriú","MS"));
        lista.add(new Cidade("afTQxzrsUp8tKnMvt3js","Amambaí","MS"));
        lista.add(new Cidade("9GKkUsKEV1bV0txY6yuc","Amandina ","MS"));
        lista.add(new Cidade("WEDl95mvNNZ3AXWC0AVn","Amolar","MS"));
        lista.add(new Cidade("T6hx2Tix7Gt7Ait55IFI","Anastácio","MS"));
        lista.add(new Cidade("uu4fQqmKFL8iPW3AOLau","Anaurilândia","MS"));
        lista.add(new Cidade("ChfPDZpX4jfIPNUkuVN6","Angélica","MS"));
        lista.add(new Cidade("ZsffkXtcBEdJGzJwmwP2","Anhandui ","MS"));
        lista.add(new Cidade("4YyAmye2CcvG5djCrFRV","Antônio João","MS"));
        lista.add(new Cidade("8lEZej3QekbAj3JIkh1r","Aparecida do Taboado","MS"));
        lista.add(new Cidade("I7yEmTFjPHsFc8YM1Kyv","Aquidauana","MS"));
        lista.add(new Cidade("PdiOkTUfD5NsM5w4pd8N","Aral Moreira","MS"));
        lista.add(new Cidade("mBKfEpZd2WfhcgjuOKNL","Arapuã ","MS"));
        lista.add(new Cidade("HTb4AOvmhrFVhHZ7Qxeq","Areado","MS"));
        lista.add(new Cidade("h1uKuIfuP86yesC2Vyuo","Árvore Grande","MS"));
        lista.add(new Cidade("EA86cuWMpF069x3XpV1L","Baianópolis","MS"));
        lista.add(new Cidade("bkkbkCSRZarurwj8vUDh","Bálsamo","MS"));
        lista.add(new Cidade("KL6IGtSDyqffkrOYIPmU","Bandeirantes","MS"));
        lista.add(new Cidade("uTK43W7Sl9COA6Xxk8nW","Bataguassu","MS"));
        lista.add(new Cidade("dViWGPvQOibtUBavzF9k","Batayporã","MS"));
        lista.add(new Cidade("4SwaMTbYmUzdfwyYg4FA","Baús","MS"));
        lista.add(new Cidade("NcHhWUnFCRyFDIVYcW6q","Bela Alvorada","MS"));
        lista.add(new Cidade("aDZ28pyTyVtSuRZdISOl","Bela Vista","MS"));
        lista.add(new Cidade("kwp797rMNhDK1OL8yWxq","Bocajá","MS"));
        lista.add(new Cidade("GoQwuJMKYOFECDKt3J1o","Bodoquena","MS"));
        lista.add(new Cidade("9bYaUgOjSvJBkk0oiqq2","Bom Fim","MS"));
        lista.add(new Cidade("6FigzD4RWpdsGdDF0Lrc","Bonito","MS"));
        lista.add(new Cidade("mbx4wCxWE0eHwlv8uy09","Boqueirão","MS"));
        lista.add(new Cidade("uyrUqVkRyfNlHfMOt9IQ","Brasilândia","MS"));
        lista.add(new Cidade("B7vohy8Juh0SgYdg7QWj","Caarapó","MS"));
        lista.add(new Cidade("YmkIxTzO1JCoIc9nOXEd","Cabeceira do Apá ","MS"));
        lista.add(new Cidade("dXvZq5o6w00EndKXZR27","Cachoeira","MS"));
        lista.add(new Cidade("usumeCfARgUkoAAn6Q4u","Camapuã","MS"));
        lista.add(new Cidade("lH7ZBhN0ulCnSCtcueEz","Camisão","MS"));
        lista.add(new Cidade("PRIu6wprGJh8l1fq0S8P","Campestre","MS"));
        lista.add(new Cidade("ifk5BVur0yPQemC3qcvh","Campo Grande","MS"));
        lista.add(new Cidade("RYuBRGrU0o4i2FsoqMOo","Capão Seco","MS"));
        lista.add(new Cidade("HUaQhP0bBtfZTuD4FU66","Caracol","MS"));
        lista.add(new Cidade("5Mo9nOzPHTHBCkyxse02","Carumbé","MS"));
        lista.add(new Cidade("BVRa1sEluOS5IY2GuUcW","Cassilândia","MS"));
        lista.add(new Cidade("W7XbozY92eRPPz2Dswgv","Chapadão do Sul","MS"));
        lista.add(new Cidade("aheaVUJxyG5r3m7WUwW3","Cipolândia","MS"));
        lista.add(new Cidade("6Zt7IBhVJijEfklqoqgV","Coimbra","MS"));
        lista.add(new Cidade("75jfIcP6KOrvkjFE5K2M","Congonhas ","MS"));
        lista.add(new Cidade("DkPmwXJ2NWHcWlBxZyEI","Corguinho","MS"));
        lista.add(new Cidade("B7cSI6Bddl0HC1Z6U8Bd","Coronel Sapucaia","MS"));
        lista.add(new Cidade("0ytR1jvyvnO29NBYFjTe","Corumbá","MS"));
        lista.add(new Cidade("XSwE3MvYjEwuMg9kcamd","Costa Rica","MS"));
        lista.add(new Cidade("cHhda8vk3Pr8O0O6kDRt","Coxim","MS"));
        lista.add(new Cidade("5ugIdKwo1292KsZzqORe","Cristalina ","MS"));
        lista.add(new Cidade("E8bJOTpFjduN48gwzkQd","Cruzaltina ","MS"));
        lista.add(new Cidade("oLvzG54YHbhNo7VKgfeU","Culturama ","MS"));
        lista.add(new Cidade("0MsG6qVbYwJss8vxjeYa","Cupins","MS"));
        lista.add(new Cidade("2C0cLSprVLiEKIre73ZI","Debrasa","MS"));
        lista.add(new Cidade("0eS2TYJJjnZNLlpSzHou","Deodápolis","MS"));
        lista.add(new Cidade("psLINCofcadDp13NYtbi","Dois Irmãos do Buriti","MS"));
        lista.add(new Cidade("5buzJrLk9Zb1peZVvKZx","Douradina","MS"));
        lista.add(new Cidade("DbOt832HcjEORRQQHF2L","Dourados","MS"));
        lista.add(new Cidade("Ta7gz4A8qmItJ5CE5i4y","Eldorado","MS"));
        lista.add(new Cidade("pB5YvtnrjhnoArJvfLzI","Fátima do Sul","MS"));
        lista.add(new Cidade("IZHfynqd2Hhsqwh0XFnw","Figueirão","MS"));
        lista.add(new Cidade("oQJ4XqTGvncuoGlESNLm","Garcias","MS"));
        lista.add(new Cidade("63zVnMqYIYxGKkgYJzXj","Glória de Dourados","MS"));
        lista.add(new Cidade("DxlfVfWEXvyYYSqrpMFl","Guaçu","MS"));
        lista.add(new Cidade("Gsm9DnbBkhbYM7lktq8d","Guaçulândia ","MS"));
        lista.add(new Cidade("nc8scQ63yFpb1HY9pDZq","Guadalupe do Alto Paraná","MS"));
        lista.add(new Cidade("ebwR4r3K9E4WKthT55cu","Guia Lopes da Laguna","MS"));
        lista.add(new Cidade("aNaC7AW1WomtHfXqyzS1","Iguatemi","MS"));
        lista.add(new Cidade("C6UJrWvWN0TkCzFdA6rh","Ilha Comprida","MS"));
        lista.add(new Cidade("tSvn5fHuR7PyaAyNtSrQ","Ilha Grande","MS"));
        lista.add(new Cidade("KWXYYXhvh9oUSnpCOOyz","Indaiá do Sul","MS"));
        lista.add(new Cidade("E7WncSpFSZgETbW5KVvr","Indaiá Grande","MS"));
        lista.add(new Cidade("kbbHG3u3iYoIK4WbRODZ","Indápolis ","MS"));
        lista.add(new Cidade("0y9DExWDLL1EDDoqK4Lm","Inocência","MS"));
        lista.add(new Cidade("F0Xr9xaKp18PUAzS6dhd","Ipezal ","MS"));
        lista.add(new Cidade("i5Pgs19RT1Pq0sQfokUP","Itahum ","MS"));
        lista.add(new Cidade("ScBp6Di4GiWLBVAz9UzW","Itaporã","MS"));
        lista.add(new Cidade("2YATv0X6QmkxgRmunMxg","Itaquiraí","MS"));
        lista.add(new Cidade("6aRX86yKm8CJZcTXgH0d","Ivinhema","MS"));
        lista.add(new Cidade("0yVjbcjFmdegoVqtVFbT","Jabuti","MS"));
        lista.add(new Cidade("vhYolVLZeAmxrPjEwMuX","Jacareí","MS"));
        lista.add(new Cidade("ZGQRHPQf14FENogvD0i8","Japorã","MS"));
        lista.add(new Cidade("PRtkvAEDBVIxviuTrB3l","Jaraguari","MS"));
        lista.add(new Cidade("dJfqAyeQWKN5NmlehwMH","Jardim","MS"));
        lista.add(new Cidade("GtNRmeUdaIwxl6iRAHoL","Jateí","MS"));
        lista.add(new Cidade("3PLV4cdVgG7HhTRtacV7","Jauru","MS"));
        lista.add(new Cidade("2gB1lTzc6BPPAuZHW79l","Juscelândia","MS"));
        lista.add(new Cidade("nWxKHGl9vbMOnxmpaEk3","Jutí","MS"));
        lista.add(new Cidade("uLZRAX1I985D5aSxGcPy","Ladário","MS"));
        lista.add(new Cidade("V8qGj6wbO8uM5FmJU7uW","Lagoa Bonita ","MS"));
        lista.add(new Cidade("zHGwZwMf1vlo9bJgNaw1","Laguna Carapã","MS"));
        lista.add(new Cidade("6TaSFy9Mv2RbHGceBaxm","Maracaju","MS"));
        lista.add(new Cidade("366UfpKabJJJlKMtOwmk","Miranda","MS"));
        lista.add(new Cidade("mRoMP2BvEmzdhraiIqwd","Montese ","MS"));
        lista.add(new Cidade("NhAXto3FoJ12CTcVFLfF","Morangas","MS"));
        lista.add(new Cidade("P5GyGZHfFLP0LMUojzmV","Morraria do Sul","MS"));
        lista.add(new Cidade("as0sTuSnj8hfcPE0Yzs1","Morumbi","MS"));
        lista.add(new Cidade("dlguxl88YKykEPwxSLy8","Mundo Novo","MS"));
        lista.add(new Cidade("58XLdRL7wi3WfFSGSds2","Naviraí","MS"));
        lista.add(new Cidade("hEdWZXVZ0YBxwlrovyri","Nhecolândia","MS"));
        lista.add(new Cidade("05miNebCwIISd79fxtLG","Nioaque","MS"));
        lista.add(new Cidade("RLEkSVUuoaBdYHQ74nMW","Nossa Senhora de Fátima","MS"));
        lista.add(new Cidade("fuT5x5kyUxVO9bFq7KYU","Nova Alvorada do Sul","MS"));
        lista.add(new Cidade("jSFT8dFtt1IDVDpHKhd1","Nova América ","MS"));
        lista.add(new Cidade("hJx31DnMP9mAdJpsB6Jk","Nova Andradina","MS"));
        lista.add(new Cidade("t9AfImTiCU8oOHz3NMbN","Nova Casa Verde ","MS"));
        lista.add(new Cidade("bNWEXP6BNBTGvZKuWGr8","Nova Esperança","MS"));
        lista.add(new Cidade("kU3Af8kwGKOA3kUwPyfT","Nova Jales","MS"));
        lista.add(new Cidade("oaldflo9uN3qLVD7OjsE","Novo Horizonte do Sul","MS"));
        lista.add(new Cidade("X3OmisG66X3vOovnysee","Oriente","MS"));
        lista.add(new Cidade("WxwpNiHUVgtnYuomzR8k","Paiaguás","MS"));
        lista.add(new Cidade("USgWpELqLyNwMJUqZcmb","Palmeiras ","MS"));
        lista.add(new Cidade("6ryOuE77IknGbmBuEzEu","Pana","MS"));
        lista.add(new Cidade("78LxiQhqfJMnBaLzRM1C","Panambi","MS"));
        lista.add(new Cidade("RGfYT6VdthqMV7Uz0kX3","Paraíso das Águas","MS"));
        lista.add(new Cidade("XYwS9yytD6UAtRxgRau2","Paranaíba","MS"));
        lista.add(new Cidade("tWTU7DhVRzrBrajRGEFK","Paranhos","MS"));
        lista.add(new Cidade("LqRQ2BvYFF3jriAP0RrH","Pedro Gomes","MS"));
        lista.add(new Cidade("5qzoz9bNCqZdCFKMy3V3","Picadinha","MS"));
        lista.add(new Cidade("pJ1CkpzXXtLzWRTNOEZH","Pirapora ","MS"));
        lista.add(new Cidade("Mjz6SAd1h0uDinCAHiWB","Piraputanga","MS"));
        lista.add(new Cidade("1dECQaUdWbaqrb0YGdqH","Ponta Porã","MS"));
        lista.add(new Cidade("TYIzB69ZoRorJSynP0Kk","Ponte Vermelha","MS"));
        lista.add(new Cidade("4gTFzuAUNmv9mvph22dY","Pontinha do Cocho","MS"));
        lista.add(new Cidade("mLzbvVdwaSdZdp4f75we","Porto Esperança","MS"));
        lista.add(new Cidade("Ust5THZY9jIBZm11OTuP","Porto Murtinho","MS"));
        lista.add(new Cidade("rOhuooS1PeBkSGmgQ3vQ","Porto Vilma ","MS"));
        lista.add(new Cidade("KuN7vMzQsoULkqRnuBvm","Porto XV de Novembro ","MS"));
        lista.add(new Cidade("7CH4iayRLYfsY2fqeC1f","Presidente Castelo","MS"));
        lista.add(new Cidade("1iASnvOZdV4qwVaacnqp","Prudêncio Thomaz ","MS"));
        lista.add(new Cidade("GGpl4BxxGkLqJXVmWHfU","Quebra Côco","MS"));
        lista.add(new Cidade("kTaImXUg1EpUxnuHsIr7","Quebracho","MS"));
        lista.add(new Cidade("QFr1eZriIHkbgvjiSR5c","Ribas do Rio Pardo","MS"));
        lista.add(new Cidade("Y1dWFK6OIKI1gAWlz6Ra","Rio Brilhante","MS"));
        lista.add(new Cidade("NFxEyzDl1W6cQ0xECknK","Rio Negro","MS"));
        lista.add(new Cidade("kz9qu7QTgXUbzFIDjlWp","Rio Verde de Mato Grosso","MS"));
        lista.add(new Cidade("44kIsEOluH1Pl7ipsevr","Rochedinho ","MS"));
        lista.add(new Cidade("sAKLi2g6w7qhERXHu2t9","Rochedo","MS"));
        lista.add(new Cidade("hrLHwpAZtZ8oCythceSX","Sanga Puitã ","MS"));
        lista.add(new Cidade("pf1FDoFkraAMb0Y2P242","Santa Rita do Pardo","MS"));
        lista.add(new Cidade("DLbjmcmz5uTTtwxQg3sT","Santa Terezinha","MS"));
        lista.add(new Cidade("Q1vr1BqyG2iWWkSGlA5o","São Gabriel do Oeste","MS"));
        lista.add(new Cidade("xlNQBIcslaWNAsyrD5fN","São João do Apore","MS"));
        lista.add(new Cidade("6QLSikMCnUaNfXcrH8G6","São José","MS"));
        lista.add(new Cidade("W8OwYf4NhAXe1mkktZP5","São José do Sucuriú","MS"));
        lista.add(new Cidade("zZhthsKONHhNfYg7p8fn","São Pedro","MS"));
        lista.add(new Cidade("B0sYWBFIR3hsFamrpk79","São Pedro ","MS"));
        lista.add(new Cidade("sFrwnYlszuLKx477g03D","São Romão","MS"));
        lista.add(new Cidade("uERHnUNWw0y1ePWyWM3S","Selvíria","MS"));
        lista.add(new Cidade("lwR0QOy6XjJfxtNBuxal","Sete Quedas","MS"));
        lista.add(new Cidade("KHeyS2Ju1P63g42ULMpP","Sidrolândia","MS"));
        lista.add(new Cidade("cHSlWwLeGZXbn1JJnMyh","Sonora","MS"));
        lista.add(new Cidade("jAcPAf7Uuf9May4EJ98G","Tacuru","MS"));
        lista.add(new Cidade("D1vzH8rCNHVHVXhmpDXn","Tamandaré","MS"));
        lista.add(new Cidade("oMEKEE3jBxetg6W66sMe","Taquari","MS"));
        lista.add(new Cidade("nSxhcaemU3UEAx4ZPqXC","Taquarussu","MS"));
        lista.add(new Cidade("kzTZ0U09ou47te5vO9UX","Taunay","MS"));
        lista.add(new Cidade("V0J82WAQKz11VtIEdBeO","Terenos","MS"));
        lista.add(new Cidade("b7gfBhV6uHZpFAhUH8ij","Três Lagoas","MS"));
        lista.add(new Cidade("0pzhPV3KPxDqYP6K8pkO","Velhacaria","MS"));
        lista.add(new Cidade("osLYFZ0rmGoKft7hA9AB","Vicentina","MS"));
        lista.add(new Cidade("kGtNDvaYNDlYc1y0fIF6","Vila Formosa","MS"));
        lista.add(new Cidade("1Et5qqszcAvUrSH4sjHL","Vila Marques ","MS"));
        lista.add(new Cidade("w8Te5nykwsyOuq72uSLJ","Vila Rica","MS"));
        lista.add(new Cidade("4hPNF0YJdp1hKYftrF80","Vila União ","MS"));
        lista.add(new Cidade("2Z0OD1KhUQ1QikMhcPd1","Vila Vargas","MS"));
        lista.add(new Cidade("oIo0O01fTAttD0ur8lUm","Vista Alegre ","MS"));

        return lista;
    }
}
