package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MS {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Água Boa", "MS"));
        lista.add(new Cidade("", "Água Clara", "MS"));
        lista.add(new Cidade("", "Albuquerque", "MS"));
        lista.add(new Cidade("", "Alcinópolis", "MS"));
        lista.add(new Cidade("", "Alto Sucuriú", "MS"));
        lista.add(new Cidade("", "Amambaí", "MS"));
        lista.add(new Cidade("", "Amandina ", "MS"));
        lista.add(new Cidade("", "Amolar", "MS"));
        lista.add(new Cidade("", "Anastácio", "MS"));
        lista.add(new Cidade("", "Anaurilândia", "MS"));
        lista.add(new Cidade("", "Angélica", "MS"));
        lista.add(new Cidade("", "Anhandui ", "MS"));
        lista.add(new Cidade("", "Antônio João", "MS"));
        lista.add(new Cidade("", "Aparecida do Taboado", "MS"));
        lista.add(new Cidade("", "Aquidauana", "MS"));
        lista.add(new Cidade("", "Aral Moreira", "MS"));
        lista.add(new Cidade("", "Arapuã ", "MS"));
        lista.add(new Cidade("", "Areado", "MS"));
        lista.add(new Cidade("", "Árvore Grande", "MS"));
        lista.add(new Cidade("", "Baianópolis", "MS"));
        lista.add(new Cidade("", "Bálsamo", "MS"));
        lista.add(new Cidade("", "Bandeirantes", "MS"));
        lista.add(new Cidade("", "Bataguassu", "MS"));
        lista.add(new Cidade("", "Batayporã", "MS"));
        lista.add(new Cidade("", "Baús", "MS"));
        lista.add(new Cidade("", "Bela Alvorada", "MS"));
        lista.add(new Cidade("", "Bela Vista", "MS"));
        lista.add(new Cidade("", "Bocajá", "MS"));
        lista.add(new Cidade("", "Bodoquena", "MS"));
        lista.add(new Cidade("", "Bom Fim", "MS"));
        lista.add(new Cidade("", "Bonito", "MS"));
        lista.add(new Cidade("", "Boqueirão", "MS"));
        lista.add(new Cidade("", "Brasilândia", "MS"));
        lista.add(new Cidade("", "Caarapó", "MS"));
        lista.add(new Cidade("", "Cabeceira do Apá ", "MS"));
        lista.add(new Cidade("", "Cachoeira", "MS"));
        lista.add(new Cidade("", "Camapuã", "MS"));
        lista.add(new Cidade("", "Camisão", "MS"));
        lista.add(new Cidade("", "Campestre", "MS"));
        lista.add(new Cidade("", "Campo Grande", "MS"));
        lista.add(new Cidade("", "Capão Seco", "MS"));
        lista.add(new Cidade("", "Caracol", "MS"));
        lista.add(new Cidade("", "Carumbé", "MS"));
        lista.add(new Cidade("", "Cassilândia", "MS"));
        lista.add(new Cidade("", "Chapadão do Sul", "MS"));
        lista.add(new Cidade("", "Cipolândia", "MS"));
        lista.add(new Cidade("", "Coimbra", "MS"));
        lista.add(new Cidade("", "Congonhas ", "MS"));
        lista.add(new Cidade("", "Corguinho", "MS"));
        lista.add(new Cidade("", "Coronel Sapucaia", "MS"));
        lista.add(new Cidade("", "Corumbá", "MS"));
        lista.add(new Cidade("", "Costa Rica", "MS"));
        lista.add(new Cidade("", "Coxim", "MS"));
        lista.add(new Cidade("", "Cristalina ", "MS"));
        lista.add(new Cidade("", "Cruzaltina ", "MS"));
        lista.add(new Cidade("", "Culturama ", "MS"));
        lista.add(new Cidade("", "Cupins", "MS"));
        lista.add(new Cidade("", "Debrasa", "MS"));
        lista.add(new Cidade("", "Deodápolis", "MS"));
        lista.add(new Cidade("", "Dois Irmãos do Buriti", "MS"));
        lista.add(new Cidade("", "Douradina", "MS"));
        lista.add(new Cidade("", "Dourados", "MS"));
        lista.add(new Cidade("", "Eldorado", "MS"));
        lista.add(new Cidade("", "Fátima do Sul", "MS"));
        lista.add(new Cidade("", "Figueirão", "MS"));
        lista.add(new Cidade("", "Garcias", "MS"));
        lista.add(new Cidade("", "Glória de Dourados", "MS"));
        lista.add(new Cidade("", "Guaçu", "MS"));
        lista.add(new Cidade("", "Guaçulândia ", "MS"));
        lista.add(new Cidade("", "Guadalupe do Alto Paraná", "MS"));
        lista.add(new Cidade("", "Guia Lopes da Laguna", "MS"));
        lista.add(new Cidade("", "Iguatemi", "MS"));
        lista.add(new Cidade("", "Ilha Comprida", "MS"));
        lista.add(new Cidade("", "Ilha Grande", "MS"));
        lista.add(new Cidade("", "Indaiá do Sul", "MS"));
        lista.add(new Cidade("", "Indaiá Grande", "MS"));
        lista.add(new Cidade("", "Indápolis ", "MS"));
        lista.add(new Cidade("", "Inocência", "MS"));
        lista.add(new Cidade("", "Ipezal ", "MS"));
        lista.add(new Cidade("", "Itahum ", "MS"));
        lista.add(new Cidade("", "Itaporã", "MS"));
        lista.add(new Cidade("", "Itaquiraí", "MS"));
        lista.add(new Cidade("", "Ivinhema", "MS"));
        lista.add(new Cidade("", "Jabuti", "MS"));
        lista.add(new Cidade("", "Jacareí", "MS"));
        lista.add(new Cidade("", "Japorã", "MS"));
        lista.add(new Cidade("", "Jaraguari", "MS"));
        lista.add(new Cidade("", "Jardim", "MS"));
        lista.add(new Cidade("", "Jateí", "MS"));
        lista.add(new Cidade("", "Jauru", "MS"));
        lista.add(new Cidade("", "Juscelândia", "MS"));
        lista.add(new Cidade("", "Jutí", "MS"));
        lista.add(new Cidade("", "Ladário", "MS"));
        lista.add(new Cidade("", "Lagoa Bonita ", "MS"));
        lista.add(new Cidade("", "Laguna Carapã", "MS"));
        lista.add(new Cidade("", "Maracaju", "MS"));
        lista.add(new Cidade("", "Miranda", "MS"));
        lista.add(new Cidade("", "Montese ", "MS"));
        lista.add(new Cidade("", "Morangas", "MS"));
        lista.add(new Cidade("", "Morraria do Sul", "MS"));
        lista.add(new Cidade("", "Morumbi", "MS"));
        lista.add(new Cidade("", "Mundo Novo", "MS"));
        lista.add(new Cidade("", "Naviraí", "MS"));
        lista.add(new Cidade("", "Nhecolândia", "MS"));
        lista.add(new Cidade("", "Nioaque", "MS"));
        lista.add(new Cidade("", "Nossa Senhora de Fátima", "MS"));
        lista.add(new Cidade("", "Nova Alvorada do Sul", "MS"));
        lista.add(new Cidade("", "Nova América ", "MS"));
        lista.add(new Cidade("", "Nova Andradina", "MS"));
        lista.add(new Cidade("", "Nova Casa Verde ", "MS"));
        lista.add(new Cidade("", "Nova Esperança", "MS"));
        lista.add(new Cidade("", "Nova Jales", "MS"));
        lista.add(new Cidade("", "Novo Horizonte do Sul", "MS"));
        lista.add(new Cidade("", "Oriente", "MS"));
        lista.add(new Cidade("", "Paiaguás", "MS"));
        lista.add(new Cidade("", "Palmeiras ", "MS"));
        lista.add(new Cidade("", "Pana", "MS"));
        lista.add(new Cidade("", "Panambi", "MS"));
        lista.add(new Cidade("", "Paraíso das Águas", "MS"));
        lista.add(new Cidade("", "Paranaíba", "MS"));
        lista.add(new Cidade("", "Paranhos", "MS"));
        lista.add(new Cidade("", "Pedro Gomes", "MS"));
        lista.add(new Cidade("", "Picadinha", "MS"));
        lista.add(new Cidade("", "Pirapora ", "MS"));
        lista.add(new Cidade("", "Piraputanga", "MS"));
        lista.add(new Cidade("", "Ponta Porã", "MS"));
        lista.add(new Cidade("", "Ponte Vermelha", "MS"));
        lista.add(new Cidade("", "Pontinha do Cocho", "MS"));
        lista.add(new Cidade("", "Porto Esperança", "MS"));
        lista.add(new Cidade("", "Porto Murtinho", "MS"));
        lista.add(new Cidade("", "Porto Vilma ", "MS"));
        lista.add(new Cidade("", "Porto XV de Novembro ", "MS"));
        lista.add(new Cidade("", "Presidente Castelo", "MS"));
        lista.add(new Cidade("", "Prudêncio Thomaz ", "MS"));
        lista.add(new Cidade("", "Quebra Côco", "MS"));
        lista.add(new Cidade("", "Quebracho", "MS"));
        lista.add(new Cidade("", "Ribas do Rio Pardo", "MS"));
        lista.add(new Cidade("", "Rio Brilhante", "MS"));
        lista.add(new Cidade("", "Rio Negro", "MS"));
        lista.add(new Cidade("", "Rio Verde de Mato Grosso", "MS"));
        lista.add(new Cidade("", "Rochedinho ", "MS"));
        lista.add(new Cidade("", "Rochedo", "MS"));
        lista.add(new Cidade("", "Sanga Puitã ", "MS"));
        lista.add(new Cidade("", "Santa Rita do Pardo", "MS"));
        lista.add(new Cidade("", "Santa Terezinha", "MS"));
        lista.add(new Cidade("", "São Gabriel do Oeste", "MS"));
        lista.add(new Cidade("", "São João do Apore", "MS"));
        lista.add(new Cidade("", "São José", "MS"));
        lista.add(new Cidade("", "São José do Sucuriú", "MS"));
        lista.add(new Cidade("", "São Pedro", "MS"));
        lista.add(new Cidade("", "São Pedro ", "MS"));
        lista.add(new Cidade("", "São Romão", "MS"));
        lista.add(new Cidade("", "Selvíria", "MS"));
        lista.add(new Cidade("", "Sete Quedas", "MS"));
        lista.add(new Cidade("", "Sidrolândia", "MS"));
        lista.add(new Cidade("", "Sonora", "MS"));
        lista.add(new Cidade("", "Tacuru", "MS"));
        lista.add(new Cidade("", "Tamandaré", "MS"));
        lista.add(new Cidade("", "Taquari", "MS"));
        lista.add(new Cidade("", "Taquarussu", "MS"));
        lista.add(new Cidade("", "Taunay", "MS"));
        lista.add(new Cidade("", "Terenos", "MS"));
        lista.add(new Cidade("", "Três Lagoas", "MS"));
        lista.add(new Cidade("", "Velhacaria", "MS"));
        lista.add(new Cidade("", "Vicentina", "MS"));
        lista.add(new Cidade("", "Vila Formosa", "MS"));
        lista.add(new Cidade("", "Vila Marques ", "MS"));
        lista.add(new Cidade("", "Vila Rica", "MS"));
        lista.add(new Cidade("", "Vila União ", "MS"));
        lista.add(new Cidade("", "Vila Vargas", "MS"));
        lista.add(new Cidade("", "Vista Alegre ", "MS"));
        return lista;
    }
}
