package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MT {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("ZkbvqDeu25MfCCRITnH7","Acorizal","MT"));
        lista.add(new Cidade("GJZ3YHWwOs285yLJGViz","Água Boa","MT"));
        lista.add(new Cidade("Mk0CjMWg61maysZ7exsJ","Água da Prata","MT"));
        lista.add(new Cidade("T1drTmzESAYyyoa9xq3X","Água Fria","MT"));
        lista.add(new Cidade("sR5NFfsZNvapdqkkYaCD","Aguaçu","MT"));
        lista.add(new Cidade("6ccwwPQRwcP77Bn1UX7U","Aguapeí","MT"));
        lista.add(new Cidade("edQ0kBlxMM7g8RXGKNjD","Águas Claras","MT"));
        lista.add(new Cidade("ybMjchjVxdyp89C7t8mu","Ainhumas","MT"));
        lista.add(new Cidade("cjjI9dP2lpGge8050D1U","Alcantilado","MT"));
        lista.add(new Cidade("6dj4IA80Cr1agybPb82J","Alta Floresta","MT"));
        lista.add(new Cidade("Xj8fubgqUHsh9xM5BFOW","Alto Araguaia","MT"));
        lista.add(new Cidade("7avfRWtC2crMr2fXFcWq","Alto Boa Vista","MT"));
        lista.add(new Cidade("3HzLqz4uW5Asqazgh74p","Alto Coité","MT"));
        lista.add(new Cidade("PTeVKjDVuQISvqYRTCht","Alto Garças","MT"));
        lista.add(new Cidade("dclNDZuSEvxyF31EngBP","Alto Juruena","MT"));
        lista.add(new Cidade("ahd8nzPeJRBifMPxHhoj","Alto Paraguai","MT"));
        lista.add(new Cidade("pmAqm8ihiEK2dgfa4QHa","Alto Paraíso","MT"));
        lista.add(new Cidade("wmthRg0kfDjJMZGELSYi","Alto Taquari","MT"));
        lista.add(new Cidade("MUdg0h6KtXKe4rDI09XX","Analândia do Norte","MT"));
        lista.add(new Cidade("hb7wK90DKmDwpgjOfug0","Apiacás","MT"));
        lista.add(new Cidade("JYymdpxXVxdzmXc8NbKk","Araguaiana","MT"));
        lista.add(new Cidade("aqzWpuEKtW0m69ZCpL0h","Araguainha","MT"));
        lista.add(new Cidade("oCWSCAhZ0hd5NonMO13z","Araputanga","MT"));
        lista.add(new Cidade("tOgopknFlfa7USDQ8DuL","Arenápolis","MT"));
        lista.add(new Cidade("edm4ihZ9E43TFo6YWkuV","Aripuanã","MT"));
        lista.add(new Cidade("5ZBBY7FwCZppTR1yKIvY","Arruda","MT"));
        lista.add(new Cidade("uZQWgkFEZZIatLgEX7XD","Assari","MT"));
        lista.add(new Cidade("DXTa2H7Yz5272mbdvPJF","Barão de Melgaço","MT"));
        lista.add(new Cidade("GwDL1gLuGFeeQNUgMF7d","Barra do Bugres","MT"));
        lista.add(new Cidade("PSk1rMj5cFMXTUpvNVCC","Barra do Garças","MT"));
        lista.add(new Cidade("EvKd9B32qmLdV6zo2Air","Batovi","MT"));
        lista.add(new Cidade("N4d757J9d2fIFaf3YVGD","Baús","MT"));
        lista.add(new Cidade("vqChQtas6e1Wzj0PeGIU","Bauxi","MT"));
        lista.add(new Cidade("6NLh4h0S61FR8mv9iT75","Bel Rios","MT"));
        lista.add(new Cidade("W9jBh9BdV4Mf0XWF40uv","Bezerro Branco","MT"));
        lista.add(new Cidade("1qvv3hS6CbEtooU7VapO","Boa Esperança","MT"));
        lista.add(new Cidade("LVy1Z8uozgigXIO31Z2M","Boa União","MT"));
        lista.add(new Cidade("GO4gTRnYkAcy8PKp36UE","Boa Vista","MT"));
        lista.add(new Cidade("lg9Gy9yXBBwwhs7kO8DM","Bocaiuval","MT"));
        lista.add(new Cidade("m66nbTjy4XyPDyhYmmt8","Bom Jesus do Araguaia","MT"));
        lista.add(new Cidade("aM2X1lFJScceaqdv3qqW","Bom Sucesso","MT"));
        lista.add(new Cidade("FJib9sZHTid2hGXa5YzP","Brasnorte","MT"));
        lista.add(new Cidade("iQdFmyyVb8QQ8iXc8TwY","Brianorte","MT"));
        lista.add(new Cidade("8lnGkzGUQZ7SKgDIN3tA","Buriti","MT"));
        lista.add(new Cidade("qx9AvKLQduciDtsga6QA","Cáceres","MT"));
        lista.add(new Cidade("Abb0ZD1XyAqUzYdfIHyd","Caite","MT"));
        lista.add(new Cidade("uvr6nTQeShsxzQXBMYFr","Campinápolis","MT"));
        lista.add(new Cidade("1b2XN6Y7PB9MCIiT5Pzc","Campo Novo do Parecis","MT"));
        lista.add(new Cidade("F9ew2qorgl8Rwu9BSMRn","Campo Verde","MT"));
        lista.add(new Cidade("AW8pnGT4ObbZKRGI5cSA","Campos de Júlio","MT"));
        lista.add(new Cidade("m296eQ6kDgsOmEjlPImO","Campos Novos","MT"));
        lista.add(new Cidade("M86dWJ3KExvVI0OS9xNJ","Canabrava do Norte","MT"));
        lista.add(new Cidade("pYldXC429JhkbBnL90OV","Canarana","MT"));
        lista.add(new Cidade("33wM70y5x0wH9L9rjmeJ","Cangas","MT"));
        lista.add(new Cidade("2fMMp86pEW8zQoHMsquY","Capão Grande","MT"));
        lista.add(new Cidade("8D9q8getxCz4IQtB2pdP","Capão Verde","MT"));
        lista.add(new Cidade("0qYPTrG8SnIYu8MV25qU","Caramujo","MT"));
        lista.add(new Cidade("e3vQgRgXOrtHYTk1SswY","Caravagio","MT"));
        lista.add(new Cidade("GkLcrUoOw41ZWgFY3hlP","Carlinda","MT"));
        lista.add(new Cidade("LwmeTtRAgvJbDr4Jlev2","Cassununga","MT"));
        lista.add(new Cidade("fh4luXrSiQ69vXf4zaRq","Castanheira","MT"));
        lista.add(new Cidade("R9tcZKJt5Y4dAMahgSiz","Catuai","MT"));
        lista.add(new Cidade("8RPMhMww3dF0hhRXhcP6","Chapada dos Guimarães","MT"));
        lista.add(new Cidade("9qVaGN8ghBugSRwzz5dJ","Cidade Morena","MT"));
        lista.add(new Cidade("WHSnBvF2Igb1XV05rPu9","Cláudia","MT"));
        lista.add(new Cidade("dRX36RVbLF2zvcIC6ZDd","Cocalinho","MT"));
        lista.add(new Cidade("mksXghicmrJZfLzqd8Ll","Colíder","MT"));
        lista.add(new Cidade("UzrupVnIwOnYJNQ7d9JH","Colniza","MT"));
        lista.add(new Cidade("WFyumbqEKD7iaDtWurZG","Colorado do Norte","MT"));
        lista.add(new Cidade("QygNeTfLcbpa0Ntd8d3g","Comodoro","MT"));
        lista.add(new Cidade("8zRHvXXstUYJEn0ydAsG","Comunidade Parque Boa Vista","MT"));
        lista.add(new Cidade("4xalJVnOVw3OKlOfrcrT","Confresa","MT"));
        lista.add(new Cidade("lutSlIpixIRyfMpODHZA","Conquista D'Oeste","MT"));
        lista.add(new Cidade("R5m6kRs1GMGm1eZs3UoA","Conselvan","MT"));
        lista.add(new Cidade("3jguL3KtntF70w06P3eS","Coronel Ponce","MT"));
        lista.add(new Cidade("CExeS15SVZDEMl3ETEr0","Cotrel","MT"));
        lista.add(new Cidade("memgVhPBgPT1z4nPgxAr","Cotriguaçu","MT"));
        lista.add(new Cidade("Sn6L3gG1TVhRz5Pii2np","Coxipó Açu","MT"));
        lista.add(new Cidade("Kge9k86dADOVIhuZsqpS","Coxipó da Ponte","MT"));
        lista.add(new Cidade("rTgKZEmgt6JZg56vDLom","Coxipó do Ouro","MT"));
        lista.add(new Cidade("8NXHvLDSIr2yFukhJdqz","Cristinópolis","MT"));
        lista.add(new Cidade("iUbPbbJ1qfef0KHNaslv","Cristo Rei","MT"));
        lista.add(new Cidade("0ClWbwaJhZOCeQCKti9G","Cuiabá","MT"));
        lista.add(new Cidade("RBGOkdgSYTpystmBT6ym","Curvelândia","MT"));
        lista.add(new Cidade("6XIQRUg2XER02w6GSWS6","Del Rios","MT"));
        lista.add(new Cidade("vAh6nnVaP3QVdaV0rh3l","Denise","MT"));
        lista.add(new Cidade("q3a28EcV7GRi8DnvJtWU","Diamantino","MT"));
        lista.add(new Cidade("UJ1yGYgliNvB3vlOTRKY","Dom Aquino","MT"));
        lista.add(new Cidade("dbwWsSWR8xho4s3WVBZm","Engenho","MT"));
        lista.add(new Cidade("A62YVYzbrfZ9th1BZ6oA","Engenho Velho","MT"));
        lista.add(new Cidade("LZYGDPYhFA7w2PLuKNKs","Entre Rios","MT"));
        lista.add(new Cidade("engGARkL8XlITOjDygn3","Estrela do Leste","MT"));
        lista.add(new Cidade("S8JrjpjJnQLgRBxlOyKx","Faval","MT"));
        lista.add(new Cidade("bXefIXbJxTaUzXWMxQyT","Fazenda de Cima","MT"));
        lista.add(new Cidade("xa6UCzQi8OSQjUxbeee5","Feliz Natal","MT"));
        lista.add(new Cidade("pZR2lNudBseCHKGfc3rd","Figueirópolis D'Oeste","MT"));
        lista.add(new Cidade("4OEReC6YbmSTzVoFbx83","Filadélfia","MT"));
        lista.add(new Cidade("qy38EyiO4ZoGGNJ3YPxq","Flor da Serra","MT"));
        lista.add(new Cidade("2s8QVH7vUOBACR3l6fQE","Fontanilhas","MT"));
        lista.add(new Cidade("gt6JFT2t632uSQbAxdYg","Gaúcha do Norte","MT"));
        lista.add(new Cidade("uHTh0dJCibYIyUwoOvKu","General Carneiro","MT"));
        lista.add(new Cidade("GFiyzU1mQYvU6u9pyCtN","Glória D'Oeste","MT"));
        lista.add(new Cidade("E9G9d8oFRHeKe4mzxpLG","Groslândia","MT"));
        lista.add(new Cidade("mGPHHnYDlfgF2wCUxpta","Guarantã do Norte","MT"));
        lista.add(new Cidade("DRwuIvGzPYu7sOBblnuP","Guariba","MT"));
        lista.add(new Cidade("0AyIkL1NKCInZvRa0hWr","Guarita","MT"));
        lista.add(new Cidade("Fp1CnhmBvLG5wn1p1XmB","Guiratinga","MT"));
        lista.add(new Cidade("KmaOM5XP6lgRW5xCgsZS","Horizonte do Oeste","MT"));
        lista.add(new Cidade("HNZSXTakjsqK1XNUf9bl","Indianápolis","MT"));
        lista.add(new Cidade("oLC21GYQ0w5QGT1lmCTB","Indiavaí","MT"));
        lista.add(new Cidade("wG2fnHFpLQepp4nLChG3","Ipiranga do Norte","MT"));
        lista.add(new Cidade("Pu5y4fbjTkEW4PGUHOaO","Irenópolis","MT"));
        lista.add(new Cidade("UfyfpycYQp8ycjecTBkH","Itamarati Norte","MT"));
        lista.add(new Cidade("mxbG7UEIvTfuLhyE0BfD","Itanhangá","MT"));
        lista.add(new Cidade("IcwkFaJIQHL5RPVKmHqE","Itaúba","MT"));
        lista.add(new Cidade("jFwvx4buPSc6pzIQ0kce","Itiquira","MT"));
        lista.add(new Cidade("dewHwcC8jtWDdULqh20K","Jaciara","MT"));
        lista.add(new Cidade("cQfb8iyMlTBx5BuOEXSE","Jangada","MT"));
        lista.add(new Cidade("B7Gof0ngCT3f2ToaIL9v","Jarudore","MT"));
        lista.add(new Cidade("oO7bcEC2HwwXv7agGi0H","Jatobá","MT"));
        lista.add(new Cidade("4EjmTXUVZv0DKIgn212y","Jauru","MT"));
        lista.add(new Cidade("Fj6EyrLqE52nKKjMPJFv","Joselândia","MT"));
        lista.add(new Cidade("wDyf1IlBjwtwe9mTzyNX","Juara","MT"));
        lista.add(new Cidade("b7WQUcbceTnP02bXN22V","Juína","MT"));
        lista.add(new Cidade("YVaxmG4Gq3ikR4QIEKQ5","Juruena","MT"));
        lista.add(new Cidade("XRVvqCsWqcRCHmvBY03Z","Juscimeira","MT"));
        lista.add(new Cidade("8iDiMmins4jzS2nInNO3","Lambari D'Oeste","MT"));
        lista.add(new Cidade("LmyAN4xHSbgRr6Hc5KLt","Lavouras","MT"));
        lista.add(new Cidade("ciCUAf5XpWnpSC7GNs5a","Lucas do Rio Verde","MT"));
        lista.add(new Cidade("abNE7h9Rklx1xWS3HI44","Lucialva","MT"));
        lista.add(new Cidade("tG02IRLCQmtZIA8FoCLE","Luciara","MT"));
        lista.add(new Cidade("1xWqXeYwTHsYu3sew7Dw","Machado","MT"));
        lista.add(new Cidade("MCOxi9D8SEUFMOIqvTyL","Marcelândia","MT"));
        lista.add(new Cidade("1kx9h6hcXJvaOjXToC4a","Marechal Rondon","MT"));
        lista.add(new Cidade("yFfVjCSKkDhjxiw1hyw3","Marzagão","MT"));
        lista.add(new Cidade("qZzvv6kEFxF9cYgSTIab","Mata Dentro","MT"));
        lista.add(new Cidade("svMEe6tKJCiJfxd9yCoH","Matupá","MT"));
        lista.add(new Cidade("ByHLw16u1fahmE9rmAiU","Mimoso","MT"));
        lista.add(new Cidade("FV7qboHZyluLasdOiGIw","Mirassol D'Oeste","MT"));
        lista.add(new Cidade("DNLjDYrVv44uglWbgSiG","Monte Castelo do Oeste","MT"));
        lista.add(new Cidade("2ToXCGfozc5O2J3JsQhl","Nobres","MT"));
        lista.add(new Cidade("rfB8xy4NOYOiTBX6dmdP","Nonoai do Norte","MT"));
        lista.add(new Cidade("D2T0PP2XOvIVbaNAToR9","Nortelândia","MT"));
        lista.add(new Cidade("VjQg5siHk3bzLJoPgNXZ","Nossa Senhora da Guia","MT"));
        lista.add(new Cidade("ODPRtRVMt48dISWhVwmH","Nossa Senhora do Livramento","MT"));
        lista.add(new Cidade("DXYq2BLcKGePtKoGSEhh","Nova Alvorada","MT"));
        lista.add(new Cidade("joc4hMstGlmGGWIQxO8I","Nova Bandeirantes","MT"));
        lista.add(new Cidade("yQTxTB3r5FlNCRpmbuxc","Nova Brasilândia","MT"));
        lista.add(new Cidade("woqBrvhFvz3owCP7LXv3","Nova Brasília","MT"));
        lista.add(new Cidade("9jBcDFC8LM3CC6cJsCct","Nova Cáceres","MT"));
        lista.add(new Cidade("SRMls5UZmGZVQF5I1Lcg","Nova Canaã do Norte","MT"));
        lista.add(new Cidade("G8wlo8x5i213zzcSCewL","Nova Catanduva","MT"));
        lista.add(new Cidade("Esc3nx0RfWYxLSAhO8oT","Nova Esperança","MT"));
        lista.add(new Cidade("5O4nMnilKgwvcuAD071S","Nova Galileia","MT"));
        lista.add(new Cidade("Jm1kwQdaPkQKtvPwPTR4","Nova Guarita","MT"));
        lista.add(new Cidade("rkMXQlwKB2KZQ23eoQQv","Nova Lacerda","MT"));
        lista.add(new Cidade("iFciey5WOGLYVBqlNXBP","Nova Marilândia","MT"));
        lista.add(new Cidade("o3rhJokBxmKdNyEQoEsO","Nova Maringá","MT"));
        lista.add(new Cidade("gVlF8ovA79h5znOnLkvJ","Nova Monte Verde","MT"));
        lista.add(new Cidade("ptZ68H4TgJQ4N4YzMSBQ","Nova Mutum","MT"));
        lista.add(new Cidade("ySdCVbjLrxJJZbth5uZW","Nova Nazaré","MT"));
        lista.add(new Cidade("8XQVtpap4TogDcSBEK9M","Nova Olímpia","MT"));
        lista.add(new Cidade("woLMN4CcvpFw2Sy6w9CB","Nova Primavera","MT"));
        lista.add(new Cidade("Gk46wddHqARxC6eAonSX","Nova Santa Helena","MT"));
        lista.add(new Cidade("RAo1YSdx8PZoqK5ZjCgl","Nova Ubiratã","MT"));
        lista.add(new Cidade("JshsmLqPX82Vj1q6sVp0","Nova Xavantina","MT"));
        lista.add(new Cidade("wVUFGYapBESXn8tpzRKS","Novo Diamantino","MT"));
        lista.add(new Cidade("x3TWZNeL8N6RUkb9Kr2l","Novo Eldorado","MT"));
        lista.add(new Cidade("V7MHt6Loyi4KxQUVJTzd","Novo Horizonte do Norte","MT"));
        lista.add(new Cidade("aVOKj5qJBKb8boWMVCdH","Novo Mato Grosso","MT"));
        lista.add(new Cidade("esfcvPlkCbYTpBP966D8","Novo Mundo","MT"));
        lista.add(new Cidade("8Uf496glDHo6FrQKaMX5","Novo Paraná","MT"));
        lista.add(new Cidade("9N9EnFwcwX51BywXgFfl","Novo Santo Antônio","MT"));
        lista.add(new Cidade("3kgVkMJLQ4DGwNR2COEa","Novo São Joaquim","MT"));
        lista.add(new Cidade("MDSXftSFIRvFj7bty5PX","Padronal","MT"));
        lista.add(new Cidade("dDpxf3d8vaP6RdyxWHok","Pai André","MT"));
        lista.add(new Cidade("8jyCbhSTkvx0fPJUxNZ1","Paraíso do Leste","MT"));
        lista.add(new Cidade("JRicXvugVlTnB2qZlYlr","Paranaitá","MT"));
        lista.add(new Cidade("XnyteIwbIYuucfG9RcnT","Paranatinga","MT"));
        lista.add(new Cidade("WTQfD0PKyaIMARQg1FAC","Parque Água Limpa","MT"));
        lista.add(new Cidade("xLdr3I6ped45EXZY7mz9","Passagem da Conceição","MT"));
        lista.add(new Cidade("kwmS1j2vAL3IFecWg0yP","Pedra Preta","MT"));
        lista.add(new Cidade("y0Pr4Qu4wr95Fgtmb8nJ","Pedro Neca","MT"));
        lista.add(new Cidade("JWlVErQOgLazX7zpyZx7","Peixoto de Azevedo","MT"));
        lista.add(new Cidade("jDYYMPfS3TZFMJm831Se","Piratininga","MT"));
        lista.add(new Cidade("B5EkeRTYooR0nmg1bb1j","Pirizal","MT"));
        lista.add(new Cidade("P33wzsLrDzARWINw1lxq","Placa de Santo Antônio","MT"));
        lista.add(new Cidade("tRxryROaAWb1suYnrDFZ","Planalto da Serra","MT"));
        lista.add(new Cidade("peX6qkyzX3inBbk9P7g4","Poconé","MT"));
        lista.add(new Cidade("h3pUUgsTmxB0yckPpjCd","Pombas","MT"));
        lista.add(new Cidade("dofqQcygq67LQ7QiuGUv","Pontal do Araguaia","MT"));
        lista.add(new Cidade("AKPrTXwmdY3EJqnNGgbb","Ponte Branca","MT"));
        lista.add(new Cidade("rIaAtqwx2DTXXXdPGMb2","Ponte de Pedra","MT"));
        lista.add(new Cidade("DRqMQuU4vGvqkyd02Yhj","Pontes e Lacerda","MT"));
        lista.add(new Cidade("ADu61XfI8eUWdfsDnPKo","Pontinópolis","MT"));
        lista.add(new Cidade("91tltFxY0E6w9mzaE66R","Porto Alegre do Norte","MT"));
        lista.add(new Cidade("fbQxzW1Pt3AWbRf0tJt9","Porto dos Gaúchos","MT"));
        lista.add(new Cidade("12pqHOSIzAfv35nf9WZw","Porto Esperidião","MT"));
        lista.add(new Cidade("fslVTqZdYBgwHFw91nzM","Porto Estrela","MT"));
        lista.add(new Cidade("Ofleslch3EasUhQUeMma","Poxoréu","MT"));
        lista.add(new Cidade("B2r6sDVvXnnbhgYMfcXD","Praia Rica","MT"));
        lista.add(new Cidade("5KulDJAS32MDzacKWg87","Primavera","MT"));
        lista.add(new Cidade("rzAJfrCGYzFdlTgc20FA","Primavera do Leste","MT"));
        lista.add(new Cidade("Z1ZKneprWBOJI4Cll6z5","Progresso","MT"));
        lista.add(new Cidade("j812WHERkro82x1DgaTe","Querência","MT"));
        lista.add(new Cidade("UvcCwGSnb3Gr0rKg8Cfb","Rancharia","MT"));
        lista.add(new Cidade("eQ8dyBPA0afwIW4yiH3M","Reserva do Cabaçal","MT"));
        lista.add(new Cidade("QE7e3rxXfPlYuq1FDRf6","Ribeirão Cascalheira","MT"));
        lista.add(new Cidade("cIs3gOAUe7EvmBQcfP6i","Ribeirão dos Cocais","MT"));
        lista.add(new Cidade("XTiVhic1NHDN16raIoCO","Ribeirãozinho","MT"));
        lista.add(new Cidade("Rakz9R8c6NcEsSzKTOWS","Rio Branco","MT"));
        lista.add(new Cidade("KyY82Yo19sCDEylB2I9M","Rio Manso","MT"));
        lista.add(new Cidade("9dniBK8WEnD4IyKfIpGL","Riolândia","MT"));
        lista.add(new Cidade("n41Aro1ohYT1B7u728bQ","Rondolândia","MT"));
        lista.add(new Cidade("5rqg5Ag5BA7IgRstLC7p","Rondonópolis","MT"));
        lista.add(new Cidade("JmjDBrUcHGcKRKKamcO8","Rosário Oeste","MT"));
        lista.add(new Cidade("u4OjGqvEVJ0ID0Bzcz9W","Salto do Céu","MT"));
        lista.add(new Cidade("GXE6iKv0xeSdUrMRNPOZ","Sangradouro","MT"));
        lista.add(new Cidade("C2529W5RKaKBGgvSd9kf","Santa Carmem","MT"));
        lista.add(new Cidade("wBhlOBxBGIXKZB5BlISn","Santa Cruz do Xingu","MT"));
        lista.add(new Cidade("KRc6bytqx5CkgpSgrwz6","Santa Elvira","MT"));
        lista.add(new Cidade("3aSBnlOk2W8DLgs5Eqju","Santa Fé","MT"));
        lista.add(new Cidade("598itLigh7WLkVgOudpo","Santa Rita","MT"));
        lista.add(new Cidade("0eVleVsHIbVmiumkZCoF","Santa Rita do Trivelato","MT"));
        lista.add(new Cidade("D1mHVlHXJPNIZh99QatU","Santa Terezinha","MT"));
        lista.add(new Cidade("aslpXOnxuwvVGPYXgC7g","Santa Terezinha do Rio Ferro","MT"));
        lista.add(new Cidade("6hygFxYpKPqX94Tq9zm4","Santaninha","MT"));
        lista.add(new Cidade("QzI6V39yLcT43UYvCwXj","Santo Afonso","MT"));
        lista.add(new Cidade("sqBWJ48ZgTv8nPjulDaP","Santo Antônio do Leste","MT"));
        lista.add(new Cidade("uitjm3u0OtRDl4RPzclp","Santo Antônio do Leverger","MT"));
        lista.add(new Cidade("xiDaVhGRgXN5iXNAEwme","Santo Antonio do Rio Bonito","MT"));
        lista.add(new Cidade("qMk180fLxbzE12kOVmsJ","São Cristovão","MT"));
        lista.add(new Cidade("Xhn6vucjQJCukNu9f6LS","São Félix do Araguaia","MT"));
        lista.add(new Cidade("htCnc4hJh6Rt5vRQl4kp","São Joaquim","MT"));
        lista.add(new Cidade("TZSXCrZnqa4EBCUqqmDX","São Jorge","MT"));
        lista.add(new Cidade("9jqGlgYCTlHE4HecUJYI","São José","MT"));
        lista.add(new Cidade("m75WAxvsQnvTJe3c0cS6","São José do Apuí","MT"));
        lista.add(new Cidade("fJM46N0qwzXqHcH3WHgX","São José do Pingador","MT"));
        lista.add(new Cidade("gMkV11gWdYdR3z3qYiMw","São José do Planalto","MT"));
        lista.add(new Cidade("dL0mo2EPsW81zZuIUiGs","São José do Povo","MT"));
        lista.add(new Cidade("bjJ8rhICybitLsgH4tUo","São José do Rio Claro","MT"));
        lista.add(new Cidade("RK6GknMw0t5kmFLJZpid","São José do Xingu","MT"));
        lista.add(new Cidade("pA1AO9BHvl3NGC2QpXkg","São José dos Quatro Marcos","MT"));
        lista.add(new Cidade("ZYnhxVZFH611WRjo4aPV","São Lourenço de Fátima","MT"));
        lista.add(new Cidade("ytEiSQGPp93MLGWH3stA","São Pedro da Cipa","MT"));
        lista.add(new Cidade("REdAaBmoXxqU7IJVpSCj","São Vicente","MT"));
        lista.add(new Cidade("ZraR78qpOeQ7C1D80dFm","Sapezal","MT"));
        lista.add(new Cidade("NnpGA4wFg3d8MKD2NZ2N","Selma","MT"));
        lista.add(new Cidade("R3LJ2J3QCllD1uYd5dCq","Serra Nova Dourada","MT"));
        lista.add(new Cidade("zOxohtrKWQNzCIAZ90H0","Sinop","MT"));
        lista.add(new Cidade("xm6DHKDlcmQbaFcHf6bk","Sonho Azul","MT"));
        lista.add(new Cidade("j9iJN2QS5yRPorff5MfY","Sorriso","MT"));
        lista.add(new Cidade("EWhsi2HjbBevquCHGnmF","Sucuri","MT"));
        lista.add(new Cidade("0gbXuCTfHPaGhAzKtq8M","Sumidouro","MT"));
        lista.add(new Cidade("dXIIp0wB7hnfRgEQkNjY","Tabaporã","MT"));
        lista.add(new Cidade("Rjihuu9VuhVraDSLdJxx","Tangará da Serra","MT"));
        lista.add(new Cidade("P7mUUYtkazzT4sqvCmSK","Tapirapua","MT"));
        lista.add(new Cidade("yB0wRaBXKbUeYuZ5LngU","Tapurah","MT"));
        lista.add(new Cidade("3Tg5aAxc410sPryIQo56","Terra Nova do Norte","MT"));
        lista.add(new Cidade("STtKbGJOmLV0wJp3jmqj","Terra Roxa","MT"));
        lista.add(new Cidade("NmeuDmxAcnLRDpI07E6G","Tesouro","MT"));
        lista.add(new Cidade("Tm2hUcSgl3FYvRrn7s9c","Toricueyje","MT"));
        lista.add(new Cidade("5QssHnw0V3Z7VRVmopQB","Torixoréu","MT"));
        lista.add(new Cidade("473mR62GjVnVVg4kqXzU","Três Pontes","MT"));
        lista.add(new Cidade("2njkgxBTdeINd0CR2fnK","União do Norte","MT"));
        lista.add(new Cidade("DUfoX6GbBVDNU8Idwofk","União do Sul","MT"));
        lista.add(new Cidade("WZ7h2vxu98i8ZrcvcmhW","Vale de São Domingos","MT"));
        lista.add(new Cidade("K935mJLZjO3H7NNkl1Op","Vale dos Sonhos","MT"));
        lista.add(new Cidade("hfwLxv4K82HhTYdFdDhS","Vale Rico","MT"));
        lista.add(new Cidade("Jsdu3zALkWNIqXRlbgZ3","Varginha","MT"));
        lista.add(new Cidade("bQD7IQ50ocXTFvhJZpBo","Várzea Grande","MT"));
        lista.add(new Cidade("py3dF17rPuHerNclzZqw","Vera","MT"));
        lista.add(new Cidade("2ZblbtdCDA3vRDQcRDGr","Veranópolis","MT"));
        lista.add(new Cidade("MietJUbQZWI5Z7czHoSt","Vila Atlântica","MT"));
        lista.add(new Cidade("8oVFUCoM3n76cPxwA6mH","Vila Bela da Santíssima Trindade","MT"));
        lista.add(new Cidade("U1LLWohkNHIC9Luiyo5L","Vila Bueno","MT"));
        lista.add(new Cidade("0fvMV1tUycpFYcMwgoQt","Vila Cardoso","MT"));
        lista.add(new Cidade("X0RYrJcxJPwTULlEy2Gy","Vila Mutum","MT"));
        lista.add(new Cidade("rEgrXfvSMoGJ7ha07oSx","Vila Operária","MT"));
        lista.add(new Cidade("91v6Gb1i31d4xKm0XAIf","Vila Paulista","MT"));
        lista.add(new Cidade("PLY3SL9wwYXuwvW3Dgcr","Vila Progresso","MT"));
        lista.add(new Cidade("oGxDDI5FRZI8U3ukMhCh","Vila Rica","MT"));

        return lista;
    }
}
