package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class MT {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Acorizal", "MT"));
        lista.add(new Cidade("", "Água Boa", "MT"));
        lista.add(new Cidade("", "Água da Prata", "MT"));
        lista.add(new Cidade("", "Água Fria", "MT"));
        lista.add(new Cidade("", "Aguaçu", "MT"));
        lista.add(new Cidade("", "Aguapeí", "MT"));
        lista.add(new Cidade("", "Águas Claras", "MT"));
        lista.add(new Cidade("", "Ainhumas", "MT"));
        lista.add(new Cidade("", "Alcantilado", "MT"));
        lista.add(new Cidade("", "Alta Floresta", "MT"));
        lista.add(new Cidade("", "Alto Araguaia", "MT"));
        lista.add(new Cidade("", "Alto Boa Vista", "MT"));
        lista.add(new Cidade("", "Alto Coité", "MT"));
        lista.add(new Cidade("", "Alto Garças", "MT"));
        lista.add(new Cidade("", "Alto Juruena", "MT"));
        lista.add(new Cidade("", "Alto Paraguai", "MT"));
        lista.add(new Cidade("", "Alto Paraíso", "MT"));
        lista.add(new Cidade("", "Alto Taquari", "MT"));
        lista.add(new Cidade("", "Analândia do Norte", "MT"));
        lista.add(new Cidade("", "Apiacás", "MT"));
        lista.add(new Cidade("", "Araguaiana", "MT"));
        lista.add(new Cidade("", "Araguainha", "MT"));
        lista.add(new Cidade("", "Araputanga", "MT"));
        lista.add(new Cidade("", "Arenápolis", "MT"));
        lista.add(new Cidade("", "Aripuanã", "MT"));
        lista.add(new Cidade("", "Arruda", "MT"));
        lista.add(new Cidade("", "Assari", "MT"));
        lista.add(new Cidade("", "Barão de Melgaço", "MT"));
        lista.add(new Cidade("", "Barra do Bugres", "MT"));
        lista.add(new Cidade("", "Barra do Garças", "MT"));
        lista.add(new Cidade("", "Batovi", "MT"));
        lista.add(new Cidade("", "Baús", "MT"));
        lista.add(new Cidade("", "Bauxi", "MT"));
        lista.add(new Cidade("", "Bel Rios", "MT"));
        lista.add(new Cidade("", "Bezerro Branco", "MT"));
        lista.add(new Cidade("", "Boa Esperança", "MT"));
        lista.add(new Cidade("", "Boa União", "MT"));
        lista.add(new Cidade("", "Boa Vista", "MT"));
        lista.add(new Cidade("", "Bocaiuval", "MT"));
        lista.add(new Cidade("", "Bom Jesus do Araguaia", "MT"));
        lista.add(new Cidade("", "Bom Sucesso", "MT"));
        lista.add(new Cidade("", "Brasnorte", "MT"));
        lista.add(new Cidade("", "Brianorte", "MT"));
        lista.add(new Cidade("", "Buriti", "MT"));
        lista.add(new Cidade("", "Cáceres", "MT"));
        lista.add(new Cidade("", "Caite", "MT"));
        lista.add(new Cidade("", "Campinápolis", "MT"));
        lista.add(new Cidade("", "Campo Novo do Parecis", "MT"));
        lista.add(new Cidade("", "Campo Verde", "MT"));
        lista.add(new Cidade("", "Campos de Júlio", "MT"));
        lista.add(new Cidade("", "Campos Novos", "MT"));
        lista.add(new Cidade("", "Canabrava do Norte", "MT"));
        lista.add(new Cidade("", "Canarana", "MT"));
        lista.add(new Cidade("", "Cangas", "MT"));
        lista.add(new Cidade("", "Capão Grande", "MT"));
        lista.add(new Cidade("", "Capão Verde", "MT"));
        lista.add(new Cidade("", "Caramujo", "MT"));
        lista.add(new Cidade("", "Caravagio", "MT"));
        lista.add(new Cidade("", "Carlinda", "MT"));
        lista.add(new Cidade("", "Cassununga", "MT"));
        lista.add(new Cidade("", "Castanheira", "MT"));
        lista.add(new Cidade("", "Catuai", "MT"));
        lista.add(new Cidade("", "Chapada dos Guimarães", "MT"));
        lista.add(new Cidade("", "Cidade Morena", "MT"));
        lista.add(new Cidade("", "Cláudia", "MT"));
        lista.add(new Cidade("", "Cocalinho", "MT"));
        lista.add(new Cidade("", "Colíder", "MT"));
        lista.add(new Cidade("", "Colniza", "MT"));
        lista.add(new Cidade("", "Colorado do Norte", "MT"));
        lista.add(new Cidade("", "Comodoro", "MT"));
        lista.add(new Cidade("", "Comunidade Parque Boa Vista", "MT"));
        lista.add(new Cidade("", "Confresa", "MT"));
        lista.add(new Cidade("", "Conquista D'Oeste", "MT"));
        lista.add(new Cidade("", "Conselvan", "MT"));
        lista.add(new Cidade("", "Coronel Ponce", "MT"));
        lista.add(new Cidade("", "Cotrel", "MT"));
        lista.add(new Cidade("", "Cotriguaçu", "MT"));
        lista.add(new Cidade("", "Coxipó Açu", "MT"));
        lista.add(new Cidade("", "Coxipó da Ponte", "MT"));
        lista.add(new Cidade("", "Coxipó do Ouro", "MT"));
        lista.add(new Cidade("", "Cristinópolis", "MT"));
        lista.add(new Cidade("", "Cristo Rei", "MT"));
        lista.add(new Cidade("", "Cuiabá", "MT"));
        lista.add(new Cidade("", "Curvelândia", "MT"));
        lista.add(new Cidade("", "Del Rios", "MT"));
        lista.add(new Cidade("", "Denise", "MT"));
        lista.add(new Cidade("", "Diamantino", "MT"));
        lista.add(new Cidade("", "Dom Aquino", "MT"));
        lista.add(new Cidade("", "Engenho", "MT"));
        lista.add(new Cidade("", "Engenho Velho", "MT"));
        lista.add(new Cidade("", "Entre Rios", "MT"));
        lista.add(new Cidade("", "Estrela do Leste", "MT"));
        lista.add(new Cidade("", "Faval", "MT"));
        lista.add(new Cidade("", "Fazenda de Cima", "MT"));
        lista.add(new Cidade("", "Feliz Natal", "MT"));
        lista.add(new Cidade("", "Figueirópolis D'Oeste", "MT"));
        lista.add(new Cidade("", "Filadélfia", "MT"));
        lista.add(new Cidade("", "Flor da Serra", "MT"));
        lista.add(new Cidade("", "Fontanilhas", "MT"));
        lista.add(new Cidade("", "Gaúcha do Norte", "MT"));
        lista.add(new Cidade("", "General Carneiro", "MT"));
        lista.add(new Cidade("", "Glória D'Oeste", "MT"));
        lista.add(new Cidade("", "Groslândia", "MT"));
        lista.add(new Cidade("", "Guarantã do Norte", "MT"));
        lista.add(new Cidade("", "Guariba", "MT"));
        lista.add(new Cidade("", "Guarita", "MT"));
        lista.add(new Cidade("", "Guiratinga", "MT"));
        lista.add(new Cidade("", "Horizonte do Oeste", "MT"));
        lista.add(new Cidade("", "Indianápolis", "MT"));
        lista.add(new Cidade("", "Indiavaí", "MT"));
        lista.add(new Cidade("", "Ipiranga do Norte", "MT"));
        lista.add(new Cidade("", "Irenópolis", "MT"));
        lista.add(new Cidade("", "Itamarati Norte", "MT"));
        lista.add(new Cidade("", "Itanhangá", "MT"));
        lista.add(new Cidade("", "Itaúba", "MT"));
        lista.add(new Cidade("", "Itiquira", "MT"));
        lista.add(new Cidade("", "Jaciara", "MT"));
        lista.add(new Cidade("", "Jangada", "MT"));
        lista.add(new Cidade("", "Jarudore", "MT"));
        lista.add(new Cidade("", "Jatobá", "MT"));
        lista.add(new Cidade("", "Jauru", "MT"));
        lista.add(new Cidade("", "Joselândia", "MT"));
        lista.add(new Cidade("", "Juara", "MT"));
        lista.add(new Cidade("", "Juína", "MT"));
        lista.add(new Cidade("", "Juruena", "MT"));
        lista.add(new Cidade("", "Juscimeira", "MT"));
        lista.add(new Cidade("", "Lambari D'Oeste", "MT"));
        lista.add(new Cidade("", "Lavouras", "MT"));
        lista.add(new Cidade("", "Lucas do Rio Verde", "MT"));
        lista.add(new Cidade("", "Lucialva", "MT"));
        lista.add(new Cidade("", "Luciara", "MT"));
        lista.add(new Cidade("", "Machado", "MT"));
        lista.add(new Cidade("", "Marcelândia", "MT"));
        lista.add(new Cidade("", "Marechal Rondon", "MT"));
        lista.add(new Cidade("", "Marzagão", "MT"));
        lista.add(new Cidade("", "Mata Dentro", "MT"));
        lista.add(new Cidade("", "Matupá", "MT"));
        lista.add(new Cidade("", "Mimoso", "MT"));
        lista.add(new Cidade("", "Mirassol D'Oeste", "MT"));
        lista.add(new Cidade("", "Monte Castelo do Oeste", "MT"));
        lista.add(new Cidade("", "Nobres", "MT"));
        lista.add(new Cidade("", "Nonoai do Norte", "MT"));
        lista.add(new Cidade("", "Nortelândia", "MT"));
        lista.add(new Cidade("", "Nossa Senhora da Guia", "MT"));
        lista.add(new Cidade("", "Nossa Senhora do Livramento", "MT"));
        lista.add(new Cidade("", "Nova Alvorada", "MT"));
        lista.add(new Cidade("", "Nova Bandeirantes", "MT"));
        lista.add(new Cidade("", "Nova Brasilândia", "MT"));
        lista.add(new Cidade("", "Nova Brasília", "MT"));
        lista.add(new Cidade("", "Nova Cáceres", "MT"));
        lista.add(new Cidade("", "Nova Canaã do Norte", "MT"));
        lista.add(new Cidade("", "Nova Catanduva", "MT"));
        lista.add(new Cidade("", "Nova Esperança", "MT"));
        lista.add(new Cidade("", "Nova Galileia", "MT"));
        lista.add(new Cidade("", "Nova Guarita", "MT"));
        lista.add(new Cidade("", "Nova Lacerda", "MT"));
        lista.add(new Cidade("", "Nova Marilândia", "MT"));
        lista.add(new Cidade("", "Nova Maringá", "MT"));
        lista.add(new Cidade("", "Nova Monte Verde", "MT"));
        lista.add(new Cidade("", "Nova Mutum", "MT"));
        lista.add(new Cidade("", "Nova Nazaré", "MT"));
        lista.add(new Cidade("", "Nova Olímpia", "MT"));
        lista.add(new Cidade("", "Nova Primavera", "MT"));
        lista.add(new Cidade("", "Nova Santa Helena", "MT"));
        lista.add(new Cidade("", "Nova Ubiratã", "MT"));
        lista.add(new Cidade("", "Nova Xavantina", "MT"));
        lista.add(new Cidade("", "Novo Diamantino", "MT"));
        lista.add(new Cidade("", "Novo Eldorado", "MT"));
        lista.add(new Cidade("", "Novo Horizonte do Norte", "MT"));
        lista.add(new Cidade("", "Novo Mato Grosso", "MT"));
        lista.add(new Cidade("", "Novo Mundo", "MT"));
        lista.add(new Cidade("", "Novo Paraná", "MT"));
        lista.add(new Cidade("", "Novo Santo Antônio", "MT"));
        lista.add(new Cidade("", "Novo São Joaquim", "MT"));
        lista.add(new Cidade("", "Padronal", "MT"));
        lista.add(new Cidade("", "Pai André", "MT"));
        lista.add(new Cidade("", "Paraíso do Leste", "MT"));
        lista.add(new Cidade("", "Paranaitá", "MT"));
        lista.add(new Cidade("", "Paranatinga", "MT"));
        lista.add(new Cidade("", "Parque Água Limpa", "MT"));
        lista.add(new Cidade("", "Passagem da Conceição", "MT"));
        lista.add(new Cidade("", "Pedra Preta", "MT"));
        lista.add(new Cidade("", "Pedro Neca", "MT"));
        lista.add(new Cidade("", "Peixoto de Azevedo", "MT"));
        lista.add(new Cidade("", "Piratininga", "MT"));
        lista.add(new Cidade("", "Pirizal", "MT"));
        lista.add(new Cidade("", "Placa de Santo Antônio", "MT"));
        lista.add(new Cidade("", "Planalto da Serra", "MT"));
        lista.add(new Cidade("", "Poconé", "MT"));
        lista.add(new Cidade("", "Pombas", "MT"));
        lista.add(new Cidade("", "Pontal do Araguaia", "MT"));
        lista.add(new Cidade("", "Ponte Branca", "MT"));
        lista.add(new Cidade("", "Ponte de Pedra", "MT"));
        lista.add(new Cidade("", "Pontes e Lacerda", "MT"));
        lista.add(new Cidade("", "Pontinópolis", "MT"));
        lista.add(new Cidade("", "Porto Alegre do Norte", "MT"));
        lista.add(new Cidade("", "Porto dos Gaúchos", "MT"));
        lista.add(new Cidade("", "Porto Esperidião", "MT"));
        lista.add(new Cidade("", "Porto Estrela", "MT"));
        lista.add(new Cidade("", "Poxoréu", "MT"));
        lista.add(new Cidade("", "Praia Rica", "MT"));
        lista.add(new Cidade("", "Primavera", "MT"));
        lista.add(new Cidade("", "Primavera do Leste", "MT"));
        lista.add(new Cidade("", "Progresso", "MT"));
        lista.add(new Cidade("", "Querência", "MT"));
        lista.add(new Cidade("", "Rancharia", "MT"));
        lista.add(new Cidade("", "Reserva do Cabaçal", "MT"));
        lista.add(new Cidade("", "Ribeirão Cascalheira", "MT"));
        lista.add(new Cidade("", "Ribeirão dos Cocais", "MT"));
        lista.add(new Cidade("", "Ribeirãozinho", "MT"));
        lista.add(new Cidade("", "Rio Branco", "MT"));
        lista.add(new Cidade("", "Rio Manso", "MT"));
        lista.add(new Cidade("", "Riolândia", "MT"));
        lista.add(new Cidade("", "Rondolândia", "MT"));
        lista.add(new Cidade("", "Rondonópolis", "MT"));
        lista.add(new Cidade("", "Rosário Oeste", "MT"));
        lista.add(new Cidade("", "Salto do Céu", "MT"));
        lista.add(new Cidade("", "Sangradouro", "MT"));
        lista.add(new Cidade("", "Santa Carmem", "MT"));
        lista.add(new Cidade("", "Santa Cruz do Xingu", "MT"));
        lista.add(new Cidade("", "Santa Elvira", "MT"));
        lista.add(new Cidade("", "Santa Fé", "MT"));
        lista.add(new Cidade("", "Santa Rita", "MT"));
        lista.add(new Cidade("", "Santa Rita do Trivelato", "MT"));
        lista.add(new Cidade("", "Santa Terezinha", "MT"));
        lista.add(new Cidade("", "Santa Terezinha do Rio Ferro", "MT"));
        lista.add(new Cidade("", "Santaninha", "MT"));
        lista.add(new Cidade("", "Santo Afonso", "MT"));
        lista.add(new Cidade("", "Santo Antônio do Leste", "MT"));
        lista.add(new Cidade("", "Santo Antônio do Leverger", "MT"));
        lista.add(new Cidade("", "Santo Antonio do Rio Bonito", "MT"));
        lista.add(new Cidade("", "São Cristovão", "MT"));
        lista.add(new Cidade("", "São Félix do Araguaia", "MT"));
        lista.add(new Cidade("", "São Joaquim", "MT"));
        lista.add(new Cidade("", "São Jorge", "MT"));
        lista.add(new Cidade("", "São José", "MT"));
        lista.add(new Cidade("", "São José do Apuí", "MT"));
        lista.add(new Cidade("", "São José do Pingador", "MT"));
        lista.add(new Cidade("", "São José do Planalto", "MT"));
        lista.add(new Cidade("", "São José do Povo", "MT"));
        lista.add(new Cidade("", "São José do Rio Claro", "MT"));
        lista.add(new Cidade("", "São José do Xingu", "MT"));
        lista.add(new Cidade("", "São José dos Quatro Marcos", "MT"));
        lista.add(new Cidade("", "São Lourenço de Fátima", "MT"));
        lista.add(new Cidade("", "São Pedro da Cipa", "MT"));
        lista.add(new Cidade("", "São Vicente", "MT"));
        lista.add(new Cidade("", "Sapezal", "MT"));
        lista.add(new Cidade("", "Selma", "MT"));
        lista.add(new Cidade("", "Serra Nova Dourada", "MT"));
        lista.add(new Cidade("", "Sinop", "MT"));
        lista.add(new Cidade("", "Sonho Azul", "MT"));
        lista.add(new Cidade("", "Sorriso", "MT"));
        lista.add(new Cidade("", "Sucuri", "MT"));
        lista.add(new Cidade("", "Sumidouro", "MT"));
        lista.add(new Cidade("", "Tabaporã", "MT"));
        lista.add(new Cidade("", "Tangará da Serra", "MT"));
        lista.add(new Cidade("", "Tapirapua", "MT"));
        lista.add(new Cidade("", "Tapurah", "MT"));
        lista.add(new Cidade("", "Terra Nova do Norte", "MT"));
        lista.add(new Cidade("", "Terra Roxa", "MT"));
        lista.add(new Cidade("", "Tesouro", "MT"));
        lista.add(new Cidade("", "Toricueyje", "MT"));
        lista.add(new Cidade("", "Torixoréu", "MT"));
        lista.add(new Cidade("", "Três Pontes", "MT"));
        lista.add(new Cidade("", "União do Norte", "MT"));
        lista.add(new Cidade("", "União do Sul", "MT"));
        lista.add(new Cidade("", "Vale de São Domingos", "MT"));
        lista.add(new Cidade("", "Vale dos Sonhos", "MT"));
        lista.add(new Cidade("", "Vale Rico", "MT"));
        lista.add(new Cidade("", "Varginha", "MT"));
        lista.add(new Cidade("", "Várzea Grande", "MT"));
        lista.add(new Cidade("", "Vera", "MT"));
        lista.add(new Cidade("", "Veranópolis", "MT"));
        lista.add(new Cidade("", "Vila Atlântica", "MT"));
        lista.add(new Cidade("", "Vila Bela da Santíssima Trindade", "MT"));
        lista.add(new Cidade("", "Vila Bueno", "MT"));
        lista.add(new Cidade("", "Vila Cardoso", "MT"));
        lista.add(new Cidade("", "Vila Mutum", "MT"));
        lista.add(new Cidade("", "Vila Operária", "MT"));
        lista.add(new Cidade("", "Vila Paulista", "MT"));
        lista.add(new Cidade("", "Vila Progresso", "MT"));
        lista.add(new Cidade("", "Vila Rica", "MT"));
        return lista;
    }
}
