package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Abaetetuba", "PA"));
        lista.add(new Cidade("", "Abel Figueiredo", "PA"));
        lista.add(new Cidade("", "Acará", "PA"));
        lista.add(new Cidade("", "Afuá", "PA"));
        lista.add(new Cidade("", "Agrópolis Bela Vista", "PA"));
        lista.add(new Cidade("", "Água Azul do Norte", "PA"));
        lista.add(new Cidade("", "Água Fria", "PA"));
        lista.add(new Cidade("", "Alenquer", "PA"));
        lista.add(new Cidade("", "Algodoal", "PA"));
        lista.add(new Cidade("", "Almeirim", "PA"));
        lista.add(new Cidade("", "Almoço", "PA"));
        lista.add(new Cidade("", "Alta Pará", "PA"));
        lista.add(new Cidade("", "Altamira", "PA"));
        lista.add(new Cidade("", "Alter do Chão", "PA"));
        lista.add(new Cidade("", "Alvorada", "PA"));
        lista.add(new Cidade("", "Americano", "PA"));
        lista.add(new Cidade("", "Anajás", "PA"));
        lista.add(new Cidade("", "Ananindeua", "PA"));
        lista.add(new Cidade("", "Anapu", "PA"));
        lista.add(new Cidade("", "Antônio Lemos", "PA"));
        lista.add(new Cidade("", "Apeú", "PA"));
        lista.add(new Cidade("", "Apinagés", "PA"));
        lista.add(new Cidade("", "Arapixuna", "PA"));
        lista.add(new Cidade("", "Araquaim", "PA"));
        lista.add(new Cidade("", "Arco-Íris", "PA"));
        lista.add(new Cidade("", "Areias", "PA"));
        lista.add(new Cidade("", "Arumanduba", "PA"));
        lista.add(new Cidade("", "Aruri", "PA"));
        lista.add(new Cidade("", "Aturiaí", "PA"));
        lista.add(new Cidade("", "Augusto Corrêa", "PA"));
        lista.add(new Cidade("", "Aurora do Pará", "PA"));
        lista.add(new Cidade("", "Aveiro", "PA"));
        lista.add(new Cidade("", "Bagre", "PA"));
        lista.add(new Cidade("", "Baião", "PA"));
        lista.add(new Cidade("", "Bannach", "PA"));
        lista.add(new Cidade("", "Barcarena", "PA"));
        lista.add(new Cidade("", "Barreira Branca", "PA"));
        lista.add(new Cidade("", "Barreira dos Campos", "PA"));
        lista.add(new Cidade("", "Barreiras", "PA"));
        lista.add(new Cidade("", "Baturité", "PA"));
        lista.add(new Cidade("", "Beja", "PA"));
        lista.add(new Cidade("", "Bela Vista do Caracol", "PA"));
        lista.add(new Cidade("", "Belém", "PA"));
        lista.add(new Cidade("", "Belo Monte", "PA"));
        lista.add(new Cidade("", "Belterra", "PA"));
        lista.add(new Cidade("", "Benevides", "PA"));
        lista.add(new Cidade("", "Benfica", "PA"));
        lista.add(new Cidade("", "Boa Esperança", "PA"));
        lista.add(new Cidade("", "Boa Fé", "PA"));
        lista.add(new Cidade("", "Boa Sorte", "PA"));
        lista.add(new Cidade("", "Boa Vista do Iririteua", "PA"));
        lista.add(new Cidade("", "Boim", "PA"));
        lista.add(new Cidade("", "Bom Jardim", "PA"));
        lista.add(new Cidade("", "Bom Jesus do Tocantins", "PA"));
        lista.add(new Cidade("", "Bonito", "PA"));
        lista.add(new Cidade("", "Bragança", "PA"));
        lista.add(new Cidade("", "Brasil Novo", "PA"));
        lista.add(new Cidade("", "Brasília Legal", "PA"));
        lista.add(new Cidade("", "Brejo do Meio", "PA"));
        lista.add(new Cidade("", "Brejo Grande do Araguaia", "PA"));
        lista.add(new Cidade("", "Breu Branco", "PA"));
        lista.add(new Cidade("", "Breves", "PA"));
        lista.add(new Cidade("", "Bujaru", "PA"));
        lista.add(new Cidade("", "Cachoeira da Serra", "PA"));
        lista.add(new Cidade("", "Cachoeira do Arari", "PA"));
        lista.add(new Cidade("", "Cachoeira do Piriá", "PA"));
        lista.add(new Cidade("", "Cafezal", "PA"));
        lista.add(new Cidade("", "Cairari", "PA"));
        lista.add(new Cidade("", "Caju", "PA"));
        lista.add(new Cidade("", "Câmara do Marajó", "PA"));
        lista.add(new Cidade("", "Cambuquira", "PA"));
        lista.add(new Cidade("", "Cametá", "PA"));
        lista.add(new Cidade("", "Camiranga", "PA"));
        lista.add(new Cidade("", "Canaã dos Carajás", "PA"));
        lista.add(new Cidade("", "Capanema", "PA"));
        lista.add(new Cidade("", "Capitão Poço", "PA"));
        lista.add(new Cidade("", "Caracará do Arari", "PA"));
        lista.add(new Cidade("", "Caracol", "PA"));
        lista.add(new Cidade("", "Carajás", "PA"));
        lista.add(new Cidade("", "Carapajó", "PA"));
        lista.add(new Cidade("", "Caraparu", "PA"));
        lista.add(new Cidade("", "Caratateua", "PA"));
        lista.add(new Cidade("", "Caripi", "PA"));
        lista.add(new Cidade("", "Carrazedo", "PA"));
        lista.add(new Cidade("", "Casa de Tábua", "PA"));
        lista.add(new Cidade("", "Castanhal", "PA"));
        lista.add(new Cidade("", "Castelo dos Sonhos", "PA"));
        lista.add(new Cidade("", "Chaves", "PA"));
        lista.add(new Cidade("", "Colares", "PA"));
        lista.add(new Cidade("", "Conceição", "PA"));
        lista.add(new Cidade("", "Conceição do Araguaia", "PA"));
        lista.add(new Cidade("", "Concórdia do Pará", "PA"));
        lista.add(new Cidade("", "Condeixa", "PA"));
        lista.add(new Cidade("", "Coqueiro", "PA"));
        lista.add(new Cidade("", "Cripurizão", "PA"));
        lista.add(new Cidade("", "Cripurizinho", "PA"));
        lista.add(new Cidade("", "Cuiú-Cuiú", "PA"));
        lista.add(new Cidade("", "Cumaru do Norte", "PA"));
        lista.add(new Cidade("", "Curionópolis", "PA"));
        lista.add(new Cidade("", "Curralinho", "PA"));
        lista.add(new Cidade("", "Curuá", "PA"));
        lista.add(new Cidade("", "Curuaí", "PA"));
        lista.add(new Cidade("", "Curuçá", "PA"));
        lista.add(new Cidade("", "Curuçambaba", "PA"));
        lista.add(new Cidade("", "Curumu", "PA"));
        lista.add(new Cidade("", "Dom Eliseu", "PA"));
        lista.add(new Cidade("", "Eldorado dos Carajás", "PA"));
        lista.add(new Cidade("", "Emboraí", "PA"));
        lista.add(new Cidade("", "Espírito Santo do Tauá", "PA"));
        lista.add(new Cidade("", "Faro", "PA"));
        lista.add(new Cidade("", "Fernandes Belo", "PA"));
        lista.add(new Cidade("", "Flexal", "PA"));
        lista.add(new Cidade("", "Floresta", "PA"));
        lista.add(new Cidade("", "Floresta do Araguaia", "PA"));
        lista.add(new Cidade("", "Garrafão do Norte", "PA"));
        lista.add(new Cidade("", "Goianésia do Pará", "PA"));
        lista.add(new Cidade("", "Gradaus", "PA"));
        lista.add(new Cidade("", "Guajará-Açú", "PA"));
        lista.add(new Cidade("", "Guajará-Miri", "PA"));
        lista.add(new Cidade("", "Gurupá", "PA"));
        lista.add(new Cidade("", "Gurupizinho", "PA"));
        lista.add(new Cidade("", "Hidrelétrica Tucuruí", "PA"));
        lista.add(new Cidade("", "Iataí", "PA"));
        lista.add(new Cidade("", "Icoaraci", "PA"));
        lista.add(new Cidade("", "Igarapé da Lama", "PA"));
        lista.add(new Cidade("", "Igarapé-Açu", "PA"));
        lista.add(new Cidade("", "Igarapé-Miri", "PA"));
        lista.add(new Cidade("", "Inanu", "PA"));
        lista.add(new Cidade("", "Inhangapi", "PA"));
        lista.add(new Cidade("", "Ipixuna do Pará", "PA"));
        lista.add(new Cidade("", "Irituia", "PA"));
        lista.add(new Cidade("", "Itaituba", "PA"));
        lista.add(new Cidade("", "Itapixuna", "PA"));
        lista.add(new Cidade("", "Itatupã", "PA"));
        lista.add(new Cidade("", "Itupiranga", "PA"));
        lista.add(new Cidade("", "Jacareacanga", "PA"));
        lista.add(new Cidade("", "Jacundá", "PA"));
        lista.add(new Cidade("", "Jaguarari", "PA"));
        lista.add(new Cidade("", "Jamanxinzinho", "PA"));
        lista.add(new Cidade("", "Jambuaçu", "PA"));
        lista.add(new Cidade("", "Jandiaí", "PA"));
        lista.add(new Cidade("", "Japerica", "PA"));
        lista.add(new Cidade("", "Joana Coeli", "PA"));
        lista.add(new Cidade("", "Joana Peres", "PA"));
        lista.add(new Cidade("", "Joanes", "PA"));
        lista.add(new Cidade("", "Juabá", "PA"));
        lista.add(new Cidade("", "Jubim", "PA"));
        lista.add(new Cidade("", "Juruti", "PA"));
        lista.add(new Cidade("", "Km 19", "PA"));
        lista.add(new Cidade("", "Km 26", "PA"));
        lista.add(new Cidade("", "Lauro Sodré", "PA"));
        lista.add(new Cidade("", "Ligação do Pará", "PA"));
        lista.add(new Cidade("", "Limoeiro do Ajuru", "PA"));
        lista.add(new Cidade("", "Mãe do Rio", "PA"));
        lista.add(new Cidade("", "Magalhães Barata", "PA"));
        lista.add(new Cidade("", "Maiauata", "PA"));
        lista.add(new Cidade("", "Manjeiro", "PA"));
        lista.add(new Cidade("", "Marabá", "PA"));
        lista.add(new Cidade("", "Maracanã", "PA"));
        lista.add(new Cidade("", "Marajoara", "PA"));
        lista.add(new Cidade("", "Marapanim", "PA"));
        lista.add(new Cidade("", "Marituba", "PA"));
        lista.add(new Cidade("", "Marudá", "PA"));
        lista.add(new Cidade("", "Mata Geral", "PA"));
        lista.add(new Cidade("", "Matapiquara", "PA"));
        lista.add(new Cidade("", "Medicilândia", "PA"));
        lista.add(new Cidade("", "Melgaço", "PA"));
        lista.add(new Cidade("", "Menino Deus do Anapu", "PA"));
        lista.add(new Cidade("", "Meruú", "PA"));
        lista.add(new Cidade("", "Mirasselvas", "PA"));
        lista.add(new Cidade("", "Miritituba", "PA"));
        lista.add(new Cidade("", "Mocajuba", "PA"));
        lista.add(new Cidade("", "Moiraba", "PA"));
        lista.add(new Cidade("", "Moju", "PA"));
        lista.add(new Cidade("", "Mojuí dos Campos", "PA"));
        lista.add(new Cidade("", "Monsaras", "PA"));
        lista.add(new Cidade("", "Monte Alegre", "PA"));
        lista.add(new Cidade("", "Monte Alegre do Mau", "PA"));
        lista.add(new Cidade("", "Monte Dourado", "PA"));
        lista.add(new Cidade("", "Morada Nova", "PA"));
        lista.add(new Cidade("", "Moraes Almeida", "PA"));
        lista.add(new Cidade("", "Mosqueiro", "PA"));
        lista.add(new Cidade("", "Muaná", "PA"));
        lista.add(new Cidade("", "Mujuí dos Campos", "PA"));
        lista.add(new Cidade("", "Murajá", "PA"));
        lista.add(new Cidade("", "Murucupi", "PA"));
        lista.add(new Cidade("", "Murumuru", "PA"));
        lista.add(new Cidade("", "Muta", "PA"));
        lista.add(new Cidade("", "Mutucal", "PA"));
        lista.add(new Cidade("", "Nazaré de Mocajuba", "PA"));
        lista.add(new Cidade("", "Nazaré dos Patos", "PA"));
        lista.add(new Cidade("", "Nova Esperança do Piriá", "PA"));
        lista.add(new Cidade("", "Nova Ipixuna", "PA"));
        lista.add(new Cidade("", "Nova Mocajuba", "PA"));
        lista.add(new Cidade("", "Nova Timboteua", "PA"));
        lista.add(new Cidade("", "Novo Planalto", "PA"));
        lista.add(new Cidade("", "Novo Progresso", "PA"));
        lista.add(new Cidade("", "Novo Repartimento", "PA"));
        lista.add(new Cidade("", "Núcleo Urbano Quilômetro 30", "PA"));
        lista.add(new Cidade("", "Óbidos", "PA"));
        lista.add(new Cidade("", "Oeiras do Pará", "PA"));
        lista.add(new Cidade("", "Oriximiná", "PA"));
        lista.add(new Cidade("", "Osvaldilândia", "PA"));
        lista.add(new Cidade("", "Ourém", "PA"));
        lista.add(new Cidade("", "Ourilândia do Norte", "PA"));
        lista.add(new Cidade("", "Outeiro", "PA"));
        lista.add(new Cidade("", "Pacajá", "PA"));
        lista.add(new Cidade("", "Pacoval", "PA"));
        lista.add(new Cidade("", "Palestina do Pará", "PA"));
        lista.add(new Cidade("", "Palmares", "PA"));
        lista.add(new Cidade("", "Paragominas", "PA"));
        lista.add(new Cidade("", "Paratins", "PA"));
        lista.add(new Cidade("", "Parauapebas", "PA"));
        lista.add(new Cidade("", "Pau D'Arco", "PA"));
        lista.add(new Cidade("", "Pedreira", "PA"));
        lista.add(new Cidade("", "Peixe-Boi", "PA"));
        lista.add(new Cidade("", "Penhalonga", "PA"));
        lista.add(new Cidade("", "Perseverança", "PA"));
        lista.add(new Cidade("", "Pesqueiro", "PA"));
        lista.add(new Cidade("", "Piabas", "PA"));
        lista.add(new Cidade("", "Piçarra", "PA"));
        lista.add(new Cidade("", "Pinhal", "PA"));
        lista.add(new Cidade("", "Piraquara", "PA"));
        lista.add(new Cidade("", "Piriá", "PA"));
        lista.add(new Cidade("", "Placas", "PA"));
        lista.add(new Cidade("", "Ponta de Pedras", "PA"));
        lista.add(new Cidade("", "Ponta de Ramos", "PA"));
        lista.add(new Cidade("", "Portel", "PA"));
        lista.add(new Cidade("", "Porto de Moz", "PA"));
        lista.add(new Cidade("", "Porto Salvo", "PA"));
        lista.add(new Cidade("", "Porto Trombetas", "PA"));
        lista.add(new Cidade("", "Prainha", "PA"));
        lista.add(new Cidade("", "Primavera", "PA"));
        lista.add(new Cidade("", "Quatipuru", "PA"));
        lista.add(new Cidade("", "Quatro Bocas", "PA"));
        lista.add(new Cidade("", "Redenção", "PA"));
        lista.add(new Cidade("", "Remansão", "PA"));
        lista.add(new Cidade("", "Repartimento", "PA"));
        lista.add(new Cidade("", "Rio Maria", "PA"));
        lista.add(new Cidade("", "Rio Vermelho", "PA"));
        lista.add(new Cidade("", "Riozinho", "PA"));
        lista.add(new Cidade("", "Rondon do Pará", "PA"));
        lista.add(new Cidade("", "Rurópolis", "PA"));
        lista.add(new Cidade("", "Salinópolis", "PA"));
        lista.add(new Cidade("", "Salvaterra", "PA"));
        lista.add(new Cidade("", "Santa Bárbara do Pará", "PA"));
        lista.add(new Cidade("", "Santa Cruz do Arari", "PA"));
        lista.add(new Cidade("", "Santa Isabel do Pará", "PA"));
        lista.add(new Cidade("", "Santa Luzia do Pará", "PA"));
        lista.add(new Cidade("", "Santa Maria", "PA"));
        lista.add(new Cidade("", "Santa Maria das Barreiras", "PA"));
        lista.add(new Cidade("", "Santa Maria do Pará", "PA"));
        lista.add(new Cidade("", "Santa Rosa da Vigia", "PA"));
        lista.add(new Cidade("", "Santa Terezinha", "PA"));
        lista.add(new Cidade("", "Santana do Araguaia", "PA"));
        lista.add(new Cidade("", "Santarém", "PA"));
        lista.add(new Cidade("", "Santarém Novo", "PA"));
        lista.add(new Cidade("", "Santo Antônio", "PA"));
        lista.add(new Cidade("", "Santo Antônio do Tauá", "PA"));
        lista.add(new Cidade("", "São Caetano de Odivelas", "PA"));
        lista.add(new Cidade("", "São Domingos do Araguaia", "PA"));
        lista.add(new Cidade("", "São Domingos do Capim", "PA"));
        lista.add(new Cidade("", "São Félix do Xingu", "PA"));
        lista.add(new Cidade("", "São Francisco", "PA"));
        lista.add(new Cidade("", "São Francisco da Jararaca", "PA"));
        lista.add(new Cidade("", "São Francisco do Pará", "PA"));
        lista.add(new Cidade("", "São Geraldo do Araguaia", "PA"));
        lista.add(new Cidade("", "São João da Ponta", "PA"));
        lista.add(new Cidade("", "São João de Pirabas", "PA"));
        lista.add(new Cidade("", "São João do Acangata", "PA"));
        lista.add(new Cidade("", "São João do Araguaia", "PA"));
        lista.add(new Cidade("", "São João do Piriá", "PA"));
        lista.add(new Cidade("", "São João dos Ramos", "PA"));
        lista.add(new Cidade("", "São Joaquim do Tapará", "PA"));
        lista.add(new Cidade("", "São Jorge", "PA"));
        lista.add(new Cidade("", "São José do Gurupi", "PA"));
        lista.add(new Cidade("", "São José do Piriá", "PA"));
        lista.add(new Cidade("", "São Luiz do Tapajós", "PA"));
        lista.add(new Cidade("", "São Miguel de Pracuuba", "PA"));
        lista.add(new Cidade("", "São Miguel do Guamá", "PA"));
        lista.add(new Cidade("", "São Miguel dos Macacos", "PA"));
        lista.add(new Cidade("", "São Pedro de Viseu", "PA"));
        lista.add(new Cidade("", "São Pedro do Capim", "PA"));
        lista.add(new Cidade("", "São Raimundo de Borralhos", "PA"));
        lista.add(new Cidade("", "São Raimundo do Araguaia", "PA"));
        lista.add(new Cidade("", "São Raimundo dos Furtados", "PA"));
        lista.add(new Cidade("", "São Roberto", "PA"));
        lista.add(new Cidade("", "São Sebastião da Boa Vista", "PA"));
        lista.add(new Cidade("", "São Sebastião de Viçosa", "PA"));
        lista.add(new Cidade("", "Sapucaia", "PA"));
        lista.add(new Cidade("", "Senador José Porfírio", "PA"));
        lista.add(new Cidade("", "Serra Pelada", "PA"));
        lista.add(new Cidade("", "Soure", "PA"));
        lista.add(new Cidade("", "Tailândia", "PA"));
        lista.add(new Cidade("", "Tatuteua", "PA"));
        lista.add(new Cidade("", "Tauari", "PA"));
        lista.add(new Cidade("", "Tauarizinho", "PA"));
        lista.add(new Cidade("", "Tentugal", "PA"));
        lista.add(new Cidade("", "Terra Alta", "PA"));
        lista.add(new Cidade("", "Terra Santa", "PA"));
        lista.add(new Cidade("", "Tijoca", "PA"));
        lista.add(new Cidade("", "Timboteua", "PA"));
        lista.add(new Cidade("", "Tomé-Açú", "PA"));
        lista.add(new Cidade("", "Tracuateua", "PA"));
        lista.add(new Cidade("", "Trairão", "PA"));
        lista.add(new Cidade("", "Tucumã", "PA"));
        lista.add(new Cidade("", "Tucuruí", "PA"));
        lista.add(new Cidade("", "Ulianópolis", "PA"));
        lista.add(new Cidade("", "União da Floresta", "PA"));
        lista.add(new Cidade("", "Uruará", "PA"));
        lista.add(new Cidade("", "Urucuri", "PA"));
        lista.add(new Cidade("", "Urucuriteua", "PA"));
        lista.add(new Cidade("", "Val-de-Cães", "PA"));
        lista.add(new Cidade("", "Veiros", "PA"));
        lista.add(new Cidade("", "Vigia", "PA"));
        lista.add(new Cidade("", "Vila do Carmo do Tocantins", "PA"));
        lista.add(new Cidade("", "Vila dos Cabanos", "PA"));
        lista.add(new Cidade("", "Vila França", "PA"));
        lista.add(new Cidade("", "Vila Goreth", "PA"));
        lista.add(new Cidade("", "Vila Isol", "PA"));
        lista.add(new Cidade("", "Vila Mandi", "PA"));
        lista.add(new Cidade("", "Vila Nova", "PA"));
        lista.add(new Cidade("", "Vila Planalto", "PA"));
        lista.add(new Cidade("", "Vila Santa Fé", "PA"));
        lista.add(new Cidade("", "Vila Socorro", "PA"));
        lista.add(new Cidade("", "Vilarinho do Monte", "PA"));
        lista.add(new Cidade("", "Viseu", "PA"));
        lista.add(new Cidade("", "Vista Alegre", "PA"));
        lista.add(new Cidade("", "Vista Alegre do Pará", "PA"));
        lista.add(new Cidade("", "Vitória do Xingu", "PA"));
        lista.add(new Cidade("", "Xinguara", "PA"));
        lista.add(new Cidade("", "Xinguarinha", "PA"));

        return lista;
    }
}
