package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PA {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("VrnvoR0ech19NEHGSvjm","Abaetetuba","PA"));
        lista.add(new Cidade("B4xaRPxK5fMGUDrwY7Bh","Abel Figueiredo","PA"));
        lista.add(new Cidade("gcjRGJTPYEnKdgxzpAm2","Acará","PA"));
        lista.add(new Cidade("jJ9Zw0s2iHBgKdkat51r","Afuá","PA"));
        lista.add(new Cidade("d2mPhaMQjOZmSxRzAdSG","Agrópolis Bela Vista","PA"));
        lista.add(new Cidade("exrfvtcJQ3bAyzlU5RPc","Água Azul do Norte","PA"));
        lista.add(new Cidade("kPrxbMTC4eo3z5TPnZ39","Água Fria","PA"));
        lista.add(new Cidade("ju4InxjvoqbVv8JF4Jjc","Alenquer","PA"));
        lista.add(new Cidade("dchkv5rIhcdHfA7x1CQB","Algodoal","PA"));
        lista.add(new Cidade("30Z486d1LKP53mpvkpsf","Almeirim","PA"));
        lista.add(new Cidade("MWimZN1z9qEICFjVcFKy","Almoço","PA"));
        lista.add(new Cidade("qb8pfMroUtIdctWUCgiA","Alta Pará","PA"));
        lista.add(new Cidade("BDgdI2KaMPlzrFe6h06Y","Altamira","PA"));
        lista.add(new Cidade("lDD82AaHG1PWWK0S4ZFE","Alter do Chão","PA"));
        lista.add(new Cidade("DHXY0fDqrXiRPzdFnq8M","Alvorada","PA"));
        lista.add(new Cidade("6aXd99U84uYVeEWB4Bs1","Americano","PA"));
        lista.add(new Cidade("guGzg8Xzy52Lq2cDTNUG","Anajás","PA"));
        lista.add(new Cidade("DuTcwaDLTrH3ehPHFqUc","Ananindeua","PA"));
        lista.add(new Cidade("anXwGsIObfR9sZCTbknl","Anapu","PA"));
        lista.add(new Cidade("1ba48VanMdLSYzc0eU1s","Antônio Lemos","PA"));
        lista.add(new Cidade("UTcE32JCsvAkOOnwEzhS","Apeú","PA"));
        lista.add(new Cidade("BiiHbgGRueJP7Kq26Jl1","Apinagés","PA"));
        lista.add(new Cidade("GTvJu1C9EzzcMkU9BB2O","Arapixuna","PA"));
        lista.add(new Cidade("6SN1imv0xCQYbrh2uWA0","Araquaim","PA"));
        lista.add(new Cidade("5zBzDrwf5iw43fNvIskm","Arco-Íris","PA"));
        lista.add(new Cidade("AOl8yRYncNIvNs5Ep18u","Areias","PA"));
        lista.add(new Cidade("GVGQ5iIzgvoP4iONvpNJ","Arumanduba","PA"));
        lista.add(new Cidade("KTaPVx61QsqoLLvvQz0q","Aruri","PA"));
        lista.add(new Cidade("ICh3Z6vGqpVVOtCLFEAU","Aturiaí","PA"));
        lista.add(new Cidade("cpmsHNsEFfJdLiEb1GBD","Augusto Corrêa","PA"));
        lista.add(new Cidade("g7eiH1EPW660zTEfaTYO","Aurora do Pará","PA"));
        lista.add(new Cidade("dy2MZ5ufgp6YQdVadvsM","Aveiro","PA"));
        lista.add(new Cidade("ZCwkXOzd91uS0AxyWHRa","Bagre","PA"));
        lista.add(new Cidade("FD88AUjwLxlD8SSEnK0R","Baião","PA"));
        lista.add(new Cidade("zvGnVSAwdauwIlhLIfNR","Bannach","PA"));
        lista.add(new Cidade("IUo4ckOg3evv39fsC4zU","Barcarena","PA"));
        lista.add(new Cidade("NP4qF9m8ULvwm3wDWXNZ","Barreira Branca","PA"));
        lista.add(new Cidade("yFcIuxDsdBCYQM3kkVXk","Barreira dos Campos","PA"));
        lista.add(new Cidade("TqKl5QUiNoQtzhPECkpO","Barreiras","PA"));
        lista.add(new Cidade("dlAE88SHJsG3KC9siHZH","Baturité","PA"));
        lista.add(new Cidade("mdkS7iW6QP2BMY8ydYaO","Beja","PA"));
        lista.add(new Cidade("FxSmXbeYFcsSkSVBgC2w","Bela Vista do Caracol","PA"));
        lista.add(new Cidade("1229UtAOOeFUJQnYqEbO","Belém","PA"));
        lista.add(new Cidade("M2fPgEtGBM7kCnx5nXgY","Belo Monte","PA"));
        lista.add(new Cidade("Uck4FrfPNoNRZUDq2Sx4","Belterra","PA"));
        lista.add(new Cidade("KLlWisRxrYSBFDC72PTZ","Benevides","PA"));
        lista.add(new Cidade("36k2Ww3X1fpbC5pUVn4W","Benfica","PA"));
        lista.add(new Cidade("Ay28bcIIKw9FvckQRj71","Boa Esperança","PA"));
        lista.add(new Cidade("m7n8Uia8cKYy6cttunDa","Boa Fé","PA"));
        lista.add(new Cidade("MhDu7GX8RfhjlwZLm3NW","Boa Sorte","PA"));
        lista.add(new Cidade("QmjeYquFHdBu8qEsNk3Y","Boa Vista do Iririteua","PA"));
        lista.add(new Cidade("EWtnbFf53iKLOUjfeBM7","Boim","PA"));
        lista.add(new Cidade("XMq65FAvGAuYwz6YqvpN","Bom Jardim","PA"));
        lista.add(new Cidade("IHU3Pyaue9fTmbZxo5RH","Bom Jesus do Tocantins","PA"));
        lista.add(new Cidade("Kys39U4IcPJuB4G77Q8o","Bonito","PA"));
        lista.add(new Cidade("yeROKvbhh8DpWvZ5bO1b","Bragança","PA"));
        lista.add(new Cidade("xtn1o9aDBXXMpnyCI6rB","Brasil Novo","PA"));
        lista.add(new Cidade("GHrgd4Ct3VAcvdp9ie8H","Brasília Legal","PA"));
        lista.add(new Cidade("bil5pSfvmZutY5dqBDtp","Brejo do Meio","PA"));
        lista.add(new Cidade("FXJPftVVqV2kbypCkoPX","Brejo Grande do Araguaia","PA"));
        lista.add(new Cidade("XmKUBaLC7QM4ZDsnDuVc","Breu Branco","PA"));
        lista.add(new Cidade("mV8k5lFgikxiGnJCNwGq","Breves","PA"));
        lista.add(new Cidade("7SC218Hcw4vjnhLI7pvY","Bujaru","PA"));
        lista.add(new Cidade("diXSFdiluVEWdiYijGHC","Cachoeira da Serra","PA"));
        lista.add(new Cidade("xX3HX8nXGl09im5rt3UA","Cachoeira do Arari","PA"));
        lista.add(new Cidade("iajIZ3Cv9HtJXJnD9ztj","Cachoeira do Piriá","PA"));
        lista.add(new Cidade("8g7XQQ5FRuEzhoImZ3B4","Cafezal","PA"));
        lista.add(new Cidade("OSPlb9ULJ3DiKkghJhf2","Cairari","PA"));
        lista.add(new Cidade("YmBY01xA68m4Obie59SS","Caju","PA"));
        lista.add(new Cidade("SOduvLWRgwYC9pjaPpou","Câmara do Marajó","PA"));
        lista.add(new Cidade("C14qLF1zyO1ezeadMokS","Cambuquira","PA"));
        lista.add(new Cidade("rnFPDGlmbkuOoNulc4Xg","Cametá","PA"));
        lista.add(new Cidade("942K2MGHeEXQ5qubT66u","Camiranga","PA"));
        lista.add(new Cidade("5t10pSCsOapmBeSKV3hU","Canaã dos Carajás","PA"));
        lista.add(new Cidade("7sYGghfYT6QcCNlOq6wq","Capanema","PA"));
        lista.add(new Cidade("Ts0RdZlvJBZWY2FD3RUl","Capitão Poço","PA"));
        lista.add(new Cidade("YEA506n4emRuqrdlV5ag","Caracará do Arari","PA"));
        lista.add(new Cidade("ekABoESSPtbyXoP9dU30","Caracol","PA"));
        lista.add(new Cidade("7n6XXTSXGLaWKD1OflI9","Carajás","PA"));
        lista.add(new Cidade("TlNYCBNC5IPyEdipAGtl","Carapajó","PA"));
        lista.add(new Cidade("mv4KLkX8Mo8EMrgM0elv","Caraparu","PA"));
        lista.add(new Cidade("ShDSEZ8re5EQlZ9vNjYv","Caratateua","PA"));
        lista.add(new Cidade("PppWyIs8XRASGHxdzMOn","Caripi","PA"));
        lista.add(new Cidade("tAfXh2LYihgolOKoEhKh","Carrazedo","PA"));
        lista.add(new Cidade("PgyUR8Plg6OuMC5cedwo","Casa de Tábua","PA"));
        lista.add(new Cidade("sfhniZz28IEktIOpLKTZ","Castanhal","PA"));
        lista.add(new Cidade("HDp6ozZjnbxwojdxmInM","Castelo dos Sonhos","PA"));
        lista.add(new Cidade("EvH9kC7wdwYHXitinhmW","Chaves","PA"));
        lista.add(new Cidade("s4WdmxxuOpBdGDZ028zt","Colares","PA"));
        lista.add(new Cidade("vrlS8WCnND28KEzGYsVh","Conceição","PA"));
        lista.add(new Cidade("mzTeAeCJDBF5J7Zaqv6E","Conceição do Araguaia","PA"));
        lista.add(new Cidade("hl90IjQZpuLST5Ac7QEE","Concórdia do Pará","PA"));
        lista.add(new Cidade("hMwpoaEJxGkuTa3LSH0j","Condeixa","PA"));
        lista.add(new Cidade("YZeLzJqV5eTzLHsOcjqZ","Coqueiro","PA"));
        lista.add(new Cidade("sqLQjJBsd0iqRiCyANqm","Cripurizão","PA"));
        lista.add(new Cidade("AAII26UpNV1QthypDlkB","Cripurizinho","PA"));
        lista.add(new Cidade("0Hl7dOCdplbtqRTjGslb","Cuiú-Cuiú","PA"));
        lista.add(new Cidade("xEBg97xw3nXsakR6WfOe","Cumaru do Norte","PA"));
        lista.add(new Cidade("s1h3leDMniadYeX5nVLo","Curionópolis","PA"));
        lista.add(new Cidade("BqexumrgPFmVgzcuIRqC","Curralinho","PA"));
        lista.add(new Cidade("NMFOA1gb8CTg0w5jB0qH","Curuá","PA"));
        lista.add(new Cidade("i5XCJ0KLxkuDT9XLXYv8","Curuaí","PA"));
        lista.add(new Cidade("EsBtqhsgSOop0WOZej9R","Curuçá","PA"));
        lista.add(new Cidade("Mh062o9KGO69eWCoNv6R","Curuçambaba","PA"));
        lista.add(new Cidade("RFyd0ocWKE7PBPuVaX5U","Curumu","PA"));
        lista.add(new Cidade("NR9x1DZ2FwjMNzHMEnqM","Dom Eliseu","PA"));
        lista.add(new Cidade("rh7UahI3lkozKbI6EHj5","Eldorado dos Carajás","PA"));
        lista.add(new Cidade("Uk96Fijr81v3ORTFXt0i","Emboraí","PA"));
        lista.add(new Cidade("cKRKHRynYewKxdVzSOZt","Espírito Santo do Tauá","PA"));
        lista.add(new Cidade("uPqUk9tXtRrGNMWVi78r","Faro","PA"));
        lista.add(new Cidade("0DCCsulXV9qnqs1xus2j","Fernandes Belo","PA"));
        lista.add(new Cidade("0ippjSqZUxV0qJbkBzXO","Flexal","PA"));
        lista.add(new Cidade("GzWIPk6FrABAUc4ZjhqC","Floresta","PA"));
        lista.add(new Cidade("HULrLiHY4OvcQdM0vz82","Floresta do Araguaia","PA"));
        lista.add(new Cidade("Cl8DBH1c9pEsDTmwZIXv","Garrafão do Norte","PA"));
        lista.add(new Cidade("FOaVAsJraN4FecC1JVKq","Goianésia do Pará","PA"));
        lista.add(new Cidade("UPtaCywLYIoJXWDVEoHq","Gradaus","PA"));
        lista.add(new Cidade("dXkNNOgg3WI5T0CK3Zfu","Guajará-Açú","PA"));
        lista.add(new Cidade("ONcHCeFsT3r8egBeeF5z","Guajará-Miri","PA"));
        lista.add(new Cidade("DSdL7QkSmjkbqCSWFimK","Gurupá","PA"));
        lista.add(new Cidade("7JImgGSeqFD09v36N8DP","Gurupizinho","PA"));
        lista.add(new Cidade("O84GfjoNrWuP94KcoaUH","Hidrelétrica Tucuruí","PA"));
        lista.add(new Cidade("xvZcxHymIEaUeB5HaCjb","Iataí","PA"));
        lista.add(new Cidade("rrz1BACtk8zRUW8TvU8P","Icoaraci","PA"));
        lista.add(new Cidade("fG0r6jFy6muTuYgMMip6","Igarapé da Lama","PA"));
        lista.add(new Cidade("Wk38pHwe4IWDQ7Rm6cop","Igarapé-Açu","PA"));
        lista.add(new Cidade("imAAuHsPx9yS7heyweId","Igarapé-Miri","PA"));
        lista.add(new Cidade("KbmfIoIAlcWI3eOUIwuY","Inanu","PA"));
        lista.add(new Cidade("e3UhbdFKeN1CB6LLQhiv","Inhangapi","PA"));
        lista.add(new Cidade("l7iXTUusSuEiyYhFvJsv","Ipixuna do Pará","PA"));
        lista.add(new Cidade("4NnMfLp4yDpxoQEkhWSu","Irituia","PA"));
        lista.add(new Cidade("yvOt2kl1AFjxwttaQKGA","Itaituba","PA"));
        lista.add(new Cidade("vzk5SXuSUeLnnhq0fjFY","Itapixuna","PA"));
        lista.add(new Cidade("l5zdqx0vreNsntQD5anJ","Itatupã","PA"));
        lista.add(new Cidade("lQNRnGa7gZiTvs4O4TK6","Itupiranga","PA"));
        lista.add(new Cidade("9myiTCVcTvjqn34jjAj8","Jacareacanga","PA"));
        lista.add(new Cidade("ZrTjwTOSBVqqYQHK7WYi","Jacundá","PA"));
        lista.add(new Cidade("Xi5tOMEFi1QnVE7uv8Lw","Jaguarari","PA"));
        lista.add(new Cidade("Y7pK1eM63JoZlBbjXKE4","Jamanxinzinho","PA"));
        lista.add(new Cidade("PN0vVce8QjuUZfOQv6P2","Jambuaçu","PA"));
        lista.add(new Cidade("oZz0PPF23JXADabVEHCW","Jandiaí","PA"));
        lista.add(new Cidade("DDGOGEfKCDFq4achlsTd","Japerica","PA"));
        lista.add(new Cidade("V1ukY2hPTY6rMEIIHlbz","Joana Coeli","PA"));
        lista.add(new Cidade("XGh8logUHGNt6wfTxpIP","Joana Peres","PA"));
        lista.add(new Cidade("hYwy5V8GNQVgrZ7SGQXm","Joanes","PA"));
        lista.add(new Cidade("ELGuAXvMSx1aHQyFv6CM","Juabá","PA"));
        lista.add(new Cidade("HfPwIal8UTAYkyxSIFrW","Jubim","PA"));
        lista.add(new Cidade("flt1JaqpANawv6sxsqLG","Juruti","PA"));
        lista.add(new Cidade("7PkrJ4il1pjmsZn8mkXA","Km 19","PA"));
        lista.add(new Cidade("4938LVvc26Zq3OkMFvxv","Km 26","PA"));
        lista.add(new Cidade("cd47PJx2pVI5LC6CUkCI","Lauro Sodré","PA"));
        lista.add(new Cidade("rIaJRm096II6sThqZs1e","Ligação do Pará","PA"));
        lista.add(new Cidade("MuS0q9gwAEAmxcXXLXRY","Limoeiro do Ajuru","PA"));
        lista.add(new Cidade("rxfWL7may9lkGrrAHf76","Mãe do Rio","PA"));
        lista.add(new Cidade("pysKLEBpzrwi4udGcHeJ","Magalhães Barata","PA"));
        lista.add(new Cidade("UiwxP8YWv4dm5ccobRaF","Maiauata","PA"));
        lista.add(new Cidade("QbjPlCcTbl0iVFaTLCUx","Manjeiro","PA"));
        lista.add(new Cidade("hI6sRQrXKQQkq2lzEQr3","Marabá","PA"));
        lista.add(new Cidade("IeU1ztDnD0T68zEXjHUu","Maracanã","PA"));
        lista.add(new Cidade("sFtiM8vzhWc7bbl5X2kH","Marajoara","PA"));
        lista.add(new Cidade("oKyIdIALeE9M4YETUhz1","Marapanim","PA"));
        lista.add(new Cidade("zYXDGaCaV4JcA56OYmVB","Marituba","PA"));
        lista.add(new Cidade("7OpqXUQ5zeSujnEOuTfr","Marudá","PA"));
        lista.add(new Cidade("3YW2GGjVydfDVPn6tNs0","Mata Geral","PA"));
        lista.add(new Cidade("UsR9nfhqZt9rFX7f7ngq","Matapiquara","PA"));
        lista.add(new Cidade("hPgiv9HOcZ6CF6m5IqSc","Medicilândia","PA"));
        lista.add(new Cidade("8LfRx9XXCBqJP9G8Rp2l","Melgaço","PA"));
        lista.add(new Cidade("bDQ7BUm2bd1SwMW3CM7W","Menino Deus do Anapu","PA"));
        lista.add(new Cidade("0ee3uPZr0kZkUoqzZc4k","Meruú","PA"));
        lista.add(new Cidade("MBVOfoIhoxG8CgK0PL0T","Mirasselvas","PA"));
        lista.add(new Cidade("fAl8s0c22Ntqw2LqQX20","Miritituba","PA"));
        lista.add(new Cidade("gmETibUb8QfHHhpZsDHA","Mocajuba","PA"));
        lista.add(new Cidade("ZcfpAY7oxs1DbErRTVcq","Moiraba","PA"));
        lista.add(new Cidade("f1ymVGDO3E8FZPpioWbU","Moju","PA"));
        lista.add(new Cidade("saxZWtdbAglysAy0Z8ra","Mojuí dos Campos","PA"));
        lista.add(new Cidade("GmN9viKWm4swUrh19NFF","Monsaras","PA"));
        lista.add(new Cidade("a1HZVRnBykkY7DiQBiqL","Monte Alegre","PA"));
        lista.add(new Cidade("OIhGINILFT6oswc0Ndb0","Monte Alegre do Mau","PA"));
        lista.add(new Cidade("7WTMPvRJkU55GJsayjcJ","Monte Dourado","PA"));
        lista.add(new Cidade("MbNqVU9RxSpEpe9Zst2s","Morada Nova","PA"));
        lista.add(new Cidade("1Rg5N6q4ZqKerA6AHgL5","Moraes Almeida","PA"));
        lista.add(new Cidade("3Z79tdRTI9OGq33ynzYB","Mosqueiro","PA"));
        lista.add(new Cidade("YaTfrZnUpGVDYGBuYmzL","Muaná","PA"));
        lista.add(new Cidade("bNR1kOAzAK97UeJtCu2V","Mujuí dos Campos","PA"));
        lista.add(new Cidade("yfIII3YGchdcL4HgT1n4","Murajá","PA"));
        lista.add(new Cidade("MM3tSPnK9bZCCIajw3Gr","Murucupi","PA"));
        lista.add(new Cidade("ygMFVF5FEL6QiFC7x7Qp","Murumuru","PA"));
        lista.add(new Cidade("ZSXTX15zINPmbv1DTYz8","Muta","PA"));
        lista.add(new Cidade("LnaFOkIQp2XpYc7bMyOH","Mutucal","PA"));
        lista.add(new Cidade("H5a1oYfo5nHtkDFbClMw","Nazaré de Mocajuba","PA"));
        lista.add(new Cidade("PB6RUMEP7soUOL7281XG","Nazaré dos Patos","PA"));
        lista.add(new Cidade("7CELg1HLq62IqTunnAkN","Nova Esperança do Piriá","PA"));
        lista.add(new Cidade("jAcl64WCTlvQzcFb9jlb","Nova Ipixuna","PA"));
        lista.add(new Cidade("UCoTdwPrn8hptotGQgQP","Nova Mocajuba","PA"));
        lista.add(new Cidade("wNeIg2pYnE85V6PB9JWC","Nova Timboteua","PA"));
        lista.add(new Cidade("ZX5bzN3eWYhOW59ooSmv","Novo Planalto","PA"));
        lista.add(new Cidade("dHcg4QDafFkanZZ363pt","Novo Progresso","PA"));
        lista.add(new Cidade("VaNT4vWj1UDEkv8RPSGs","Novo Repartimento","PA"));
        lista.add(new Cidade("DYjTVQsWUOwONyQmpxwH","Núcleo Urbano Quilômetro 30","PA"));
        lista.add(new Cidade("dDa1G1XRDFXbyU31zR13","Óbidos","PA"));
        lista.add(new Cidade("78MpwlTBvzCJUa62DhFB","Oeiras do Pará","PA"));
        lista.add(new Cidade("gBWrRWAMQdAav7v5yMOQ","Oriximiná","PA"));
        lista.add(new Cidade("D1UG5LVoQ73pR0pu8pm9","Osvaldilândia","PA"));
        lista.add(new Cidade("oKRYoxq3RbppPcJ5qOZw","Ourém","PA"));
        lista.add(new Cidade("hlMnaZt09Hhae8SgRUlM","Ourilândia do Norte","PA"));
        lista.add(new Cidade("oyZtd1kUdV98gUno4JqZ","Outeiro","PA"));
        lista.add(new Cidade("JVRVfsQQ8q04XUqibelD","Pacajá","PA"));
        lista.add(new Cidade("qjLf6h5Ue0eWuwc3eENZ","Pacoval","PA"));
        lista.add(new Cidade("ujxTgdWT1ln319pZrZAn","Palestina do Pará","PA"));
        lista.add(new Cidade("4OFiLSWQCzrJ8ucGTf8G","Palmares","PA"));
        lista.add(new Cidade("WxhTY57SIIyOSIu7BXgB","Paragominas","PA"));
        lista.add(new Cidade("DCTiHz1gAZsJuXZiutiy","Paratins","PA"));
        lista.add(new Cidade("LM2zNIfe0GAWukNUylsJ","Parauapebas","PA"));
        lista.add(new Cidade("uuUj6q0bdzUr1vzN34yd","Pau D'Arco","PA"));
        lista.add(new Cidade("5y4QJ0DDTBF1tWzy1Wff","Pedreira","PA"));
        lista.add(new Cidade("5e1cbvs36QWTPHfP017t","Peixe-Boi","PA"));
        lista.add(new Cidade("JTVvHxHTXfdFx7sxDsCe","Penhalonga","PA"));
        lista.add(new Cidade("MezUfFyIlKM2NluygyqB","Perseverança","PA"));
        lista.add(new Cidade("9oeXWErd6p54NgO3kplg","Pesqueiro","PA"));
        lista.add(new Cidade("Hmdi2ckvGh06nuevUMgz","Piabas","PA"));
        lista.add(new Cidade("MCk35stw38vIkkRZ1HGm","Piçarra","PA"));
        lista.add(new Cidade("TkQwNFRKuF0LH0YmzGVz","Pinhal","PA"));
        lista.add(new Cidade("J9X9WQyh0mtWO4EZPDwM","Piraquara","PA"));
        lista.add(new Cidade("Mf1gDc36VSP2CcyOpPkI","Piriá","PA"));
        lista.add(new Cidade("AmJfhk8hRxv0QDtEyyZ2","Placas","PA"));
        lista.add(new Cidade("pCcxbv9GBUHMIAji8kXU","Ponta de Pedras","PA"));
        lista.add(new Cidade("W0quI7DTlhBl5OiEbDQW","Ponta de Ramos","PA"));
        lista.add(new Cidade("7g8vzYKdm6PySlu9jiHv","Portel","PA"));
        lista.add(new Cidade("o4jR1vrNyhTxsSInUSfB","Porto de Moz","PA"));
        lista.add(new Cidade("wV1r8ySZBRtWKLbIcnq2","Porto Salvo","PA"));
        lista.add(new Cidade("ZzXUiDYRBJ6FCLlzh1Hp","Porto Trombetas","PA"));
        lista.add(new Cidade("A8aXCyPFgAD6Cx5UiwUH","Prainha","PA"));
        lista.add(new Cidade("J6WArdh1g9WmwtKG9gF7","Primavera","PA"));
        lista.add(new Cidade("Jjm1ODoBFASe3F0mF01s","Quatipuru","PA"));
        lista.add(new Cidade("yjRjFSvCLnHjvxweX9Nm","Quatro Bocas","PA"));
        lista.add(new Cidade("V24jgdUpCPVcp5Yrewky","Redenção","PA"));
        lista.add(new Cidade("viXPaaRz31Gd3kk4Ftde","Remansão","PA"));
        lista.add(new Cidade("fVmomnydVFBqXy7Wo8FU","Repartimento","PA"));
        lista.add(new Cidade("tANnI1ZcYHygQHPGQFvS","Rio Maria","PA"));
        lista.add(new Cidade("ufIotppNZVEU3Pxw61go","Rio Vermelho","PA"));
        lista.add(new Cidade("GTWz044XCfV5FAPKfcvD","Riozinho","PA"));
        lista.add(new Cidade("moXfOf0P9GQCXyJTQrUr","Rondon do Pará","PA"));
        lista.add(new Cidade("xhaRS6opu7LKD6aMUa2v","Rurópolis","PA"));
        lista.add(new Cidade("ZtJifN9VY1MJd61G3LMg","Salinópolis","PA"));
        lista.add(new Cidade("CDEVSLbUtSZBICtgMSFy","Salvaterra","PA"));
        lista.add(new Cidade("yOtrp7rv0yEi29qceTz1","Santa Bárbara do Pará","PA"));
        lista.add(new Cidade("OJgGVK02A5EjTVlh485A","Santa Cruz do Arari","PA"));
        lista.add(new Cidade("6NUg8NfGLP6nL4QnG0J1","Santa Isabel do Pará","PA"));
        lista.add(new Cidade("yjnWNUM7PpJMPk240r0y","Santa Luzia do Pará","PA"));
        lista.add(new Cidade("fTwMPsSxhuB6Gz7K23Wz","Santa Maria","PA"));
        lista.add(new Cidade("Vcg5zG2eHyk16NJEWg6N","Santa Maria das Barreiras","PA"));
        lista.add(new Cidade("cuZfLeUFWxYTwTDSvdye","Santa Maria do Pará","PA"));
        lista.add(new Cidade("Nvl8O1aLZr3kqgVKwsnj","Santa Rosa da Vigia","PA"));
        lista.add(new Cidade("HnifRW47dvHZxY6fvnIn","Santa Terezinha","PA"));
        lista.add(new Cidade("t6OJfPdj9pb513CFlU6Z","Santana do Araguaia","PA"));
        lista.add(new Cidade("2C8Qd48bPBDiMU37805P","Santarém","PA"));
        lista.add(new Cidade("fGgvhhDBz0qGeWIDfoWK","Santarém Novo","PA"));
        lista.add(new Cidade("5U7g9Qt9W9cOGu1XdspL","Santo Antônio","PA"));
        lista.add(new Cidade("46O13733fu1jzkCyBC1K","Santo Antônio do Tauá","PA"));
        lista.add(new Cidade("gy4sgUvsZ8s81EbPdXrw","São Caetano de Odivelas","PA"));
        lista.add(new Cidade("KOtdxTESFLl0PVvQemw9","São Domingos do Araguaia","PA"));
        lista.add(new Cidade("7zZCObaFPrOSMnW5dnAV","São Domingos do Capim","PA"));
        lista.add(new Cidade("qKuofnSiRE3b5e4COwLy","São Félix do Xingu","PA"));
        lista.add(new Cidade("9gNNMEfD7PUHcHdm9zjB","São Francisco","PA"));
        lista.add(new Cidade("RTzt2O9IwkXPuFZqjDNw","São Francisco da Jararaca","PA"));
        lista.add(new Cidade("owO9U2bgNhCdQTWwy1Pz","São Francisco do Pará","PA"));
        lista.add(new Cidade("nlbJWLVNYgBFi65XaGu1","São Geraldo do Araguaia","PA"));
        lista.add(new Cidade("9VVcUnpz1lUlaHw8XZjz","São João da Ponta","PA"));
        lista.add(new Cidade("r0aBzERreitjhsRw7IxS","São João de Pirabas","PA"));
        lista.add(new Cidade("PZUhZBSnC3VYZ8sX7agi","São João do Acangata","PA"));
        lista.add(new Cidade("CdDyC5DflkWqGjuKh88a","São João do Araguaia","PA"));
        lista.add(new Cidade("1a3OcPQKx69cYNSPog6L","São João do Piriá","PA"));
        lista.add(new Cidade("JMDV0jW6zY5y8OLgExve","São João dos Ramos","PA"));
        lista.add(new Cidade("rxCQ9I7f1dCuRmdMCbKP","São Joaquim do Tapará","PA"));
        lista.add(new Cidade("gTHlFFKG9gbpKTZkrRGD","São Jorge","PA"));
        lista.add(new Cidade("zKfWYJzfEjMtRSHwa4lT","São José do Gurupi","PA"));
        lista.add(new Cidade("nW2PlvPotrCUeItOsRDV","São José do Piriá","PA"));
        lista.add(new Cidade("QUAWDAPzP3U9rZpi8VgK","São Luiz do Tapajós","PA"));
        lista.add(new Cidade("MiCLxSLCtdeMurW4KCYx","São Miguel de Pracuuba","PA"));
        lista.add(new Cidade("CDTgRXQRHPw2Ni3rGUIn","São Miguel do Guamá","PA"));
        lista.add(new Cidade("5ONpy3izLQ9kkRqOihLN","São Miguel dos Macacos","PA"));
        lista.add(new Cidade("92nv9iqSDKDLwg6m7V1y","São Pedro de Viseu","PA"));
        lista.add(new Cidade("rg9Tzy3aBfOLAFoFQL7D","São Pedro do Capim","PA"));
        lista.add(new Cidade("I12kIUesjJmmDpVlLR7O","São Raimundo de Borralhos","PA"));
        lista.add(new Cidade("VIvaymWPx3kojvzf6q5u","São Raimundo do Araguaia","PA"));
        lista.add(new Cidade("EvczCOXD7LcBpPclTZYT","São Raimundo dos Furtados","PA"));
        lista.add(new Cidade("7z4IkYUWz6C16AOgeNo8","São Roberto","PA"));
        lista.add(new Cidade("In6Mh4BwZTwPnGajnYXM","São Sebastião da Boa Vista","PA"));
        lista.add(new Cidade("zHp0FsH6wm4hSC2HS78q","São Sebastião de Viçosa","PA"));
        lista.add(new Cidade("aqSEaS1ab3Dkk2eI8LAd","Sapucaia","PA"));
        lista.add(new Cidade("NBA30vKBHdxGzL8ekpuz","Senador José Porfírio","PA"));
        lista.add(new Cidade("KhLARYbCRmoGfsphclGR","Serra Pelada","PA"));
        lista.add(new Cidade("mTSrYj7qoOfvkqgmu9ju","Soure","PA"));
        lista.add(new Cidade("UXEXBnnUsc5h0nrdZvWb","Tailândia","PA"));
        lista.add(new Cidade("1MvqGrMWAftP706A5zwM","Tatuteua","PA"));
        lista.add(new Cidade("B0zLDqkKwtCVCXjh5jFk","Tauari","PA"));
        lista.add(new Cidade("2gmTAnExYT2J3ag1sLYF","Tauarizinho","PA"));
        lista.add(new Cidade("3x5ZS8d5Dvz2IQcRiKvM","Tentugal","PA"));
        lista.add(new Cidade("qlxKHaTHfMU2XzT8ZOov","Terra Alta","PA"));
        lista.add(new Cidade("dK7UrZb6tNxPKDATkSsK","Terra Santa","PA"));
        lista.add(new Cidade("czct4jKoypDKHdYPhsaL","Tijoca","PA"));
        lista.add(new Cidade("9mnQHbK0Bxhx4zLeeC0v","Timboteua","PA"));
        lista.add(new Cidade("Q5KjDk5EQFh0MSPnrByd","Tomé-Açú","PA"));
        lista.add(new Cidade("NzhgvfFP7Mo1SXWfUVa9","Tracuateua","PA"));
        lista.add(new Cidade("sBKAQkNcr9eTOYkeqf7D","Trairão","PA"));
        lista.add(new Cidade("LeyoNUcFKVzjPLd8NPHn","Tucumã","PA"));
        lista.add(new Cidade("GU1qJVSGRsigJoe9v44a","Tucuruí","PA"));
        lista.add(new Cidade("zX25sZ0dPEfU9BUCsVOM","Ulianópolis","PA"));
        lista.add(new Cidade("jDDIBW1LreZGzdmdj2dQ","União da Floresta","PA"));
        lista.add(new Cidade("BAM9v0dohesrLYbStdZ4","Uruará","PA"));
        lista.add(new Cidade("oJ60oprkZiuWxN744X9F","Urucuri","PA"));
        lista.add(new Cidade("SQ2Tvp217uhpBLNmC0bE","Urucuriteua","PA"));
        lista.add(new Cidade("bJRkF0cSJhpuYGgSormt","Val-de-Cães","PA"));
        lista.add(new Cidade("bLzDX6rVpql189epCF3x","Veiros","PA"));
        lista.add(new Cidade("AZ0mjRfaFV4hgIJQhxHL","Vigia","PA"));
        lista.add(new Cidade("U9H7TifgKS0mxuiwEdPA","Vila do Carmo do Tocantins","PA"));
        lista.add(new Cidade("HbvzVqOhSFLBrIPGs6CY","Vila dos Cabanos","PA"));
        lista.add(new Cidade("DyZ5IchbseUQvCeHEB0A","Vila França","PA"));
        lista.add(new Cidade("CeAhcw3RQCp8VF5Ft9vk","Vila Goreth","PA"));
        lista.add(new Cidade("qxFXLVGUyD37sc3L85YU","Vila Isol","PA"));
        lista.add(new Cidade("CbkVkwEGhq5C1WKLAMbV","Vila Mandi","PA"));
        lista.add(new Cidade("ixtKpojyhxPJxOHMk0Pu","Vila Nova","PA"));
        lista.add(new Cidade("w2VRL3NoS7Tv2YqdPr6b","Vila Planalto","PA"));
        lista.add(new Cidade("2hh0qdxXRQYLvLtofrZk","Vila Santa Fé","PA"));
        lista.add(new Cidade("P3V1bsjqtQLfWfMEfm0F","Vila Socorro","PA"));
        lista.add(new Cidade("apRznTqVTDQiLbrumTXx","Vilarinho do Monte","PA"));
        lista.add(new Cidade("dzbJrW0rLjcgvIFOPP5p","Viseu","PA"));
        lista.add(new Cidade("PtMsYhnptdYSBG4K38n7","Vista Alegre","PA"));
        lista.add(new Cidade("Xfgr2De8n27SEZMJF5vj","Vista Alegre do Pará","PA"));
        lista.add(new Cidade("IL45pQL59t06unFAh88N","Vitória do Xingu","PA"));
        lista.add(new Cidade("274b0SoxakbxcirUJok8","Xinguara","PA"));
        lista.add(new Cidade("F4ESFmF8wDr9OijbSQCG","Xinguarinha","PA"));

        return lista;
    }
}
