package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PB {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Água Branca","PB"));
        lista.add(new Cidade("","Aguiar","PB"));
        lista.add(new Cidade("","Alagoa Grande","PB"));
        lista.add(new Cidade("","Alagoa Nova","PB"));
        lista.add(new Cidade("","Alagoinha","PB"));
        lista.add(new Cidade("","Alcantil","PB"));
        lista.add(new Cidade("","Algodão de Jandaíra","PB"));
        lista.add(new Cidade("","Alhandra","PB"));
        lista.add(new Cidade("","Amparo","PB"));
        lista.add(new Cidade("","Aparecida","PB"));
        lista.add(new Cidade("","Araçagi","PB"));
        lista.add(new Cidade("","Arara","PB"));
        lista.add(new Cidade("","Araruna","PB"));
        lista.add(new Cidade("","Areia","PB"));
        lista.add(new Cidade("","Areia de Baraúnas","PB"));
        lista.add(new Cidade("","Areial","PB"));
        lista.add(new Cidade("","Aroeiras","PB"));
        lista.add(new Cidade("","Assunção","PB"));
        lista.add(new Cidade("","Baía da Traição","PB"));
        lista.add(new Cidade("","Bananeiras","PB"));
        lista.add(new Cidade("","Baraúna","PB"));
        lista.add(new Cidade("","Barra de Santa Rosa","PB"));
        lista.add(new Cidade("","Barra de Santana","PB"));
        lista.add(new Cidade("","Barra de São Miguel","PB"));
        lista.add(new Cidade("","Bayeux","PB"));
        lista.add(new Cidade("","Belém","PB"));
        lista.add(new Cidade("","Belém do Brejo do Cruz","PB"));
        lista.add(new Cidade("","Bernardino Batista","PB"));
        lista.add(new Cidade("","Boa Ventura","PB"));
        lista.add(new Cidade("","Boa Vista","PB"));
        lista.add(new Cidade("","Bom Jesus","PB"));
        lista.add(new Cidade("","Bom Sucesso","PB"));
        lista.add(new Cidade("","Bonito de Santa Fé","PB"));
        lista.add(new Cidade("","Boqueirão","PB"));
        lista.add(new Cidade("","Borborema","PB"));
        lista.add(new Cidade("","Brejo do Cruz","PB"));
        lista.add(new Cidade("","Brejo dos Santos","PB"));
        lista.add(new Cidade("","Caaporã","PB"));
        lista.add(new Cidade("","Cabaceiras","PB"));
        lista.add(new Cidade("","Cabedelo","PB"));
        lista.add(new Cidade("","Cachoeira dos Índios","PB"));
        lista.add(new Cidade("","Cacimba de Areia","PB"));
        lista.add(new Cidade("","Cacimba de Dentro","PB"));
        lista.add(new Cidade("","Cacimbas","PB"));
        lista.add(new Cidade("","Caiçara","PB"));
        lista.add(new Cidade("","Cajazeiras","PB"));
        lista.add(new Cidade("","Cajazeirinhas","PB"));
        lista.add(new Cidade("","Caldas Brandão","PB"));
        lista.add(new Cidade("","Camalaú","PB"));
        lista.add(new Cidade("","Campina Grande","PB"));
        lista.add(new Cidade("","Campo de Santana","PB"));
        lista.add(new Cidade("","Capim","PB"));
        lista.add(new Cidade("","Caraúbas","PB"));
        lista.add(new Cidade("","Carrapateira","PB"));
        lista.add(new Cidade("","Casserengue","PB"));
        lista.add(new Cidade("","Catingueira","PB"));
        lista.add(new Cidade("","Catolé do Rocha","PB"));
        lista.add(new Cidade("","Caturité","PB"));
        lista.add(new Cidade("","Conceição","PB"));
        lista.add(new Cidade("","Condado","PB"));
        lista.add(new Cidade("","Conde","PB"));
        lista.add(new Cidade("","Congo","PB"));
        lista.add(new Cidade("","Coremas","PB"));
        lista.add(new Cidade("","Coxixola","PB"));
        lista.add(new Cidade("","Cruz do Espírito Santo","PB"));
        lista.add(new Cidade("","Cubati","PB"));
        lista.add(new Cidade("","Cuité","PB"));
        lista.add(new Cidade("","Cuité de Mamanguape","PB"));
        lista.add(new Cidade("","Cuitegi","PB"));
        lista.add(new Cidade("","Curral de Cima","PB"));
        lista.add(new Cidade("","Curral Velho","PB"));
        lista.add(new Cidade("","Damião","PB"));
        lista.add(new Cidade("","Desterro","PB"));
        lista.add(new Cidade("","Diamante","PB"));
        lista.add(new Cidade("","Dona Inês","PB"));
        lista.add(new Cidade("","Duas Estradas","PB"));
        lista.add(new Cidade("","Emas","PB"));
        lista.add(new Cidade("","Esperança","PB"));
        lista.add(new Cidade("","Fagundes","PB"));
        lista.add(new Cidade("","Frei Martinho","PB"));
        lista.add(new Cidade("","Gado Bravo","PB"));
        lista.add(new Cidade("","Guarabira","PB"));
        lista.add(new Cidade("","Gurinhém","PB"));
        lista.add(new Cidade("","Gurjão","PB"));
        lista.add(new Cidade("","Ibiara","PB"));
        lista.add(new Cidade("","Igaracy","PB"));
        lista.add(new Cidade("","Imaculada","PB"));
        lista.add(new Cidade("","Ingá","PB"));
        lista.add(new Cidade("","Itabaiana","PB"));
        lista.add(new Cidade("","Itaporanga","PB"));
        lista.add(new Cidade("","Itapororoca","PB"));
        lista.add(new Cidade("","Itatuba","PB"));
        lista.add(new Cidade("","Jacaraú","PB"));
        lista.add(new Cidade("","Jericó","PB"));
        lista.add(new Cidade("","João Pessoa","PB"));
        lista.add(new Cidade("","Juarez Távora","PB"));
        lista.add(new Cidade("","Juazeirinho","PB"));
        lista.add(new Cidade("","Junco do Seridó","PB"));
        lista.add(new Cidade("","Juripiranga","PB"));
        lista.add(new Cidade("","Juru","PB"));
        lista.add(new Cidade("","Lagoa","PB"));
        lista.add(new Cidade("","Lagoa de Dentro","PB"));
        lista.add(new Cidade("","Lagoa Seca","PB"));
        lista.add(new Cidade("","Lastro","PB"));
        lista.add(new Cidade("","Livramento","PB"));
        lista.add(new Cidade("","Logradouro","PB"));
        lista.add(new Cidade("","Lucena","PB"));
        lista.add(new Cidade("","Mãe d'Água","PB"));
        lista.add(new Cidade("","Malta","PB"));
        lista.add(new Cidade("","Mamanguape","PB"));
        lista.add(new Cidade("","Manaíra","PB"));
        lista.add(new Cidade("","Marcação","PB"));
        lista.add(new Cidade("","Mari","PB"));
        lista.add(new Cidade("","Marizópolis","PB"));
        lista.add(new Cidade("","Massaranduba","PB"));
        lista.add(new Cidade("","Mataraca","PB"));
        lista.add(new Cidade("","Matinhas","PB"));
        lista.add(new Cidade("","Mato Grosso","PB"));
        lista.add(new Cidade("","Maturéia","PB"));
        lista.add(new Cidade("","Mogeiro","PB"));
        lista.add(new Cidade("","Montadas","PB"));
        lista.add(new Cidade("","Monte Horebe","PB"));
        lista.add(new Cidade("","Monteiro","PB"));
        lista.add(new Cidade("","Mulungu","PB"));
        lista.add(new Cidade("","Natuba","PB"));
        lista.add(new Cidade("","Nazarezinho","PB"));
        lista.add(new Cidade("","Nova Floresta","PB"));
        lista.add(new Cidade("","Nova Olinda","PB"));
        lista.add(new Cidade("","Nova Palmeira","PB"));
        lista.add(new Cidade("","Olho d'Água","PB"));
        lista.add(new Cidade("","Olivedos","PB"));
        lista.add(new Cidade("","Ouro Velho","PB"));
        lista.add(new Cidade("","Parari","PB"));
        lista.add(new Cidade("","Passagem","PB"));
        lista.add(new Cidade("","Patos","PB"));
        lista.add(new Cidade("","Paulista","PB"));
        lista.add(new Cidade("","Pedra Branca","PB"));
        lista.add(new Cidade("","Pedra Lavrada","PB"));
        lista.add(new Cidade("","Pedras de Fogo","PB"));
        lista.add(new Cidade("","Pedro Régis","PB"));
        lista.add(new Cidade("","Piancó","PB"));
        lista.add(new Cidade("","Picuí","PB"));
        lista.add(new Cidade("","Pilar","PB"));
        lista.add(new Cidade("","Pilões","PB"));
        lista.add(new Cidade("","Pilõezinhos","PB"));
        lista.add(new Cidade("","Pirpirituba","PB"));
        lista.add(new Cidade("","Pitimbu","PB"));
        lista.add(new Cidade("","Pocinhos","PB"));
        lista.add(new Cidade("","Poço Dantas","PB"));
        lista.add(new Cidade("","Poço de José de Moura","PB"));
        lista.add(new Cidade("","Pombal","PB"));
        lista.add(new Cidade("","Prata","PB"));
        lista.add(new Cidade("","Princesa Isabel","PB"));
        lista.add(new Cidade("","Puxinanã","PB"));
        lista.add(new Cidade("","Queimadas","PB"));
        lista.add(new Cidade("","Quixabá","PB"));
        lista.add(new Cidade("","Remígio","PB"));
        lista.add(new Cidade("","Riachão","PB"));
        lista.add(new Cidade("","Riachão do Bacamarte","PB"));
        lista.add(new Cidade("","Riachão do Poço","PB"));
        lista.add(new Cidade("","Riacho de Santo Antônio","PB"));
        lista.add(new Cidade("","Riacho dos Cavalos","PB"));
        lista.add(new Cidade("","Rio Tinto","PB"));
        lista.add(new Cidade("","Salgadinho","PB"));
        lista.add(new Cidade("","Salgado de São Félix","PB"));
        lista.add(new Cidade("","Santa Cecília","PB"));
        lista.add(new Cidade("","Santa Cruz","PB"));
        lista.add(new Cidade("","Santa Helena","PB"));
        lista.add(new Cidade("","Santa Inês","PB"));
        lista.add(new Cidade("","Santa Luzia","PB"));
        lista.add(new Cidade("","Santa Rita","PB"));
        lista.add(new Cidade("","Santa Teresinha","PB"));
        lista.add(new Cidade("","Santana de Mangueira","PB"));
        lista.add(new Cidade("","Santana dos Garrotes","PB"));
        lista.add(new Cidade("","Santarém","PB"));
        lista.add(new Cidade("","Santo André","PB"));
        lista.add(new Cidade("","São Bentinho","PB"));
        lista.add(new Cidade("","São Bento","PB"));
        lista.add(new Cidade("","São Domingos de Pombal","PB"));
        lista.add(new Cidade("","São Domingos do Cariri","PB"));
        lista.add(new Cidade("","São Francisco","PB"));
        lista.add(new Cidade("","São João do Cariri","PB"));
        lista.add(new Cidade("","São João do Rio do Peixe","PB"));
        lista.add(new Cidade("","São João do Tigre","PB"));
        lista.add(new Cidade("","São José da Lagoa Tapada","PB"));
        lista.add(new Cidade("","São José de Caiana","PB"));
        lista.add(new Cidade("","São José de Espinharas","PB"));
        lista.add(new Cidade("","São José de Piranhas","PB"));
        lista.add(new Cidade("","São José de Princesa","PB"));
        lista.add(new Cidade("","São José do Bonfim","PB"));
        lista.add(new Cidade("","São José do Brejo do Cruz","PB"));
        lista.add(new Cidade("","São José do Sabugi","PB"));
        lista.add(new Cidade("","São José dos Cordeiros","PB"));
        lista.add(new Cidade("","São José dos Ramos","PB"));
        lista.add(new Cidade("","São Mamede","PB"));
        lista.add(new Cidade("","São Miguel de Taipu","PB"));
        lista.add(new Cidade("","São Sebastião de Lagoa de Roça","PB"));
        lista.add(new Cidade("","São Sebastião do Umbuzeiro","PB"));
        lista.add(new Cidade("","Sapé","PB"));
        lista.add(new Cidade("","Seridó","PB"));
        lista.add(new Cidade("","Serra Branca","PB"));
        lista.add(new Cidade("","Serra da Raiz","PB"));
        lista.add(new Cidade("","Serra Grande","PB"));
        lista.add(new Cidade("","Serra Redonda","PB"));
        lista.add(new Cidade("","Serraria","PB"));
        lista.add(new Cidade("","Sertãozinho","PB"));
        lista.add(new Cidade("","Sobrado","PB"));
        lista.add(new Cidade("","Solânea","PB"));
        lista.add(new Cidade("","Soledade","PB"));
        lista.add(new Cidade("","Sossêgo","PB"));
        lista.add(new Cidade("","Sousa","PB"));
        lista.add(new Cidade("","Sumé","PB"));
        lista.add(new Cidade("","Taperoá","PB"));
        lista.add(new Cidade("","Tavares","PB"));
        lista.add(new Cidade("","Teixeira","PB"));
        lista.add(new Cidade("","Tenório","PB"));
        lista.add(new Cidade("","Triunfo","PB"));
        lista.add(new Cidade("","Uiraúna","PB"));
        lista.add(new Cidade("","Umbuzeiro","PB"));
        lista.add(new Cidade("","Várzea","PB"));
        lista.add(new Cidade("","Vieirópolis","PB"));
        lista.add(new Cidade("","Vista Serrana","PB"));
        lista.add(new Cidade("","Zabelê","PB"));
        return lista;
    }
}
