package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PB {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("q9rCW8FjGIUh5kOuM0Bu","Água Branca","PB"));
        lista.add(new Cidade("kYum73jBZjnTKyJVUbnS","Aguiar","PB"));
        lista.add(new Cidade("adfz9fiWodGrFlnyXn66","Alagoa Grande","PB"));
        lista.add(new Cidade("d2XKpMmiXMfbIulB7HA5","Alagoa Nova","PB"));
        lista.add(new Cidade("MLtwhgYeXZpb40iiYavk","Alagoinha","PB"));
        lista.add(new Cidade("fQdIzACc5Hy8Pu56qc0h","Alcantil","PB"));
        lista.add(new Cidade("d9nB3RtkdSbVELoECQtE","Algodão de Jandaíra","PB"));
        lista.add(new Cidade("v9etumKcAxdv9rhByheW","Alhandra","PB"));
        lista.add(new Cidade("J91a7pkjEPjGMxzLZysR","Amparo","PB"));
        lista.add(new Cidade("S1lzObhkHpVVLTnLumYo","Aparecida","PB"));
        lista.add(new Cidade("r01dWOZrDLsKIH81RnHP","Araçagi","PB"));
        lista.add(new Cidade("SrkWPwnDn9MjOAz8vBUp","Arara","PB"));
        lista.add(new Cidade("ezu4tzjnGZeBVuLLkApC","Araruna","PB"));
        lista.add(new Cidade("QFebuvpJqSFDa2EQe7NN","Areia","PB"));
        lista.add(new Cidade("TS0XOXpAOjJGRa2SaPQV","Areia de Baraúnas","PB"));
        lista.add(new Cidade("WN1zBrOSQfDCz9DKkbHD","Areial","PB"));
        lista.add(new Cidade("2pLQJQsADCIKJLCJfBjC","Aroeiras","PB"));
        lista.add(new Cidade("FHBkwKZ21jDYQJDhP2DH","Assunção","PB"));
        lista.add(new Cidade("vp57uu3j9tCrg9He89kq","Baía da Traição","PB"));
        lista.add(new Cidade("f0fyGEA8VFwLBDPJhIxH","Bananeiras","PB"));
        lista.add(new Cidade("3psRvWVKikIscTx2jsSS","Baraúna","PB"));
        lista.add(new Cidade("mnpAilQOVuVIe95lMEWC","Barra de Santa Rosa","PB"));
        lista.add(new Cidade("Ubfd6f1IRhrYuIzotsYu","Barra de Santana","PB"));
        lista.add(new Cidade("QNDBxe0yrnxGT8EBU78R","Barra de São Miguel","PB"));
        lista.add(new Cidade("9FOBooPF3NjCBFJIid2U","Bayeux","PB"));
        lista.add(new Cidade("bhpJ5Wulct8shuQ3YiMr","Belém","PB"));
        lista.add(new Cidade("5dNqzexACuRUWHqXXCIC","Belém do Brejo do Cruz","PB"));
        lista.add(new Cidade("AwPBuM6yhlSfMxO28VWF","Bernardino Batista","PB"));
        lista.add(new Cidade("hFwUReafqerTQc8rdEE9","Boa Ventura","PB"));
        lista.add(new Cidade("s3JESD0nYPCuepcreARn","Boa Vista","PB"));
        lista.add(new Cidade("4cbP2v72gP3o7ApcVYn1","Bom Jesus","PB"));
        lista.add(new Cidade("QSDz9LTMNEhNIpQNQADU","Bom Sucesso","PB"));
        lista.add(new Cidade("4z8o4VFULFL1tYgVQ1eM","Bonito de Santa Fé","PB"));
        lista.add(new Cidade("XMNwZkGyvwAiycjlmacj","Boqueirão","PB"));
        lista.add(new Cidade("3sDVTgFo2IASVcmIkM75","Borborema","PB"));
        lista.add(new Cidade("bh645V701VBDXJagfcuI","Brejo do Cruz","PB"));
        lista.add(new Cidade("vLBQtVLIQnET6vS9eltx","Brejo dos Santos","PB"));
        lista.add(new Cidade("bR8fWN6mfYlF7Ouee3Ao","Caaporã","PB"));
        lista.add(new Cidade("Sjm1gTMB3dodKNG3N9Is","Cabaceiras","PB"));
        lista.add(new Cidade("gTbDdqEHDNFdpvTefdce","Cabedelo","PB"));
        lista.add(new Cidade("llqHKhAxNkY1g99iU5XH","Cachoeira dos Índios","PB"));
        lista.add(new Cidade("kOsZ5SOQwbK0ATZQTHqR","Cacimba de Areia","PB"));
        lista.add(new Cidade("5AHeks6IU9aSOE48x8Li","Cacimba de Dentro","PB"));
        lista.add(new Cidade("pMkTaOyhW6W1oLyUfw81","Cacimbas","PB"));
        lista.add(new Cidade("bIcVnfGkiRvWG3v69RVN","Caiçara","PB"));
        lista.add(new Cidade("NZStQG4QRpIJNyHsevhZ","Cajazeiras","PB"));
        lista.add(new Cidade("UkLftyehzaafkSsX6I97","Cajazeirinhas","PB"));
        lista.add(new Cidade("k9VCB7okR53TiCsHil6F","Caldas Brandão","PB"));
        lista.add(new Cidade("9CDOHDLPTjWYPLbtsoId","Camalaú","PB"));
        lista.add(new Cidade("EdOy8m37wN4Avb5rqHk3","Campina Grande","PB"));
        lista.add(new Cidade("tPQ8uvQiqo0PWEmI6me6","Campo de Santana","PB"));
        lista.add(new Cidade("vE9msV9vWU5LnZd6jbJc","Capim","PB"));
        lista.add(new Cidade("F3hlLJwFXqBzO2OyJi67","Caraúbas","PB"));
        lista.add(new Cidade("ZchtFkG7yBglYj91LNUK","Carrapateira","PB"));
        lista.add(new Cidade("yRNo42asHcoB30P9hweD","Casserengue","PB"));
        lista.add(new Cidade("b09kdHkX8HeQVM5pEhbn","Catingueira","PB"));
        lista.add(new Cidade("91GYeEy6C2q70Fcxc05O","Catolé do Rocha","PB"));
        lista.add(new Cidade("UGHBT721wvzGtUpKuyUm","Caturité","PB"));
        lista.add(new Cidade("zzU1Hs1fjjbf3s3eRYL9","Conceição","PB"));
        lista.add(new Cidade("xgFveWt8nsFkKjCGjMn7","Condado","PB"));
        lista.add(new Cidade("jyZ6fvcXghcaP3X75qVI","Conde","PB"));
        lista.add(new Cidade("neH0bkHkE7A9K9q5NiTx","Congo","PB"));
        lista.add(new Cidade("vGoDL0t52Y6F7yfn47DQ","Coremas","PB"));
        lista.add(new Cidade("UdSNLFsL1wggrdqaqG4R","Coxixola","PB"));
        lista.add(new Cidade("4eREN1BFoVCBYJWNXlhk","Cruz do Espírito Santo","PB"));
        lista.add(new Cidade("Dhxvejinu5ivDCCmlR1d","Cubati","PB"));
        lista.add(new Cidade("WYS878hfTlEqUrrUD5m1","Cuité","PB"));
        lista.add(new Cidade("C1LBSvVvIyqQiBiyls1d","Cuité de Mamanguape","PB"));
        lista.add(new Cidade("tYDkPsgfeX3QHZQXpP8B","Cuitegi","PB"));
        lista.add(new Cidade("qlUGGFXuNJPFGEoGgpaO","Curral de Cima","PB"));
        lista.add(new Cidade("PzxXx4VCqiwxvGXJbAir","Curral Velho","PB"));
        lista.add(new Cidade("VietqulpqzBBa3EkyGKD","Damião","PB"));
        lista.add(new Cidade("gmT0bVCljyNiUdxbTpvV","Desterro","PB"));
        lista.add(new Cidade("ZWW4pTkabzu0pA7G0EHo","Diamante","PB"));
        lista.add(new Cidade("sGLOyqSscEnnIiHrXr5J","Dona Inês","PB"));
        lista.add(new Cidade("HilWGCLZmfMcfRFewUZW","Duas Estradas","PB"));
        lista.add(new Cidade("a2CbzKosgglQCLx0B6my","Emas","PB"));
        lista.add(new Cidade("bSopG1jj9WmG77uizkuF","Esperança","PB"));
        lista.add(new Cidade("on2KfXbaTBqsAnVsqPQw","Fagundes","PB"));
        lista.add(new Cidade("PKaUWpSltojnhUi4CYZ1","Frei Martinho","PB"));
        lista.add(new Cidade("JqSaXe981C7kaUrLMa3j","Gado Bravo","PB"));
        lista.add(new Cidade("lbN6CjPzASFjpwXwix4t","Guarabira","PB"));
        lista.add(new Cidade("uSkBD0PLY5VX7EVbnvXg","Gurinhém","PB"));
        lista.add(new Cidade("dqPoswI9p43gcPEOJRjS","Gurjão","PB"));
        lista.add(new Cidade("hW7aTBnaH58mCAmDhFMx","Ibiara","PB"));
        lista.add(new Cidade("S9AxnselsU77UG8HPiNI","Igaracy","PB"));
        lista.add(new Cidade("BSRySJu4pYjrSrBvWIrE","Imaculada","PB"));
        lista.add(new Cidade("vn7EnecJSywtAKq5Ns7E","Ingá","PB"));
        lista.add(new Cidade("t2cN3sXg7dXilkx6pGo5","Itabaiana","PB"));
        lista.add(new Cidade("UA0eYhp69b6hZt5uLowf","Itaporanga","PB"));
        lista.add(new Cidade("OfmN8mopbMf0VIxuOohI","Itapororoca","PB"));
        lista.add(new Cidade("xkvNUkTTK0q0p12bNmTH","Itatuba","PB"));
        lista.add(new Cidade("gd2hcwxDmUjfYPs2Mxdd","Jacaraú","PB"));
        lista.add(new Cidade("nRErI2kdSeHETCP6rprK","Jericó","PB"));
        lista.add(new Cidade("0jBrGnI2tLFnIvM8K3uc","João Pessoa","PB"));
        lista.add(new Cidade("MCUvOxMiLHjQbn2z6XVj","Juarez Távora","PB"));
        lista.add(new Cidade("3Tcem8k5POwhwCTAqBLX","Juazeirinho","PB"));
        lista.add(new Cidade("TSlzAbRdJtpM8NVZCtVu","Junco do Seridó","PB"));
        lista.add(new Cidade("YJxPJhlWsRTAJPa1ZWlg","Juripiranga","PB"));
        lista.add(new Cidade("z3Pb14nbucHfs9apdYo5","Juru","PB"));
        lista.add(new Cidade("tjGdpDm9XlPfzDF3QFyH","Lagoa","PB"));
        lista.add(new Cidade("ub0SYNESV5WhsziJae8e","Lagoa de Dentro","PB"));
        lista.add(new Cidade("XsXU0q7mKsHuFlJjpPko","Lagoa Seca","PB"));
        lista.add(new Cidade("l8WKbg8lSosYS3138hk3","Lastro","PB"));
        lista.add(new Cidade("6vxnf5E0BqaEnEMvb9TU","Livramento","PB"));
        lista.add(new Cidade("8nkl5RY9D8YED5CqqX7u","Logradouro","PB"));
        lista.add(new Cidade("lVQuT0EitWKdHs4Fv7L8","Lucena","PB"));
        lista.add(new Cidade("5w1iScrMsnbzy7JNDick","Mãe d'Água","PB"));
        lista.add(new Cidade("eiKbMqWtGNNuCbTFj59p","Malta","PB"));
        lista.add(new Cidade("3GiaAh2HsIk8LwLdqx1x","Mamanguape","PB"));
        lista.add(new Cidade("3XXqTDMwL72AFyMDYOEF","Manaíra","PB"));
        lista.add(new Cidade("AGfy7E3OJxHqhtPrMZIh","Marcação","PB"));
        lista.add(new Cidade("nWV1L0RbMHoV857gccJP","Mari","PB"));
        lista.add(new Cidade("sZbYnReT7x3uUvn7HKjk","Marizópolis","PB"));
        lista.add(new Cidade("1ZqSbiWcx1wPfU1YslNv","Massaranduba","PB"));
        lista.add(new Cidade("UKyrGsA9LURbbgreoJ1u","Mataraca","PB"));
        lista.add(new Cidade("tGDnCOzyoMqTJ6sgOsrY","Matinhas","PB"));
        lista.add(new Cidade("rlATZio8jC2GeHftHbMo","Mato Grosso","PB"));
        lista.add(new Cidade("eVCgj3Q5MCXc9uiGMzB7","Maturéia","PB"));
        lista.add(new Cidade("h56Cks02gtmwbGijK8Aa","Mogeiro","PB"));
        lista.add(new Cidade("Y8pj6bfMckpsaPnm6Uv0","Montadas","PB"));
        lista.add(new Cidade("ylVU0JuriUqPUudmmGBP","Monte Horebe","PB"));
        lista.add(new Cidade("2u18c95coKDwh4Xcwo4u","Monteiro","PB"));
        lista.add(new Cidade("93g2Y54ydqqjxEJQNPnB","Mulungu","PB"));
        lista.add(new Cidade("f1kULmH09nznjRYU9IdV","Natuba","PB"));
        lista.add(new Cidade("vn3SgRQJikboa5gjgXPo","Nazarezinho","PB"));
        lista.add(new Cidade("Y2jBNfJijrmdourmEZxI","Nova Floresta","PB"));
        lista.add(new Cidade("VMvdeAkF3wRupMw9Xx1e","Nova Olinda","PB"));
        lista.add(new Cidade("zjYx7ldDDOGYldZNIDWs","Nova Palmeira","PB"));
        lista.add(new Cidade("wrEw06qxdLMfypDmUSXZ","Olho d'Água","PB"));
        lista.add(new Cidade("iG0jMq3vsDuVKQOejM51","Olivedos","PB"));
        lista.add(new Cidade("BIxdPRAnpM7lgk86wDm9","Ouro Velho","PB"));
        lista.add(new Cidade("JrU5gxbwsIAOtZe0qROi","Parari","PB"));
        lista.add(new Cidade("wJ90Ej6zo374WrKzVuq3","Passagem","PB"));
        lista.add(new Cidade("Q9bH5g2vAeAQ36gazUpp","Patos","PB"));
        lista.add(new Cidade("iAkGTPOwS9Rh7SsTIPZg","Paulista","PB"));
        lista.add(new Cidade("qLt5t6zEIz6ujYZ7LsUP","Pedra Branca","PB"));
        lista.add(new Cidade("Dk2NGgozKXPyRajW533K","Pedra Lavrada","PB"));
        lista.add(new Cidade("YU130Ccp4isJjxeOuTGp","Pedras de Fogo","PB"));
        lista.add(new Cidade("9LRZ0lwlxjY3luVMgBBM","Pedro Régis","PB"));
        lista.add(new Cidade("40TKOk78j1iLT3x7o3Bv","Piancó","PB"));
        lista.add(new Cidade("auy7UurBc1bIcnVKaT7I","Picuí","PB"));
        lista.add(new Cidade("E7Dc8L3if3crLDh5SZsV","Pilar","PB"));
        lista.add(new Cidade("C8mbvBqytyW14OkbBnFC","Pilões","PB"));
        lista.add(new Cidade("qApekaKr1bQqxfW1DFxZ","Pilõezinhos","PB"));
        lista.add(new Cidade("w2x1K6MjmMjvYWYfgsFZ","Pirpirituba","PB"));
        lista.add(new Cidade("6kVwjQcqWlHkzB5wrLvK","Pitimbu","PB"));
        lista.add(new Cidade("bgGDqFKHwk6H2tjNw0cw","Pocinhos","PB"));
        lista.add(new Cidade("6kWJqptS4QqBIULZBZmN","Poço Dantas","PB"));
        lista.add(new Cidade("CbgjizN3eNdB4SvbdnrX","Poço de José de Moura","PB"));
        lista.add(new Cidade("G846R55Db81SKInNvYdH","Pombal","PB"));
        lista.add(new Cidade("5RXVJsvJ260ZNsHlPQcc","Prata","PB"));
        lista.add(new Cidade("J4fb5YJZqgbvalItj3bi","Princesa Isabel","PB"));
        lista.add(new Cidade("MAji6YMDmaqOoYfn6rGD","Puxinanã","PB"));
        lista.add(new Cidade("e4U95yl5m7JUqLkySosu","Queimadas","PB"));
        lista.add(new Cidade("ksrxlqKPDxPURLdAsiRe","Quixabá","PB"));
        lista.add(new Cidade("FTWfyrldgf7avGwiHvUt","Remígio","PB"));
        lista.add(new Cidade("TzOsADNhNV1HS7VM7v9C","Riachão","PB"));
        lista.add(new Cidade("jQs2FSoxdaGWwEnSsJ7H","Riachão do Bacamarte","PB"));
        lista.add(new Cidade("eEWSiUGc2QFrDDsLL3iR","Riachão do Poço","PB"));
        lista.add(new Cidade("pF7aSKRYycJI6LHk0IW6","Riacho de Santo Antônio","PB"));
        lista.add(new Cidade("lm9fPm9ktkkLQ03aINgM","Riacho dos Cavalos","PB"));
        lista.add(new Cidade("xc01JoxCw5kn9HdiCte4","Rio Tinto","PB"));
        lista.add(new Cidade("LZw95SNgUBHBvz1IJqgG","Salgadinho","PB"));
        lista.add(new Cidade("JZJRCeXR1eEcnko3h2YD","Salgado de São Félix","PB"));
        lista.add(new Cidade("MbcZd8WBaGq2YahGlwts","Santa Cecília","PB"));
        lista.add(new Cidade("T3WlNx7ppkggW471QCn7","Santa Cruz","PB"));
        lista.add(new Cidade("McosmIqL95lvK5Q3LFhj","Santa Helena","PB"));
        lista.add(new Cidade("xZ4a04hkdtrUQ00WsdN1","Santa Inês","PB"));
        lista.add(new Cidade("xJFUrpNr3DOPCMFoBrRk","Santa Luzia","PB"));
        lista.add(new Cidade("jqMGYfPMJpHHtKCqddEX","Santa Rita","PB"));
        lista.add(new Cidade("cnZDZD8ne8J3Kko2GH1M","Santa Teresinha","PB"));
        lista.add(new Cidade("fgH5yXsxv1zQEPKNfW1Q","Santana de Mangueira","PB"));
        lista.add(new Cidade("Xy9TX3Vb8w261fWYSrYe","Santana dos Garrotes","PB"));
        lista.add(new Cidade("6b10Lk3PDOAORdjI9HjW","Santarém","PB"));
        lista.add(new Cidade("ewjKEeOCHkypynHsQlVi","Santo André","PB"));
        lista.add(new Cidade("liPYUpvQlLYAS9Expc2y","São Bentinho","PB"));
        lista.add(new Cidade("DagtGbvMiYe9Okbpla9f","São Bento","PB"));
        lista.add(new Cidade("yss76FvEvuZQcMEwTCuY","São Domingos de Pombal","PB"));
        lista.add(new Cidade("NBa2N9kkAdrRr0FmLekZ","São Domingos do Cariri","PB"));
        lista.add(new Cidade("cYlflxU3GR3jgUSkBgEg","São Francisco","PB"));
        lista.add(new Cidade("gp8Yk6nNx6DPdDDGiRNc","São João do Cariri","PB"));
        lista.add(new Cidade("ME2rouW9BNQ2wMUDubsH","São João do Rio do Peixe","PB"));
        lista.add(new Cidade("qtBqLrOEzs8bg1sGREuP","São João do Tigre","PB"));
        lista.add(new Cidade("VClg4QwWcJ4VrFPGnM0q","São José da Lagoa Tapada","PB"));
        lista.add(new Cidade("iQtq2vMjsO0bEOwR6to6","São José de Caiana","PB"));
        lista.add(new Cidade("KWbt6klecq0FN2YKDvul","São José de Espinharas","PB"));
        lista.add(new Cidade("D81194c9ZqMp6dJuL9bA","São José de Piranhas","PB"));
        lista.add(new Cidade("TfFSLzHTMuRo3hNk5mRL","São José de Princesa","PB"));
        lista.add(new Cidade("Xcj4rN2iaQJxUZfigJ8a","São José do Bonfim","PB"));
        lista.add(new Cidade("8gcK6XaKf57l2ZptVwPf","São José do Brejo do Cruz","PB"));
        lista.add(new Cidade("RpDbe13K2CK0qtDUCqRj","São José do Sabugi","PB"));
        lista.add(new Cidade("sANQmAiwPkCkURiqO0W2","São José dos Cordeiros","PB"));
        lista.add(new Cidade("dwhRKmfCWE07sffXH5c4","São José dos Ramos","PB"));
        lista.add(new Cidade("iQ1qpoiWxvCdL2gQBqpu","São Mamede","PB"));
        lista.add(new Cidade("6Pp4i4ZnJMjhU7VqLqNB","São Miguel de Taipu","PB"));
        lista.add(new Cidade("Q24B31fUOb8xUT1oBmNt","São Sebastião de Lagoa de Roça","PB"));
        lista.add(new Cidade("nmQwAyBTElwtZvnhl1iV","São Sebastião do Umbuzeiro","PB"));
        lista.add(new Cidade("GzbHkiQNYeC61LMV0PE4","Sapé","PB"));
        lista.add(new Cidade("8j5NpIc3IOe56tQzYqsK","Seridó","PB"));
        lista.add(new Cidade("iwxB5Y2Q0CU8n2NfJIXY","Serra Branca","PB"));
        lista.add(new Cidade("b5buvMPHilE7v6PJzEBJ","Serra da Raiz","PB"));
        lista.add(new Cidade("l02SB90Aki9yhfz2z932","Serra Grande","PB"));
        lista.add(new Cidade("gji10hiPrCYaee9d1Uuq","Serra Redonda","PB"));
        lista.add(new Cidade("xx9iFkgCNWDydyAuIAzS","Serraria","PB"));
        lista.add(new Cidade("arWOv5pgrt27IjFqVUqB","Sertãozinho","PB"));
        lista.add(new Cidade("KboIRtA8o1r9uQQFQvb4","Sobrado","PB"));
        lista.add(new Cidade("jlrswcsBSg0NkFnrAeVw","Solânea","PB"));
        lista.add(new Cidade("NbMifcEQ3wwF90OzmQM6","Soledade","PB"));
        lista.add(new Cidade("q8RgG7EIcFEI2JBiluCD","Sossêgo","PB"));
        lista.add(new Cidade("ca7yXa4BH9WaNEFKo7r4","Sousa","PB"));
        lista.add(new Cidade("91EdxRZZ4hvgtwQlS2KP","Sumé","PB"));
        lista.add(new Cidade("85I2CDOwHZJestNADSoc","Taperoá","PB"));
        lista.add(new Cidade("2aBcfnvn4PFDcHQvDKg6","Tavares","PB"));
        lista.add(new Cidade("5ZHxrZxZhy1lRlKbAUfk","Teixeira","PB"));
        lista.add(new Cidade("15J1l86ctpZUiZCSmfym","Tenório","PB"));
        lista.add(new Cidade("05HHgQRSbcHf7KoLYUz2","Triunfo","PB"));
        lista.add(new Cidade("bokT3phsfDfjTR0jHV0A","Uiraúna","PB"));
        lista.add(new Cidade("h7EFAZDeUvwEvsvRowiN","Umbuzeiro","PB"));
        lista.add(new Cidade("zQrc4Or0k9FRnH7NVFqP","Várzea","PB"));
        lista.add(new Cidade("UCEuzhI3knIKwDHpgUfr","Vieirópolis","PB"));
        lista.add(new Cidade("4hDGgA012g2ltETv6Sql","Vista Serrana","PB"));
        lista.add(new Cidade("r6Ohp4DI0eA7BOM6zrcX","Zabelê","PB"));

        return lista;
    }
}
