package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PE {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Abreu e Lima","PE"));
        lista.add(new Cidade("","Afogados da Ingazeira","PE"));
        lista.add(new Cidade("","Afrânio","PE"));
        lista.add(new Cidade("","Agrestina","PE"));
        lista.add(new Cidade("","Água Preta","PE"));
        lista.add(new Cidade("","Águas Belas","PE"));
        lista.add(new Cidade("","Alagoinha","PE"));
        lista.add(new Cidade("","Aliança","PE"));
        lista.add(new Cidade("","Altinho","PE"));
        lista.add(new Cidade("","Amaraji","PE"));
        lista.add(new Cidade("","Angelim","PE"));
        lista.add(new Cidade("","Araçoiaba","PE"));
        lista.add(new Cidade("","Araripina","PE"));
        lista.add(new Cidade("","Arcoverde","PE"));
        lista.add(new Cidade("","Barra de Guabiraba","PE"));
        lista.add(new Cidade("","Barreiros","PE"));
        lista.add(new Cidade("","Belém de Maria","PE"));
        lista.add(new Cidade("","Belém de São Francisco","PE"));
        lista.add(new Cidade("","Belo Jardim","PE"));
        lista.add(new Cidade("","Betânia","PE"));
        lista.add(new Cidade("","Bezerros","PE"));
        lista.add(new Cidade("","Bodocó","PE"));
        lista.add(new Cidade("","Bom Conselho","PE"));
        lista.add(new Cidade("","Bom Jardim","PE"));
        lista.add(new Cidade("","Bonito","PE"));
        lista.add(new Cidade("","Brejão","PE"));
        lista.add(new Cidade("","Brejinho","PE"));
        lista.add(new Cidade("","Brejo da Madre de Deus","PE"));
        lista.add(new Cidade("","Buenos Aires","PE"));
        lista.add(new Cidade("","Buíque","PE"));
        lista.add(new Cidade("","Cabo de Santo Agostinho","PE"));
        lista.add(new Cidade("","Cabrobó","PE"));
        lista.add(new Cidade("","Cachoeirinha","PE"));
        lista.add(new Cidade("","Caetés","PE"));
        lista.add(new Cidade("","Calçado","PE"));
        lista.add(new Cidade("","Calumbi","PE"));
        lista.add(new Cidade("","Camaragibe","PE"));
        lista.add(new Cidade("","Camocim de São Félix","PE"));
        lista.add(new Cidade("","Camutanga","PE"));
        lista.add(new Cidade("","Canhotinho","PE"));
        lista.add(new Cidade("","Capoeiras","PE"));
        lista.add(new Cidade("","Carnaíba","PE"));
        lista.add(new Cidade("","Carnaubeira da Penha","PE"));
        lista.add(new Cidade("","Carpina","PE"));
        lista.add(new Cidade("","Caruaru","PE"));
        lista.add(new Cidade("","Casinhas","PE"));
        lista.add(new Cidade("","Catende","PE"));
        lista.add(new Cidade("","Cedro","PE"));
        lista.add(new Cidade("","Chã de Alegria","PE"));
        lista.add(new Cidade("","Chã Grande","PE"));
        lista.add(new Cidade("","Condado","PE"));
        lista.add(new Cidade("","Correntes","PE"));
        lista.add(new Cidade("","Cortês","PE"));
        lista.add(new Cidade("","Cumaru","PE"));
        lista.add(new Cidade("","Cupira","PE"));
        lista.add(new Cidade("","Custódia","PE"));
        lista.add(new Cidade("","Dormentes","PE"));
        lista.add(new Cidade("","Escada","PE"));
        lista.add(new Cidade("","Exu","PE"));
        lista.add(new Cidade("","Feira Nova","PE"));
        lista.add(new Cidade("","Fernando de Noronha","PE"));
        lista.add(new Cidade("","Ferreiros","PE"));
        lista.add(new Cidade("","Flores","PE"));
        lista.add(new Cidade("","Floresta","PE"));
        lista.add(new Cidade("","Frei Miguelinho","PE"));
        lista.add(new Cidade("","Gameleira","PE"));
        lista.add(new Cidade("","Garanhuns","PE"));
        lista.add(new Cidade("","Glória do Goitá","PE"));
        lista.add(new Cidade("","Goiana","PE"));
        lista.add(new Cidade("","Granito","PE"));
        lista.add(new Cidade("","Gravatá","PE"));
        lista.add(new Cidade("","Iati","PE"));
        lista.add(new Cidade("","Ibimirim","PE"));
        lista.add(new Cidade("","Ibirajuba","PE"));
        lista.add(new Cidade("","Igarassu","PE"));
        lista.add(new Cidade("","Iguaraci","PE"));
        lista.add(new Cidade("","Inajá","PE"));
        lista.add(new Cidade("","Ingazeira","PE"));
        lista.add(new Cidade("","Ipojuca","PE"));
        lista.add(new Cidade("","Ipubi","PE"));
        lista.add(new Cidade("","Itacuruba","PE"));
        lista.add(new Cidade("","Itaíba","PE"));
        lista.add(new Cidade("","Itamaracá","PE"));
        lista.add(new Cidade("","Itambé","PE"));
        lista.add(new Cidade("","Itapetim","PE"));
        lista.add(new Cidade("","Itapissuma","PE"));
        lista.add(new Cidade("","Itaquitinga","PE"));
        lista.add(new Cidade("","Jaboatão dos Guararapes","PE"));
        lista.add(new Cidade("","Jaqueira","PE"));
        lista.add(new Cidade("","Jataúba","PE"));
        lista.add(new Cidade("","Jatobá","PE"));
        lista.add(new Cidade("","João Alfredo","PE"));
        lista.add(new Cidade("","Joaquim Nabuco","PE"));
        lista.add(new Cidade("","Jucati","PE"));
        lista.add(new Cidade("","Jupi","PE"));
        lista.add(new Cidade("","Jurema","PE"));
        lista.add(new Cidade("","Lagoa do Carro","PE"));
        lista.add(new Cidade("","Lagoa do Itaenga","PE"));
        lista.add(new Cidade("","Lagoa do Ouro","PE"));
        lista.add(new Cidade("","Lagoa dos Gatos","PE"));
        lista.add(new Cidade("","Lagoa Grande","PE"));
        lista.add(new Cidade("","Lajedo","PE"));
        lista.add(new Cidade("","Limoeiro","PE"));
        lista.add(new Cidade("","Macaparana","PE"));
        lista.add(new Cidade("","Machados","PE"));
        lista.add(new Cidade("","Manari","PE"));
        lista.add(new Cidade("","Maraial","PE"));
        lista.add(new Cidade("","Mirandiba","PE"));
        lista.add(new Cidade("","Moreilândia","PE"));
        lista.add(new Cidade("","Moreno","PE"));
        lista.add(new Cidade("","Nazaré da Mata","PE"));
        lista.add(new Cidade("","Olinda","PE"));
        lista.add(new Cidade("","Orobó","PE"));
        lista.add(new Cidade("","Orocó","PE"));
        lista.add(new Cidade("","Ouricuri","PE"));
        lista.add(new Cidade("","Palmares","PE"));
        lista.add(new Cidade("","Palmeirina","PE"));
        lista.add(new Cidade("","Panelas","PE"));
        lista.add(new Cidade("","Paranatama","PE"));
        lista.add(new Cidade("","Parnamirim","PE"));
        lista.add(new Cidade("","Passira","PE"));
        lista.add(new Cidade("","Paudalho","PE"));
        lista.add(new Cidade("","Paulista","PE"));
        lista.add(new Cidade("","Pedra","PE"));
        lista.add(new Cidade("","Pesqueira","PE"));
        lista.add(new Cidade("","Petrolândia","PE"));
        lista.add(new Cidade("","Petrolina","PE"));
        lista.add(new Cidade("","Poção","PE"));
        lista.add(new Cidade("","Pombos","PE"));
        lista.add(new Cidade("","Primavera","PE"));
        lista.add(new Cidade("","Quipapá","PE"));
        lista.add(new Cidade("","Quixaba","PE"));
        lista.add(new Cidade("","Recife","PE"));
        lista.add(new Cidade("","Riacho das Almas","PE"));
        lista.add(new Cidade("","Ribeirão","PE"));
        lista.add(new Cidade("","Rio Formoso","PE"));
        lista.add(new Cidade("","Sairé","PE"));
        lista.add(new Cidade("","Salgadinho","PE"));
        lista.add(new Cidade("","Salgueiro","PE"));
        lista.add(new Cidade("","Saloá","PE"));
        lista.add(new Cidade("","Sanharó","PE"));
        lista.add(new Cidade("","Santa Cruz","PE"));
        lista.add(new Cidade("","Santa Cruz da Baixa Verde","PE"));
        lista.add(new Cidade("","Santa Cruz do Capibaribe","PE"));
        lista.add(new Cidade("","Santa Filomena","PE"));
        lista.add(new Cidade("","Santa Maria da Boa Vista","PE"));
        lista.add(new Cidade("","Santa Maria do Cambucá","PE"));
        lista.add(new Cidade("","Santa Terezinha","PE"));
        lista.add(new Cidade("","São Benedito do Sul","PE"));
        lista.add(new Cidade("","São Bento do Una","PE"));
        lista.add(new Cidade("","São Caitano","PE"));
        lista.add(new Cidade("","São João","PE"));
        lista.add(new Cidade("","São Joaquim do Monte","PE"));
        lista.add(new Cidade("","São José da Coroa Grande","PE"));
        lista.add(new Cidade("","São José do Belmonte","PE"));
        lista.add(new Cidade("","São José do Egito","PE"));
        lista.add(new Cidade("","São Lourenço da Mata","PE"));
        lista.add(new Cidade("","São Vicente Ferrer","PE"));
        lista.add(new Cidade("","Serra Talhada","PE"));
        lista.add(new Cidade("","Serrita","PE"));
        lista.add(new Cidade("","Sertânia","PE"));
        lista.add(new Cidade("","Sirinhaém","PE"));
        lista.add(new Cidade("","Solidão","PE"));
        lista.add(new Cidade("","Surubim","PE"));
        lista.add(new Cidade("","Tabira","PE"));
        lista.add(new Cidade("","Tacaimbó","PE"));
        lista.add(new Cidade("","Tacaratu","PE"));
        lista.add(new Cidade("","Tamandaré","PE"));
        lista.add(new Cidade("","Taquaritinga do Norte","PE"));
        lista.add(new Cidade("","Terezinha","PE"));
        lista.add(new Cidade("","Terra Nova","PE"));
        lista.add(new Cidade("","Timbaúba","PE"));
        lista.add(new Cidade("","Toritama","PE"));
        lista.add(new Cidade("","Tracunhaém","PE"));
        lista.add(new Cidade("","Trindade","PE"));
        lista.add(new Cidade("","Triunfo","PE"));
        lista.add(new Cidade("","Tupanatinga","PE"));
        lista.add(new Cidade("","Tuparetama","PE"));
        lista.add(new Cidade("","Venturosa","PE"));
        lista.add(new Cidade("","Verdejante","PE"));
        lista.add(new Cidade("","Vertente do Lério","PE"));
        lista.add(new Cidade("","Vertentes","PE"));
        lista.add(new Cidade("","Vicência","PE"));
        lista.add(new Cidade("","Vitória de Santo Antão","PE"));
        lista.add(new Cidade("","Xexéu","PE"));

        return lista;
    }
}
