package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PE {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("RI7DFAnhMxjBWBqz5Brz","Abreu e Lima","PE"));
        lista.add(new Cidade("zRHl1PyfOPWySoRFhgDd","Afogados da Ingazeira","PE"));
        lista.add(new Cidade("LoWRYCTmxXjKoZtQ0z01","Afrânio","PE"));
        lista.add(new Cidade("QBK91GdXO0tNDM1b7vsb","Agrestina","PE"));
        lista.add(new Cidade("01RsJEdteWiYwCdeKK9R","Água Preta","PE"));
        lista.add(new Cidade("bVT0ILe1gidmMFwAJa6x","Águas Belas","PE"));
        lista.add(new Cidade("nlqcMqGJ4nF6ZKpNigwp","Alagoinha","PE"));
        lista.add(new Cidade("q2VQchEaz9gJtQdCQXF7","Aliança","PE"));
        lista.add(new Cidade("hWxMJfF76qZJ2MDReVrV","Altinho","PE"));
        lista.add(new Cidade("CPFq5FBppfb7FJfwzmbk","Amaraji","PE"));
        lista.add(new Cidade("IBlKFOxYocYJ7HcpH1ox","Angelim","PE"));
        lista.add(new Cidade("HhV4k6Y4c4XiW7AaZwcQ","Araçoiaba","PE"));
        lista.add(new Cidade("QTprko0cdncFVM5yCVfD","Araripina","PE"));
        lista.add(new Cidade("bQpICA2MptjyPwZrSe2C","Arcoverde","PE"));
        lista.add(new Cidade("dzGSm1CGcP4bC4pZGlke","Barra de Guabiraba","PE"));
        lista.add(new Cidade("tu2VB9eOYtxRDxjO6IJ2","Barreiros","PE"));
        lista.add(new Cidade("GtNqsRpBRznj56sGlPoi","Belém de Maria","PE"));
        lista.add(new Cidade("BUJqcAMA6hFvYPKu9Qp4","Belém de São Francisco","PE"));
        lista.add(new Cidade("bAIVfjEWCo2vmGi9E87U","Belo Jardim","PE"));
        lista.add(new Cidade("ffoxCt3jU11TCCh5phVN","Betânia","PE"));
        lista.add(new Cidade("98R58ULZ1VbqALctIa5z","Bezerros","PE"));
        lista.add(new Cidade("z5dB6ts6wrt0lU4C1mFp","Bodocó","PE"));
        lista.add(new Cidade("HOj4OyZsGf8CkWbV7yp8","Bom Conselho","PE"));
        lista.add(new Cidade("cagXm5MUIkVghkFqC8UN","Bom Jardim","PE"));
        lista.add(new Cidade("tIcW2ckXt8XHsgwVjrCb","Bonito","PE"));
        lista.add(new Cidade("YBOH1dN9fRhXRnATXrOs","Brejão","PE"));
        lista.add(new Cidade("xnPXjxKjm8ZHScwFSxh1","Brejinho","PE"));
        lista.add(new Cidade("BuUbUEUVslpmleuBRsC0","Brejo da Madre de Deus","PE"));
        lista.add(new Cidade("DFMkTTqLNsNe36Ww8oTa","Buenos Aires","PE"));
        lista.add(new Cidade("VG0ulLsQzse6jBChBxno","Buíque","PE"));
        lista.add(new Cidade("WluUmtODdAdM07EIvctd","Cabo de Santo Agostinho","PE"));
        lista.add(new Cidade("zwJYY6JmH01bzpqs2llv","Cabrobó","PE"));
        lista.add(new Cidade("m2iaMz9jtgL3Eman9mLy","Cachoeirinha","PE"));
        lista.add(new Cidade("wW92fGuwQ5wIX2f4zGIy","Caetés","PE"));
        lista.add(new Cidade("k5f2C6w8fMEPpFWNgxkQ","Calçado","PE"));
        lista.add(new Cidade("eWzH6nnnYgOuWg7ifdey","Calumbi","PE"));
        lista.add(new Cidade("KeDodtmtYyi4fm0It8Pf","Camaragibe","PE"));
        lista.add(new Cidade("dwGTxRpJ4GEsMYdfFSgs","Camocim de São Félix","PE"));
        lista.add(new Cidade("VPZ8HIKoKnET7h1xRoUo","Camutanga","PE"));
        lista.add(new Cidade("rtw5afvzDDVwBzbNgFmY","Canhotinho","PE"));
        lista.add(new Cidade("mklBVi9XqIwDeNNYCZXf","Capoeiras","PE"));
        lista.add(new Cidade("G1PcqKuhDfZwbjLjpd4i","Carnaíba","PE"));
        lista.add(new Cidade("pkrHa9RYaCvRhZZuhXSv","Carnaubeira da Penha","PE"));
        lista.add(new Cidade("KianllmHecDcsQ9qM0Y2","Carpina","PE"));
        lista.add(new Cidade("WEddvZAFoikvq7HN2D8W","Caruaru","PE"));
        lista.add(new Cidade("ZYoDfwDNGdgJmRCFFHIW","Casinhas","PE"));
        lista.add(new Cidade("HlKq5jfwSnqpjK9ia7GS","Catende","PE"));
        lista.add(new Cidade("C9CSYnC9FgQKq3YoVMJ9","Cedro","PE"));
        lista.add(new Cidade("ax6C1kQY3hSLONL8X5RD","Chã de Alegria","PE"));
        lista.add(new Cidade("iq7WdVTTLbDP0OND6HGg","Chã Grande","PE"));
        lista.add(new Cidade("XltObIIDzlmrJe9dhRtT","Condado","PE"));
        lista.add(new Cidade("RxanQ0TtNTkKy9TjM7Le","Correntes","PE"));
        lista.add(new Cidade("6TXTNpn2MnUQE4nCEfYB","Cortês","PE"));
        lista.add(new Cidade("QP1PsZsU9d7LiwKBhlgc","Cumaru","PE"));
        lista.add(new Cidade("WABg0A0nUafbeUXzDs4f","Cupira","PE"));
        lista.add(new Cidade("WzH5zUOUdvjEjCa5ESyh","Custódia","PE"));
        lista.add(new Cidade("aoOiOgpaffAS2p9SkpZL","Dormentes","PE"));
        lista.add(new Cidade("sRkzF1fB95gLBptD0pob","Escada","PE"));
        lista.add(new Cidade("eKXjP4oxZLn6ZdoynaNM","Exu","PE"));
        lista.add(new Cidade("Pn4WpT6MjMwUsNbk2hBF","Feira Nova","PE"));
        lista.add(new Cidade("Y8nkDsqmJMml75VQg1Bq","Fernando de Noronha","PE"));
        lista.add(new Cidade("KCU1c7qZIMW714n93xMu","Ferreiros","PE"));
        lista.add(new Cidade("V1ohiMSSQhXlW9tHQmEb","Flores","PE"));
        lista.add(new Cidade("jBs0YgRUt1pWP9fEVMpq","Floresta","PE"));
        lista.add(new Cidade("tyZUCGHxcmxE6zw5LS9v","Frei Miguelinho","PE"));
        lista.add(new Cidade("cBA1TB87fVfzkcBHZltA","Gameleira","PE"));
        lista.add(new Cidade("PWkFkvCrfSQBFSfZqLvl","Garanhuns","PE"));
        lista.add(new Cidade("MqLpHZNvuDobPXYWEetX","Glória do Goitá","PE"));
        lista.add(new Cidade("kU4MPL7sRhSm3aBn0B16","Goiana","PE"));
        lista.add(new Cidade("FlaDypHSdceYarVyRvVx","Granito","PE"));
        lista.add(new Cidade("iPaVmJYlXk3ovt2J4gXd","Gravatá","PE"));
        lista.add(new Cidade("0BwBLSAzEWpcYxPo57Hf","Iati","PE"));
        lista.add(new Cidade("uBwRZP79lp8Iao7BlNlv","Ibimirim","PE"));
        lista.add(new Cidade("BpCJgNVPXny6fj8zUiti","Ibirajuba","PE"));
        lista.add(new Cidade("Rqa47mEevxkQ8hZ5S3x4","Igarassu","PE"));
        lista.add(new Cidade("tU2a7RHwFFNSM5KFkBYZ","Iguaraci","PE"));
        lista.add(new Cidade("5QeUiAXzrnpJ5B4fIBGA","Inajá","PE"));
        lista.add(new Cidade("WI2s1h2jQldu5iRD4WY4","Ingazeira","PE"));
        lista.add(new Cidade("yzZOoYl0KShZOIWwINmK","Ipojuca","PE"));
        lista.add(new Cidade("VZSUXIzNQQPTv1mFn384","Ipubi","PE"));
        lista.add(new Cidade("E4lokwEplxxU4StrdodX","Itacuruba","PE"));
        lista.add(new Cidade("pnHnmJkAbjZdN76ZB6d7","Itaíba","PE"));
        lista.add(new Cidade("wpDjJnxS5hPb2CeJS4f9","Itamaracá","PE"));
        lista.add(new Cidade("RrePDMGB2caLFOMZgc7s","Itambé","PE"));
        lista.add(new Cidade("A4lQEjFtMeS0I6I5hc5c","Itapetim","PE"));
        lista.add(new Cidade("rbuF561bLHmg8AtgmWTk","Itapissuma","PE"));
        lista.add(new Cidade("kJBTsKWP1Pfn3490GU4e","Itaquitinga","PE"));
        lista.add(new Cidade("wNr6vwQQTk0QPqEcW7T3","Jaboatão dos Guararapes","PE"));
        lista.add(new Cidade("zxPQzZtTC2RyuDs2srlO","Jaqueira","PE"));
        lista.add(new Cidade("Az16ZaxV5z4Qi7KyANvJ","Jataúba","PE"));
        lista.add(new Cidade("VuF2HZsdyDrtzUH5K7E9","Jatobá","PE"));
        lista.add(new Cidade("KBto67oOzvm7dNE5kuyg","João Alfredo","PE"));
        lista.add(new Cidade("3qgORYAHLdJaIAr4KgPi","Joaquim Nabuco","PE"));
        lista.add(new Cidade("XNtMTSkrA1a7USpLNvN3","Jucati","PE"));
        lista.add(new Cidade("uceTrn1WJE7dthRNJr6z","Jupi","PE"));
        lista.add(new Cidade("g7UcvD9OE8dFVbChY11y","Jurema","PE"));
        lista.add(new Cidade("RVgqXmWQgKEt3JTMNFOH","Lagoa do Carro","PE"));
        lista.add(new Cidade("Nx0TSzOCQavNgEVHI1IF","Lagoa do Itaenga","PE"));
        lista.add(new Cidade("TSsBZGhcYoyMCzJCHyhH","Lagoa do Ouro","PE"));
        lista.add(new Cidade("MwaZRFQMLAI95VzRDj0b","Lagoa dos Gatos","PE"));
        lista.add(new Cidade("H1Qna17jzczD18MUgNAt","Lagoa Grande","PE"));
        lista.add(new Cidade("gLaYm0hhQ5KPHyHEAjmb","Lajedo","PE"));
        lista.add(new Cidade("NmKUjAPXhHb6qXagzNaN","Limoeiro","PE"));
        lista.add(new Cidade("HRejO7qHx77lpeeIlMDP","Macaparana","PE"));
        lista.add(new Cidade("GbrIs5yKo0OTtCv3SbcW","Machados","PE"));
        lista.add(new Cidade("WK9gKktHQk07DNBYjqtG","Manari","PE"));
        lista.add(new Cidade("hi4fVvAgBgUGr5PbEYqL","Maraial","PE"));
        lista.add(new Cidade("pr2YsTLKqGAfGYEdnczi","Mirandiba","PE"));
        lista.add(new Cidade("TcDYfWFBkyc6HXtyKU5v","Moreilândia","PE"));
        lista.add(new Cidade("yzEsyqCxsc3SjLFYDsyB","Moreno","PE"));
        lista.add(new Cidade("auo8SspG1uHUcezKFkzZ","Nazaré da Mata","PE"));
        lista.add(new Cidade("DW3RpLidsInH7yGs5aw4","Olinda","PE"));
        lista.add(new Cidade("r1pdKyeKOzDXiuXyhy3t","Orobó","PE"));
        lista.add(new Cidade("xWSOcHWLS2KhqjC7f4kx","Orocó","PE"));
        lista.add(new Cidade("zByfVGEMtY2fMs4gRSkn","Ouricuri","PE"));
        lista.add(new Cidade("VxDsG4xwECDY08VLXLRU","Palmares","PE"));
        lista.add(new Cidade("WTWLgxFQoajhewBK66yA","Palmeirina","PE"));
        lista.add(new Cidade("FiYaOpisgufDSJP0gieG","Panelas","PE"));
        lista.add(new Cidade("e6uxFLw3O8Jb5H84SfjW","Paranatama","PE"));
        lista.add(new Cidade("v2W2dyfWfFrPJNcSnCgW","Parnamirim","PE"));
        lista.add(new Cidade("OA0JOFJBYyPwFZeojYvR","Passira","PE"));
        lista.add(new Cidade("6taXvjXkeMgs6AhCRn6e","Paudalho","PE"));
        lista.add(new Cidade("xoKzwH5K6UsR04z7ur96","Paulista","PE"));
        lista.add(new Cidade("hiYMQDfAecSQYWCN1FgB","Pedra","PE"));
        lista.add(new Cidade("hQvSgcfpCRaiJpsPUM4V","Pesqueira","PE"));
        lista.add(new Cidade("fe0YxwnLeghdbLHG4VvA","Petrolândia","PE"));
        lista.add(new Cidade("HdCKUD9irtcjVOU4bg6Q","Petrolina","PE"));
        lista.add(new Cidade("F4uXSJzxzF4HEkqm5QUk","Poção","PE"));
        lista.add(new Cidade("xsMu0CkZoBs4p6IFPS4n","Pombos","PE"));
        lista.add(new Cidade("EuI7X4dGKpae6lo8pHI5","Primavera","PE"));
        lista.add(new Cidade("JagN1Oom3pCupG0RggZO","Quipapá","PE"));
        lista.add(new Cidade("Lh9LzLDVSEPbaTMn5IPw","Quixaba","PE"));
        lista.add(new Cidade("oELRf77Mxeeu8Og2dxNd","Recife","PE"));
        lista.add(new Cidade("fvzZPSfw0W7GT4GSXZ1r","Riacho das Almas","PE"));
        lista.add(new Cidade("UkcGPuAusjS6KYgUTgc9","Ribeirão","PE"));
        lista.add(new Cidade("BWjeo98Om5ie0vVonMVM","Rio Formoso","PE"));
        lista.add(new Cidade("HJ8vEyxJIvtHLK0QoLFD","Sairé","PE"));
        lista.add(new Cidade("n9D4ZQe4GhCHgW9cjQRt","Salgadinho","PE"));
        lista.add(new Cidade("4y4SNTynmVY8TOWLlJRA","Salgueiro","PE"));
        lista.add(new Cidade("RZgt1ayU8K3BXObnmaSI","Saloá","PE"));
        lista.add(new Cidade("rwUvt1jqccihZTvfh9oe","Sanharó","PE"));
        lista.add(new Cidade("ejceDY63QSpGlKO1rKSh","Santa Cruz","PE"));
        lista.add(new Cidade("CKkp5sgrkxpaqd8Nk3uU","Santa Cruz da Baixa Verde","PE"));
        lista.add(new Cidade("27wcj9c5m5hVLjxRsWy6","Santa Cruz do Capibaribe","PE"));
        lista.add(new Cidade("tUhLusRFyaAXXrHBnYmD","Santa Filomena","PE"));
        lista.add(new Cidade("H7AM5GEwO5LOfsWudAo7","Santa Maria da Boa Vista","PE"));
        lista.add(new Cidade("YsMWYGOizf24vjMlrRlg","Santa Maria do Cambucá","PE"));
        lista.add(new Cidade("6sAKh1ehWUieaIzXatEX","Santa Terezinha","PE"));
        lista.add(new Cidade("PTJ1NLuGzisWvSuxYzI8","São Benedito do Sul","PE"));
        lista.add(new Cidade("KhUVAj6zLzFMj7VYtCEa","São Bento do Una","PE"));
        lista.add(new Cidade("JYvhCv8U8asfYeTAHXQY","São Caitano","PE"));
        lista.add(new Cidade("mL7Iga21ejRiWecbMsyl","São João","PE"));
        lista.add(new Cidade("SKDCl2ffeDzrCe4oCxxx","São Joaquim do Monte","PE"));
        lista.add(new Cidade("VanPg4CdDsrg2DJuiLzl","São José da Coroa Grande","PE"));
        lista.add(new Cidade("lGzAK28kDHM5919ezeoC","São José do Belmonte","PE"));
        lista.add(new Cidade("8nu4i86CBGKA5J2J5TzP","São José do Egito","PE"));
        lista.add(new Cidade("RVhBBtEY9V84Uhl6kPtc","São Lourenço da Mata","PE"));
        lista.add(new Cidade("h3khCe5KZzTvYKL6JFcE","São Vicente Ferrer","PE"));
        lista.add(new Cidade("uPCzIJXeyKUIzhpZHJEJ","Serra Talhada","PE"));
        lista.add(new Cidade("n1qCNDirSLe1Cb2S1Ir8","Serrita","PE"));
        lista.add(new Cidade("hCHiRhw8S6T6HIoTi608","Sertânia","PE"));
        lista.add(new Cidade("DGBgHPsuaAnlnWwzsvnJ","Sirinhaém","PE"));
        lista.add(new Cidade("YNPEn99fxOMSt1CJa9Hx","Solidão","PE"));
        lista.add(new Cidade("QkQyeItBqq0AcpeZx29h","Surubim","PE"));
        lista.add(new Cidade("GTW03K4RjyD6rVzEEahY","Tabira","PE"));
        lista.add(new Cidade("vyX0quT4Ztg7jrA0vhre","Tacaimbó","PE"));
        lista.add(new Cidade("y0pWd7S7vPzbZtc6WNop","Tacaratu","PE"));
        lista.add(new Cidade("0Oul8baroDRBzQjFYQEm","Tamandaré","PE"));
        lista.add(new Cidade("gpPuA1PdzOqYmvx9UE3n","Taquaritinga do Norte","PE"));
        lista.add(new Cidade("Vr9a8bzML9qhv076F8q4","Terezinha","PE"));
        lista.add(new Cidade("sfscS43NDGLA9Hqoqdlr","Terra Nova","PE"));
        lista.add(new Cidade("e9kfIxDRKydFNNNj94Nw","Timbaúba","PE"));
        lista.add(new Cidade("L3WSPCBPXWXJKUbGxzpV","Toritama","PE"));
        lista.add(new Cidade("mCLYT2vqNBqTwCFnc95w","Tracunhaém","PE"));
        lista.add(new Cidade("vo5Ai66TAy2QybMsgvyq","Trindade","PE"));
        lista.add(new Cidade("H4EbuRWF724PeCttF4El","Triunfo","PE"));
        lista.add(new Cidade("O6aazYGdRpdTQuUD0wJY","Tupanatinga","PE"));
        lista.add(new Cidade("E9zBBJawGbyJ5cDNSrsb","Tuparetama","PE"));
        lista.add(new Cidade("2589pfE6s27gwNNnCJbF","Venturosa","PE"));
        lista.add(new Cidade("giWkm8ynbmt3GwLiZwJQ","Verdejante","PE"));
        lista.add(new Cidade("ecipuZgIG2kkLPm3af9s","Vertente do Lério","PE"));
        lista.add(new Cidade("lL55QXBMp10gasiFGl8J","Vertentes","PE"));
        lista.add(new Cidade("0qJVAwZpSZ75B9zsUmrN","Vicência","PE"));
        lista.add(new Cidade("Ciq3yMSWddytOorUUw6z","Vitória de Santo Antão","PE"));
        lista.add(new Cidade("rscW27M04z85U7CcDrSZ","Xexéu","PE"));

        return lista;
    }
}
