package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PE {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("RI7DFAnhMxjBWBqz5Brz","Abreu e Lima","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("zRHl1PyfOPWySoRFhgDd","Afogados da Ingazeira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("LoWRYCTmxXjKoZtQ0z01","Afrânio","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("QBK91GdXO0tNDM1b7vsb","Agrestina","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("01RsJEdteWiYwCdeKK9R","Água Preta","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("bVT0ILe1gidmMFwAJa6x","Águas Belas","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("nlqcMqGJ4nF6ZKpNigwp","Alagoinha","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("q2VQchEaz9gJtQdCQXF7","Aliança","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("hWxMJfF76qZJ2MDReVrV","Altinho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("CPFq5FBppfb7FJfwzmbk","Amaraji","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("IBlKFOxYocYJ7HcpH1ox","Angelim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("HhV4k6Y4c4XiW7AaZwcQ","Araçoiaba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("QTprko0cdncFVM5yCVfD","Araripina","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("bQpICA2MptjyPwZrSe2C","Arcoverde","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("dzGSm1CGcP4bC4pZGlke","Barra de Guabiraba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("tu2VB9eOYtxRDxjO6IJ2","Barreiros","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("GtNqsRpBRznj56sGlPoi","Belém de Maria","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("BUJqcAMA6hFvYPKu9Qp4","Belém de São Francisco","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("bAIVfjEWCo2vmGi9E87U","Belo Jardim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("ffoxCt3jU11TCCh5phVN","Betânia","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("98R58ULZ1VbqALctIa5z","Bezerros","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("z5dB6ts6wrt0lU4C1mFp","Bodocó","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("HOj4OyZsGf8CkWbV7yp8","Bom Conselho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("cagXm5MUIkVghkFqC8UN","Bom Jardim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("tIcW2ckXt8XHsgwVjrCb","Bonito","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("YBOH1dN9fRhXRnATXrOs","Brejão","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("xnPXjxKjm8ZHScwFSxh1","Brejinho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("BuUbUEUVslpmleuBRsC0","Brejo da Madre de Deus","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("DFMkTTqLNsNe36Ww8oTa","Buenos Aires","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("VG0ulLsQzse6jBChBxno","Buíque","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WluUmtODdAdM07EIvctd","Cabo de Santo Agostinho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("zwJYY6JmH01bzpqs2llv","Cabrobó","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("m2iaMz9jtgL3Eman9mLy","Cachoeirinha","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("wW92fGuwQ5wIX2f4zGIy","Caetés","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("k5f2C6w8fMEPpFWNgxkQ","Calçado","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("eWzH6nnnYgOuWg7ifdey","Calumbi","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("KeDodtmtYyi4fm0It8Pf","Camaragibe","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("dwGTxRpJ4GEsMYdfFSgs","Camocim de São Félix","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("VPZ8HIKoKnET7h1xRoUo","Camutanga","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("rtw5afvzDDVwBzbNgFmY","Canhotinho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("mklBVi9XqIwDeNNYCZXf","Capoeiras","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("G1PcqKuhDfZwbjLjpd4i","Carnaíba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("pkrHa9RYaCvRhZZuhXSv","Carnaubeira da Penha","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("KianllmHecDcsQ9qM0Y2","Carpina","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WEddvZAFoikvq7HN2D8W","Caruaru","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("ZYoDfwDNGdgJmRCFFHIW","Casinhas","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("HlKq5jfwSnqpjK9ia7GS","Catende","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("C9CSYnC9FgQKq3YoVMJ9","Cedro","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("ax6C1kQY3hSLONL8X5RD","Chã de Alegria","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("iq7WdVTTLbDP0OND6HGg","Chã Grande","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("XltObIIDzlmrJe9dhRtT","Condado","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("RxanQ0TtNTkKy9TjM7Le","Correntes","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("6TXTNpn2MnUQE4nCEfYB","Cortês","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("QP1PsZsU9d7LiwKBhlgc","Cumaru","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WABg0A0nUafbeUXzDs4f","Cupira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WzH5zUOUdvjEjCa5ESyh","Custódia","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("aoOiOgpaffAS2p9SkpZL","Dormentes","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("sRkzF1fB95gLBptD0pob","Escada","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("eKXjP4oxZLn6ZdoynaNM","Exu","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Pn4WpT6MjMwUsNbk2hBF","Feira Nova","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Y8nkDsqmJMml75VQg1Bq","Fernando de Noronha","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("KCU1c7qZIMW714n93xMu","Ferreiros","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("V1ohiMSSQhXlW9tHQmEb","Flores","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("jBs0YgRUt1pWP9fEVMpq","Floresta","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("tyZUCGHxcmxE6zw5LS9v","Frei Miguelinho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("cBA1TB87fVfzkcBHZltA","Gameleira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("PWkFkvCrfSQBFSfZqLvl","Garanhuns","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("MqLpHZNvuDobPXYWEetX","Glória do Goitá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("kU4MPL7sRhSm3aBn0B16","Goiana","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("FlaDypHSdceYarVyRvVx","Granito","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("iPaVmJYlXk3ovt2J4gXd","Gravatá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("0BwBLSAzEWpcYxPo57Hf","Iati","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("uBwRZP79lp8Iao7BlNlv","Ibimirim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("BpCJgNVPXny6fj8zUiti","Ibirajuba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Rqa47mEevxkQ8hZ5S3x4","Igarassu","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("tU2a7RHwFFNSM5KFkBYZ","Iguaraci","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("5QeUiAXzrnpJ5B4fIBGA","Inajá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WI2s1h2jQldu5iRD4WY4","Ingazeira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("yzZOoYl0KShZOIWwINmK","Ipojuca","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("VZSUXIzNQQPTv1mFn384","Ipubi","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("E4lokwEplxxU4StrdodX","Itacuruba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("pnHnmJkAbjZdN76ZB6d7","Itaíba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("wpDjJnxS5hPb2CeJS4f9","Itamaracá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("RrePDMGB2caLFOMZgc7s","Itambé","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("A4lQEjFtMeS0I6I5hc5c","Itapetim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("rbuF561bLHmg8AtgmWTk","Itapissuma","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("kJBTsKWP1Pfn3490GU4e","Itaquitinga","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("wNr6vwQQTk0QPqEcW7T3","Jaboatão dos Guararapes","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("zxPQzZtTC2RyuDs2srlO","Jaqueira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Az16ZaxV5z4Qi7KyANvJ","Jataúba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("VuF2HZsdyDrtzUH5K7E9","Jatobá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("KBto67oOzvm7dNE5kuyg","João Alfredo","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("3qgORYAHLdJaIAr4KgPi","Joaquim Nabuco","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("XNtMTSkrA1a7USpLNvN3","Jucati","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("uceTrn1WJE7dthRNJr6z","Jupi","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("g7UcvD9OE8dFVbChY11y","Jurema","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("RVgqXmWQgKEt3JTMNFOH","Lagoa do Carro","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Nx0TSzOCQavNgEVHI1IF","Lagoa do Itaenga","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("TSsBZGhcYoyMCzJCHyhH","Lagoa do Ouro","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("MwaZRFQMLAI95VzRDj0b","Lagoa dos Gatos","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("H1Qna17jzczD18MUgNAt","Lagoa Grande","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("gLaYm0hhQ5KPHyHEAjmb","Lajedo","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("NmKUjAPXhHb6qXagzNaN","Limoeiro","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("HRejO7qHx77lpeeIlMDP","Macaparana","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("GbrIs5yKo0OTtCv3SbcW","Machados","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WK9gKktHQk07DNBYjqtG","Manari","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("hi4fVvAgBgUGr5PbEYqL","Maraial","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("pr2YsTLKqGAfGYEdnczi","Mirandiba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("TcDYfWFBkyc6HXtyKU5v","Moreilândia","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("yzEsyqCxsc3SjLFYDsyB","Moreno","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("auo8SspG1uHUcezKFkzZ","Nazaré da Mata","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("DW3RpLidsInH7yGs5aw4","Olinda","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("r1pdKyeKOzDXiuXyhy3t","Orobó","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("xWSOcHWLS2KhqjC7f4kx","Orocó","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("zByfVGEMtY2fMs4gRSkn","Ouricuri","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("VxDsG4xwECDY08VLXLRU","Palmares","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("WTWLgxFQoajhewBK66yA","Palmeirina","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("FiYaOpisgufDSJP0gieG","Panelas","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("e6uxFLw3O8Jb5H84SfjW","Paranatama","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("v2W2dyfWfFrPJNcSnCgW","Parnamirim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("OA0JOFJBYyPwFZeojYvR","Passira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("6taXvjXkeMgs6AhCRn6e","Paudalho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("xoKzwH5K6UsR04z7ur96","Paulista","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("hiYMQDfAecSQYWCN1FgB","Pedra","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("hQvSgcfpCRaiJpsPUM4V","Pesqueira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("fe0YxwnLeghdbLHG4VvA","Petrolândia","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("HdCKUD9irtcjVOU4bg6Q","Petrolina","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("F4uXSJzxzF4HEkqm5QUk","Poção","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("xsMu0CkZoBs4p6IFPS4n","Pombos","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("EuI7X4dGKpae6lo8pHI5","Primavera","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("JagN1Oom3pCupG0RggZO","Quipapá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Lh9LzLDVSEPbaTMn5IPw","Quixaba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("oELRf77Mxeeu8Og2dxNd","Recife","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("fvzZPSfw0W7GT4GSXZ1r","Riacho das Almas","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("UkcGPuAusjS6KYgUTgc9","Ribeirão","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("BWjeo98Om5ie0vVonMVM","Rio Formoso","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("HJ8vEyxJIvtHLK0QoLFD","Sairé","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("n9D4ZQe4GhCHgW9cjQRt","Salgadinho","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("4y4SNTynmVY8TOWLlJRA","Salgueiro","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("RZgt1ayU8K3BXObnmaSI","Saloá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("rwUvt1jqccihZTvfh9oe","Sanharó","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("ejceDY63QSpGlKO1rKSh","Santa Cruz","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("CKkp5sgrkxpaqd8Nk3uU","Santa Cruz da Baixa Verde","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("27wcj9c5m5hVLjxRsWy6","Santa Cruz do Capibaribe","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("tUhLusRFyaAXXrHBnYmD","Santa Filomena","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("H7AM5GEwO5LOfsWudAo7","Santa Maria da Boa Vista","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("YsMWYGOizf24vjMlrRlg","Santa Maria do Cambucá","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("6sAKh1ehWUieaIzXatEX","Santa Terezinha","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("PTJ1NLuGzisWvSuxYzI8","São Benedito do Sul","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("KhUVAj6zLzFMj7VYtCEa","São Bento do Una","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("JYvhCv8U8asfYeTAHXQY","São Caitano","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("mL7Iga21ejRiWecbMsyl","São João","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("SKDCl2ffeDzrCe4oCxxx","São Joaquim do Monte","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("VanPg4CdDsrg2DJuiLzl","São José da Coroa Grande","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("lGzAK28kDHM5919ezeoC","São José do Belmonte","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("8nu4i86CBGKA5J2J5TzP","São José do Egito","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("RVhBBtEY9V84Uhl6kPtc","São Lourenço da Mata","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("h3khCe5KZzTvYKL6JFcE","São Vicente Ferrer","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("uPCzIJXeyKUIzhpZHJEJ","Serra Talhada","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("n1qCNDirSLe1Cb2S1Ir8","Serrita","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("hCHiRhw8S6T6HIoTi608","Sertânia","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("DGBgHPsuaAnlnWwzsvnJ","Sirinhaém","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("YNPEn99fxOMSt1CJa9Hx","Solidão","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("QkQyeItBqq0AcpeZx29h","Surubim","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("GTW03K4RjyD6rVzEEahY","Tabira","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("vyX0quT4Ztg7jrA0vhre","Tacaimbó","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("y0pWd7S7vPzbZtc6WNop","Tacaratu","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("0Oul8baroDRBzQjFYQEm","Tamandaré","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("gpPuA1PdzOqYmvx9UE3n","Taquaritinga do Norte","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Vr9a8bzML9qhv076F8q4","Terezinha","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("sfscS43NDGLA9Hqoqdlr","Terra Nova","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("e9kfIxDRKydFNNNj94Nw","Timbaúba","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("L3WSPCBPXWXJKUbGxzpV","Toritama","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("mCLYT2vqNBqTwCFnc95w","Tracunhaém","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("vo5Ai66TAy2QybMsgvyq","Trindade","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("H4EbuRWF724PeCttF4El","Triunfo","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("O6aazYGdRpdTQuUD0wJY","Tupanatinga","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("E9zBBJawGbyJ5cDNSrsb","Tuparetama","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("2589pfE6s27gwNNnCJbF","Venturosa","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("giWkm8ynbmt3GwLiZwJQ","Verdejante","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("ecipuZgIG2kkLPm3af9s","Vertente do Lério","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("lL55QXBMp10gasiFGl8J","Vertentes","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("0qJVAwZpSZ75B9zsUmrN","Vicência","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("Ciq3yMSWddytOorUUw6z","Vitória de Santo Antão","YS1okckJJhDXNtmcKS9b", "PE"));
        lista.add(new Cidade("rscW27M04z85U7CcDrSZ","Xexéu","YS1okckJJhDXNtmcKS9b", "PE"));

        return lista;
    }
}
