package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PI {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("AoitetdPpEwWXdM0jozD","Acauã","PI"));
        lista.add(new Cidade("zU7aGGatRVMCcDCDHFdy","Agricolândia","PI"));
        lista.add(new Cidade("aLamTslBglS0P3Ze5hc5","Água Branca","PI"));
        lista.add(new Cidade("sKeWKeMapWO93LE1fGB7","Alagoinha do Piauí","PI"));
        lista.add(new Cidade("6Ys7WETc2zjmwTPbbI28","Alegrete do Piauí","PI"));
        lista.add(new Cidade("SZFzU0AMrWzVXZuyABw7","Alto Longá","PI"));
        lista.add(new Cidade("0DWJBn04m0WiWlNQUqff","Altos","PI"));
        lista.add(new Cidade("UaUd5Wo2Pzk5l44hkk4B","Alvorada do Gurguéia","PI"));
        lista.add(new Cidade("f8meryQVQUCOIOWcW6NC","Amarante","PI"));
        lista.add(new Cidade("bCvVGGQ1w8JkdxqTz4om","Angical do Piauí","PI"));
        lista.add(new Cidade("CACBGYr9MoO6IYBLcdWW","Anísio de Abreu","PI"));
        lista.add(new Cidade("xuGDBNiFP5l2wKEz7VVC","Antônio Almeida","PI"));
        lista.add(new Cidade("I9ZAFQEMA5z85qCzIaGT","Aroazes","PI"));
        lista.add(new Cidade("DuiBCYkaQkQtyD73eQx6","Arraial","PI"));
        lista.add(new Cidade("FhSb0F7pxeurDcbUzNvK","Assunção do Piauí","PI"));
        lista.add(new Cidade("4PTgBS7PX6WY9O3S9dVJ","Avelino Lopes","PI"));
        lista.add(new Cidade("YNDiTVqwCZY6zig5ydvE","Baixa Grande do Ribeiro","PI"));
        lista.add(new Cidade("4UVMxvkziOPXg37vrRg1","Barra d'Alcântara","PI"));
        lista.add(new Cidade("BHtv2KkgbHuZ7gfI2PMG","Barras","PI"));
        lista.add(new Cidade("SLGsUDKpOBTdUd7OV9jV","Barreiras do Piauí","PI"));
        lista.add(new Cidade("HF1kxegWpwTYBJ0rdS1d","Barro Duro","PI"));
        lista.add(new Cidade("gqRIaFMuwtFpVhbsyq7G","Batalha","PI"));
        lista.add(new Cidade("JCpJ3orGmK5WrW7cD1xw","Bela Vista do Piauí","PI"));
        lista.add(new Cidade("nddLiJC1abcqWfUePSZF","Belém do Piauí","PI"));
        lista.add(new Cidade("bJWZnvPzL4Vhxefj3ePi","Beneditinos","PI"));
        lista.add(new Cidade("9UlQxCmgeSEcPj7Fi7PV","Bertolínia","PI"));
        lista.add(new Cidade("toy0iWDSZ33fCG64l2tu","Betânia do Piauí","PI"));
        lista.add(new Cidade("cGYK9YfX3NmMzFWmxJfB","Boa Hora","PI"));
        lista.add(new Cidade("hg2XV0jWDA5kqhfvKkL7","Bocaina","PI"));
        lista.add(new Cidade("6Ec44NqPD6vU1ljJZrGG","Bom Jesus","PI"));
        lista.add(new Cidade("e2mAOnWGx0UcFUPQaheq","Bom Princípio do Piauí","PI"));
        lista.add(new Cidade("1pUmSP1yrlrHp0KBbofP","Bonfim do Piauí","PI"));
        lista.add(new Cidade("azeAYD1FK0wlgz3pHHox","Boqueirão do Piauí","PI"));
        lista.add(new Cidade("cvJ3ckIqVpdTWR9MfIvt","Brasileira","PI"));
        lista.add(new Cidade("XLV7e3oVJ2DLH7nXOMlY","Brejo do Piauí","PI"));
        lista.add(new Cidade("1xsglIgo1XdXTo42Mf36","Buriti dos Lopes","PI"));
        lista.add(new Cidade("RaHTQ1fxQqzUcsEaFuWb","Buriti dos Montes","PI"));
        lista.add(new Cidade("pE7xB7jzePim73S0eC3u","Cabeceiras do Piauí","PI"));
        lista.add(new Cidade("6v5rKkjPEBuPTcUb7jrG","Cajazeiras do Piauí","PI"));
        lista.add(new Cidade("KVRYykDLT0K8OHHUdq7X","Cajueiro da Praia","PI"));
        lista.add(new Cidade("Szn8ZegiBNjrkyziVQpX","Caldeirão Grande do Piauí","PI"));
        lista.add(new Cidade("ZKkWdNiR4UruOLxPDca2","Campinas do Piauí","PI"));
        lista.add(new Cidade("9yBTLqWMQ3AjyLS71KJG","Campo Alegre do Fidalgo","PI"));
        lista.add(new Cidade("dWa4sjPkM0uKfC0CBhmg","Campo Grande do Piauí","PI"));
        lista.add(new Cidade("6bblNfyxDU0CgF4ZJaCN","Campo Largo do Piauí","PI"));
        lista.add(new Cidade("6XdW2jt0ONkDFQ5egw88","Campo Maior","PI"));
        lista.add(new Cidade("gWuN3ivNOXOfe184qGL2","Canavieira","PI"));
        lista.add(new Cidade("iyOv8Qz2VoBc9M64AnRe","Canto do Buriti","PI"));
        lista.add(new Cidade("PuZTSbqAswnt1qzAr7bW","Capitão de Campos","PI"));
        lista.add(new Cidade("syZPjK19vKI6zGa1m2ru","Capitão Gervásio Oliveira","PI"));
        lista.add(new Cidade("1lPPiHFY9Ys230qFOyoV","Caracol","PI"));
        lista.add(new Cidade("65fOknbHbsnyoLxaIqKn","Caraúbas do Piauí","PI"));
        lista.add(new Cidade("9cHxT4Kqnm7YevfUstag","Caridade do Piauí","PI"));
        lista.add(new Cidade("yzdDUjiBdOI0xfgWhMcb","Castelo do Piauí","PI"));
        lista.add(new Cidade("b4mdpfiJzqtcT3ttrA52","Caxingó","PI"));
        lista.add(new Cidade("e4vZ0dIgZe4rEL6zjHzf","Cocal","PI"));
        lista.add(new Cidade("vAWPXDnfuWbLaVWDzopY","Cocal de Telha","PI"));
        lista.add(new Cidade("aMIc58rB2cjlVbReSjkd","Cocal dos Alves","PI"));
        lista.add(new Cidade("sOLnVYIRBmMv5nDf0ABw","Coivaras","PI"));
        lista.add(new Cidade("wYnZTSK7VngV8ZlIYnnZ","Colônia do Gurguéia","PI"));
        lista.add(new Cidade("ln2ourTXQro1Qd3eWgfd","Colônia do Piauí","PI"));
        lista.add(new Cidade("cVzGinEfWVfmb4mmm0CY","Conceição do Canindé","PI"));
        lista.add(new Cidade("hTN7gGtj9ECOKr3wfKeG","Coronel José Dias","PI"));
        lista.add(new Cidade("96qtWzHKHpEfxQDpkFfg","Corrente","PI"));
        lista.add(new Cidade("r8VH2rRcn7uBX6gMTnt5","Cristalândia do Piauí","PI"));
        lista.add(new Cidade("OSgcfHxcatMR9CGSsclv","Cristino Castro","PI"));
        lista.add(new Cidade("CdTPQAgbTRhCevzrtjh2","Curimatá","PI"));
        lista.add(new Cidade("1WqOhvVyWqBHhMdqcaKq","Currais","PI"));
        lista.add(new Cidade("DpiN8KEaqPCiPWpJaHV4","Curral Novo do Piauí","PI"));
        lista.add(new Cidade("n7a5b3CqGd7Hq8wxWprh","Curralinhos","PI"));
        lista.add(new Cidade("E0Ho1q02XrfpOKEUKPY6","Demerval Lobão","PI"));
        lista.add(new Cidade("Ke7O3qp6Ta4wJYUB8rxn","Dirceu Arcoverde","PI"));
        lista.add(new Cidade("HY3wxTPwhm7rajWJQSWf","Dom Expedito Lopes","PI"));
        lista.add(new Cidade("zG3nJR2lyzg5jk62hADf","Dom Inocêncio","PI"));
        lista.add(new Cidade("t0Y6IGbVK7TEwrFWLfdx","Domingos Mourão","PI"));
        lista.add(new Cidade("HMCBbIcOCUdP3Y8gB3w1","Elesbão Veloso","PI"));
        lista.add(new Cidade("S1ksarXDXb2HeR9RmcAr","Eliseu Martins","PI"));
        lista.add(new Cidade("dwYoaje91Lt5mQxzRd2u","Esperantina","PI"));
        lista.add(new Cidade("qwJodihuphzyQMwR8xsI","Fartura do Piauí","PI"));
        lista.add(new Cidade("XPMqTjeB0TAP9NaoW2vo","Flores do Piauí","PI"));
        lista.add(new Cidade("RLmFCuTVETLrwzjuL5Ln","Floresta do Piauí","PI"));
        lista.add(new Cidade("jbJWjQzSxVleLKKfuVtu","Floriano","PI"));
        lista.add(new Cidade("bsgV3HLkayEe8qf1OrZf","Francinópolis","PI"));
        lista.add(new Cidade("GhX0Za1IwqozC6OJdtj8","Francisco Ayres","PI"));
        lista.add(new Cidade("lTHZzPaflMpmJJ1TWO7D","Francisco Macedo","PI"));
        lista.add(new Cidade("g1R7uH3ISEl93I4xYGJK","Francisco Santos","PI"));
        lista.add(new Cidade("7l5eVZs3WmvUJggKoAtY","Fronteiras","PI"));
        lista.add(new Cidade("ZvXLwg9FyZ5xfc8QCiaK","Geminiano","PI"));
        lista.add(new Cidade("fggcL07zFC6UYgti12yE","Gilbués","PI"));
        lista.add(new Cidade("vlYiC2PhsLJ0jSVZwzRA","Guadalupe","PI"));
        lista.add(new Cidade("VFJNf5pSHMRY5bu0FLob","Guaribas","PI"));
        lista.add(new Cidade("GseT69tzCRinPzcUyxgj","Hugo Napoleão","PI"));
        lista.add(new Cidade("VS4nyDvRZaEn3pXRZyEP","Ilha Grande","PI"));
        lista.add(new Cidade("Fl6Uw798Yb2FCvTwoXtD","Inhuma","PI"));
        lista.add(new Cidade("6y4zHG0sci8hLyIHQqxS","Ipiranga do Piauí","PI"));
        lista.add(new Cidade("fZPabwxKS4PgNJv2XqIq","Isaías Coelho","PI"));
        lista.add(new Cidade("EHU5VgineXX8lNeo6t8w","Itainópolis","PI"));
        lista.add(new Cidade("YOD1HIfI1STnG7QYNNAi","Itaueira","PI"));
        lista.add(new Cidade("1WZiqhLR4fSId9lnKZPA","Jacobina do Piauí","PI"));
        lista.add(new Cidade("9AZXIxKXjSFJO1K4IWdf","Jaicós","PI"));
        lista.add(new Cidade("ahAbWOeNN04UtYXoDC4Y","Jardim do Mulato","PI"));
        lista.add(new Cidade("1pRTQNVGCr0H5B3YgUGm","Jatobá do Piauí","PI"));
        lista.add(new Cidade("YdqB6wzh7fmBNEcgg3Hh","Jerumenha","PI"));
        lista.add(new Cidade("PKydcPTIstn6rO0pIRT4","João Costa","PI"));
        lista.add(new Cidade("yG2RAqadXYHcPDDAAcDB","Joaquim Pires","PI"));
        lista.add(new Cidade("gpkDBPxJJGFaifyogmug","Joca Marques","PI"));
        lista.add(new Cidade("ROXqiTpIN1mfJsjBVBLk","José de Freitas","PI"));
        lista.add(new Cidade("hdYRt1D2F4T1HV6zcTvi","Juazeiro do Piauí","PI"));
        lista.add(new Cidade("UwNlX9k7nlT5m0KKsjkm","Júlio Borges","PI"));
        lista.add(new Cidade("pIsUyfIiUGakukRyehoY","Jurema","PI"));
        lista.add(new Cidade("Fo0DZ4bXfHQUgfHO7t0d","Lagoa Alegre","PI"));
        lista.add(new Cidade("YfqlROibXMxIhaelMqIN","Lagoa de São Francisco","PI"));
        lista.add(new Cidade("H7ZZqxsr9NxD7LHCXooV","Lagoa do Barro do Piauí","PI"));
        lista.add(new Cidade("wunk8nKIvYZPVO0jZh9w","Lagoa do Piauí","PI"));
        lista.add(new Cidade("2JjKXsVXFIgPkS5sfRJ9","Lagoa do Sítio","PI"));
        lista.add(new Cidade("ointQ5UNEThlzx9l4bKK","Lagoinha do Piauí","PI"));
        lista.add(new Cidade("xFISUTBQoVetpzklDeOT","Landri Sales","PI"));
        lista.add(new Cidade("o1jvXmGP46lj4CCIslZz","Luís Correia","PI"));
        lista.add(new Cidade("hSxIuDkt0Ma8Uu2EN2PL","Luzilândia","PI"));
        lista.add(new Cidade("nLWS79IlQCqHq13mDCrV","Madeiro","PI"));
        lista.add(new Cidade("cw65Uz2gy6GjOk23C4li","Manoel Emídio","PI"));
        lista.add(new Cidade("NU2zOJDm7b5lO0QZvurV","Marcolândia","PI"));
        lista.add(new Cidade("oIkZ1c5QqwuZPQfFcQN0","Marcos Parente","PI"));
        lista.add(new Cidade("6qbJHmv55zhpGfA4WuRz","Massapê do Piauí","PI"));
        lista.add(new Cidade("jm83qVdXASa58kyEeXvq","Matias Olímpio","PI"));
        lista.add(new Cidade("0tEC18kFVq98FB9Yarxt","Miguel Alves","PI"));
        lista.add(new Cidade("K3dCuaSdRWYhYiHkcVvm","Miguel Leão","PI"));
        lista.add(new Cidade("FJdqyzwzXUj93u8N0W9C","Milton Brandão","PI"));
        lista.add(new Cidade("DJX6boQ74xiBapTxqOIq","Monsenhor Gil","PI"));
        lista.add(new Cidade("lrV0HOOZCeXmHrvT521F","Monsenhor Hipólito","PI"));
        lista.add(new Cidade("kQrXlIBmu7lm9226XssC","Monte Alegre do Piauí","PI"));
        lista.add(new Cidade("KOYHqzLTft7qIMD1PhPv","Morro Cabeça no Tempo","PI"));
        lista.add(new Cidade("MDWspnOSOyezER3SFTTe","Morro do Chapéu do Piauí","PI"));
        lista.add(new Cidade("dtea1YhSF2CbzfOz1RbK","Murici dos Portelas","PI"));
        lista.add(new Cidade("ks7rmA89MXuGBsr6A1jW","Nazaré do Piauí","PI"));
        lista.add(new Cidade("8WxOYrrkdjaY6Ow1QVaL","Nossa Senhora de Nazaré","PI"));
        lista.add(new Cidade("m2FGAZaeNC0ek50I0hK4","Nossa Senhora dos Remédios","PI"));
        lista.add(new Cidade("NIRir29ikE5WJ9qSDD3n","Nova Santa Rita","PI"));
        lista.add(new Cidade("aHn4WpJyMgEkgLIHGwXf","Novo Oriente do Piauí","PI"));
        lista.add(new Cidade("TmvALUKpmFNNqekRQ7M0","Novo Santo Antônio","PI"));
        lista.add(new Cidade("cdX1yeGhij7tRh87Ko4G","Oeiras","PI"));
        lista.add(new Cidade("MukpNU2NmQXZDEw0f59p","Olho d'Água do Piauí","PI"));
        lista.add(new Cidade("UFx863CfSNT6HXEbsc8d","Padre Marcos","PI"));
        lista.add(new Cidade("xwbTSLYBrIFwqJA612Ey","Paes Landim","PI"));
        lista.add(new Cidade("0f3BR65tuLnUTlSmkFDd","Pajeú do Piauí","PI"));
        lista.add(new Cidade("ahmshAxosUrGGkG7rh3n","Palmeira do Piauí","PI"));
        lista.add(new Cidade("XbkLHsKMONYOWDVPVA10","Palmeirais","PI"));
        lista.add(new Cidade("F3Jvz2PFHOnPAKlt05sS","Paquetá","PI"));
        lista.add(new Cidade("c9CngkmJqyHcIvObEt4e","Parnaguá","PI"));
        lista.add(new Cidade("OjWVHhyNM78yxS5SEaJe","Parnaíba","PI"));
        lista.add(new Cidade("84TN1oYcBPjJz4q7tt2A","Passagem Franca do Piauí","PI"));
        lista.add(new Cidade("5C1jkluWMcju4sHTEgvU","Patos do Piauí","PI"));
        lista.add(new Cidade("zqidExXhYeQxUalRAKcd","Pau d'Arco do Piauí","PI"));
        lista.add(new Cidade("WZ2J6qQ3VrcOaocuFphN","Paulistana","PI"));
        lista.add(new Cidade("6MLfRO8uU1u8KhPtqa9C","Pavussu","PI"));
        lista.add(new Cidade("TNP4ecw6FeoT8y1TkrIi","Pedro II","PI"));
        lista.add(new Cidade("Ypnh5o0sSutZM9PZhS12","Pedro Laurentino","PI"));
        lista.add(new Cidade("ycNFwNTM5TX4XLdT3mfp","Picos","PI"));
        lista.add(new Cidade("ePxTcNcL51ZBE6u3MZse","Pimenteiras","PI"));
        lista.add(new Cidade("WcmIG1Wp0yenBchV8ZmD","Pio IX","PI"));
        lista.add(new Cidade("1WxUHZ5TIT4GNFmTWwV4","Piracuruca","PI"));
        lista.add(new Cidade("ehzkdKZ2DsqlnbcR7l90","Piripiri","PI"));
        lista.add(new Cidade("iQoocy3moqPDlL5bdPqr","Porto","PI"));
        lista.add(new Cidade("77qc0G6HWg4mT8Tfk9xd","Porto Alegre do Piauí","PI"));
        lista.add(new Cidade("MRzfYMmeiLwXx0W7lumS","Prata do Piauí","PI"));
        lista.add(new Cidade("3wLgjbuZHNm0bvqh57pY","Queimada Nova","PI"));
        lista.add(new Cidade("9SdbJDAixMvEq6SXHaBD","Redenção do Gurguéia","PI"));
        lista.add(new Cidade("R3YFZtu2wlczpPludSLt","Regeneração","PI"));
        lista.add(new Cidade("du0aFD5r6aNgjRiA2SdN","Riacho Frio","PI"));
        lista.add(new Cidade("jYdQwNnpYMX4TXD4aBeX","Ribeira do Piauí","PI"));
        lista.add(new Cidade("1Z9XaVIfknIq6apnZD4l","Ribeiro Gonçalves","PI"));
        lista.add(new Cidade("guKXAoeCJixutabzoSNQ","Rio Grande do Piauí","PI"));
        lista.add(new Cidade("pfZ8UdqQLUngCsnctLPZ","Santa Cruz do Piauí","PI"));
        lista.add(new Cidade("Tbv8LeddO6RVie05DiKZ","Santa Cruz dos Milagres","PI"));
        lista.add(new Cidade("rQWVPIa9zpTmk9ZnLXe2","Santa Filomena","PI"));
        lista.add(new Cidade("qlgaLBjgXgnU8reue1nV","Santa Luz","PI"));
        lista.add(new Cidade("PKWuUb3ZSD0Lu5xUVS3T","Santa Rosa do Piauí","PI"));
        lista.add(new Cidade("AJqrzzSsOqoVTaIghUsa","Santana do Piauí","PI"));
        lista.add(new Cidade("ZtdTtUF4ZyLPAdbwE5mT","Santo Antônio de Lisboa","PI"));
        lista.add(new Cidade("ZF6vYICUTfNUeeD9ZJVa","Santo Antônio dos Milagres","PI"));
        lista.add(new Cidade("dquDxl2vy2dm4SMEtZRo","Santo Inácio do Piauí","PI"));
        lista.add(new Cidade("zW1FjyouEfUFsCq8N706","São Braz do Piauí","PI"));
        lista.add(new Cidade("czCYrxGdF47lfMCszc6u","São Félix do Piauí","PI"));
        lista.add(new Cidade("WFBN2xC2vRHS2evKcba6","São Francisco de Assis do Piauí","PI"));
        lista.add(new Cidade("zjzpXr0aITaEpSFnVf1J","São Francisco do Piauí","PI"));
        lista.add(new Cidade("57dRUntTR7wSh4QeXX77","São Gonçalo do Gurguéia","PI"));
        lista.add(new Cidade("Ll9Oiapfa2XYhzRsTEL8","São Gonçalo do Piauí","PI"));
        lista.add(new Cidade("x7ArWehNZM2OjArbUbcc","São João da Canabrava","PI"));
        lista.add(new Cidade("wIXSYtXjfHVSgVu3oefi","São João da Fronteira","PI"));
        lista.add(new Cidade("AX4HUVXZXeJMT7gVyZrk","São João da Serra","PI"));
        lista.add(new Cidade("ZeQoKU36NUgcfLqtNzdP","São João da Varjota","PI"));
        lista.add(new Cidade("sJ1ddpqdlmqcEUH3hwUw","São João do Arraial","PI"));
        lista.add(new Cidade("dLrwQu0kjGMJbULVWlun","São João do Piauí","PI"));
        lista.add(new Cidade("ppsLsDdofHLPckuFdTPb","São José do Divino","PI"));
        lista.add(new Cidade("N8ru5ASC5y3UObfVUSE2","São José do Peixe","PI"));
        lista.add(new Cidade("Ou4vJNkrcGU4Yk2YkrQs","São José do Piauí","PI"));
        lista.add(new Cidade("lJgJ4RJa0WOPgqVquiGI","São Julião","PI"));
        lista.add(new Cidade("upj5FjcO9X5TAc9IxCTN","São Lourenço do Piauí","PI"));
        lista.add(new Cidade("4HVmuL5W4iSVXL80Ze2L","São Luis do Piauí","PI"));
        lista.add(new Cidade("VgsJQNYK4iKD4Yo1oHuf","São Miguel da Baixa Grande","PI"));
        lista.add(new Cidade("Ogphqy5PITLY6o7KRQjN","São Miguel do Fidalgo","PI"));
        lista.add(new Cidade("rNRGSX9Tcl4rayGxTNCu","São Miguel do Tapuio","PI"));
        lista.add(new Cidade("jQyKUjTkuKDqcWW4tGGq","São Pedro do Piauí","PI"));
        lista.add(new Cidade("dagANy6emQONXgd34Yk3","São Raimundo Nonato","PI"));
        lista.add(new Cidade("2YUjLeBbRjutnc8iXrh8","Sebastião Barros","PI"));
        lista.add(new Cidade("ejuEuYqdETwKJL2bEVIv","Sebastião Leal","PI"));
        lista.add(new Cidade("L6kRZFUqmYwboauJrXqL","Sigefredo Pacheco","PI"));
        lista.add(new Cidade("mAXxhgWr0tgBE1XB6mSm","Simões","PI"));
        lista.add(new Cidade("LkmUynXUanEhGB1j0VTk","Simplício Mendes","PI"));
        lista.add(new Cidade("XUKGlBitcnxxRhLGDd07","Socorro do Piauí","PI"));
        lista.add(new Cidade("EaRvARvXrKI49VdyXZ1F","Sussuapara","PI"));
        lista.add(new Cidade("xQBCITsShzyHdvQWOLgr","Tamboril do Piauí","PI"));
        lista.add(new Cidade("T7ANu5aUkAHCWm65lpiu","Tanque do Piauí","PI"));
        lista.add(new Cidade("pabQNSDUKn8QKPLcualc","Teresina","PI"));
        lista.add(new Cidade("vcWzH6dR1U5tlCVTtSCG","União","PI"));
        lista.add(new Cidade("HOJZYd1yelKFLxDaC465","Uruçuí","PI"));
        lista.add(new Cidade("j0My24AwjusgfG7K0y1X","Valença do Piauí","PI"));
        lista.add(new Cidade("skhjd5xxZ4cNkBiU5PvC","Várzea Branca","PI"));
        lista.add(new Cidade("IwxjGVitcEa30rQ98HoT","Várzea Grande","PI"));
        lista.add(new Cidade("CIJL997naukLK7ztPUvG","Vera Mendes","PI"));
        lista.add(new Cidade("pDPR6RhpIWVN1vxTKYQ4","Vila Nova do Piauí","PI"));
        lista.add(new Cidade("NUd9pDQbLkuRSCbMe8yf","Wall Ferraz","PI"));

        return lista;
    }
}
