package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PI {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("", "Acauã", "PI"));
        lista.add(new Cidade("", "Agricolândia", "PI"));
        lista.add(new Cidade("", "Água Branca", "PI"));
        lista.add(new Cidade("", "Alagoinha do Piauí", "PI"));
        lista.add(new Cidade("", "Alegrete do Piauí", "PI"));
        lista.add(new Cidade("", "Alto Longá", "PI"));
        lista.add(new Cidade("", "Altos", "PI"));
        lista.add(new Cidade("", "Alvorada do Gurguéia", "PI"));
        lista.add(new Cidade("", "Amarante", "PI"));
        lista.add(new Cidade("", "Angical do Piauí", "PI"));
        lista.add(new Cidade("", "Anísio de Abreu", "PI"));
        lista.add(new Cidade("", "Antônio Almeida", "PI"));
        lista.add(new Cidade("", "Aroazes", "PI"));
        lista.add(new Cidade("", "Arraial", "PI"));
        lista.add(new Cidade("", "Assunção do Piauí", "PI"));
        lista.add(new Cidade("", "Avelino Lopes", "PI"));
        lista.add(new Cidade("", "Baixa Grande do Ribeiro", "PI"));
        lista.add(new Cidade("", "Barra d'Alcântara", "PI"));
        lista.add(new Cidade("", "Barras", "PI"));
        lista.add(new Cidade("", "Barreiras do Piauí", "PI"));
        lista.add(new Cidade("", "Barro Duro", "PI"));
        lista.add(new Cidade("", "Batalha", "PI"));
        lista.add(new Cidade("", "Bela Vista do Piauí", "PI"));
        lista.add(new Cidade("", "Belém do Piauí", "PI"));
        lista.add(new Cidade("", "Beneditinos", "PI"));
        lista.add(new Cidade("", "Bertolínia", "PI"));
        lista.add(new Cidade("", "Betânia do Piauí", "PI"));
        lista.add(new Cidade("", "Boa Hora", "PI"));
        lista.add(new Cidade("", "Bocaina", "PI"));
        lista.add(new Cidade("", "Bom Jesus", "PI"));
        lista.add(new Cidade("", "Bom Princípio do Piauí", "PI"));
        lista.add(new Cidade("", "Bonfim do Piauí", "PI"));
        lista.add(new Cidade("", "Boqueirão do Piauí", "PI"));
        lista.add(new Cidade("", "Brasileira", "PI"));
        lista.add(new Cidade("", "Brejo do Piauí", "PI"));
        lista.add(new Cidade("", "Buriti dos Lopes", "PI"));
        lista.add(new Cidade("", "Buriti dos Montes", "PI"));
        lista.add(new Cidade("", "Cabeceiras do Piauí", "PI"));
        lista.add(new Cidade("", "Cajazeiras do Piauí", "PI"));
        lista.add(new Cidade("", "Cajueiro da Praia", "PI"));
        lista.add(new Cidade("", "Caldeirão Grande do Piauí", "PI"));
        lista.add(new Cidade("", "Campinas do Piauí", "PI"));
        lista.add(new Cidade("", "Campo Alegre do Fidalgo", "PI"));
        lista.add(new Cidade("", "Campo Grande do Piauí", "PI"));
        lista.add(new Cidade("", "Campo Largo do Piauí", "PI"));
        lista.add(new Cidade("", "Campo Maior", "PI"));
        lista.add(new Cidade("", "Canavieira", "PI"));
        lista.add(new Cidade("", "Canto do Buriti", "PI"));
        lista.add(new Cidade("", "Capitão de Campos", "PI"));
        lista.add(new Cidade("", "Capitão Gervásio Oliveira", "PI"));
        lista.add(new Cidade("", "Caracol", "PI"));
        lista.add(new Cidade("", "Caraúbas do Piauí", "PI"));
        lista.add(new Cidade("", "Caridade do Piauí", "PI"));
        lista.add(new Cidade("", "Castelo do Piauí", "PI"));
        lista.add(new Cidade("", "Caxingó", "PI"));
        lista.add(new Cidade("", "Cocal", "PI"));
        lista.add(new Cidade("", "Cocal de Telha", "PI"));
        lista.add(new Cidade("", "Cocal dos Alves", "PI"));
        lista.add(new Cidade("", "Coivaras", "PI"));
        lista.add(new Cidade("", "Colônia do Gurguéia", "PI"));
        lista.add(new Cidade("", "Colônia do Piauí", "PI"));
        lista.add(new Cidade("", "Conceição do Canindé", "PI"));
        lista.add(new Cidade("", "Coronel José Dias", "PI"));
        lista.add(new Cidade("", "Corrente", "PI"));
        lista.add(new Cidade("", "Cristalândia do Piauí", "PI"));
        lista.add(new Cidade("", "Cristino Castro", "PI"));
        lista.add(new Cidade("", "Curimatá", "PI"));
        lista.add(new Cidade("", "Currais", "PI"));
        lista.add(new Cidade("", "Curral Novo do Piauí", "PI"));
        lista.add(new Cidade("", "Curralinhos", "PI"));
        lista.add(new Cidade("", "Demerval Lobão", "PI"));
        lista.add(new Cidade("", "Dirceu Arcoverde", "PI"));
        lista.add(new Cidade("", "Dom Expedito Lopes", "PI"));
        lista.add(new Cidade("", "Dom Inocêncio", "PI"));
        lista.add(new Cidade("", "Domingos Mourão", "PI"));
        lista.add(new Cidade("", "Elesbão Veloso", "PI"));
        lista.add(new Cidade("", "Eliseu Martins", "PI"));
        lista.add(new Cidade("", "Esperantina", "PI"));
        lista.add(new Cidade("", "Fartura do Piauí", "PI"));
        lista.add(new Cidade("", "Flores do Piauí", "PI"));
        lista.add(new Cidade("", "Floresta do Piauí", "PI"));
        lista.add(new Cidade("", "Floriano", "PI"));
        lista.add(new Cidade("", "Francinópolis", "PI"));
        lista.add(new Cidade("", "Francisco Ayres", "PI"));
        lista.add(new Cidade("", "Francisco Macedo", "PI"));
        lista.add(new Cidade("", "Francisco Santos", "PI"));
        lista.add(new Cidade("", "Fronteiras", "PI"));
        lista.add(new Cidade("", "Geminiano", "PI"));
        lista.add(new Cidade("", "Gilbués", "PI"));
        lista.add(new Cidade("", "Guadalupe", "PI"));
        lista.add(new Cidade("", "Guaribas", "PI"));
        lista.add(new Cidade("", "Hugo Napoleão", "PI"));
        lista.add(new Cidade("", "Ilha Grande", "PI"));
        lista.add(new Cidade("", "Inhuma", "PI"));
        lista.add(new Cidade("", "Ipiranga do Piauí", "PI"));
        lista.add(new Cidade("", "Isaías Coelho", "PI"));
        lista.add(new Cidade("", "Itainópolis", "PI"));
        lista.add(new Cidade("", "Itaueira", "PI"));
        lista.add(new Cidade("", "Jacobina do Piauí", "PI"));
        lista.add(new Cidade("", "Jaicós", "PI"));
        lista.add(new Cidade("", "Jardim do Mulato", "PI"));
        lista.add(new Cidade("", "Jatobá do Piauí", "PI"));
        lista.add(new Cidade("", "Jerumenha", "PI"));
        lista.add(new Cidade("", "João Costa", "PI"));
        lista.add(new Cidade("", "Joaquim Pires", "PI"));
        lista.add(new Cidade("", "Joca Marques", "PI"));
        lista.add(new Cidade("", "José de Freitas", "PI"));
        lista.add(new Cidade("", "Juazeiro do Piauí", "PI"));
        lista.add(new Cidade("", "Júlio Borges", "PI"));
        lista.add(new Cidade("", "Jurema", "PI"));
        lista.add(new Cidade("", "Lagoa Alegre", "PI"));
        lista.add(new Cidade("", "Lagoa de São Francisco", "PI"));
        lista.add(new Cidade("", "Lagoa do Barro do Piauí", "PI"));
        lista.add(new Cidade("", "Lagoa do Piauí", "PI"));
        lista.add(new Cidade("", "Lagoa do Sítio", "PI"));
        lista.add(new Cidade("", "Lagoinha do Piauí", "PI"));
        lista.add(new Cidade("", "Landri Sales", "PI"));
        lista.add(new Cidade("", "Luís Correia", "PI"));
        lista.add(new Cidade("", "Luzilândia", "PI"));
        lista.add(new Cidade("", "Madeiro", "PI"));
        lista.add(new Cidade("", "Manoel Emídio", "PI"));
        lista.add(new Cidade("", "Marcolândia", "PI"));
        lista.add(new Cidade("", "Marcos Parente", "PI"));
        lista.add(new Cidade("", "Massapê do Piauí", "PI"));
        lista.add(new Cidade("", "Matias Olímpio", "PI"));
        lista.add(new Cidade("", "Miguel Alves", "PI"));
        lista.add(new Cidade("", "Miguel Leão", "PI"));
        lista.add(new Cidade("", "Milton Brandão", "PI"));
        lista.add(new Cidade("", "Monsenhor Gil", "PI"));
        lista.add(new Cidade("", "Monsenhor Hipólito", "PI"));
        lista.add(new Cidade("", "Monte Alegre do Piauí", "PI"));
        lista.add(new Cidade("", "Morro Cabeça no Tempo", "PI"));
        lista.add(new Cidade("", "Morro do Chapéu do Piauí", "PI"));
        lista.add(new Cidade("", "Murici dos Portelas", "PI"));
        lista.add(new Cidade("", "Nazaré do Piauí", "PI"));
        lista.add(new Cidade("", "Nossa Senhora de Nazaré", "PI"));
        lista.add(new Cidade("", "Nossa Senhora dos Remédios", "PI"));
        lista.add(new Cidade("", "Nova Santa Rita", "PI"));
        lista.add(new Cidade("", "Novo Oriente do Piauí", "PI"));
        lista.add(new Cidade("", "Novo Santo Antônio", "PI"));
        lista.add(new Cidade("", "Oeiras", "PI"));
        lista.add(new Cidade("", "Olho d'Água do Piauí", "PI"));
        lista.add(new Cidade("", "Padre Marcos", "PI"));
        lista.add(new Cidade("", "Paes Landim", "PI"));
        lista.add(new Cidade("", "Pajeú do Piauí", "PI"));
        lista.add(new Cidade("", "Palmeira do Piauí", "PI"));
        lista.add(new Cidade("", "Palmeirais", "PI"));
        lista.add(new Cidade("", "Paquetá", "PI"));
        lista.add(new Cidade("", "Parnaguá", "PI"));
        lista.add(new Cidade("", "Parnaíba", "PI"));
        lista.add(new Cidade("", "Passagem Franca do Piauí", "PI"));
        lista.add(new Cidade("", "Patos do Piauí", "PI"));
        lista.add(new Cidade("", "Pau d'Arco do Piauí", "PI"));
        lista.add(new Cidade("", "Paulistana", "PI"));
        lista.add(new Cidade("", "Pavussu", "PI"));
        lista.add(new Cidade("", "Pedro II", "PI"));
        lista.add(new Cidade("", "Pedro Laurentino", "PI"));
        lista.add(new Cidade("", "Picos", "PI"));
        lista.add(new Cidade("", "Pimenteiras", "PI"));
        lista.add(new Cidade("", "Pio IX", "PI"));
        lista.add(new Cidade("", "Piracuruca", "PI"));
        lista.add(new Cidade("", "Piripiri", "PI"));
        lista.add(new Cidade("", "Porto", "PI"));
        lista.add(new Cidade("", "Porto Alegre do Piauí", "PI"));
        lista.add(new Cidade("", "Prata do Piauí", "PI"));
        lista.add(new Cidade("", "Queimada Nova", "PI"));
        lista.add(new Cidade("", "Redenção do Gurguéia", "PI"));
        lista.add(new Cidade("", "Regeneração", "PI"));
        lista.add(new Cidade("", "Riacho Frio", "PI"));
        lista.add(new Cidade("", "Ribeira do Piauí", "PI"));
        lista.add(new Cidade("", "Ribeiro Gonçalves", "PI"));
        lista.add(new Cidade("", "Rio Grande do Piauí", "PI"));
        lista.add(new Cidade("", "Santa Cruz do Piauí", "PI"));
        lista.add(new Cidade("", "Santa Cruz dos Milagres", "PI"));
        lista.add(new Cidade("", "Santa Filomena", "PI"));
        lista.add(new Cidade("", "Santa Luz", "PI"));
        lista.add(new Cidade("", "Santa Rosa do Piauí", "PI"));
        lista.add(new Cidade("", "Santana do Piauí", "PI"));
        lista.add(new Cidade("", "Santo Antônio de Lisboa", "PI"));
        lista.add(new Cidade("", "Santo Antônio dos Milagres", "PI"));
        lista.add(new Cidade("", "Santo Inácio do Piauí", "PI"));
        lista.add(new Cidade("", "São Braz do Piauí", "PI"));
        lista.add(new Cidade("", "São Félix do Piauí", "PI"));
        lista.add(new Cidade("", "São Francisco de Assis do Piauí", "PI"));
        lista.add(new Cidade("", "São Francisco do Piauí", "PI"));
        lista.add(new Cidade("", "São Gonçalo do Gurguéia", "PI"));
        lista.add(new Cidade("", "São Gonçalo do Piauí", "PI"));
        lista.add(new Cidade("", "São João da Canabrava", "PI"));
        lista.add(new Cidade("", "São João da Fronteira", "PI"));
        lista.add(new Cidade("", "São João da Serra", "PI"));
        lista.add(new Cidade("", "São João da Varjota", "PI"));
        lista.add(new Cidade("", "São João do Arraial", "PI"));
        lista.add(new Cidade("", "São João do Piauí", "PI"));
        lista.add(new Cidade("", "São José do Divino", "PI"));
        lista.add(new Cidade("", "São José do Peixe", "PI"));
        lista.add(new Cidade("", "São José do Piauí", "PI"));
        lista.add(new Cidade("", "São Julião", "PI"));
        lista.add(new Cidade("", "São Lourenço do Piauí", "PI"));
        lista.add(new Cidade("", "São Luis do Piauí", "PI"));
        lista.add(new Cidade("", "São Miguel da Baixa Grande", "PI"));
        lista.add(new Cidade("", "São Miguel do Fidalgo", "PI"));
        lista.add(new Cidade("", "São Miguel do Tapuio", "PI"));
        lista.add(new Cidade("", "São Pedro do Piauí", "PI"));
        lista.add(new Cidade("", "São Raimundo Nonato", "PI"));
        lista.add(new Cidade("", "Sebastião Barros", "PI"));
        lista.add(new Cidade("", "Sebastião Leal", "PI"));
        lista.add(new Cidade("", "Sigefredo Pacheco", "PI"));
        lista.add(new Cidade("", "Simões", "PI"));
        lista.add(new Cidade("", "Simplício Mendes", "PI"));
        lista.add(new Cidade("", "Socorro do Piauí", "PI"));
        lista.add(new Cidade("", "Sussuapara", "PI"));
        lista.add(new Cidade("", "Tamboril do Piauí", "PI"));
        lista.add(new Cidade("", "Tanque do Piauí", "PI"));
        lista.add(new Cidade("", "Teresina", "PI"));
        lista.add(new Cidade("", "União", "PI"));
        lista.add(new Cidade("", "Uruçuí", "PI"));
        lista.add(new Cidade("", "Valença do Piauí", "PI"));
        lista.add(new Cidade("", "Várzea Branca", "PI"));
        lista.add(new Cidade("", "Várzea Grande", "PI"));
        lista.add(new Cidade("", "Vera Mendes", "PI"));
        lista.add(new Cidade("", "Vila Nova do Piauí", "PI"));
        lista.add(new Cidade("", "Wall Ferraz", "PI"));

        return lista;
    }
}
