package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PI {
    public static ArrayList<Cidade> getCidades() {
        ArrayList<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("AoitetdPpEwWXdM0jozD","Acauã","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("zU7aGGatRVMCcDCDHFdy","Agricolândia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("aLamTslBglS0P3Ze5hc5","Água Branca","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("sKeWKeMapWO93LE1fGB7","Alagoinha do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6Ys7WETc2zjmwTPbbI28","Alegrete do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("SZFzU0AMrWzVXZuyABw7","Alto Longá","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("0DWJBn04m0WiWlNQUqff","Altos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("UaUd5Wo2Pzk5l44hkk4B","Alvorada do Gurguéia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("f8meryQVQUCOIOWcW6NC","Amarante","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("bCvVGGQ1w8JkdxqTz4om","Angical do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("CACBGYr9MoO6IYBLcdWW","Anísio de Abreu","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("xuGDBNiFP5l2wKEz7VVC","Antônio Almeida","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("I9ZAFQEMA5z85qCzIaGT","Aroazes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("DuiBCYkaQkQtyD73eQx6","Arraial","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("FhSb0F7pxeurDcbUzNvK","Assunção do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("4PTgBS7PX6WY9O3S9dVJ","Avelino Lopes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("YNDiTVqwCZY6zig5ydvE","Baixa Grande do Ribeiro","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("4UVMxvkziOPXg37vrRg1","Barra d'Alcântara","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("BHtv2KkgbHuZ7gfI2PMG","Barras","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("SLGsUDKpOBTdUd7OV9jV","Barreiras do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("HF1kxegWpwTYBJ0rdS1d","Barro Duro","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("gqRIaFMuwtFpVhbsyq7G","Batalha","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("JCpJ3orGmK5WrW7cD1xw","Bela Vista do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("nddLiJC1abcqWfUePSZF","Belém do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("bJWZnvPzL4Vhxefj3ePi","Beneditinos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("9UlQxCmgeSEcPj7Fi7PV","Bertolínia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("toy0iWDSZ33fCG64l2tu","Betânia do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("cGYK9YfX3NmMzFWmxJfB","Boa Hora","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("hg2XV0jWDA5kqhfvKkL7","Bocaina","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6Ec44NqPD6vU1ljJZrGG","Bom Jesus","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("e2mAOnWGx0UcFUPQaheq","Bom Princípio do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1pUmSP1yrlrHp0KBbofP","Bonfim do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("azeAYD1FK0wlgz3pHHox","Boqueirão do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("cvJ3ckIqVpdTWR9MfIvt","Brasileira","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("XLV7e3oVJ2DLH7nXOMlY","Brejo do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1xsglIgo1XdXTo42Mf36","Buriti dos Lopes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("RaHTQ1fxQqzUcsEaFuWb","Buriti dos Montes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("pE7xB7jzePim73S0eC3u","Cabeceiras do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6v5rKkjPEBuPTcUb7jrG","Cajazeiras do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("KVRYykDLT0K8OHHUdq7X","Cajueiro da Praia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Szn8ZegiBNjrkyziVQpX","Caldeirão Grande do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ZKkWdNiR4UruOLxPDca2","Campinas do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("9yBTLqWMQ3AjyLS71KJG","Campo Alegre do Fidalgo","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("dWa4sjPkM0uKfC0CBhmg","Campo Grande do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6bblNfyxDU0CgF4ZJaCN","Campo Largo do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6XdW2jt0ONkDFQ5egw88","Campo Maior","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("gWuN3ivNOXOfe184qGL2","Canavieira","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("iyOv8Qz2VoBc9M64AnRe","Canto do Buriti","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("PuZTSbqAswnt1qzAr7bW","Capitão de Campos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("syZPjK19vKI6zGa1m2ru","Capitão Gervásio Oliveira","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1lPPiHFY9Ys230qFOyoV","Caracol","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("65fOknbHbsnyoLxaIqKn","Caraúbas do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("9cHxT4Kqnm7YevfUstag","Caridade do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("yzdDUjiBdOI0xfgWhMcb","Castelo do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("b4mdpfiJzqtcT3ttrA52","Caxingó","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("e4vZ0dIgZe4rEL6zjHzf","Cocal","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("vAWPXDnfuWbLaVWDzopY","Cocal de Telha","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("aMIc58rB2cjlVbReSjkd","Cocal dos Alves","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("sOLnVYIRBmMv5nDf0ABw","Coivaras","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("wYnZTSK7VngV8ZlIYnnZ","Colônia do Gurguéia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ln2ourTXQro1Qd3eWgfd","Colônia do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("cVzGinEfWVfmb4mmm0CY","Conceição do Canindé","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("hTN7gGtj9ECOKr3wfKeG","Coronel José Dias","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("96qtWzHKHpEfxQDpkFfg","Corrente","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("r8VH2rRcn7uBX6gMTnt5","Cristalândia do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("OSgcfHxcatMR9CGSsclv","Cristino Castro","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("CdTPQAgbTRhCevzrtjh2","Curimatá","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1WqOhvVyWqBHhMdqcaKq","Currais","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("DpiN8KEaqPCiPWpJaHV4","Curral Novo do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("n7a5b3CqGd7Hq8wxWprh","Curralinhos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("E0Ho1q02XrfpOKEUKPY6","Demerval Lobão","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Ke7O3qp6Ta4wJYUB8rxn","Dirceu Arcoverde","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("HY3wxTPwhm7rajWJQSWf","Dom Expedito Lopes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("zG3nJR2lyzg5jk62hADf","Dom Inocêncio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("t0Y6IGbVK7TEwrFWLfdx","Domingos Mourão","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("HMCBbIcOCUdP3Y8gB3w1","Elesbão Veloso","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("S1ksarXDXb2HeR9RmcAr","Eliseu Martins","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("dwYoaje91Lt5mQxzRd2u","Esperantina","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("qwJodihuphzyQMwR8xsI","Fartura do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("XPMqTjeB0TAP9NaoW2vo","Flores do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("RLmFCuTVETLrwzjuL5Ln","Floresta do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("jbJWjQzSxVleLKKfuVtu","Floriano","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("bsgV3HLkayEe8qf1OrZf","Francinópolis","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("GhX0Za1IwqozC6OJdtj8","Francisco Ayres","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("lTHZzPaflMpmJJ1TWO7D","Francisco Macedo","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("g1R7uH3ISEl93I4xYGJK","Francisco Santos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("7l5eVZs3WmvUJggKoAtY","Fronteiras","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ZvXLwg9FyZ5xfc8QCiaK","Geminiano","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("fggcL07zFC6UYgti12yE","Gilbués","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("vlYiC2PhsLJ0jSVZwzRA","Guadalupe","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("VFJNf5pSHMRY5bu0FLob","Guaribas","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("GseT69tzCRinPzcUyxgj","Hugo Napoleão","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("VS4nyDvRZaEn3pXRZyEP","Ilha Grande","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Fl6Uw798Yb2FCvTwoXtD","Inhuma","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6y4zHG0sci8hLyIHQqxS","Ipiranga do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("fZPabwxKS4PgNJv2XqIq","Isaías Coelho","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("EHU5VgineXX8lNeo6t8w","Itainópolis","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("YOD1HIfI1STnG7QYNNAi","Itaueira","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1WZiqhLR4fSId9lnKZPA","Jacobina do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("9AZXIxKXjSFJO1K4IWdf","Jaicós","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ahAbWOeNN04UtYXoDC4Y","Jardim do Mulato","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1pRTQNVGCr0H5B3YgUGm","Jatobá do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("YdqB6wzh7fmBNEcgg3Hh","Jerumenha","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("PKydcPTIstn6rO0pIRT4","João Costa","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("yG2RAqadXYHcPDDAAcDB","Joaquim Pires","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("gpkDBPxJJGFaifyogmug","Joca Marques","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ROXqiTpIN1mfJsjBVBLk","José de Freitas","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("hdYRt1D2F4T1HV6zcTvi","Juazeiro do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("UwNlX9k7nlT5m0KKsjkm","Júlio Borges","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("pIsUyfIiUGakukRyehoY","Jurema","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Fo0DZ4bXfHQUgfHO7t0d","Lagoa Alegre","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("YfqlROibXMxIhaelMqIN","Lagoa de São Francisco","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("H7ZZqxsr9NxD7LHCXooV","Lagoa do Barro do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("wunk8nKIvYZPVO0jZh9w","Lagoa do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("2JjKXsVXFIgPkS5sfRJ9","Lagoa do Sítio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ointQ5UNEThlzx9l4bKK","Lagoinha do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("xFISUTBQoVetpzklDeOT","Landri Sales","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("o1jvXmGP46lj4CCIslZz","Luís Correia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("hSxIuDkt0Ma8Uu2EN2PL","Luzilândia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("nLWS79IlQCqHq13mDCrV","Madeiro","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("cw65Uz2gy6GjOk23C4li","Manoel Emídio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("NU2zOJDm7b5lO0QZvurV","Marcolândia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("oIkZ1c5QqwuZPQfFcQN0","Marcos Parente","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6qbJHmv55zhpGfA4WuRz","Massapê do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("jm83qVdXASa58kyEeXvq","Matias Olímpio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("0tEC18kFVq98FB9Yarxt","Miguel Alves","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("K3dCuaSdRWYhYiHkcVvm","Miguel Leão","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("FJdqyzwzXUj93u8N0W9C","Milton Brandão","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("DJX6boQ74xiBapTxqOIq","Monsenhor Gil","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("lrV0HOOZCeXmHrvT521F","Monsenhor Hipólito","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("kQrXlIBmu7lm9226XssC","Monte Alegre do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("KOYHqzLTft7qIMD1PhPv","Morro Cabeça no Tempo","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("MDWspnOSOyezER3SFTTe","Morro do Chapéu do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("dtea1YhSF2CbzfOz1RbK","Murici dos Portelas","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ks7rmA89MXuGBsr6A1jW","Nazaré do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("8WxOYrrkdjaY6Ow1QVaL","Nossa Senhora de Nazaré","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("m2FGAZaeNC0ek50I0hK4","Nossa Senhora dos Remédios","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("NIRir29ikE5WJ9qSDD3n","Nova Santa Rita","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("aHn4WpJyMgEkgLIHGwXf","Novo Oriente do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("TmvALUKpmFNNqekRQ7M0","Novo Santo Antônio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("cdX1yeGhij7tRh87Ko4G","Oeiras","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("MukpNU2NmQXZDEw0f59p","Olho d'Água do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("UFx863CfSNT6HXEbsc8d","Padre Marcos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("xwbTSLYBrIFwqJA612Ey","Paes Landim","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("0f3BR65tuLnUTlSmkFDd","Pajeú do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ahmshAxosUrGGkG7rh3n","Palmeira do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("XbkLHsKMONYOWDVPVA10","Palmeirais","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("F3Jvz2PFHOnPAKlt05sS","Paquetá","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("c9CngkmJqyHcIvObEt4e","Parnaguá","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("OjWVHhyNM78yxS5SEaJe","Parnaíba","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("84TN1oYcBPjJz4q7tt2A","Passagem Franca do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("5C1jkluWMcju4sHTEgvU","Patos do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("zqidExXhYeQxUalRAKcd","Pau d'Arco do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("WZ2J6qQ3VrcOaocuFphN","Paulistana","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("6MLfRO8uU1u8KhPtqa9C","Pavussu","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("TNP4ecw6FeoT8y1TkrIi","Pedro II","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Ypnh5o0sSutZM9PZhS12","Pedro Laurentino","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ycNFwNTM5TX4XLdT3mfp","Picos","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ePxTcNcL51ZBE6u3MZse","Pimenteiras","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("WcmIG1Wp0yenBchV8ZmD","Pio IX","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1WxUHZ5TIT4GNFmTWwV4","Piracuruca","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ehzkdKZ2DsqlnbcR7l90","Piripiri","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("iQoocy3moqPDlL5bdPqr","Porto","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("77qc0G6HWg4mT8Tfk9xd","Porto Alegre do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("MRzfYMmeiLwXx0W7lumS","Prata do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("3wLgjbuZHNm0bvqh57pY","Queimada Nova","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("9SdbJDAixMvEq6SXHaBD","Redenção do Gurguéia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("R3YFZtu2wlczpPludSLt","Regeneração","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("du0aFD5r6aNgjRiA2SdN","Riacho Frio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("jYdQwNnpYMX4TXD4aBeX","Ribeira do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("1Z9XaVIfknIq6apnZD4l","Ribeiro Gonçalves","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("guKXAoeCJixutabzoSNQ","Rio Grande do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("pfZ8UdqQLUngCsnctLPZ","Santa Cruz do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Tbv8LeddO6RVie05DiKZ","Santa Cruz dos Milagres","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("rQWVPIa9zpTmk9ZnLXe2","Santa Filomena","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("qlgaLBjgXgnU8reue1nV","Santa Luz","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("PKWuUb3ZSD0Lu5xUVS3T","Santa Rosa do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("AJqrzzSsOqoVTaIghUsa","Santana do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ZtdTtUF4ZyLPAdbwE5mT","Santo Antônio de Lisboa","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ZF6vYICUTfNUeeD9ZJVa","Santo Antônio dos Milagres","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("dquDxl2vy2dm4SMEtZRo","Santo Inácio do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("zW1FjyouEfUFsCq8N706","São Braz do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("czCYrxGdF47lfMCszc6u","São Félix do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("WFBN2xC2vRHS2evKcba6","São Francisco de Assis do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("zjzpXr0aITaEpSFnVf1J","São Francisco do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("57dRUntTR7wSh4QeXX77","São Gonçalo do Gurguéia","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Ll9Oiapfa2XYhzRsTEL8","São Gonçalo do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("x7ArWehNZM2OjArbUbcc","São João da Canabrava","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("wIXSYtXjfHVSgVu3oefi","São João da Fronteira","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("AX4HUVXZXeJMT7gVyZrk","São João da Serra","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ZeQoKU36NUgcfLqtNzdP","São João da Varjota","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("sJ1ddpqdlmqcEUH3hwUw","São João do Arraial","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("dLrwQu0kjGMJbULVWlun","São João do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ppsLsDdofHLPckuFdTPb","São José do Divino","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("N8ru5ASC5y3UObfVUSE2","São José do Peixe","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Ou4vJNkrcGU4Yk2YkrQs","São José do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("lJgJ4RJa0WOPgqVquiGI","São Julião","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("upj5FjcO9X5TAc9IxCTN","São Lourenço do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("4HVmuL5W4iSVXL80Ze2L","São Luis do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("VgsJQNYK4iKD4Yo1oHuf","São Miguel da Baixa Grande","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("Ogphqy5PITLY6o7KRQjN","São Miguel do Fidalgo","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("rNRGSX9Tcl4rayGxTNCu","São Miguel do Tapuio","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("jQyKUjTkuKDqcWW4tGGq","São Pedro do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("dagANy6emQONXgd34Yk3","São Raimundo Nonato","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("2YUjLeBbRjutnc8iXrh8","Sebastião Barros","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("ejuEuYqdETwKJL2bEVIv","Sebastião Leal","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("L6kRZFUqmYwboauJrXqL","Sigefredo Pacheco","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("mAXxhgWr0tgBE1XB6mSm","Simões","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("LkmUynXUanEhGB1j0VTk","Simplício Mendes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("XUKGlBitcnxxRhLGDd07","Socorro do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("EaRvARvXrKI49VdyXZ1F","Sussuapara","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("xQBCITsShzyHdvQWOLgr","Tamboril do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("T7ANu5aUkAHCWm65lpiu","Tanque do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("pabQNSDUKn8QKPLcualc","Teresina","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("vcWzH6dR1U5tlCVTtSCG","União","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("HOJZYd1yelKFLxDaC465","Uruçuí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("j0My24AwjusgfG7K0y1X","Valença do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("skhjd5xxZ4cNkBiU5PvC","Várzea Branca","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("IwxjGVitcEa30rQ98HoT","Várzea Grande","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("CIJL997naukLK7ztPUvG","Vera Mendes","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("pDPR6RhpIWVN1vxTKYQ4","Vila Nova do Piauí","n30NTxhAuxqCa6OMcR42", "PI"));
        lista.add(new Cidade("NUd9pDQbLkuRSCbMe8yf","Wall Ferraz","n30NTxhAuxqCa6OMcR42", "PI"));

        return lista;
    }
}
