package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PR {
    public static ArrayList<Cidade> getCidades() {
        ArrayList<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("shNShMK50uGrr4dAEz5K","Abatiá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("CnG0zokfrYANDxnM0HaR","Adrianópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("IsiXjLO9R5FXRTFvvG3u","Agudos do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UK99IeXacgqD7Zqxfycx","Almirante Tamandaré","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("HAvRyzJueUjcLFsroOe0","Altamira do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("30V28xzS4KuCADzdAxv5","Alto Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ICChUBLV5xJtvA15FE2p","Alto Piquiri","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("cxMqhuCQHtgvRdWXxqmZ","Altônia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("6E2VTU70pOPiOguCjCNC","Alvorada do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("QQflRsyL3VLXAgsFFoik","Amaporã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("9Tt0Q157MDKDgTxddVWB","Ampére","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("IL0BqIAexG3YkFMRRcZd","Anahy","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("FzokRufKVIe7Dm63NoAN","Andirá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("lJgOzjFi6qQN3bYTH502","Ângulo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KSo8Ek2rYY1LjeprboxC","Antonina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("bIos7S1CHyjFv0eFfdUy","Antônio Olinto","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2Wy3L341CgxUSsYY8dNw","Apucarana","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("s0t6xRY7748avopkYA2i","Arapongas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xjsW0CCOJOAJ80jzNnqJ","Arapoti","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UqQa6kLnqM4OH3IVrzkS","Arapuã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Mx88qAyl5omcZD8WY1D5","Araruna","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("bXlpYMRU3j1FuRtUMSJ6","Araucária","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("EdlBQX7RVfyVnp1BySiW","Ariranha do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KApVwjk4rBBKPPTo5MNx","Assaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("k7FWiPFyKKzjwBSBfi2i","Assis Chateaubriand","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LikdHiMsKZp4Yq6gDAgO","Astorga","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("smmrhRFh0mzUVdUjripb","Atalaia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ORxCqGpMsIcZNRLfYcCT","Balsa Nova","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("3B6nwgKgR1roxGV9rGXU","Bandeirantes","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("j5d3ySNoF83hzkl80ZuT","Barbosa Ferraz","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("QXY9Q32zQuPNwO3UHhln","Barra do Jacaré","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gZ7NdkVptHSMzonVnC80","Barracão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("GmqXxR4CZT29NSWVmlfO","Bela Vista da Caroba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aFPSXbvKGTpq9Yybh9HB","Bela Vista do Paraíso","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("iiseQGQfF9aunLilvhb1","Bituruna","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KXlBAy8P8po0cuw0g5cv","Boa Esperança","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Vvz4uFCPNqfshoGzaQ35","Boa Esperança do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("1f2tGHBUfnsbycEBzwRX","Boa Ventura de São Roque","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aa4KXNNI4pb2vDX95jTt","Boa Vista da Aparecida","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("FBwo7cdhebSDxT7AWkXL","Bocaiúva do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LiHGPj1HNARcG4Hm1GVx","Bom Jesus do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("zWGIXLKJWPYJLAedbqFd","Bom Sucesso","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("bZm16k1wrTYVUPznhWuu","Bom Sucesso do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hDCiZfzBkgz4qJgptFIg","Borrazópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("u5kIumAehHwIXphtGrGU","Braganey","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("MT3dRDwvxySrC6VWDaIv","Brasilândia do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("8mie3ZDSZGBDCnBQJ336","Cafeara","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("dHXBy3igPIWCo6Jy9dDx","Cafelândia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("NjVctuChnjrEQ4qDpbey","Cafezal do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Jqydxg6c3ig8c7c3T0qu","Califórnia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("1mPVZokMCQ0yZ0o2n4ND","Cambará","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("iqFetPGrPaB70YAm2BT2","Cambé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("6vmdQ29fIhzzpiCXLMLp","Cambira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("WYEGzqdPgIJbxV1iSHnC","Campina da Lagoa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("3MJU8KQcXQKCcaTlZDKs","Campina do Simão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("vcclaekCUUUB6f03imI5","Campina Grande do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("w5GUv9c7FZjztLCySQfU","Campo Bonito","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LjAgCqwGhh46elgI4r1l","Campo do Tenente","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hdCwaTqeyyveh3xj4sK8","Campo Largo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ax2Esr8T8Mf1QZcqiKpn","Campo Magro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("7Hlqn4xXdrrkLRPxPY96","Campo Mourão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xcR0tYjFn7il3zBRAsUc","Cândido de Abreu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("XojDrgBGuZcfezBtZQfx","Candói","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aHLSFXU2WCd3BUF4DM8D","Cantagalo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KuzCf95G7Mr3zQidFCvG","Capanema","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Nm9ElfmEVNEM5PtYTAnQ","Capitão Leônidas Marques","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("IVAy2wHT7c6PqlJivogK","Carambeí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("FHRT8E3sCZh5YtdvguHa","Carlópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("v9UiHnMvPhOPO10rFH8f","Cascavel","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("rBFxw19Uc8FvBmsn7c4l","Castro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("IjJE7u0AkY6iNFAedpsI","Catanduvas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("QASIeekdQndwM7TquIIh","Centenário do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("jKX9M4jUFPcyRRwvOJTO","Cerro Azul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ajhSblDmY5CFcJHOUBIr","Céu Azul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("A2mFZeDNsns7Diyfc3AT","Chopinzinho","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("f3sMAkPgywP39xbQozRY","Cianorte","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("9rCRUScRUG4Mg9w95G1o","Cidade Gaúcha","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("CaKykNkejgbLVabbvcX6","Clevelândia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hvsBlWfjipjpjtMEuW0n","Colombo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("yYnu51yqBoAIrovvtYIo","Colorado","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("SYuBX3H5WajPEgptbkQ9","Congonhinhas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LNLf2sy61QCOUJdFKFlv","Conselheiro Mairinck","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("EmCSU4kORD7Fu7oT7oZV","Contenda","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ZwlBrKBjOblE3Xe4saeN","Corbélia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("uXQ32MM6jYNQZqRJ7tUP","Cornélio Procópio","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Ge7S7WJeUxhMPxm6S14R","Coronel Domingos Soares","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("MSf6UFSqRO5S3BtOYn6j","Coronel Vivida","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("zh1OC8ploLpsgJj4edbQ","Corumbataí do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("q7xWrl1wP8MiHI9zwyAP","Cruz Machado","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KQFqG0aRD3ksA3q9ANg3","Cruzeiro do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("P8FzgX5qc7M2K6jReFa2","Cruzeiro do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("npTjQNVoy4wf4cy3Mi5F","Cruzeiro do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("f6Z7s6oWcrCWoNDzOKVe","Cruzmaltina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hNLrfk4CNB8A8DU27UmD","Curitiba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("strY6aoZnGvgazM3LY9l","Curiúva","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ZoqMCz2S19espZyrjRW5","Diamante d'Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xTTVN9DTDFqIVhGlZJ2F","Diamante do Norte","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("fbJLtzkyi68Da3UfwAFf","Diamante do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("SYKEFo2EUHsiw0sPzYVQ","Dois Vizinhos","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("73weTZqaPuivlHlNhwkc","Douradina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Ue56rVd9MPaQu1cS4gu7","Doutor Camargo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Y3QRKlg5EPzZgyxIAYkv","Doutor Ulysses","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hKyeHqvuwZFKAmRpSHwv","Enéas Marques","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("tRASnO19hggXUbF4uvNs","Engenheiro Beltrão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("JbpRxnhPgjpQWp5ex2Yo","Entre Rios do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xQj6snFXI2mkLOynPutB","Esperança Nova","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("RBc1shYn5JwWFThhT1TT","Espigão Alto do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("PDmsZIScECyJMWSDPFfp","Farol","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("rMDgcq6Mr8lL3LzKxLHP","Faxinal","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("eP4Jt1Yx9fcSdtFLjoOC","Fazenda Rio Grande","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("DqpC0vQQ6eZiA9Kot4b4","Fênix","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4J52jn8mcJZAwP9AP9SW","Fernandes Pinheiro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Kwkfc5X2B0n6pXYMZQSi","Figueira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("wL96ICdkCLtckwetKA0i","Flor da Serra do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Kkq7yBqpQYTTPu99g0jA","Floraí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("isv13iHAQrZ0Jcdu5brF","Floresta","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("0iNo3cgZTIDdIKyvTmFY","Florestópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gF8ZHCvDyNIBKpGlnTTt","Flórida","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("AsRcNpBHRS0wO2pbWFhF","Formosa do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("RXbCleR7TdpZswPowAEH","Foz do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UWgfJsjODUWOHPCyPjEq","Foz do Jordão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("VZ0ksB1W3ql8bcgxVFxY","Francisco Alves","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("RdW3j0esHGHBzXYosQLK","Francisco Beltrão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Vfjg5hycMVIp6PPc3E3e","General Carneiro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2I9m333v9LFMaheEj5Ct","Godoy Moreira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("61YR4IAyxFXOd0bOBkH9","Goioerê","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("EWV30Rs1Uv50HxEMA0kg","Goioxim","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("p44qL3DZZOOso2l5jRX5","Grandes Rios","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Y2IDeTfsM9Ihk481pDM4","Guaíra","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("C7Wo4ks4ELgvw29hLMtz","Guairaçá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xdbIcfujOKrEMzcx4gsP","Guamiranga","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("d4tCJ8lWwDuLqa90mB3l","Guapirama","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UvxsbaYRfrZs2TKIHAJZ","Guaporema","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LAWshmtmsZK7OXhPJuWF","Guaraci","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("c8gIxQ0NV0YuKjZ2XdCV","Guaraniaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("QblYlozNakdr0hY1s1je","Guarapuava","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("VYXmgbqZsdKU5jKE3yp2","Guaraqueçaba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("liqg0URfuPDSVwUxRYN6","Guaratuba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ITmO4QVyFO6nM6AQsEa7","Honório Serpa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("iidpYGvyV4RBwXn2DJKK","Ibaiti","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("XH7ITX5QJMKR0RfDrjxe","Ibema","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("6Cq1365e3m5MVdzNq9KW","Ibiporã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("6kal1FlGmAvMC5swVvzD","Icaraíma","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("g1k48F9v1aoP099sK12V","Iguaraçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("9yyjGxiJZOA5R5yuTkpS","Iguatu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("btxE4V7BFEG44PB4AOYA","Imbaú","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aHAdaAndmMBbIj4R3rc2","Imbituva","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("zjbY4RWAWJoVZ9iDgZpD","Inácio Martins","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ZysE2lOPPO9fH1UbeqOq","Inajá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("sCM6BjDKyUPLGEAkHQw1","Indianópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("JscPtRnoap0zg4sBbmVu","Ipiranga","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("cx3qY0JdpW2t86zUJEsJ","Iporã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("0xQ5wk1MBO1ncthcAoXS","Iracema do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BjitA866VaUeedANcTwZ","Irati","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("krMUpNiTyUPETVlzjGg8","Iretama","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("tCJZvqnjlIFQFG02ihKr","Itaguajé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("m2gmfynZOdY4M21eqMxq","Itaipulândia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("NkmBBCW43plyphjrRHkA","Itambaracá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("n2RbOgOD3TK282bULT17","Itambé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("HqG29n66T2OLNzVTDpFw","Itapejara d'Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Wx4qbbedDzw74SNvGVuw","Itaperuçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BBXCl1NzP8KpST7sOS0V","Itaúna do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("6SJuJa21suUz5b1CINmd","Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4VxqvWDX2XM2MK3JYIYI","Ivaiporã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qqSbYZOHrzeWfipjZhYz","Ivaté","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("XxNRldxteOjcUaN3yzXM","Ivatuba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("we4xeOKoyG8vXYL6ruhV","Jaboti","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("eRBRlxmZZxpVMUZbD9En","Jacarezinho","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("NPvsgkQuGDMRbtiam7jF","Jaguapitã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gjGrYpz7GPmXoeWx3COH","Jaguariaíva","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("L1JC631LUGfeNYMiADBA","Jandaia do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ZH8siduLwhqvSJAERSLt","Janiópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("dbzOc9WIti0ldsENykPD","Japira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2fBCnfO0J0HwcNmID2fP","Japurá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Vk4LOA3FBagCLygymK84","Jardim Alegre","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UdxTrAKjgIB5cmyz8lF0","Jardim Olinda","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gBXe5LRCmFEXGZ400GcO","Jataizinho","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("7Zq0zhFMNWIRhax61IoH","Jesuítas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("vSlct5HthKz7I3cqzIjf","Joaquim Távora","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("F5kJFoNcnP5gm1qMlJU0","Jundiaí do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4xVSM3xPixdgF4GCz7Md","Juranda","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("l32U6beiXkjXsgJ6tT4r","Jussara","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("kq2SBTlS202CprmbwH5T","Kaloré","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("3TcKNx5yZgtYz9IJ6Uyp","Lapa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("n9H1lF6JFPMqB1TxoaKP","Laranjal","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("GYq48rYQ7QbTOAXlNjci","Laranjeiras do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("5RGmRR5kYelwihMfwXPb","Leópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xOdeabZQXi0gViXmlYCN","Lidianópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2ULpUy7DNgSn1zBiyITg","Lindoeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("cWATnZgtUKbCJ9jiiJDL","Loanda","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("X1CtnYhnZHvCC1i2H3Aa","Lobato","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("A5cZ3HDuyPt5JWrwQbXr","Londrina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("CzgLnonft8jJ98pcp6zG","Luiziana","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("095ytHDpMi1Lgt8g2szp","Lunardelli","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2WEj3MlzCj6Rcn3FC0pb","Lupionópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xcn79cLc8PyxAsucKrkF","Mallet","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("NIcLRf8ijYsja1UK8Kr2","Mamborê","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("9bXPppXZ6n04pcXtbxyq","Mandaguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qqXWL97OYjJDENEpJ9UA","Mandaguari","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("eAn58ifAco3I8999LLUa","Mandirituba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("yFUYNBM3mme4ArslxiZv","Manfrinópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("0Z8iAba3hLDE7rZYqavq","Mangueirinha","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("1G3mYnhYJlYG9GVGbkcn","Manoel Ribas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("3V0I50Mkg2NDohOnCySP","Marechal Cândido Rondon","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("r9JjuLwsY0aHnohUtJ4n","Maria Helena","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ZNk7aJSvSuKVSjibNZVc","Marialva","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("GVkeqjv2KR6XgeK9wPLw","Marilândia do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("zkt0y7argG5xxDCEy9Cd","Marilena","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LSs92W0jT6E1H5nS6cSs","Mariluz","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("PcXSMZQMxdKDrUNV4tqj","Maringá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KHaxOBB7Nj01cMu9uhDM","Mariópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("16E465GNFRT1FMeuKwvt","Maripá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Y8t99VCu00axE3JSzYlm","Marmeleiro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("19pQ5T06bMBwy0AhbX0R","Marquinho","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("trqLIbimSCLa9fQTwAqq","Marumbi","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BiuG5tlnmWpZJiTYyXrK","Matelândia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("pQvn5uBeuiKZtFoqOR31","Matinhos","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("IjJo7PU9I6LEmqzIfUkK","Mato Rico","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("HqPM3R9fArJKPO0iUlcf","Mauá da Serra","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4iFShG6SxpTLH5vRXwnT","Medianeira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("scvANOAuBbZ9OQhcNQdk","Mercedes","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("awY9TfupE3TBBLu87mDI","Mirador","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("NsYSIGFtMycbyTGgdwXM","Miraselva","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("tqBFew9kxvoxN8ehba75","Missal","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("T0mK45vnBI2n2rVOEhal","Moreira Sales","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("zA4rFHVTpt7PpjymFrJK","Morretes","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("9ZL6mRYkBpWVji5o2ks0","Munhoz de Melo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4z6YS1SWGLnig9YyVRM0","Nossa Senhora das Graças","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4lkvdgakreQSGXMS7ptr","Nova Aliança do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("szPVIVKYBzDm08hOdJEP","Nova América da Colina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("1dWuHoyScMyr7HM9I94F","Nova Aurora","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xNSknKVXkYeZXVCVR5y3","Nova Cantu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ZeoXOkyj9Ups9qpEmlzh","Nova Esperança","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("QjIIpk0Mppa3eO3BTRPz","Nova Esperança do Sudoeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("6jLwUkkmCqqBDVy2scCV","Nova Fátima","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("115G7AYYekPSYeN2va0W","Nova Laranjeiras","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("OSIa73KaZNtnX3dgxQ2I","Nova Londrina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("SjEcpugXXP92bPIZ8Yxu","Nova Olímpia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Nu9hxbMR6K9MV0NJidmO","Nova Prata do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("DqXES3IljYHvLKQyTDga","Nova Santa Bárbara","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("fWWZEoUBBvhI9q4s89vP","Nova Santa Rosa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("I1G9RNtUG1FEzu86QAOH","Nova Tebas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4SOk6yXq5mxaXRp60dzr","Novo Itacolomi","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Qz4XTF0CbgZt5w9a0ATC","Ortigueira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qY8cwu8fjStoH78Yiesm","Ourizona","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hbhIJ3kVhKzvosS69jVQ","Ouro Verde do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("pSC4jiXI82CLFnzrWsJv","Paiçandu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("FEtVWLKeTCHiZTaMo2hl","Palmas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("yVLcJQZ4kiMzQQdHrVlf","Palmeira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ASGkuQpF7LMohVygD77q","Palmital","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UmFjtGvRRRKvsl2EibK6","Palotina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("oIeHwAokveL0j6nQKoqs","Paraíso do Norte","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("VrHf1p6WCXOo1botkDAL","Paranacity","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LkLe3Cb9BRnaS7Nw1Rao","Paranaguá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Rd6VC8sKD1IA5zMoj55Z","Paranapoema","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ljzH1X4PvJwAUXb7tNYB","Paranavaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("oZJgCVBKwxYxd6QBNh3B","Pato Bragado","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("L6OMgS7Hz6R0o6sredig","Pato Branco","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("7R68LEw1QDbPFtxg57RV","Paula Freitas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2TdFO0dqFqj19825cgNY","Paulo Frontin","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("TAoYnOKhca84Yf7SrLF9","Peabiru","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hEIMj2ZBwbrunOup3voa","Perobal","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("yhAyXSb1jRJ96DXrsC55","Pérola","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("DVPZXCTzzKRlOlHsBW7U","Pérola d'Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("vJlWLGFBE67gH3IQmjdJ","Piên","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("swWxFFkqQrePM2CtCPb7","Pinhais","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("mZcz7H3ClLAEcNMbABx5","Pinhal de São Bento","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ze9NDxdN7kgB5vTdLPEp","Pinhalão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("GBaqrgHlbVQoAYNAPwOP","Pinhão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("iEScJFNJxEZaCiL3Jgx6","Piraí do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("HkJa03ThbXCMJqJwYYAH","Piraquara","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("VHuwKoVyuekeNJkCOWaA","Pitanga","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("XkSRcWtRdyCSnG0DIZAV","Pitangueiras","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BlwZnWZzRPPry9kZq8l5","Planaltina do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("w2MIWVSqaaxPMeMbgQcS","Planalto","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("piMdrebTzNSvG8FCwVnX","Ponta Grossa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("tKBbR19kOWpWKC7S3AKS","Pontal do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BoxbOeom2cr7VXadii5E","Porecatu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("eAdwUFRxNJHjiXkmQXyd","Porto Amazonas","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xw8K3t90Xqh76mCeJyZ5","Porto Barreiro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("D21VgMZyPaH42uMvE1kw","Porto Rico","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("mEK14rsu9mlSOqzCOBMP","Porto Vitória","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Yyu8sV72lA2Oq0dMliqR","Prado Ferreira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ixcMdPEdoH1qAj6u1Fuv","Pranchita","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("YbydtSA0T5dj5DLfJkHe","Presidente Castelo Branco","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("GhZnsDtjoIqi8gVcl4d9","Primeiro de Maio","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("VTlpyohBjRSMGJhjfl1w","Prudentópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("tk1l3ZBSRrkfzHdWzhKY","Quarto Centenário","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ke7dm91MMCXceyfgbfVK","Quatiguá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("k0A0PpGA6YKMqJDicbz8","Quatro Barras","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("RZDSU9gVgRkVmNx0ypNi","Quatro Pontes","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BaNJioFr5Wl1vcv36d44","Quedas do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("pM4xmcpggEEKd88F574y","Querência do Norte","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("pPJuFjhCGnmdS28zEGNs","Quinta do Sol","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Q5qJ6BDFG9DQyUQpzVbP","Quitandinha","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("xfQv7PPX0Ljbe0CgYiCo","Ramilândia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("apGsVpidCVlh1lS2JGUU","Rancho Alegre","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("HfRezmMuz2Us7IL5vPlT","Rancho Alegre d'Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("0DhQh69FxfPSj4YbY2zS","Realeza","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("pbH0oeD4q16b3lxbD63I","Rebouças","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("XxmeNA075ieLpBvNuBuq","Renascença","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("RRRGQmNw6wFgyF4ecrNv","Reserva","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("3KPWnLm5HfUmQLcnqP7U","Reserva do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Ha3R5zldQjmbFjLObCX9","Ribeirão Claro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("MhraoBwSxCdSO8j0ugTl","Ribeirão do Pinhal","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("zr7TSCH69obdTa0eb6AB","Rio Azul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("d4YnLPLcNgoF2mSBnjZq","Rio Bom","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("hXHpjZQHs3pQ2KAWRGjJ","Rio Bonito do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2Ql8Xf1HnZk3w1DN0hS3","Rio Branco do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("wILFVmtqvTmFBML7qhvX","Rio Branco do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("bAlfeLzNnaKD5bLVPgak","Rio Negro","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("P6bymhh3PndJPKf7wiRX","Rolândia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("1KrFxhhx87eVMc0MyMxF","Roncador","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("yLUeMjyb7IGRi3ySwR4v","Rondon","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("CoteHlDJUN6aDRaLfNXi","Rosário do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("CXvRlSfO4Dsc7dSowPOD","Sabáudia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("I1hbp0kwy85r0o15NQ1m","Salgado Filho","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gttvsdAEAlhEaMkBQX9M","Salto do Itararé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("4RKfrJ87hMj9uRKCoNGt","Salto do Lontra","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("neJ4b4MGEaXl0RXA0Suh","Santa Amélia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("2MFewYLE1FRIKiQ6vyU1","Santa Cecília do Pavão","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("D1euLRvONUdWSisxmRE7","Santa Cruz Monte Castelo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Zj3BWrnJ1LQQftwpmLI4","Santa Fé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("IaH2skTQ3Kzjnq2Xso09","Santa Helena","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Omb4FGLv6zXLa6baQ2ad","Santa Inês","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("L1ZlpXdmeVDpmdu9nOsG","Santa Isabel do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("MshIRKCeIGs2KZMNu2zD","Santa Izabel do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("P6kjgUQ2zyYgSBSWefOx","Santa Lúcia","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("C7ggimWetSZOjVDRfjfu","Santa Maria do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("LxhbxEDdjkrh0zdghegO","Santa Mariana","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("q9Y4CQMEWKBwv5g3Aj5X","Santa Mônica","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("WZZdlrnRat4paUiy8DJu","Santa Tereza do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("etoY8AGCc3qxRE4YbUdy","Santa Terezinha de Itaipu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aVLhK6S9FApoqX5IU7A0","Santana do Itararé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("m5DbFeD6POcIrupGPte8","Santo Antônio da Platina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("wVz0tQSfMcwn4p3QgBEF","Santo Antônio do Caiuá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UoY3wiJd0HvSxkVqZzfa","Santo Antônio do Paraíso","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("lcyND4ZqJtFPHKauAjIq","Santo Antônio do Sudoeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("sFWS87nkvbnu4X6WoPvu","Santo Inácio","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("OvFikw4IfdtiIm7BrwcC","São Carlos do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("MGVeo3tnOaUC1SEyyMr0","São Jerônimo da Serra","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("A24BwqAKoGJ4Le8sBlvq","São João","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Y1ZzLs4NTka0Luf5jypl","São João do Caiuá","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gZs4k0tg0aewUly4cBM8","São João do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("V2QFPob9yEUm1TKbARev","São João do Triunfo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Hk93pTmiq36CIZmVp8qn","São Jorge d'Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("JzXuXfInRF9OobY8r71V","São Jorge do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("7vUDNwWPCGwKn0ohaoTn","São Jorge do Patrocínio","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BfpU2ANrqSm5JcDqKetQ","São José da Boa Vista","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("cpiNAzbpScVJwIp9Z9Nt","São José das Palmeiras","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qAyhoMxu7nLr4m0su0wH","São José dos Pinhais","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("H3wKtAegsIUDfCYGGter","São Manoel do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("vRpD6bKyc8VtEZ4KQcJk","São Mateus do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qaG7KBRUgCrgtAy6sKmQ","São Miguel do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("9gCm7RUS8gkiW4ITXV5j","São Pedro do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("QSaX7NqsChcSBDpRKI6F","São Pedro do Ivaí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("nCqAfiAHnDHGQLRaJPUi","São Pedro do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("237cSZaP9WqDjYs8JIUl","São Sebastião da Amoreira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Xl4sPhRjInDC9XUqIC4p","São Tomé","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("K5D550QtN1KlfNm6SWwK","Sapopema","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("kMQc1zXU2BYUEA76Z0f0","Sarandi","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("JnpXSQpcHJ21d4NnotWr","Saudade do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("fTkjB5ia2hIqRCArhPEJ","Sengés","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("7tLUe1PP0IDKTAhxF6bl","Serranópolis do Iguaçu","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gNdEtHab1gLfMMO5V7Bt","Sertaneja","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("nrW9Ym7nIdspsfVRhtBc","Sertanópolis","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("nOgkTSx0HtB02YanYbv4","Siqueira Campos","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UKlKn0LYc6E22MlNoMIR","Sulina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("U2QtFZc7ctWNFBnnVGn9","Tamarana","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("emWyxqy00wO4RxXc4Ap3","Tamboara","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("rWjLI4gR3ewEJULcI1tn","Tapejara","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("oonD34iZfYVgd9gdJ42S","Tapira","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qPfeNeJXazyLicl8yT4v","Teixeira Soares","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("eSoW4sihuwLB1BsXCpob","Telêmaco Borba","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ENEnGkxNLqMJz4ujBcgu","Terra Boa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qv2rN6iKFEU62K4EX4D1","Terra Rica","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("nhXORa0aweYwiGfSrNoz","Terra Roxa","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aRGLB13jui745ctdy3N7","Tibagi","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KAVD28KlzhKfDc5gFH0p","Tijucas do Sul","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("nAadq404QtEfI1yWXXIk","Toledo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("kA3KeRlclJn9Rw8P3HM1","Tomazina","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("ncBs42e3zQLBBzUFBdBn","Três Barras do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("rKmx6MNgnAmJ3RwWP55M","Tunas do Paraná","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("KbzclomHRggrNXfgxm18","Tuneiras do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("UyKvxpjdiSDc169OJjpp","Tupãssi","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("iil0KM3EUH3dNr8Eb2El","Turvo","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Sov84QH7jmxuHT0pIBYS","Ubiratã","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("gNf0rWn2PeuHWkzv61hE","Umuarama","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("EP2dvnPWg3WQcYJ4gVgs","União da Vitória","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("D40lbqPewgwvRMDzBygU","Uniflor","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("coCbwZA73gYwp1sqiMzW","Uraí","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("dHGO5IazilKJwjj5Wj4B","Ventania","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("qVTtYxCcb9GeeIL4F29w","Vera Cruz do Oeste","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("kAL5grVpL0uTT0ilIU8n","Verê","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("XYzIZo2PUZLFAnlHRODV","Vila Alta","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("Jm8YzB6fLlaUdQRc7ETe","Virmond","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("aflVA67blhIiGlEwjdRE","Vitorino","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("BodRrxiTYU0DqyqmBGRm","Wenceslau Braz","ExaDaauaC2Jwt6W9rT8Y", "PR"));
        lista.add(new Cidade("t2TjEQiALrAFcvX9Sxd9","Xambrê","ExaDaauaC2Jwt6W9rT8Y", "PR"));

        return lista;
    }
}
