package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class PR {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Abatiá","PR"));
        lista.add(new Cidade("","Adrianópolis","PR"));
        lista.add(new Cidade("","Agudos do Sul","PR"));
        lista.add(new Cidade("","Almirante Tamandaré","PR"));
        lista.add(new Cidade("","Altamira do Paraná","PR"));
        lista.add(new Cidade("","Alto Paraná","PR"));
        lista.add(new Cidade("","Alto Piquiri","PR"));
        lista.add(new Cidade("","Altônia","PR"));
        lista.add(new Cidade("","Alvorada do Sul","PR"));
        lista.add(new Cidade("","Amaporã","PR"));
        lista.add(new Cidade("","Ampére","PR"));
        lista.add(new Cidade("","Anahy","PR"));
        lista.add(new Cidade("","Andirá","PR"));
        lista.add(new Cidade("","Ângulo","PR"));
        lista.add(new Cidade("","Antonina","PR"));
        lista.add(new Cidade("","Antônio Olinto","PR"));
        lista.add(new Cidade("","Apucarana","PR"));
        lista.add(new Cidade("","Arapongas","PR"));
        lista.add(new Cidade("","Arapoti","PR"));
        lista.add(new Cidade("","Arapuã","PR"));
        lista.add(new Cidade("","Araruna","PR"));
        lista.add(new Cidade("","Araucária","PR"));
        lista.add(new Cidade("","Ariranha do Ivaí","PR"));
        lista.add(new Cidade("","Assaí","PR"));
        lista.add(new Cidade("","Assis Chateaubriand","PR"));
        lista.add(new Cidade("","Astorga","PR"));
        lista.add(new Cidade("","Atalaia","PR"));
        lista.add(new Cidade("","Balsa Nova","PR"));
        lista.add(new Cidade("","Bandeirantes","PR"));
        lista.add(new Cidade("","Barbosa Ferraz","PR"));
        lista.add(new Cidade("","Barra do Jacaré","PR"));
        lista.add(new Cidade("","Barracão","PR"));
        lista.add(new Cidade("","Bela Vista da Caroba","PR"));
        lista.add(new Cidade("","Bela Vista do Paraíso","PR"));
        lista.add(new Cidade("","Bituruna","PR"));
        lista.add(new Cidade("","Boa Esperança","PR"));
        lista.add(new Cidade("","Boa Esperança do Iguaçu","PR"));
        lista.add(new Cidade("","Boa Ventura de São Roque","PR"));
        lista.add(new Cidade("","Boa Vista da Aparecida","PR"));
        lista.add(new Cidade("","Bocaiúva do Sul","PR"));
        lista.add(new Cidade("","Bom Jesus do Sul","PR"));
        lista.add(new Cidade("","Bom Sucesso","PR"));
        lista.add(new Cidade("","Bom Sucesso do Sul","PR"));
        lista.add(new Cidade("","Borrazópolis","PR"));
        lista.add(new Cidade("","Braganey","PR"));
        lista.add(new Cidade("","Brasilândia do Sul","PR"));
        lista.add(new Cidade("","Cafeara","PR"));
        lista.add(new Cidade("","Cafelândia","PR"));
        lista.add(new Cidade("","Cafezal do Sul","PR"));
        lista.add(new Cidade("","Califórnia","PR"));
        lista.add(new Cidade("","Cambará","PR"));
        lista.add(new Cidade("","Cambé","PR"));
        lista.add(new Cidade("","Cambira","PR"));
        lista.add(new Cidade("","Campina da Lagoa","PR"));
        lista.add(new Cidade("","Campina do Simão","PR"));
        lista.add(new Cidade("","Campina Grande do Sul","PR"));
        lista.add(new Cidade("","Campo Bonito","PR"));
        lista.add(new Cidade("","Campo do Tenente","PR"));
        lista.add(new Cidade("","Campo Largo","PR"));
        lista.add(new Cidade("","Campo Magro","PR"));
        lista.add(new Cidade("","Campo Mourão","PR"));
        lista.add(new Cidade("","Cândido de Abreu","PR"));
        lista.add(new Cidade("","Candói","PR"));
        lista.add(new Cidade("","Cantagalo","PR"));
        lista.add(new Cidade("","Capanema","PR"));
        lista.add(new Cidade("","Capitão Leônidas Marques","PR"));
        lista.add(new Cidade("","Carambeí","PR"));
        lista.add(new Cidade("","Carlópolis","PR"));
        lista.add(new Cidade("","Cascavel","PR"));
        lista.add(new Cidade("","Castro","PR"));
        lista.add(new Cidade("","Catanduvas","PR"));
        lista.add(new Cidade("","Centenário do Sul","PR"));
        lista.add(new Cidade("","Cerro Azul","PR"));
        lista.add(new Cidade("","Céu Azul","PR"));
        lista.add(new Cidade("","Chopinzinho","PR"));
        lista.add(new Cidade("","Cianorte","PR"));
        lista.add(new Cidade("","Cidade Gaúcha","PR"));
        lista.add(new Cidade("","Clevelândia","PR"));
        lista.add(new Cidade("","Colombo","PR"));
        lista.add(new Cidade("","Colorado","PR"));
        lista.add(new Cidade("","Congonhinhas","PR"));
        lista.add(new Cidade("","Conselheiro Mairinck","PR"));
        lista.add(new Cidade("","Contenda","PR"));
        lista.add(new Cidade("","Corbélia","PR"));
        lista.add(new Cidade("","Cornélio Procópio","PR"));
        lista.add(new Cidade("","Coronel Domingos Soares","PR"));
        lista.add(new Cidade("","Coronel Vivida","PR"));
        lista.add(new Cidade("","Corumbataí do Sul","PR"));
        lista.add(new Cidade("","Cruz Machado","PR"));
        lista.add(new Cidade("","Cruzeiro do Iguaçu","PR"));
        lista.add(new Cidade("","Cruzeiro do Oeste","PR"));
        lista.add(new Cidade("","Cruzeiro do Sul","PR"));
        lista.add(new Cidade("","Cruzmaltina","PR"));
        lista.add(new Cidade("","Curitiba","PR"));
        lista.add(new Cidade("","Curiúva","PR"));
        lista.add(new Cidade("","Diamante d'Oeste","PR"));
        lista.add(new Cidade("","Diamante do Norte","PR"));
        lista.add(new Cidade("","Diamante do Sul","PR"));
        lista.add(new Cidade("","Dois Vizinhos","PR"));
        lista.add(new Cidade("","Douradina","PR"));
        lista.add(new Cidade("","Doutor Camargo","PR"));
        lista.add(new Cidade("","Doutor Ulysses","PR"));
        lista.add(new Cidade("","Enéas Marques","PR"));
        lista.add(new Cidade("","Engenheiro Beltrão","PR"));
        lista.add(new Cidade("","Entre Rios do Oeste","PR"));
        lista.add(new Cidade("","Esperança Nova","PR"));
        lista.add(new Cidade("","Espigão Alto do Iguaçu","PR"));
        lista.add(new Cidade("","Farol","PR"));
        lista.add(new Cidade("","Faxinal","PR"));
        lista.add(new Cidade("","Fazenda Rio Grande","PR"));
        lista.add(new Cidade("","Fênix","PR"));
        lista.add(new Cidade("","Fernandes Pinheiro","PR"));
        lista.add(new Cidade("","Figueira","PR"));
        lista.add(new Cidade("","Flor da Serra do Sul","PR"));
        lista.add(new Cidade("","Floraí","PR"));
        lista.add(new Cidade("","Floresta","PR"));
        lista.add(new Cidade("","Florestópolis","PR"));
        lista.add(new Cidade("","Flórida","PR"));
        lista.add(new Cidade("","Formosa do Oeste","PR"));
        lista.add(new Cidade("","Foz do Iguaçu","PR"));
        lista.add(new Cidade("","Foz do Jordão","PR"));
        lista.add(new Cidade("","Francisco Alves","PR"));
        lista.add(new Cidade("","Francisco Beltrão","PR"));
        lista.add(new Cidade("","General Carneiro","PR"));
        lista.add(new Cidade("","Godoy Moreira","PR"));
        lista.add(new Cidade("","Goioerê","PR"));
        lista.add(new Cidade("","Goioxim","PR"));
        lista.add(new Cidade("","Grandes Rios","PR"));
        lista.add(new Cidade("","Guaíra","PR"));
        lista.add(new Cidade("","Guairaçá","PR"));
        lista.add(new Cidade("","Guamiranga","PR"));
        lista.add(new Cidade("","Guapirama","PR"));
        lista.add(new Cidade("","Guaporema","PR"));
        lista.add(new Cidade("","Guaraci","PR"));
        lista.add(new Cidade("","Guaraniaçu","PR"));
        lista.add(new Cidade("","Guarapuava","PR"));
        lista.add(new Cidade("","Guaraqueçaba","PR"));
        lista.add(new Cidade("","Guaratuba","PR"));
        lista.add(new Cidade("","Honório Serpa","PR"));
        lista.add(new Cidade("","Ibaiti","PR"));
        lista.add(new Cidade("","Ibema","PR"));
        lista.add(new Cidade("","Ibiporã","PR"));
        lista.add(new Cidade("","Icaraíma","PR"));
        lista.add(new Cidade("","Iguaraçu","PR"));
        lista.add(new Cidade("","Iguatu","PR"));
        lista.add(new Cidade("","Imbaú","PR"));
        lista.add(new Cidade("","Imbituva","PR"));
        lista.add(new Cidade("","Inácio Martins","PR"));
        lista.add(new Cidade("","Inajá","PR"));
        lista.add(new Cidade("","Indianópolis","PR"));
        lista.add(new Cidade("","Ipiranga","PR"));
        lista.add(new Cidade("","Iporã","PR"));
        lista.add(new Cidade("","Iracema do Oeste","PR"));
        lista.add(new Cidade("","Irati","PR"));
        lista.add(new Cidade("","Iretama","PR"));
        lista.add(new Cidade("","Itaguajé","PR"));
        lista.add(new Cidade("","Itaipulândia","PR"));
        lista.add(new Cidade("","Itambaracá","PR"));
        lista.add(new Cidade("","Itambé","PR"));
        lista.add(new Cidade("","Itapejara d'Oeste","PR"));
        lista.add(new Cidade("","Itaperuçu","PR"));
        lista.add(new Cidade("","Itaúna do Sul","PR"));
        lista.add(new Cidade("","Ivaí","PR"));
        lista.add(new Cidade("","Ivaiporã","PR"));
        lista.add(new Cidade("","Ivaté","PR"));
        lista.add(new Cidade("","Ivatuba","PR"));
        lista.add(new Cidade("","Jaboti","PR"));
        lista.add(new Cidade("","Jacarezinho","PR"));
        lista.add(new Cidade("","Jaguapitã","PR"));
        lista.add(new Cidade("","Jaguariaíva","PR"));
        lista.add(new Cidade("","Jandaia do Sul","PR"));
        lista.add(new Cidade("","Janiópolis","PR"));
        lista.add(new Cidade("","Japira","PR"));
        lista.add(new Cidade("","Japurá","PR"));
        lista.add(new Cidade("","Jardim Alegre","PR"));
        lista.add(new Cidade("","Jardim Olinda","PR"));
        lista.add(new Cidade("","Jataizinho","PR"));
        lista.add(new Cidade("","Jesuítas","PR"));
        lista.add(new Cidade("","Joaquim Távora","PR"));
        lista.add(new Cidade("","Jundiaí do Sul","PR"));
        lista.add(new Cidade("","Juranda","PR"));
        lista.add(new Cidade("","Jussara","PR"));
        lista.add(new Cidade("","Kaloré","PR"));
        lista.add(new Cidade("","Lapa","PR"));
        lista.add(new Cidade("","Laranjal","PR"));
        lista.add(new Cidade("","Laranjeiras do Sul","PR"));
        lista.add(new Cidade("","Leópolis","PR"));
        lista.add(new Cidade("","Lidianópolis","PR"));
        lista.add(new Cidade("","Lindoeste","PR"));
        lista.add(new Cidade("","Loanda","PR"));
        lista.add(new Cidade("","Lobato","PR"));
        lista.add(new Cidade("","Londrina","PR"));
        lista.add(new Cidade("","Luiziana","PR"));
        lista.add(new Cidade("","Lunardelli","PR"));
        lista.add(new Cidade("","Lupionópolis","PR"));
        lista.add(new Cidade("","Mallet","PR"));
        lista.add(new Cidade("","Mamborê","PR"));
        lista.add(new Cidade("","Mandaguaçu","PR"));
        lista.add(new Cidade("","Mandaguari","PR"));
        lista.add(new Cidade("","Mandirituba","PR"));
        lista.add(new Cidade("","Manfrinópolis","PR"));
        lista.add(new Cidade("","Mangueirinha","PR"));
        lista.add(new Cidade("","Manoel Ribas","PR"));
        lista.add(new Cidade("","Marechal Cândido Rondon","PR"));
        lista.add(new Cidade("","Maria Helena","PR"));
        lista.add(new Cidade("","Marialva","PR"));
        lista.add(new Cidade("","Marilândia do Sul","PR"));
        lista.add(new Cidade("","Marilena","PR"));
        lista.add(new Cidade("","Mariluz","PR"));
        lista.add(new Cidade("","Maringá","PR"));
        lista.add(new Cidade("","Mariópolis","PR"));
        lista.add(new Cidade("","Maripá","PR"));
        lista.add(new Cidade("","Marmeleiro","PR"));
        lista.add(new Cidade("","Marquinho","PR"));
        lista.add(new Cidade("","Marumbi","PR"));
        lista.add(new Cidade("","Matelândia","PR"));
        lista.add(new Cidade("","Matinhos","PR"));
        lista.add(new Cidade("","Mato Rico","PR"));
        lista.add(new Cidade("","Mauá da Serra","PR"));
        lista.add(new Cidade("","Medianeira","PR"));
        lista.add(new Cidade("","Mercedes","PR"));
        lista.add(new Cidade("","Mirador","PR"));
        lista.add(new Cidade("","Miraselva","PR"));
        lista.add(new Cidade("","Missal","PR"));
        lista.add(new Cidade("","Moreira Sales","PR"));
        lista.add(new Cidade("","Morretes","PR"));
        lista.add(new Cidade("","Munhoz de Melo","PR"));
        lista.add(new Cidade("","Nossa Senhora das Graças","PR"));
        lista.add(new Cidade("","Nova Aliança do Ivaí","PR"));
        lista.add(new Cidade("","Nova América da Colina","PR"));
        lista.add(new Cidade("","Nova Aurora","PR"));
        lista.add(new Cidade("","Nova Cantu","PR"));
        lista.add(new Cidade("","Nova Esperança","PR"));
        lista.add(new Cidade("","Nova Esperança do Sudoeste","PR"));
        lista.add(new Cidade("","Nova Fátima","PR"));
        lista.add(new Cidade("","Nova Laranjeiras","PR"));
        lista.add(new Cidade("","Nova Londrina","PR"));
        lista.add(new Cidade("","Nova Olímpia","PR"));
        lista.add(new Cidade("","Nova Prata do Iguaçu","PR"));
        lista.add(new Cidade("","Nova Santa Bárbara","PR"));
        lista.add(new Cidade("","Nova Santa Rosa","PR"));
        lista.add(new Cidade("","Nova Tebas","PR"));
        lista.add(new Cidade("","Novo Itacolomi","PR"));
        lista.add(new Cidade("","Ortigueira","PR"));
        lista.add(new Cidade("","Ourizona","PR"));
        lista.add(new Cidade("","Ouro Verde do Oeste","PR"));
        lista.add(new Cidade("","Paiçandu","PR"));
        lista.add(new Cidade("","Palmas","PR"));
        lista.add(new Cidade("","Palmeira","PR"));
        lista.add(new Cidade("","Palmital","PR"));
        lista.add(new Cidade("","Palotina","PR"));
        lista.add(new Cidade("","Paraíso do Norte","PR"));
        lista.add(new Cidade("","Paranacity","PR"));
        lista.add(new Cidade("","Paranaguá","PR"));
        lista.add(new Cidade("","Paranapoema","PR"));
        lista.add(new Cidade("","Paranavaí","PR"));
        lista.add(new Cidade("","Pato Bragado","PR"));
        lista.add(new Cidade("","Pato Branco","PR"));
        lista.add(new Cidade("","Paula Freitas","PR"));
        lista.add(new Cidade("","Paulo Frontin","PR"));
        lista.add(new Cidade("","Peabiru","PR"));
        lista.add(new Cidade("","Perobal","PR"));
        lista.add(new Cidade("","Pérola","PR"));
        lista.add(new Cidade("","Pérola d'Oeste","PR"));
        lista.add(new Cidade("","Piên","PR"));
        lista.add(new Cidade("","Pinhais","PR"));
        lista.add(new Cidade("","Pinhal de São Bento","PR"));
        lista.add(new Cidade("","Pinhalão","PR"));
        lista.add(new Cidade("","Pinhão","PR"));
        lista.add(new Cidade("","Piraí do Sul","PR"));
        lista.add(new Cidade("","Piraquara","PR"));
        lista.add(new Cidade("","Pitanga","PR"));
        lista.add(new Cidade("","Pitangueiras","PR"));
        lista.add(new Cidade("","Planaltina do Paraná","PR"));
        lista.add(new Cidade("","Planalto","PR"));
        lista.add(new Cidade("","Ponta Grossa","PR"));
        lista.add(new Cidade("","Pontal do Paraná","PR"));
        lista.add(new Cidade("","Porecatu","PR"));
        lista.add(new Cidade("","Porto Amazonas","PR"));
        lista.add(new Cidade("","Porto Barreiro","PR"));
        lista.add(new Cidade("","Porto Rico","PR"));
        lista.add(new Cidade("","Porto Vitória","PR"));
        lista.add(new Cidade("","Prado Ferreira","PR"));
        lista.add(new Cidade("","Pranchita","PR"));
        lista.add(new Cidade("","Presidente Castelo Branco","PR"));
        lista.add(new Cidade("","Primeiro de Maio","PR"));
        lista.add(new Cidade("","Prudentópolis","PR"));
        lista.add(new Cidade("","Quarto Centenário","PR"));
        lista.add(new Cidade("","Quatiguá","PR"));
        lista.add(new Cidade("","Quatro Barras","PR"));
        lista.add(new Cidade("","Quatro Pontes","PR"));
        lista.add(new Cidade("","Quedas do Iguaçu","PR"));
        lista.add(new Cidade("","Querência do Norte","PR"));
        lista.add(new Cidade("","Quinta do Sol","PR"));
        lista.add(new Cidade("","Quitandinha","PR"));
        lista.add(new Cidade("","Ramilândia","PR"));
        lista.add(new Cidade("","Rancho Alegre","PR"));
        lista.add(new Cidade("","Rancho Alegre d'Oeste","PR"));
        lista.add(new Cidade("","Realeza","PR"));
        lista.add(new Cidade("","Rebouças","PR"));
        lista.add(new Cidade("","Renascença","PR"));
        lista.add(new Cidade("","Reserva","PR"));
        lista.add(new Cidade("","Reserva do Iguaçu","PR"));
        lista.add(new Cidade("","Ribeirão Claro","PR"));
        lista.add(new Cidade("","Ribeirão do Pinhal","PR"));
        lista.add(new Cidade("","Rio Azul","PR"));
        lista.add(new Cidade("","Rio Bom","PR"));
        lista.add(new Cidade("","Rio Bonito do Iguaçu","PR"));
        lista.add(new Cidade("","Rio Branco do Ivaí","PR"));
        lista.add(new Cidade("","Rio Branco do Sul","PR"));
        lista.add(new Cidade("","Rio Negro","PR"));
        lista.add(new Cidade("","Rolândia","PR"));
        lista.add(new Cidade("","Roncador","PR"));
        lista.add(new Cidade("","Rondon","PR"));
        lista.add(new Cidade("","Rosário do Ivaí","PR"));
        lista.add(new Cidade("","Sabáudia","PR"));
        lista.add(new Cidade("","Salgado Filho","PR"));
        lista.add(new Cidade("","Salto do Itararé","PR"));
        lista.add(new Cidade("","Salto do Lontra","PR"));
        lista.add(new Cidade("","Santa Amélia","PR"));
        lista.add(new Cidade("","Santa Cecília do Pavão","PR"));
        lista.add(new Cidade("","Santa Cruz Monte Castelo","PR"));
        lista.add(new Cidade("","Santa Fé","PR"));
        lista.add(new Cidade("","Santa Helena","PR"));
        lista.add(new Cidade("","Santa Inês","PR"));
        lista.add(new Cidade("","Santa Isabel do Ivaí","PR"));
        lista.add(new Cidade("","Santa Izabel do Oeste","PR"));
        lista.add(new Cidade("","Santa Lúcia","PR"));
        lista.add(new Cidade("","Santa Maria do Oeste","PR"));
        lista.add(new Cidade("","Santa Mariana","PR"));
        lista.add(new Cidade("","Santa Mônica","PR"));
        lista.add(new Cidade("","Santa Tereza do Oeste","PR"));
        lista.add(new Cidade("","Santa Terezinha de Itaipu","PR"));
        lista.add(new Cidade("","Santana do Itararé","PR"));
        lista.add(new Cidade("","Santo Antônio da Platina","PR"));
        lista.add(new Cidade("","Santo Antônio do Caiuá","PR"));
        lista.add(new Cidade("","Santo Antônio do Paraíso","PR"));
        lista.add(new Cidade("","Santo Antônio do Sudoeste","PR"));
        lista.add(new Cidade("","Santo Inácio","PR"));
        lista.add(new Cidade("","São Carlos do Ivaí","PR"));
        lista.add(new Cidade("","São Jerônimo da Serra","PR"));
        lista.add(new Cidade("","São João","PR"));
        lista.add(new Cidade("","São João do Caiuá","PR"));
        lista.add(new Cidade("","São João do Ivaí","PR"));
        lista.add(new Cidade("","São João do Triunfo","PR"));
        lista.add(new Cidade("","São Jorge d'Oeste","PR"));
        lista.add(new Cidade("","São Jorge do Ivaí","PR"));
        lista.add(new Cidade("","São Jorge do Patrocínio","PR"));
        lista.add(new Cidade("","São José da Boa Vista","PR"));
        lista.add(new Cidade("","São José das Palmeiras","PR"));
        lista.add(new Cidade("","São José dos Pinhais","PR"));
        lista.add(new Cidade("","São Manoel do Paraná","PR"));
        lista.add(new Cidade("","São Mateus do Sul","PR"));
        lista.add(new Cidade("","São Miguel do Iguaçu","PR"));
        lista.add(new Cidade("","São Pedro do Iguaçu","PR"));
        lista.add(new Cidade("","São Pedro do Ivaí","PR"));
        lista.add(new Cidade("","São Pedro do Paraná","PR"));
        lista.add(new Cidade("","São Sebastião da Amoreira","PR"));
        lista.add(new Cidade("","São Tomé","PR"));
        lista.add(new Cidade("","Sapopema","PR"));
        lista.add(new Cidade("","Sarandi","PR"));
        lista.add(new Cidade("","Saudade do Iguaçu","PR"));
        lista.add(new Cidade("","Sengés","PR"));
        lista.add(new Cidade("","Serranópolis do Iguaçu","PR"));
        lista.add(new Cidade("","Sertaneja","PR"));
        lista.add(new Cidade("","Sertanópolis","PR"));
        lista.add(new Cidade("","Siqueira Campos","PR"));
        lista.add(new Cidade("","Sulina","PR"));
        lista.add(new Cidade("","Tamarana","PR"));
        lista.add(new Cidade("","Tamboara","PR"));
        lista.add(new Cidade("","Tapejara","PR"));
        lista.add(new Cidade("","Tapira","PR"));
        lista.add(new Cidade("","Teixeira Soares","PR"));
        lista.add(new Cidade("","Telêmaco Borba","PR"));
        lista.add(new Cidade("","Terra Boa","PR"));
        lista.add(new Cidade("","Terra Rica","PR"));
        lista.add(new Cidade("","Terra Roxa","PR"));
        lista.add(new Cidade("","Tibagi","PR"));
        lista.add(new Cidade("","Tijucas do Sul","PR"));
        lista.add(new Cidade("","Toledo","PR"));
        lista.add(new Cidade("","Tomazina","PR"));
        lista.add(new Cidade("","Três Barras do Paraná","PR"));
        lista.add(new Cidade("","Tunas do Paraná","PR"));
        lista.add(new Cidade("","Tuneiras do Oeste","PR"));
        lista.add(new Cidade("","Tupãssi","PR"));
        lista.add(new Cidade("","Turvo","PR"));
        lista.add(new Cidade("","Ubiratã","PR"));
        lista.add(new Cidade("","Umuarama","PR"));
        lista.add(new Cidade("","União da Vitória","PR"));
        lista.add(new Cidade("","Uniflor","PR"));
        lista.add(new Cidade("","Uraí","PR"));
        lista.add(new Cidade("","Ventania","PR"));
        lista.add(new Cidade("","Vera Cruz do Oeste","PR"));
        lista.add(new Cidade("","Verê","PR"));
        lista.add(new Cidade("","Vila Alta","PR"));
        lista.add(new Cidade("","Virmond","PR"));
        lista.add(new Cidade("","Vitorino","PR"));
        lista.add(new Cidade("","Wenceslau Braz","PR"));
        lista.add(new Cidade("","Xambrê","PR"));
        return lista;
    }
}
