package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RJ {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("QocuBDDFZy3EuF3fXiQP","Angra dos Reis","RJ"));
        lista.add(new Cidade("Ic859tOSsbpyXFBlwSaM","Aperibé","RJ"));
        lista.add(new Cidade("XYQQx5k1B5bhf6spaM9p","Araruama","RJ"));
        lista.add(new Cidade("ZoCEll7l6aosbBMQ0TCg","Areal","RJ"));
        lista.add(new Cidade("OpgFdBaWi1E6s8X2VfyE","Armação de Búzios","RJ"));
        lista.add(new Cidade("hAipohFyuIkT7t9zzHyX","Arraial do Cabo","RJ"));
        lista.add(new Cidade("atdBs73y97N9IoA23y6q","Barra do Piraí","RJ"));
        lista.add(new Cidade("MMNykwLnUZbxdPf4XJD0","Barra Mansa","RJ"));
        lista.add(new Cidade("TdorWlmq7L5cnfSvvu1u","Belford Roxo","RJ"));
        lista.add(new Cidade("KU18OgyjVcBdks32GLnG","Bom Jardim","RJ"));
        lista.add(new Cidade("8VEo234xVZkOKxk9zhGE","Bom Jesus do Itabapoana","RJ"));
        lista.add(new Cidade("QcJKpN5qPvp7ZARScqhy","Cabo Frio","RJ"));
        lista.add(new Cidade("ZrWK8XeQXEgDpe9myImP","Cachoeiras de Macacu","RJ"));
        lista.add(new Cidade("BjkAcWjw4EecTFpUGaQQ","Cambuci","RJ"));
        lista.add(new Cidade("47A4ZPeymdGXb2ycFIrK","Campos dos Goytacazes","RJ"));
        lista.add(new Cidade("oWKYKe3QMCLPGD4bq6sj","Cantagalo","RJ"));
        lista.add(new Cidade("b3lcuTdyUi2zDuPw8cN6","Carapebus","RJ"));
        lista.add(new Cidade("u98GwYfjYxr0DGMyVGhH","Cardoso Moreira","RJ"));
        lista.add(new Cidade("S24gyLKRTlr8OoJBN6X5","Carmo","RJ"));
        lista.add(new Cidade("diqA41y5f6uKhpevf6sg","Casimiro de Abreu","RJ"));
        lista.add(new Cidade("weFIti90z3MBU1yKboVZ","Comendador Levy Gasparian","RJ"));
        lista.add(new Cidade("mhwm6yBtxtZ83AsxwIhk","Conceição de Macabu","RJ"));
        lista.add(new Cidade("RTDIKxAEE1BwZjD0EZHO","Cordeiro","RJ"));
        lista.add(new Cidade("aAYOpw4LBO43fWOihZUo","Duas Barras","RJ"));
        lista.add(new Cidade("Nhs2ax3jGCOh6uA1xF13","Duque de Caxias","RJ"));
        lista.add(new Cidade("0qw5Q3nz3aVbC0mIlSEV","Engenheiro Paulo de Frontin","RJ"));
        lista.add(new Cidade("NJmEnCrekQyZ0g7xqioS","Guapimirim","RJ"));
        lista.add(new Cidade("FiWdLDyeIxEzNtf2jvym","Iguaba Grande","RJ"));
        lista.add(new Cidade("LJjTTWTmMdkjHlb1RLMN","Itaboraí","RJ"));
        lista.add(new Cidade("bQeCHPmPDd2cqLm2ooAB","Itaguaí","RJ"));
        lista.add(new Cidade("xMXTwvJiaGkbJlDD3twx","Italva","RJ"));
        lista.add(new Cidade("nyPx0oYaklfXJWX4TeXy","Itaocara","RJ"));
        lista.add(new Cidade("NWpPymJCpJD609omTSJy","Itaperuna","RJ"));
        lista.add(new Cidade("bXZeig9mWSqiLrZv71tk","Itatiaia","RJ"));
        lista.add(new Cidade("r0As5hIuVXB1Y7y5d0Th","Japeri","RJ"));
        lista.add(new Cidade("mgwYjwc9JApPcbO7Jorq","Laje do Muriaé","RJ"));
        lista.add(new Cidade("mEvrV4lw03Dz4En7SEvF","Macaé","RJ"));
        lista.add(new Cidade("gGikmyE7LWQy3CfYEOKO","Macuco","RJ"));
        lista.add(new Cidade("RLKC9deki1I7HLBaHT6U","Magé","RJ"));
        lista.add(new Cidade("7bkHKnROM8Kbu4somepG","Mangaratiba","RJ"));
        lista.add(new Cidade("e9Z52whaFIUamJjfpJnT","Maricá","RJ"));
        lista.add(new Cidade("6sqCNffggZUsscHxF2m1","Mendes","RJ"));
        lista.add(new Cidade("2G0DJu8RAj734SPZ6WO0","Mesquita","RJ"));
        lista.add(new Cidade("mrzJYF4J75RGDgvnrzGV","Miguel Pereira","RJ"));
        lista.add(new Cidade("h0z452gPfO5vAMLGnXsx","Miracema","RJ"));
        lista.add(new Cidade("X1d2VQVhBXwitGDcec32","Natividade","RJ"));
        lista.add(new Cidade("Z6KhTELnYkNrtnaTgIQB","Nilópolis","RJ"));
        lista.add(new Cidade("Nm9rxf4NeCOF8quew7W9","Niterói","RJ"));
        lista.add(new Cidade("XacvGcx6hbTg0sHBFcFA","Nova Friburgo","RJ"));
        lista.add(new Cidade("mnEXIwlbp52i3cgfdgDZ","Nova Iguaçu","RJ"));
        lista.add(new Cidade("JwQPWLu1OBfGzg2Hz0x4","Paracambi","RJ"));
        lista.add(new Cidade("p2IzaLgHL8l7O9VGrDBA","Paraíba do Sul","RJ"));
        lista.add(new Cidade("jsB9l2h4VdfuEeR2Bfew","Parati","RJ"));
        lista.add(new Cidade("ff5yPabIXEnbguUgP58v","Paty do Alferes","RJ"));
        lista.add(new Cidade("Jdtkchjq0ynMexthfbOU","Petrópolis","RJ"));
        lista.add(new Cidade("qTdXaeHrIbLrvQn2GHb3","Pinheiral","RJ"));
        lista.add(new Cidade("M4kW2lCo272oTymByc97","Piraí","RJ"));
        lista.add(new Cidade("zrR5BWJcZ9mwsQ7xUTH4","Porciúncula","RJ"));
        lista.add(new Cidade("mfqgO8Ga0SV05rrubfZy","Porto Real","RJ"));
        lista.add(new Cidade("xvvLQ70jjbjfVNS66oPH","Quatis","RJ"));
        lista.add(new Cidade("gr9TSA70wFaEEcYvsViL","Queimados","RJ"));
        lista.add(new Cidade("KdL0zNEcyIe1c5Bez1JF","Quissamã","RJ"));
        lista.add(new Cidade("SVVYMrDjpCnC0p7mxPmE","Resende","RJ"));
        lista.add(new Cidade("E57JYX65RsCUYpaQOQ0k","Rio Bonito","RJ"));
        lista.add(new Cidade("8xt8pRu43SzGrCS7BBkQ","Rio Claro","RJ"));
        lista.add(new Cidade("BOIBfvPI1dflHz2BwmRH","Rio das Flores","RJ"));
        lista.add(new Cidade("Rz2oCll81b4tsrHNQus4","Rio das Ostras","RJ"));
        lista.add(new Cidade("bvdJZo2l1quwnwwaQmRP","Rio de Janeiro","RJ"));
        lista.add(new Cidade("UIsoytNfwiR94Ld5Nyiw","Santa Maria Madalena","RJ"));
        lista.add(new Cidade("Mcu0uMFzgELZsEQ3SfK3","Santo Antônio de Pádua","RJ"));
        lista.add(new Cidade("Rz76h3d41zi0hzsOk30k","São Fidélis","RJ"));
        lista.add(new Cidade("JcqEfyqo6aIG2FstM02R","São Francisco de Itabapoana","RJ"));
        lista.add(new Cidade("iCGToRu5qNyjYQ4Huzgj","São Gonçalo","RJ"));
        lista.add(new Cidade("sDza34erPeC288vuMNH7","São João da Barra","RJ"));
        lista.add(new Cidade("LR9NHC60ZF3uKm3EqyaK","São João de Meriti","RJ"));
        lista.add(new Cidade("xOQe8FjY3wyFgXdIJpX6","São José de Ubá","RJ"));
        lista.add(new Cidade("ASw4kxqZvZIgkZ7v5lVj","São José do Vale do Rio Preto","RJ"));
        lista.add(new Cidade("wgFtEUUIt4hATE1HHAuY","São Pedro da Aldeia","RJ"));
        lista.add(new Cidade("FODCjvGuGTrscx761iQw","São Sebastião do Alto","RJ"));
        lista.add(new Cidade("ULLBG22Q57Hwc8ba2dUb","Sapucaia","RJ"));
        lista.add(new Cidade("ph5P7ahEczsEpnEy85Fv","Saquarema","RJ"));
        lista.add(new Cidade("J6UofKCvQtDVBROPWgag","Seropédica","RJ"));
        lista.add(new Cidade("bsQxOpohnxU10EDDZL9T","Silva Jardim","RJ"));
        lista.add(new Cidade("ex2mSU02wnM1OyR72dw4","Sumidouro","RJ"));
        lista.add(new Cidade("tCicwXchZIismwxLcjnR","Tanguá","RJ"));
        lista.add(new Cidade("aobQpxry8DtoSeTdY6Sq","Teresópolis","RJ"));
        lista.add(new Cidade("ItDKlhD6nQbqHXPTrzaK","Trajano de Morais","RJ"));
        lista.add(new Cidade("emCbAcShNsqDSHmpup7S","Três Rios","RJ"));
        lista.add(new Cidade("3rC7e0RAIJbJxtffq5pc","Valença","RJ"));
        lista.add(new Cidade("wjsywmVnUgn4Rdp84B9M","Varre-Sai","RJ"));
        lista.add(new Cidade("IJ8LdmWP8bO6C4frqizY","Vassouras","RJ"));
        lista.add(new Cidade("CKQpNaVvBivW1C5pf2bv","Volta Redonda","RJ"));

        return lista;
    }
}
