package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RJ {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Angra dos Reis","RJ"));
        lista.add(new Cidade("","Aperibé","RJ"));
        lista.add(new Cidade("","Araruama","RJ"));
        lista.add(new Cidade("","Areal","RJ"));
        lista.add(new Cidade("","Armação de Búzios","RJ"));
        lista.add(new Cidade("","Arraial do Cabo","RJ"));
        lista.add(new Cidade("","Barra do Piraí","RJ"));
        lista.add(new Cidade("","Barra Mansa","RJ"));
        lista.add(new Cidade("","Belford Roxo","RJ"));
        lista.add(new Cidade("","Bom Jardim","RJ"));
        lista.add(new Cidade("","Bom Jesus do Itabapoana","RJ"));
        lista.add(new Cidade("","Cabo Frio","RJ"));
        lista.add(new Cidade("","Cachoeiras de Macacu","RJ"));
        lista.add(new Cidade("","Cambuci","RJ"));
        lista.add(new Cidade("","Campos dos Goytacazes","RJ"));
        lista.add(new Cidade("","Cantagalo","RJ"));
        lista.add(new Cidade("","Carapebus","RJ"));
        lista.add(new Cidade("","Cardoso Moreira","RJ"));
        lista.add(new Cidade("","Carmo","RJ"));
        lista.add(new Cidade("","Casimiro de Abreu","RJ"));
        lista.add(new Cidade("","Comendador Levy Gasparian","RJ"));
        lista.add(new Cidade("","Conceição de Macabu","RJ"));
        lista.add(new Cidade("","Cordeiro","RJ"));
        lista.add(new Cidade("","Duas Barras","RJ"));
        lista.add(new Cidade("","Duque de Caxias","RJ"));
        lista.add(new Cidade("","Engenheiro Paulo de Frontin","RJ"));
        lista.add(new Cidade("","Guapimirim","RJ"));
        lista.add(new Cidade("","Iguaba Grande","RJ"));
        lista.add(new Cidade("","Itaboraí","RJ"));
        lista.add(new Cidade("","Itaguaí","RJ"));
        lista.add(new Cidade("","Italva","RJ"));
        lista.add(new Cidade("","Itaocara","RJ"));
        lista.add(new Cidade("","Itaperuna","RJ"));
        lista.add(new Cidade("","Itatiaia","RJ"));
        lista.add(new Cidade("","Japeri","RJ"));
        lista.add(new Cidade("","Laje do Muriaé","RJ"));
        lista.add(new Cidade("","Macaé","RJ"));
        lista.add(new Cidade("","Macuco","RJ"));
        lista.add(new Cidade("","Magé","RJ"));
        lista.add(new Cidade("","Mangaratiba","RJ"));
        lista.add(new Cidade("","Maricá","RJ"));
        lista.add(new Cidade("","Mendes","RJ"));
        lista.add(new Cidade("","Mesquita","RJ"));
        lista.add(new Cidade("","Miguel Pereira","RJ"));
        lista.add(new Cidade("","Miracema","RJ"));
        lista.add(new Cidade("","Natividade","RJ"));
        lista.add(new Cidade("","Nilópolis","RJ"));
        lista.add(new Cidade("","Niterói","RJ"));
        lista.add(new Cidade("","Nova Friburgo","RJ"));
        lista.add(new Cidade("","Nova Iguaçu","RJ"));
        lista.add(new Cidade("","Paracambi","RJ"));
        lista.add(new Cidade("","Paraíba do Sul","RJ"));
        lista.add(new Cidade("","Parati","RJ"));
        lista.add(new Cidade("","Paty do Alferes","RJ"));
        lista.add(new Cidade("","Petrópolis","RJ"));
        lista.add(new Cidade("","Pinheiral","RJ"));
        lista.add(new Cidade("","Piraí","RJ"));
        lista.add(new Cidade("","Porciúncula","RJ"));
        lista.add(new Cidade("","Porto Real","RJ"));
        lista.add(new Cidade("","Quatis","RJ"));
        lista.add(new Cidade("","Queimados","RJ"));
        lista.add(new Cidade("","Quissamã","RJ"));
        lista.add(new Cidade("","Resende","RJ"));
        lista.add(new Cidade("","Rio Bonito","RJ"));
        lista.add(new Cidade("","Rio Claro","RJ"));
        lista.add(new Cidade("","Rio das Flores","RJ"));
        lista.add(new Cidade("","Rio das Ostras","RJ"));
        lista.add(new Cidade("","Rio de Janeiro","RJ"));
        lista.add(new Cidade("","Santa Maria Madalena","RJ"));
        lista.add(new Cidade("","Santo Antônio de Pádua","RJ"));
        lista.add(new Cidade("","São Fidélis","RJ"));
        lista.add(new Cidade("","São Francisco de Itabapoana","RJ"));
        lista.add(new Cidade("","São Gonçalo","RJ"));
        lista.add(new Cidade("","São João da Barra","RJ"));
        lista.add(new Cidade("","São João de Meriti","RJ"));
        lista.add(new Cidade("","São José de Ubá","RJ"));
        lista.add(new Cidade("","São José do Vale do Rio Preto","RJ"));
        lista.add(new Cidade("","São Pedro da Aldeia","RJ"));
        lista.add(new Cidade("","São Sebastião do Alto","RJ"));
        lista.add(new Cidade("","Sapucaia","RJ"));
        lista.add(new Cidade("","Saquarema","RJ"));
        lista.add(new Cidade("","Seropédica","RJ"));
        lista.add(new Cidade("","Silva Jardim","RJ"));
        lista.add(new Cidade("","Sumidouro","RJ"));
        lista.add(new Cidade("","Tanguá","RJ"));
        lista.add(new Cidade("","Teresópolis","RJ"));
        lista.add(new Cidade("","Trajano de Morais","RJ"));
        lista.add(new Cidade("","Três Rios","RJ"));
        lista.add(new Cidade("","Valença","RJ"));
        lista.add(new Cidade("","Varre-Sai","RJ"));
        lista.add(new Cidade("","Vassouras","RJ"));
        lista.add(new Cidade("","Volta Redonda","RJ"));
        return lista;
    }
}
