package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RJ {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("QocuBDDFZy3EuF3fXiQP","Angra dos Reis","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Ic859tOSsbpyXFBlwSaM","Aperibé","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("XYQQx5k1B5bhf6spaM9p","Araruama","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ZoCEll7l6aosbBMQ0TCg","Areal","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("OpgFdBaWi1E6s8X2VfyE","Armação de Búzios","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("hAipohFyuIkT7t9zzHyX","Arraial do Cabo","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("atdBs73y97N9IoA23y6q","Barra do Piraí","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("MMNykwLnUZbxdPf4XJD0","Barra Mansa","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("TdorWlmq7L5cnfSvvu1u","Belford Roxo","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("KU18OgyjVcBdks32GLnG","Bom Jardim","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("8VEo234xVZkOKxk9zhGE","Bom Jesus do Itabapoana","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("QcJKpN5qPvp7ZARScqhy","Cabo Frio","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ZrWK8XeQXEgDpe9myImP","Cachoeiras de Macacu","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("BjkAcWjw4EecTFpUGaQQ","Cambuci","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("47A4ZPeymdGXb2ycFIrK","Campos dos Goytacazes","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("oWKYKe3QMCLPGD4bq6sj","Cantagalo","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("b3lcuTdyUi2zDuPw8cN6","Carapebus","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("u98GwYfjYxr0DGMyVGhH","Cardoso Moreira","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("S24gyLKRTlr8OoJBN6X5","Carmo","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("diqA41y5f6uKhpevf6sg","Casimiro de Abreu","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("weFIti90z3MBU1yKboVZ","Comendador Levy Gasparian","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("mhwm6yBtxtZ83AsxwIhk","Conceição de Macabu","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("RTDIKxAEE1BwZjD0EZHO","Cordeiro","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("aAYOpw4LBO43fWOihZUo","Duas Barras","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Nhs2ax3jGCOh6uA1xF13","Duque de Caxias","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("0qw5Q3nz3aVbC0mIlSEV","Engenheiro Paulo de Frontin","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("NJmEnCrekQyZ0g7xqioS","Guapimirim","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("FiWdLDyeIxEzNtf2jvym","Iguaba Grande","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("LJjTTWTmMdkjHlb1RLMN","Itaboraí","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("bQeCHPmPDd2cqLm2ooAB","Itaguaí","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("xMXTwvJiaGkbJlDD3twx","Italva","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("nyPx0oYaklfXJWX4TeXy","Itaocara","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("NWpPymJCpJD609omTSJy","Itaperuna","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("bXZeig9mWSqiLrZv71tk","Itatiaia","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("r0As5hIuVXB1Y7y5d0Th","Japeri","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("mgwYjwc9JApPcbO7Jorq","Laje do Muriaé","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("mEvrV4lw03Dz4En7SEvF","Macaé","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("gGikmyE7LWQy3CfYEOKO","Macuco","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("RLKC9deki1I7HLBaHT6U","Magé","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("7bkHKnROM8Kbu4somepG","Mangaratiba","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("e9Z52whaFIUamJjfpJnT","Maricá","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("6sqCNffggZUsscHxF2m1","Mendes","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("2G0DJu8RAj734SPZ6WO0","Mesquita","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("mrzJYF4J75RGDgvnrzGV","Miguel Pereira","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("h0z452gPfO5vAMLGnXsx","Miracema","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("X1d2VQVhBXwitGDcec32","Natividade","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Z6KhTELnYkNrtnaTgIQB","Nilópolis","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Nm9rxf4NeCOF8quew7W9","Niterói","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("XacvGcx6hbTg0sHBFcFA","Nova Friburgo","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("mnEXIwlbp52i3cgfdgDZ","Nova Iguaçu","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("JwQPWLu1OBfGzg2Hz0x4","Paracambi","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("p2IzaLgHL8l7O9VGrDBA","Paraíba do Sul","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("jsB9l2h4VdfuEeR2Bfew","Parati","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ff5yPabIXEnbguUgP58v","Paty do Alferes","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Jdtkchjq0ynMexthfbOU","Petrópolis","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("qTdXaeHrIbLrvQn2GHb3","Pinheiral","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("M4kW2lCo272oTymByc97","Piraí","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("zrR5BWJcZ9mwsQ7xUTH4","Porciúncula","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("mfqgO8Ga0SV05rrubfZy","Porto Real","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("xvvLQ70jjbjfVNS66oPH","Quatis","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("gr9TSA70wFaEEcYvsViL","Queimados","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("KdL0zNEcyIe1c5Bez1JF","Quissamã","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("SVVYMrDjpCnC0p7mxPmE","Resende","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("E57JYX65RsCUYpaQOQ0k","Rio Bonito","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("8xt8pRu43SzGrCS7BBkQ","Rio Claro","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("BOIBfvPI1dflHz2BwmRH","Rio das Flores","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Rz2oCll81b4tsrHNQus4","Rio das Ostras","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("bvdJZo2l1quwnwwaQmRP","Rio de Janeiro","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("UIsoytNfwiR94Ld5Nyiw","Santa Maria Madalena","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Mcu0uMFzgELZsEQ3SfK3","Santo Antônio de Pádua","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("Rz76h3d41zi0hzsOk30k","São Fidélis","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("JcqEfyqo6aIG2FstM02R","São Francisco de Itabapoana","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("iCGToRu5qNyjYQ4Huzgj","São Gonçalo","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("sDza34erPeC288vuMNH7","São João da Barra","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("LR9NHC60ZF3uKm3EqyaK","São João de Meriti","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("xOQe8FjY3wyFgXdIJpX6","São José de Ubá","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ASw4kxqZvZIgkZ7v5lVj","São José do Vale do Rio Preto","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("wgFtEUUIt4hATE1HHAuY","São Pedro da Aldeia","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("FODCjvGuGTrscx761iQw","São Sebastião do Alto","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ULLBG22Q57Hwc8ba2dUb","Sapucaia","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ph5P7ahEczsEpnEy85Fv","Saquarema","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("J6UofKCvQtDVBROPWgag","Seropédica","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("bsQxOpohnxU10EDDZL9T","Silva Jardim","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ex2mSU02wnM1OyR72dw4","Sumidouro","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("tCicwXchZIismwxLcjnR","Tanguá","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("aobQpxry8DtoSeTdY6Sq","Teresópolis","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("ItDKlhD6nQbqHXPTrzaK","Trajano de Morais","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("emCbAcShNsqDSHmpup7S","Três Rios","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("3rC7e0RAIJbJxtffq5pc","Valença","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("wjsywmVnUgn4Rdp84B9M","Varre-Sai","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("IJ8LdmWP8bO6C4frqizY","Vassouras","piIRsvy9nHTMzBq3lRU0", "RJ"));
        lista.add(new Cidade("CKQpNaVvBivW1C5pf2bv","Volta Redonda","piIRsvy9nHTMzBq3lRU0", "RJ"));

        return lista;
    }
}
