package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RN {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Acari","RN"));
        lista.add(new Cidade("","Açu","RN"));
        lista.add(new Cidade("","Afonso Bezerra","RN"));
        lista.add(new Cidade("","Água Nova","RN"));
        lista.add(new Cidade("","Alexandria","RN"));
        lista.add(new Cidade("","Almino Afonso","RN"));
        lista.add(new Cidade("","Alto do Rodrigues","RN"));
        lista.add(new Cidade("","Angicos","RN"));
        lista.add(new Cidade("","Antônio Martins","RN"));
        lista.add(new Cidade("","Apodi","RN"));
        lista.add(new Cidade("","Areia Branca","RN"));
        lista.add(new Cidade("","Arês","RN"));
        lista.add(new Cidade("","Augusto Severo","RN"));
        lista.add(new Cidade("","Baía Formosa","RN"));
        lista.add(new Cidade("","Baraúna","RN"));
        lista.add(new Cidade("","Barcelona","RN"));
        lista.add(new Cidade("","Bento Fernandes","RN"));
        lista.add(new Cidade("","Bodó","RN"));
        lista.add(new Cidade("","Bom Jesus","RN"));
        lista.add(new Cidade("","Brejinho","RN"));
        lista.add(new Cidade("","Caiçara do Norte","RN"));
        lista.add(new Cidade("","Caiçara do Rio do Vento","RN"));
        lista.add(new Cidade("","Caicó","RN"));
        lista.add(new Cidade("","Campo Redondo","RN"));
        lista.add(new Cidade("","Canguaretama","RN"));
        lista.add(new Cidade("","Caraúbas","RN"));
        lista.add(new Cidade("","Carnaúba dos Dantas","RN"));
        lista.add(new Cidade("","Carnaubais","RN"));
        lista.add(new Cidade("","Ceará-Mirim","RN"));
        lista.add(new Cidade("","Cerro Corá","RN"));
        lista.add(new Cidade("","Coronel Ezequiel","RN"));
        lista.add(new Cidade("","Coronel João Pessoa","RN"));
        lista.add(new Cidade("","Cruzeta","RN"));
        lista.add(new Cidade("","Currais Novos","RN"));
        lista.add(new Cidade("","Doutor Severiano","RN"));
        lista.add(new Cidade("","Encanto","RN"));
        lista.add(new Cidade("","Equador","RN"));
        lista.add(new Cidade("","Espírito Santo","RN"));
        lista.add(new Cidade("","Extremoz","RN"));
        lista.add(new Cidade("","Felipe Guerra","RN"));
        lista.add(new Cidade("","Fernando Pedroza","RN"));
        lista.add(new Cidade("","Florânia","RN"));
        lista.add(new Cidade("","Francisco Dantas","RN"));
        lista.add(new Cidade("","Frutuoso Gomes","RN"));
        lista.add(new Cidade("","Galinhos","RN"));
        lista.add(new Cidade("","Goianinha","RN"));
        lista.add(new Cidade("","Governador Dix-Sept Rosado","RN"));
        lista.add(new Cidade("","Grossos","RN"));
        lista.add(new Cidade("","Guamaré","RN"));
        lista.add(new Cidade("","Ielmo Marinho","RN"));
        lista.add(new Cidade("","Ipanguaçu","RN"));
        lista.add(new Cidade("","Ipueira","RN"));
        lista.add(new Cidade("","Itajá","RN"));
        lista.add(new Cidade("","Itaú","RN"));
        lista.add(new Cidade("","Jaçanã","RN"));
        lista.add(new Cidade("","Jandaíra","RN"));
        lista.add(new Cidade("","Janduís","RN"));
        lista.add(new Cidade("","Januário Cicco","RN"));
        lista.add(new Cidade("","Japi","RN"));
        lista.add(new Cidade("","Jardim de Angicos","RN"));
        lista.add(new Cidade("","Jardim de Piranhas","RN"));
        lista.add(new Cidade("","Jardim do Seridó","RN"));
        lista.add(new Cidade("","João Câmara","RN"));
        lista.add(new Cidade("","João Dias","RN"));
        lista.add(new Cidade("","José da Penha","RN"));
        lista.add(new Cidade("","Jucurutu","RN"));
        lista.add(new Cidade("","Jundiá","RN"));
        lista.add(new Cidade("","Lagoa d'Anta","RN"));
        lista.add(new Cidade("","Lagoa de Pedras","RN"));
        lista.add(new Cidade("","Lagoa de Velhos","RN"));
        lista.add(new Cidade("","Lagoa Nova","RN"));
        lista.add(new Cidade("","Lagoa Salgada","RN"));
        lista.add(new Cidade("","Lajes","RN"));
        lista.add(new Cidade("","Lajes Pintadas","RN"));
        lista.add(new Cidade("","Lucrécia","RN"));
        lista.add(new Cidade("","Luís Gomes","RN"));
        lista.add(new Cidade("","Macaíba","RN"));
        lista.add(new Cidade("","Macau","RN"));
        lista.add(new Cidade("","Major Sales","RN"));
        lista.add(new Cidade("","Marcelino Vieira","RN"));
        lista.add(new Cidade("","Martins","RN"));
        lista.add(new Cidade("","Maxaranguape","RN"));
        lista.add(new Cidade("","Messias Targino","RN"));
        lista.add(new Cidade("","Montanhas","RN"));
        lista.add(new Cidade("","Monte Alegre","RN"));
        lista.add(new Cidade("","Monte das Gameleiras","RN"));
        lista.add(new Cidade("","Mossoró","RN"));
        lista.add(new Cidade("","Natal","RN"));
        lista.add(new Cidade("","Nísia Floresta","RN"));
        lista.add(new Cidade("","Nova Cruz","RN"));
        lista.add(new Cidade("","Olho-d'Água do Borges","RN"));
        lista.add(new Cidade("","Ouro Branco","RN"));
        lista.add(new Cidade("","Paraná","RN"));
        lista.add(new Cidade("","Paraú","RN"));
        lista.add(new Cidade("","Parazinho","RN"));
        lista.add(new Cidade("","Parelhas","RN"));
        lista.add(new Cidade("","Parnamirim","RN"));
        lista.add(new Cidade("","Passa e Fica","RN"));
        lista.add(new Cidade("","Passagem","RN"));
        lista.add(new Cidade("","Patu","RN"));
        lista.add(new Cidade("","Pau dos Ferros","RN"));
        lista.add(new Cidade("","Pedra Grande","RN"));
        lista.add(new Cidade("","Pedra Preta","RN"));
        lista.add(new Cidade("","Pedro Avelino","RN"));
        lista.add(new Cidade("","Pedro Velho","RN"));
        lista.add(new Cidade("","Pendências","RN"));
        lista.add(new Cidade("","Pilões","RN"));
        lista.add(new Cidade("","Poço Branco","RN"));
        lista.add(new Cidade("","Portalegre","RN"));
        lista.add(new Cidade("","Porto do Mangue","RN"));
        lista.add(new Cidade("","Presidente Juscelino","RN"));
        lista.add(new Cidade("","Pureza","RN"));
        lista.add(new Cidade("","Rafael Fernandes","RN"));
        lista.add(new Cidade("","Rafael Godeiro","RN"));
        lista.add(new Cidade("","Riacho da Cruz","RN"));
        lista.add(new Cidade("","Riacho de Santana","RN"));
        lista.add(new Cidade("","Riachuelo","RN"));
        lista.add(new Cidade("","Rio do Fogo","RN"));
        lista.add(new Cidade("","Rodolfo Fernandes","RN"));
        lista.add(new Cidade("","Ruy Barbosa","RN"));
        lista.add(new Cidade("","Santa Cruz","RN"));
        lista.add(new Cidade("","Santa Maria","RN"));
        lista.add(new Cidade("","Santana do Matos","RN"));
        lista.add(new Cidade("","Santana do Seridó","RN"));
        lista.add(new Cidade("","Santo Antônio","RN"));
        lista.add(new Cidade("","São Bento do Norte","RN"));
        lista.add(new Cidade("","São Bento do Trairí","RN"));
        lista.add(new Cidade("","São Fernando","RN"));
        lista.add(new Cidade("","São Francisco do Oeste","RN"));
        lista.add(new Cidade("","São Gonçalo do Amarante","RN"));
        lista.add(new Cidade("","São João do Sabugi","RN"));
        lista.add(new Cidade("","São José de Mipibu","RN"));
        lista.add(new Cidade("","São José do Campestre","RN"));
        lista.add(new Cidade("","São José do Seridó","RN"));
        lista.add(new Cidade("","São Miguel","RN"));
        lista.add(new Cidade("","São Miguel de Touros","RN"));
        lista.add(new Cidade("","São Paulo do Potengi","RN"));
        lista.add(new Cidade("","São Pedro","RN"));
        lista.add(new Cidade("","São Rafael","RN"));
        lista.add(new Cidade("","São Tomé","RN"));
        lista.add(new Cidade("","São Vicente","RN"));
        lista.add(new Cidade("","Senador Elói de Souza","RN"));
        lista.add(new Cidade("","Senador Georgino Avelino","RN"));
        lista.add(new Cidade("","Serra de São Bento","RN"));
        lista.add(new Cidade("","Serra do Mel","RN"));
        lista.add(new Cidade("","Serra Negra do Norte","RN"));
        lista.add(new Cidade("","Serrinha","RN"));
        lista.add(new Cidade("","Serrinha dos Pintos","RN"));
        lista.add(new Cidade("","Severiano Melo","RN"));
        lista.add(new Cidade("","Sítio Novo","RN"));
        lista.add(new Cidade("","Taboleiro Grande","RN"));
        lista.add(new Cidade("","Taipu","RN"));
        lista.add(new Cidade("","Tangará","RN"));
        lista.add(new Cidade("","Tenente Ananias","RN"));
        lista.add(new Cidade("","Tenente Laurentino Cruz","RN"));
        lista.add(new Cidade("","Tibau","RN"));
        lista.add(new Cidade("","Tibau do Sul","RN"));
        lista.add(new Cidade("","Timbaúba dos Batistas","RN"));
        lista.add(new Cidade("","Touros","RN"));
        lista.add(new Cidade("","Triunfo Potiguar","RN"));
        lista.add(new Cidade("","Umarizal","RN"));
        lista.add(new Cidade("","Upanema","RN"));
        lista.add(new Cidade("","Várzea","RN"));
        lista.add(new Cidade("","Venha-Ver","RN"));
        lista.add(new Cidade("","Vera Cruz","RN"));
        lista.add(new Cidade("","Viçosa","RN"));
        lista.add(new Cidade("","Vila Flor","RN"));
        return lista;
    }
}
