package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RN {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("1vm9yfK526Z55enkhLug","Acari","RN"));
        lista.add(new Cidade("G12ZJkqfzEdaknPvT8gK","Açu","RN"));
        lista.add(new Cidade("hWys2TBOZLo96BtWFPKq","Afonso Bezerra","RN"));
        lista.add(new Cidade("IWUIoDRwZbOjNXnqdcYI","Água Nova","RN"));
        lista.add(new Cidade("DcPMZVlnlQ5m7asBu6c2","Alexandria","RN"));
        lista.add(new Cidade("3qG73jjd151ci0zT0c5Q","Almino Afonso","RN"));
        lista.add(new Cidade("CQ9TIvQU4yuiq3iBQyLd","Alto do Rodrigues","RN"));
        lista.add(new Cidade("jIvzO9Xw1UxKnzbiYMpF","Angicos","RN"));
        lista.add(new Cidade("vK8t3fLgoCURbMobLqjz","Antônio Martins","RN"));
        lista.add(new Cidade("KlNsTft1ipyEFQRP9jAn","Apodi","RN"));
        lista.add(new Cidade("d3sNkC3NTLj9w2kf9xxZ","Areia Branca","RN"));
        lista.add(new Cidade("jZD8EqlnksKduOZ2a0lT","Arês","RN"));
        lista.add(new Cidade("umcOAfv9Ht6raNnmB9wY","Augusto Severo","RN"));
        lista.add(new Cidade("bSmRHigBuUymchI3GBlh","Baía Formosa","RN"));
        lista.add(new Cidade("aPkN3L5xII6CP9WQkmtS","Baraúna","RN"));
        lista.add(new Cidade("4J5sWqSUsZvsICfDvtNW","Barcelona","RN"));
        lista.add(new Cidade("QpbWZ2X1R06V2SpuAZWe","Bento Fernandes","RN"));
        lista.add(new Cidade("szTPrlQFVq6Hw20Qo3cx","Bodó","RN"));
        lista.add(new Cidade("g562lhUu6x2xLIUoIk5Z","Bom Jesus","RN"));
        lista.add(new Cidade("W7zn4m0UmtZXD67FJ5Fx","Brejinho","RN"));
        lista.add(new Cidade("WgudY6b5i9Af5SFGiP2a","Caiçara do Norte","RN"));
        lista.add(new Cidade("cBTouGh0KRF0Sw04Jeaz","Caiçara do Rio do Vento","RN"));
        lista.add(new Cidade("lFzBHS27zK8ULFU8GsBV","Caicó","RN"));
        lista.add(new Cidade("LvhYvcnXcCmO8S7Dh5hq","Campo Redondo","RN"));
        lista.add(new Cidade("VTMcGCFMf9dy9bPUxc6B","Canguaretama","RN"));
        lista.add(new Cidade("yFW4tQ6hhJVU0g8YGMDa","Caraúbas","RN"));
        lista.add(new Cidade("R2RJS8ZRYw38T6epyLiN","Carnaúba dos Dantas","RN"));
        lista.add(new Cidade("O2yHmqnmvJYPTu69EH5w","Carnaubais","RN"));
        lista.add(new Cidade("GPH4hTbraj6BdCm2dyiG","Ceará-Mirim","RN"));
        lista.add(new Cidade("u6kxtW0fKo24zs7uuX2V","Cerro Corá","RN"));
        lista.add(new Cidade("duUiebIpV0IGm251vOJ9","Coronel Ezequiel","RN"));
        lista.add(new Cidade("I2S8J4mfLepJ5O5UOTY1","Coronel João Pessoa","RN"));
        lista.add(new Cidade("hYHgCqVUFvcqkiZarCGt","Cruzeta","RN"));
        lista.add(new Cidade("qqRBKpz81aCtlZN4f4SR","Currais Novos","RN"));
        lista.add(new Cidade("NlzkPgO7ZgfxSm7SWfyW","Doutor Severiano","RN"));
        lista.add(new Cidade("niIihZC8aKTlBcaxfuMv","Encanto","RN"));
        lista.add(new Cidade("hEDqMVpO7ood5MY7N6yL","Equador","RN"));
        lista.add(new Cidade("lSAR3djQZDoNik9Gryau","Espírito Santo","RN"));
        lista.add(new Cidade("vSVFsOU3th6fTIDCvNll","Extremoz","RN"));
        lista.add(new Cidade("b8BP7OocnvPuhIGyUlY5","Felipe Guerra","RN"));
        lista.add(new Cidade("0vfNf2vve4qHixBeArxi","Fernando Pedroza","RN"));
        lista.add(new Cidade("dkKPJsDSWUa8yCkXuhVZ","Florânia","RN"));
        lista.add(new Cidade("ZG2o9naGCd6TPhCb5Cv5","Francisco Dantas","RN"));
        lista.add(new Cidade("Jv8r7QrkbB9bdCCEiE7X","Frutuoso Gomes","RN"));
        lista.add(new Cidade("HO0v74wd8Tg7UWz7vMws","Galinhos","RN"));
        lista.add(new Cidade("Yjc26euXiryq9RaLxp7G","Goianinha","RN"));
        lista.add(new Cidade("cBY8qQiDiGVn8kp8JsaT","Governador Dix-Sept Rosado","RN"));
        lista.add(new Cidade("8tLjXNMxDz1L2MAsiwHN","Grossos","RN"));
        lista.add(new Cidade("6odtkulKwVN0naUS7koX","Guamaré","RN"));
        lista.add(new Cidade("gW8zPyKNIgviqHp2n8YK","Ielmo Marinho","RN"));
        lista.add(new Cidade("xYH8eG0CCsCX4FElfnKl","Ipanguaçu","RN"));
        lista.add(new Cidade("jbmmWSe0wEh1eB4d4ca8","Ipueira","RN"));
        lista.add(new Cidade("VY4HcxoWm3Eu0gtKeHWT","Itajá","RN"));
        lista.add(new Cidade("6qjjzcZEAdtunMRVvU27","Itaú","RN"));
        lista.add(new Cidade("ztVAYXBaWY9PPuiJ2sYL","Jaçanã","RN"));
        lista.add(new Cidade("AHB8BKUDyOyz6TrmqiX7","Jandaíra","RN"));
        lista.add(new Cidade("YGzA2CJSohxltPTPRXBZ","Janduís","RN"));
        lista.add(new Cidade("CIVVZlgCXyn0Pvfq6ylv","Januário Cicco","RN"));
        lista.add(new Cidade("D91gGJ4zEwDJvhk2q6DP","Japi","RN"));
        lista.add(new Cidade("joCKfk1LJ7K6TVMLp0SC","Jardim de Angicos","RN"));
        lista.add(new Cidade("yFpEmqU4LaQzjeXWqZRi","Jardim de Piranhas","RN"));
        lista.add(new Cidade("ocnJHoAWLbMfpo6uUjgs","Jardim do Seridó","RN"));
        lista.add(new Cidade("qxtBiteZaccITUBFwkVY","João Câmara","RN"));
        lista.add(new Cidade("UkJsRm4ygUuETKJdKPiG","João Dias","RN"));
        lista.add(new Cidade("vMiBfDeruzHsTERyQDJ4","José da Penha","RN"));
        lista.add(new Cidade("tUXnvmgJtV2OMux2aRll","Jucurutu","RN"));
        lista.add(new Cidade("OEmGqDbfxILnt0MNaLM1","Jundiá","RN"));
        lista.add(new Cidade("UqWenIYpg9lvQPcqF1sK","Lagoa d'Anta","RN"));
        lista.add(new Cidade("2tT9xwXze50ytqTxayze","Lagoa de Pedras","RN"));
        lista.add(new Cidade("qB5gqTCSNYYNheVrUa4g","Lagoa de Velhos","RN"));
        lista.add(new Cidade("CX29FMIAfZoNiQNLxyz0","Lagoa Nova","RN"));
        lista.add(new Cidade("muwfzwvanioPPC4eXgV9","Lagoa Salgada","RN"));
        lista.add(new Cidade("w1mTrr4JzMiymBFN5CkW","Lajes","RN"));
        lista.add(new Cidade("vanFPU0hrabZcDJkfo3u","Lajes Pintadas","RN"));
        lista.add(new Cidade("6gl0ew2enwA9qUD5fbxp","Lucrécia","RN"));
        lista.add(new Cidade("c37mthR7ZkYVMxYsP0hx","Luís Gomes","RN"));
        lista.add(new Cidade("QIfPf1UQj2rbGmoLFzEK","Macaíba","RN"));
        lista.add(new Cidade("oBGcPbpCDFa5CFo25wGZ","Macau","RN"));
        lista.add(new Cidade("Wl0h9eq2c2JrIdc6fu6d","Major Sales","RN"));
        lista.add(new Cidade("MLDtfTl43jZJIA9ApdwC","Marcelino Vieira","RN"));
        lista.add(new Cidade("uD2SU3KPaH2uNY3engOl","Martins","RN"));
        lista.add(new Cidade("UsPdcmcPct3PHY7Gxi7q","Maxaranguape","RN"));
        lista.add(new Cidade("PorDYYIFJV2XKeysPiqG","Messias Targino","RN"));
        lista.add(new Cidade("PJX1sJHF6PY2gIrb3XOq","Montanhas","RN"));
        lista.add(new Cidade("RJpeiiOH1i5Uk4nXPrkC","Monte Alegre","RN"));
        lista.add(new Cidade("eGRKhtjUMmQUp6tN9FNn","Monte das Gameleiras","RN"));
        lista.add(new Cidade("40drUnw3A8mV9flFS3DR","Mossoró","RN"));
        lista.add(new Cidade("YvR9FcqBCr72duqGGeSX","Natal","RN"));
        lista.add(new Cidade("h8wuM0fGS3Su1nKi5KLm","Nísia Floresta","RN"));
        lista.add(new Cidade("yA8v150hnDwB2yIEhBnE","Nova Cruz","RN"));
        lista.add(new Cidade("HuYCiRuXknoJCncEoauv","Olho-d'Água do Borges","RN"));
        lista.add(new Cidade("423Tm9WLCSiClsJXuHTR","Ouro Branco","RN"));
        lista.add(new Cidade("40LC3TNrlbAM3yPaTPxs","Paraná","RN"));
        lista.add(new Cidade("1cZB6PMFcAP0IYjrTACx","Paraú","RN"));
        lista.add(new Cidade("ssVWdTbEjUXzOfy4QOF6","Parazinho","RN"));
        lista.add(new Cidade("SPb47SWvThXq8sLVtRKl","Parelhas","RN"));
        lista.add(new Cidade("4jWJau8MW5cmF8gqccUW","Parnamirim","RN"));
        lista.add(new Cidade("o6ysZmyNc6gIGk8c1E4R","Passa e Fica","RN"));
        lista.add(new Cidade("rS7RlJtGway5YTcq00PG","Passagem","RN"));
        lista.add(new Cidade("DR8QBTMk6DDCZymTcBHU","Patu","RN"));
        lista.add(new Cidade("pEW0AqaX4i6emWLIWX8R","Pau dos Ferros","RN"));
        lista.add(new Cidade("qEydBu0I8L2DGuavOBPq","Pedra Grande","RN"));
        lista.add(new Cidade("1cZ7eg881925xHnd50uK","Pedra Preta","RN"));
        lista.add(new Cidade("B9P6XER8kiFsb3QO2HNJ","Pedro Avelino","RN"));
        lista.add(new Cidade("87FcAwASckBAC3h9cGD9","Pedro Velho","RN"));
        lista.add(new Cidade("i2FavKcpFaHiXN1Kz32r","Pendências","RN"));
        lista.add(new Cidade("44teD0uO8l4ea4onJ5zN","Pilões","RN"));
        lista.add(new Cidade("swTgEkRlDOIkCV0PxpH2","Poço Branco","RN"));
        lista.add(new Cidade("KPVh3JmH165ebJHH28dV","Portalegre","RN"));
        lista.add(new Cidade("GNVHhoIHrfdLeEszFvWL","Porto do Mangue","RN"));
        lista.add(new Cidade("F8Df36433yP1eJudK37r","Presidente Juscelino","RN"));
        lista.add(new Cidade("MSkxj3pivi7lhCrq35kH","Pureza","RN"));
        lista.add(new Cidade("NHDYG9XUoH3Jyc3XTBJH","Rafael Fernandes","RN"));
        lista.add(new Cidade("iJTmfs9EKs6agWX0UMYi","Rafael Godeiro","RN"));
        lista.add(new Cidade("HS0IqIxDn4EkfM9qVwwS","Riacho da Cruz","RN"));
        lista.add(new Cidade("9ajzESiiOasxo8hpeF0a","Riacho de Santana","RN"));
        lista.add(new Cidade("ZygsnKgAcAoiicEVosyO","Riachuelo","RN"));
        lista.add(new Cidade("tTybHIoaMI1qq11D2gAw","Rio do Fogo","RN"));
        lista.add(new Cidade("ALdJSvW1kzGvWqjTQwdx","Rodolfo Fernandes","RN"));
        lista.add(new Cidade("U3rqp2DgLCOvle2ctb9o","Ruy Barbosa","RN"));
        lista.add(new Cidade("8quPbdmpDzBgba6iaoN6","Santa Cruz","RN"));
        lista.add(new Cidade("ZZfxE9fDZUgKGMElulpB","Santa Maria","RN"));
        lista.add(new Cidade("Ehs9pBjJl3GFDjW7OGCe","Santana do Matos","RN"));
        lista.add(new Cidade("cSINmbBtVp9cYaeAR7FG","Santana do Seridó","RN"));
        lista.add(new Cidade("HpCwe3dCZ7xPIPFAXWRJ","Santo Antônio","RN"));
        lista.add(new Cidade("TxlbplmhRPAmRprg6pLJ","São Bento do Norte","RN"));
        lista.add(new Cidade("cHbMuNh5vgAHNCxTNh0s","São Bento do Trairí","RN"));
        lista.add(new Cidade("Rkh4TyL1MsfzJVESEvFh","São Fernando","RN"));
        lista.add(new Cidade("wyaV3AsKokKl4DtVUmS1","São Francisco do Oeste","RN"));
        lista.add(new Cidade("tNVNB9iytp3Sqmo7rPrb","São Gonçalo do Amarante","RN"));
        lista.add(new Cidade("kiDr4M9MZJxq8gi48wE6","São João do Sabugi","RN"));
        lista.add(new Cidade("UGVTDW0dEk2JgAN7uzwY","São José de Mipibu","RN"));
        lista.add(new Cidade("cZ5suUFx5K4bRbLI3m2h","São José do Campestre","RN"));
        lista.add(new Cidade("qSAbMCAZkKoi0j9q05yZ","São José do Seridó","RN"));
        lista.add(new Cidade("ZLvXlacM2uZ94Ym74fLi","São Miguel","RN"));
        lista.add(new Cidade("Oox6FoRFulueaQ1Rag7m","São Miguel de Touros","RN"));
        lista.add(new Cidade("nNHuvaMhShEIGIwHMyxH","São Paulo do Potengi","RN"));
        lista.add(new Cidade("rJq3o56vQRFfO1yiNwru","São Pedro","RN"));
        lista.add(new Cidade("I4z0N9kNGNZbquc4ch2a","São Rafael","RN"));
        lista.add(new Cidade("UriipjLMDQIrmbUgXBI3","São Tomé","RN"));
        lista.add(new Cidade("0nIc1tRsToFCF8bWjr8K","São Vicente","RN"));
        lista.add(new Cidade("AAlrvQe1L29FUbb6CmIT","Senador Elói de Souza","RN"));
        lista.add(new Cidade("PS0jZQB0AJVxVMNR7MZ1","Senador Georgino Avelino","RN"));
        lista.add(new Cidade("WEZQnWloGb6orsRvwVBZ","Serra de São Bento","RN"));
        lista.add(new Cidade("be15Bpjx0EdA1R4pfwiU","Serra do Mel","RN"));
        lista.add(new Cidade("NExL2B9MwulQc4qJHRCv","Serra Negra do Norte","RN"));
        lista.add(new Cidade("m2l2Qf1zCkk8grJsUdqc","Serrinha","RN"));
        lista.add(new Cidade("K8vjP0SgulsiBCdhChrS","Serrinha dos Pintos","RN"));
        lista.add(new Cidade("OuVWck2Ygae9vNZequno","Severiano Melo","RN"));
        lista.add(new Cidade("WAJzWq1Z9HRgROszC4fS","Sítio Novo","RN"));
        lista.add(new Cidade("YR8HRNHSkUUggAhV7rsC","Taboleiro Grande","RN"));
        lista.add(new Cidade("lcmyw5TNgvGJtwAa0iKT","Taipu","RN"));
        lista.add(new Cidade("RI4jJcFmgEkAuZK13nkL","Tangará","RN"));
        lista.add(new Cidade("5UTe1SO0G8p3MYmf9idv","Tenente Ananias","RN"));
        lista.add(new Cidade("NrzN6I04KTmtJQXy8rwj","Tenente Laurentino Cruz","RN"));
        lista.add(new Cidade("uRgOdKeaz2pQW2G2KgPm","Tibau","RN"));
        lista.add(new Cidade("hKb5sD9ql997DS0J0OHn","Tibau do Sul","RN"));
        lista.add(new Cidade("vM0NI9bDYhXxsFJ6Y1IW","Timbaúba dos Batistas","RN"));
        lista.add(new Cidade("SznQ5SPEemKpPUfxpx2B","Touros","RN"));
        lista.add(new Cidade("T8NfC5ocOL9cvWaNMfCT","Triunfo Potiguar","RN"));
        lista.add(new Cidade("DMJSPyB8JXl8G6YNhPz8","Umarizal","RN"));
        lista.add(new Cidade("c4obmQngGLCH3QwgLf5A","Upanema","RN"));
        lista.add(new Cidade("kFltMUcWfssy8X5ojDIM","Várzea","RN"));
        lista.add(new Cidade("UguBKYdX4Q5OOhziKx6r","Venha-Ver","RN"));
        lista.add(new Cidade("a39Ch05m4ofCFcTYYzaO","Vera Cruz","RN"));
        lista.add(new Cidade("WIzz0ewQgFfaENX0sp1t","Viçosa","RN"));
        lista.add(new Cidade("C9tSpNF5tR6Xk3okp1CM","Vila Flor","RN"));

        return lista;
    }
}
