package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RS {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Aceguá","RS"));
        lista.add(new Cidade("","Água Santa","RS"));
        lista.add(new Cidade("","Agudo","RS"));
        lista.add(new Cidade("","Ajuricaba","RS"));
        lista.add(new Cidade("","Alecrim","RS"));
        lista.add(new Cidade("","Alegrete","RS"));
        lista.add(new Cidade("","Alegria","RS"));
        lista.add(new Cidade("","Almirante Tamandaré do Sul","RS"));
        lista.add(new Cidade("","Alpestre","RS"));
        lista.add(new Cidade("","Alto Alegre","RS"));
        lista.add(new Cidade("","Alto Feliz","RS"));
        lista.add(new Cidade("","Alvorada","RS"));
        lista.add(new Cidade("","Amaral Ferrador","RS"));
        lista.add(new Cidade("","Ametista do Sul","RS"));
        lista.add(new Cidade("","André da Rocha","RS"));
        lista.add(new Cidade("","Anta Gorda","RS"));
        lista.add(new Cidade("","Antônio Prado","RS"));
        lista.add(new Cidade("","Arambaré","RS"));
        lista.add(new Cidade("","Araricá","RS"));
        lista.add(new Cidade("","Aratiba","RS"));
        lista.add(new Cidade("","Arroio do Meio","RS"));
        lista.add(new Cidade("","Arroio do Padre","RS"));
        lista.add(new Cidade("","Arroio do Sal","RS"));
        lista.add(new Cidade("","Arroio do Tigre","RS"));
        lista.add(new Cidade("","Arroio dos Ratos","RS"));
        lista.add(new Cidade("","Arroio Grande","RS"));
        lista.add(new Cidade("","Arvorezinha","RS"));
        lista.add(new Cidade("","Augusto Pestana","RS"));
        lista.add(new Cidade("","Áurea","RS"));
        lista.add(new Cidade("","Bagé","RS"));
        lista.add(new Cidade("","Balneário Pinhal","RS"));
        lista.add(new Cidade("","Barão","RS"));
        lista.add(new Cidade("","Barão de Cotegipe","RS"));
        lista.add(new Cidade("","Barão do Triunfo","RS"));
        lista.add(new Cidade("","Barra do Guarita","RS"));
        lista.add(new Cidade("","Barra do Quaraí","RS"));
        lista.add(new Cidade("","Barra do Ribeiro","RS"));
        lista.add(new Cidade("","Barra do Rio Azul","RS"));
        lista.add(new Cidade("","Barra Funda","RS"));
        lista.add(new Cidade("","Barracão","RS"));
        lista.add(new Cidade("","Barros Cassal","RS"));
        lista.add(new Cidade("","Benjamin Constan do Sul","RS"));
        lista.add(new Cidade("","Bento Gonçalves","RS"));
        lista.add(new Cidade("","Boa Vista das Missões","RS"));
        lista.add(new Cidade("","Boa Vista do Buricá","RS"));
        lista.add(new Cidade("","Boa Vista do Cadeado","RS"));
        lista.add(new Cidade("","Boa Vista do Incra","RS"));
        lista.add(new Cidade("","Boa Vista do Sul","RS"));
        lista.add(new Cidade("","Bom Jesus","RS"));
        lista.add(new Cidade("","Bom Princípio","RS"));
        lista.add(new Cidade("","Bom Progresso","RS"));
        lista.add(new Cidade("","Bom Retiro do Sul","RS"));
        lista.add(new Cidade("","Boqueirão do Leão","RS"));
        lista.add(new Cidade("","Bossoroca","RS"));
        lista.add(new Cidade("","Bozano","RS"));
        lista.add(new Cidade("","Braga","RS"));
        lista.add(new Cidade("","Brochier","RS"));
        lista.add(new Cidade("","Butiá","RS"));
        lista.add(new Cidade("","Caçapava do Sul","RS"));
        lista.add(new Cidade("","Cacequi","RS"));
        lista.add(new Cidade("","Cachoeira do Sul","RS"));
        lista.add(new Cidade("","Cachoeirinha","RS"));
        lista.add(new Cidade("","Cacique Doble","RS"));
        lista.add(new Cidade("","Caibaté","RS"));
        lista.add(new Cidade("","Caiçara","RS"));
        lista.add(new Cidade("","Camaquã","RS"));
        lista.add(new Cidade("","Camargo","RS"));
        lista.add(new Cidade("","Cambará do Sul","RS"));
        lista.add(new Cidade("","Campestre da Serra","RS"));
        lista.add(new Cidade("","Campina das Missões","RS"));
        lista.add(new Cidade("","Campinas do Sul","RS"));
        lista.add(new Cidade("","Campo Bom","RS"));
        lista.add(new Cidade("","Campo Novo","RS"));
        lista.add(new Cidade("","Campos Borges","RS"));
        lista.add(new Cidade("","Candelária","RS"));
        lista.add(new Cidade("","Cândido Godói","RS"));
        lista.add(new Cidade("","Candiota","RS"));
        lista.add(new Cidade("","Canela","RS"));
        lista.add(new Cidade("","Canguçu","RS"));
        lista.add(new Cidade("","Canoas","RS"));
        lista.add(new Cidade("","Canudos do Vale","RS"));
        lista.add(new Cidade("","Capão Bonito do Sul","RS"));
        lista.add(new Cidade("","Capão da Canoa","RS"));
        lista.add(new Cidade("","Capão do Cipó","RS"));
        lista.add(new Cidade("","Capão do Leão","RS"));
        lista.add(new Cidade("","Capela de Santana","RS"));
        lista.add(new Cidade("","Capitão","RS"));
        lista.add(new Cidade("","Capivari do Sul","RS"));
        lista.add(new Cidade("","Caraá","RS"));
        lista.add(new Cidade("","Carazinho","RS"));
        lista.add(new Cidade("","Carlos Barbosa","RS"));
        lista.add(new Cidade("","Carlos Gomes","RS"));
        lista.add(new Cidade("","Casca","RS"));
        lista.add(new Cidade("","Caseiros","RS"));
        lista.add(new Cidade("","Catuípe","RS"));
        lista.add(new Cidade("","Caxias do Sul","RS"));
        lista.add(new Cidade("","Centenário","RS"));
        lista.add(new Cidade("","Cerrito","RS"));
        lista.add(new Cidade("","Cerro Branco","RS"));
        lista.add(new Cidade("","Cerro Grande","RS"));
        lista.add(new Cidade("","Cerro Grande do Sul","RS"));
        lista.add(new Cidade("","Cerro Largo","RS"));
        lista.add(new Cidade("","Chapada","RS"));
        lista.add(new Cidade("","Charqueadas","RS"));
        lista.add(new Cidade("","Charrua","RS"));
        lista.add(new Cidade("","Chiapeta","RS"));
        lista.add(new Cidade("","Chuí","RS"));
        lista.add(new Cidade("","Chuvisca","RS"));
        lista.add(new Cidade("","Cidreira","RS"));
        lista.add(new Cidade("","Ciríaco","RS"));
        lista.add(new Cidade("","Colinas","RS"));
        lista.add(new Cidade("","Colorado","RS"));
        lista.add(new Cidade("","Condor","RS"));
        lista.add(new Cidade("","Constantina","RS"));
        lista.add(new Cidade("","Coqueiro Baixo","RS"));
        lista.add(new Cidade("","Coqueiros do Sul","RS"));
        lista.add(new Cidade("","Coronel Barros","RS"));
        lista.add(new Cidade("","Coronel Bicaco","RS"));
        lista.add(new Cidade("","Coronel Pilar","RS"));
        lista.add(new Cidade("","Cotiporã","RS"));
        lista.add(new Cidade("","Coxilha","RS"));
        lista.add(new Cidade("","Crissiumal","RS"));
        lista.add(new Cidade("","Cristal","RS"));
        lista.add(new Cidade("","Cristal do Sul","RS"));
        lista.add(new Cidade("","Cruz Alta","RS"));
        lista.add(new Cidade("","Cruzaltense","RS"));
        lista.add(new Cidade("","Cruzeiro do Sul","RS"));
        lista.add(new Cidade("","David Canabarro","RS"));
        lista.add(new Cidade("","Derrubadas","RS"));
        lista.add(new Cidade("","Dezesseis de Novembro","RS"));
        lista.add(new Cidade("","Dilermando de Aguiar","RS"));
        lista.add(new Cidade("","Dois Irmãos","RS"));
        lista.add(new Cidade("","Dois Irmãos das Missões","RS"));
        lista.add(new Cidade("","Dois Lajeados","RS"));
        lista.add(new Cidade("","Dom Feliciano","RS"));
        lista.add(new Cidade("","Dom Pedrito","RS"));
        lista.add(new Cidade("","Dom Pedro de Alcântara","RS"));
        lista.add(new Cidade("","Dona Francisca","RS"));
        lista.add(new Cidade("","Doutor Maurício Cardoso","RS"));
        lista.add(new Cidade("","Doutor Ricardo","RS"));
        lista.add(new Cidade("","Eldorado do Sul","RS"));
        lista.add(new Cidade("","Encantado","RS"));
        lista.add(new Cidade("","Encruzilhada do Sul","RS"));
        lista.add(new Cidade("","Engenho Velho","RS"));
        lista.add(new Cidade("","Entre Rios do Sul","RS"));
        lista.add(new Cidade("","Entre-Ijuís","RS"));
        lista.add(new Cidade("","Erebango","RS"));
        lista.add(new Cidade("","Erechim","RS"));
        lista.add(new Cidade("","Ernestina","RS"));
        lista.add(new Cidade("","Erval Grande","RS"));
        lista.add(new Cidade("","Erval Seco","RS"));
        lista.add(new Cidade("","Esmeralda","RS"));
        lista.add(new Cidade("","Esperança do Sul","RS"));
        lista.add(new Cidade("","Espumoso","RS"));
        lista.add(new Cidade("","Estação","RS"));
        lista.add(new Cidade("","Estância Velha","RS"));
        lista.add(new Cidade("","Esteio","RS"));
        lista.add(new Cidade("","Estrela","RS"));
        lista.add(new Cidade("","Estrela Velha","RS"));
        lista.add(new Cidade("","Eugênio de Castro","RS"));
        lista.add(new Cidade("","Fagundes Varela","RS"));
        lista.add(new Cidade("","Farroupilha","RS"));
        lista.add(new Cidade("","Faxinal do Soturno","RS"));
        lista.add(new Cidade("","Faxinalzinho","RS"));
        lista.add(new Cidade("","Fazenda Vilanova","RS"));
        lista.add(new Cidade("","Feliz","RS"));
        lista.add(new Cidade("","Flores da Cunha","RS"));
        lista.add(new Cidade("","Floriano Peixoto","RS"));
        lista.add(new Cidade("","Fontoura Xavier","RS"));
        lista.add(new Cidade("","Formigueiro","RS"));
        lista.add(new Cidade("","Forquetinha","RS"));
        lista.add(new Cidade("","Fortaleza dos Valos","RS"));
        lista.add(new Cidade("","Frederico Westphalen","RS"));
        lista.add(new Cidade("","Garibaldi","RS"));
        lista.add(new Cidade("","Garruchos","RS"));
        lista.add(new Cidade("","Gaurama","RS"));
        lista.add(new Cidade("","General Câmara","RS"));
        lista.add(new Cidade("","Gentil","RS"));
        lista.add(new Cidade("","Getúlio Vargas","RS"));
        lista.add(new Cidade("","Giruá","RS"));
        lista.add(new Cidade("","Glorinha","RS"));
        lista.add(new Cidade("","Gramado","RS"));
        lista.add(new Cidade("","Gramado dos Loureiros","RS"));
        lista.add(new Cidade("","Gramado Xavier","RS"));
        lista.add(new Cidade("","Gravataí","RS"));
        lista.add(new Cidade("","Guabiju","RS"));
        lista.add(new Cidade("","Guaíba","RS"));
        lista.add(new Cidade("","Guaporé","RS"));
        lista.add(new Cidade("","Guarani das Missões","RS"));
        lista.add(new Cidade("","Harmonia","RS"));
        lista.add(new Cidade("","Herval","RS"));
        lista.add(new Cidade("","Herveiras","RS"));
        lista.add(new Cidade("","Horizontina","RS"));
        lista.add(new Cidade("","Hulha Negra","RS"));
        lista.add(new Cidade("","Humaitá","RS"));
        lista.add(new Cidade("","Ibarama","RS"));
        lista.add(new Cidade("","Ibiaçá","RS"));
        lista.add(new Cidade("","Ibiraiaras","RS"));
        lista.add(new Cidade("","Ibirapuitã","RS"));
        lista.add(new Cidade("","Ibirubá","RS"));
        lista.add(new Cidade("","Igrejinha","RS"));
        lista.add(new Cidade("","Ijuí","RS"));
        lista.add(new Cidade("","Ilópolis","RS"));
        lista.add(new Cidade("","Imbé","RS"));
        lista.add(new Cidade("","Imigrante","RS"));
        lista.add(new Cidade("","Independência","RS"));
        lista.add(new Cidade("","Inhacorá","RS"));
        lista.add(new Cidade("","Ipê","RS"));
        lista.add(new Cidade("","Ipiranga do Sul","RS"));
        lista.add(new Cidade("","Iraí","RS"));
        lista.add(new Cidade("","Itaara","RS"));
        lista.add(new Cidade("","Itacurubi","RS"));
        lista.add(new Cidade("","Itapuca","RS"));
        lista.add(new Cidade("","Itaqui","RS"));
        lista.add(new Cidade("","Itati","RS"));
        lista.add(new Cidade("","Itatiba do Sul","RS"));
        lista.add(new Cidade("","Ivorá","RS"));
        lista.add(new Cidade("","Ivoti","RS"));
        lista.add(new Cidade("","Jaboticaba","RS"));
        lista.add(new Cidade("","Jacuizinho","RS"));
        lista.add(new Cidade("","Jacutinga","RS"));
        lista.add(new Cidade("","Jaguarão","RS"));
        lista.add(new Cidade("","Jaguari","RS"));
        lista.add(new Cidade("","Jaquirana","RS"));
        lista.add(new Cidade("","Jari","RS"));
        lista.add(new Cidade("","Jóia","RS"));
        lista.add(new Cidade("","Júlio de Castilhos","RS"));
        lista.add(new Cidade("","Lagoa Bonita do Sul","RS"));
        lista.add(new Cidade("","Lagoa dos Três Cantos","RS"));
        lista.add(new Cidade("","Lagoa Vermelha","RS"));
        lista.add(new Cidade("","Lagoão","RS"));
        lista.add(new Cidade("","Lajeado","RS"));
        lista.add(new Cidade("","Lajeado do Bugre","RS"));
        lista.add(new Cidade("","Lavras do Sul","RS"));
        lista.add(new Cidade("","Liberato Salzano","RS"));
        lista.add(new Cidade("","Lindolfo Collor","RS"));
        lista.add(new Cidade("","Linha Nova","RS"));
        lista.add(new Cidade("","Maçambara","RS"));
        lista.add(new Cidade("","Machadinho","RS"));
        lista.add(new Cidade("","Mampituba","RS"));
        lista.add(new Cidade("","Manoel Viana","RS"));
        lista.add(new Cidade("","Maquiné","RS"));
        lista.add(new Cidade("","Maratá","RS"));
        lista.add(new Cidade("","Marau","RS"));
        lista.add(new Cidade("","Marcelino Ramos","RS"));
        lista.add(new Cidade("","Mariana Pimentel","RS"));
        lista.add(new Cidade("","Mariano Moro","RS"));
        lista.add(new Cidade("","Marques de Souza","RS"));
        lista.add(new Cidade("","Mata","RS"));
        lista.add(new Cidade("","Mato Castelhano","RS"));
        lista.add(new Cidade("","Mato Leitão","RS"));
        lista.add(new Cidade("","Mato Queimado","RS"));
        lista.add(new Cidade("","Maximiliano de Almeida","RS"));
        lista.add(new Cidade("","Minas do Leão","RS"));
        lista.add(new Cidade("","Miraguaí","RS"));
        lista.add(new Cidade("","Montauri","RS"));
        lista.add(new Cidade("","Monte Alegre dos Campos","RS"));
        lista.add(new Cidade("","Monte Belo do Sul","RS"));
        lista.add(new Cidade("","Montenegro","RS"));
        lista.add(new Cidade("","Mormaço","RS"));
        lista.add(new Cidade("","Morrinhos do Sul","RS"));
        lista.add(new Cidade("","Morro Redondo","RS"));
        lista.add(new Cidade("","Morro Reuter","RS"));
        lista.add(new Cidade("","Mostardas","RS"));
        lista.add(new Cidade("","Muçum","RS"));
        lista.add(new Cidade("","Muitos Capões","RS"));
        lista.add(new Cidade("","Muliterno","RS"));
        lista.add(new Cidade("","Não-Me-Toque","RS"));
        lista.add(new Cidade("","Nicolau Vergueiro","RS"));
        lista.add(new Cidade("","Nonoai","RS"));
        lista.add(new Cidade("","Nova Alvorada","RS"));
        lista.add(new Cidade("","Nova Araçá","RS"));
        lista.add(new Cidade("","Nova Bassano","RS"));
        lista.add(new Cidade("","Nova Boa Vista","RS"));
        lista.add(new Cidade("","Nova Bréscia","RS"));
        lista.add(new Cidade("","Nova Candelária","RS"));
        lista.add(new Cidade("","Nova Esperança do Sul","RS"));
        lista.add(new Cidade("","Nova Hartz","RS"));
        lista.add(new Cidade("","Nova Pádua","RS"));
        lista.add(new Cidade("","Nova Palma","RS"));
        lista.add(new Cidade("","Nova Petrópolis","RS"));
        lista.add(new Cidade("","Nova Prata","RS"));
        lista.add(new Cidade("","Nova Ramada","RS"));
        lista.add(new Cidade("","Nova Roma do Sul","RS"));
        lista.add(new Cidade("","Nova Santa Rita","RS"));
        lista.add(new Cidade("","Novo Barreiro","RS"));
        lista.add(new Cidade("","Novo Cabrais","RS"));
        lista.add(new Cidade("","Novo Hamburgo","RS"));
        lista.add(new Cidade("","Novo Machado","RS"));
        lista.add(new Cidade("","Novo Tiradentes","RS"));
        lista.add(new Cidade("","Novo Xingu","RS"));
        lista.add(new Cidade("","Osório","RS"));
        lista.add(new Cidade("","Paim Filho","RS"));
        lista.add(new Cidade("","Palmares do Sul","RS"));
        lista.add(new Cidade("","Palmeira das Missões","RS"));
        lista.add(new Cidade("","Palmitinho","RS"));
        lista.add(new Cidade("","Panambi","RS"));
        lista.add(new Cidade("","Pântano Grande","RS"));
        lista.add(new Cidade("","Paraí","RS"));
        lista.add(new Cidade("","Paraíso do Sul","RS"));
        lista.add(new Cidade("","Pareci Novo","RS"));
        lista.add(new Cidade("","Parobé","RS"));
        lista.add(new Cidade("","Passa Sete","RS"));
        lista.add(new Cidade("","Passo do Sobrado","RS"));
        lista.add(new Cidade("","Passo Fundo","RS"));
        lista.add(new Cidade("","Paulo Bento","RS"));
        lista.add(new Cidade("","Paverama","RS"));
        lista.add(new Cidade("","Pedras Altas","RS"));
        lista.add(new Cidade("","Pedro Osório","RS"));
        lista.add(new Cidade("","Pejuçara","RS"));
        lista.add(new Cidade("","Pelotas","RS"));
        lista.add(new Cidade("","Picada Café","RS"));
        lista.add(new Cidade("","Pinhal","RS"));
        lista.add(new Cidade("","Pinhal da Serra","RS"));
        lista.add(new Cidade("","Pinhal Grande","RS"));
        lista.add(new Cidade("","Pinheirinho do Vale","RS"));
        lista.add(new Cidade("","Pinheiro Machado","RS"));
        lista.add(new Cidade("","Pirapó","RS"));
        lista.add(new Cidade("","Piratini","RS"));
        lista.add(new Cidade("","Planalto","RS"));
        lista.add(new Cidade("","Poço das Antas","RS"));
        lista.add(new Cidade("","Pontão","RS"));
        lista.add(new Cidade("","Ponte Preta","RS"));
        lista.add(new Cidade("","Portão","RS"));
        lista.add(new Cidade("","Porto Alegre","RS"));
        lista.add(new Cidade("","Porto Lucena","RS"));
        lista.add(new Cidade("","Porto Mauá","RS"));
        lista.add(new Cidade("","Porto Vera Cruz","RS"));
        lista.add(new Cidade("","Porto Xavier","RS"));
        lista.add(new Cidade("","Pouso Novo","RS"));
        lista.add(new Cidade("","Presidente Lucena","RS"));
        lista.add(new Cidade("","Progresso","RS"));
        lista.add(new Cidade("","Protásio Alves","RS"));
        lista.add(new Cidade("","Putinga","RS"));
        lista.add(new Cidade("","Quaraí","RS"));
        lista.add(new Cidade("","Quatro Irmãos","RS"));
        lista.add(new Cidade("","Quevedos","RS"));
        lista.add(new Cidade("","Quinze de Novembro","RS"));
        lista.add(new Cidade("","Redentora","RS"));
        lista.add(new Cidade("","Relvado","RS"));
        lista.add(new Cidade("","Restinga Seca","RS"));
        lista.add(new Cidade("","Rio dos Índios","RS"));
        lista.add(new Cidade("","Rio Grande","RS"));
        lista.add(new Cidade("","Rio Pardo","RS"));
        lista.add(new Cidade("","Riozinho","RS"));
        lista.add(new Cidade("","Roca Sales","RS"));
        lista.add(new Cidade("","Rodeio Bonito","RS"));
        lista.add(new Cidade("","Rolador","RS"));
        lista.add(new Cidade("","Rolante","RS"));
        lista.add(new Cidade("","Ronda Alta","RS"));
        lista.add(new Cidade("","Rondinha","RS"));
        lista.add(new Cidade("","Roque Gonzales","RS"));
        lista.add(new Cidade("","Rosário do Sul","RS"));
        lista.add(new Cidade("","Sagrada Família","RS"));
        lista.add(new Cidade("","Saldanha Marinho","RS"));
        lista.add(new Cidade("","Salto do Jacuí","RS"));
        lista.add(new Cidade("","Salvador das Missões","RS"));
        lista.add(new Cidade("","Salvador do Sul","RS"));
        lista.add(new Cidade("","Sananduva","RS"));
        lista.add(new Cidade("","Santa Bárbara do Sul","RS"));
        lista.add(new Cidade("","Santa Cecília do Sul","RS"));
        lista.add(new Cidade("","Santa Clara do Sul","RS"));
        lista.add(new Cidade("","Santa Cruz do Sul","RS"));
        lista.add(new Cidade("","Santa Margarida do Sul","RS"));
        lista.add(new Cidade("","Santa Maria","RS"));
        lista.add(new Cidade("","Santa Maria do Herval","RS"));
        lista.add(new Cidade("","Santa Rosa","RS"));
        lista.add(new Cidade("","Santa Tereza","RS"));
        lista.add(new Cidade("","Santa Vitória do Palmar","RS"));
        lista.add(new Cidade("","Santana da Boa Vista","RS"));
        lista.add(new Cidade("","Santana do Livramento","RS"));
        lista.add(new Cidade("","Santiago","RS"));
        lista.add(new Cidade("","Santo Ângelo","RS"));
        lista.add(new Cidade("","Santo Antônio da Patrulha","RS"));
        lista.add(new Cidade("","Santo Antônio das Missões","RS"));
        lista.add(new Cidade("","Santo Antônio do Palma","RS"));
        lista.add(new Cidade("","Santo Antônio do Planalto","RS"));
        lista.add(new Cidade("","Santo Augusto","RS"));
        lista.add(new Cidade("","Santo Cristo","RS"));
        lista.add(new Cidade("","Santo Expedito do Sul","RS"));
        lista.add(new Cidade("","São Borja","RS"));
        lista.add(new Cidade("","São Domingos do Sul","RS"));
        lista.add(new Cidade("","São Francisco de Assis","RS"));
        lista.add(new Cidade("","São Francisco de Paula","RS"));
        lista.add(new Cidade("","São Gabriel","RS"));
        lista.add(new Cidade("","São Jerônimo","RS"));
        lista.add(new Cidade("","São João da Urtiga","RS"));
        lista.add(new Cidade("","São João do Polêsine","RS"));
        lista.add(new Cidade("","São Jorge","RS"));
        lista.add(new Cidade("","São José das Missões","RS"));
        lista.add(new Cidade("","São José do Herval","RS"));
        lista.add(new Cidade("","São José do Hortêncio","RS"));
        lista.add(new Cidade("","São José do Inhacorá","RS"));
        lista.add(new Cidade("","São José do Norte","RS"));
        lista.add(new Cidade("","São José do Ouro","RS"));
        lista.add(new Cidade("","São José do Sul","RS"));
        lista.add(new Cidade("","São José dos Ausentes","RS"));
        lista.add(new Cidade("","São Leopoldo","RS"));
        lista.add(new Cidade("","São Lourenço do Sul","RS"));
        lista.add(new Cidade("","São Luiz Gonzaga","RS"));
        lista.add(new Cidade("","São Marcos","RS"));
        lista.add(new Cidade("","São Martinho","RS"));
        lista.add(new Cidade("","São Martinho da Serra","RS"));
        lista.add(new Cidade("","São Miguel das Missões","RS"));
        lista.add(new Cidade("","São Nicolau","RS"));
        lista.add(new Cidade("","São Paulo das Missões","RS"));
        lista.add(new Cidade("","São Pedro da Serra","RS"));
        lista.add(new Cidade("","São Pedro das Missões","RS"));
        lista.add(new Cidade("","São Pedro do Butiá","RS"));
        lista.add(new Cidade("","São Pedro do Sul","RS"));
        lista.add(new Cidade("","São Sebastião do Caí","RS"));
        lista.add(new Cidade("","São Sepé","RS"));
        lista.add(new Cidade("","São Valentim","RS"));
        lista.add(new Cidade("","São Valentim do Sul","RS"));
        lista.add(new Cidade("","São Valério do Sul","RS"));
        lista.add(new Cidade("","São Vendelino","RS"));
        lista.add(new Cidade("","São Vicente do Sul","RS"));
        lista.add(new Cidade("","Sapiranga","RS"));
        lista.add(new Cidade("","Sapucaia do Sul","RS"));
        lista.add(new Cidade("","Sarandi","RS"));
        lista.add(new Cidade("","Seberi","RS"));
        lista.add(new Cidade("","Sede Nova","RS"));
        lista.add(new Cidade("","Segredo","RS"));
        lista.add(new Cidade("","Selbach","RS"));
        lista.add(new Cidade("","Senador Salgado Filho","RS"));
        lista.add(new Cidade("","Sentinela do Sul","RS"));
        lista.add(new Cidade("","Serafina Corrêa","RS"));
        lista.add(new Cidade("","Sério","RS"));
        lista.add(new Cidade("","Sertão","RS"));
        lista.add(new Cidade("","Sertão Santana","RS"));
        lista.add(new Cidade("","Sete de Setembro","RS"));
        lista.add(new Cidade("","Severiano de Almeida","RS"));
        lista.add(new Cidade("","Silveira Martins","RS"));
        lista.add(new Cidade("","Sinimbu","RS"));
        lista.add(new Cidade("","Sobradinho","RS"));
        lista.add(new Cidade("","Soledade","RS"));
        lista.add(new Cidade("","Tabaí","RS"));
        lista.add(new Cidade("","Tapejara","RS"));
        lista.add(new Cidade("","Tapera","RS"));
        lista.add(new Cidade("","Tapes","RS"));
        lista.add(new Cidade("","Taquara","RS"));
        lista.add(new Cidade("","Taquari","RS"));
        lista.add(new Cidade("","Taquaruçu do Sul","RS"));
        lista.add(new Cidade("","Tavares","RS"));
        lista.add(new Cidade("","Tenente Portela","RS"));
        lista.add(new Cidade("","Terra de Areia","RS"));
        lista.add(new Cidade("","Teutônia","RS"));
        lista.add(new Cidade("","Tio Hugo","RS"));
        lista.add(new Cidade("","Tiradentes do Sul","RS"));
        lista.add(new Cidade("","Toropi","RS"));
        lista.add(new Cidade("","Torres","RS"));
        lista.add(new Cidade("","Tramandaí","RS"));
        lista.add(new Cidade("","Travesseiro","RS"));
        lista.add(new Cidade("","Três Arroios","RS"));
        lista.add(new Cidade("","Três Cachoeiras","RS"));
        lista.add(new Cidade("","Três Coroas","RS"));
        lista.add(new Cidade("","Três de Maio","RS"));
        lista.add(new Cidade("","Três Forquilhas","RS"));
        lista.add(new Cidade("","Três Palmeiras","RS"));
        lista.add(new Cidade("","Três Passos","RS"));
        lista.add(new Cidade("","Trindade do Sul","RS"));
        lista.add(new Cidade("","Triunfo","RS"));
        lista.add(new Cidade("","Tucunduva","RS"));
        lista.add(new Cidade("","Tunas","RS"));
        lista.add(new Cidade("","Tupanci do Sul","RS"));
        lista.add(new Cidade("","Tupanciretã","RS"));
        lista.add(new Cidade("","Tupandi","RS"));
        lista.add(new Cidade("","Tuparendi","RS"));
        lista.add(new Cidade("","Turuçu","RS"));
        lista.add(new Cidade("","Ubiretama","RS"));
        lista.add(new Cidade("","União da Serra","RS"));
        lista.add(new Cidade("","Unistalda","RS"));
        lista.add(new Cidade("","Uruguaiana","RS"));
        lista.add(new Cidade("","Vacaria","RS"));
        lista.add(new Cidade("","Vale do Sol","RS"));
        lista.add(new Cidade("","Vale Real","RS"));
        lista.add(new Cidade("","Vale Verde","RS"));
        lista.add(new Cidade("","Vanini","RS"));
        lista.add(new Cidade("","Venâncio Aires","RS"));
        lista.add(new Cidade("","Vera Cruz","RS"));
        lista.add(new Cidade("","Veranópolis","RS"));
        lista.add(new Cidade("","Vespasiano Correa","RS"));
        lista.add(new Cidade("","Viadutos","RS"));
        lista.add(new Cidade("","Viamão","RS"));
        lista.add(new Cidade("","Vicente Dutra","RS"));
        lista.add(new Cidade("","Victor Graeff","RS"));
        lista.add(new Cidade("","Vila Flores","RS"));
        lista.add(new Cidade("","Vila Lângaro","RS"));
        lista.add(new Cidade("","Vila Maria","RS"));
        lista.add(new Cidade("","Vila Nova do Sul","RS"));
        lista.add(new Cidade("","Vista Alegre","RS"));
        lista.add(new Cidade("","Vista Alegre do Prata","RS"));
        lista.add(new Cidade("","Vista Gaúcha","RS"));
        lista.add(new Cidade("","Vitória das Missões","RS"));
        lista.add(new Cidade("","Westfália","RS"));
        lista.add(new Cidade("","Xangri-lá","RS"));
        return lista;
    }
}
