package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RS {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("lmqD0PPZyi6MbHmMRzCu","Aceguá","RS"));
        lista.add(new Cidade("hu25xpLVpymU7mRLOXD3","Água Santa","RS"));
        lista.add(new Cidade("Xu7SQmrMrOrNSk5FEiwH","Agudo","RS"));
        lista.add(new Cidade("52IXXU6oZXnsyhXWHqNA","Ajuricaba","RS"));
        lista.add(new Cidade("2ZtkTRwFyPMhI4miPjDF","Alecrim","RS"));
        lista.add(new Cidade("OFwX7rsX5WNTy8aM4f04","Alegrete","RS"));
        lista.add(new Cidade("sB9ndMNU1QMC5bmBCKK1","Alegria","RS"));
        lista.add(new Cidade("PD2VaCWfpvXjfVHjRm2C","Almirante Tamandaré do Sul","RS"));
        lista.add(new Cidade("5BjMpaTxFlILkiYvQjDT","Alpestre","RS"));
        lista.add(new Cidade("SnwTIbHaSyyxEmTd13Ct","Alto Alegre","RS"));
        lista.add(new Cidade("PwqbXZNvgHgGywmpfn9s","Alto Feliz","RS"));
        lista.add(new Cidade("1Ajo4w6vmkbSAjYckU1b","Alvorada","RS"));
        lista.add(new Cidade("qpX6JtTcvyPS17rw9hyQ","Amaral Ferrador","RS"));
        lista.add(new Cidade("JEO1FXP8I9Jgck9jxWEz","Ametista do Sul","RS"));
        lista.add(new Cidade("mlexupanSxmaetJdRbnI","André da Rocha","RS"));
        lista.add(new Cidade("2czoeSEHPT0GiOVlfJxQ","Anta Gorda","RS"));
        lista.add(new Cidade("yzwd0yXybbjUJnrZOPe8","Antônio Prado","RS"));
        lista.add(new Cidade("EBaobboLVwipVq6njoNc","Arambaré","RS"));
        lista.add(new Cidade("055GWzIWhOQI4vqvGNWO","Araricá","RS"));
        lista.add(new Cidade("lKzPkuhIXZA2sKFcvYV4","Aratiba","RS"));
        lista.add(new Cidade("v5A9VJmK9Uk4UKZQf5TW","Arroio do Meio","RS"));
        lista.add(new Cidade("mumVmtTcZDkmGZYRV6wF","Arroio do Padre","RS"));
        lista.add(new Cidade("Eo777e1VwK0Tqf4Ukoxy","Arroio do Sal","RS"));
        lista.add(new Cidade("XbU3qUKsxzpXper9vuMK","Arroio do Tigre","RS"));
        lista.add(new Cidade("vwJB8U6sSFUE2wi87sLs","Arroio dos Ratos","RS"));
        lista.add(new Cidade("g8PgmrywcuWKTvOF2iJd","Arroio Grande","RS"));
        lista.add(new Cidade("vpcw78rIwu5vYdY1Yf4O","Arvorezinha","RS"));
        lista.add(new Cidade("ZUWNU9xlj6GZYcmI9i2b","Augusto Pestana","RS"));
        lista.add(new Cidade("zAE4FPjOaUA3DkJg4psu","Áurea","RS"));
        lista.add(new Cidade("EeZPXckmq3zaadftmRrC","Bagé","RS"));
        lista.add(new Cidade("QgU8HbRadX2IaPKmbmyO","Balneário Pinhal","RS"));
        lista.add(new Cidade("3o7jLWm3txvEho6mwsDY","Barão","RS"));
        lista.add(new Cidade("bXkgcWhr8wNj9NMroxnp","Barão de Cotegipe","RS"));
        lista.add(new Cidade("KYzNCBHRwiiJnwjYWzuU","Barão do Triunfo","RS"));
        lista.add(new Cidade("duvhFkD48sfNjn4K5t7s","Barra do Guarita","RS"));
        lista.add(new Cidade("WPXerndMjnZOkWiDsGTn","Barra do Quaraí","RS"));
        lista.add(new Cidade("pF2ARsLKNwcdThAsxOny","Barra do Ribeiro","RS"));
        lista.add(new Cidade("EiUmA8uPYYAW9Xaz6t4c","Barra do Rio Azul","RS"));
        lista.add(new Cidade("7v64sP7sf72TxYGfSgAe","Barra Funda","RS"));
        lista.add(new Cidade("qu9O0PWw7x46P58k2VfR","Barracão","RS"));
        lista.add(new Cidade("DkMq756xuLaSBc5TKTaV","Barros Cassal","RS"));
        lista.add(new Cidade("f7igRUbf3eQWtGphYF4K","Benjamin Constan do Sul","RS"));
        lista.add(new Cidade("s3g3QIv4oPw2t1bt3iXW","Bento Gonçalves","RS"));
        lista.add(new Cidade("e5eqhAIcD6PPL6bX0ehi","Boa Vista das Missões","RS"));
        lista.add(new Cidade("SMihVTrzxzutUo1BA6A5","Boa Vista do Buricá","RS"));
        lista.add(new Cidade("YJTG8rHDfOuu8QboYYfS","Boa Vista do Cadeado","RS"));
        lista.add(new Cidade("IKKawYR4eCWqN5lz3oyE","Boa Vista do Incra","RS"));
        lista.add(new Cidade("E3Nr8JnHinyBIWZrJdEH","Boa Vista do Sul","RS"));
        lista.add(new Cidade("VddC5WeIvBjAUMawoY2z","Bom Jesus","RS"));
        lista.add(new Cidade("RtCa1x1kDjKeow4oeumd","Bom Princípio","RS"));
        lista.add(new Cidade("RKITKD8uuQNn8MxmF57H","Bom Progresso","RS"));
        lista.add(new Cidade("zdviFRW217iPzZhW3UE6","Bom Retiro do Sul","RS"));
        lista.add(new Cidade("QhYpk00kR9Sogk9b5Wlx","Boqueirão do Leão","RS"));
        lista.add(new Cidade("CftA2gbMtU8BjxD2R035","Bossoroca","RS"));
        lista.add(new Cidade("nV2DNnynS9bFkWwAozyV","Bozano","RS"));
        lista.add(new Cidade("biJ7Sl9Q2t8EWdFH30GJ","Braga","RS"));
        lista.add(new Cidade("Apj9s7QESx21FtyNcXkK","Brochier","RS"));
        lista.add(new Cidade("CODA3MtwifLQFHrpCBXZ","Butiá","RS"));
        lista.add(new Cidade("LhzwL59dRyoKMlwMYhqd","Caçapava do Sul","RS"));
        lista.add(new Cidade("HIJx4JeWpqls4eErtq1o","Cacequi","RS"));
        lista.add(new Cidade("YdoPbSXPXaxUGl0NdPgw","Cachoeira do Sul","RS"));
        lista.add(new Cidade("GYDfJ1Zgnn1wdZuTEsIw","Cachoeirinha","RS"));
        lista.add(new Cidade("JPTkdOkx7Qf9WKorl3Yz","Cacique Doble","RS"));
        lista.add(new Cidade("O33EkRuO5R16wXmxayiA","Caibaté","RS"));
        lista.add(new Cidade("UMEpGdNHYW458AMQnepE","Caiçara","RS"));
        lista.add(new Cidade("xGeC2VYOxZDretKUueZi","Camaquã","RS"));
        lista.add(new Cidade("w4r0SrxWwnJzJceDrHFI","Camargo","RS"));
        lista.add(new Cidade("vUJpew2CrLWnZ6Xxx8Bj","Cambará do Sul","RS"));
        lista.add(new Cidade("7LulQ50UB5BJEkVE4Svj","Campestre da Serra","RS"));
        lista.add(new Cidade("psLXn9JsNd1qBTp4bmen","Campina das Missões","RS"));
        lista.add(new Cidade("pGlZxrx7kfup0YfUb3HV","Campinas do Sul","RS"));
        lista.add(new Cidade("HspugBkmstfvn2BELMQ6","Campo Bom","RS"));
        lista.add(new Cidade("krmQgOgepYZETlF2kgLH","Campo Novo","RS"));
        lista.add(new Cidade("AdtymxfpTDxuYn1EN6Iz","Campos Borges","RS"));
        lista.add(new Cidade("hVipnY0tzlSB6IJXhCwP","Candelária","RS"));
        lista.add(new Cidade("4ADNS7FNWoypfqCk4Op6","Cândido Godói","RS"));
        lista.add(new Cidade("HtAD5jmuTu43s1bwCoHw","Candiota","RS"));
        lista.add(new Cidade("r5OlztDNDczJfhVRi1VG","Canela","RS"));
        lista.add(new Cidade("hHt8Sg5kxlW15e4M0XLs","Canguçu","RS"));
        lista.add(new Cidade("WjCABk7OFOCcXFeeFZTY","Canoas","RS"));
        lista.add(new Cidade("Ns0ZPaiPWpdt6z5IbZZi","Canudos do Vale","RS"));
        lista.add(new Cidade("tnKtqU9dLDufylucIxK4","Capão Bonito do Sul","RS"));
        lista.add(new Cidade("tFatcg1YPVH4b2mwGt4V","Capão da Canoa","RS"));
        lista.add(new Cidade("LTZ2lkhT7JSX3PbQtxOt","Capão do Cipó","RS"));
        lista.add(new Cidade("FXhcA1AGP7CP52NaBOW6","Capão do Leão","RS"));
        lista.add(new Cidade("yHmXMk8z8VTBENcjbdT4","Capela de Santana","RS"));
        lista.add(new Cidade("EiJRAWH0ujLaUy2OEKTg","Capitão","RS"));
        lista.add(new Cidade("yihT6oo6hJqrbU9KclHZ","Capivari do Sul","RS"));
        lista.add(new Cidade("ZRewkvQpyYCmjk7vZK7F","Caraá","RS"));
        lista.add(new Cidade("4cDEjILWPeA008XU5O8T","Carazinho","RS"));
        lista.add(new Cidade("yaEfCopPbhMURODYx5xe","Carlos Barbosa","RS"));
        lista.add(new Cidade("kDzADaBIGPE68ke00dQu","Carlos Gomes","RS"));
        lista.add(new Cidade("QC9z7p1QbNFubR8QJnGc","Casca","RS"));
        lista.add(new Cidade("F83W2NtOkF763bGowHXV","Caseiros","RS"));
        lista.add(new Cidade("h02Yl7HDwGWWb8ny4ezb","Catuípe","RS"));
        lista.add(new Cidade("pXABIrxPSoCeIMI0CNpj","Caxias do Sul","RS"));
        lista.add(new Cidade("bxqqFWMh7Fw5rM1A5V3a","Centenário","RS"));
        lista.add(new Cidade("CeVbQgBW2WMNZWEo0TjY","Cerrito","RS"));
        lista.add(new Cidade("ZSKgzYZKUlYloKtFP7VS","Cerro Branco","RS"));
        lista.add(new Cidade("r8OnnEqNXUX0mG3YNRC0","Cerro Grande","RS"));
        lista.add(new Cidade("7XOajcOtDjZgGzHUEBn6","Cerro Grande do Sul","RS"));
        lista.add(new Cidade("or2AgT2J1q2v2nc4oFpW","Cerro Largo","RS"));
        lista.add(new Cidade("y4JyF0Ji85ZhM6H5zqLb","Chapada","RS"));
        lista.add(new Cidade("p6nR60etwSPAc55SbcGU","Charqueadas","RS"));
        lista.add(new Cidade("yOaHgNpBdpCqLVxV75yO","Charrua","RS"));
        lista.add(new Cidade("wNKkUOWwxueVEEj0b3by","Chiapeta","RS"));
        lista.add(new Cidade("dWO2URkhjIxRqxLKGb4Q","Chuí","RS"));
        lista.add(new Cidade("IefMeF2duJExHecEYLrc","Chuvisca","RS"));
        lista.add(new Cidade("sV5JfyZ5ucbRaIHUgfBY","Cidreira","RS"));
        lista.add(new Cidade("hcaYbxyfAudfcaIQucMK","Ciríaco","RS"));
        lista.add(new Cidade("aXuVOq2U3rEUFKjOS6pz","Colinas","RS"));
        lista.add(new Cidade("xZe8I4ni955E2WzXBYqT","Colorado","RS"));
        lista.add(new Cidade("laCjFZ6jlQehXuhQo6wL","Condor","RS"));
        lista.add(new Cidade("9XJsfbKLsqGCDRh9qZKA","Constantina","RS"));
        lista.add(new Cidade("y1orddQvMcXguSeo520w","Coqueiro Baixo","RS"));
        lista.add(new Cidade("wXSgSnjqDiuLOXxFW80r","Coqueiros do Sul","RS"));
        lista.add(new Cidade("kQFxU71yWxh2otCU3hHA","Coronel Barros","RS"));
        lista.add(new Cidade("N6bxJaDKLj2hO3WtiV1L","Coronel Bicaco","RS"));
        lista.add(new Cidade("UWhUzPzRfJ5f0O11tlcA","Coronel Pilar","RS"));
        lista.add(new Cidade("3ougEISwVKyHXxar3mW7","Cotiporã","RS"));
        lista.add(new Cidade("IoPZTeRA9Dekx8XztPIw","Coxilha","RS"));
        lista.add(new Cidade("5aTQ3X5XjeLTb4koVJFJ","Crissiumal","RS"));
        lista.add(new Cidade("dq4K2RqjfAu4A91zBSWc","Cristal","RS"));
        lista.add(new Cidade("q4fpS9gmVkGPu2dQwyGj","Cristal do Sul","RS"));
        lista.add(new Cidade("QTeCafDA7OZuAMLIj8Zf","Cruz Alta","RS"));
        lista.add(new Cidade("IdzJ55FecYEKipWT62pa","Cruzaltense","RS"));
        lista.add(new Cidade("z0Jr4OA2LVWNSdW6D60A","Cruzeiro do Sul","RS"));
        lista.add(new Cidade("THadfTbjdp8ZOJmbU0Nq","David Canabarro","RS"));
        lista.add(new Cidade("av5HITLBHmayZxq50HXa","Derrubadas","RS"));
        lista.add(new Cidade("n71Vjr7iGGCQbbGJ7zG9","Dezesseis de Novembro","RS"));
        lista.add(new Cidade("LJdwDDhDxDifccklekSV","Dilermando de Aguiar","RS"));
        lista.add(new Cidade("5urM7wBuWDVBMNOh926s","Dois Irmãos","RS"));
        lista.add(new Cidade("IqFUV6wBoWDbU3RDapFS","Dois Irmãos das Missões","RS"));
        lista.add(new Cidade("aUMB8JJvsVkk1EeUu5bp","Dois Lajeados","RS"));
        lista.add(new Cidade("hqcQheRi8NtOEaBoZICx","Dom Feliciano","RS"));
        lista.add(new Cidade("yOy2dhNdmnQGBFnZm2yA","Dom Pedrito","RS"));
        lista.add(new Cidade("Q6Y4owSofmuZjJEiiJ32","Dom Pedro de Alcântara","RS"));
        lista.add(new Cidade("eQiLwL9Lp9hc0QczFjXO","Dona Francisca","RS"));
        lista.add(new Cidade("Mblx8jtr5GSZsj2B5D3S","Doutor Maurício Cardoso","RS"));
        lista.add(new Cidade("NveNW5UumJU63rkCXBXR","Doutor Ricardo","RS"));
        lista.add(new Cidade("POSEJlLzoXN5JJESiPTR","Eldorado do Sul","RS"));
        lista.add(new Cidade("OPFZgFva0vtLKLSF28Vr","Encantado","RS"));
        lista.add(new Cidade("LTWo1Vgz2knMSNOZRuEc","Encruzilhada do Sul","RS"));
        lista.add(new Cidade("WFqqCOkUkCvSga7pLqY2","Engenho Velho","RS"));
        lista.add(new Cidade("6YmNQipMpCv5aXG7u6kD","Entre Rios do Sul","RS"));
        lista.add(new Cidade("6yAkrUhcPhP8nwloPH87","Entre-Ijuís","RS"));
        lista.add(new Cidade("DZoDon9UkcgCZzYUrB0L","Erebango","RS"));
        lista.add(new Cidade("aKmxFe9d6s7RHW0OmFBf","Erechim","RS"));
        lista.add(new Cidade("MZPJPW52CimS1aHKOSkO","Ernestina","RS"));
        lista.add(new Cidade("QbjNYqCy10mGG8dMNBEP","Erval Grande","RS"));
        lista.add(new Cidade("08fBYR2pQBWOSPEOed4J","Erval Seco","RS"));
        lista.add(new Cidade("LxhvuDOYymxDlfs07rCz","Esmeralda","RS"));
        lista.add(new Cidade("f51uObsPHja92urXOohm","Esperança do Sul","RS"));
        lista.add(new Cidade("pMmbfbjDPjf4mkPsNNcV","Espumoso","RS"));
        lista.add(new Cidade("L0o8cfxnBqUAjcjrkzGY","Estação","RS"));
        lista.add(new Cidade("6i5H3Hc1cYZKjrSnIfDI","Estância Velha","RS"));
        lista.add(new Cidade("xyz3OgnW9GaRbB8luRew","Esteio","RS"));
        lista.add(new Cidade("Q5Kq5vvR87kPIk75Hs3Z","Estrela","RS"));
        lista.add(new Cidade("ko5yzaezldibEg3SDYLo","Estrela Velha","RS"));
        lista.add(new Cidade("t8TDUwIDp92hX3kxONYn","Eugênio de Castro","RS"));
        lista.add(new Cidade("4uMVujXAlijJWAB497YV","Fagundes Varela","RS"));
        lista.add(new Cidade("ncGFUf5u9KQzf21Wprzl","Farroupilha","RS"));
        lista.add(new Cidade("JwFBKRSx6TkaQBiI9dDE","Faxinal do Soturno","RS"));
        lista.add(new Cidade("vvWP7JtMCnZZg4pUpoes","Faxinalzinho","RS"));
        lista.add(new Cidade("xgEe5zTdf6h5Xm3fkjaV","Fazenda Vilanova","RS"));
        lista.add(new Cidade("O50BqcfRKGhkoRqV0NSZ","Feliz","RS"));
        lista.add(new Cidade("sqGg6qecKeABG5lFud98","Flores da Cunha","RS"));
        lista.add(new Cidade("1F4T3Xj7sz5zG5S2jPtp","Floriano Peixoto","RS"));
        lista.add(new Cidade("hrlMdkHinEbHyiPMqw1i","Fontoura Xavier","RS"));
        lista.add(new Cidade("oSEsNdJPOS9PpKaybbuB","Formigueiro","RS"));
        lista.add(new Cidade("upPVZNUwzMKyhkBFzJaw","Forquetinha","RS"));
        lista.add(new Cidade("eChbr7YLHZeJaYCcwEY2","Fortaleza dos Valos","RS"));
        lista.add(new Cidade("NavtmfcioqHE7Rugr3XV","Frederico Westphalen","RS"));
        lista.add(new Cidade("88qZR0JDaFY5qkYfXngA","Garibaldi","RS"));
        lista.add(new Cidade("rwkpFumoBhvwnGYCch4i","Garruchos","RS"));
        lista.add(new Cidade("D08wUxLMzKKBOuwxeDSo","Gaurama","RS"));
        lista.add(new Cidade("jroAdW69judNsxlscxIc","General Câmara","RS"));
        lista.add(new Cidade("1oKmNSEwbOFTlZkjQ5oZ","Gentil","RS"));
        lista.add(new Cidade("0YdmuDqqBMM1USvZsyfu","Getúlio Vargas","RS"));
        lista.add(new Cidade("HPfEeSqzFyHzq59Oa1WD","Giruá","RS"));
        lista.add(new Cidade("JdjYxV3LZxIO9UZfGodX","Glorinha","RS"));
        lista.add(new Cidade("F70IgZjZL6wnzrTfMzvH","Gramado","RS"));
        lista.add(new Cidade("P5Mj0fwN4nH1Ra6JKskc","Gramado dos Loureiros","RS"));
        lista.add(new Cidade("nOkvd89fekiCUNc1FlKU","Gramado Xavier","RS"));
        lista.add(new Cidade("zSHukwd4XnbJNbOLbeFR","Gravataí","RS"));
        lista.add(new Cidade("ot1reppLlnon4wwjrK6q","Guabiju","RS"));
        lista.add(new Cidade("5UJUYMVsgk9V55t1vLJe","Guaíba","RS"));
        lista.add(new Cidade("0mFLpLzoMoIh3v03325r","Guaporé","RS"));
        lista.add(new Cidade("iMAamrWZ562Gn0RhH100","Guarani das Missões","RS"));
        lista.add(new Cidade("ksT2dM419Fya8U4XwHAS","Harmonia","RS"));
        lista.add(new Cidade("N1wUBZdamLHaad0b63b4","Herval","RS"));
        lista.add(new Cidade("O1cAL1bUivCnV6vAJWUU","Herveiras","RS"));
        lista.add(new Cidade("dpA8bK65Noy7PfmpLqgZ","Horizontina","RS"));
        lista.add(new Cidade("oCHjJLqWiFjCJq0w0f4n","Hulha Negra","RS"));
        lista.add(new Cidade("m8fTd21L6xFqQfKB5lNX","Humaitá","RS"));
        lista.add(new Cidade("OPWgizT0lTsYHnsgdqQn","Ibarama","RS"));
        lista.add(new Cidade("B4ApC60lVImlw3epbRbe","Ibiaçá","RS"));
        lista.add(new Cidade("t3wkrDsKISxq08V8fMrU","Ibiraiaras","RS"));
        lista.add(new Cidade("8BSrFVCENF7onpKllAtR","Ibirapuitã","RS"));
        lista.add(new Cidade("OFz3RRBl1xuOkkfDgMIC","Ibirubá","RS"));
        lista.add(new Cidade("EqV2mtNyHTdi6jtrGbUU","Igrejinha","RS"));
        lista.add(new Cidade("9XyAnRqjWw3hEDTrTcN8","Ijuí","RS"));
        lista.add(new Cidade("qtRWvQBJPzQtw4TqzHpH","Ilópolis","RS"));
        lista.add(new Cidade("4JoUtBy0QPyPlqJQe92u","Imbé","RS"));
        lista.add(new Cidade("aGsbroq1IgSTuWPApleN","Imigrante","RS"));
        lista.add(new Cidade("cET1eh5tSBVvaIGtn7WZ","Independência","RS"));
        lista.add(new Cidade("MRBNvQxInL1D6St76cyN","Inhacorá","RS"));
        lista.add(new Cidade("R6slb3QvXvdszNa0EiVs","Ipê","RS"));
        lista.add(new Cidade("pkwDlgtUt1uGyzk2lqhw","Ipiranga do Sul","RS"));
        lista.add(new Cidade("zAyDg2u2FW3YhijNuIdl","Iraí","RS"));
        lista.add(new Cidade("EbJiSiQPOuPIIsqwLw6a","Itaara","RS"));
        lista.add(new Cidade("USslUhm4DYIgm3x8GTma","Itacurubi","RS"));
        lista.add(new Cidade("Q3SNf8RrCzIkCutmkEfA","Itapuca","RS"));
        lista.add(new Cidade("VLVYkDlAbSZWcZNUyge6","Itaqui","RS"));
        lista.add(new Cidade("MOiKFkEWQurTX8a3K377","Itati","RS"));
        lista.add(new Cidade("2TM56LUXYTeVTymbioAk","Itatiba do Sul","RS"));
        lista.add(new Cidade("FTmx6jmyn0tFYAfyUFRT","Ivorá","RS"));
        lista.add(new Cidade("zytT6ZsjO56OXpWitZ0H","Ivoti","RS"));
        lista.add(new Cidade("Z22bR1h3Oflwc5iyhzLp","Jaboticaba","RS"));
        lista.add(new Cidade("F7sIs7A8bRdX0N05qSTq","Jacuizinho","RS"));
        lista.add(new Cidade("QSGO78oSQKnIwD97LZKH","Jacutinga","RS"));
        lista.add(new Cidade("yfJ7IcXXohWGnqyXSOli","Jaguarão","RS"));
        lista.add(new Cidade("7R5k3KCAnfWN3B22pcGT","Jaguari","RS"));
        lista.add(new Cidade("Jz2FTfwB2WchJ3RdKIc8","Jaquirana","RS"));
        lista.add(new Cidade("QqvK7edZw3zXeWClJvuS","Jari","RS"));
        lista.add(new Cidade("NmoEcu3txaYTfVZULVmX","Jóia","RS"));
        lista.add(new Cidade("xBYthLL1SSYLg3ndxX8k","Júlio de Castilhos","RS"));
        lista.add(new Cidade("cCuw7sGVaEzJgjE9kRNO","Lagoa Bonita do Sul","RS"));
        lista.add(new Cidade("ZmmmJQ0TtAIMYLs92tlH","Lagoa dos Três Cantos","RS"));
        lista.add(new Cidade("AdCK9x59F0f21QNswvsz","Lagoa Vermelha","RS"));
        lista.add(new Cidade("R3JZR4bbdto201YXudVX","Lagoão","RS"));
        lista.add(new Cidade("omSZ42xhQoqgRFJZMq6u","Lajeado","RS"));
        lista.add(new Cidade("1aLjBPeRKIxzEecI7GAT","Lajeado do Bugre","RS"));
        lista.add(new Cidade("piXicaPie2S38cO2O1vj","Lavras do Sul","RS"));
        lista.add(new Cidade("lLjH3R0JwGxveMzLCxX5","Liberato Salzano","RS"));
        lista.add(new Cidade("QC0x0WWKUYbrfi55sc7k","Lindolfo Collor","RS"));
        lista.add(new Cidade("hzcDZas89I3RZS2pH9nw","Linha Nova","RS"));
        lista.add(new Cidade("4bj0E3ATGXRIJETAPT3U","Maçambara","RS"));
        lista.add(new Cidade("9PGm1YMevf70E0mqKPOG","Machadinho","RS"));
        lista.add(new Cidade("IarzULN1FunOsXg5X5Jl","Mampituba","RS"));
        lista.add(new Cidade("5yBR7SQK1uv2vQ2UxdyC","Manoel Viana","RS"));
        lista.add(new Cidade("1Nf7I5bCoPwjXN5oiteS","Maquiné","RS"));
        lista.add(new Cidade("4T7w1glVRgqxQyqqEj1O","Maratá","RS"));
        lista.add(new Cidade("HfOdlIEXk5JXBiKJpaCo","Marau","RS"));
        lista.add(new Cidade("z4Eqvu66qx1J1TMK1ikC","Marcelino Ramos","RS"));
        lista.add(new Cidade("OCzQIpdrSi2su2iBJ2JJ","Mariana Pimentel","RS"));
        lista.add(new Cidade("MkMUAq2uzlnnIKz2bjxr","Mariano Moro","RS"));
        lista.add(new Cidade("hCs3yxQIJoe3nsjLzZnu","Marques de Souza","RS"));
        lista.add(new Cidade("yDpUTH27Q96yte8bQFOf","Mata","RS"));
        lista.add(new Cidade("oaHnyMMi56k4O3uvE8p5","Mato Castelhano","RS"));
        lista.add(new Cidade("2pCg8gMJ8CDu13ghTKjt","Mato Leitão","RS"));
        lista.add(new Cidade("5ipZLq5QU0W3H1tnLJ9W","Mato Queimado","RS"));
        lista.add(new Cidade("cVrnE0PGlCy2y5fzREnY","Maximiliano de Almeida","RS"));
        lista.add(new Cidade("UlsG5m9PxcBD6YAugWhE","Minas do Leão","RS"));
        lista.add(new Cidade("YHeLaa5ZwD4KMrIKwYnm","Miraguaí","RS"));
        lista.add(new Cidade("HVOZSFnRs7P0zcmUYJNV","Montauri","RS"));
        lista.add(new Cidade("9mEIx8o3otWwYmUoRnUf","Monte Alegre dos Campos","RS"));
        lista.add(new Cidade("6niIKLLdxMQBwz11SYlK","Monte Belo do Sul","RS"));
        lista.add(new Cidade("h4kzl8JPXzfEDRIbK8D2","Montenegro","RS"));
        lista.add(new Cidade("4n7WZPD8OHPyAwxIkcJU","Mormaço","RS"));
        lista.add(new Cidade("0ZznsY2m6GMzcV0cqY9P","Morrinhos do Sul","RS"));
        lista.add(new Cidade("CU98TzlAircgsjYsyNX8","Morro Redondo","RS"));
        lista.add(new Cidade("staVaBA1DsttQO0c0Bah","Morro Reuter","RS"));
        lista.add(new Cidade("arWCz188IoxAubhANyAS","Mostardas","RS"));
        lista.add(new Cidade("WCC8X5RZ6D0shcUJmOo9","Muçum","RS"));
        lista.add(new Cidade("hbZRZVitJ7WSeqWyylP9","Muitos Capões","RS"));
        lista.add(new Cidade("ClmuiJezXNgLOZw6SW4m","Muliterno","RS"));
        lista.add(new Cidade("lgr7bx7X8dylKdLvZxQ7","Não-Me-Toque","RS"));
        lista.add(new Cidade("4gAeZCamj6YuOmsbhSzb","Nicolau Vergueiro","RS"));
        lista.add(new Cidade("eCt33JBmn49gjlB6RnA0","Nonoai","RS"));
        lista.add(new Cidade("PBB5AB0X8N4kN54GhZkD","Nova Alvorada","RS"));
        lista.add(new Cidade("jtmbQvzDNPVswc8icchH","Nova Araçá","RS"));
        lista.add(new Cidade("aoLykacvypwAGu1lOLyT","Nova Bassano","RS"));
        lista.add(new Cidade("UYuGhvEiRiTRK7nBrV4f","Nova Boa Vista","RS"));
        lista.add(new Cidade("r9SXLhBD9XvKdtLjyIo5","Nova Bréscia","RS"));
        lista.add(new Cidade("mTgaMnkv7j6vCnOuAmHq","Nova Candelária","RS"));
        lista.add(new Cidade("RtOYKMiJS6sze81UonsE","Nova Esperança do Sul","RS"));
        lista.add(new Cidade("9FPK6Jyt2beT4TbvOSXK","Nova Hartz","RS"));
        lista.add(new Cidade("OYmO0zUKkBVchX8xCRbI","Nova Pádua","RS"));
        lista.add(new Cidade("fq9xeAEJWxHGgwF85Zbo","Nova Palma","RS"));
        lista.add(new Cidade("uNf9e0Cl3JZzfjSperqG","Nova Petrópolis","RS"));
        lista.add(new Cidade("dkwAu0jPJ1Zf3vVfxElV","Nova Prata","RS"));
        lista.add(new Cidade("wWaY8WHG90Ljs6wcjlI5","Nova Ramada","RS"));
        lista.add(new Cidade("b4xrHWHHpRqStWolTLhF","Nova Roma do Sul","RS"));
        lista.add(new Cidade("ZHpOXDe0Hln1mTK5WlsV","Nova Santa Rita","RS"));
        lista.add(new Cidade("jzgbT1YgIr59fPb8xoPF","Novo Barreiro","RS"));
        lista.add(new Cidade("cNSK5YJOiEkOgmzwMOdZ","Novo Cabrais","RS"));
        lista.add(new Cidade("TOYaAffLiRK8Qut4PVeV","Novo Hamburgo","RS"));
        lista.add(new Cidade("d2fmHsqwuKKdn7dRkt9s","Novo Machado","RS"));
        lista.add(new Cidade("AgVihhR6OqZlQxYWIsmB","Novo Tiradentes","RS"));
        lista.add(new Cidade("TbDGxFeecJM7TmlkjXyv","Novo Xingu","RS"));
        lista.add(new Cidade("laRb3pFIcnDKYfFVjmVk","Osório","RS"));
        lista.add(new Cidade("RBk2deJnolCdBJQWEfQo","Paim Filho","RS"));
        lista.add(new Cidade("yME79ipgNkf7x8ddvxZa","Palmares do Sul","RS"));
        lista.add(new Cidade("bQyjTMchRBT07xoXLXBK","Palmeira das Missões","RS"));
        lista.add(new Cidade("xY6Ms3Wpjnm8ArUzKV39","Palmitinho","RS"));
        lista.add(new Cidade("GSJaO63RPjzNQN88W0Rp","Panambi","RS"));
        lista.add(new Cidade("gEDmNfaNIDKUrkMKDL80","Pântano Grande","RS"));
        lista.add(new Cidade("Kkkgvp94ZXqflaxKBwNr","Paraí","RS"));
        lista.add(new Cidade("Q1s9o1Y0pzQhVEhaSnaS","Paraíso do Sul","RS"));
        lista.add(new Cidade("gwPLKZGvN1bP7VCI4c2m","Pareci Novo","RS"));
        lista.add(new Cidade("fliBqOnvXEMaREb2gBL9","Parobé","RS"));
        lista.add(new Cidade("xK0laiWGLqUYCsKdQWXL","Passa Sete","RS"));
        lista.add(new Cidade("2Yqzkck7mL1dCpKLWkFT","Passo do Sobrado","RS"));
        lista.add(new Cidade("RRkadjsyJOMWQXMmf0U8","Passo Fundo","RS"));
        lista.add(new Cidade("LFe9EbiJTAE45D84iqyh","Paulo Bento","RS"));
        lista.add(new Cidade("l6v6kCnB31AU8u44HxIF","Paverama","RS"));
        lista.add(new Cidade("KIXzqZF1SrrNymYYQq8c","Pedras Altas","RS"));
        lista.add(new Cidade("EtqCqlQHclU9WOFjQrCx","Pedro Osório","RS"));
        lista.add(new Cidade("CUXxjSxLQN5wZmIMgoQj","Pejuçara","RS"));
        lista.add(new Cidade("tBJLW2XWyvXLNYAWGxtb","Pelotas","RS"));
        lista.add(new Cidade("LoJ29DVj66U0FkRTfnt7","Picada Café","RS"));
        lista.add(new Cidade("wUORYwv5N5AaFXBlN0Fl","Pinhal","RS"));
        lista.add(new Cidade("zzqoziSFVYWNjXZmXn3m","Pinhal da Serra","RS"));
        lista.add(new Cidade("wYnqrQvDgw08qZ4S4xdY","Pinhal Grande","RS"));
        lista.add(new Cidade("pCDzHokUNXFo3YqUgR07","Pinheirinho do Vale","RS"));
        lista.add(new Cidade("o9JTeKGNlwq8RQ6A3rVz","Pinheiro Machado","RS"));
        lista.add(new Cidade("TASD1mLSkqTvqL0cd2i8","Pirapó","RS"));
        lista.add(new Cidade("IGHoDSgZsjbXuG2CKBDT","Piratini","RS"));
        lista.add(new Cidade("0JDuObBCqJS62X7ArfIF","Planalto","RS"));
        lista.add(new Cidade("qx3GVJ3JIBOzPS6YOyzP","Poço das Antas","RS"));
        lista.add(new Cidade("NoqPDHyhX5RSFvPmJ36t","Pontão","RS"));
        lista.add(new Cidade("tdGNg7FWUo8bWMHBFlUV","Ponte Preta","RS"));
        lista.add(new Cidade("eldmC7xnhXRvzNnTeK5h","Portão","RS"));
        lista.add(new Cidade("fhCqnoCjqZLWOCDOzJ3d","Porto Alegre","RS"));
        lista.add(new Cidade("1fOou7ZLUwQilOc2TmlP","Porto Lucena","RS"));
        lista.add(new Cidade("Rzw8EWas0gAGqUxTYGxF","Porto Mauá","RS"));
        lista.add(new Cidade("PnXey7kJOwzmcPvWJgQq","Porto Vera Cruz","RS"));
        lista.add(new Cidade("r7MGVXDfSEW3BoCAKp83","Porto Xavier","RS"));
        lista.add(new Cidade("xSiSdRiDuWGvYAZhiQLN","Pouso Novo","RS"));
        lista.add(new Cidade("sGYXFMSrDECtYnn2Gs4O","Presidente Lucena","RS"));
        lista.add(new Cidade("ahIPDDqf84iUOubLUjq0","Progresso","RS"));
        lista.add(new Cidade("m8CXLiNmPR5aXcDNeYjK","Protásio Alves","RS"));
        lista.add(new Cidade("qUkhj4ZrhntYYGBY2c3X","Putinga","RS"));
        lista.add(new Cidade("9jcpcCYYYMglP2WTIlCf","Quaraí","RS"));
        lista.add(new Cidade("vrKbftguK9XGhP7XUimX","Quatro Irmãos","RS"));
        lista.add(new Cidade("hoHAAIJFLKfx2YVnYxFY","Quevedos","RS"));
        lista.add(new Cidade("PDkobz4WXAAjPyvuQNnx","Quinze de Novembro","RS"));
        lista.add(new Cidade("fLMKR3Oh8USew4lPwhBt","Redentora","RS"));
        lista.add(new Cidade("m0OpKquH4nTYIydoBI8f","Relvado","RS"));
        lista.add(new Cidade("Tp7z6kAFhioBpSTiOD8W","Restinga Seca","RS"));
        lista.add(new Cidade("a5KshE3MoZppug0yCxun","Rio dos Índios","RS"));
        lista.add(new Cidade("KA8AT1AB2WMptQwYeRE6","Rio Grande","RS"));
        lista.add(new Cidade("zxzlknEjM26UCj15UXFz","Rio Pardo","RS"));
        lista.add(new Cidade("gvwuQUyGoYVNcBEsPLit","Riozinho","RS"));
        lista.add(new Cidade("nIsgUOCGGR8fIyz1EGl5","Roca Sales","RS"));
        lista.add(new Cidade("SC2dkdlwt9CTsfLHmtxb","Rodeio Bonito","RS"));
        lista.add(new Cidade("ItYiWRBkykV2mmrxBJnx","Rolador","RS"));
        lista.add(new Cidade("CT2PCXemCuu3emvTf98P","Rolante","RS"));
        lista.add(new Cidade("2tZuGs0KjD5IYhsBC19U","Ronda Alta","RS"));
        lista.add(new Cidade("QSg8JJHbBr48xSO8va7k","Rondinha","RS"));
        lista.add(new Cidade("5ZJMkU25lQVaeeJXjMiy","Roque Gonzales","RS"));
        lista.add(new Cidade("LlFRSzHx86n9RjMIe5dd","Rosário do Sul","RS"));
        lista.add(new Cidade("etBE9pnOiiHJ2RmYqi6q","Sagrada Família","RS"));
        lista.add(new Cidade("jCJjkWjBElNeNYaZXyO5","Saldanha Marinho","RS"));
        lista.add(new Cidade("tvVGvIwJIcnkd1XccTgS","Salto do Jacuí","RS"));
        lista.add(new Cidade("8VYJXpiX8UfUkoh0rT5i","Salvador das Missões","RS"));
        lista.add(new Cidade("OKWEZpma6eaihC9875aw","Salvador do Sul","RS"));
        lista.add(new Cidade("qUqtSr9hKI94TQ6zPp1F","Sananduva","RS"));
        lista.add(new Cidade("l10obWKaRPz1a7bx5gW4","Santa Bárbara do Sul","RS"));
        lista.add(new Cidade("XvOjCHfCiN1LtfyLhbH1","Santa Cecília do Sul","RS"));
        lista.add(new Cidade("IpvSWU3sKFdw8y4gyOhg","Santa Clara do Sul","RS"));
        lista.add(new Cidade("klqSxZn9aJ7y2zlvbwWL","Santa Cruz do Sul","RS"));
        lista.add(new Cidade("MvI8r04ToRZOcYMd00Yh","Santa Margarida do Sul","RS"));
        lista.add(new Cidade("fYCnhYkfoTCaVnOzu6ov","Santa Maria","RS"));
        lista.add(new Cidade("kW4CLwzfheb3ZwgrdVKJ","Santa Maria do Herval","RS"));
        lista.add(new Cidade("QcoVwUCQkIrQjSZXSwMU","Santa Rosa","RS"));
        lista.add(new Cidade("vRzw8HQg6Ok8GrsYGDxi","Santa Tereza","RS"));
        lista.add(new Cidade("70fwAyTjl1YbDu5Ql2wE","Santa Vitória do Palmar","RS"));
        lista.add(new Cidade("duZjuyO2yQPMShaR68m4","Santana da Boa Vista","RS"));
        lista.add(new Cidade("pbw8fKbQe9qb4mdBXAjp","Santana do Livramento","RS"));
        lista.add(new Cidade("tkwP4zKLaWC9UgmrsLKE","Santiago","RS"));
        lista.add(new Cidade("poVzi2PjHF3qaRUCGCF2","Santo Ângelo","RS"));
        lista.add(new Cidade("5naosiJbxc1YOqtMqNMl","Santo Antônio da Patrulha","RS"));
        lista.add(new Cidade("AEKgc48o3iec20ffnQYo","Santo Antônio das Missões","RS"));
        lista.add(new Cidade("zZ7Zozk6XxMAqQ63bsMB","Santo Antônio do Palma","RS"));
        lista.add(new Cidade("TLEj94uJVhjbRUUnpZ5L","Santo Antônio do Planalto","RS"));
        lista.add(new Cidade("kQGWeicdeB4GzNRZNFAJ","Santo Augusto","RS"));
        lista.add(new Cidade("ZlUelZxijKsRfEVAc79E","Santo Cristo","RS"));
        lista.add(new Cidade("6mFhFEpsxj9snIZrM89B","Santo Expedito do Sul","RS"));
        lista.add(new Cidade("WYz2VBeIn26onvUzxMaC","São Borja","RS"));
        lista.add(new Cidade("f8cBTc8kPLojsHSQXXXr","São Domingos do Sul","RS"));
        lista.add(new Cidade("KL7dgZy68lsN44kN3AuV","São Francisco de Assis","RS"));
        lista.add(new Cidade("LcdiMu5BErZdEKqNxLRv","São Francisco de Paula","RS"));
        lista.add(new Cidade("QvSldvfHHpn8pNT6cn7L","São Gabriel","RS"));
        lista.add(new Cidade("3mF3abp4aUY9oAu4JKor","São Jerônimo","RS"));
        lista.add(new Cidade("WZAneC0M8UJtCShrOe9M","São João da Urtiga","RS"));
        lista.add(new Cidade("8fIZNbXzZxyJa2nX8ivq","São João do Polêsine","RS"));
        lista.add(new Cidade("eYJZ0z6AHVFaIirDdUN2","São Jorge","RS"));
        lista.add(new Cidade("AHForJk8KvfCyJJEHGkt","São José das Missões","RS"));
        lista.add(new Cidade("Pm4jUJI3i3EgLLq2jpAJ","São José do Herval","RS"));
        lista.add(new Cidade("hiGZ8FjHBwCbQIhjKSuk","São José do Hortêncio","RS"));
        lista.add(new Cidade("3lxKURgLYAZAsGzbQ1Vu","São José do Inhacorá","RS"));
        lista.add(new Cidade("K8rxblYVs8Cl8B6ag9xc","São José do Norte","RS"));
        lista.add(new Cidade("qABnUxN9HKWGEiGI2vh1","São José do Ouro","RS"));
        lista.add(new Cidade("ARsQj7VqM4Cnm7CLD5fx","São José do Sul","RS"));
        lista.add(new Cidade("XY7M0YY127WSO65r4R4O","São José dos Ausentes","RS"));
        lista.add(new Cidade("rnaHIqb0IDZDAtA2GZBG","São Leopoldo","RS"));
        lista.add(new Cidade("O3JOrVpHPD4ZMmpfICcd","São Lourenço do Sul","RS"));
        lista.add(new Cidade("c2kWPMJohQUnB3SmMzf9","São Luiz Gonzaga","RS"));
        lista.add(new Cidade("uOD2RUqSMPrJg2gKleIK","São Marcos","RS"));
        lista.add(new Cidade("O9WnKVrG3hUYWxx23CWR","São Martinho","RS"));
        lista.add(new Cidade("oZ5M9wgTmTv0xXtiJzx8","São Martinho da Serra","RS"));
        lista.add(new Cidade("VbeQTYZCJE9h7JacvJ1A","São Miguel das Missões","RS"));
        lista.add(new Cidade("HdtTb0deB7keHK96WXPu","São Nicolau","RS"));
        lista.add(new Cidade("YsWBXYIdDXfIy7Eklv7S","São Paulo das Missões","RS"));
        lista.add(new Cidade("YUvyDuLgqX9I5lIKUEOh","São Pedro da Serra","RS"));
        lista.add(new Cidade("4uIwfZkVsxNgcQSWfSEn","São Pedro das Missões","RS"));
        lista.add(new Cidade("2T9yWgcxqLmaVdCN1X0y","São Pedro do Butiá","RS"));
        lista.add(new Cidade("Vn9bZFVwSiizEDWLa7H7","São Pedro do Sul","RS"));
        lista.add(new Cidade("plyoZFtBWoA7fG3InxsS","São Sebastião do Caí","RS"));
        lista.add(new Cidade("IaVXgHdKS7xdLZfCw83p","São Sepé","RS"));
        lista.add(new Cidade("Erk5lYyMPFpqRUTCKZIH","São Valentim","RS"));
        lista.add(new Cidade("jxsBN4DR1FCbvcpALlXo","São Valentim do Sul","RS"));
        lista.add(new Cidade("vg7htd81qy9ny3v59KMF","São Valério do Sul","RS"));
        lista.add(new Cidade("AkKehTNEkvXpfWXTxKSD","São Vendelino","RS"));
        lista.add(new Cidade("i9yiZdv6HHsR1DXV2Q4A","São Vicente do Sul","RS"));
        lista.add(new Cidade("J3WUva3vN0bDk4DWZoNM","Sapiranga","RS"));
        lista.add(new Cidade("SUsW4akzOWxEjfPKdotz","Sapucaia do Sul","RS"));
        lista.add(new Cidade("eMJUbX8RaBOYdbOORb3A","Sarandi","RS"));
        lista.add(new Cidade("MWAFvSP8QiZ75A4rptY3","Seberi","RS"));
        lista.add(new Cidade("cAALE6EKdEOtAgnXnJX7","Sede Nova","RS"));
        lista.add(new Cidade("yflSpHZTsQsjHePr24jE","Segredo","RS"));
        lista.add(new Cidade("uFuXktFAwgrovDywvFnD","Selbach","RS"));
        lista.add(new Cidade("WwyVV8eXD6x670Q3H5gQ","Senador Salgado Filho","RS"));
        lista.add(new Cidade("p5D6blOXDBamLGGc1kOz","Sentinela do Sul","RS"));
        lista.add(new Cidade("1KmpXXqGJUypE7PuGqOX","Serafina Corrêa","RS"));
        lista.add(new Cidade("225CobYp3MqCJQFLERLp","Sério","RS"));
        lista.add(new Cidade("9jaTsNNCkOsbDW4855HE","Sertão","RS"));
        lista.add(new Cidade("2ftl9rwXvIosuUykZBIN","Sertão Santana","RS"));
        lista.add(new Cidade("Gfm2V8KWc4FeHKVZ08n5","Sete de Setembro","RS"));
        lista.add(new Cidade("wz6n4xGOW45RALHyJckv","Severiano de Almeida","RS"));
        lista.add(new Cidade("Pb2rmBHH1Bj1LR5MRz24","Silveira Martins","RS"));
        lista.add(new Cidade("p1c9svvbJJ5N4fdBCScU","Sinimbu","RS"));
        lista.add(new Cidade("7uWzBA0Dc5W0dUIvvngN","Sobradinho","RS"));
        lista.add(new Cidade("i4IpfayuXysbncyG9JOj","Soledade","RS"));
        lista.add(new Cidade("ttzVBLh2C9oGpOt75CjI","Tabaí","RS"));
        lista.add(new Cidade("Fa8GzryQzaLvsdQLVNyR","Tapejara","RS"));
        lista.add(new Cidade("5lttFYYfWGgC8G9kg106","Tapera","RS"));
        lista.add(new Cidade("clQ8D4Vs2hqhzhEnB6uO","Tapes","RS"));
        lista.add(new Cidade("EeY8YlndUPO6rieSGPqL","Taquara","RS"));
        lista.add(new Cidade("z5AlodqkY0ihUQZTAcVm","Taquari","RS"));
        lista.add(new Cidade("x1DUr9W4liPedm1oSQbp","Taquaruçu do Sul","RS"));
        lista.add(new Cidade("66vNvDJca5UDnflSLMwK","Tavares","RS"));
        lista.add(new Cidade("SBKU7HdtlwzoUrKtjCBJ","Tenente Portela","RS"));
        lista.add(new Cidade("75sR19mp6wqlk2wqL2If","Terra de Areia","RS"));
        lista.add(new Cidade("6V2G1htKhPLPI8YuzfGD","Teutônia","RS"));
        lista.add(new Cidade("qsLjNG4oebbrbKuvkdxl","Tio Hugo","RS"));
        lista.add(new Cidade("reM92UzdypnN2qH114c0","Tiradentes do Sul","RS"));
        lista.add(new Cidade("znnwyeiwAJ7Oqf2F89fy","Toropi","RS"));
        lista.add(new Cidade("7QwmtK4IpkM6LfnTvzYv","Torres","RS"));
        lista.add(new Cidade("rgV3K75XQ3davqWKiOE9","Tramandaí","RS"));
        lista.add(new Cidade("Es2qT9odAfUUGZLZQn3B","Travesseiro","RS"));
        lista.add(new Cidade("X2YmZjXYE0KEAZwSyVeV","Três Arroios","RS"));
        lista.add(new Cidade("C4BLEMY9rH8hAD6nHgln","Três Cachoeiras","RS"));
        lista.add(new Cidade("KKB94zBYfaOPRpfaOMc6","Três Coroas","RS"));
        lista.add(new Cidade("5DzKi7QQQLkvaBon4813","Três de Maio","RS"));
        lista.add(new Cidade("0xr6DbvvhFxII2TNuqFi","Três Forquilhas","RS"));
        lista.add(new Cidade("ass4ZejFntkuUZV1G6BA","Três Palmeiras","RS"));
        lista.add(new Cidade("jOnyc2qqQUC4LaWnW3Nd","Três Passos","RS"));
        lista.add(new Cidade("n5HzIU3JgWX93n0PP1Ju","Trindade do Sul","RS"));
        lista.add(new Cidade("dPPH5UbH7elb56qJOIW4","Triunfo","RS"));
        lista.add(new Cidade("xAsIBikiePF0ITRyZ1oE","Tucunduva","RS"));
        lista.add(new Cidade("U7fsgI1jzE07wqMn17Np","Tunas","RS"));
        lista.add(new Cidade("BuvUSej1J6VKGM2H68z3","Tupanci do Sul","RS"));
        lista.add(new Cidade("x9oADu5sfxVOIOdpGD5P","Tupanciretã","RS"));
        lista.add(new Cidade("7ZOb7VP7j8yS0IdUANRB","Tupandi","RS"));
        lista.add(new Cidade("TtagRaXjkRo4zqRky3uY","Tuparendi","RS"));
        lista.add(new Cidade("c5EAhrfyjuWzyA7uPsjU","Turuçu","RS"));
        lista.add(new Cidade("7qp1RV1cywgpaswpHEnj","Ubiretama","RS"));
        lista.add(new Cidade("eRBQgzj7SyKONuWgAsDD","União da Serra","RS"));
        lista.add(new Cidade("1H6Et2ezGEGsIiN1sSue","Unistalda","RS"));
        lista.add(new Cidade("ugLQeWSO26woEZdscmu4","Uruguaiana","RS"));
        lista.add(new Cidade("lroBLqpmBkL9xRrgGhyz","Vacaria","RS"));
        lista.add(new Cidade("bpm9aqDR9Bzan8MgnaVc","Vale do Sol","RS"));
        lista.add(new Cidade("HhA8T8CVl4YufNPKsFAU","Vale Real","RS"));
        lista.add(new Cidade("VkH3DMb6oOfdVweKPRlF","Vale Verde","RS"));
        lista.add(new Cidade("IdzxWlVPnI6mqqYrYXfZ","Vanini","RS"));
        lista.add(new Cidade("sMHPzKq8EhRQpUWrO0ho","Venâncio Aires","RS"));
        lista.add(new Cidade("438GnofwbMtj9B0OPnoB","Vera Cruz","RS"));
        lista.add(new Cidade("UCWxLWaRJIZVwWYDpqUO","Veranópolis","RS"));
        lista.add(new Cidade("ozmRWjFA7gbx0yyQTAja","Vespasiano Correa","RS"));
        lista.add(new Cidade("Gb7if7oYoVLtYjonRctn","Viadutos","RS"));
        lista.add(new Cidade("PJqRlyZcZGqjrusrQYJq","Viamão","RS"));
        lista.add(new Cidade("2CA90JUS4REDYHAtfqB7","Vicente Dutra","RS"));
        lista.add(new Cidade("WtwF49cc6VG8wsd07BXw","Victor Graeff","RS"));
        lista.add(new Cidade("LFYSApGjpBn10DxJoYzR","Vila Flores","RS"));
        lista.add(new Cidade("VoIXA3te4LyfQKhAuikC","Vila Lângaro","RS"));
        lista.add(new Cidade("j21oBQ6ZIoF4YXMt073a","Vila Maria","RS"));
        lista.add(new Cidade("kGOuqGcffnUYIB4JHkVc","Vila Nova do Sul","RS"));
        lista.add(new Cidade("IaRbpP8okglO1HT3PlTf","Vista Alegre","RS"));
        lista.add(new Cidade("GSzvDeEoODBqPuBU9Es7","Vista Alegre do Prata","RS"));
        lista.add(new Cidade("uEvbau9MNyAHGv7QZx5Q","Vista Gaúcha","RS"));
        lista.add(new Cidade("x5DOpqH7ShnGY2vKyyJw","Vitória das Missões","RS"));
        lista.add(new Cidade("eKIglwuMkLqGiPTQP3oN","Westfália","RS"));
        lista.add(new Cidade("i7ohaG3ZzbMUCXFA2SgI","Xangri-lá","RS"));

        return lista;
    }
}
