package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class RS {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("lmqD0PPZyi6MbHmMRzCu","Aceguá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hu25xpLVpymU7mRLOXD3","Água Santa","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Xu7SQmrMrOrNSk5FEiwH","Agudo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("52IXXU6oZXnsyhXWHqNA","Ajuricaba","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2ZtkTRwFyPMhI4miPjDF","Alecrim","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OFwX7rsX5WNTy8aM4f04","Alegrete","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("sB9ndMNU1QMC5bmBCKK1","Alegria","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("PD2VaCWfpvXjfVHjRm2C","Almirante Tamandaré do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5BjMpaTxFlILkiYvQjDT","Alpestre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("SnwTIbHaSyyxEmTd13Ct","Alto Alegre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("PwqbXZNvgHgGywmpfn9s","Alto Feliz","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1Ajo4w6vmkbSAjYckU1b","Alvorada","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qpX6JtTcvyPS17rw9hyQ","Amaral Ferrador","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("JEO1FXP8I9Jgck9jxWEz","Ametista do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("mlexupanSxmaetJdRbnI","André da Rocha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2czoeSEHPT0GiOVlfJxQ","Anta Gorda","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yzwd0yXybbjUJnrZOPe8","Antônio Prado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EBaobboLVwipVq6njoNc","Arambaré","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("055GWzIWhOQI4vqvGNWO","Araricá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("lKzPkuhIXZA2sKFcvYV4","Aratiba","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("v5A9VJmK9Uk4UKZQf5TW","Arroio do Meio","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("mumVmtTcZDkmGZYRV6wF","Arroio do Padre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Eo777e1VwK0Tqf4Ukoxy","Arroio do Sal","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("XbU3qUKsxzpXper9vuMK","Arroio do Tigre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vwJB8U6sSFUE2wi87sLs","Arroio dos Ratos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("g8PgmrywcuWKTvOF2iJd","Arroio Grande","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vpcw78rIwu5vYdY1Yf4O","Arvorezinha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ZUWNU9xlj6GZYcmI9i2b","Augusto Pestana","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zAE4FPjOaUA3DkJg4psu","Áurea","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EeZPXckmq3zaadftmRrC","Bagé","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QgU8HbRadX2IaPKmbmyO","Balneário Pinhal","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("3o7jLWm3txvEho6mwsDY","Barão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("bXkgcWhr8wNj9NMroxnp","Barão de Cotegipe","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("KYzNCBHRwiiJnwjYWzuU","Barão do Triunfo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("duvhFkD48sfNjn4K5t7s","Barra do Guarita","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WPXerndMjnZOkWiDsGTn","Barra do Quaraí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pF2ARsLKNwcdThAsxOny","Barra do Ribeiro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EiUmA8uPYYAW9Xaz6t4c","Barra do Rio Azul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7v64sP7sf72TxYGfSgAe","Barra Funda","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qu9O0PWw7x46P58k2VfR","Barracão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("DkMq756xuLaSBc5TKTaV","Barros Cassal","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("f7igRUbf3eQWtGphYF4K","Benjamin Constan do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("s3g3QIv4oPw2t1bt3iXW","Bento Gonçalves","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("e5eqhAIcD6PPL6bX0ehi","Boa Vista das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("SMihVTrzxzutUo1BA6A5","Boa Vista do Buricá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("YJTG8rHDfOuu8QboYYfS","Boa Vista do Cadeado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IKKawYR4eCWqN5lz3oyE","Boa Vista do Incra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("E3Nr8JnHinyBIWZrJdEH","Boa Vista do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("VddC5WeIvBjAUMawoY2z","Bom Jesus","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("RtCa1x1kDjKeow4oeumd","Bom Princípio","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("RKITKD8uuQNn8MxmF57H","Bom Progresso","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zdviFRW217iPzZhW3UE6","Bom Retiro do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QhYpk00kR9Sogk9b5Wlx","Boqueirão do Leão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("CftA2gbMtU8BjxD2R035","Bossoroca","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("nV2DNnynS9bFkWwAozyV","Bozano","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("biJ7Sl9Q2t8EWdFH30GJ","Braga","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Apj9s7QESx21FtyNcXkK","Brochier","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("CODA3MtwifLQFHrpCBXZ","Butiá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LhzwL59dRyoKMlwMYhqd","Caçapava do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HIJx4JeWpqls4eErtq1o","Cacequi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("YdoPbSXPXaxUGl0NdPgw","Cachoeira do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("GYDfJ1Zgnn1wdZuTEsIw","Cachoeirinha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("JPTkdOkx7Qf9WKorl3Yz","Cacique Doble","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("O33EkRuO5R16wXmxayiA","Caibaté","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("UMEpGdNHYW458AMQnepE","Caiçara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xGeC2VYOxZDretKUueZi","Camaquã","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("w4r0SrxWwnJzJceDrHFI","Camargo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vUJpew2CrLWnZ6Xxx8Bj","Cambará do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7LulQ50UB5BJEkVE4Svj","Campestre da Serra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("psLXn9JsNd1qBTp4bmen","Campina das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pGlZxrx7kfup0YfUb3HV","Campinas do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HspugBkmstfvn2BELMQ6","Campo Bom","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("krmQgOgepYZETlF2kgLH","Campo Novo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("AdtymxfpTDxuYn1EN6Iz","Campos Borges","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hVipnY0tzlSB6IJXhCwP","Candelária","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4ADNS7FNWoypfqCk4Op6","Cândido Godói","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HtAD5jmuTu43s1bwCoHw","Candiota","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("r5OlztDNDczJfhVRi1VG","Canela","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hHt8Sg5kxlW15e4M0XLs","Canguçu","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WjCABk7OFOCcXFeeFZTY","Canoas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Ns0ZPaiPWpdt6z5IbZZi","Canudos do Vale","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("tnKtqU9dLDufylucIxK4","Capão Bonito do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("tFatcg1YPVH4b2mwGt4V","Capão da Canoa","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LTZ2lkhT7JSX3PbQtxOt","Capão do Cipó","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("FXhcA1AGP7CP52NaBOW6","Capão do Leão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yHmXMk8z8VTBENcjbdT4","Capela de Santana","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EiJRAWH0ujLaUy2OEKTg","Capitão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yihT6oo6hJqrbU9KclHZ","Capivari do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ZRewkvQpyYCmjk7vZK7F","Caraá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4cDEjILWPeA008XU5O8T","Carazinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yaEfCopPbhMURODYx5xe","Carlos Barbosa","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("kDzADaBIGPE68ke00dQu","Carlos Gomes","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QC9z7p1QbNFubR8QJnGc","Casca","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("F83W2NtOkF763bGowHXV","Caseiros","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("h02Yl7HDwGWWb8ny4ezb","Catuípe","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pXABIrxPSoCeIMI0CNpj","Caxias do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("bxqqFWMh7Fw5rM1A5V3a","Centenário","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("CeVbQgBW2WMNZWEo0TjY","Cerrito","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ZSKgzYZKUlYloKtFP7VS","Cerro Branco","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("r8OnnEqNXUX0mG3YNRC0","Cerro Grande","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7XOajcOtDjZgGzHUEBn6","Cerro Grande do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("or2AgT2J1q2v2nc4oFpW","Cerro Largo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("y4JyF0Ji85ZhM6H5zqLb","Chapada","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("p6nR60etwSPAc55SbcGU","Charqueadas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yOaHgNpBdpCqLVxV75yO","Charrua","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("wNKkUOWwxueVEEj0b3by","Chiapeta","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("dWO2URkhjIxRqxLKGb4Q","Chuí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IefMeF2duJExHecEYLrc","Chuvisca","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("sV5JfyZ5ucbRaIHUgfBY","Cidreira","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hcaYbxyfAudfcaIQucMK","Ciríaco","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("aXuVOq2U3rEUFKjOS6pz","Colinas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xZe8I4ni955E2WzXBYqT","Colorado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("laCjFZ6jlQehXuhQo6wL","Condor","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9XJsfbKLsqGCDRh9qZKA","Constantina","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("y1orddQvMcXguSeo520w","Coqueiro Baixo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("wXSgSnjqDiuLOXxFW80r","Coqueiros do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("kQFxU71yWxh2otCU3hHA","Coronel Barros","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("N6bxJaDKLj2hO3WtiV1L","Coronel Bicaco","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("UWhUzPzRfJ5f0O11tlcA","Coronel Pilar","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("3ougEISwVKyHXxar3mW7","Cotiporã","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IoPZTeRA9Dekx8XztPIw","Coxilha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5aTQ3X5XjeLTb4koVJFJ","Crissiumal","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("dq4K2RqjfAu4A91zBSWc","Cristal","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("q4fpS9gmVkGPu2dQwyGj","Cristal do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QTeCafDA7OZuAMLIj8Zf","Cruz Alta","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IdzJ55FecYEKipWT62pa","Cruzaltense","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("z0Jr4OA2LVWNSdW6D60A","Cruzeiro do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("THadfTbjdp8ZOJmbU0Nq","David Canabarro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("av5HITLBHmayZxq50HXa","Derrubadas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("n71Vjr7iGGCQbbGJ7zG9","Dezesseis de Novembro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LJdwDDhDxDifccklekSV","Dilermando de Aguiar","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5urM7wBuWDVBMNOh926s","Dois Irmãos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IqFUV6wBoWDbU3RDapFS","Dois Irmãos das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("aUMB8JJvsVkk1EeUu5bp","Dois Lajeados","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hqcQheRi8NtOEaBoZICx","Dom Feliciano","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yOy2dhNdmnQGBFnZm2yA","Dom Pedrito","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Q6Y4owSofmuZjJEiiJ32","Dom Pedro de Alcântara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eQiLwL9Lp9hc0QczFjXO","Dona Francisca","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Mblx8jtr5GSZsj2B5D3S","Doutor Maurício Cardoso","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("NveNW5UumJU63rkCXBXR","Doutor Ricardo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("POSEJlLzoXN5JJESiPTR","Eldorado do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OPFZgFva0vtLKLSF28Vr","Encantado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LTWo1Vgz2knMSNOZRuEc","Encruzilhada do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WFqqCOkUkCvSga7pLqY2","Engenho Velho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("6YmNQipMpCv5aXG7u6kD","Entre Rios do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("6yAkrUhcPhP8nwloPH87","Entre-Ijuís","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("DZoDon9UkcgCZzYUrB0L","Erebango","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("aKmxFe9d6s7RHW0OmFBf","Erechim","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("MZPJPW52CimS1aHKOSkO","Ernestina","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QbjNYqCy10mGG8dMNBEP","Erval Grande","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("08fBYR2pQBWOSPEOed4J","Erval Seco","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LxhvuDOYymxDlfs07rCz","Esmeralda","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("f51uObsPHja92urXOohm","Esperança do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pMmbfbjDPjf4mkPsNNcV","Espumoso","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("L0o8cfxnBqUAjcjrkzGY","Estação","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("6i5H3Hc1cYZKjrSnIfDI","Estância Velha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xyz3OgnW9GaRbB8luRew","Esteio","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Q5Kq5vvR87kPIk75Hs3Z","Estrela","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ko5yzaezldibEg3SDYLo","Estrela Velha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("t8TDUwIDp92hX3kxONYn","Eugênio de Castro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4uMVujXAlijJWAB497YV","Fagundes Varela","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ncGFUf5u9KQzf21Wprzl","Farroupilha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("JwFBKRSx6TkaQBiI9dDE","Faxinal do Soturno","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vvWP7JtMCnZZg4pUpoes","Faxinalzinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xgEe5zTdf6h5Xm3fkjaV","Fazenda Vilanova","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("O50BqcfRKGhkoRqV0NSZ","Feliz","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("sqGg6qecKeABG5lFud98","Flores da Cunha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1F4T3Xj7sz5zG5S2jPtp","Floriano Peixoto","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hrlMdkHinEbHyiPMqw1i","Fontoura Xavier","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("oSEsNdJPOS9PpKaybbuB","Formigueiro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("upPVZNUwzMKyhkBFzJaw","Forquetinha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eChbr7YLHZeJaYCcwEY2","Fortaleza dos Valos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("NavtmfcioqHE7Rugr3XV","Frederico Westphalen","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("88qZR0JDaFY5qkYfXngA","Garibaldi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("rwkpFumoBhvwnGYCch4i","Garruchos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("D08wUxLMzKKBOuwxeDSo","Gaurama","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("jroAdW69judNsxlscxIc","General Câmara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1oKmNSEwbOFTlZkjQ5oZ","Gentil","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("0YdmuDqqBMM1USvZsyfu","Getúlio Vargas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HPfEeSqzFyHzq59Oa1WD","Giruá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("JdjYxV3LZxIO9UZfGodX","Glorinha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("F70IgZjZL6wnzrTfMzvH","Gramado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("P5Mj0fwN4nH1Ra6JKskc","Gramado dos Loureiros","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("nOkvd89fekiCUNc1FlKU","Gramado Xavier","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zSHukwd4XnbJNbOLbeFR","Gravataí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ot1reppLlnon4wwjrK6q","Guabiju","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5UJUYMVsgk9V55t1vLJe","Guaíba","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("0mFLpLzoMoIh3v03325r","Guaporé","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("iMAamrWZ562Gn0RhH100","Guarani das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ksT2dM419Fya8U4XwHAS","Harmonia","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("N1wUBZdamLHaad0b63b4","Herval","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("O1cAL1bUivCnV6vAJWUU","Herveiras","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("dpA8bK65Noy7PfmpLqgZ","Horizontina","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("oCHjJLqWiFjCJq0w0f4n","Hulha Negra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("m8fTd21L6xFqQfKB5lNX","Humaitá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OPWgizT0lTsYHnsgdqQn","Ibarama","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("B4ApC60lVImlw3epbRbe","Ibiaçá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("t3wkrDsKISxq08V8fMrU","Ibiraiaras","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("8BSrFVCENF7onpKllAtR","Ibirapuitã","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OFz3RRBl1xuOkkfDgMIC","Ibirubá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EqV2mtNyHTdi6jtrGbUU","Igrejinha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9XyAnRqjWw3hEDTrTcN8","Ijuí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qtRWvQBJPzQtw4TqzHpH","Ilópolis","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4JoUtBy0QPyPlqJQe92u","Imbé","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("aGsbroq1IgSTuWPApleN","Imigrante","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("cET1eh5tSBVvaIGtn7WZ","Independência","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("MRBNvQxInL1D6St76cyN","Inhacorá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("R6slb3QvXvdszNa0EiVs","Ipê","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pkwDlgtUt1uGyzk2lqhw","Ipiranga do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zAyDg2u2FW3YhijNuIdl","Iraí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EbJiSiQPOuPIIsqwLw6a","Itaara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("USslUhm4DYIgm3x8GTma","Itacurubi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Q3SNf8RrCzIkCutmkEfA","Itapuca","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("VLVYkDlAbSZWcZNUyge6","Itaqui","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("MOiKFkEWQurTX8a3K377","Itati","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2TM56LUXYTeVTymbioAk","Itatiba do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("FTmx6jmyn0tFYAfyUFRT","Ivorá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zytT6ZsjO56OXpWitZ0H","Ivoti","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Z22bR1h3Oflwc5iyhzLp","Jaboticaba","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("F7sIs7A8bRdX0N05qSTq","Jacuizinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QSGO78oSQKnIwD97LZKH","Jacutinga","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yfJ7IcXXohWGnqyXSOli","Jaguarão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7R5k3KCAnfWN3B22pcGT","Jaguari","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Jz2FTfwB2WchJ3RdKIc8","Jaquirana","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QqvK7edZw3zXeWClJvuS","Jari","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("NmoEcu3txaYTfVZULVmX","Jóia","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xBYthLL1SSYLg3ndxX8k","Júlio de Castilhos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("cCuw7sGVaEzJgjE9kRNO","Lagoa Bonita do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ZmmmJQ0TtAIMYLs92tlH","Lagoa dos Três Cantos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("AdCK9x59F0f21QNswvsz","Lagoa Vermelha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("R3JZR4bbdto201YXudVX","Lagoão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("omSZ42xhQoqgRFJZMq6u","Lajeado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1aLjBPeRKIxzEecI7GAT","Lajeado do Bugre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("piXicaPie2S38cO2O1vj","Lavras do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("lLjH3R0JwGxveMzLCxX5","Liberato Salzano","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QC0x0WWKUYbrfi55sc7k","Lindolfo Collor","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hzcDZas89I3RZS2pH9nw","Linha Nova","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4bj0E3ATGXRIJETAPT3U","Maçambara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9PGm1YMevf70E0mqKPOG","Machadinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IarzULN1FunOsXg5X5Jl","Mampituba","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5yBR7SQK1uv2vQ2UxdyC","Manoel Viana","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1Nf7I5bCoPwjXN5oiteS","Maquiné","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4T7w1glVRgqxQyqqEj1O","Maratá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HfOdlIEXk5JXBiKJpaCo","Marau","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("z4Eqvu66qx1J1TMK1ikC","Marcelino Ramos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OCzQIpdrSi2su2iBJ2JJ","Mariana Pimentel","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("MkMUAq2uzlnnIKz2bjxr","Mariano Moro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hCs3yxQIJoe3nsjLzZnu","Marques de Souza","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yDpUTH27Q96yte8bQFOf","Mata","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("oaHnyMMi56k4O3uvE8p5","Mato Castelhano","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2pCg8gMJ8CDu13ghTKjt","Mato Leitão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5ipZLq5QU0W3H1tnLJ9W","Mato Queimado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("cVrnE0PGlCy2y5fzREnY","Maximiliano de Almeida","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("UlsG5m9PxcBD6YAugWhE","Minas do Leão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("YHeLaa5ZwD4KMrIKwYnm","Miraguaí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HVOZSFnRs7P0zcmUYJNV","Montauri","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9mEIx8o3otWwYmUoRnUf","Monte Alegre dos Campos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("6niIKLLdxMQBwz11SYlK","Monte Belo do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("h4kzl8JPXzfEDRIbK8D2","Montenegro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4n7WZPD8OHPyAwxIkcJU","Mormaço","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("0ZznsY2m6GMzcV0cqY9P","Morrinhos do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("CU98TzlAircgsjYsyNX8","Morro Redondo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("staVaBA1DsttQO0c0Bah","Morro Reuter","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("arWCz188IoxAubhANyAS","Mostardas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WCC8X5RZ6D0shcUJmOo9","Muçum","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hbZRZVitJ7WSeqWyylP9","Muitos Capões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ClmuiJezXNgLOZw6SW4m","Muliterno","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("lgr7bx7X8dylKdLvZxQ7","Não-Me-Toque","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4gAeZCamj6YuOmsbhSzb","Nicolau Vergueiro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eCt33JBmn49gjlB6RnA0","Nonoai","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("PBB5AB0X8N4kN54GhZkD","Nova Alvorada","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("jtmbQvzDNPVswc8icchH","Nova Araçá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("aoLykacvypwAGu1lOLyT","Nova Bassano","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("UYuGhvEiRiTRK7nBrV4f","Nova Boa Vista","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("r9SXLhBD9XvKdtLjyIo5","Nova Bréscia","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("mTgaMnkv7j6vCnOuAmHq","Nova Candelária","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("RtOYKMiJS6sze81UonsE","Nova Esperança do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9FPK6Jyt2beT4TbvOSXK","Nova Hartz","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OYmO0zUKkBVchX8xCRbI","Nova Pádua","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("fq9xeAEJWxHGgwF85Zbo","Nova Palma","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("uNf9e0Cl3JZzfjSperqG","Nova Petrópolis","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("dkwAu0jPJ1Zf3vVfxElV","Nova Prata","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("wWaY8WHG90Ljs6wcjlI5","Nova Ramada","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("b4xrHWHHpRqStWolTLhF","Nova Roma do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ZHpOXDe0Hln1mTK5WlsV","Nova Santa Rita","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("jzgbT1YgIr59fPb8xoPF","Novo Barreiro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("cNSK5YJOiEkOgmzwMOdZ","Novo Cabrais","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("TOYaAffLiRK8Qut4PVeV","Novo Hamburgo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("d2fmHsqwuKKdn7dRkt9s","Novo Machado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("AgVihhR6OqZlQxYWIsmB","Novo Tiradentes","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("TbDGxFeecJM7TmlkjXyv","Novo Xingu","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("laRb3pFIcnDKYfFVjmVk","Osório","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("RBk2deJnolCdBJQWEfQo","Paim Filho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yME79ipgNkf7x8ddvxZa","Palmares do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("bQyjTMchRBT07xoXLXBK","Palmeira das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xY6Ms3Wpjnm8ArUzKV39","Palmitinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("GSJaO63RPjzNQN88W0Rp","Panambi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("gEDmNfaNIDKUrkMKDL80","Pântano Grande","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Kkkgvp94ZXqflaxKBwNr","Paraí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Q1s9o1Y0pzQhVEhaSnaS","Paraíso do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("gwPLKZGvN1bP7VCI4c2m","Pareci Novo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("fliBqOnvXEMaREb2gBL9","Parobé","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xK0laiWGLqUYCsKdQWXL","Passa Sete","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2Yqzkck7mL1dCpKLWkFT","Passo do Sobrado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("RRkadjsyJOMWQXMmf0U8","Passo Fundo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LFe9EbiJTAE45D84iqyh","Paulo Bento","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("l6v6kCnB31AU8u44HxIF","Paverama","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("KIXzqZF1SrrNymYYQq8c","Pedras Altas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EtqCqlQHclU9WOFjQrCx","Pedro Osório","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("CUXxjSxLQN5wZmIMgoQj","Pejuçara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("tBJLW2XWyvXLNYAWGxtb","Pelotas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LoJ29DVj66U0FkRTfnt7","Picada Café","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("wUORYwv5N5AaFXBlN0Fl","Pinhal","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zzqoziSFVYWNjXZmXn3m","Pinhal da Serra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("wYnqrQvDgw08qZ4S4xdY","Pinhal Grande","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pCDzHokUNXFo3YqUgR07","Pinheirinho do Vale","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("o9JTeKGNlwq8RQ6A3rVz","Pinheiro Machado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("TASD1mLSkqTvqL0cd2i8","Pirapó","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IGHoDSgZsjbXuG2CKBDT","Piratini","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("0JDuObBCqJS62X7ArfIF","Planalto","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qx3GVJ3JIBOzPS6YOyzP","Poço das Antas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("NoqPDHyhX5RSFvPmJ36t","Pontão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("tdGNg7FWUo8bWMHBFlUV","Ponte Preta","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eldmC7xnhXRvzNnTeK5h","Portão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("fhCqnoCjqZLWOCDOzJ3d","Porto Alegre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1fOou7ZLUwQilOc2TmlP","Porto Lucena","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Rzw8EWas0gAGqUxTYGxF","Porto Mauá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("PnXey7kJOwzmcPvWJgQq","Porto Vera Cruz","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("r7MGVXDfSEW3BoCAKp83","Porto Xavier","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xSiSdRiDuWGvYAZhiQLN","Pouso Novo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("sGYXFMSrDECtYnn2Gs4O","Presidente Lucena","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ahIPDDqf84iUOubLUjq0","Progresso","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("m8CXLiNmPR5aXcDNeYjK","Protásio Alves","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qUkhj4ZrhntYYGBY2c3X","Putinga","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9jcpcCYYYMglP2WTIlCf","Quaraí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vrKbftguK9XGhP7XUimX","Quatro Irmãos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hoHAAIJFLKfx2YVnYxFY","Quevedos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("PDkobz4WXAAjPyvuQNnx","Quinze de Novembro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("fLMKR3Oh8USew4lPwhBt","Redentora","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("m0OpKquH4nTYIydoBI8f","Relvado","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Tp7z6kAFhioBpSTiOD8W","Restinga Seca","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("a5KshE3MoZppug0yCxun","Rio dos Índios","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("KA8AT1AB2WMptQwYeRE6","Rio Grande","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zxzlknEjM26UCj15UXFz","Rio Pardo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("gvwuQUyGoYVNcBEsPLit","Riozinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("nIsgUOCGGR8fIyz1EGl5","Roca Sales","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("SC2dkdlwt9CTsfLHmtxb","Rodeio Bonito","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ItYiWRBkykV2mmrxBJnx","Rolador","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("CT2PCXemCuu3emvTf98P","Rolante","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2tZuGs0KjD5IYhsBC19U","Ronda Alta","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QSg8JJHbBr48xSO8va7k","Rondinha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5ZJMkU25lQVaeeJXjMiy","Roque Gonzales","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LlFRSzHx86n9RjMIe5dd","Rosário do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("etBE9pnOiiHJ2RmYqi6q","Sagrada Família","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("jCJjkWjBElNeNYaZXyO5","Saldanha Marinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("tvVGvIwJIcnkd1XccTgS","Salto do Jacuí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("8VYJXpiX8UfUkoh0rT5i","Salvador das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("OKWEZpma6eaihC9875aw","Salvador do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qUqtSr9hKI94TQ6zPp1F","Sananduva","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("l10obWKaRPz1a7bx5gW4","Santa Bárbara do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("XvOjCHfCiN1LtfyLhbH1","Santa Cecília do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IpvSWU3sKFdw8y4gyOhg","Santa Clara do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("klqSxZn9aJ7y2zlvbwWL","Santa Cruz do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("MvI8r04ToRZOcYMd00Yh","Santa Margarida do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("fYCnhYkfoTCaVnOzu6ov","Santa Maria","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("kW4CLwzfheb3ZwgrdVKJ","Santa Maria do Herval","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QcoVwUCQkIrQjSZXSwMU","Santa Rosa","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vRzw8HQg6Ok8GrsYGDxi","Santa Tereza","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("70fwAyTjl1YbDu5Ql2wE","Santa Vitória do Palmar","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("duZjuyO2yQPMShaR68m4","Santana da Boa Vista","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("pbw8fKbQe9qb4mdBXAjp","Santana do Livramento","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("tkwP4zKLaWC9UgmrsLKE","Santiago","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("poVzi2PjHF3qaRUCGCF2","Santo Ângelo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5naosiJbxc1YOqtMqNMl","Santo Antônio da Patrulha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("AEKgc48o3iec20ffnQYo","Santo Antônio das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("zZ7Zozk6XxMAqQ63bsMB","Santo Antônio do Palma","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("TLEj94uJVhjbRUUnpZ5L","Santo Antônio do Planalto","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("kQGWeicdeB4GzNRZNFAJ","Santo Augusto","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ZlUelZxijKsRfEVAc79E","Santo Cristo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("6mFhFEpsxj9snIZrM89B","Santo Expedito do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WYz2VBeIn26onvUzxMaC","São Borja","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("f8cBTc8kPLojsHSQXXXr","São Domingos do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("KL7dgZy68lsN44kN3AuV","São Francisco de Assis","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LcdiMu5BErZdEKqNxLRv","São Francisco de Paula","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("QvSldvfHHpn8pNT6cn7L","São Gabriel","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("3mF3abp4aUY9oAu4JKor","São Jerônimo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WZAneC0M8UJtCShrOe9M","São João da Urtiga","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("8fIZNbXzZxyJa2nX8ivq","São João do Polêsine","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eYJZ0z6AHVFaIirDdUN2","São Jorge","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("AHForJk8KvfCyJJEHGkt","São José das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Pm4jUJI3i3EgLLq2jpAJ","São José do Herval","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("hiGZ8FjHBwCbQIhjKSuk","São José do Hortêncio","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("3lxKURgLYAZAsGzbQ1Vu","São José do Inhacorá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("K8rxblYVs8Cl8B6ag9xc","São José do Norte","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qABnUxN9HKWGEiGI2vh1","São José do Ouro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ARsQj7VqM4Cnm7CLD5fx","São José do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("XY7M0YY127WSO65r4R4O","São José dos Ausentes","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("rnaHIqb0IDZDAtA2GZBG","São Leopoldo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("O3JOrVpHPD4ZMmpfICcd","São Lourenço do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("c2kWPMJohQUnB3SmMzf9","São Luiz Gonzaga","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("uOD2RUqSMPrJg2gKleIK","São Marcos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("O9WnKVrG3hUYWxx23CWR","São Martinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("oZ5M9wgTmTv0xXtiJzx8","São Martinho da Serra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("VbeQTYZCJE9h7JacvJ1A","São Miguel das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HdtTb0deB7keHK96WXPu","São Nicolau","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("YsWBXYIdDXfIy7Eklv7S","São Paulo das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("YUvyDuLgqX9I5lIKUEOh","São Pedro da Serra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("4uIwfZkVsxNgcQSWfSEn","São Pedro das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2T9yWgcxqLmaVdCN1X0y","São Pedro do Butiá","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Vn9bZFVwSiizEDWLa7H7","São Pedro do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("plyoZFtBWoA7fG3InxsS","São Sebastião do Caí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IaVXgHdKS7xdLZfCw83p","São Sepé","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Erk5lYyMPFpqRUTCKZIH","São Valentim","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("jxsBN4DR1FCbvcpALlXo","São Valentim do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("vg7htd81qy9ny3v59KMF","São Valério do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("AkKehTNEkvXpfWXTxKSD","São Vendelino","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("i9yiZdv6HHsR1DXV2Q4A","São Vicente do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("J3WUva3vN0bDk4DWZoNM","Sapiranga","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("SUsW4akzOWxEjfPKdotz","Sapucaia do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eMJUbX8RaBOYdbOORb3A","Sarandi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("MWAFvSP8QiZ75A4rptY3","Seberi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("cAALE6EKdEOtAgnXnJX7","Sede Nova","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("yflSpHZTsQsjHePr24jE","Segredo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("uFuXktFAwgrovDywvFnD","Selbach","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WwyVV8eXD6x670Q3H5gQ","Senador Salgado Filho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("p5D6blOXDBamLGGc1kOz","Sentinela do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1KmpXXqGJUypE7PuGqOX","Serafina Corrêa","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("225CobYp3MqCJQFLERLp","Sério","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("9jaTsNNCkOsbDW4855HE","Sertão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2ftl9rwXvIosuUykZBIN","Sertão Santana","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Gfm2V8KWc4FeHKVZ08n5","Sete de Setembro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("wz6n4xGOW45RALHyJckv","Severiano de Almeida","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Pb2rmBHH1Bj1LR5MRz24","Silveira Martins","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("p1c9svvbJJ5N4fdBCScU","Sinimbu","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7uWzBA0Dc5W0dUIvvngN","Sobradinho","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("i4IpfayuXysbncyG9JOj","Soledade","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ttzVBLh2C9oGpOt75CjI","Tabaí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Fa8GzryQzaLvsdQLVNyR","Tapejara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5lttFYYfWGgC8G9kg106","Tapera","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("clQ8D4Vs2hqhzhEnB6uO","Tapes","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("EeY8YlndUPO6rieSGPqL","Taquara","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("z5AlodqkY0ihUQZTAcVm","Taquari","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("x1DUr9W4liPedm1oSQbp","Taquaruçu do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("66vNvDJca5UDnflSLMwK","Tavares","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("SBKU7HdtlwzoUrKtjCBJ","Tenente Portela","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("75sR19mp6wqlk2wqL2If","Terra de Areia","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("6V2G1htKhPLPI8YuzfGD","Teutônia","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("qsLjNG4oebbrbKuvkdxl","Tio Hugo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("reM92UzdypnN2qH114c0","Tiradentes do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("znnwyeiwAJ7Oqf2F89fy","Toropi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7QwmtK4IpkM6LfnTvzYv","Torres","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("rgV3K75XQ3davqWKiOE9","Tramandaí","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Es2qT9odAfUUGZLZQn3B","Travesseiro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("X2YmZjXYE0KEAZwSyVeV","Três Arroios","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("C4BLEMY9rH8hAD6nHgln","Três Cachoeiras","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("KKB94zBYfaOPRpfaOMc6","Três Coroas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("5DzKi7QQQLkvaBon4813","Três de Maio","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("0xr6DbvvhFxII2TNuqFi","Três Forquilhas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ass4ZejFntkuUZV1G6BA","Três Palmeiras","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("jOnyc2qqQUC4LaWnW3Nd","Três Passos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("n5HzIU3JgWX93n0PP1Ju","Trindade do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("dPPH5UbH7elb56qJOIW4","Triunfo","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("xAsIBikiePF0ITRyZ1oE","Tucunduva","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("U7fsgI1jzE07wqMn17Np","Tunas","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("BuvUSej1J6VKGM2H68z3","Tupanci do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("x9oADu5sfxVOIOdpGD5P","Tupanciretã","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7ZOb7VP7j8yS0IdUANRB","Tupandi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("TtagRaXjkRo4zqRky3uY","Tuparendi","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("c5EAhrfyjuWzyA7uPsjU","Turuçu","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("7qp1RV1cywgpaswpHEnj","Ubiretama","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eRBQgzj7SyKONuWgAsDD","União da Serra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("1H6Et2ezGEGsIiN1sSue","Unistalda","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ugLQeWSO26woEZdscmu4","Uruguaiana","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("lroBLqpmBkL9xRrgGhyz","Vacaria","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("bpm9aqDR9Bzan8MgnaVc","Vale do Sol","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("HhA8T8CVl4YufNPKsFAU","Vale Real","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("VkH3DMb6oOfdVweKPRlF","Vale Verde","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IdzxWlVPnI6mqqYrYXfZ","Vanini","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("sMHPzKq8EhRQpUWrO0ho","Venâncio Aires","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("438GnofwbMtj9B0OPnoB","Vera Cruz","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("UCWxLWaRJIZVwWYDpqUO","Veranópolis","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("ozmRWjFA7gbx0yyQTAja","Vespasiano Correa","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("Gb7if7oYoVLtYjonRctn","Viadutos","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("PJqRlyZcZGqjrusrQYJq","Viamão","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("2CA90JUS4REDYHAtfqB7","Vicente Dutra","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("WtwF49cc6VG8wsd07BXw","Victor Graeff","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("LFYSApGjpBn10DxJoYzR","Vila Flores","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("VoIXA3te4LyfQKhAuikC","Vila Lângaro","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("j21oBQ6ZIoF4YXMt073a","Vila Maria","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("kGOuqGcffnUYIB4JHkVc","Vila Nova do Sul","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("IaRbpP8okglO1HT3PlTf","Vista Alegre","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("GSzvDeEoODBqPuBU9Es7","Vista Alegre do Prata","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("uEvbau9MNyAHGv7QZx5Q","Vista Gaúcha","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("x5DOpqH7ShnGY2vKyyJw","Vitória das Missões","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("eKIglwuMkLqGiPTQP3oN","Westfália","XE0DpyxK9DOXBlSqfma6", "RS"));
        lista.add(new Cidade("i7ohaG3ZzbMUCXFA2SgI","Xangri-lá","XE0DpyxK9DOXBlSqfma6", "RS"));

        return lista;
    }
}
