package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class SC {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("PEb4SUVBJtua8OinzH4t","Abdon Batista,","SC"));
        lista.add(new Cidade("DfrHQp9ouHEVwKqr2tw3","Abelardo Luz,","SC"));
        lista.add(new Cidade("enClWCyqBF5PDWJYs1fc","Agrolândia,","SC"));
        lista.add(new Cidade("YgR9xpda1WsnjpuzjOqb","Agronômica,","SC"));
        lista.add(new Cidade("4mw3Vs2ZoId0bjsq4rFD","Água Doce,","SC"));
        lista.add(new Cidade("yx3viDe2PHvtT5TfSD0n","Águas de Chapecó,","SC"));
        lista.add(new Cidade("CqnAlnlzxGKSDdwUR0YR","Águas Frias,","SC"));
        lista.add(new Cidade("sPItI4OfnPsmMVGPphtS","Águas Mornas,","SC"));
        lista.add(new Cidade("j7QD9yadnxgh9JxKcsF7","Alfredo Wagner,","SC"));
        lista.add(new Cidade("6GCTH9uZ41HzKUYeB1Fz","Alto Bela Vista,","SC"));
        lista.add(new Cidade("JEFUAQxN5Qb740UgXldT","Anchieta,","SC"));
        lista.add(new Cidade("LyJBIvSk2JuTDVEk8GbL","Angelina,","SC"));
        lista.add(new Cidade("uSmTLSKQogbBvkmwp5Ec","Anita Garibaldi,","SC"));
        lista.add(new Cidade("tkq6mz9D7fZTEUQ6Vs5H","Anitápolis,","SC"));
        lista.add(new Cidade("uWIXm4ZNv6qSkXS57cs5","Antônio Carlos,","SC"));
        lista.add(new Cidade("wA6C7CoJgpuYfrXQHI2n","Apiúna,","SC"));
        lista.add(new Cidade("zSd9g4eDIDVyqgvLo14w","Arabutã,","SC"));
        lista.add(new Cidade("sYWbBuHGxy4TNtmEK1OF","Araquari,","SC"));
        lista.add(new Cidade("c4eClBMDqroQCVfnmzQO","Araranguá,","SC"));
        lista.add(new Cidade("ZeujVVyvB5YVr5gCaiEW","Armazém,","SC"));
        lista.add(new Cidade("BA7j09olhsUaMBo5ta1N","Arroio Trinta,","SC"));
        lista.add(new Cidade("ETRuwfzBYHwtF2VAb8sC","Arvoredo,","SC"));
        lista.add(new Cidade("Ct9EzSxEdWLqHS5q08mN","Ascurra,","SC"));
        lista.add(new Cidade("wK6UBnc5uk37L2d0qcgQ","Atalanta,","SC"));
        lista.add(new Cidade("9aiMp3OW0VdvlxZAsZhP","Aurora,","SC"));
        lista.add(new Cidade("uRmLPhH7kQrXu1nwUdDQ","Balneário Arroio do Silva,","SC"));
        lista.add(new Cidade("2TQcrQCrwBc2mzap6WQp","Balneário Barra do Sul,","SC"));
        lista.add(new Cidade("uMVfocxmeZCj9KIWz5d8","Balneário Camboriú,","SC"));
        lista.add(new Cidade("uLHI2iNwxpsrnrXGDSjV","Balneário Gaivota,","SC"));
        lista.add(new Cidade("N4RPDkm2D6pHJtn1J3Of","Bandeirante,","SC"));
        lista.add(new Cidade("k8hqkBltzwnZDqyzGNB2","Barra Bonita,","SC"));
        lista.add(new Cidade("HR3hdMcfwHUnDJJkjVCO","Barra Velha,","SC"));
        lista.add(new Cidade("wMTAjy6vUeqcVC8MLpIM","Bela Vista do Toldo,","SC"));
        lista.add(new Cidade("UpYvooAKtWJxDTbOlbgo","Belmonte,","SC"));
        lista.add(new Cidade("xPuUPuQx1s4UoRslWQbV","Benedito Novo,","SC"));
        lista.add(new Cidade("zWnLUTFhAzzBSAuQuxyx","Biguaçu,","SC"));
        lista.add(new Cidade("En7lI9WmjJE10eOyXOSG","Blumenau,","SC"));
        lista.add(new Cidade("rGb13nh2OQLLf4oXX5yO","Bocaina do Sul,","SC"));
        lista.add(new Cidade("SNlcFtnR4l9foR5vUyQo","Bom Jardim da Serra,","SC"));
        lista.add(new Cidade("KopU30QO2mpgS33it73g","Bom Jesus,","SC"));
        lista.add(new Cidade("pQuZGJXFV5hOTz1K4eqT","Bom Jesus do Oeste,","SC"));
        lista.add(new Cidade("YdRMYOejyuucfihYjZkD","Bom Retiro,","SC"));
        lista.add(new Cidade("2xy22U7pVy9mUxmFwQqh","Bombinhas,","SC"));
        lista.add(new Cidade("lSVNMRyAFhdsGonY8hC6","Botuverá,","SC"));
        lista.add(new Cidade("w2U6krHMx1qcV6LEAvJ0","Braço do Norte,","SC"));
        lista.add(new Cidade("e9yKNCaAJUZFzjDHjmt8","Braço do Trombudo,","SC"));
        lista.add(new Cidade("P3atpAAqvwTyuUN3ZIHu","Brunópolis,","SC"));
        lista.add(new Cidade("SZ50wTamoF5Ocjqz7AJK","Brusque,","SC"));
        lista.add(new Cidade("5qCVIOyqSxG5Uc7WvCJh","Caçador,","SC"));
        lista.add(new Cidade("ubzR4alm0kNhXGMOyyj5","Caibi,","SC"));
        lista.add(new Cidade("e5GBkzvXbegDgaYybad3","Calmon,","SC"));
        lista.add(new Cidade("UPc027c3LxyH36hp3zee","Camboriú,","SC"));
        lista.add(new Cidade("ElkBSZ32FbQy5L1uGUeV","Campo Alegre,","SC"));
        lista.add(new Cidade("erToCMp9LxRBTRuRHfGq","Campo Belo do Sul,","SC"));
        lista.add(new Cidade("hOHfD9T4vZ1FMNQhBiNI","Campo Erê,","SC"));
        lista.add(new Cidade("DvSIDKlDNcyXNigfrFtf","Campos Novos,","SC"));
        lista.add(new Cidade("NBH7ubBieTtEo5rCXwG5","Canelinha,","SC"));
        lista.add(new Cidade("cOcu9xzQvetz5zsbIa5c","Canoinhas,","SC"));
        lista.add(new Cidade("fvnqdddzV9q9ser9a3Bn","Capão Alto,","SC"));
        lista.add(new Cidade("o1SDduO7pLqiKM0N7Pkf","Capinzal,","SC"));
        lista.add(new Cidade("0dGnxxFHuiGYMEx1m1RD","Capivari de Baixo,","SC"));
        lista.add(new Cidade("mksFC16fMTkHYcShOq5w","Catanduvas,","SC"));
        lista.add(new Cidade("QzwzgS4Q2FuKMdOcvJTS","Caxambu do Sul,","SC"));
        lista.add(new Cidade("Nqhs51f7HTIfmLTEhPSe","Celso Ramos,","SC"));
        lista.add(new Cidade("z3yLOVVyHqiw3Fr9vaur","Cerro Negro,","SC"));
        lista.add(new Cidade("VOQUhsSznG46S0BMIvrk","Chapadão do Lageado,","SC"));
        lista.add(new Cidade("QqtbhMezHPfKBgV4A2N0","Chapecó,","SC"));
        lista.add(new Cidade("Ld0EMdqe59ZvoPSPUvuq","Cocal do Sul,","SC"));
        lista.add(new Cidade("LRo4VQQPjU4R6UTr9g0i","Concórdia,","SC"));
        lista.add(new Cidade("KkIg1AewCCvokjzkk8rd","Cordilheira Alta,","SC"));
        lista.add(new Cidade("nbGglxyzO4cQCFx7YgnL","Coronel Freitas,","SC"));
        lista.add(new Cidade("CJtka9zSs2wbx8bevnfF","Coronel Martins,","SC"));
        lista.add(new Cidade("Z7uNcgZJLJvdNKKwv5gJ","Correia Pinto,","SC"));
        lista.add(new Cidade("vBBjpA5LeE105HQFPVOS","Corupá,","SC"));
        lista.add(new Cidade("AnOSYYokoiqbKwENPc3e","Criciúma,","SC"));
        lista.add(new Cidade("RIVraTYMTDgD2KptmBL3","Cunha Porã,","SC"));
        lista.add(new Cidade("f4kCspNVCs1ZOJlrVmTV","Cunhataí,","SC"));
        lista.add(new Cidade("51GIIJsS0ygXFlYIlnyx","Curitibanos,","SC"));
        lista.add(new Cidade("rxlx5Cc3nWhgCv7Cchhe","Descanso,","SC"));
        lista.add(new Cidade("lqud9WImvLLEIxywegh2","Dionísio Cerqueira,","SC"));
        lista.add(new Cidade("s5CuqKc7xsrRLFbWiOwe","Dona Emma,","SC"));
        lista.add(new Cidade("kPaKqislZTua4utXR2e7","Doutor Pedrinho,","SC"));
        lista.add(new Cidade("JD0Cd2EhVhp5JG4TX4px","Entre Rios,","SC"));
        lista.add(new Cidade("PGOAmFwJMBdPG8FpgtJe","Ermo,","SC"));
        lista.add(new Cidade("0ZMdFky6KEhCWkOmY62k","Erval Velho,","SC"));
        lista.add(new Cidade("T5CxTry80mnzMRq7ine6","Faxinal dos Guedes,","SC"));
        lista.add(new Cidade("llNptTlngmpcVO018jfR","Flor do Sertão,","SC"));
        lista.add(new Cidade("Kf1jx9pVCLNuJXmLHYAj","Florianópolis,","SC"));
        lista.add(new Cidade("i4XUxw3C46uYM8wDveXY","Formosa do Sul,","SC"));
        lista.add(new Cidade("bI1eLQ30DUxBcaySVx3R","Forquilhinha,","SC"));
        lista.add(new Cidade("inPnubCt0mWew0Zvh3iW","Fraiburgo,","SC"));
        lista.add(new Cidade("tfqtemQ5uxPKJHXYwAAn","Frei Rogério,","SC"));
        lista.add(new Cidade("wBtx0wW0r7SWwt6iCPgD","Galvão,","SC"));
        lista.add(new Cidade("gAPVWNMj25xECgRzVh9Q","Garopaba,","SC"));
        lista.add(new Cidade("gss9OqsqrP2GvPrZzSfu","Garuva,","SC"));
        lista.add(new Cidade("r8HdMiBlX18Bu4Mn3Pbu","Gaspar,","SC"));
        lista.add(new Cidade("tKFLCWlW9VEFtETxwtJz","Governador Celso Ramos,","SC"));
        lista.add(new Cidade("AeA53AaWPscNs9TgSQdC","Grão Pará,","SC"));
        lista.add(new Cidade("OP57J9IGm5DwdvYhB60m","Gravatal,","SC"));
        lista.add(new Cidade("v5NaUfc23S3EKDBaAWjT","Guabiruba,","SC"));
        lista.add(new Cidade("cVpWRv8w2uGwpYAcbCxQ","Guaraciaba,","SC"));
        lista.add(new Cidade("ggXe1imTPos0bvLk6ttf","Guaramirim,","SC"));
        lista.add(new Cidade("uTT23QkGk0kqYGbPqoWW","Guarujá do Sul,","SC"));
        lista.add(new Cidade("VhXurR2c4r499gOD0Hhr","Guatambú,","SC"));
        lista.add(new Cidade("Zuh5QnXDPKBioHzxy8XW","Herval d'Oeste,","SC"));
        lista.add(new Cidade("of9bCvTRP6Fmcaosli1X","Ibiam,","SC"));
        lista.add(new Cidade("7bs1fpcmYF5eW8vaNypB","Ibicaré,","SC"));
        lista.add(new Cidade("sj66XDnrAlTnvS3SxOcR","Ibirama,","SC"));
        lista.add(new Cidade("TEYElbZK60DrZljKBlv2","Içara,","SC"));
        lista.add(new Cidade("LTWgeoG2ZkJ8iL6geo9v","Ilhota,","SC"));
        lista.add(new Cidade("oTWjbjdBOQX1lduvHECT","Imaruí,","SC"));
        lista.add(new Cidade("MK0QXLdgHuguaYiDevvV","Imbituba,","SC"));
        lista.add(new Cidade("Rxtefzbn8Vldwd8c2MI0","Imbuia,","SC"));
        lista.add(new Cidade("RthvCrBrGS55J3pZuZSH","Indaial,","SC"));
        lista.add(new Cidade("wGbiAHwdXyEQaCnLtYFh","Iomerê,","SC"));
        lista.add(new Cidade("2aylmgT83ao4V4FGtumy","Ipira,","SC"));
        lista.add(new Cidade("8geBCo6otgX72uzRyG5C","Iporã do Oeste,","SC"));
        lista.add(new Cidade("Cv51nv1n6RRHvT8iTHzr","Ipuaçu,","SC"));
        lista.add(new Cidade("A74LlSU66wgFOqodGmRN","Ipumirim,","SC"));
        lista.add(new Cidade("2LSqaXIx1TpCBWVHLcGG","Iraceminha,","SC"));
        lista.add(new Cidade("Ow3SKqynR9UiWIVueMgj","Irani,","SC"));
        lista.add(new Cidade("N9o88sErX6axAbL91Cid","Irati,","SC"));
        lista.add(new Cidade("EkCIUXHivxjoFIvyfN09","Irineópolis,","SC"));
        lista.add(new Cidade("UZuEWl89SwJgBQFsl4DT","Itá,","SC"));
        lista.add(new Cidade("pMP5aKn9OT4XqfNOoY8E","Itaiópolis,","SC"));
        lista.add(new Cidade("ccdCQsvFkL17pGkSVm0a","Itajaí,","SC"));
        lista.add(new Cidade("vUaoKI2eev13xFeahyvD","Itapema,","SC"));
        lista.add(new Cidade("gaEjf4rapItiaNSYVSdR","Itapiranga,","SC"));
        lista.add(new Cidade("vRUie0d85SXnmu15pk6j","Itapoá,","SC"));
        lista.add(new Cidade("lvFcb1a0QSHCTU8sIRFp","Ituporanga,","SC"));
        lista.add(new Cidade("kPrjc6HijcZBtQA35qYb","Jaborá,","SC"));
        lista.add(new Cidade("APhqMEElzFZPKRIElnay","Jacinto Machado,","SC"));
        lista.add(new Cidade("5SwoeLtSUUZlIQEgzisN","Jaguaruna,","SC"));
        lista.add(new Cidade("NNkoLCw4Qi4mBjSGlutl","Jaraguá do Sul,","SC"));
        lista.add(new Cidade("kNtVJrcz7kuqbzeJTbJg","Jardinópolis,","SC"));
        lista.add(new Cidade("aDJNHN4NHQoM3ylGrKJ3","Joaçaba,","SC"));
        lista.add(new Cidade("CsqqjdENkpGkqlIag4H3","Joinville,","SC"));
        lista.add(new Cidade("l0nq46POJgdxvLuBgOuN","José Boiteux,","SC"));
        lista.add(new Cidade("EarwvqxK8olQtWTj5vz3","Jupiá,","SC"));
        lista.add(new Cidade("Q4jhC4DfXlPoC8U2zhAS","Lacerdópolis,","SC"));
        lista.add(new Cidade("3ZcWAjV9Qm8n0br4vHUj","Lages,","SC"));
        lista.add(new Cidade("sE07a5EyPZGpp7W59stW","Laguna,","SC"));
        lista.add(new Cidade("n3mOU1t0eaXVCDvbgS5e","Lajeado Grande,","SC"));
        lista.add(new Cidade("QqqymMgEtPSzocdOGa2U","Laurentino,","SC"));
        lista.add(new Cidade("gj4y5NIYRenQCdFanRXj","Lauro Muller,","SC"));
        lista.add(new Cidade("VIJ6oQbzCPl7HHrCrzDG","Lebon Régis,","SC"));
        lista.add(new Cidade("qjAQ2yMs8hwZR0k3UhCb","Leoberto Leal,","SC"));
        lista.add(new Cidade("ryv6NXwX1BG43YJXc1nt","Lindóia do Sul,","SC"));
        lista.add(new Cidade("t3jCgWcFo2dmqUvywFkM","Lontras,","SC"));
        lista.add(new Cidade("gKNNLHFDYYoD2KORL2VV","Luiz Alves,","SC"));
        lista.add(new Cidade("9V1hjEXkM6BRMRyw2iJ3","Luzerna,","SC"));
        lista.add(new Cidade("7BIzbTxglTEMAMOAVeMf","Macieira,","SC"));
        lista.add(new Cidade("OozxUcTnH0L50YYTrwSi","Mafra,","SC"));
        lista.add(new Cidade("VWIJHmY2FVyasJh99UyT","Major Gercino,","SC"));
        lista.add(new Cidade("YF3pViVSYOKS9xOztIvL","Major Vieira,","SC"));
        lista.add(new Cidade("Mpus6mBRshlOA6byeayU","Maracajá,","SC"));
        lista.add(new Cidade("mpEWyK35lMJg7xDq4vbV","Maravilha,","SC"));
        lista.add(new Cidade("KVMkYxO8Ze1yRN1u6cPa","Marema,","SC"));
        lista.add(new Cidade("pOH7lEjlOnsdGIfoeYn4","Massaranduba,","SC"));
        lista.add(new Cidade("5uB115PCxcxfbppwyoHa","Matos Costa,","SC"));
        lista.add(new Cidade("6Ap1QA0ecIDlXmdEz9A4","Meleiro,","SC"));
        lista.add(new Cidade("94OcDBnVnHAwi8fNPfZY","Mirim Doce,","SC"));
        lista.add(new Cidade("3EC7XCH2dsI4Emga7fuk","Modelo,","SC"));
        lista.add(new Cidade("oGl1nW4VkOG5cOmqHC0G","Mondaí,","SC"));
        lista.add(new Cidade("Hjy8DF5bExEA7mgmTXp9","Monte Carlo,","SC"));
        lista.add(new Cidade("2iwEl6pOV7Z1LiByIE46","Monte Castelo,","SC"));
        lista.add(new Cidade("AP0ZGlSrKvsrmZlM7PhP","Morro da Fumaça,","SC"));
        lista.add(new Cidade("OOkqJTEMa6tp9cij3IIx","Morro Grande,","SC"));
        lista.add(new Cidade("Xa00q73AzhpFdJGSpWnL","Navegantes,","SC"));
        lista.add(new Cidade("YzeBpNwEIlCyAtxzVkRs","Nova Erechim,","SC"));
        lista.add(new Cidade("XGnsk4eIkc2ANbd1Js5H","Nova Itaberaba,","SC"));
        lista.add(new Cidade("e31Hq49eimOKsz5thnIx","Nova Trento,","SC"));
        lista.add(new Cidade("4QHTxvt4DF0S6P6HPKtQ","Nova Veneza,","SC"));
        lista.add(new Cidade("QPt30JUrFq5P5Ubb1ijM","Novo Horizonte,","SC"));
        lista.add(new Cidade("qdYTWZhdBZv72amHg6D8","Orleans,","SC"));
        lista.add(new Cidade("4LS17AyuVlIfVQ02GUzy","Otacílio Costa,","SC"));
        lista.add(new Cidade("6BvVb8wa3eKLbdpZo8Wk","Ouro,","SC"));
        lista.add(new Cidade("LuMk5oPbP6zLNd1BVPUR","Ouro Verde,","SC"));
        lista.add(new Cidade("KoWtJEhepZAMZtykLuq9","Paial,","SC"));
        lista.add(new Cidade("DzzvCXCRtnUwxIewodxU","Painel,","SC"));
        lista.add(new Cidade("4YGmYtXIp1LyJymjis0Q","Palhoça,","SC"));
        lista.add(new Cidade("6InuBuhPtLpsJH2VoySj","Palma Sola,","SC"));
        lista.add(new Cidade("MJCbqYXKN5zGWyYuywjW","Palmeira,","SC"));
        lista.add(new Cidade("WO8eQye3jJX9GuYZgIZn","Palmitos,","SC"));
        lista.add(new Cidade("LMKR5rYv8sC9RLDT5m9O","Papanduva,","SC"));
        lista.add(new Cidade("43gS3BU0OAVZJXRB2MZd","Paraíso,","SC"));
        lista.add(new Cidade("3l2zgG3bsm4MI8RNjaQt","Passo de Torres,","SC"));
        lista.add(new Cidade("AmTSPQXAh9FKh4JY5A6L","Passos Maia,","SC"));
        lista.add(new Cidade("ygupdn6KpZzTiThXJaK4","Paulo Lopes,","SC"));
        lista.add(new Cidade("Dl5nlSiXb0IoD0Pj5s4K","Pedras Grandes,","SC"));
        lista.add(new Cidade("5BMK7C4YvajddV7ZfkGS","Penha,","SC"));
        lista.add(new Cidade("wjndrKPBq2OjQja4WoHq","Peritiba,","SC"));
        lista.add(new Cidade("pqLQT7T5PkNjBa2RYtg7","Petrolândia,","SC"));
        lista.add(new Cidade("HQC6vtvFpZjhLiPx6ofS","Piçarras,","SC"));
        lista.add(new Cidade("xedUzBJO2KPGjaFjHH7D","Pinhalzinho,","SC"));
        lista.add(new Cidade("F32ebKH7OsyuLrAJNOew","Pinheiro Preto,","SC"));
        lista.add(new Cidade("8lZcyipNj6AtnrLq0ZPI","Piratuba,","SC"));
        lista.add(new Cidade("3xJtQjufIlKQSqnp0BBo","Planalto Alegre,","SC"));
        lista.add(new Cidade("jUdcm9HUquo2YbDAkU4w","Pomerode,","SC"));
        lista.add(new Cidade("oZo8KKRokCoKGm8898mO","Ponte Alta,","SC"));
        lista.add(new Cidade("5L6aScOyF9cTAe5WWcxl","Ponte Alta do Norte,","SC"));
        lista.add(new Cidade("Svx6eiTAlTNUgCBWZmXi","Ponte Serrada,","SC"));
        lista.add(new Cidade("VnGE1hWD4tTPMxtrFCpd","Porto Belo,","SC"));
        lista.add(new Cidade("WYHVis2vCAJOSUD5xT1b","Porto União,","SC"));
        lista.add(new Cidade("xkjzMeymAJiFpqNk5eZ4","Pouso Redondo,","SC"));
        lista.add(new Cidade("Ux0dGs9FJWvVD6A7BUkG","Praia Grande,","SC"));
        lista.add(new Cidade("To8P9rXeIYUjqq3liFdo","Presidente Castelo Branco,","SC"));
        lista.add(new Cidade("lU5R6BRT9pEd5h1DTK1y","Presidente Getúlio,","SC"));
        lista.add(new Cidade("bsDSHzNysKBtYGdyWozd","Presidente Nereu,","SC"));
        lista.add(new Cidade("RiJnvUMEw4KMC1gryMjl","Princesa,","SC"));
        lista.add(new Cidade("EYxjWjrY9tANcQ6xYWSK","Quilombo,","SC"));
        lista.add(new Cidade("qtmUk9I8fmXg65Dyhv6O","Rancho Queimado,","SC"));
        lista.add(new Cidade("cAIFhsUsBrggIN9DRkqt","Rio das Antas,","SC"));
        lista.add(new Cidade("TRp1EBFhXTSBv9Lf2Tlj","Rio do Campo,","SC"));
        lista.add(new Cidade("WKkYvbNNYLWeF0trLX43","Rio do Oeste,","SC"));
        lista.add(new Cidade("tsTOK9WF2D6AE58IcWZJ","Rio do Sul,","SC"));
        lista.add(new Cidade("6zm1Q42NFnjenAxirvWh","Rio dos Cedros,","SC"));
        lista.add(new Cidade("hJa0lIs4umMl4wSYhJS6","Rio Fortuna,","SC"));
        lista.add(new Cidade("0xGwajU0C1ctvVtDJeNu","Rio Negrinho,","SC"));
        lista.add(new Cidade("ZuDYP4ewoKzf2LDx5C6H","Rio Rufino,","SC"));
        lista.add(new Cidade("5mSPdW6UcMaYwiAefQrK","Riqueza,","SC"));
        lista.add(new Cidade("SZeMl10D7YjRFKiWity7","Rodeio,","SC"));
        lista.add(new Cidade("EeUKFZWkViwqyFsKZxf7","Romelândia,","SC"));
        lista.add(new Cidade("wJxgqtQOgwlReOT9uQ8l","Salete,","SC"));
        lista.add(new Cidade("vkCrVUod9lZ8J6A1C89s","Saltinho,","SC"));
        lista.add(new Cidade("IEWZkBFHhzOMDrb5qEKc","Salto Veloso,","SC"));
        lista.add(new Cidade("FoIo33EIJ9pSjxKo2p8P","Sangão,","SC"));
        lista.add(new Cidade("ofzeVGfuQVjOdVnaXelN","Santa Cecília,","SC"));
        lista.add(new Cidade("b7WnuFZBM2yRqKIuGZoj","Santa Helena,","SC"));
        lista.add(new Cidade("dGcoYNU3mXVdLqrPAyOh","Santa Rosa de Lima,","SC"));
        lista.add(new Cidade("WVoVtIWFWqDoipN2dRlX","Santa Rosa do Sul,","SC"));
        lista.add(new Cidade("zfYyRcE0GSCr7TpwIobY","Santa Terezinha,","SC"));
        lista.add(new Cidade("ZEPa0qJzksKh7PmrlMjw","Santa Terezinha do Progresso,","SC"));
        lista.add(new Cidade("eD9qNWr0WpZOp2znIl7O","Santiago do Sul,","SC"));
        lista.add(new Cidade("qAzdw2qtx72Hzwwh4ew0","Santo Amaro da Imperatriz,","SC"));
        lista.add(new Cidade("pS4su39DzpgWh8H5j7Wb","São Bento do Sul,","SC"));
        lista.add(new Cidade("lHs1AsMcuqoF2L1r2mn0","São Bernardino,","SC"));
        lista.add(new Cidade("VV0j7SZxjQibhgEoISJs","São Bonifácio,","SC"));
        lista.add(new Cidade("Rs5ps2cshenYdorRZWx3","São Carlos,","SC"));
        lista.add(new Cidade("IUd7WRVAIAY5jYeiqINQ","São Cristovão do Sul,","SC"));
        lista.add(new Cidade("CBDFyeI79Rj9btkSoGTn","São Domingos,","SC"));
        lista.add(new Cidade("euqyXDZeHARF9BgTVDtg","São Francisco do Sul,","SC"));
        lista.add(new Cidade("w3R99IqbHgYVZ8nV5mI9","São João Batista,","SC"));
        lista.add(new Cidade("y7JQOgXh3WEjh1hjtox1","São João do Itaperiú,","SC"));
        lista.add(new Cidade("YDYMA1CXbhILKtIykMOl","São João do Oeste,","SC"));
        lista.add(new Cidade("qgRVn5a54TGrOXWQQA6m","São João do Sul,","SC"));
        lista.add(new Cidade("Km76Zal8jFB2JWLUxLfn","São Joaquim,","SC"));
        lista.add(new Cidade("bw2jDNtcqGMd96vs0F02","São José,","SC"));
        lista.add(new Cidade("e3qCeC3YZqgNPDN5gAy6","São José do Cedro,","SC"));
        lista.add(new Cidade("2IjasDBluit4i1NdTaW8","São José do Cerrito,","SC"));
        lista.add(new Cidade("Epyd4my0z8Z37sbAEkpK","São Lourenço do Oeste,","SC"));
        lista.add(new Cidade("eEDdjxXGw5ch8cOTTZw1","São Ludgero,","SC"));
        lista.add(new Cidade("Mh0li8KEDaBoZsdpbBwH","São Martinho,","SC"));
        lista.add(new Cidade("IAgMt7rztKWTQoL9yQ5p","São Miguel da Boa Vista,","SC"));
        lista.add(new Cidade("Lwcxf4WEXSuPvx9blnpo","São Miguel do Oeste,","SC"));
        lista.add(new Cidade("35cCjn2dInPGFBAyhxLh","São Pedro de Alcântara,","SC"));
        lista.add(new Cidade("9vUn7AfJLWySKlUNyGOJ","Saudades,","SC"));
        lista.add(new Cidade("tO9qFuJeWZmHtyINMiV1","Schroeder,","SC"));
        lista.add(new Cidade("VX2KKvHlUGylxSCyw66F","Seara,","SC"));
        lista.add(new Cidade("x3eElxkFAWEAcegkWleH","Serra Alta,","SC"));
        lista.add(new Cidade("dofqD7ecB6na7mXxFIn9","Siderópolis,","SC"));
        lista.add(new Cidade("EKuoNNeDx56z5IPLGJdK","Sombrio,","SC"));
        lista.add(new Cidade("0Tst4EmAVuBBcbKEpD6x","Sul Brasil,","SC"));
        lista.add(new Cidade("QjW9DS0VvtcfTVI4B1u6","Taió,","SC"));
        lista.add(new Cidade("gKQRvIz0hBlqOpYmPTEH","Tangará,","SC"));
        lista.add(new Cidade("J6V571RNLcnciCv9W1s1","Tigrinhos,","SC"));
        lista.add(new Cidade("H9lIdVtVR9ItQR460LBk","Tijucas,","SC"));
        lista.add(new Cidade("H2Zhz8sPyk30SZ2tWUkf","Timbé do Sul,","SC"));
        lista.add(new Cidade("lURjFUBDGvSdmdMXjDlZ","Timbó,","SC"));
        lista.add(new Cidade("AyJkO2PdmDvtjSuZfTLw","Timbó Grande,","SC"));
        lista.add(new Cidade("R0D0eSCH6w3UyeLEBCE0","Três Barras,","SC"));
        lista.add(new Cidade("SW9i1r9IBlDWDroZujbG","Treviso,","SC"));
        lista.add(new Cidade("vXinbKx4HarwpNDjmaKx","Treze de Maio,","SC"));
        lista.add(new Cidade("YlGw8ElaZLnlYo8gzDwz","Treze Tílias,","SC"));
        lista.add(new Cidade("vcfLjgH4yw1C15OTPFlx","Trombudo Central,","SC"));
        lista.add(new Cidade("g1SUrXUMWO4tHeWMtJa3","Tubarão,","SC"));
        lista.add(new Cidade("fIDuY7qasVQOwPaRYBoz","Tunápolis,","SC"));
        lista.add(new Cidade("clWRZDKaZUvJ93ehicxO","Turvo,","SC"));
        lista.add(new Cidade("3kyKaOnTlDOYJYbgvDjx","União do Oeste,","SC"));
        lista.add(new Cidade("DoQ0GVO9YvFOOhqvwuBN","Urubici,","SC"));
        lista.add(new Cidade("stoz2SkzJPwCT7YhbIYx","Urupema,","SC"));
        lista.add(new Cidade("w7HpTI8G5vISONTHJiwy","Urussanga,","SC"));
        lista.add(new Cidade("2odMJs06inUB9isKT9uJ","Vargeão,","SC"));
        lista.add(new Cidade("CEZpPQbsgkXsSGGnAGji","Vargem,","SC"));
        lista.add(new Cidade("D04yjcOAenb1EIMAtis2","Vargem Bonita,","SC"));
        lista.add(new Cidade("TH6s778AWvX7ANSYkAmg","Vidal Ramos,","SC"));
        lista.add(new Cidade("yexKye15gFRXhjxtN5xv","Videira,","SC"));
        lista.add(new Cidade("WS881zpnNhBX1lKDeiFx","Vitor Meireles,","SC"));
        lista.add(new Cidade("AgWF6spA4rHqlFgyy8ez","Witmarsum,","SC"));
        lista.add(new Cidade("RBE0VsOvn4bXkeZ67yzY","Xanxerê,","SC"));
        lista.add(new Cidade("sQJ19Zequi66uOZ1efCq","Xavantina,","SC"));
        lista.add(new Cidade("gxPsA5tsxPPRvofqNVKv","Xaxim,","SC"));
        lista.add(new Cidade("pDpEoGeNxGci8QOwGXmT","Zortéa","SC"));

        return lista;
    }
}
