package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class SC {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Abdon Batista,","SC"));
        lista.add(new Cidade("","Abelardo Luz,","SC"));
        lista.add(new Cidade("","Agrolândia,","SC"));
        lista.add(new Cidade("","Agronômica,","SC"));
        lista.add(new Cidade("","Água Doce,","SC"));
        lista.add(new Cidade("","Águas de Chapecó,","SC"));
        lista.add(new Cidade("","Águas Frias,","SC"));
        lista.add(new Cidade("","Águas Mornas,","SC"));
        lista.add(new Cidade("","Alfredo Wagner,","SC"));
        lista.add(new Cidade("","Alto Bela Vista,","SC"));
        lista.add(new Cidade("","Anchieta,","SC"));
        lista.add(new Cidade("","Angelina,","SC"));
        lista.add(new Cidade("","Anita Garibaldi,","SC"));
        lista.add(new Cidade("","Anitápolis,","SC"));
        lista.add(new Cidade("","Antônio Carlos,","SC"));
        lista.add(new Cidade("","Apiúna,","SC"));
        lista.add(new Cidade("","Arabutã,","SC"));
        lista.add(new Cidade("","Araquari,","SC"));
        lista.add(new Cidade("","Araranguá,","SC"));
        lista.add(new Cidade("","Armazém,","SC"));
        lista.add(new Cidade("","Arroio Trinta,","SC"));
        lista.add(new Cidade("","Arvoredo,","SC"));
        lista.add(new Cidade("","Ascurra,","SC"));
        lista.add(new Cidade("","Atalanta,","SC"));
        lista.add(new Cidade("","Aurora,","SC"));
        lista.add(new Cidade("","Balneário Arroio do Silva,","SC"));
        lista.add(new Cidade("","Balneário Barra do Sul,","SC"));
        lista.add(new Cidade("","Balneário Camboriú,","SC"));
        lista.add(new Cidade("","Balneário Gaivota,","SC"));
        lista.add(new Cidade("","Bandeirante,","SC"));
        lista.add(new Cidade("","Barra Bonita,","SC"));
        lista.add(new Cidade("","Barra Velha,","SC"));
        lista.add(new Cidade("","Bela Vista do Toldo,","SC"));
        lista.add(new Cidade("","Belmonte,","SC"));
        lista.add(new Cidade("","Benedito Novo,","SC"));
        lista.add(new Cidade("","Biguaçu,","SC"));
        lista.add(new Cidade("","Blumenau,","SC"));
        lista.add(new Cidade("","Bocaina do Sul,","SC"));
        lista.add(new Cidade("","Bom Jardim da Serra,","SC"));
        lista.add(new Cidade("","Bom Jesus,","SC"));
        lista.add(new Cidade("","Bom Jesus do Oeste,","SC"));
        lista.add(new Cidade("","Bom Retiro,","SC"));
        lista.add(new Cidade("","Bombinhas,","SC"));
        lista.add(new Cidade("","Botuverá,","SC"));
        lista.add(new Cidade("","Braço do Norte,","SC"));
        lista.add(new Cidade("","Braço do Trombudo,","SC"));
        lista.add(new Cidade("","Brunópolis,","SC"));
        lista.add(new Cidade("","Brusque,","SC"));
        lista.add(new Cidade("","Caçador,","SC"));
        lista.add(new Cidade("","Caibi,","SC"));
        lista.add(new Cidade("","Calmon,","SC"));
        lista.add(new Cidade("","Camboriú,","SC"));
        lista.add(new Cidade("","Campo Alegre,","SC"));
        lista.add(new Cidade("","Campo Belo do Sul,","SC"));
        lista.add(new Cidade("","Campo Erê,","SC"));
        lista.add(new Cidade("","Campos Novos,","SC"));
        lista.add(new Cidade("","Canelinha,","SC"));
        lista.add(new Cidade("","Canoinhas,","SC"));
        lista.add(new Cidade("","Capão Alto,","SC"));
        lista.add(new Cidade("","Capinzal,","SC"));
        lista.add(new Cidade("","Capivari de Baixo,","SC"));
        lista.add(new Cidade("","Catanduvas,","SC"));
        lista.add(new Cidade("","Caxambu do Sul,","SC"));
        lista.add(new Cidade("","Celso Ramos,","SC"));
        lista.add(new Cidade("","Cerro Negro,","SC"));
        lista.add(new Cidade("","Chapadão do Lageado,","SC"));
        lista.add(new Cidade("","Chapecó,","SC"));
        lista.add(new Cidade("","Cocal do Sul,","SC"));
        lista.add(new Cidade("","Concórdia,","SC"));
        lista.add(new Cidade("","Cordilheira Alta,","SC"));
        lista.add(new Cidade("","Coronel Freitas,","SC"));
        lista.add(new Cidade("","Coronel Martins,","SC"));
        lista.add(new Cidade("","Correia Pinto,","SC"));
        lista.add(new Cidade("","Corupá,","SC"));
        lista.add(new Cidade("","Criciúma,","SC"));
        lista.add(new Cidade("","Cunha Porã,","SC"));
        lista.add(new Cidade("","Cunhataí,","SC"));
        lista.add(new Cidade("","Curitibanos,","SC"));
        lista.add(new Cidade("","Descanso,","SC"));
        lista.add(new Cidade("","Dionísio Cerqueira,","SC"));
        lista.add(new Cidade("","Dona Emma,","SC"));
        lista.add(new Cidade("","Doutor Pedrinho,","SC"));
        lista.add(new Cidade("","Entre Rios,","SC"));
        lista.add(new Cidade("","Ermo,","SC"));
        lista.add(new Cidade("","Erval Velho,","SC"));
        lista.add(new Cidade("","Faxinal dos Guedes,","SC"));
        lista.add(new Cidade("","Flor do Sertão,","SC"));
        lista.add(new Cidade("","Florianópolis,","SC"));
        lista.add(new Cidade("","Formosa do Sul,","SC"));
        lista.add(new Cidade("","Forquilhinha,","SC"));
        lista.add(new Cidade("","Fraiburgo,","SC"));
        lista.add(new Cidade("","Frei Rogério,","SC"));
        lista.add(new Cidade("","Galvão,","SC"));
        lista.add(new Cidade("","Garopaba,","SC"));
        lista.add(new Cidade("","Garuva,","SC"));
        lista.add(new Cidade("","Gaspar,","SC"));
        lista.add(new Cidade("","Governador Celso Ramos,","SC"));
        lista.add(new Cidade("","Grão Pará,","SC"));
        lista.add(new Cidade("","Gravatal,","SC"));
        lista.add(new Cidade("","Guabiruba,","SC"));
        lista.add(new Cidade("","Guaraciaba,","SC"));
        lista.add(new Cidade("","Guaramirim,","SC"));
        lista.add(new Cidade("","Guarujá do Sul,","SC"));
        lista.add(new Cidade("","Guatambú,","SC"));
        lista.add(new Cidade("","Herval d'Oeste,","SC"));
        lista.add(new Cidade("","Ibiam,","SC"));
        lista.add(new Cidade("","Ibicaré,","SC"));
        lista.add(new Cidade("","Ibirama,","SC"));
        lista.add(new Cidade("","Içara,","SC"));
        lista.add(new Cidade("","Ilhota,","SC"));
        lista.add(new Cidade("","Imaruí,","SC"));
        lista.add(new Cidade("","Imbituba,","SC"));
        lista.add(new Cidade("","Imbuia,","SC"));
        lista.add(new Cidade("","Indaial,","SC"));
        lista.add(new Cidade("","Iomerê,","SC"));
        lista.add(new Cidade("","Ipira,","SC"));
        lista.add(new Cidade("","Iporã do Oeste,","SC"));
        lista.add(new Cidade("","Ipuaçu,","SC"));
        lista.add(new Cidade("","Ipumirim,","SC"));
        lista.add(new Cidade("","Iraceminha,","SC"));
        lista.add(new Cidade("","Irani,","SC"));
        lista.add(new Cidade("","Irati,","SC"));
        lista.add(new Cidade("","Irineópolis,","SC"));
        lista.add(new Cidade("","Itá,","SC"));
        lista.add(new Cidade("","Itaiópolis,","SC"));
        lista.add(new Cidade("","Itajaí,","SC"));
        lista.add(new Cidade("","Itapema,","SC"));
        lista.add(new Cidade("","Itapiranga,","SC"));
        lista.add(new Cidade("","Itapoá,","SC"));
        lista.add(new Cidade("","Ituporanga,","SC"));
        lista.add(new Cidade("","Jaborá,","SC"));
        lista.add(new Cidade("","Jacinto Machado,","SC"));
        lista.add(new Cidade("","Jaguaruna,","SC"));
        lista.add(new Cidade("","Jaraguá do Sul,","SC"));
        lista.add(new Cidade("","Jardinópolis,","SC"));
        lista.add(new Cidade("","Joaçaba,","SC"));
        lista.add(new Cidade("","Joinville,","SC"));
        lista.add(new Cidade("","José Boiteux,","SC"));
        lista.add(new Cidade("","Jupiá,","SC"));
        lista.add(new Cidade("","Lacerdópolis,","SC"));
        lista.add(new Cidade("","Lages,","SC"));
        lista.add(new Cidade("","Laguna,","SC"));
        lista.add(new Cidade("","Lajeado Grande,","SC"));
        lista.add(new Cidade("","Laurentino,","SC"));
        lista.add(new Cidade("","Lauro Muller,","SC"));
        lista.add(new Cidade("","Lebon Régis,","SC"));
        lista.add(new Cidade("","Leoberto Leal,","SC"));
        lista.add(new Cidade("","Lindóia do Sul,","SC"));
        lista.add(new Cidade("","Lontras,","SC"));
        lista.add(new Cidade("","Luiz Alves,","SC"));
        lista.add(new Cidade("","Luzerna,","SC"));
        lista.add(new Cidade("","Macieira,","SC"));
        lista.add(new Cidade("","Mafra,","SC"));
        lista.add(new Cidade("","Major Gercino,","SC"));
        lista.add(new Cidade("","Major Vieira,","SC"));
        lista.add(new Cidade("","Maracajá,","SC"));
        lista.add(new Cidade("","Maravilha,","SC"));
        lista.add(new Cidade("","Marema,","SC"));
        lista.add(new Cidade("","Massaranduba,","SC"));
        lista.add(new Cidade("","Matos Costa,","SC"));
        lista.add(new Cidade("","Meleiro,","SC"));
        lista.add(new Cidade("","Mirim Doce,","SC"));
        lista.add(new Cidade("","Modelo,","SC"));
        lista.add(new Cidade("","Mondaí,","SC"));
        lista.add(new Cidade("","Monte Carlo,","SC"));
        lista.add(new Cidade("","Monte Castelo,","SC"));
        lista.add(new Cidade("","Morro da Fumaça,","SC"));
        lista.add(new Cidade("","Morro Grande,","SC"));
        lista.add(new Cidade("","Navegantes,","SC"));
        lista.add(new Cidade("","Nova Erechim,","SC"));
        lista.add(new Cidade("","Nova Itaberaba,","SC"));
        lista.add(new Cidade("","Nova Trento,","SC"));
        lista.add(new Cidade("","Nova Veneza,","SC"));
        lista.add(new Cidade("","Novo Horizonte,","SC"));
        lista.add(new Cidade("","Orleans,","SC"));
        lista.add(new Cidade("","Otacílio Costa,","SC"));
        lista.add(new Cidade("","Ouro,","SC"));
        lista.add(new Cidade("","Ouro Verde,","SC"));
        lista.add(new Cidade("","Paial,","SC"));
        lista.add(new Cidade("","Painel,","SC"));
        lista.add(new Cidade("","Palhoça,","SC"));
        lista.add(new Cidade("","Palma Sola,","SC"));
        lista.add(new Cidade("","Palmeira,","SC"));
        lista.add(new Cidade("","Palmitos,","SC"));
        lista.add(new Cidade("","Papanduva,","SC"));
        lista.add(new Cidade("","Paraíso,","SC"));
        lista.add(new Cidade("","Passo de Torres,","SC"));
        lista.add(new Cidade("","Passos Maia,","SC"));
        lista.add(new Cidade("","Paulo Lopes,","SC"));
        lista.add(new Cidade("","Pedras Grandes,","SC"));
        lista.add(new Cidade("","Penha,","SC"));
        lista.add(new Cidade("","Peritiba,","SC"));
        lista.add(new Cidade("","Petrolândia,","SC"));
        lista.add(new Cidade("","Piçarras,","SC"));
        lista.add(new Cidade("","Pinhalzinho,","SC"));
        lista.add(new Cidade("","Pinheiro Preto,","SC"));
        lista.add(new Cidade("","Piratuba,","SC"));
        lista.add(new Cidade("","Planalto Alegre,","SC"));
        lista.add(new Cidade("","Pomerode,","SC"));
        lista.add(new Cidade("","Ponte Alta,","SC"));
        lista.add(new Cidade("","Ponte Alta do Norte,","SC"));
        lista.add(new Cidade("","Ponte Serrada,","SC"));
        lista.add(new Cidade("","Porto Belo,","SC"));
        lista.add(new Cidade("","Porto União,","SC"));
        lista.add(new Cidade("","Pouso Redondo,","SC"));
        lista.add(new Cidade("","Praia Grande,","SC"));
        lista.add(new Cidade("","Presidente Castelo Branco,","SC"));
        lista.add(new Cidade("","Presidente Getúlio,","SC"));
        lista.add(new Cidade("","Presidente Nereu,","SC"));
        lista.add(new Cidade("","Princesa,","SC"));
        lista.add(new Cidade("","Quilombo,","SC"));
        lista.add(new Cidade("","Rancho Queimado,","SC"));
        lista.add(new Cidade("","Rio das Antas,","SC"));
        lista.add(new Cidade("","Rio do Campo,","SC"));
        lista.add(new Cidade("","Rio do Oeste,","SC"));
        lista.add(new Cidade("","Rio do Sul,","SC"));
        lista.add(new Cidade("","Rio dos Cedros,","SC"));
        lista.add(new Cidade("","Rio Fortuna,","SC"));
        lista.add(new Cidade("","Rio Negrinho,","SC"));
        lista.add(new Cidade("","Rio Rufino,","SC"));
        lista.add(new Cidade("","Riqueza,","SC"));
        lista.add(new Cidade("","Rodeio,","SC"));
        lista.add(new Cidade("","Romelândia,","SC"));
        lista.add(new Cidade("","Salete,","SC"));
        lista.add(new Cidade("","Saltinho,","SC"));
        lista.add(new Cidade("","Salto Veloso,","SC"));
        lista.add(new Cidade("","Sangão,","SC"));
        lista.add(new Cidade("","Santa Cecília,","SC"));
        lista.add(new Cidade("","Santa Helena,","SC"));
        lista.add(new Cidade("","Santa Rosa de Lima,","SC"));
        lista.add(new Cidade("","Santa Rosa do Sul,","SC"));
        lista.add(new Cidade("","Santa Terezinha,","SC"));
        lista.add(new Cidade("","Santa Terezinha do Progresso,","SC"));
        lista.add(new Cidade("","Santiago do Sul,","SC"));
        lista.add(new Cidade("","Santo Amaro da Imperatriz,","SC"));
        lista.add(new Cidade("","São Bento do Sul,","SC"));
        lista.add(new Cidade("","São Bernardino,","SC"));
        lista.add(new Cidade("","São Bonifácio,","SC"));
        lista.add(new Cidade("","São Carlos,","SC"));
        lista.add(new Cidade("","São Cristovão do Sul,","SC"));
        lista.add(new Cidade("","São Domingos,","SC"));
        lista.add(new Cidade("","São Francisco do Sul,","SC"));
        lista.add(new Cidade("","São João Batista,","SC"));
        lista.add(new Cidade("","São João do Itaperiú,","SC"));
        lista.add(new Cidade("","São João do Oeste,","SC"));
        lista.add(new Cidade("","São João do Sul,","SC"));
        lista.add(new Cidade("","São Joaquim,","SC"));
        lista.add(new Cidade("","São José,","SC"));
        lista.add(new Cidade("","São José do Cedro,","SC"));
        lista.add(new Cidade("","São José do Cerrito,","SC"));
        lista.add(new Cidade("","São Lourenço do Oeste,","SC"));
        lista.add(new Cidade("","São Ludgero,","SC"));
        lista.add(new Cidade("","São Martinho,","SC"));
        lista.add(new Cidade("","São Miguel da Boa Vista,","SC"));
        lista.add(new Cidade("","São Miguel do Oeste,","SC"));
        lista.add(new Cidade("","São Pedro de Alcântara,","SC"));
        lista.add(new Cidade("","Saudades,","SC"));
        lista.add(new Cidade("","Schroeder,","SC"));
        lista.add(new Cidade("","Seara,","SC"));
        lista.add(new Cidade("","Serra Alta,","SC"));
        lista.add(new Cidade("","Siderópolis,","SC"));
        lista.add(new Cidade("","Sombrio,","SC"));
        lista.add(new Cidade("","Sul Brasil,","SC"));
        lista.add(new Cidade("","Taió,","SC"));
        lista.add(new Cidade("","Tangará,","SC"));
        lista.add(new Cidade("","Tigrinhos,","SC"));
        lista.add(new Cidade("","Tijucas,","SC"));
        lista.add(new Cidade("","Timbé do Sul,","SC"));
        lista.add(new Cidade("","Timbó,","SC"));
        lista.add(new Cidade("","Timbó Grande,","SC"));
        lista.add(new Cidade("","Três Barras,","SC"));
        lista.add(new Cidade("","Treviso,","SC"));
        lista.add(new Cidade("","Treze de Maio,","SC"));
        lista.add(new Cidade("","Treze Tílias,","SC"));
        lista.add(new Cidade("","Trombudo Central,","SC"));
        lista.add(new Cidade("","Tubarão,","SC"));
        lista.add(new Cidade("","Tunápolis,","SC"));
        lista.add(new Cidade("","Turvo,","SC"));
        lista.add(new Cidade("","União do Oeste,","SC"));
        lista.add(new Cidade("","Urubici,","SC"));
        lista.add(new Cidade("","Urupema,","SC"));
        lista.add(new Cidade("","Urussanga,","SC"));
        lista.add(new Cidade("","Vargeão,","SC"));
        lista.add(new Cidade("","Vargem,","SC"));
        lista.add(new Cidade("","Vargem Bonita,","SC"));
        lista.add(new Cidade("","Vidal Ramos,","SC"));
        lista.add(new Cidade("","Videira,","SC"));
        lista.add(new Cidade("","Vitor Meireles,","SC"));
        lista.add(new Cidade("","Witmarsum,","SC"));
        lista.add(new Cidade("","Xanxerê,","SC"));
        lista.add(new Cidade("","Xavantina,","SC"));
        lista.add(new Cidade("","Xaxim,","SC"));
        lista.add(new Cidade("","Zortéa","SC"));
        return lista;
    }
}
