package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class SC {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("PEb4SUVBJtua8OinzH4t","Abdon Batista,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("DfrHQp9ouHEVwKqr2tw3","Abelardo Luz,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("enClWCyqBF5PDWJYs1fc","Agrolândia,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("YgR9xpda1WsnjpuzjOqb","Agronômica,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("4mw3Vs2ZoId0bjsq4rFD","Água Doce,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("yx3viDe2PHvtT5TfSD0n","Águas de Chapecó,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("CqnAlnlzxGKSDdwUR0YR","Águas Frias,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("sPItI4OfnPsmMVGPphtS","Águas Mornas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("j7QD9yadnxgh9JxKcsF7","Alfredo Wagner,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("6GCTH9uZ41HzKUYeB1Fz","Alto Bela Vista,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("JEFUAQxN5Qb740UgXldT","Anchieta,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("LyJBIvSk2JuTDVEk8GbL","Angelina,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("uSmTLSKQogbBvkmwp5Ec","Anita Garibaldi,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("tkq6mz9D7fZTEUQ6Vs5H","Anitápolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("uWIXm4ZNv6qSkXS57cs5","Antônio Carlos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wA6C7CoJgpuYfrXQHI2n","Apiúna,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("zSd9g4eDIDVyqgvLo14w","Arabutã,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("sYWbBuHGxy4TNtmEK1OF","Araquari,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("c4eClBMDqroQCVfnmzQO","Araranguá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ZeujVVyvB5YVr5gCaiEW","Armazém,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("BA7j09olhsUaMBo5ta1N","Arroio Trinta,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ETRuwfzBYHwtF2VAb8sC","Arvoredo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Ct9EzSxEdWLqHS5q08mN","Ascurra,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wK6UBnc5uk37L2d0qcgQ","Atalanta,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("9aiMp3OW0VdvlxZAsZhP","Aurora,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("uRmLPhH7kQrXu1nwUdDQ","Balneário Arroio do Silva,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2TQcrQCrwBc2mzap6WQp","Balneário Barra do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("uMVfocxmeZCj9KIWz5d8","Balneário Camboriú,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("uLHI2iNwxpsrnrXGDSjV","Balneário Gaivota,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("N4RPDkm2D6pHJtn1J3Of","Bandeirante,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("k8hqkBltzwnZDqyzGNB2","Barra Bonita,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("HR3hdMcfwHUnDJJkjVCO","Barra Velha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wMTAjy6vUeqcVC8MLpIM","Bela Vista do Toldo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("UpYvooAKtWJxDTbOlbgo","Belmonte,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("xPuUPuQx1s4UoRslWQbV","Benedito Novo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("zWnLUTFhAzzBSAuQuxyx","Biguaçu,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("En7lI9WmjJE10eOyXOSG","Blumenau,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("rGb13nh2OQLLf4oXX5yO","Bocaina do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("SNlcFtnR4l9foR5vUyQo","Bom Jardim da Serra,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("KopU30QO2mpgS33it73g","Bom Jesus,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("pQuZGJXFV5hOTz1K4eqT","Bom Jesus do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("YdRMYOejyuucfihYjZkD","Bom Retiro,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2xy22U7pVy9mUxmFwQqh","Bombinhas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("lSVNMRyAFhdsGonY8hC6","Botuverá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("w2U6krHMx1qcV6LEAvJ0","Braço do Norte,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("e9yKNCaAJUZFzjDHjmt8","Braço do Trombudo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("P3atpAAqvwTyuUN3ZIHu","Brunópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("SZ50wTamoF5Ocjqz7AJK","Brusque,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("5qCVIOyqSxG5Uc7WvCJh","Caçador,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ubzR4alm0kNhXGMOyyj5","Caibi,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("e5GBkzvXbegDgaYybad3","Calmon,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("UPc027c3LxyH36hp3zee","Camboriú,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ElkBSZ32FbQy5L1uGUeV","Campo Alegre,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("erToCMp9LxRBTRuRHfGq","Campo Belo do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("hOHfD9T4vZ1FMNQhBiNI","Campo Erê,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("DvSIDKlDNcyXNigfrFtf","Campos Novos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("NBH7ubBieTtEo5rCXwG5","Canelinha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("cOcu9xzQvetz5zsbIa5c","Canoinhas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("fvnqdddzV9q9ser9a3Bn","Capão Alto,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("o1SDduO7pLqiKM0N7Pkf","Capinzal,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("0dGnxxFHuiGYMEx1m1RD","Capivari de Baixo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("mksFC16fMTkHYcShOq5w","Catanduvas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("QzwzgS4Q2FuKMdOcvJTS","Caxambu do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Nqhs51f7HTIfmLTEhPSe","Celso Ramos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("z3yLOVVyHqiw3Fr9vaur","Cerro Negro,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VOQUhsSznG46S0BMIvrk","Chapadão do Lageado,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("QqtbhMezHPfKBgV4A2N0","Chapecó,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Ld0EMdqe59ZvoPSPUvuq","Cocal do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("LRo4VQQPjU4R6UTr9g0i","Concórdia,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("KkIg1AewCCvokjzkk8rd","Cordilheira Alta,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("nbGglxyzO4cQCFx7YgnL","Coronel Freitas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("CJtka9zSs2wbx8bevnfF","Coronel Martins,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Z7uNcgZJLJvdNKKwv5gJ","Correia Pinto,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("vBBjpA5LeE105HQFPVOS","Corupá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("AnOSYYokoiqbKwENPc3e","Criciúma,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("RIVraTYMTDgD2KptmBL3","Cunha Porã,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("f4kCspNVCs1ZOJlrVmTV","Cunhataí,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("51GIIJsS0ygXFlYIlnyx","Curitibanos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("rxlx5Cc3nWhgCv7Cchhe","Descanso,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("lqud9WImvLLEIxywegh2","Dionísio Cerqueira,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("s5CuqKc7xsrRLFbWiOwe","Dona Emma,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("kPaKqislZTua4utXR2e7","Doutor Pedrinho,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("JD0Cd2EhVhp5JG4TX4px","Entre Rios,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("PGOAmFwJMBdPG8FpgtJe","Ermo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("0ZMdFky6KEhCWkOmY62k","Erval Velho,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("T5CxTry80mnzMRq7ine6","Faxinal dos Guedes,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("llNptTlngmpcVO018jfR","Flor do Sertão,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Kf1jx9pVCLNuJXmLHYAj","Florianópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("i4XUxw3C46uYM8wDveXY","Formosa do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("bI1eLQ30DUxBcaySVx3R","Forquilhinha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("inPnubCt0mWew0Zvh3iW","Fraiburgo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("tfqtemQ5uxPKJHXYwAAn","Frei Rogério,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wBtx0wW0r7SWwt6iCPgD","Galvão,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gAPVWNMj25xECgRzVh9Q","Garopaba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gss9OqsqrP2GvPrZzSfu","Garuva,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("r8HdMiBlX18Bu4Mn3Pbu","Gaspar,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("tKFLCWlW9VEFtETxwtJz","Governador Celso Ramos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("AeA53AaWPscNs9TgSQdC","Grão Pará,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("OP57J9IGm5DwdvYhB60m","Gravatal,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("v5NaUfc23S3EKDBaAWjT","Guabiruba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("cVpWRv8w2uGwpYAcbCxQ","Guaraciaba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ggXe1imTPos0bvLk6ttf","Guaramirim,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("uTT23QkGk0kqYGbPqoWW","Guarujá do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VhXurR2c4r499gOD0Hhr","Guatambú,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Zuh5QnXDPKBioHzxy8XW","Herval d'Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("of9bCvTRP6Fmcaosli1X","Ibiam,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("7bs1fpcmYF5eW8vaNypB","Ibicaré,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("sj66XDnrAlTnvS3SxOcR","Ibirama,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("TEYElbZK60DrZljKBlv2","Içara,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("LTWgeoG2ZkJ8iL6geo9v","Ilhota,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("oTWjbjdBOQX1lduvHECT","Imaruí,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("MK0QXLdgHuguaYiDevvV","Imbituba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Rxtefzbn8Vldwd8c2MI0","Imbuia,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("RthvCrBrGS55J3pZuZSH","Indaial,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wGbiAHwdXyEQaCnLtYFh","Iomerê,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2aylmgT83ao4V4FGtumy","Ipira,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("8geBCo6otgX72uzRyG5C","Iporã do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Cv51nv1n6RRHvT8iTHzr","Ipuaçu,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("A74LlSU66wgFOqodGmRN","Ipumirim,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2LSqaXIx1TpCBWVHLcGG","Iraceminha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Ow3SKqynR9UiWIVueMgj","Irani,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("N9o88sErX6axAbL91Cid","Irati,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("EkCIUXHivxjoFIvyfN09","Irineópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("UZuEWl89SwJgBQFsl4DT","Itá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("pMP5aKn9OT4XqfNOoY8E","Itaiópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ccdCQsvFkL17pGkSVm0a","Itajaí,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("vUaoKI2eev13xFeahyvD","Itapema,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gaEjf4rapItiaNSYVSdR","Itapiranga,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("vRUie0d85SXnmu15pk6j","Itapoá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("lvFcb1a0QSHCTU8sIRFp","Ituporanga,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("kPrjc6HijcZBtQA35qYb","Jaborá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("APhqMEElzFZPKRIElnay","Jacinto Machado,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("5SwoeLtSUUZlIQEgzisN","Jaguaruna,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("NNkoLCw4Qi4mBjSGlutl","Jaraguá do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("kNtVJrcz7kuqbzeJTbJg","Jardinópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("aDJNHN4NHQoM3ylGrKJ3","Joaçaba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("CsqqjdENkpGkqlIag4H3","Joinville,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("l0nq46POJgdxvLuBgOuN","José Boiteux,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("EarwvqxK8olQtWTj5vz3","Jupiá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Q4jhC4DfXlPoC8U2zhAS","Lacerdópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("3ZcWAjV9Qm8n0br4vHUj","Lages,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("sE07a5EyPZGpp7W59stW","Laguna,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("n3mOU1t0eaXVCDvbgS5e","Lajeado Grande,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("QqqymMgEtPSzocdOGa2U","Laurentino,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gj4y5NIYRenQCdFanRXj","Lauro Muller,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VIJ6oQbzCPl7HHrCrzDG","Lebon Régis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("qjAQ2yMs8hwZR0k3UhCb","Leoberto Leal,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ryv6NXwX1BG43YJXc1nt","Lindóia do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("t3jCgWcFo2dmqUvywFkM","Lontras,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gKNNLHFDYYoD2KORL2VV","Luiz Alves,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("9V1hjEXkM6BRMRyw2iJ3","Luzerna,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("7BIzbTxglTEMAMOAVeMf","Macieira,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("OozxUcTnH0L50YYTrwSi","Mafra,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VWIJHmY2FVyasJh99UyT","Major Gercino,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("YF3pViVSYOKS9xOztIvL","Major Vieira,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Mpus6mBRshlOA6byeayU","Maracajá,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("mpEWyK35lMJg7xDq4vbV","Maravilha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("KVMkYxO8Ze1yRN1u6cPa","Marema,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("pOH7lEjlOnsdGIfoeYn4","Massaranduba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("5uB115PCxcxfbppwyoHa","Matos Costa,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("6Ap1QA0ecIDlXmdEz9A4","Meleiro,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("94OcDBnVnHAwi8fNPfZY","Mirim Doce,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("3EC7XCH2dsI4Emga7fuk","Modelo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("oGl1nW4VkOG5cOmqHC0G","Mondaí,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Hjy8DF5bExEA7mgmTXp9","Monte Carlo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2iwEl6pOV7Z1LiByIE46","Monte Castelo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("AP0ZGlSrKvsrmZlM7PhP","Morro da Fumaça,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("OOkqJTEMa6tp9cij3IIx","Morro Grande,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Xa00q73AzhpFdJGSpWnL","Navegantes,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("YzeBpNwEIlCyAtxzVkRs","Nova Erechim,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("XGnsk4eIkc2ANbd1Js5H","Nova Itaberaba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("e31Hq49eimOKsz5thnIx","Nova Trento,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("4QHTxvt4DF0S6P6HPKtQ","Nova Veneza,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("QPt30JUrFq5P5Ubb1ijM","Novo Horizonte,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("qdYTWZhdBZv72amHg6D8","Orleans,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("4LS17AyuVlIfVQ02GUzy","Otacílio Costa,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("6BvVb8wa3eKLbdpZo8Wk","Ouro,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("LuMk5oPbP6zLNd1BVPUR","Ouro Verde,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("KoWtJEhepZAMZtykLuq9","Paial,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("DzzvCXCRtnUwxIewodxU","Painel,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("4YGmYtXIp1LyJymjis0Q","Palhoça,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("6InuBuhPtLpsJH2VoySj","Palma Sola,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("MJCbqYXKN5zGWyYuywjW","Palmeira,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("WO8eQye3jJX9GuYZgIZn","Palmitos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("LMKR5rYv8sC9RLDT5m9O","Papanduva,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("43gS3BU0OAVZJXRB2MZd","Paraíso,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("3l2zgG3bsm4MI8RNjaQt","Passo de Torres,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("AmTSPQXAh9FKh4JY5A6L","Passos Maia,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ygupdn6KpZzTiThXJaK4","Paulo Lopes,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Dl5nlSiXb0IoD0Pj5s4K","Pedras Grandes,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("5BMK7C4YvajddV7ZfkGS","Penha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wjndrKPBq2OjQja4WoHq","Peritiba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("pqLQT7T5PkNjBa2RYtg7","Petrolândia,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("HQC6vtvFpZjhLiPx6ofS","Piçarras,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("xedUzBJO2KPGjaFjHH7D","Pinhalzinho,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("F32ebKH7OsyuLrAJNOew","Pinheiro Preto,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("8lZcyipNj6AtnrLq0ZPI","Piratuba,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("3xJtQjufIlKQSqnp0BBo","Planalto Alegre,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("jUdcm9HUquo2YbDAkU4w","Pomerode,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("oZo8KKRokCoKGm8898mO","Ponte Alta,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("5L6aScOyF9cTAe5WWcxl","Ponte Alta do Norte,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Svx6eiTAlTNUgCBWZmXi","Ponte Serrada,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VnGE1hWD4tTPMxtrFCpd","Porto Belo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("WYHVis2vCAJOSUD5xT1b","Porto União,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("xkjzMeymAJiFpqNk5eZ4","Pouso Redondo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Ux0dGs9FJWvVD6A7BUkG","Praia Grande,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("To8P9rXeIYUjqq3liFdo","Presidente Castelo Branco,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("lU5R6BRT9pEd5h1DTK1y","Presidente Getúlio,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("bsDSHzNysKBtYGdyWozd","Presidente Nereu,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("RiJnvUMEw4KMC1gryMjl","Princesa,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("EYxjWjrY9tANcQ6xYWSK","Quilombo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("qtmUk9I8fmXg65Dyhv6O","Rancho Queimado,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("cAIFhsUsBrggIN9DRkqt","Rio das Antas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("TRp1EBFhXTSBv9Lf2Tlj","Rio do Campo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("WKkYvbNNYLWeF0trLX43","Rio do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("tsTOK9WF2D6AE58IcWZJ","Rio do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("6zm1Q42NFnjenAxirvWh","Rio dos Cedros,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("hJa0lIs4umMl4wSYhJS6","Rio Fortuna,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("0xGwajU0C1ctvVtDJeNu","Rio Negrinho,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ZuDYP4ewoKzf2LDx5C6H","Rio Rufino,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("5mSPdW6UcMaYwiAefQrK","Riqueza,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("SZeMl10D7YjRFKiWity7","Rodeio,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("EeUKFZWkViwqyFsKZxf7","Romelândia,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("wJxgqtQOgwlReOT9uQ8l","Salete,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("vkCrVUod9lZ8J6A1C89s","Saltinho,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("IEWZkBFHhzOMDrb5qEKc","Salto Veloso,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("FoIo33EIJ9pSjxKo2p8P","Sangão,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ofzeVGfuQVjOdVnaXelN","Santa Cecília,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("b7WnuFZBM2yRqKIuGZoj","Santa Helena,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("dGcoYNU3mXVdLqrPAyOh","Santa Rosa de Lima,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("WVoVtIWFWqDoipN2dRlX","Santa Rosa do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("zfYyRcE0GSCr7TpwIobY","Santa Terezinha,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("ZEPa0qJzksKh7PmrlMjw","Santa Terezinha do Progresso,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("eD9qNWr0WpZOp2znIl7O","Santiago do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("qAzdw2qtx72Hzwwh4ew0","Santo Amaro da Imperatriz,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("pS4su39DzpgWh8H5j7Wb","São Bento do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("lHs1AsMcuqoF2L1r2mn0","São Bernardino,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VV0j7SZxjQibhgEoISJs","São Bonifácio,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Rs5ps2cshenYdorRZWx3","São Carlos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("IUd7WRVAIAY5jYeiqINQ","São Cristovão do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("CBDFyeI79Rj9btkSoGTn","São Domingos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("euqyXDZeHARF9BgTVDtg","São Francisco do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("w3R99IqbHgYVZ8nV5mI9","São João Batista,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("y7JQOgXh3WEjh1hjtox1","São João do Itaperiú,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("YDYMA1CXbhILKtIykMOl","São João do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("qgRVn5a54TGrOXWQQA6m","São João do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Km76Zal8jFB2JWLUxLfn","São Joaquim,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("bw2jDNtcqGMd96vs0F02","São José,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("e3qCeC3YZqgNPDN5gAy6","São José do Cedro,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2IjasDBluit4i1NdTaW8","São José do Cerrito,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Epyd4my0z8Z37sbAEkpK","São Lourenço do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("eEDdjxXGw5ch8cOTTZw1","São Ludgero,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Mh0li8KEDaBoZsdpbBwH","São Martinho,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("IAgMt7rztKWTQoL9yQ5p","São Miguel da Boa Vista,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("Lwcxf4WEXSuPvx9blnpo","São Miguel do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("35cCjn2dInPGFBAyhxLh","São Pedro de Alcântara,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("9vUn7AfJLWySKlUNyGOJ","Saudades,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("tO9qFuJeWZmHtyINMiV1","Schroeder,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("VX2KKvHlUGylxSCyw66F","Seara,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("x3eElxkFAWEAcegkWleH","Serra Alta,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("dofqD7ecB6na7mXxFIn9","Siderópolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("EKuoNNeDx56z5IPLGJdK","Sombrio,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("0Tst4EmAVuBBcbKEpD6x","Sul Brasil,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("QjW9DS0VvtcfTVI4B1u6","Taió,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gKQRvIz0hBlqOpYmPTEH","Tangará,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("J6V571RNLcnciCv9W1s1","Tigrinhos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("H9lIdVtVR9ItQR460LBk","Tijucas,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("H2Zhz8sPyk30SZ2tWUkf","Timbé do Sul,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("lURjFUBDGvSdmdMXjDlZ","Timbó,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("AyJkO2PdmDvtjSuZfTLw","Timbó Grande,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("R0D0eSCH6w3UyeLEBCE0","Três Barras,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("SW9i1r9IBlDWDroZujbG","Treviso,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("vXinbKx4HarwpNDjmaKx","Treze de Maio,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("YlGw8ElaZLnlYo8gzDwz","Treze Tílias,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("vcfLjgH4yw1C15OTPFlx","Trombudo Central,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("g1SUrXUMWO4tHeWMtJa3","Tubarão,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("fIDuY7qasVQOwPaRYBoz","Tunápolis,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("clWRZDKaZUvJ93ehicxO","Turvo,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("3kyKaOnTlDOYJYbgvDjx","União do Oeste,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("DoQ0GVO9YvFOOhqvwuBN","Urubici,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("stoz2SkzJPwCT7YhbIYx","Urupema,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("w7HpTI8G5vISONTHJiwy","Urussanga,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("2odMJs06inUB9isKT9uJ","Vargeão,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("CEZpPQbsgkXsSGGnAGji","Vargem,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("D04yjcOAenb1EIMAtis2","Vargem Bonita,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("TH6s778AWvX7ANSYkAmg","Vidal Ramos,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("yexKye15gFRXhjxtN5xv","Videira,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("WS881zpnNhBX1lKDeiFx","Vitor Meireles,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("AgWF6spA4rHqlFgyy8ez","Witmarsum,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("RBE0VsOvn4bXkeZ67yzY","Xanxerê,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("sQJ19Zequi66uOZ1efCq","Xavantina,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("gxPsA5tsxPPRvofqNVKv","Xaxim,","4niJNacnYflWAk7B2yA4", "SC"));
        lista.add(new Cidade("pDpEoGeNxGci8QOwGXmT","Zortéa","4niJNacnYflWAk7B2yA4", "SC"));

        return lista;
    }
}
