package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class SP {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("HYsbUTJmqj356KQTDWy4","Adamantina","SP"));
        lista.add(new Cidade("P2vEtoRFe4rhC2JbO9bi","Adolfo","SP"));
        lista.add(new Cidade("XiSzlZVUNhHUINmp5Aly","Aguaí","SP"));
        lista.add(new Cidade("XNXHcZA7aiQzRDQkXmvv","Águas da Prata","SP"));
        lista.add(new Cidade("1O4eiFAhGrFZmYVfLDEU","Águas de Lindóia","SP"));
        lista.add(new Cidade("Z2Jo8N02DjAPSwFRsGu5","Águas de Santa Bárbara","SP"));
        lista.add(new Cidade("vpZm8vJpcELj1zvUy3sx","Águas de São Pedro","SP"));
        lista.add(new Cidade("c0oooLWihkH9UUz9hT60","Agudos","SP"));
        lista.add(new Cidade("9CPadl6dxHshyfLycpJJ","Alambari","SP"));
        lista.add(new Cidade("K2hwazj56NfUOVF6kOwj","Alfredo Marcondes","SP"));
        lista.add(new Cidade("yThCk47cNfFphJvN2fiK","Altair","SP"));
        lista.add(new Cidade("YTOW9JfxUvexRwVV9lsi","Altinópolis","SP"));
        lista.add(new Cidade("sRSCfKA9Kip7peiVKPFQ","Alto Alegre","SP"));
        lista.add(new Cidade("RFRx0N5pYZ02u8SLr5EV","Alumínio","SP"));
        lista.add(new Cidade("yPQc2weu7lfti8q82YpS","Álvares Florence","SP"));
        lista.add(new Cidade("GudBT0KcjAo05eJ3kteU","Álvares Machado","SP"));
        lista.add(new Cidade("1JMDxGMiOrvLBJtbUtuA","Álvaro de Carvalho","SP"));
        lista.add(new Cidade("ycvL4d8DQOHQanoEPHRW","Alvinlândia","SP"));
        lista.add(new Cidade("2LsW8l2P1gSvw6JvDDBS","Americana","SP"));
        lista.add(new Cidade("Dsml4AXUtndUvWq8jgVA","Américo Brasiliense","SP"));
        lista.add(new Cidade("u4cxwQrPrFPNi87dPLCB","Américo de Campos","SP"));
        lista.add(new Cidade("HqXVLSNP4f2x3VTC84SM","Amparo","SP"));
        lista.add(new Cidade("8h2vC0hdRwXvOXOeKgJE","Analândia","SP"));
        lista.add(new Cidade("ykV6rFyQQPUdDffkLIFR","Andradina","SP"));
        lista.add(new Cidade("Xak0PohKzjcV2S7rcjet","Angatuba","SP"));
        lista.add(new Cidade("ziesY4GQUBeEzjQS9Ebi","Anhembi","SP"));
        lista.add(new Cidade("K9XMIC5VwTdzl5rq6UF1","Anhumas","SP"));
        lista.add(new Cidade("wwGPHxrZXa4XYAjxRyg1","Aparecida","SP"));
        lista.add(new Cidade("9MmcXv6foZPFDEE93d39","Aparecida d'Oeste","SP"));
        lista.add(new Cidade("ssxkarsI0s2aXGEd1LfA","Apiaí","SP"));
        lista.add(new Cidade("GMSmEXFKdJ5JL5pczEuL","Araçariguama","SP"));
        lista.add(new Cidade("sBltpl90hXuzGkyiPPH3","Araçatuba","SP"));
        lista.add(new Cidade("a6B7e1q0ILzUmCxOQEp2","Araçoiaba da Serra","SP"));
        lista.add(new Cidade("MNjlhDlpYdbtkL5QQMxf","Aramina","SP"));
        lista.add(new Cidade("Zf9FHVhBmux7aWlBPxPx","Arandu","SP"));
        lista.add(new Cidade("vJ4VHfEwwQjydZHzNLlt","Arapeí","SP"));
        lista.add(new Cidade("kP5rqhcy8abH6obs1X0K","Araraquara","SP"));
        lista.add(new Cidade("oH8bAXBI76K9rRhjY8Ur","Araras","SP"));
        lista.add(new Cidade("khKmgnkD8Y5IbnnXo75F","Arco-Íris","SP"));
        lista.add(new Cidade("WzQ8dVBZzeUTTP6Y1sbJ","Arealva","SP"));
        lista.add(new Cidade("1koDjTpKtGgEHpQijHFH","Areias","SP"));
        lista.add(new Cidade("kVN7DWt8wQvTEtIS8uaN","Areiópolis","SP"));
        lista.add(new Cidade("AWqhH6neQeW3F8Cg0s7y","Ariranha","SP"));
        lista.add(new Cidade("CDJ6xh89PZzWdQPbe4BJ","Artur Nogueira","SP"));
        lista.add(new Cidade("iSckvS0Fh4YZ4yijY2Pj","Arujá","SP"));
        lista.add(new Cidade("L6FkbuoOV87OdBBvDLnn","Aspásia","SP"));
        lista.add(new Cidade("Wbl9hgBlHGI9KXcEL8CF","Assis","SP"));
        lista.add(new Cidade("NB6VT0UuOPGjxJ5tPBmd","Atibaia","SP"));
        lista.add(new Cidade("Q7SX4bnJ4pUXPNDSyt2l","Auriflama","SP"));
        lista.add(new Cidade("D14Zh6nF9FWYXESdlib3","Avaí","SP"));
        lista.add(new Cidade("7IeQ6n8KbFfsHkbCdCjN","Avanhandava","SP"));
        lista.add(new Cidade("Sxs4tt8wKdiUgF7ukYUW","Avaré","SP"));
        lista.add(new Cidade("gLmpJsVazQXhlWAeOMC7","Bady Bassitt","SP"));
        lista.add(new Cidade("KR9XokKveg0RZQul3QZs","Balbinos","SP"));
        lista.add(new Cidade("eJlxHYNaQmcaXKhljCTx","Bálsamo","SP"));
        lista.add(new Cidade("thgCyZUrGELwO30x9q0h","Bananal","SP"));
        lista.add(new Cidade("ANC7xV3ajhDYqkpqsH0j","Barão de Antonina","SP"));
        lista.add(new Cidade("DbRJf8xh7EJD2F7gEAqQ","Barbosa","SP"));
        lista.add(new Cidade("87pYMOCoxsGK6s3lm7Dx","Bariri","SP"));
        lista.add(new Cidade("eJVjNbLO9WWMlZGtbFzg","Barra Bonita","SP"));
        lista.add(new Cidade("UK4FOlU652wbP4TARMON","Barra do Chapéu","SP"));
        lista.add(new Cidade("nZxZyoOfayfKe97YhLvP","Barra do Turvo","SP"));
        lista.add(new Cidade("Knk72RRzWVnEMa0QXsRF","Barretos","SP"));
        lista.add(new Cidade("IHBLWn5Yb0z6z93mpruB","Barrinha","SP"));
        lista.add(new Cidade("Sdi7QgwFaZbfkHXhH0AZ","Barueri","SP"));
        lista.add(new Cidade("S6sh8xdO3WvVGwgLiPSt","Bastos","SP"));
        lista.add(new Cidade("3UjgLfqt9QlPcVtsdv1Q","Batatais","SP"));
        lista.add(new Cidade("igSoy2xkcUuqVW8QAT5B","Bauru","SP"));
        lista.add(new Cidade("leEsmXnHMFUidwqLrvfa","Bebedouro","SP"));
        lista.add(new Cidade("zRr9ICdq0hmWr8V2sMXD","Bento de Abreu","SP"));
        lista.add(new Cidade("mIZdvHm9jTxHgG4w0Fk4","Bernardino de Campos","SP"));
        lista.add(new Cidade("hCiCfiEX9VjYHxgj42AZ","Bertioga","SP"));
        lista.add(new Cidade("eR9LfIleRKqKadoYjzqV","Bilac","SP"));
        lista.add(new Cidade("Qdd6pyRzPvVkd95SXw74","Birigui","SP"));
        lista.add(new Cidade("hdihOsRF6GOeuldYkp8Y","Biritiba-Mirim","SP"));
        lista.add(new Cidade("iq0Iy3HmZZNt0q2lj6ES","Boa Esperança do Sul","SP"));
        lista.add(new Cidade("EVv28ZZlbveidYcmHaF5","Bocaina","SP"));
        lista.add(new Cidade("iFo4OzEfaVT47QBr8DCO","Bofete","SP"));
        lista.add(new Cidade("4KyxSOSoKleXRkgsMS6B","Boituva","SP"));
        lista.add(new Cidade("3ooE7BLtF9tBzInpzvAP","Bom Jesus dos Perdões","SP"));
        lista.add(new Cidade("deryrVkUEJCd2KQJCp4E","Bom Sucesso de Itararé","SP"));
        lista.add(new Cidade("kc4XisnsBByLeHvqrRvX","Borá","SP"));
        lista.add(new Cidade("aEZDnfg2bH6KCv6ZHF0i","Boracéia","SP"));
        lista.add(new Cidade("CKBX1pKy7BVAD8PNW6J4","Borborema","SP"));
        lista.add(new Cidade("6VnVoX7gltsthhse1WwW","Borebi","SP"));
        lista.add(new Cidade("UtJiSFFwKpzumn8qQ1gO","Botucatu","SP"));
        lista.add(new Cidade("1Ye0ZImdSshB3RsMj7dc","Bragança Paulista","SP"));
        lista.add(new Cidade("NOFxwEiHJV8p9GqKPaEC","Braúna","SP"));
        lista.add(new Cidade("SInPWYy8ddxq4R87FicX","Brejo Alegre","SP"));
        lista.add(new Cidade("rLGSIsiLuoevyVKhcvar","Brodowski","SP"));
        lista.add(new Cidade("MKEuYK0NOfhlyDlQXtTC","Brotas","SP"));
        lista.add(new Cidade("8eqR37SBNI7fJg22KD2B","Buri","SP"));
        lista.add(new Cidade("BZy9GEDEqdL00PjrXkEF","Buritama","SP"));
        lista.add(new Cidade("btxJKXvDxF5mJCeYHZct","Buritizal","SP"));
        lista.add(new Cidade("Cmmf9NPDHdaBZPV1wbPh","Cabrália Paulista","SP"));
        lista.add(new Cidade("7ZqqMIpl6DTWmDH6Kt4j","Cabreúva","SP"));
        lista.add(new Cidade("xwOEAZ8CYtpNj1viYfFo","Caçapava","SP"));
        lista.add(new Cidade("5AbQE9MrIcMgnyNXwB8Z","Cachoeira Paulista","SP"));
        lista.add(new Cidade("CqRmEfhdh1NBNuNTG07Y","Caconde","SP"));
        lista.add(new Cidade("tA0b2aFEVkITWehw7TNW","Cafelândia","SP"));
        lista.add(new Cidade("zapezqa12s3VmTPL4Pon","Caiabu","SP"));
        lista.add(new Cidade("FbHGJXiuXBr2pWuN3V2T","Caieiras","SP"));
        lista.add(new Cidade("qBM2SAeSG0pN9aF06QaH","Caiuá","SP"));
        lista.add(new Cidade("KhUkldYeSiOhz0cHocdH","Cajamar","SP"));
        lista.add(new Cidade("dKKPYJZAZNJpjq4x7eZN","Cajati","SP"));
        lista.add(new Cidade("X9viXIrKvHTaKYZB4nIr","Cajobi","SP"));
        lista.add(new Cidade("fSOurHOUx7wphAjwOx15","Cajuru","SP"));
        lista.add(new Cidade("bYviSVLjTpTt1H3YxYDE","Campina do Monte Alegre","SP"));
        lista.add(new Cidade("kAZxNqTkUbjexrJNFkwf","Campinas","SP"));
        lista.add(new Cidade("TpI6ZG49wFdIIwMjKUkc","Campo Limpo Paulista","SP"));
        lista.add(new Cidade("oTgpmRMqSXSG744Ji7KI","Campos do Jordão","SP"));
        lista.add(new Cidade("9a2RHgJEHIATw16ix5R4","Campos Novos Paulista","SP"));
        lista.add(new Cidade("f3uaQf0fiTtqDVVuHi8m","Cananéia","SP"));
        lista.add(new Cidade("iGgqLBzBnx0oQSWwkwux","Canas","SP"));
        lista.add(new Cidade("ectJA0SACy6qIRr46rNU","Cândido Mota","SP"));
        lista.add(new Cidade("B0415gs6vTbbR2qUiO3h","Cândido Rodrigues","SP"));
        lista.add(new Cidade("MHms4YZKQ5HooW42DmGz","Canitar","SP"));
        lista.add(new Cidade("MTG6adzCbhjAtVqxXmDZ","Capão Bonito","SP"));
        lista.add(new Cidade("cjnhAjw6wXpNLtVUnOeZ","Capela do Alto","SP"));
        lista.add(new Cidade("Eah0eCAPVlamohrkeo7k","Capivari","SP"));
        lista.add(new Cidade("xhziXvVGbitKR294n9A6","Caraguatatuba","SP"));
        lista.add(new Cidade("jDQS9L47NIILJccuxCZA","Carapicuíba","SP"));
        lista.add(new Cidade("kHTHXJmwadU4NPIoj7K5","Cardoso","SP"));
        lista.add(new Cidade("9EeknTXjpIzJIgSUFItD","Casa Branca","SP"));
        lista.add(new Cidade("sGlPFCNQ6zNY985sKieb","Cássia dos Coqueiros","SP"));
        lista.add(new Cidade("gzGezRU7GdqN5gzbvIPs","Castilho","SP"));
        lista.add(new Cidade("OTDmg2sXiFbO7zjGvmy0","Catanduva","SP"));
        lista.add(new Cidade("XF6nOuoEUnjdswZjrLI6","Catiguá","SP"));
        lista.add(new Cidade("YzpQF2JIhsI7x3U6mWL4","Cedral","SP"));
        lista.add(new Cidade("GzUVaUpszYlTarCVHuqj","Cerqueira César","SP"));
        lista.add(new Cidade("tlQhIfH5TN0hEQc81VZc","Cerquilho","SP"));
        lista.add(new Cidade("H0izqJQDORVOp0bD5PGN","Cesário Lange","SP"));
        lista.add(new Cidade("dFw1MOImoYEy2RJQbDOC","Charqueada","SP"));
        lista.add(new Cidade("9ZtSjXvitWr9lwLvUWDM","Chavantes","SP"));
        lista.add(new Cidade("wiG1CZhxBQklWgseLYSf","Clementina","SP"));
        lista.add(new Cidade("gByabbZPSj2COrlhST7S","Colina","SP"));
        lista.add(new Cidade("zaKCeXaBqhBoDA4mTyj2","Colômbia","SP"));
        lista.add(new Cidade("TZu4gvKAXtWb4ZcwaeqK","Conchal","SP"));
        lista.add(new Cidade("48KB0U2EvISwne7froUi","Conchas","SP"));
        lista.add(new Cidade("AWD3eMP3OKij5kbgtv3K","Cordeirópolis","SP"));
        lista.add(new Cidade("F2DqpUZY1FOyIBixvKEa","Coroados","SP"));
        lista.add(new Cidade("zAqJLYlfT8OH9ENwMbpc","Coronel Macedo","SP"));
        lista.add(new Cidade("mb4ttiyCM3u9FAQ8w7Iv","Corumbataí","SP"));
        lista.add(new Cidade("xcFL5a5XDzoupIj72Ght","Cosmópolis","SP"));
        lista.add(new Cidade("pfHvyAIbM38oz7NRuG6u","Cosmorama","SP"));
        lista.add(new Cidade("6flliKthSpczIVfJFHZY","Cotia","SP"));
        lista.add(new Cidade("YlbfpnwxOZqZyZ7kcKhf","Cravinhos","SP"));
        lista.add(new Cidade("aKilZLSxFAV2S0ZYL3x2","Cristais Paulista","SP"));
        lista.add(new Cidade("d03qI8uaIxRjv2bVQCv7","Cruzália","SP"));
        lista.add(new Cidade("uUYkexdA4w9wYXO19Pc0","Cruzeiro","SP"));
        lista.add(new Cidade("HXtntT4FpOpbkZ59olUz","Cubatão","SP"));
        lista.add(new Cidade("1KCwW2NY86aYq0ii9lKg","Cunha","SP"));
        lista.add(new Cidade("TBvRbj5Mq3KrAoeZZwl3","Descalvado","SP"));
        lista.add(new Cidade("qaKDRUKsC5Wlc0xDgtSW","Diadema","SP"));
        lista.add(new Cidade("HgnQxv3o2HuIeS2HzqHm","Dirce Reis","SP"));
        lista.add(new Cidade("d0Up2o5vEAXA53PQlRZC","Divinolândia","SP"));
        lista.add(new Cidade("tbmkaquhU1rkVopYDXrU","Dobrada","SP"));
        lista.add(new Cidade("rWn3eVqb02JYFXmWpkp1","Dois Córregos","SP"));
        lista.add(new Cidade("a3HaUc2zv9r1DLJgWktR","Dolcinópolis","SP"));
        lista.add(new Cidade("kvihiMGmA54ONIx89Srd","Dourado","SP"));
        lista.add(new Cidade("t3UUMFzkx9baIXp0pc0D","Dracena","SP"));
        lista.add(new Cidade("zC0V7Dh9nBxjpFoEdgby","Duartina","SP"));
        lista.add(new Cidade("Rgj0EkaULLC8ZfvZJ5aZ","Dumont","SP"));
        lista.add(new Cidade("jYfUPYHvBovj3LVE3zy5","Echaporã","SP"));
        lista.add(new Cidade("uES3SYyupa2f0lxJ3uiM","Eldorado","SP"));
        lista.add(new Cidade("kAIcb5rftOMQw3RFMY44","Elias Fausto","SP"));
        lista.add(new Cidade("xEVJKVqMHD1hQgIJhlVX","Elisiário","SP"));
        lista.add(new Cidade("PaRjUTA8Jm76nfCpsCXt","Embaúba","SP"));
        lista.add(new Cidade("piBPaNBHi5whgwVHHtNo","Embu","SP"));
        lista.add(new Cidade("3k4fdajewuHjc30ocMAQ","Embu-Guaçu","SP"));
        lista.add(new Cidade("XZTuimGk7aSrjZCAY4Sw","Emilianópolis","SP"));
        lista.add(new Cidade("SWC3S9IKzfSxG6JSW12L","Engenheiro Coelho","SP"));
        lista.add(new Cidade("B35qvMNg2z8OuBAlFXUH","Espírito Santo do Pinhal","SP"));
        lista.add(new Cidade("8PCSaqIg2Zk7Nduv6HY7","Espírito Santo do Turvo","SP"));
        lista.add(new Cidade("dtrqOcBZ97kJfbH8PrAE","Estiva Gerbi","SP"));
        lista.add(new Cidade("YKgHeLex3KArxUZpFFsQ","Estrela d'Oeste","SP"));
        lista.add(new Cidade("c92YFLtApUL4stQJCmDs","Estrela do Norte","SP"));
        lista.add(new Cidade("x4mxgvqZLE5bhVwAtlvX","Euclides da Cunha Paulista","SP"));
        lista.add(new Cidade("P2k8Mtj9obbjVuibU31S","Fartura","SP"));
        lista.add(new Cidade("LekXe6kv2IEi7Ll692KS","Fernando Prestes","SP"));
        lista.add(new Cidade("5gLcXOk2QQ1ks6yqhHZz","Fernandópolis","SP"));
        lista.add(new Cidade("rdoi6jOIdrdpjAtYq7s8","Fernão","SP"));
        lista.add(new Cidade("CD3RjtOHCOCad8WKNeQ6","Ferraz de Vasconcelos","SP"));
        lista.add(new Cidade("HpNdg4uBDYTGW0JnbPd1","Flora Rica","SP"));
        lista.add(new Cidade("tlKAvp4TXrtO2aPdThqT","Floreal","SP"));
        lista.add(new Cidade("zXtQpDUAUyzjIMfQ3tLq","Florínia","SP"));
        lista.add(new Cidade("vRlErRElQix6deqBmpHe","Flórida Paulista","SP"));
        lista.add(new Cidade("DPDpimxWah6iBuKEHmb7","Franca","SP"));
        lista.add(new Cidade("l4Ul2MHn9KWrPG2s7u6R","Francisco Morato","SP"));
        lista.add(new Cidade("lM1mAaJKG14YuSwWUmvq","Franco da Rocha","SP"));
        lista.add(new Cidade("d5feAWwuLgRb4qkW6uiq","Gabriel Monteiro","SP"));
        lista.add(new Cidade("NAQDVh6wiaFHwGkmrUCo","Gália","SP"));
        lista.add(new Cidade("fjjNoh3NPr1whB9jqijz","Garça","SP"));
        lista.add(new Cidade("PL71mZNjYM93YBXjvAGT","Gastão Vidigal","SP"));
        lista.add(new Cidade("TfNjSywYj94ylm6pK5jO","Gavião Peixoto","SP"));
        lista.add(new Cidade("Y1c4S6DIIs5B9G6hJusV","General Salgado","SP"));
        lista.add(new Cidade("r1AHun7mIbNnvFdwGRRR","Getulina","SP"));
        lista.add(new Cidade("z9uFNID7OCt3mkt0jU04","Glicério","SP"));
        lista.add(new Cidade("ZDlrpZ4HUI90gnzgMe6w","Guaiçara","SP"));
        lista.add(new Cidade("miyJA4nR0WMFeJ9Ijy6j","Guaimbê","SP"));
        lista.add(new Cidade("7ky3gKYNrrRq3iOrmibY","Guaíra","SP"));
        lista.add(new Cidade("wg86Zmj1ps17VDWwnwuJ","Guapiaçu","SP"));
        lista.add(new Cidade("9d8WyyyhfgfDiyhaKwJG","Guapiara","SP"));
        lista.add(new Cidade("sX9BN3bzHrlR7URHWoAM","Guará","SP"));
        lista.add(new Cidade("DL6IkhhgA8M5Yo4XS5g2","Guaraçaí","SP"));
        lista.add(new Cidade("rGFUjdLrva3gFGcjv5DG","Guaraci","SP"));
        lista.add(new Cidade("PYMKHU0wu07Ligt92VvW","Guarani d'Oeste","SP"));
        lista.add(new Cidade("qxib1dDUAyjfXajDLjZ6","Guarantã","SP"));
        lista.add(new Cidade("HkWNkAAFOCrK4mrHKYeE","Guararapes","SP"));
        lista.add(new Cidade("a0SZa3sGJKF6f3EvXZSH","Guararema","SP"));
        lista.add(new Cidade("1yJrmj9mYxb8UnbTWVwt","Guaratinguetá","SP"));
        lista.add(new Cidade("PxhZskfHgwss7nfpjMpv","Guareí","SP"));
        lista.add(new Cidade("gJgI5piPT9gQeFs0F5hU","Guariba","SP"));
        lista.add(new Cidade("zm53zIVUtBtID25FGDBA","Guarujá","SP"));
        lista.add(new Cidade("cg4htjR1I6DiqPmn3Sud","Guarulhos","SP"));
        lista.add(new Cidade("pyenNbMBl0k9n2hx5xRA","Guatapará","SP"));
        lista.add(new Cidade("rwVwYaCfdTaVwDnZwNKB","Guzolândia","SP"));
        lista.add(new Cidade("hX3NApSSu68uI2hchcDr","Herculândia","SP"));
        lista.add(new Cidade("Z1WQtlysJBQL1SY7PpZX","Holambra","SP"));
        lista.add(new Cidade("Bu0iESLLeLPCt5E5RScj","Hortolândia","SP"));
        lista.add(new Cidade("LcQa2b3uUD4G7J3L34wv","Iacanga","SP"));
        lista.add(new Cidade("357eATqkDJUQU50YDTkx","Iacri","SP"));
        lista.add(new Cidade("0elCVsLsDhQUVmsXornu","Iaras","SP"));
        lista.add(new Cidade("cDSsdQAFMnzBT4KJ8SR4","Ibaté","SP"));
        lista.add(new Cidade("CMjYr0FQBUoLIezj4ZKh","Ibirá","SP"));
        lista.add(new Cidade("8XePXh6gdSaiELQRLHzr","Ibirarema","SP"));
        lista.add(new Cidade("ZRGyIfkGIPFMcxiJcXzQ","Ibitinga","SP"));
        lista.add(new Cidade("fAY4uKFfo0Qi6QANjj28","Ibiúna","SP"));
        lista.add(new Cidade("B9fQfO4OSn6Ro00CFRke","Icém","SP"));
        lista.add(new Cidade("vlL2YLxSTMI4cRo3shIy","Iepê","SP"));
        lista.add(new Cidade("tKNEZf8rdLyGdl7ulHuB","Igaraçu do Tietê","SP"));
        lista.add(new Cidade("32WBU9ZZdcJ2aq0ot23b","Igarapava","SP"));
        lista.add(new Cidade("hH1rDf4jCDqwmAe6Z9OA","Igaratá","SP"));
        lista.add(new Cidade("jwd49isLGG4zY1pzCNKO","Iguape","SP"));
        lista.add(new Cidade("F9AjzOn8TGC6xC3b22lL","Ilha Comprida","SP"));
        lista.add(new Cidade("5RWr8npqD0yySFkyNxi2","Ilha Solteira","SP"));
        lista.add(new Cidade("Dhl8Ea89nGd0SdMYsJdA","Ilhabela","SP"));
        lista.add(new Cidade("AUUMSqEHtAohPO7IvKxl","Indaiatuba","SP"));
        lista.add(new Cidade("MnUWTHOQcglqGvaA00Eg","Indiana","SP"));
        lista.add(new Cidade("49bYrpRHepoVSLWexvGC","Indiaporã","SP"));
        lista.add(new Cidade("lFVAw16mghq1Wda0Rt6x","Inúbia Paulista","SP"));
        lista.add(new Cidade("0mA25HqdTgFRcUchOWqt","Ipauçu","SP"));
        lista.add(new Cidade("TMEgc2iLt67P03S3DbL7","Iperó","SP"));
        lista.add(new Cidade("xbcE6l1qVu0dRdYQ3Z3s","Ipeúna","SP"));
        lista.add(new Cidade("hsVDZBGjO39vb4goHHpl","Ipiguá","SP"));
        lista.add(new Cidade("FgUWvmXXIZAPjLVKOkFt","Iporanga","SP"));
        lista.add(new Cidade("ooKxHue80f2PtFGBpfnK","Ipuã","SP"));
        lista.add(new Cidade("A6s94vWD7fQa05EySbIr","Iracemápolis","SP"));
        lista.add(new Cidade("bxQhdKKWggqspOMioYW8","Irapuã","SP"));
        lista.add(new Cidade("n1PvImpgBIr4y5JbfhUs","Irapuru","SP"));
        lista.add(new Cidade("bTbjguqdnutLbqhaYjuO","Itaberá","SP"));
        lista.add(new Cidade("8mOC3lkl2s6UEJgMW5l3","Itaí","SP"));
        lista.add(new Cidade("IqIA0hFdwtFuJL7z6y2n","Itajobi","SP"));
        lista.add(new Cidade("qwm796BS8dEtjDxd3snp","Itaju","SP"));
        lista.add(new Cidade("uOYckVsceny9z3P0fgDb","Itanhaém","SP"));
        lista.add(new Cidade("Vf98Ti7e5fYM7PO6Yl8d","Itaóca","SP"));
        lista.add(new Cidade("RuZdqecc6EAKpKcZS4mH","Itapecerica da Serra","SP"));
        lista.add(new Cidade("Z1ruryvE6AxNnDMdiojA","Itapetininga","SP"));
        lista.add(new Cidade("9mMIHGstrUuUbNvYsPiw","Itapeva","SP"));
        lista.add(new Cidade("um90wLusrXZjkaaa4Tlt","Itapevi","SP"));
        lista.add(new Cidade("vAUVG5gQEvDCo8mtsFCh","Itapira","SP"));
        lista.add(new Cidade("5O86V4CfnETCMES9bcdX","Itapirapuã Paulista","SP"));
        lista.add(new Cidade("JlGsjao2GhZOXfFEAMoF","Itápolis","SP"));
        lista.add(new Cidade("fAwFHd6nkZxYvRScZRrS","Itaporanga","SP"));
        lista.add(new Cidade("glhYl7ncYElOJPYZbggr","Itapuí","SP"));
        lista.add(new Cidade("UWYGWXQqtGPb69iYT8t7","Itapura","SP"));
        lista.add(new Cidade("2Av8TEPLuBMCra9ITm3a","Itaquaquecetuba","SP"));
        lista.add(new Cidade("iho8SqHSilyY8CgGuPtO","Itararé","SP"));
        lista.add(new Cidade("iWFMNpZXeQQOql8SgJgd","Itariri","SP"));
        lista.add(new Cidade("ipg3YE2zbB2MaKytLRAc","Itatiba","SP"));
        lista.add(new Cidade("j1kLsMRMqw0l0qNviGeb","Itatinga","SP"));
        lista.add(new Cidade("0jnECtHHUczMDaQr5Izr","Itirapina","SP"));
        lista.add(new Cidade("RPDqgXmXScKdXnQKJH45","Itirapuã","SP"));
        lista.add(new Cidade("4GZ0owWfKy36JtPUTaKU","Itobi","SP"));
        lista.add(new Cidade("BdWjDOhQ7DTTyjGZihao","Itu","SP"));
        lista.add(new Cidade("orTA8Ur90JGoTxvcYU57","Itupeva","SP"));
        lista.add(new Cidade("sckERq16JD3Ws8z3sSOd","Ituverava","SP"));
        lista.add(new Cidade("9XfamIDUTP1tS4S4uC3k","Jaborandi","SP"));
        lista.add(new Cidade("VHq6e1ygtDXgF9Rey79E","Jaboticabal","SP"));
        lista.add(new Cidade("XYt6ybBH4qowmpN1fANF","Jacareí","SP"));
        lista.add(new Cidade("mxhgZEjLXhRSKEGN2cFx","Jaci","SP"));
        lista.add(new Cidade("YAbKiD7dDywxtQTPqcdk","Jacupiranga","SP"));
        lista.add(new Cidade("ueBIvjnZXNjIU8pxKkTS","Jaguariúna","SP"));
        lista.add(new Cidade("uYGkiO49b7MobKxwcSNf","Jales","SP"));
        lista.add(new Cidade("433dnhzxmVsi41k7xTIg","Jambeiro","SP"));
        lista.add(new Cidade("jAduukhmtItCKqMQQbjd","Jandira","SP"));
        lista.add(new Cidade("ooensBrsERFaDyUZ5wyY","Jardinópolis","SP"));
        lista.add(new Cidade("JxL9fOW64QBBuRpdhoWQ","Jarinu","SP"));
        lista.add(new Cidade("gGMVbMD2eA2AtwbjaMLr","Jaú","SP"));
        lista.add(new Cidade("8wBMoxlIA5zHB4woo4uf","Jeriquara","SP"));
        lista.add(new Cidade("APgyTxAw5NpB7coJtknM","Joanópolis","SP"));
        lista.add(new Cidade("KUOWVCPrpW5nXuMRLI5z","João Ramalho","SP"));
        lista.add(new Cidade("Gz8P1ke97hhROQ6goAu9","José Bonifácio","SP"));
        lista.add(new Cidade("bBzYHjKlpdhcVwL1TQZV","Júlio Mesquita","SP"));
        lista.add(new Cidade("MD1e1cmCMeUzeWf1cUB3","Jumirim","SP"));
        lista.add(new Cidade("Xa92Cnjwa6CAebO1lg7P","Jundiaí","SP"));
        lista.add(new Cidade("eRiPJN6TaAFdBtJrqYOh","Junqueirópolis","SP"));
        lista.add(new Cidade("oRkHtYeBBPA6KGyWKut4","Juquiá","SP"));
        lista.add(new Cidade("h5GR2L5khbuKP8g58NpY","Juquitiba","SP"));
        lista.add(new Cidade("Ezlk1lCX9Ey7qoI0KHGt","Lagoinha","SP"));
        lista.add(new Cidade("z3PLoUnzhJJF9N1EeE4K","Laranjal Paulista","SP"));
        lista.add(new Cidade("mIDUjLYOyjsRQpxWht10","Lavínia","SP"));
        lista.add(new Cidade("X3P2n0DvcXjvyWQBOIYa","Lavrinhas","SP"));
        lista.add(new Cidade("DLjSKf7R3hbpVCIPCAtv","Leme","SP"));
        lista.add(new Cidade("unFyNrx3V8Q3qlnzGbj2","Lençóis Paulista","SP"));
        lista.add(new Cidade("nY4DIITezdq0ONGnkcGl","Limeira","SP"));
        lista.add(new Cidade("QiBRAzllCIC5NearaoYa","Lindóia","SP"));
        lista.add(new Cidade("bcr3bFN45HxuSgLsWz6r","Lins","SP"));
        lista.add(new Cidade("sAiM8nFhI8J1dO8CZ7u1","Lorena","SP"));
        lista.add(new Cidade("8gRPV4W6aOj02z3vM4GY","Lourdes","SP"));
        lista.add(new Cidade("48IK21FLsmVLcmMzvzT7","Louveira","SP"));
        lista.add(new Cidade("NRwpyaQ4JVlTbtyj3m9S","Lucélia","SP"));
        lista.add(new Cidade("9zjnfomtGTg5kuupSkpB","Lucianópolis","SP"));
        lista.add(new Cidade("xT0FWsiHMhU8TyePEQam","Luís Antônio","SP"));
        lista.add(new Cidade("WHrIrXgPKVGjWhBQnPvm","Luiziânia","SP"));
        lista.add(new Cidade("4v0DQ9e6hbFtd1xcwIOI","Lupércio","SP"));
        lista.add(new Cidade("bTnkjJ15tYrzQtLFxS0J","Lutécia","SP"));
        lista.add(new Cidade("KsmEc5e1ApJAnRGR6XjM","Macatuba","SP"));
        lista.add(new Cidade("NIOWmbhRqCgu1bHAnusa","Macaubal","SP"));
        lista.add(new Cidade("lI2s0KseqAgGR7sxGiDA","Macedônia","SP"));
        lista.add(new Cidade("CO4yh2NvWAXGCCGcR6SG","Magda","SP"));
        lista.add(new Cidade("YtU8VrNsJO3xFMc1Oejk","Mairinque","SP"));
        lista.add(new Cidade("4MKhkJ3rKBU5pNwF8rau","Mairiporã","SP"));
        lista.add(new Cidade("VTzNI2jzfKvbMxfQp4L1","Manduri","SP"));
        lista.add(new Cidade("Nw4HYyJItkgjj28v4XVo","Marabá Paulista","SP"));
        lista.add(new Cidade("doYfMNw3CYK1gRS47gEb","Maracaí","SP"));
        lista.add(new Cidade("IC1EyMpAFbYglt1gdEc8","Marapoama","SP"));
        lista.add(new Cidade("OLumJISeLANi6L5YOKik","Mariápolis","SP"));
        lista.add(new Cidade("3ophlxDfPQnjM2cJ0yXr","Marília","SP"));
        lista.add(new Cidade("9NOYLIaxmAGTP9UXaGsW","Marinópolis","SP"));
        lista.add(new Cidade("omfxJwPkjDtpMBhjw9GE","Martinópolis","SP"));
        lista.add(new Cidade("co6s37lIQUwKrIHsgHJ9","Matão","SP"));
        lista.add(new Cidade("dVsOhWqVvK2UGLr1zIlU","Mauá","SP"));
        lista.add(new Cidade("lCgGElLZCB9BC6nSEe8H","Mendonça","SP"));
        lista.add(new Cidade("DGON8ABMDIUDZHeJ0QDk","Meridiano","SP"));
        lista.add(new Cidade("N15bQyo9CbKB9QE7YKhm","Mesópolis","SP"));
        lista.add(new Cidade("fIo5KkYYCo85wtCQrDAz","Miguelópolis","SP"));
        lista.add(new Cidade("kROWdcHabTgJL9CyRwg6","Mineiros do Tietê","SP"));
        lista.add(new Cidade("LQIOQCD9nSrud5RKRkZS","Mira Estrela","SP"));
        lista.add(new Cidade("75KahTuAGbb2YtZZFThU","Miracatu","SP"));
        lista.add(new Cidade("FdFzM0XX0riBN5kYO0sE","Mirandópolis","SP"));
        lista.add(new Cidade("iCCanlnBYClJ92CGVglY","Mirante do Paranapanema","SP"));
        lista.add(new Cidade("yd9Bozt62ZeUKn6Rzydw","Mirassol","SP"));
        lista.add(new Cidade("VAH5NNSKf5UHrzA1VQlr","Mirassolândia","SP"));
        lista.add(new Cidade("ROd9zjNJmjMpbNP5hD8p","Mococa","SP"));
        lista.add(new Cidade("5TBW5KvCtrhyvtq37PMh","Mogi das Cruzes","SP"));
        lista.add(new Cidade("KFx2QooqzjfwSS5yuuPi","Mogi-Guaçu","SP"));
        lista.add(new Cidade("6CG6szC5T1QlvkCd8kwy","Mogi-Mirim","SP"));
        lista.add(new Cidade("8NrJxUEOWh8kVCmEb1Z5","Mombuca","SP"));
        lista.add(new Cidade("RdJSOQxzcfLuA0SekQ6V","Monções","SP"));
        lista.add(new Cidade("DRo2ltSrWnkZtgGsdjas","Mongaguá","SP"));
        lista.add(new Cidade("K1nh5QaDgYyEsD2wPsjy","Monte Alegre do Sul","SP"));
        lista.add(new Cidade("HVgxlJYiXOcfpVTO7PvD","Monte Alto","SP"));
        lista.add(new Cidade("DjfDFJYVcSYCWhfPktwy","Monte Aprazível","SP"));
        lista.add(new Cidade("JwOfzy2BM0qDtC29cLuf","Monte Azul Paulista","SP"));
        lista.add(new Cidade("ir5CQANV8MunC1vmk6fd","Monte Castelo","SP"));
        lista.add(new Cidade("72jukrsyOqLLs7bhzz7B","Monte Mor","SP"));
        lista.add(new Cidade("e0qgVzzhvkGScf1dU3jF","Monteiro Lobato","SP"));
        lista.add(new Cidade("45FXFFX7880hEgoWwNEj","Morro Agudo","SP"));
        lista.add(new Cidade("2l6H3TwoQFkIoN4Zimhl","Morungaba","SP"));
        lista.add(new Cidade("GXEt6lfMQsUcch87SN8B","Motuca","SP"));
        lista.add(new Cidade("CJkClhE9okkT1jFLbHDj","Murutinga do Sul","SP"));
        lista.add(new Cidade("LuD0R6aojHsyXzJz3R2V","Nantes","SP"));
        lista.add(new Cidade("FG16Do3vRC4gpj6T0Pxw","Narandiba","SP"));
        lista.add(new Cidade("QJ4yIYoa4rObq4CC7yWC","Natividade da Serra","SP"));
        lista.add(new Cidade("PWZokHnnITmClyOQ1rwp","Nazaré Paulista","SP"));
        lista.add(new Cidade("ddKHo5acrPWCxRFOrPmN","Neves Paulista","SP"));
        lista.add(new Cidade("XwRiTrckZih9stfJUmMN","Nhandeara","SP"));
        lista.add(new Cidade("7xV80nHsa2QsK3l0gAAR","Nipoã","SP"));
        lista.add(new Cidade("AN8fHMHqXPyOBmaWRBtP","Nova Aliança","SP"));
        lista.add(new Cidade("XS8QeGtDkrFLgVWcsGY4","Nova Campina","SP"));
        lista.add(new Cidade("aN5Ovx7xANCjOngaWYfT","Nova Canaã Paulista","SP"));
        lista.add(new Cidade("CqiMMFFTfAP28CIuOAtX","Nova Castilho","SP"));
        lista.add(new Cidade("kiR95RZ3FAWpOEpTZjED","Nova Europa","SP"));
        lista.add(new Cidade("oWYC7ePHIDYyQTUZ5dsD","Nova Granada","SP"));
        lista.add(new Cidade("RCj9g8kGFum9P4R5qgbi","Nova Guataporanga","SP"));
        lista.add(new Cidade("6kGIrGY6iIiNdz8uoYfg","Nova Independência","SP"));
        lista.add(new Cidade("IJPKvD170FHWvYj7UacO","Nova Luzitânia","SP"));
        lista.add(new Cidade("4eJfdhUU6E0FGee3GHg7","Nova Odessa","SP"));
        lista.add(new Cidade("n2PC6E3f3GfatE1xV8ui","Novais","SP"));
        lista.add(new Cidade("yFwfs7AH6HuEmJsrccsK","Novo Horizonte","SP"));
        lista.add(new Cidade("F4n8DoSBMlDtwK9izXp3","Nuporanga","SP"));
        lista.add(new Cidade("Z0hGcINX7L6oIE8zEamh","Ocauçu","SP"));
        lista.add(new Cidade("TXRcDl3elLedcXCoymxV","Óleo","SP"));
        lista.add(new Cidade("o5K1e5XsUBOOaansdGxv","Olímpia","SP"));
        lista.add(new Cidade("K3KuxtxX3YVzx2LbtgFs","Onda Verde","SP"));
        lista.add(new Cidade("K7DAQDGGABhGG2HOgREJ","Oriente","SP"));
        lista.add(new Cidade("ObZUGPluDZL8A5jqErYf","Orindiúva","SP"));
        lista.add(new Cidade("wxe3KXGYN36UARLasWYo","Orlândia","SP"));
        lista.add(new Cidade("ZMqhOUi1dUOGnngNDuek","Osasco","SP"));
        lista.add(new Cidade("0FXzpEuSBMZ5PeygLvUR","Oscar Bressane","SP"));
        lista.add(new Cidade("apZmyRh6tDC9ABEfSnXl","Osvaldo Cruz","SP"));
        lista.add(new Cidade("GiJGcesZCxrZe676xLJW","Ourinhos","SP"));
        lista.add(new Cidade("4DXuRHdSyYVQGWMJZDdZ","Ouro Verde","SP"));
        lista.add(new Cidade("TrcH3d992ukO7Nxqe3Qc","Ouroeste","SP"));
        lista.add(new Cidade("WWfTL4H1DPTMZRxzio6B","Pacaembu","SP"));
        lista.add(new Cidade("377E8JAIRNNxZuj2NCza","Palestina","SP"));
        lista.add(new Cidade("3kb3E3CpE1UF6Cn7LgJ3","Palmares Paulista","SP"));
        lista.add(new Cidade("k4g4ruFQRRjPJp40hfOK","Palmeira d'Oeste","SP"));
        lista.add(new Cidade("Q4u9ybMs1vhstoSXjJK4","Palmital","SP"));
        lista.add(new Cidade("7JXwIT4ImzT8tAnY9KUL","Panorama","SP"));
        lista.add(new Cidade("IsBCzN0Bmx3kHGDhPgo3","Paraguaçu Paulista","SP"));
        lista.add(new Cidade("yj46V0OY78JZb10mDIyQ","Paraibuna","SP"));
        lista.add(new Cidade("pDToxunUeeD061pWfrNO","Paraíso","SP"));
        lista.add(new Cidade("EQzvGh8BhnZNlCZZb5aR","Paranapanema","SP"));
        lista.add(new Cidade("qtRX6notypff6yZdevdE","Paranapuã","SP"));
        lista.add(new Cidade("pCS6C8lKPjmg5DPJaKxR","Parapuã","SP"));
        lista.add(new Cidade("lgAmMyvz25sXRRc35R0E","Pardinho","SP"));
        lista.add(new Cidade("3BLhE40xD1aSL6Hc8YQi","Pariquera-Açu","SP"));
        lista.add(new Cidade("SS9hNGB6NqpPUvk2FZ1y","Parisi","SP"));
        lista.add(new Cidade("zxUOkwXkm3MbTQCimJ3v","Patrocínio Paulista","SP"));
        lista.add(new Cidade("PA2cEfvz2hGjVxUjPjKh","Paulicéia","SP"));
        lista.add(new Cidade("C2vsDbf92DUISXuvVC6k","Paulínia","SP"));
        lista.add(new Cidade("kf2tfEoT3KAme3QVsT5S","Paulistânia","SP"));
        lista.add(new Cidade("BGbHyoMR8Sg3j5yhvq6W","Paulo de Faria","SP"));
        lista.add(new Cidade("xlN04zjOaCPu72cYuZko","Pederneiras","SP"));
        lista.add(new Cidade("3B3nsPEmlKwmC4LWjUyM","Pedra Bela","SP"));
        lista.add(new Cidade("FuAjF3DhpX9Hkxhyn7lr","Pedranópolis","SP"));
        lista.add(new Cidade("KSE10j2FjYX5204Hr0bO","Pedregulho","SP"));
        lista.add(new Cidade("G9mXFwzLDIT2z8vReSMo","Pedreira","SP"));
        lista.add(new Cidade("UMM0vtKdAwYrO7lZue9o","Pedrinhas Paulista","SP"));
        lista.add(new Cidade("DpvcY7ny09JwCWWnnyfr","Pedro de Toledo","SP"));
        lista.add(new Cidade("bPQ3RUdi7nPEr7I1VMPV","Penápolis","SP"));
        lista.add(new Cidade("kBNtPFuBX3ZdNCuuCCrn","Pereira Barreto","SP"));
        lista.add(new Cidade("M0l5IIfy8p1cQKleMzM6","Pereiras","SP"));
        lista.add(new Cidade("cmRzzJij9zdBVWAhf6hZ","Peruíbe","SP"));
        lista.add(new Cidade("9yDMwVLpXA2KzYA7jEGY","Piacatu","SP"));
        lista.add(new Cidade("wgm7FqWsL5a5rojPpBBc","Piedade","SP"));
        lista.add(new Cidade("470LGeM4eaDEPyvqvVha","Pilar do Sul","SP"));
        lista.add(new Cidade("rRJSYfZOFEAIDNAh2g2A","Pindamonhangaba","SP"));
        lista.add(new Cidade("MTfxoQt7Ycir9UOE4H8b","Pindorama","SP"));
        lista.add(new Cidade("hjThi4JmkIBlzGoUeIQT","Pinhalzinho","SP"));
        lista.add(new Cidade("uTjZmXcc9pNk47GXHWbm","Piquerobi","SP"));
        lista.add(new Cidade("jDQWN2lYx8es8DCkEMki","Piquete","SP"));
        lista.add(new Cidade("hKaDwMoNpKIFUKp0Hxsx","Piracaia","SP"));
        lista.add(new Cidade("mbP2OE6e5Cc6ngZM0SGe","Piracicaba","SP"));
        lista.add(new Cidade("A6brNdksbLd9KiGGmsr9","Piraju","SP"));
        lista.add(new Cidade("ZAbJpHqFWolB0B8kjfjO","Pirajuí","SP"));
        lista.add(new Cidade("0qZSWY5uWmr7sSWk5T3Q","Pirangi","SP"));
        lista.add(new Cidade("A42vfx2wlzhPJzzQjRSP","Pirapora do Bom Jesus","SP"));
        lista.add(new Cidade("USNEfvYjb7TB5xH95e9V","Pirapozinho","SP"));
        lista.add(new Cidade("ULmmPSg5DNckednUS5ze","Pirassununga","SP"));
        lista.add(new Cidade("ZGhuiGqgXJnoLdkOjxPT","Piratininga","SP"));
        lista.add(new Cidade("zxYbBn7CU0cW08RhJB8s","Pitangueiras","SP"));
        lista.add(new Cidade("d9AHQe8FNGTlgf9ATOrq","Planalto","SP"));
        lista.add(new Cidade("0EILekYMNPuIlowTyZhT","Platina","SP"));
        lista.add(new Cidade("AzxmaueEYQaNDf37P83X","Poá","SP"));
        lista.add(new Cidade("BsJUT84g6IeBW42GKbL9","Poloni","SP"));
        lista.add(new Cidade("fb7Jkx6hDGR4iL4Hf0rh","Pompéia","SP"));
        lista.add(new Cidade("paXc1K2KWMO7BgnFh6k9","Pongaí","SP"));
        lista.add(new Cidade("uP4oV9J1qSV6WvLfSlbd","Pontal","SP"));
        lista.add(new Cidade("byyIYmu5Bm5myFkN3Qqp","Pontalinda","SP"));
        lista.add(new Cidade("WwasTAhtXdR399P6nez7","Pontes Gestal","SP"));
        lista.add(new Cidade("TTU26PDSqsi5L14Yv275","Populina","SP"));
        lista.add(new Cidade("NTOde0ra0mBFha44irMC","Porangaba","SP"));
        lista.add(new Cidade("BYVYRyXIGHK492pPdYqk","Porto Feliz","SP"));
        lista.add(new Cidade("7niM0fnmCVjtZtxaWza2","Porto Ferreira","SP"));
        lista.add(new Cidade("gsl60qWPI59AtO87SbSn","Potim","SP"));
        lista.add(new Cidade("6o4wvfoYHAZIvZxdrp3L","Potirendaba","SP"));
        lista.add(new Cidade("SJ3PSiz38rk2ChG4GXbx","Pracinha","SP"));
        lista.add(new Cidade("Q0fwdmKcWZFj1jXgQ83v","Pradópolis","SP"));
        lista.add(new Cidade("IteyPOzbECVQ3HyzXiT9","Praia Grande","SP"));
        lista.add(new Cidade("slKPzenW1pvHYPIWVF5X","Pratânia","SP"));
        lista.add(new Cidade("EKfQedOsZkSR36N1Z64Z","Presidente Alves","SP"));
        lista.add(new Cidade("nMSZ9m2nozP2H3NuTm29","Presidente Bernardes","SP"));
        lista.add(new Cidade("aB6cpM4BxuRGAyIL9JiO","Presidente Epitácio","SP"));
        lista.add(new Cidade("coV4S86fS4eZ19OZ8vz7","Presidente Prudente","SP"));
        lista.add(new Cidade("WO4mUWRcjunSfclX4mZc","Presidente Venceslau","SP"));
        lista.add(new Cidade("edgLN0yQekGtK9U26Uhx","Promissão","SP"));
        lista.add(new Cidade("lM9IDOQJcDmg9TABCjiO","Quadra","SP"));
        lista.add(new Cidade("WXVtAgCc8pMa21e0Bhwn","Quatá","SP"));
        lista.add(new Cidade("5owtJIMCZ1Y8EKFHzzQu","Queiroz","SP"));
        lista.add(new Cidade("g7jUxAnJFDNeRtUmsoBk","Queluz","SP"));
        lista.add(new Cidade("K2sZSKlLj3z3I4ifkkzZ","Quintana","SP"));
        lista.add(new Cidade("PMroEFs7yDO6DHgwAIJt","Rafard","SP"));
        lista.add(new Cidade("d2gYZtUjUvpBo3XaODR3","Rancharia","SP"));
        lista.add(new Cidade("MhNyyrQao8boqqV05d7K","Redenção da Serra","SP"));
        lista.add(new Cidade("Mi2rHc9OAZEIUXA3mjo0","Regente Feijó","SP"));
        lista.add(new Cidade("XivKf470YQHuVhCCadF7","Reginópolis","SP"));
        lista.add(new Cidade("MyivO1dB7u2LjPTY1H52","Registro","SP"));
        lista.add(new Cidade("AsoUkmfgy4GbbubSwv0m","Restinga","SP"));
        lista.add(new Cidade("dz0OGW6xVuKMBEekPuwd","Ribeira","SP"));
        lista.add(new Cidade("zPeRurG1swecp3N3STUZ","Ribeirão Bonito","SP"));
        lista.add(new Cidade("gFoHukIp5sxEhmdlIMi3","Ribeirão Branco","SP"));
        lista.add(new Cidade("ge57Sj2yV0ql6EYqgaly","Ribeirão Corrente","SP"));
        lista.add(new Cidade("c5Q6RVUrcGrFlHLriXNC","Ribeirão do Sul","SP"));
        lista.add(new Cidade("X2cSOGfa9T9JqZdoXKPL","Ribeirão dos Índios","SP"));
        lista.add(new Cidade("jXIqV5VaNnxdNZ8evql7","Ribeirão Grande","SP"));
        lista.add(new Cidade("yKcvxiRju3KBVgdByqfY","Ribeirão Pires","SP"));
        lista.add(new Cidade("PMqFv95r33L2Xp4w7Ltk","Ribeirão Preto","SP"));
        lista.add(new Cidade("TA0RVexZLIuIv6PsvXvb","Rifaina","SP"));
        lista.add(new Cidade("f5pj381atZeobZ3x8rRb","Rincão","SP"));
        lista.add(new Cidade("RMkcEG13iyCstk8QqIOr","Rinópolis","SP"));
        lista.add(new Cidade("9rUmzJLLkMQb2wt5URtc","Rio Claro","SP"));
        lista.add(new Cidade("HOaZnXD2lzVfW7GX3iNL","Rio das Pedras","SP"));
        lista.add(new Cidade("Q5zTZU35Jfrh2NEvy33L","Rio Grande da Serra","SP"));
        lista.add(new Cidade("3njlJd77W8vJ0O4uKPEo","Riolândia","SP"));
        lista.add(new Cidade("yhU3CBOAxwd7Nta75I5A","Riversul","SP"));
        lista.add(new Cidade("OIl1Kdnr3x75jv1rvJej","Rosana","SP"));
        lista.add(new Cidade("i2LHwKcEtjvdRRWkt0bJ","Roseira","SP"));
        lista.add(new Cidade("DAv6Y9g0jCPzrKEC2iIj","Rubiácea","SP"));
        lista.add(new Cidade("fSaKpZgOAXWUcBG97wev","Rubinéia","SP"));
        lista.add(new Cidade("pYfW4dzzgJuoi3QGFyrO","Sabino","SP"));
        lista.add(new Cidade("b163VVa0zDaT5pYr9Zi1","Sagres","SP"));
        lista.add(new Cidade("mcm99XQTRcv4WZdBH0dS","Sales","SP"));
        lista.add(new Cidade("MvspE0miI7vGybyiSXLn","Sales Oliveira","SP"));
        lista.add(new Cidade("wog7Hm8LaOFOnIDI3uyd","Salesópolis","SP"));
        lista.add(new Cidade("w61qQBXuGbFtF3HXTWIp","Salmourão","SP"));
        lista.add(new Cidade("qiX2bG4rChxVsumiCKLW","Saltinho","SP"));
        lista.add(new Cidade("jmJhVT3afZOOST9235HC","Salto","SP"));
        lista.add(new Cidade("Htgy4d6GJUQ8MbKfLAOC","Salto de Pirapora","SP"));
        lista.add(new Cidade("pdMMOJ2CV9torYb3Zel2","Salto Grande","SP"));
        lista.add(new Cidade("tchQnw4S7pqQHNLkAg8S","Sandovalina","SP"));
        lista.add(new Cidade("Egr30pGa6YsdQhMte7Ct","Santa Adélia","SP"));
        lista.add(new Cidade("Y43RiYoDS3lNsnyGO1Hj","Santa Albertina","SP"));
        lista.add(new Cidade("vZyRafnCDlXrwVTVOb9g","Santa Bárbara d'Oeste","SP"));
        lista.add(new Cidade("AoqiDckR5u3YGKgdpcvL","Santa Branca","SP"));
        lista.add(new Cidade("ZteXB6RKTyPwy9rv8GYP","Santa Clara d'Oeste","SP"));
        lista.add(new Cidade("pKHTwyUDg32DIxkppX4d","Santa Cruz da Conceição","SP"));
        lista.add(new Cidade("eBzxFHWRqQhL82Uwl3dz","Santa Cruz da Esperança","SP"));
        lista.add(new Cidade("7sMth6rxvkq5nIPynpPf","Santa Cruz das Palmeiras","SP"));
        lista.add(new Cidade("ZidmlUWot7SiqOwhltNI","Santa Cruz do Rio Pardo","SP"));
        lista.add(new Cidade("lJdGpDafaR0JQ0B640hv","Santa Ernestina","SP"));
        lista.add(new Cidade("IZZQTh0YJ21CJRb9wmlj","Santa Fé do Sul","SP"));
        lista.add(new Cidade("Sdy4aR4RZAzifEdXG96O","Santa Gertrudes","SP"));
        lista.add(new Cidade("770NpTYdfCmfvtoek2Aq","Santa Isabel","SP"));
        lista.add(new Cidade("g6Efsc1EfxWh6FdA5wAS","Santa Lúcia","SP"));
        lista.add(new Cidade("TTY5uqPF1WCMXGzuslus","Santa Maria da Serra","SP"));
        lista.add(new Cidade("ZcJFftBxQPWBCEa0J5YJ","Santa Mercedes","SP"));
        lista.add(new Cidade("0RFqjONqoAUXQGprzf4D","Santa Rita d'Oeste","SP"));
        lista.add(new Cidade("yhfk1IMssOsm5XZ1c2xT","Santa Rita do Passa Quatro","SP"));
        lista.add(new Cidade("rCJFoLqVJEUBTsPwGzXV","Santa Rosa de Viterbo","SP"));
        lista.add(new Cidade("lHmeLVDJ8OFG5C175Y3A","Santa Salete","SP"));
        lista.add(new Cidade("T2A8tfIPT2OkEh9zJmyS","Santana da Ponte Pensa","SP"));
        lista.add(new Cidade("FOPULY9NZhC8EYhYGmcc","Santana de Parnaíba","SP"));
        lista.add(new Cidade("08wuKjh7SuQRF0Zrpc5d","Santo Anastácio","SP"));
        lista.add(new Cidade("TahTyl6x0JYPB5NGZ1GY","Santo André","SP"));
        lista.add(new Cidade("jBg6INDBjdTKdgrE1bY6","Santo Antônio da Alegria","SP"));
        lista.add(new Cidade("FNaW9rs1WvZmQFtgrlNi","Santo Antônio de Posse","SP"));
        lista.add(new Cidade("0SSmv6KFWgnUGm2Te34K","Santo Antônio do Aracanguá","SP"));
        lista.add(new Cidade("K7C3UGyPY8r6TIdyX2Yl","Santo Antônio do Jardim","SP"));
        lista.add(new Cidade("uVSmBbdq1ztAaMy3uUL6","Santo Antônio do Pinhal","SP"));
        lista.add(new Cidade("t1CXcFbmls8OlTAlIMDZ","Santo Expedito","SP"));
        lista.add(new Cidade("Pqkklh7AbeuRGjWhgxKh","Santópolis do Aguapeí","SP"));
        lista.add(new Cidade("kXQuS4ZDYbqU7rR3jOZ2","Santos","SP"));
        lista.add(new Cidade("S9fRpyPC0rBJqLwX810y","São Bento do Sapucaí","SP"));
        lista.add(new Cidade("QJgX6qByTjSkp9FetgeA","São Bernardo do Campo","SP"));
        lista.add(new Cidade("BchBmYq6KSCbEhUekkKW","São Caetano do Sul","SP"));
        lista.add(new Cidade("hL0q9EQkyHhqCGwQP3ZL","São Carlos","SP"));
        lista.add(new Cidade("FClRlnVIiRYR9XcP34uA","São Francisco","SP"));
        lista.add(new Cidade("IIQFWZlfcvDbKyKtJVU1","São João da Boa Vista","SP"));
        lista.add(new Cidade("3eN2OxB2YhuvFQ6nrodt","São João das Duas Pontes","SP"));
        lista.add(new Cidade("HuIHdkqvvAxgMu6fIPnH","São João de Iracema","SP"));
        lista.add(new Cidade("ljF21d7nO47Nh25Zf8PS","São João do Pau d'Alho","SP"));
        lista.add(new Cidade("J8DBGzSxS1adl968DvrB","São Joaquim da Barra","SP"));
        lista.add(new Cidade("EjLkA8UUhd2KkMBJz9O2","São José da Bela Vista","SP"));
        lista.add(new Cidade("hKwrmF2xtNx2Sgn7hAUl","São José do Barreiro","SP"));
        lista.add(new Cidade("iASLb2X48pgNi9zNnoDZ","São José do Rio Pardo","SP"));
        lista.add(new Cidade("BM1MXe85Brn0rOFMAenv","São José do Rio Preto","SP"));
        lista.add(new Cidade("YAWZWwCVFfK3nMnY57SE","São José dos Campos","SP"));
        lista.add(new Cidade("ixb1aLQhtfype8zzj9Rj","São Lourenço da Serra","SP"));
        lista.add(new Cidade("HUCQhtk4Lff5zmCA4rMk","São Luís do Paraitinga","SP"));
        lista.add(new Cidade("jijgNQp1EyHd0ynBqxg8","São Manuel","SP"));
        lista.add(new Cidade("aRtk5PerQ7ncIfP2zdiT","São Miguel Arcanjo","SP"));
        lista.add(new Cidade("dCOpI8pCGlNIVWOCa9cJ","São Paulo","SP"));
        lista.add(new Cidade("PGWOxqR7bhiJUUUhqy98","São Pedro","SP"));
        lista.add(new Cidade("js3AZAWrio1DYyEpUIit","São Pedro do Turvo","SP"));
        lista.add(new Cidade("uQfpzaECRSVBHSVw60nw","São Roque","SP"));
        lista.add(new Cidade("uwjj5Da65JHgH3l2Axd7","São Sebastião","SP"));
        lista.add(new Cidade("al1O6FZ8f1RRN8WS7vq9","São Sebastião da Grama","SP"));
        lista.add(new Cidade("sssovHSDQbkuMq3FGc7G","São Simão","SP"));
        lista.add(new Cidade("qduRHGijdWhMIJ9XE20J","São Vicente","SP"));
        lista.add(new Cidade("v4OUo1wxjy6OTYcAld7o","Sarapuí","SP"));
        lista.add(new Cidade("u0SeUqHLJvhrrfKtEQ1r","Sarutaiá","SP"));
        lista.add(new Cidade("MiQwQd7ZRDoIPWVNgiUP","Sebastianópolis do Sul","SP"));
        lista.add(new Cidade("bFp0w2p0H6XWFDrBbTBV","Serra Azul","SP"));
        lista.add(new Cidade("2erlOGBloj9Gvi2Icg4f","Serra Negra","SP"));
        lista.add(new Cidade("kimDsWa3T8GHUdZV2JzL","Serrana","SP"));
        lista.add(new Cidade("0WIqI0I0a9GPJc7li9xp","Sertãozinho","SP"));
        lista.add(new Cidade("6gACiis34e9hqUJmTYym","Sete Barras","SP"));
        lista.add(new Cidade("4py87zRvVCofVWp3NWiZ","Severínia","SP"));
        lista.add(new Cidade("lvICPBdixVrhwYNkmKL8","Silveiras","SP"));
        lista.add(new Cidade("742QJxQvJkhYyZnDXJQE","Socorro","SP"));
        lista.add(new Cidade("wt7FOA2deLbhGIhICGck","Sorocaba","SP"));
        lista.add(new Cidade("UGBAEh8FMS8nrsB5uGGp","Sud Mennucci","SP"));
        lista.add(new Cidade("i0TYGlHWTttFzu7dbHwS","Sumaré","SP"));
        lista.add(new Cidade("UF1vRFhwj7rQ9sZI9Ko1","Suzanápolis","SP"));
        lista.add(new Cidade("4eQcSaGbA3uK5F7tarEh","Suzano","SP"));
        lista.add(new Cidade("3GJWvoHjjqf57engg5sm","Tabapuã","SP"));
        lista.add(new Cidade("suXKoQBDzeFxLbzH0wYs","Tabatinga","SP"));
        lista.add(new Cidade("lNaKyC9eME5h4br7p2gx","Taboão da Serra","SP"));
        lista.add(new Cidade("JNfxWJpfMpnPLrJyPfTG","Taciba","SP"));
        lista.add(new Cidade("7JjMVQVgETElxleYJkKK","Taguaí","SP"));
        lista.add(new Cidade("82eTD1LtV14zyQWY15Sk","Taiaçu","SP"));
        lista.add(new Cidade("rCtZoiLrEWEztr42dwM7","Taiúva","SP"));
        lista.add(new Cidade("ooH3fp3bZ7cJYypDNnJt","Tambaú","SP"));
        lista.add(new Cidade("AuhAXSJhXUhqzNOsV92t","Tanabi","SP"));
        lista.add(new Cidade("05CVUpkcbcKmDN9IEK6m","Tapiraí","SP"));
        lista.add(new Cidade("mVkjtXj9WnI3J03bHTBy","Tapiratiba","SP"));
        lista.add(new Cidade("evf58ZyDnisum6517m1Z","Taquaral","SP"));
        lista.add(new Cidade("QvzRJcZ47duM3ytYK694","Taquaritinga","SP"));
        lista.add(new Cidade("Ik6MfXcykktrL5nw9pnz","Taquarituba","SP"));
        lista.add(new Cidade("UWdOf3vIFxDP2hdDB2dp","Taquarivaí","SP"));
        lista.add(new Cidade("oAcgTo7X784g0KrSJKtv","Tarabai","SP"));
        lista.add(new Cidade("G0W5gC7iAUfL2D7zvN9C","Tarumã","SP"));
        lista.add(new Cidade("A8eEz1Ux0U3O2au1wRkI","Tatuí","SP"));
        lista.add(new Cidade("h2Gm7Fyn9QH2hnwmuzKh","Taubaté","SP"));
        lista.add(new Cidade("u6QzZVJfNwdckIrJ41wj","Tejupá","SP"));
        lista.add(new Cidade("BTFKRS1DjrqxAHsXJ9xj","Teodoro Sampaio","SP"));
        lista.add(new Cidade("M8pqWm2AcEO2NdUkHsXr","Terra Roxa","SP"));
        lista.add(new Cidade("6kxQxfZCGtfVokjIKhRx","Tietê","SP"));
        lista.add(new Cidade("LWCJLwEq3CblRq4QeMrD","Timburi","SP"));
        lista.add(new Cidade("8fN5e2QlJDhsspaP867Y","Torre de Pedra","SP"));
        lista.add(new Cidade("kRaVkzDgU0fNMkGX5rEv","Torrinha","SP"));
        lista.add(new Cidade("Lo83uIVQWoAm9Eg0UcH1","Trabiju","SP"));
        lista.add(new Cidade("jKSRCpa3l92U5FYcIMln","Tremembé","SP"));
        lista.add(new Cidade("nHPFFQCfDKXPyLR8oMNY","Três Fronteiras","SP"));
        lista.add(new Cidade("XoHj5lbHnTuORj6O341f","Tuiuti","SP"));
        lista.add(new Cidade("5B3QcKSFMnqrIiDI2eYE","Tupã","SP"));
        lista.add(new Cidade("3CmiQeDR3qMLALcmMFuL","Tupi Paulista","SP"));
        lista.add(new Cidade("nca6N17kD2BpTQl5NJjR","Turiúba","SP"));
        lista.add(new Cidade("6E1tgYV778uPNuoIt3sC","Turmalina","SP"));
        lista.add(new Cidade("sGcQaVp2K65jv6hGD5L6","Ubarana","SP"));
        lista.add(new Cidade("wnyC5rXoow4hoTq93L2c","Ubatuba","SP"));
        lista.add(new Cidade("PjfFJrz6WNYsDSrW6tgm","Ubirajara","SP"));
        lista.add(new Cidade("r0ys6THerB8w0hJAP0L4","Uchoa","SP"));
        lista.add(new Cidade("TCOdv1YAXMyzDBl662Lx","União Paulista","SP"));
        lista.add(new Cidade("BYXZxTZSNSeBeKVG7jrw","Urânia","SP"));
        lista.add(new Cidade("dIGF3yV2ygVFNy7ICfZt","Uru","SP"));
        lista.add(new Cidade("aN5ay6YmnsBHQZ18iHjf","Urupês","SP"));
        lista.add(new Cidade("9SnYcdiYQRBiD9872ImV","Valentim Gentil","SP"));
        lista.add(new Cidade("Tr7fz4Lu1vSoERhl1wTI","Valinhos","SP"));
        lista.add(new Cidade("JSk1xa4TQa2kO5IxEBy6","Valparaíso","SP"));
        lista.add(new Cidade("sD4wHNMEt4WfNJdjLssL","Vargem","SP"));
        lista.add(new Cidade("pxqZkMgfpYaIKzMcJaCm","Vargem Grande do Sul","SP"));
        lista.add(new Cidade("bEvyxPk2kpEqBIL2sJLh","Vargem Grande Paulista","SP"));
        lista.add(new Cidade("EufLifZBma5F14fUY9Bi","Várzea Paulista","SP"));
        lista.add(new Cidade("k031GrkZ5pnAUOBrHsn4","Vera Cruz","SP"));
        lista.add(new Cidade("3Yhd4szXwAovGvIbf2pV","Vinhedo","SP"));
        lista.add(new Cidade("5sh8Dq0J09vTIdJcxftM","Viradouro","SP"));
        lista.add(new Cidade("Q80jzJ60GGO6DQtlPIDH","Vista Alegre do Alto","SP"));
        lista.add(new Cidade("h6KL87Edd8qREx77cH9Y","Vitória Brasil","SP"));
        lista.add(new Cidade("ml5bDMBcM0wEfg86oX3Z","Votorantim","SP"));
        lista.add(new Cidade("pqjX6hLfStaZsgOaipKm","Votuporanga","SP"));
        lista.add(new Cidade("WJ9WBomX8P8aUlr4OaL8","Zacarias","SP"));
        return lista;
    }
}
