package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class SP {
    public static ArrayList<Cidade> getCidades() {
        ArrayList<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("HYsbUTJmqj356KQTDWy4","Adamantina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("P2vEtoRFe4rhC2JbO9bi","Adolfo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XiSzlZVUNhHUINmp5Aly","Aguaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XNXHcZA7aiQzRDQkXmvv","Águas da Prata","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("1O4eiFAhGrFZmYVfLDEU","Águas de Lindóia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Z2Jo8N02DjAPSwFRsGu5","Águas de Santa Bárbara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("vpZm8vJpcELj1zvUy3sx","Águas de São Pedro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("c0oooLWihkH9UUz9hT60","Agudos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9CPadl6dxHshyfLycpJJ","Alambari","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K2hwazj56NfUOVF6kOwj","Alfredo Marcondes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yThCk47cNfFphJvN2fiK","Altair","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YTOW9JfxUvexRwVV9lsi","Altinópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sRSCfKA9Kip7peiVKPFQ","Alto Alegre","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("RFRx0N5pYZ02u8SLr5EV","Alumínio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yPQc2weu7lfti8q82YpS","Álvares Florence","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("GudBT0KcjAo05eJ3kteU","Álvares Machado","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("1JMDxGMiOrvLBJtbUtuA","Álvaro de Carvalho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ycvL4d8DQOHQanoEPHRW","Alvinlândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("2LsW8l2P1gSvw6JvDDBS","Americana","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Dsml4AXUtndUvWq8jgVA","Américo Brasiliense","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("u4cxwQrPrFPNi87dPLCB","Américo de Campos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HqXVLSNP4f2x3VTC84SM","Amparo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8h2vC0hdRwXvOXOeKgJE","Analândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ykV6rFyQQPUdDffkLIFR","Andradina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Xak0PohKzjcV2S7rcjet","Angatuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ziesY4GQUBeEzjQS9Ebi","Anhembi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K9XMIC5VwTdzl5rq6UF1","Anhumas","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wwGPHxrZXa4XYAjxRyg1","Aparecida","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9MmcXv6foZPFDEE93d39","Aparecida d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ssxkarsI0s2aXGEd1LfA","Apiaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("GMSmEXFKdJ5JL5pczEuL","Araçariguama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sBltpl90hXuzGkyiPPH3","Araçatuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("a6B7e1q0ILzUmCxOQEp2","Araçoiaba da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MNjlhDlpYdbtkL5QQMxf","Aramina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Zf9FHVhBmux7aWlBPxPx","Arandu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("vJ4VHfEwwQjydZHzNLlt","Arapeí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kP5rqhcy8abH6obs1X0K","Araraquara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("oH8bAXBI76K9rRhjY8Ur","Araras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("khKmgnkD8Y5IbnnXo75F","Arco-Íris","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WzQ8dVBZzeUTTP6Y1sbJ","Arealva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("1koDjTpKtGgEHpQijHFH","Areias","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kVN7DWt8wQvTEtIS8uaN","Areiópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AWqhH6neQeW3F8Cg0s7y","Ariranha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CDJ6xh89PZzWdQPbe4BJ","Artur Nogueira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iSckvS0Fh4YZ4yijY2Pj","Arujá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("L6FkbuoOV87OdBBvDLnn","Aspásia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Wbl9hgBlHGI9KXcEL8CF","Assis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("NB6VT0UuOPGjxJ5tPBmd","Atibaia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Q7SX4bnJ4pUXPNDSyt2l","Auriflama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("D14Zh6nF9FWYXESdlib3","Avaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7IeQ6n8KbFfsHkbCdCjN","Avanhandava","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Sxs4tt8wKdiUgF7ukYUW","Avaré","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gLmpJsVazQXhlWAeOMC7","Bady Bassitt","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("KR9XokKveg0RZQul3QZs","Balbinos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("eJlxHYNaQmcaXKhljCTx","Bálsamo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("thgCyZUrGELwO30x9q0h","Bananal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ANC7xV3ajhDYqkpqsH0j","Barão de Antonina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DbRJf8xh7EJD2F7gEAqQ","Barbosa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("87pYMOCoxsGK6s3lm7Dx","Bariri","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("eJVjNbLO9WWMlZGtbFzg","Barra Bonita","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UK4FOlU652wbP4TARMON","Barra do Chapéu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("nZxZyoOfayfKe97YhLvP","Barra do Turvo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Knk72RRzWVnEMa0QXsRF","Barretos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IHBLWn5Yb0z6z93mpruB","Barrinha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Sdi7QgwFaZbfkHXhH0AZ","Barueri","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("S6sh8xdO3WvVGwgLiPSt","Bastos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3UjgLfqt9QlPcVtsdv1Q","Batatais","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("igSoy2xkcUuqVW8QAT5B","Bauru","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("leEsmXnHMFUidwqLrvfa","Bebedouro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zRr9ICdq0hmWr8V2sMXD","Bento de Abreu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mIZdvHm9jTxHgG4w0Fk4","Bernardino de Campos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hCiCfiEX9VjYHxgj42AZ","Bertioga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("eR9LfIleRKqKadoYjzqV","Bilac","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Qdd6pyRzPvVkd95SXw74","Birigui","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hdihOsRF6GOeuldYkp8Y","Biritiba-Mirim","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iq0Iy3HmZZNt0q2lj6ES","Boa Esperança do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("EVv28ZZlbveidYcmHaF5","Bocaina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iFo4OzEfaVT47QBr8DCO","Bofete","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4KyxSOSoKleXRkgsMS6B","Boituva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3ooE7BLtF9tBzInpzvAP","Bom Jesus dos Perdões","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("deryrVkUEJCd2KQJCp4E","Bom Sucesso de Itararé","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kc4XisnsBByLeHvqrRvX","Borá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("aEZDnfg2bH6KCv6ZHF0i","Boracéia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CKBX1pKy7BVAD8PNW6J4","Borborema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6VnVoX7gltsthhse1WwW","Borebi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UtJiSFFwKpzumn8qQ1gO","Botucatu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("1Ye0ZImdSshB3RsMj7dc","Bragança Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("NOFxwEiHJV8p9GqKPaEC","Braúna","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("SInPWYy8ddxq4R87FicX","Brejo Alegre","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rLGSIsiLuoevyVKhcvar","Brodowski","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MKEuYK0NOfhlyDlQXtTC","Brotas","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8eqR37SBNI7fJg22KD2B","Buri","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BZy9GEDEqdL00PjrXkEF","Buritama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("btxJKXvDxF5mJCeYHZct","Buritizal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Cmmf9NPDHdaBZPV1wbPh","Cabrália Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7ZqqMIpl6DTWmDH6Kt4j","Cabreúva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xwOEAZ8CYtpNj1viYfFo","Caçapava","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5AbQE9MrIcMgnyNXwB8Z","Cachoeira Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CqRmEfhdh1NBNuNTG07Y","Caconde","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("tA0b2aFEVkITWehw7TNW","Cafelândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zapezqa12s3VmTPL4Pon","Caiabu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FbHGJXiuXBr2pWuN3V2T","Caieiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qBM2SAeSG0pN9aF06QaH","Caiuá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("KhUkldYeSiOhz0cHocdH","Cajamar","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dKKPYJZAZNJpjq4x7eZN","Cajati","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("X9viXIrKvHTaKYZB4nIr","Cajobi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fSOurHOUx7wphAjwOx15","Cajuru","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bYviSVLjTpTt1H3YxYDE","Campina do Monte Alegre","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kAZxNqTkUbjexrJNFkwf","Campinas","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TpI6ZG49wFdIIwMjKUkc","Campo Limpo Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("oTgpmRMqSXSG744Ji7KI","Campos do Jordão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9a2RHgJEHIATw16ix5R4","Campos Novos Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("f3uaQf0fiTtqDVVuHi8m","Cananéia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iGgqLBzBnx0oQSWwkwux","Canas","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ectJA0SACy6qIRr46rNU","Cândido Mota","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("B0415gs6vTbbR2qUiO3h","Cândido Rodrigues","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MHms4YZKQ5HooW42DmGz","Canitar","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MTG6adzCbhjAtVqxXmDZ","Capão Bonito","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("cjnhAjw6wXpNLtVUnOeZ","Capela do Alto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Eah0eCAPVlamohrkeo7k","Capivari","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xhziXvVGbitKR294n9A6","Caraguatatuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jDQS9L47NIILJccuxCZA","Carapicuíba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kHTHXJmwadU4NPIoj7K5","Cardoso","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9EeknTXjpIzJIgSUFItD","Casa Branca","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sGlPFCNQ6zNY985sKieb","Cássia dos Coqueiros","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gzGezRU7GdqN5gzbvIPs","Castilho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("OTDmg2sXiFbO7zjGvmy0","Catanduva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XF6nOuoEUnjdswZjrLI6","Catiguá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YzpQF2JIhsI7x3U6mWL4","Cedral","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("GzUVaUpszYlTarCVHuqj","Cerqueira César","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("tlQhIfH5TN0hEQc81VZc","Cerquilho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("H0izqJQDORVOp0bD5PGN","Cesário Lange","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dFw1MOImoYEy2RJQbDOC","Charqueada","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9ZtSjXvitWr9lwLvUWDM","Chavantes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wiG1CZhxBQklWgseLYSf","Clementina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gByabbZPSj2COrlhST7S","Colina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zaKCeXaBqhBoDA4mTyj2","Colômbia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TZu4gvKAXtWb4ZcwaeqK","Conchal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("48KB0U2EvISwne7froUi","Conchas","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AWD3eMP3OKij5kbgtv3K","Cordeirópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("F2DqpUZY1FOyIBixvKEa","Coroados","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zAqJLYlfT8OH9ENwMbpc","Coronel Macedo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mb4ttiyCM3u9FAQ8w7Iv","Corumbataí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xcFL5a5XDzoupIj72Ght","Cosmópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pfHvyAIbM38oz7NRuG6u","Cosmorama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6flliKthSpczIVfJFHZY","Cotia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YlbfpnwxOZqZyZ7kcKhf","Cravinhos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("aKilZLSxFAV2S0ZYL3x2","Cristais Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("d03qI8uaIxRjv2bVQCv7","Cruzália","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uUYkexdA4w9wYXO19Pc0","Cruzeiro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HXtntT4FpOpbkZ59olUz","Cubatão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("1KCwW2NY86aYq0ii9lKg","Cunha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TBvRbj5Mq3KrAoeZZwl3","Descalvado","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qaKDRUKsC5Wlc0xDgtSW","Diadema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HgnQxv3o2HuIeS2HzqHm","Dirce Reis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("d0Up2o5vEAXA53PQlRZC","Divinolândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("tbmkaquhU1rkVopYDXrU","Dobrada","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rWn3eVqb02JYFXmWpkp1","Dois Córregos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("a3HaUc2zv9r1DLJgWktR","Dolcinópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kvihiMGmA54ONIx89Srd","Dourado","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("t3UUMFzkx9baIXp0pc0D","Dracena","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zC0V7Dh9nBxjpFoEdgby","Duartina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Rgj0EkaULLC8ZfvZJ5aZ","Dumont","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jYfUPYHvBovj3LVE3zy5","Echaporã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uES3SYyupa2f0lxJ3uiM","Eldorado","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kAIcb5rftOMQw3RFMY44","Elias Fausto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xEVJKVqMHD1hQgIJhlVX","Elisiário","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PaRjUTA8Jm76nfCpsCXt","Embaúba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("piBPaNBHi5whgwVHHtNo","Embu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3k4fdajewuHjc30ocMAQ","Embu-Guaçu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XZTuimGk7aSrjZCAY4Sw","Emilianópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("SWC3S9IKzfSxG6JSW12L","Engenheiro Coelho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("B35qvMNg2z8OuBAlFXUH","Espírito Santo do Pinhal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8PCSaqIg2Zk7Nduv6HY7","Espírito Santo do Turvo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dtrqOcBZ97kJfbH8PrAE","Estiva Gerbi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YKgHeLex3KArxUZpFFsQ","Estrela d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("c92YFLtApUL4stQJCmDs","Estrela do Norte","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("x4mxgvqZLE5bhVwAtlvX","Euclides da Cunha Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("P2k8Mtj9obbjVuibU31S","Fartura","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("LekXe6kv2IEi7Ll692KS","Fernando Prestes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5gLcXOk2QQ1ks6yqhHZz","Fernandópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rdoi6jOIdrdpjAtYq7s8","Fernão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CD3RjtOHCOCad8WKNeQ6","Ferraz de Vasconcelos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HpNdg4uBDYTGW0JnbPd1","Flora Rica","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("tlKAvp4TXrtO2aPdThqT","Floreal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zXtQpDUAUyzjIMfQ3tLq","Florínia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("vRlErRElQix6deqBmpHe","Flórida Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DPDpimxWah6iBuKEHmb7","Franca","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("l4Ul2MHn9KWrPG2s7u6R","Francisco Morato","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lM1mAaJKG14YuSwWUmvq","Franco da Rocha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("d5feAWwuLgRb4qkW6uiq","Gabriel Monteiro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("NAQDVh6wiaFHwGkmrUCo","Gália","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fjjNoh3NPr1whB9jqijz","Garça","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PL71mZNjYM93YBXjvAGT","Gastão Vidigal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TfNjSywYj94ylm6pK5jO","Gavião Peixoto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Y1c4S6DIIs5B9G6hJusV","General Salgado","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("r1AHun7mIbNnvFdwGRRR","Getulina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("z9uFNID7OCt3mkt0jU04","Glicério","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZDlrpZ4HUI90gnzgMe6w","Guaiçara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("miyJA4nR0WMFeJ9Ijy6j","Guaimbê","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7ky3gKYNrrRq3iOrmibY","Guaíra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wg86Zmj1ps17VDWwnwuJ","Guapiaçu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9d8WyyyhfgfDiyhaKwJG","Guapiara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sX9BN3bzHrlR7URHWoAM","Guará","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DL6IkhhgA8M5Yo4XS5g2","Guaraçaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rGFUjdLrva3gFGcjv5DG","Guaraci","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PYMKHU0wu07Ligt92VvW","Guarani d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qxib1dDUAyjfXajDLjZ6","Guarantã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HkWNkAAFOCrK4mrHKYeE","Guararapes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("a0SZa3sGJKF6f3EvXZSH","Guararema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("1yJrmj9mYxb8UnbTWVwt","Guaratinguetá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PxhZskfHgwss7nfpjMpv","Guareí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gJgI5piPT9gQeFs0F5hU","Guariba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zm53zIVUtBtID25FGDBA","Guarujá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("cg4htjR1I6DiqPmn3Sud","Guarulhos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pyenNbMBl0k9n2hx5xRA","Guatapará","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rwVwYaCfdTaVwDnZwNKB","Guzolândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hX3NApSSu68uI2hchcDr","Herculândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Z1WQtlysJBQL1SY7PpZX","Holambra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Bu0iESLLeLPCt5E5RScj","Hortolândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("LcQa2b3uUD4G7J3L34wv","Iacanga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("357eATqkDJUQU50YDTkx","Iacri","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0elCVsLsDhQUVmsXornu","Iaras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("cDSsdQAFMnzBT4KJ8SR4","Ibaté","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CMjYr0FQBUoLIezj4ZKh","Ibirá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8XePXh6gdSaiELQRLHzr","Ibirarema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZRGyIfkGIPFMcxiJcXzQ","Ibitinga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fAY4uKFfo0Qi6QANjj28","Ibiúna","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("B9fQfO4OSn6Ro00CFRke","Icém","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("vlL2YLxSTMI4cRo3shIy","Iepê","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("tKNEZf8rdLyGdl7ulHuB","Igaraçu do Tietê","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("32WBU9ZZdcJ2aq0ot23b","Igarapava","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hH1rDf4jCDqwmAe6Z9OA","Igaratá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jwd49isLGG4zY1pzCNKO","Iguape","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("F9AjzOn8TGC6xC3b22lL","Ilha Comprida","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5RWr8npqD0yySFkyNxi2","Ilha Solteira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Dhl8Ea89nGd0SdMYsJdA","Ilhabela","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AUUMSqEHtAohPO7IvKxl","Indaiatuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MnUWTHOQcglqGvaA00Eg","Indiana","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("49bYrpRHepoVSLWexvGC","Indiaporã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lFVAw16mghq1Wda0Rt6x","Inúbia Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0mA25HqdTgFRcUchOWqt","Ipauçu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TMEgc2iLt67P03S3DbL7","Iperó","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xbcE6l1qVu0dRdYQ3Z3s","Ipeúna","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hsVDZBGjO39vb4goHHpl","Ipiguá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FgUWvmXXIZAPjLVKOkFt","Iporanga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ooKxHue80f2PtFGBpfnK","Ipuã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("A6s94vWD7fQa05EySbIr","Iracemápolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bxQhdKKWggqspOMioYW8","Irapuã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("n1PvImpgBIr4y5JbfhUs","Irapuru","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bTbjguqdnutLbqhaYjuO","Itaberá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8mOC3lkl2s6UEJgMW5l3","Itaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IqIA0hFdwtFuJL7z6y2n","Itajobi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qwm796BS8dEtjDxd3snp","Itaju","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uOYckVsceny9z3P0fgDb","Itanhaém","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Vf98Ti7e5fYM7PO6Yl8d","Itaóca","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("RuZdqecc6EAKpKcZS4mH","Itapecerica da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Z1ruryvE6AxNnDMdiojA","Itapetininga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9mMIHGstrUuUbNvYsPiw","Itapeva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("um90wLusrXZjkaaa4Tlt","Itapevi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("vAUVG5gQEvDCo8mtsFCh","Itapira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5O86V4CfnETCMES9bcdX","Itapirapuã Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("JlGsjao2GhZOXfFEAMoF","Itápolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fAwFHd6nkZxYvRScZRrS","Itaporanga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("glhYl7ncYElOJPYZbggr","Itapuí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UWYGWXQqtGPb69iYT8t7","Itapura","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("2Av8TEPLuBMCra9ITm3a","Itaquaquecetuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iho8SqHSilyY8CgGuPtO","Itararé","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iWFMNpZXeQQOql8SgJgd","Itariri","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ipg3YE2zbB2MaKytLRAc","Itatiba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("j1kLsMRMqw0l0qNviGeb","Itatinga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0jnECtHHUczMDaQr5Izr","Itirapina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("RPDqgXmXScKdXnQKJH45","Itirapuã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4GZ0owWfKy36JtPUTaKU","Itobi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BdWjDOhQ7DTTyjGZihao","Itu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("orTA8Ur90JGoTxvcYU57","Itupeva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sckERq16JD3Ws8z3sSOd","Ituverava","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9XfamIDUTP1tS4S4uC3k","Jaborandi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("VHq6e1ygtDXgF9Rey79E","Jaboticabal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XYt6ybBH4qowmpN1fANF","Jacareí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mxhgZEjLXhRSKEGN2cFx","Jaci","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YAbKiD7dDywxtQTPqcdk","Jacupiranga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ueBIvjnZXNjIU8pxKkTS","Jaguariúna","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uYGkiO49b7MobKxwcSNf","Jales","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("433dnhzxmVsi41k7xTIg","Jambeiro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jAduukhmtItCKqMQQbjd","Jandira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ooensBrsERFaDyUZ5wyY","Jardinópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("JxL9fOW64QBBuRpdhoWQ","Jarinu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gGMVbMD2eA2AtwbjaMLr","Jaú","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8wBMoxlIA5zHB4woo4uf","Jeriquara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("APgyTxAw5NpB7coJtknM","Joanópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("KUOWVCPrpW5nXuMRLI5z","João Ramalho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Gz8P1ke97hhROQ6goAu9","José Bonifácio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bBzYHjKlpdhcVwL1TQZV","Júlio Mesquita","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MD1e1cmCMeUzeWf1cUB3","Jumirim","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Xa92Cnjwa6CAebO1lg7P","Jundiaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("eRiPJN6TaAFdBtJrqYOh","Junqueirópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("oRkHtYeBBPA6KGyWKut4","Juquiá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("h5GR2L5khbuKP8g58NpY","Juquitiba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Ezlk1lCX9Ey7qoI0KHGt","Lagoinha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("z3PLoUnzhJJF9N1EeE4K","Laranjal Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mIDUjLYOyjsRQpxWht10","Lavínia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("X3P2n0DvcXjvyWQBOIYa","Lavrinhas","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DLjSKf7R3hbpVCIPCAtv","Leme","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("unFyNrx3V8Q3qlnzGbj2","Lençóis Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("nY4DIITezdq0ONGnkcGl","Limeira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("QiBRAzllCIC5NearaoYa","Lindóia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bcr3bFN45HxuSgLsWz6r","Lins","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sAiM8nFhI8J1dO8CZ7u1","Lorena","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8gRPV4W6aOj02z3vM4GY","Lourdes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("48IK21FLsmVLcmMzvzT7","Louveira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("NRwpyaQ4JVlTbtyj3m9S","Lucélia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9zjnfomtGTg5kuupSkpB","Lucianópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xT0FWsiHMhU8TyePEQam","Luís Antônio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WHrIrXgPKVGjWhBQnPvm","Luiziânia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4v0DQ9e6hbFtd1xcwIOI","Lupércio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bTnkjJ15tYrzQtLFxS0J","Lutécia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("KsmEc5e1ApJAnRGR6XjM","Macatuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("NIOWmbhRqCgu1bHAnusa","Macaubal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lI2s0KseqAgGR7sxGiDA","Macedônia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CO4yh2NvWAXGCCGcR6SG","Magda","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YtU8VrNsJO3xFMc1Oejk","Mairinque","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4MKhkJ3rKBU5pNwF8rau","Mairiporã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("VTzNI2jzfKvbMxfQp4L1","Manduri","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Nw4HYyJItkgjj28v4XVo","Marabá Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("doYfMNw3CYK1gRS47gEb","Maracaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IC1EyMpAFbYglt1gdEc8","Marapoama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("OLumJISeLANi6L5YOKik","Mariápolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3ophlxDfPQnjM2cJ0yXr","Marília","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9NOYLIaxmAGTP9UXaGsW","Marinópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("omfxJwPkjDtpMBhjw9GE","Martinópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("co6s37lIQUwKrIHsgHJ9","Matão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dVsOhWqVvK2UGLr1zIlU","Mauá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lCgGElLZCB9BC6nSEe8H","Mendonça","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DGON8ABMDIUDZHeJ0QDk","Meridiano","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("N15bQyo9CbKB9QE7YKhm","Mesópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fIo5KkYYCo85wtCQrDAz","Miguelópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kROWdcHabTgJL9CyRwg6","Mineiros do Tietê","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("LQIOQCD9nSrud5RKRkZS","Mira Estrela","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("75KahTuAGbb2YtZZFThU","Miracatu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FdFzM0XX0riBN5kYO0sE","Mirandópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iCCanlnBYClJ92CGVglY","Mirante do Paranapanema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yd9Bozt62ZeUKn6Rzydw","Mirassol","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("VAH5NNSKf5UHrzA1VQlr","Mirassolândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ROd9zjNJmjMpbNP5hD8p","Mococa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5TBW5KvCtrhyvtq37PMh","Mogi das Cruzes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("KFx2QooqzjfwSS5yuuPi","Mogi-Guaçu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6CG6szC5T1QlvkCd8kwy","Mogi-Mirim","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8NrJxUEOWh8kVCmEb1Z5","Mombuca","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("RdJSOQxzcfLuA0SekQ6V","Monções","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DRo2ltSrWnkZtgGsdjas","Mongaguá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K1nh5QaDgYyEsD2wPsjy","Monte Alegre do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HVgxlJYiXOcfpVTO7PvD","Monte Alto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DjfDFJYVcSYCWhfPktwy","Monte Aprazível","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("JwOfzy2BM0qDtC29cLuf","Monte Azul Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ir5CQANV8MunC1vmk6fd","Monte Castelo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("72jukrsyOqLLs7bhzz7B","Monte Mor","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("e0qgVzzhvkGScf1dU3jF","Monteiro Lobato","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("45FXFFX7880hEgoWwNEj","Morro Agudo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("2l6H3TwoQFkIoN4Zimhl","Morungaba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("GXEt6lfMQsUcch87SN8B","Motuca","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CJkClhE9okkT1jFLbHDj","Murutinga do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("LuD0R6aojHsyXzJz3R2V","Nantes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FG16Do3vRC4gpj6T0Pxw","Narandiba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("QJ4yIYoa4rObq4CC7yWC","Natividade da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PWZokHnnITmClyOQ1rwp","Nazaré Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ddKHo5acrPWCxRFOrPmN","Neves Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XwRiTrckZih9stfJUmMN","Nhandeara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7xV80nHsa2QsK3l0gAAR","Nipoã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AN8fHMHqXPyOBmaWRBtP","Nova Aliança","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XS8QeGtDkrFLgVWcsGY4","Nova Campina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("aN5Ovx7xANCjOngaWYfT","Nova Canaã Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("CqiMMFFTfAP28CIuOAtX","Nova Castilho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kiR95RZ3FAWpOEpTZjED","Nova Europa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("oWYC7ePHIDYyQTUZ5dsD","Nova Granada","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("RCj9g8kGFum9P4R5qgbi","Nova Guataporanga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6kGIrGY6iIiNdz8uoYfg","Nova Independência","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IJPKvD170FHWvYj7UacO","Nova Luzitânia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4eJfdhUU6E0FGee3GHg7","Nova Odessa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("n2PC6E3f3GfatE1xV8ui","Novais","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yFwfs7AH6HuEmJsrccsK","Novo Horizonte","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("F4n8DoSBMlDtwK9izXp3","Nuporanga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Z0hGcINX7L6oIE8zEamh","Ocauçu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TXRcDl3elLedcXCoymxV","Óleo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("o5K1e5XsUBOOaansdGxv","Olímpia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K3KuxtxX3YVzx2LbtgFs","Onda Verde","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K7DAQDGGABhGG2HOgREJ","Oriente","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ObZUGPluDZL8A5jqErYf","Orindiúva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wxe3KXGYN36UARLasWYo","Orlândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZMqhOUi1dUOGnngNDuek","Osasco","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0FXzpEuSBMZ5PeygLvUR","Oscar Bressane","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("apZmyRh6tDC9ABEfSnXl","Osvaldo Cruz","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("GiJGcesZCxrZe676xLJW","Ourinhos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4DXuRHdSyYVQGWMJZDdZ","Ouro Verde","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TrcH3d992ukO7Nxqe3Qc","Ouroeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WWfTL4H1DPTMZRxzio6B","Pacaembu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("377E8JAIRNNxZuj2NCza","Palestina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3kb3E3CpE1UF6Cn7LgJ3","Palmares Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("k4g4ruFQRRjPJp40hfOK","Palmeira d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Q4u9ybMs1vhstoSXjJK4","Palmital","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7JXwIT4ImzT8tAnY9KUL","Panorama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IsBCzN0Bmx3kHGDhPgo3","Paraguaçu Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yj46V0OY78JZb10mDIyQ","Paraibuna","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pDToxunUeeD061pWfrNO","Paraíso","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("EQzvGh8BhnZNlCZZb5aR","Paranapanema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qtRX6notypff6yZdevdE","Paranapuã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pCS6C8lKPjmg5DPJaKxR","Parapuã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lgAmMyvz25sXRRc35R0E","Pardinho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3BLhE40xD1aSL6Hc8YQi","Pariquera-Açu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("SS9hNGB6NqpPUvk2FZ1y","Parisi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zxUOkwXkm3MbTQCimJ3v","Patrocínio Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PA2cEfvz2hGjVxUjPjKh","Paulicéia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("C2vsDbf92DUISXuvVC6k","Paulínia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kf2tfEoT3KAme3QVsT5S","Paulistânia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BGbHyoMR8Sg3j5yhvq6W","Paulo de Faria","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("xlN04zjOaCPu72cYuZko","Pederneiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3B3nsPEmlKwmC4LWjUyM","Pedra Bela","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FuAjF3DhpX9Hkxhyn7lr","Pedranópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("KSE10j2FjYX5204Hr0bO","Pedregulho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("G9mXFwzLDIT2z8vReSMo","Pedreira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UMM0vtKdAwYrO7lZue9o","Pedrinhas Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DpvcY7ny09JwCWWnnyfr","Pedro de Toledo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bPQ3RUdi7nPEr7I1VMPV","Penápolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kBNtPFuBX3ZdNCuuCCrn","Pereira Barreto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("M0l5IIfy8p1cQKleMzM6","Pereiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("cmRzzJij9zdBVWAhf6hZ","Peruíbe","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9yDMwVLpXA2KzYA7jEGY","Piacatu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wgm7FqWsL5a5rojPpBBc","Piedade","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("470LGeM4eaDEPyvqvVha","Pilar do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rRJSYfZOFEAIDNAh2g2A","Pindamonhangaba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MTfxoQt7Ycir9UOE4H8b","Pindorama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hjThi4JmkIBlzGoUeIQT","Pinhalzinho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uTjZmXcc9pNk47GXHWbm","Piquerobi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jDQWN2lYx8es8DCkEMki","Piquete","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hKaDwMoNpKIFUKp0Hxsx","Piracaia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mbP2OE6e5Cc6ngZM0SGe","Piracicaba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("A6brNdksbLd9KiGGmsr9","Piraju","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZAbJpHqFWolB0B8kjfjO","Pirajuí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0qZSWY5uWmr7sSWk5T3Q","Pirangi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("A42vfx2wlzhPJzzQjRSP","Pirapora do Bom Jesus","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("USNEfvYjb7TB5xH95e9V","Pirapozinho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ULmmPSg5DNckednUS5ze","Pirassununga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZGhuiGqgXJnoLdkOjxPT","Piratininga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zxYbBn7CU0cW08RhJB8s","Pitangueiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("d9AHQe8FNGTlgf9ATOrq","Planalto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0EILekYMNPuIlowTyZhT","Platina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AzxmaueEYQaNDf37P83X","Poá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BsJUT84g6IeBW42GKbL9","Poloni","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fb7Jkx6hDGR4iL4Hf0rh","Pompéia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("paXc1K2KWMO7BgnFh6k9","Pongaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uP4oV9J1qSV6WvLfSlbd","Pontal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("byyIYmu5Bm5myFkN3Qqp","Pontalinda","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WwasTAhtXdR399P6nez7","Pontes Gestal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TTU26PDSqsi5L14Yv275","Populina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("NTOde0ra0mBFha44irMC","Porangaba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BYVYRyXIGHK492pPdYqk","Porto Feliz","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7niM0fnmCVjtZtxaWza2","Porto Ferreira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gsl60qWPI59AtO87SbSn","Potim","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6o4wvfoYHAZIvZxdrp3L","Potirendaba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("SJ3PSiz38rk2ChG4GXbx","Pracinha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Q0fwdmKcWZFj1jXgQ83v","Pradópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IteyPOzbECVQ3HyzXiT9","Praia Grande","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("slKPzenW1pvHYPIWVF5X","Pratânia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("EKfQedOsZkSR36N1Z64Z","Presidente Alves","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("nMSZ9m2nozP2H3NuTm29","Presidente Bernardes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("aB6cpM4BxuRGAyIL9JiO","Presidente Epitácio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("coV4S86fS4eZ19OZ8vz7","Presidente Prudente","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WO4mUWRcjunSfclX4mZc","Presidente Venceslau","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("edgLN0yQekGtK9U26Uhx","Promissão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lM9IDOQJcDmg9TABCjiO","Quadra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WXVtAgCc8pMa21e0Bhwn","Quatá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5owtJIMCZ1Y8EKFHzzQu","Queiroz","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("g7jUxAnJFDNeRtUmsoBk","Queluz","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K2sZSKlLj3z3I4ifkkzZ","Quintana","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PMroEFs7yDO6DHgwAIJt","Rafard","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("d2gYZtUjUvpBo3XaODR3","Rancharia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MhNyyrQao8boqqV05d7K","Redenção da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Mi2rHc9OAZEIUXA3mjo0","Regente Feijó","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XivKf470YQHuVhCCadF7","Reginópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MyivO1dB7u2LjPTY1H52","Registro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AsoUkmfgy4GbbubSwv0m","Restinga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dz0OGW6xVuKMBEekPuwd","Ribeira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("zPeRurG1swecp3N3STUZ","Ribeirão Bonito","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("gFoHukIp5sxEhmdlIMi3","Ribeirão Branco","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ge57Sj2yV0ql6EYqgaly","Ribeirão Corrente","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("c5Q6RVUrcGrFlHLriXNC","Ribeirão do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("X2cSOGfa9T9JqZdoXKPL","Ribeirão dos Índios","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jXIqV5VaNnxdNZ8evql7","Ribeirão Grande","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yKcvxiRju3KBVgdByqfY","Ribeirão Pires","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PMqFv95r33L2Xp4w7Ltk","Ribeirão Preto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TA0RVexZLIuIv6PsvXvb","Rifaina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("f5pj381atZeobZ3x8rRb","Rincão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("RMkcEG13iyCstk8QqIOr","Rinópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9rUmzJLLkMQb2wt5URtc","Rio Claro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HOaZnXD2lzVfW7GX3iNL","Rio das Pedras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Q5zTZU35Jfrh2NEvy33L","Rio Grande da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3njlJd77W8vJ0O4uKPEo","Riolândia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yhU3CBOAxwd7Nta75I5A","Riversul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("OIl1Kdnr3x75jv1rvJej","Rosana","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("i2LHwKcEtjvdRRWkt0bJ","Roseira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("DAv6Y9g0jCPzrKEC2iIj","Rubiácea","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("fSaKpZgOAXWUcBG97wev","Rubinéia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pYfW4dzzgJuoi3QGFyrO","Sabino","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("b163VVa0zDaT5pYr9Zi1","Sagres","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mcm99XQTRcv4WZdBH0dS","Sales","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MvspE0miI7vGybyiSXLn","Sales Oliveira","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wog7Hm8LaOFOnIDI3uyd","Salesópolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("w61qQBXuGbFtF3HXTWIp","Salmourão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qiX2bG4rChxVsumiCKLW","Saltinho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jmJhVT3afZOOST9235HC","Salto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Htgy4d6GJUQ8MbKfLAOC","Salto de Pirapora","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pdMMOJ2CV9torYb3Zel2","Salto Grande","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("tchQnw4S7pqQHNLkAg8S","Sandovalina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Egr30pGa6YsdQhMte7Ct","Santa Adélia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Y43RiYoDS3lNsnyGO1Hj","Santa Albertina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("vZyRafnCDlXrwVTVOb9g","Santa Bárbara d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AoqiDckR5u3YGKgdpcvL","Santa Branca","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZteXB6RKTyPwy9rv8GYP","Santa Clara d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pKHTwyUDg32DIxkppX4d","Santa Cruz da Conceição","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("eBzxFHWRqQhL82Uwl3dz","Santa Cruz da Esperança","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7sMth6rxvkq5nIPynpPf","Santa Cruz das Palmeiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZidmlUWot7SiqOwhltNI","Santa Cruz do Rio Pardo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lJdGpDafaR0JQ0B640hv","Santa Ernestina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IZZQTh0YJ21CJRb9wmlj","Santa Fé do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Sdy4aR4RZAzifEdXG96O","Santa Gertrudes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("770NpTYdfCmfvtoek2Aq","Santa Isabel","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("g6Efsc1EfxWh6FdA5wAS","Santa Lúcia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TTY5uqPF1WCMXGzuslus","Santa Maria da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ZcJFftBxQPWBCEa0J5YJ","Santa Mercedes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0RFqjONqoAUXQGprzf4D","Santa Rita d'Oeste","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("yhfk1IMssOsm5XZ1c2xT","Santa Rita do Passa Quatro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rCJFoLqVJEUBTsPwGzXV","Santa Rosa de Viterbo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lHmeLVDJ8OFG5C175Y3A","Santa Salete","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("T2A8tfIPT2OkEh9zJmyS","Santana da Ponte Pensa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FOPULY9NZhC8EYhYGmcc","Santana de Parnaíba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("08wuKjh7SuQRF0Zrpc5d","Santo Anastácio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TahTyl6x0JYPB5NGZ1GY","Santo André","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jBg6INDBjdTKdgrE1bY6","Santo Antônio da Alegria","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FNaW9rs1WvZmQFtgrlNi","Santo Antônio de Posse","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0SSmv6KFWgnUGm2Te34K","Santo Antônio do Aracanguá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("K7C3UGyPY8r6TIdyX2Yl","Santo Antônio do Jardim","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uVSmBbdq1ztAaMy3uUL6","Santo Antônio do Pinhal","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("t1CXcFbmls8OlTAlIMDZ","Santo Expedito","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Pqkklh7AbeuRGjWhgxKh","Santópolis do Aguapeí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kXQuS4ZDYbqU7rR3jOZ2","Santos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("S9fRpyPC0rBJqLwX810y","São Bento do Sapucaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("QJgX6qByTjSkp9FetgeA","São Bernardo do Campo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BchBmYq6KSCbEhUekkKW","São Caetano do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hL0q9EQkyHhqCGwQP3ZL","São Carlos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("FClRlnVIiRYR9XcP34uA","São Francisco","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("IIQFWZlfcvDbKyKtJVU1","São João da Boa Vista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3eN2OxB2YhuvFQ6nrodt","São João das Duas Pontes","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HuIHdkqvvAxgMu6fIPnH","São João de Iracema","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ljF21d7nO47Nh25Zf8PS","São João do Pau d'Alho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("J8DBGzSxS1adl968DvrB","São Joaquim da Barra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("EjLkA8UUhd2KkMBJz9O2","São José da Bela Vista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("hKwrmF2xtNx2Sgn7hAUl","São José do Barreiro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("iASLb2X48pgNi9zNnoDZ","São José do Rio Pardo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BM1MXe85Brn0rOFMAenv","São José do Rio Preto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("YAWZWwCVFfK3nMnY57SE","São José dos Campos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ixb1aLQhtfype8zzj9Rj","São Lourenço da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("HUCQhtk4Lff5zmCA4rMk","São Luís do Paraitinga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jijgNQp1EyHd0ynBqxg8","São Manuel","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("aRtk5PerQ7ncIfP2zdiT","São Miguel Arcanjo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dCOpI8pCGlNIVWOCa9cJ","São Paulo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PGWOxqR7bhiJUUUhqy98","São Pedro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("js3AZAWrio1DYyEpUIit","São Pedro do Turvo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uQfpzaECRSVBHSVw60nw","São Roque","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("uwjj5Da65JHgH3l2Axd7","São Sebastião","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("al1O6FZ8f1RRN8WS7vq9","São Sebastião da Grama","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sssovHSDQbkuMq3FGc7G","São Simão","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("qduRHGijdWhMIJ9XE20J","São Vicente","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("v4OUo1wxjy6OTYcAld7o","Sarapuí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("u0SeUqHLJvhrrfKtEQ1r","Sarutaiá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("MiQwQd7ZRDoIPWVNgiUP","Sebastianópolis do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bFp0w2p0H6XWFDrBbTBV","Serra Azul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("2erlOGBloj9Gvi2Icg4f","Serra Negra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kimDsWa3T8GHUdZV2JzL","Serrana","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("0WIqI0I0a9GPJc7li9xp","Sertãozinho","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6gACiis34e9hqUJmTYym","Sete Barras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4py87zRvVCofVWp3NWiZ","Severínia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lvICPBdixVrhwYNkmKL8","Silveiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("742QJxQvJkhYyZnDXJQE","Socorro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wt7FOA2deLbhGIhICGck","Sorocaba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UGBAEh8FMS8nrsB5uGGp","Sud Mennucci","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("i0TYGlHWTttFzu7dbHwS","Sumaré","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UF1vRFhwj7rQ9sZI9Ko1","Suzanápolis","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("4eQcSaGbA3uK5F7tarEh","Suzano","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3GJWvoHjjqf57engg5sm","Tabapuã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("suXKoQBDzeFxLbzH0wYs","Tabatinga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("lNaKyC9eME5h4br7p2gx","Taboão da Serra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("JNfxWJpfMpnPLrJyPfTG","Taciba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("7JjMVQVgETElxleYJkKK","Taguaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("82eTD1LtV14zyQWY15Sk","Taiaçu","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("rCtZoiLrEWEztr42dwM7","Taiúva","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ooH3fp3bZ7cJYypDNnJt","Tambaú","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("AuhAXSJhXUhqzNOsV92t","Tanabi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("05CVUpkcbcKmDN9IEK6m","Tapiraí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("mVkjtXj9WnI3J03bHTBy","Tapiratiba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("evf58ZyDnisum6517m1Z","Taquaral","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("QvzRJcZ47duM3ytYK694","Taquaritinga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Ik6MfXcykktrL5nw9pnz","Taquarituba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("UWdOf3vIFxDP2hdDB2dp","Taquarivaí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("oAcgTo7X784g0KrSJKtv","Tarabai","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("G0W5gC7iAUfL2D7zvN9C","Tarumã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("A8eEz1Ux0U3O2au1wRkI","Tatuí","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("h2Gm7Fyn9QH2hnwmuzKh","Taubaté","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("u6QzZVJfNwdckIrJ41wj","Tejupá","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BTFKRS1DjrqxAHsXJ9xj","Teodoro Sampaio","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("M8pqWm2AcEO2NdUkHsXr","Terra Roxa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6kxQxfZCGtfVokjIKhRx","Tietê","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("LWCJLwEq3CblRq4QeMrD","Timburi","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("8fN5e2QlJDhsspaP867Y","Torre de Pedra","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("kRaVkzDgU0fNMkGX5rEv","Torrinha","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Lo83uIVQWoAm9Eg0UcH1","Trabiju","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("jKSRCpa3l92U5FYcIMln","Tremembé","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("nHPFFQCfDKXPyLR8oMNY","Três Fronteiras","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("XoHj5lbHnTuORj6O341f","Tuiuti","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5B3QcKSFMnqrIiDI2eYE","Tupã","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3CmiQeDR3qMLALcmMFuL","Tupi Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("nca6N17kD2BpTQl5NJjR","Turiúba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("6E1tgYV778uPNuoIt3sC","Turmalina","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sGcQaVp2K65jv6hGD5L6","Ubarana","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("wnyC5rXoow4hoTq93L2c","Ubatuba","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("PjfFJrz6WNYsDSrW6tgm","Ubirajara","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("r0ys6THerB8w0hJAP0L4","Uchoa","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("TCOdv1YAXMyzDBl662Lx","União Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("BYXZxTZSNSeBeKVG7jrw","Urânia","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("dIGF3yV2ygVFNy7ICfZt","Uru","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("aN5ay6YmnsBHQZ18iHjf","Urupês","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("9SnYcdiYQRBiD9872ImV","Valentim Gentil","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Tr7fz4Lu1vSoERhl1wTI","Valinhos","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("JSk1xa4TQa2kO5IxEBy6","Valparaíso","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("sD4wHNMEt4WfNJdjLssL","Vargem","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pxqZkMgfpYaIKzMcJaCm","Vargem Grande do Sul","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("bEvyxPk2kpEqBIL2sJLh","Vargem Grande Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("EufLifZBma5F14fUY9Bi","Várzea Paulista","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("k031GrkZ5pnAUOBrHsn4","Vera Cruz","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("3Yhd4szXwAovGvIbf2pV","Vinhedo","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("5sh8Dq0J09vTIdJcxftM","Viradouro","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("Q80jzJ60GGO6DQtlPIDH","Vista Alegre do Alto","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("h6KL87Edd8qREx77cH9Y","Vitória Brasil","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("ml5bDMBcM0wEfg86oX3Z","Votorantim","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("pqjX6hLfStaZsgOaipKm","Votuporanga","RhxB7uMtgwpjGI8ZCc69", "SP"));
        lista.add(new Cidade("WJ9WBomX8P8aUlr4OaL8","Zacarias","RhxB7uMtgwpjGI8ZCc69", "SP"));
        return lista;
    }
}
