package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class SP {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("","Adamantina","SP"));
        lista.add(new Cidade("","Adolfo","SP"));
        lista.add(new Cidade("","Aguaí","SP"));
        lista.add(new Cidade("","Águas da Prata","SP"));
        lista.add(new Cidade("","Águas de Lindóia","SP"));
        lista.add(new Cidade("","Águas de Santa Bárbara","SP"));
        lista.add(new Cidade("","Águas de São Pedro","SP"));
        lista.add(new Cidade("","Agudos","SP"));
        lista.add(new Cidade("","Alambari","SP"));
        lista.add(new Cidade("","Alfredo Marcondes","SP"));
        lista.add(new Cidade("","Altair","SP"));
        lista.add(new Cidade("","Altinópolis","SP"));
        lista.add(new Cidade("","Alto Alegre","SP"));
        lista.add(new Cidade("","Alumínio","SP"));
        lista.add(new Cidade("","Álvares Florence","SP"));
        lista.add(new Cidade("","Álvares Machado","SP"));
        lista.add(new Cidade("","Álvaro de Carvalho","SP"));
        lista.add(new Cidade("","Alvinlândia","SP"));
        lista.add(new Cidade("","Americana","SP"));
        lista.add(new Cidade("","Américo Brasiliense","SP"));
        lista.add(new Cidade("","Américo de Campos","SP"));
        lista.add(new Cidade("","Amparo","SP"));
        lista.add(new Cidade("","Analândia","SP"));
        lista.add(new Cidade("","Andradina","SP"));
        lista.add(new Cidade("","Angatuba","SP"));
        lista.add(new Cidade("","Anhembi","SP"));
        lista.add(new Cidade("","Anhumas","SP"));
        lista.add(new Cidade("","Aparecida","SP"));
        lista.add(new Cidade("","Aparecida d'Oeste","SP"));
        lista.add(new Cidade("","Apiaí","SP"));
        lista.add(new Cidade("","Araçariguama","SP"));
        lista.add(new Cidade("","Araçatuba","SP"));
        lista.add(new Cidade("","Araçoiaba da Serra","SP"));
        lista.add(new Cidade("","Aramina","SP"));
        lista.add(new Cidade("","Arandu","SP"));
        lista.add(new Cidade("","Arapeí","SP"));
        lista.add(new Cidade("","Araraquara","SP"));
        lista.add(new Cidade("","Araras","SP"));
        lista.add(new Cidade("","Arco-Íris","SP"));
        lista.add(new Cidade("","Arealva","SP"));
        lista.add(new Cidade("","Areias","SP"));
        lista.add(new Cidade("","Areiópolis","SP"));
        lista.add(new Cidade("","Ariranha","SP"));
        lista.add(new Cidade("","Artur Nogueira","SP"));
        lista.add(new Cidade("","Arujá","SP"));
        lista.add(new Cidade("","Aspásia","SP"));
        lista.add(new Cidade("","Assis","SP"));
        lista.add(new Cidade("","Atibaia","SP"));
        lista.add(new Cidade("","Auriflama","SP"));
        lista.add(new Cidade("","Avaí","SP"));
        lista.add(new Cidade("","Avanhandava","SP"));
        lista.add(new Cidade("","Avaré","SP"));
        lista.add(new Cidade("","Bady Bassitt","SP"));
        lista.add(new Cidade("","Balbinos","SP"));
        lista.add(new Cidade("","Bálsamo","SP"));
        lista.add(new Cidade("","Bananal","SP"));
        lista.add(new Cidade("","Barão de Antonina","SP"));
        lista.add(new Cidade("","Barbosa","SP"));
        lista.add(new Cidade("","Bariri","SP"));
        lista.add(new Cidade("","Barra Bonita","SP"));
        lista.add(new Cidade("","Barra do Chapéu","SP"));
        lista.add(new Cidade("","Barra do Turvo","SP"));
        lista.add(new Cidade("","Barretos","SP"));
        lista.add(new Cidade("","Barrinha","SP"));
        lista.add(new Cidade("","Barueri","SP"));
        lista.add(new Cidade("","Bastos","SP"));
        lista.add(new Cidade("","Batatais","SP"));
        lista.add(new Cidade("","Bauru","SP"));
        lista.add(new Cidade("","Bebedouro","SP"));
        lista.add(new Cidade("","Bento de Abreu","SP"));
        lista.add(new Cidade("","Bernardino de Campos","SP"));
        lista.add(new Cidade("","Bertioga","SP"));
        lista.add(new Cidade("","Bilac","SP"));
        lista.add(new Cidade("","Birigui","SP"));
        lista.add(new Cidade("","Biritiba-Mirim","SP"));
        lista.add(new Cidade("","Boa Esperança do Sul","SP"));
        lista.add(new Cidade("","Bocaina","SP"));
        lista.add(new Cidade("","Bofete","SP"));
        lista.add(new Cidade("","Boituva","SP"));
        lista.add(new Cidade("","Bom Jesus dos Perdões","SP"));
        lista.add(new Cidade("","Bom Sucesso de Itararé","SP"));
        lista.add(new Cidade("","Borá","SP"));
        lista.add(new Cidade("","Boracéia","SP"));
        lista.add(new Cidade("","Borborema","SP"));
        lista.add(new Cidade("","Borebi","SP"));
        lista.add(new Cidade("","Botucatu","SP"));
        lista.add(new Cidade("","Bragança Paulista","SP"));
        lista.add(new Cidade("","Braúna","SP"));
        lista.add(new Cidade("","Brejo Alegre","SP"));
        lista.add(new Cidade("","Brodowski","SP"));
        lista.add(new Cidade("","Brotas","SP"));
        lista.add(new Cidade("","Buri","SP"));
        lista.add(new Cidade("","Buritama","SP"));
        lista.add(new Cidade("","Buritizal","SP"));
        lista.add(new Cidade("","Cabrália Paulista","SP"));
        lista.add(new Cidade("","Cabreúva","SP"));
        lista.add(new Cidade("","Caçapava","SP"));
        lista.add(new Cidade("","Cachoeira Paulista","SP"));
        lista.add(new Cidade("","Caconde","SP"));
        lista.add(new Cidade("","Cafelândia","SP"));
        lista.add(new Cidade("","Caiabu","SP"));
        lista.add(new Cidade("","Caieiras","SP"));
        lista.add(new Cidade("","Caiuá","SP"));
        lista.add(new Cidade("","Cajamar","SP"));
        lista.add(new Cidade("","Cajati","SP"));
        lista.add(new Cidade("","Cajobi","SP"));
        lista.add(new Cidade("","Cajuru","SP"));
        lista.add(new Cidade("","Campina do Monte Alegre","SP"));
        lista.add(new Cidade("","Campinas","SP"));
        lista.add(new Cidade("","Campo Limpo Paulista","SP"));
        lista.add(new Cidade("","Campos do Jordão","SP"));
        lista.add(new Cidade("","Campos Novos Paulista","SP"));
        lista.add(new Cidade("","Cananéia","SP"));
        lista.add(new Cidade("","Canas","SP"));
        lista.add(new Cidade("","Cândido Mota","SP"));
        lista.add(new Cidade("","Cândido Rodrigues","SP"));
        lista.add(new Cidade("","Canitar","SP"));
        lista.add(new Cidade("","Capão Bonito","SP"));
        lista.add(new Cidade("","Capela do Alto","SP"));
        lista.add(new Cidade("","Capivari","SP"));
        lista.add(new Cidade("","Caraguatatuba","SP"));
        lista.add(new Cidade("","Carapicuíba","SP"));
        lista.add(new Cidade("","Cardoso","SP"));
        lista.add(new Cidade("","Casa Branca","SP"));
        lista.add(new Cidade("","Cássia dos Coqueiros","SP"));
        lista.add(new Cidade("","Castilho","SP"));
        lista.add(new Cidade("","Catanduva","SP"));
        lista.add(new Cidade("","Catiguá","SP"));
        lista.add(new Cidade("","Cedral","SP"));
        lista.add(new Cidade("","Cerqueira César","SP"));
        lista.add(new Cidade("","Cerquilho","SP"));
        lista.add(new Cidade("","Cesário Lange","SP"));
        lista.add(new Cidade("","Charqueada","SP"));
        lista.add(new Cidade("","Chavantes","SP"));
        lista.add(new Cidade("","Clementina","SP"));
        lista.add(new Cidade("","Colina","SP"));
        lista.add(new Cidade("","Colômbia","SP"));
        lista.add(new Cidade("","Conchal","SP"));
        lista.add(new Cidade("","Conchas","SP"));
        lista.add(new Cidade("","Cordeirópolis","SP"));
        lista.add(new Cidade("","Coroados","SP"));
        lista.add(new Cidade("","Coronel Macedo","SP"));
        lista.add(new Cidade("","Corumbataí","SP"));
        lista.add(new Cidade("","Cosmópolis","SP"));
        lista.add(new Cidade("","Cosmorama","SP"));
        lista.add(new Cidade("","Cotia","SP"));
        lista.add(new Cidade("","Cravinhos","SP"));
        lista.add(new Cidade("","Cristais Paulista","SP"));
        lista.add(new Cidade("","Cruzália","SP"));
        lista.add(new Cidade("","Cruzeiro","SP"));
        lista.add(new Cidade("","Cubatão","SP"));
        lista.add(new Cidade("","Cunha","SP"));
        lista.add(new Cidade("","Descalvado","SP"));
        lista.add(new Cidade("","Diadema","SP"));
        lista.add(new Cidade("","Dirce Reis","SP"));
        lista.add(new Cidade("","Divinolândia","SP"));
        lista.add(new Cidade("","Dobrada","SP"));
        lista.add(new Cidade("","Dois Córregos","SP"));
        lista.add(new Cidade("","Dolcinópolis","SP"));
        lista.add(new Cidade("","Dourado","SP"));
        lista.add(new Cidade("","Dracena","SP"));
        lista.add(new Cidade("","Duartina","SP"));
        lista.add(new Cidade("","Dumont","SP"));
        lista.add(new Cidade("","Echaporã","SP"));
        lista.add(new Cidade("","Eldorado","SP"));
        lista.add(new Cidade("","Elias Fausto","SP"));
        lista.add(new Cidade("","Elisiário","SP"));
        lista.add(new Cidade("","Embaúba","SP"));
        lista.add(new Cidade("","Embu","SP"));
        lista.add(new Cidade("","Embu-Guaçu","SP"));
        lista.add(new Cidade("","Emilianópolis","SP"));
        lista.add(new Cidade("","Engenheiro Coelho","SP"));
        lista.add(new Cidade("","Espírito Santo do Pinhal","SP"));
        lista.add(new Cidade("","Espírito Santo do Turvo","SP"));
        lista.add(new Cidade("","Estiva Gerbi","SP"));
        lista.add(new Cidade("","Estrela d'Oeste","SP"));
        lista.add(new Cidade("","Estrela do Norte","SP"));
        lista.add(new Cidade("","Euclides da Cunha Paulista","SP"));
        lista.add(new Cidade("","Fartura","SP"));
        lista.add(new Cidade("","Fernando Prestes","SP"));
        lista.add(new Cidade("","Fernandópolis","SP"));
        lista.add(new Cidade("","Fernão","SP"));
        lista.add(new Cidade("","Ferraz de Vasconcelos","SP"));
        lista.add(new Cidade("","Flora Rica","SP"));
        lista.add(new Cidade("","Floreal","SP"));
        lista.add(new Cidade("","Florínia","SP"));
        lista.add(new Cidade("","Flórida Paulista","SP"));
        lista.add(new Cidade("","Franca","SP"));
        lista.add(new Cidade("","Francisco Morato","SP"));
        lista.add(new Cidade("","Franco da Rocha","SP"));
        lista.add(new Cidade("","Gabriel Monteiro","SP"));
        lista.add(new Cidade("","Gália","SP"));
        lista.add(new Cidade("","Garça","SP"));
        lista.add(new Cidade("","Gastão Vidigal","SP"));
        lista.add(new Cidade("","Gavião Peixoto","SP"));
        lista.add(new Cidade("","General Salgado","SP"));
        lista.add(new Cidade("","Getulina","SP"));
        lista.add(new Cidade("","Glicério","SP"));
        lista.add(new Cidade("","Guaiçara","SP"));
        lista.add(new Cidade("","Guaimbê","SP"));
        lista.add(new Cidade("","Guaíra","SP"));
        lista.add(new Cidade("","Guapiaçu","SP"));
        lista.add(new Cidade("","Guapiara","SP"));
        lista.add(new Cidade("","Guará","SP"));
        lista.add(new Cidade("","Guaraçaí","SP"));
        lista.add(new Cidade("","Guaraci","SP"));
        lista.add(new Cidade("","Guarani d'Oeste","SP"));
        lista.add(new Cidade("","Guarantã","SP"));
        lista.add(new Cidade("","Guararapes","SP"));
        lista.add(new Cidade("","Guararema","SP"));
        lista.add(new Cidade("","Guaratinguetá","SP"));
        lista.add(new Cidade("","Guareí","SP"));
        lista.add(new Cidade("","Guariba","SP"));
        lista.add(new Cidade("","Guarujá","SP"));
        lista.add(new Cidade("","Guarulhos","SP"));
        lista.add(new Cidade("","Guatapará","SP"));
        lista.add(new Cidade("","Guzolândia","SP"));
        lista.add(new Cidade("","Herculândia","SP"));
        lista.add(new Cidade("","Holambra","SP"));
        lista.add(new Cidade("","Hortolândia","SP"));
        lista.add(new Cidade("","Iacanga","SP"));
        lista.add(new Cidade("","Iacri","SP"));
        lista.add(new Cidade("","Iaras","SP"));
        lista.add(new Cidade("","Ibaté","SP"));
        lista.add(new Cidade("","Ibirá","SP"));
        lista.add(new Cidade("","Ibirarema","SP"));
        lista.add(new Cidade("","Ibitinga","SP"));
        lista.add(new Cidade("","Ibiúna","SP"));
        lista.add(new Cidade("","Icém","SP"));
        lista.add(new Cidade("","Iepê","SP"));
        lista.add(new Cidade("","Igaraçu do Tietê","SP"));
        lista.add(new Cidade("","Igarapava","SP"));
        lista.add(new Cidade("","Igaratá","SP"));
        lista.add(new Cidade("","Iguape","SP"));
        lista.add(new Cidade("","Ilha Comprida","SP"));
        lista.add(new Cidade("","Ilha Solteira","SP"));
        lista.add(new Cidade("","Ilhabela","SP"));
        lista.add(new Cidade("","Indaiatuba","SP"));
        lista.add(new Cidade("","Indiana","SP"));
        lista.add(new Cidade("","Indiaporã","SP"));
        lista.add(new Cidade("","Inúbia Paulista","SP"));
        lista.add(new Cidade("","Ipauçu","SP"));
        lista.add(new Cidade("","Iperó","SP"));
        lista.add(new Cidade("","Ipeúna","SP"));
        lista.add(new Cidade("","Ipiguá","SP"));
        lista.add(new Cidade("","Iporanga","SP"));
        lista.add(new Cidade("","Ipuã","SP"));
        lista.add(new Cidade("","Iracemápolis","SP"));
        lista.add(new Cidade("","Irapuã","SP"));
        lista.add(new Cidade("","Irapuru","SP"));
        lista.add(new Cidade("","Itaberá","SP"));
        lista.add(new Cidade("","Itaí","SP"));
        lista.add(new Cidade("","Itajobi","SP"));
        lista.add(new Cidade("","Itaju","SP"));
        lista.add(new Cidade("","Itanhaém","SP"));
        lista.add(new Cidade("","Itaóca","SP"));
        lista.add(new Cidade("","Itapecerica da Serra","SP"));
        lista.add(new Cidade("","Itapetininga","SP"));
        lista.add(new Cidade("","Itapeva","SP"));
        lista.add(new Cidade("","Itapevi","SP"));
        lista.add(new Cidade("","Itapira","SP"));
        lista.add(new Cidade("","Itapirapuã Paulista","SP"));
        lista.add(new Cidade("","Itápolis","SP"));
        lista.add(new Cidade("","Itaporanga","SP"));
        lista.add(new Cidade("","Itapuí","SP"));
        lista.add(new Cidade("","Itapura","SP"));
        lista.add(new Cidade("","Itaquaquecetuba","SP"));
        lista.add(new Cidade("","Itararé","SP"));
        lista.add(new Cidade("","Itariri","SP"));
        lista.add(new Cidade("","Itatiba","SP"));
        lista.add(new Cidade("","Itatinga","SP"));
        lista.add(new Cidade("","Itirapina","SP"));
        lista.add(new Cidade("","Itirapuã","SP"));
        lista.add(new Cidade("","Itobi","SP"));
        lista.add(new Cidade("","Itu","SP"));
        lista.add(new Cidade("","Itupeva","SP"));
        lista.add(new Cidade("","Ituverava","SP"));
        lista.add(new Cidade("","Jaborandi","SP"));
        lista.add(new Cidade("","Jaboticabal","SP"));
        lista.add(new Cidade("","Jacareí","SP"));
        lista.add(new Cidade("","Jaci","SP"));
        lista.add(new Cidade("","Jacupiranga","SP"));
        lista.add(new Cidade("","Jaguariúna","SP"));
        lista.add(new Cidade("","Jales","SP"));
        lista.add(new Cidade("","Jambeiro","SP"));
        lista.add(new Cidade("","Jandira","SP"));
        lista.add(new Cidade("","Jardinópolis","SP"));
        lista.add(new Cidade("","Jarinu","SP"));
        lista.add(new Cidade("","Jaú","SP"));
        lista.add(new Cidade("","Jeriquara","SP"));
        lista.add(new Cidade("","Joanópolis","SP"));
        lista.add(new Cidade("","João Ramalho","SP"));
        lista.add(new Cidade("","José Bonifácio","SP"));
        lista.add(new Cidade("","Júlio Mesquita","SP"));
        lista.add(new Cidade("","Jumirim","SP"));
        lista.add(new Cidade("","Jundiaí","SP"));
        lista.add(new Cidade("","Junqueirópolis","SP"));
        lista.add(new Cidade("","Juquiá","SP"));
        lista.add(new Cidade("","Juquitiba","SP"));
        lista.add(new Cidade("","Lagoinha","SP"));
        lista.add(new Cidade("","Laranjal Paulista","SP"));
        lista.add(new Cidade("","Lavínia","SP"));
        lista.add(new Cidade("","Lavrinhas","SP"));
        lista.add(new Cidade("","Leme","SP"));
        lista.add(new Cidade("","Lençóis Paulista","SP"));
        lista.add(new Cidade("","Limeira","SP"));
        lista.add(new Cidade("","Lindóia","SP"));
        lista.add(new Cidade("","Lins","SP"));
        lista.add(new Cidade("","Lorena","SP"));
        lista.add(new Cidade("","Lourdes","SP"));
        lista.add(new Cidade("","Louveira","SP"));
        lista.add(new Cidade("","Lucélia","SP"));
        lista.add(new Cidade("","Lucianópolis","SP"));
        lista.add(new Cidade("","Luís Antônio","SP"));
        lista.add(new Cidade("","Luiziânia","SP"));
        lista.add(new Cidade("","Lupércio","SP"));
        lista.add(new Cidade("","Lutécia","SP"));
        lista.add(new Cidade("","Macatuba","SP"));
        lista.add(new Cidade("","Macaubal","SP"));
        lista.add(new Cidade("","Macedônia","SP"));
        lista.add(new Cidade("","Magda","SP"));
        lista.add(new Cidade("","Mairinque","SP"));
        lista.add(new Cidade("","Mairiporã","SP"));
        lista.add(new Cidade("","Manduri","SP"));
        lista.add(new Cidade("","Marabá Paulista","SP"));
        lista.add(new Cidade("","Maracaí","SP"));
        lista.add(new Cidade("","Marapoama","SP"));
        lista.add(new Cidade("","Mariápolis","SP"));
        lista.add(new Cidade("","Marília","SP"));
        lista.add(new Cidade("","Marinópolis","SP"));
        lista.add(new Cidade("","Martinópolis","SP"));
        lista.add(new Cidade("","Matão","SP"));
        lista.add(new Cidade("","Mauá","SP"));
        lista.add(new Cidade("","Mendonça","SP"));
        lista.add(new Cidade("","Meridiano","SP"));
        lista.add(new Cidade("","Mesópolis","SP"));
        lista.add(new Cidade("","Miguelópolis","SP"));
        lista.add(new Cidade("","Mineiros do Tietê","SP"));
        lista.add(new Cidade("","Mira Estrela","SP"));
        lista.add(new Cidade("","Miracatu","SP"));
        lista.add(new Cidade("","Mirandópolis","SP"));
        lista.add(new Cidade("","Mirante do Paranapanema","SP"));
        lista.add(new Cidade("","Mirassol","SP"));
        lista.add(new Cidade("","Mirassolândia","SP"));
        lista.add(new Cidade("","Mococa","SP"));
        lista.add(new Cidade("","Mogi das Cruzes","SP"));
        lista.add(new Cidade("","Mogi-Guaçu","SP"));
        lista.add(new Cidade("","Mogi-Mirim","SP"));
        lista.add(new Cidade("","Mombuca","SP"));
        lista.add(new Cidade("","Monções","SP"));
        lista.add(new Cidade("","Mongaguá","SP"));
        lista.add(new Cidade("","Monte Alegre do Sul","SP"));
        lista.add(new Cidade("","Monte Alto","SP"));
        lista.add(new Cidade("","Monte Aprazível","SP"));
        lista.add(new Cidade("","Monte Azul Paulista","SP"));
        lista.add(new Cidade("","Monte Castelo","SP"));
        lista.add(new Cidade("","Monte Mor","SP"));
        lista.add(new Cidade("","Monteiro Lobato","SP"));
        lista.add(new Cidade("","Morro Agudo","SP"));
        lista.add(new Cidade("","Morungaba","SP"));
        lista.add(new Cidade("","Motuca","SP"));
        lista.add(new Cidade("","Murutinga do Sul","SP"));
        lista.add(new Cidade("","Nantes","SP"));
        lista.add(new Cidade("","Narandiba","SP"));
        lista.add(new Cidade("","Natividade da Serra","SP"));
        lista.add(new Cidade("","Nazaré Paulista","SP"));
        lista.add(new Cidade("","Neves Paulista","SP"));
        lista.add(new Cidade("","Nhandeara","SP"));
        lista.add(new Cidade("","Nipoã","SP"));
        lista.add(new Cidade("","Nova Aliança","SP"));
        lista.add(new Cidade("","Nova Campina","SP"));
        lista.add(new Cidade("","Nova Canaã Paulista","SP"));
        lista.add(new Cidade("","Nova Castilho","SP"));
        lista.add(new Cidade("","Nova Europa","SP"));
        lista.add(new Cidade("","Nova Granada","SP"));
        lista.add(new Cidade("","Nova Guataporanga","SP"));
        lista.add(new Cidade("","Nova Independência","SP"));
        lista.add(new Cidade("","Nova Luzitânia","SP"));
        lista.add(new Cidade("","Nova Odessa","SP"));
        lista.add(new Cidade("","Novais","SP"));
        lista.add(new Cidade("","Novo Horizonte","SP"));
        lista.add(new Cidade("","Nuporanga","SP"));
        lista.add(new Cidade("","Ocauçu","SP"));
        lista.add(new Cidade("","Óleo","SP"));
        lista.add(new Cidade("","Olímpia","SP"));
        lista.add(new Cidade("","Onda Verde","SP"));
        lista.add(new Cidade("","Oriente","SP"));
        lista.add(new Cidade("","Orindiúva","SP"));
        lista.add(new Cidade("","Orlândia","SP"));
        lista.add(new Cidade("","Osasco","SP"));
        lista.add(new Cidade("","Oscar Bressane","SP"));
        lista.add(new Cidade("","Osvaldo Cruz","SP"));
        lista.add(new Cidade("","Ourinhos","SP"));
        lista.add(new Cidade("","Ouro Verde","SP"));
        lista.add(new Cidade("","Ouroeste","SP"));
        lista.add(new Cidade("","Pacaembu","SP"));
        lista.add(new Cidade("","Palestina","SP"));
        lista.add(new Cidade("","Palmares Paulista","SP"));
        lista.add(new Cidade("","Palmeira d'Oeste","SP"));
        lista.add(new Cidade("","Palmital","SP"));
        lista.add(new Cidade("","Panorama","SP"));
        lista.add(new Cidade("","Paraguaçu Paulista","SP"));
        lista.add(new Cidade("","Paraibuna","SP"));
        lista.add(new Cidade("","Paraíso","SP"));
        lista.add(new Cidade("","Paranapanema","SP"));
        lista.add(new Cidade("","Paranapuã","SP"));
        lista.add(new Cidade("","Parapuã","SP"));
        lista.add(new Cidade("","Pardinho","SP"));
        lista.add(new Cidade("","Pariquera-Açu","SP"));
        lista.add(new Cidade("","Parisi","SP"));
        lista.add(new Cidade("","Patrocínio Paulista","SP"));
        lista.add(new Cidade("","Paulicéia","SP"));
        lista.add(new Cidade("","Paulínia","SP"));
        lista.add(new Cidade("","Paulistânia","SP"));
        lista.add(new Cidade("","Paulo de Faria","SP"));
        lista.add(new Cidade("","Pederneiras","SP"));
        lista.add(new Cidade("","Pedra Bela","SP"));
        lista.add(new Cidade("","Pedranópolis","SP"));
        lista.add(new Cidade("","Pedregulho","SP"));
        lista.add(new Cidade("","Pedreira","SP"));
        lista.add(new Cidade("","Pedrinhas Paulista","SP"));
        lista.add(new Cidade("","Pedro de Toledo","SP"));
        lista.add(new Cidade("","Penápolis","SP"));
        lista.add(new Cidade("","Pereira Barreto","SP"));
        lista.add(new Cidade("","Pereiras","SP"));
        lista.add(new Cidade("","Peruíbe","SP"));
        lista.add(new Cidade("","Piacatu","SP"));
        lista.add(new Cidade("","Piedade","SP"));
        lista.add(new Cidade("","Pilar do Sul","SP"));
        lista.add(new Cidade("","Pindamonhangaba","SP"));
        lista.add(new Cidade("","Pindorama","SP"));
        lista.add(new Cidade("","Pinhalzinho","SP"));
        lista.add(new Cidade("","Piquerobi","SP"));
        lista.add(new Cidade("","Piquete","SP"));
        lista.add(new Cidade("","Piracaia","SP"));
        lista.add(new Cidade("","Piracicaba","SP"));
        lista.add(new Cidade("","Piraju","SP"));
        lista.add(new Cidade("","Pirajuí","SP"));
        lista.add(new Cidade("","Pirangi","SP"));
        lista.add(new Cidade("","Pirapora do Bom Jesus","SP"));
        lista.add(new Cidade("","Pirapozinho","SP"));
        lista.add(new Cidade("","Pirassununga","SP"));
        lista.add(new Cidade("","Piratininga","SP"));
        lista.add(new Cidade("","Pitangueiras","SP"));
        lista.add(new Cidade("","Planalto","SP"));
        lista.add(new Cidade("","Platina","SP"));
        lista.add(new Cidade("","Poá","SP"));
        lista.add(new Cidade("","Poloni","SP"));
        lista.add(new Cidade("","Pompéia","SP"));
        lista.add(new Cidade("","Pongaí","SP"));
        lista.add(new Cidade("","Pontal","SP"));
        lista.add(new Cidade("","Pontalinda","SP"));
        lista.add(new Cidade("","Pontes Gestal","SP"));
        lista.add(new Cidade("","Populina","SP"));
        lista.add(new Cidade("","Porangaba","SP"));
        lista.add(new Cidade("","Porto Feliz","SP"));
        lista.add(new Cidade("","Porto Ferreira","SP"));
        lista.add(new Cidade("","Potim","SP"));
        lista.add(new Cidade("","Potirendaba","SP"));
        lista.add(new Cidade("","Pracinha","SP"));
        lista.add(new Cidade("","Pradópolis","SP"));
        lista.add(new Cidade("","Praia Grande","SP"));
        lista.add(new Cidade("","Pratânia","SP"));
        lista.add(new Cidade("","Presidente Alves","SP"));
        lista.add(new Cidade("","Presidente Bernardes","SP"));
        lista.add(new Cidade("","Presidente Epitácio","SP"));
        lista.add(new Cidade("","Presidente Prudente","SP"));
        lista.add(new Cidade("","Presidente Venceslau","SP"));
        lista.add(new Cidade("","Promissão","SP"));
        lista.add(new Cidade("","Quadra","SP"));
        lista.add(new Cidade("","Quatá","SP"));
        lista.add(new Cidade("","Queiroz","SP"));
        lista.add(new Cidade("","Queluz","SP"));
        lista.add(new Cidade("","Quintana","SP"));
        lista.add(new Cidade("","Rafard","SP"));
        lista.add(new Cidade("","Rancharia","SP"));
        lista.add(new Cidade("","Redenção da Serra","SP"));
        lista.add(new Cidade("","Regente Feijó","SP"));
        lista.add(new Cidade("","Reginópolis","SP"));
        lista.add(new Cidade("","Registro","SP"));
        lista.add(new Cidade("","Restinga","SP"));
        lista.add(new Cidade("","Ribeira","SP"));
        lista.add(new Cidade("","Ribeirão Bonito","SP"));
        lista.add(new Cidade("","Ribeirão Branco","SP"));
        lista.add(new Cidade("","Ribeirão Corrente","SP"));
        lista.add(new Cidade("","Ribeirão do Sul","SP"));
        lista.add(new Cidade("","Ribeirão dos Índios","SP"));
        lista.add(new Cidade("","Ribeirão Grande","SP"));
        lista.add(new Cidade("","Ribeirão Pires","SP"));
        lista.add(new Cidade("","Ribeirão Preto","SP"));
        lista.add(new Cidade("","Rifaina","SP"));
        lista.add(new Cidade("","Rincão","SP"));
        lista.add(new Cidade("","Rinópolis","SP"));
        lista.add(new Cidade("","Rio Claro","SP"));
        lista.add(new Cidade("","Rio das Pedras","SP"));
        lista.add(new Cidade("","Rio Grande da Serra","SP"));
        lista.add(new Cidade("","Riolândia","SP"));
        lista.add(new Cidade("","Riversul","SP"));
        lista.add(new Cidade("","Rosana","SP"));
        lista.add(new Cidade("","Roseira","SP"));
        lista.add(new Cidade("","Rubiácea","SP"));
        lista.add(new Cidade("","Rubinéia","SP"));
        lista.add(new Cidade("","Sabino","SP"));
        lista.add(new Cidade("","Sagres","SP"));
        lista.add(new Cidade("","Sales","SP"));
        lista.add(new Cidade("","Sales Oliveira","SP"));
        lista.add(new Cidade("","Salesópolis","SP"));
        lista.add(new Cidade("","Salmourão","SP"));
        lista.add(new Cidade("","Saltinho","SP"));
        lista.add(new Cidade("","Salto","SP"));
        lista.add(new Cidade("","Salto de Pirapora","SP"));
        lista.add(new Cidade("","Salto Grande","SP"));
        lista.add(new Cidade("","Sandovalina","SP"));
        lista.add(new Cidade("","Santa Adélia","SP"));
        lista.add(new Cidade("","Santa Albertina","SP"));
        lista.add(new Cidade("","Santa Bárbara d'Oeste","SP"));
        lista.add(new Cidade("","Santa Branca","SP"));
        lista.add(new Cidade("","Santa Clara d'Oeste","SP"));
        lista.add(new Cidade("","Santa Cruz da Conceição","SP"));
        lista.add(new Cidade("","Santa Cruz da Esperança","SP"));
        lista.add(new Cidade("","Santa Cruz das Palmeiras","SP"));
        lista.add(new Cidade("","Santa Cruz do Rio Pardo","SP"));
        lista.add(new Cidade("","Santa Ernestina","SP"));
        lista.add(new Cidade("","Santa Fé do Sul","SP"));
        lista.add(new Cidade("","Santa Gertrudes","SP"));
        lista.add(new Cidade("","Santa Isabel","SP"));
        lista.add(new Cidade("","Santa Lúcia","SP"));
        lista.add(new Cidade("","Santa Maria da Serra","SP"));
        lista.add(new Cidade("","Santa Mercedes","SP"));
        lista.add(new Cidade("","Santa Rita d'Oeste","SP"));
        lista.add(new Cidade("","Santa Rita do Passa Quatro","SP"));
        lista.add(new Cidade("","Santa Rosa de Viterbo","SP"));
        lista.add(new Cidade("","Santa Salete","SP"));
        lista.add(new Cidade("","Santana da Ponte Pensa","SP"));
        lista.add(new Cidade("","Santana de Parnaíba","SP"));
        lista.add(new Cidade("","Santo Anastácio","SP"));
        lista.add(new Cidade("","Santo André","SP"));
        lista.add(new Cidade("","Santo Antônio da Alegria","SP"));
        lista.add(new Cidade("","Santo Antônio de Posse","SP"));
        lista.add(new Cidade("","Santo Antônio do Aracanguá","SP"));
        lista.add(new Cidade("","Santo Antônio do Jardim","SP"));
        lista.add(new Cidade("","Santo Antônio do Pinhal","SP"));
        lista.add(new Cidade("","Santo Expedito","SP"));
        lista.add(new Cidade("","Santópolis do Aguapeí","SP"));
        lista.add(new Cidade("","Santos","SP"));
        lista.add(new Cidade("","São Bento do Sapucaí","SP"));
        lista.add(new Cidade("","São Bernardo do Campo","SP"));
        lista.add(new Cidade("","São Caetano do Sul","SP"));
        lista.add(new Cidade("","São Carlos","SP"));
        lista.add(new Cidade("","São Francisco","SP"));
        lista.add(new Cidade("","São João da Boa Vista","SP"));
        lista.add(new Cidade("","São João das Duas Pontes","SP"));
        lista.add(new Cidade("","São João de Iracema","SP"));
        lista.add(new Cidade("","São João do Pau d'Alho","SP"));
        lista.add(new Cidade("","São Joaquim da Barra","SP"));
        lista.add(new Cidade("","São José da Bela Vista","SP"));
        lista.add(new Cidade("","São José do Barreiro","SP"));
        lista.add(new Cidade("","São José do Rio Pardo","SP"));
        lista.add(new Cidade("","São José do Rio Preto","SP"));
        lista.add(new Cidade("","São José dos Campos","SP"));
        lista.add(new Cidade("","São Lourenço da Serra","SP"));
        lista.add(new Cidade("","São Luís do Paraitinga","SP"));
        lista.add(new Cidade("","São Manuel","SP"));
        lista.add(new Cidade("","São Miguel Arcanjo","SP"));
        lista.add(new Cidade("","São Paulo","SP"));
        lista.add(new Cidade("","São Pedro","SP"));
        lista.add(new Cidade("","São Pedro do Turvo","SP"));
        lista.add(new Cidade("","São Roque","SP"));
        lista.add(new Cidade("","São Sebastião","SP"));
        lista.add(new Cidade("","São Sebastião da Grama","SP"));
        lista.add(new Cidade("","São Simão","SP"));
        lista.add(new Cidade("","São Vicente","SP"));
        lista.add(new Cidade("","Sarapuí","SP"));
        lista.add(new Cidade("","Sarutaiá","SP"));
        lista.add(new Cidade("","Sebastianópolis do Sul","SP"));
        lista.add(new Cidade("","Serra Azul","SP"));
        lista.add(new Cidade("","Serra Negra","SP"));
        lista.add(new Cidade("","Serrana","SP"));
        lista.add(new Cidade("","Sertãozinho","SP"));
        lista.add(new Cidade("","Sete Barras","SP"));
        lista.add(new Cidade("","Severínia","SP"));
        lista.add(new Cidade("","Silveiras","SP"));
        lista.add(new Cidade("","Socorro","SP"));
        lista.add(new Cidade("","Sorocaba","SP"));
        lista.add(new Cidade("","Sud Mennucci","SP"));
        lista.add(new Cidade("","Sumaré","SP"));
        lista.add(new Cidade("","Suzanápolis","SP"));
        lista.add(new Cidade("","Suzano","SP"));
        lista.add(new Cidade("","Tabapuã","SP"));
        lista.add(new Cidade("","Tabatinga","SP"));
        lista.add(new Cidade("","Taboão da Serra","SP"));
        lista.add(new Cidade("","Taciba","SP"));
        lista.add(new Cidade("","Taguaí","SP"));
        lista.add(new Cidade("","Taiaçu","SP"));
        lista.add(new Cidade("","Taiúva","SP"));
        lista.add(new Cidade("","Tambaú","SP"));
        lista.add(new Cidade("","Tanabi","SP"));
        lista.add(new Cidade("","Tapiraí","SP"));
        lista.add(new Cidade("","Tapiratiba","SP"));
        lista.add(new Cidade("","Taquaral","SP"));
        lista.add(new Cidade("","Taquaritinga","SP"));
        lista.add(new Cidade("","Taquarituba","SP"));
        lista.add(new Cidade("","Taquarivaí","SP"));
        lista.add(new Cidade("","Tarabai","SP"));
        lista.add(new Cidade("","Tarumã","SP"));
        lista.add(new Cidade("","Tatuí","SP"));
        lista.add(new Cidade("","Taubaté","SP"));
        lista.add(new Cidade("","Tejupá","SP"));
        lista.add(new Cidade("","Teodoro Sampaio","SP"));
        lista.add(new Cidade("","Terra Roxa","SP"));
        lista.add(new Cidade("","Tietê","SP"));
        lista.add(new Cidade("","Timburi","SP"));
        lista.add(new Cidade("","Torre de Pedra","SP"));
        lista.add(new Cidade("","Torrinha","SP"));
        lista.add(new Cidade("","Trabiju","SP"));
        lista.add(new Cidade("","Tremembé","SP"));
        lista.add(new Cidade("","Três Fronteiras","SP"));
        lista.add(new Cidade("","Tuiuti","SP"));
        lista.add(new Cidade("","Tupã","SP"));
        lista.add(new Cidade("","Tupi Paulista","SP"));
        lista.add(new Cidade("","Turiúba","SP"));
        lista.add(new Cidade("","Turmalina","SP"));
        lista.add(new Cidade("","Ubarana","SP"));
        lista.add(new Cidade("","Ubatuba","SP"));
        lista.add(new Cidade("","Ubirajara","SP"));
        lista.add(new Cidade("","Uchoa","SP"));
        lista.add(new Cidade("","União Paulista","SP"));
        lista.add(new Cidade("","Urânia","SP"));
        lista.add(new Cidade("","Uru","SP"));
        lista.add(new Cidade("","Urupês","SP"));
        lista.add(new Cidade("","Valentim Gentil","SP"));
        lista.add(new Cidade("","Valinhos","SP"));
        lista.add(new Cidade("","Valparaíso","SP"));
        lista.add(new Cidade("","Vargem","SP"));
        lista.add(new Cidade("","Vargem Grande do Sul","SP"));
        lista.add(new Cidade("","Vargem Grande Paulista","SP"));
        lista.add(new Cidade("","Várzea Paulista","SP"));
        lista.add(new Cidade("","Vera Cruz","SP"));
        lista.add(new Cidade("","Vinhedo","SP"));
        lista.add(new Cidade("","Viradouro","SP"));
        lista.add(new Cidade("","Vista Alegre do Alto","SP"));
        lista.add(new Cidade("","Vitória Brasil","SP"));
        lista.add(new Cidade("","Votorantim","SP"));
        lista.add(new Cidade("","Votuporanga","SP"));
        lista.add(new Cidade("","Zacarias","SP"));
        return lista;
    }
}
