package br.ufms.nafmanager.persistencies;

import java.util.ArrayList;
import java.util.List;

import br.ufms.nafmanager.model.Cidade;

public class TO {
    public static List<Cidade> getCidades() {
        List<Cidade> lista = new ArrayList<Cidade>();
        lista.add(new Cidade("FuxxqMHItzPnsC52wlvy","Abreulândia","TO"));
        lista.add(new Cidade("8KmGxhZHkj8SbAXYKeW8","Aguiarnópolis","TO"));
        lista.add(new Cidade("0mGN6lZ5nGG7x8r86iVO","Aliança do Tocantins","TO"));
        lista.add(new Cidade("rnUzi9zUw030TmKcgE50","Almas","TO"));
        lista.add(new Cidade("ca9CGlslQKh4HzOLN3Bi","Alvorada","TO"));
        lista.add(new Cidade("Mc39ijTOeWd5wLEyMoDl","Anajanópolis","TO"));
        lista.add(new Cidade("SD7g2lecOdX5Kj9XzZnk","Ananás","TO"));
        lista.add(new Cidade("52cUITzho8vathHAO0Fo","Angico","TO"));
        lista.add(new Cidade("K6G4npusB6yPAeTTgNuT","Aparecida do Rio Negro","TO"));
        lista.add(new Cidade("1Jsa5VVQFdquIkp3yOp8","Apinajé","TO"));
        lista.add(new Cidade("sNa09LY7z5awtInHkfBB","Aragaçuí","TO"));
        lista.add(new Cidade("2cPoezYBXrKV8av41APQ","Aragominas","TO"));
        lista.add(new Cidade("55XEw86j9toTwmv8qfAd","Araguacema","TO"));
        lista.add(new Cidade("z9tPmptai5FvMv4wRzov","Araguaçu","TO"));
        lista.add(new Cidade("SK6BWU8g2Wbml5dJXJKG","Araguaína","TO"));
        lista.add(new Cidade("uNnrXhz2HiURloKOesLW","Araguanã","TO"));
        lista.add(new Cidade("lR2NbhgVNCMZuhWrk45H","Araguatins","TO"));
        lista.add(new Cidade("VCj9zHKqIhLyaivqtEEZ","Arapoema","TO"));
        lista.add(new Cidade("sLI8TT4qQHainDGtjok8","Arraias","TO"));
        lista.add(new Cidade("28NEpe7m0DMslKIL4W2q","Augustinópolis","TO"));
        lista.add(new Cidade("1oUmdgAVkvAxa92uwfCz","Aurora do Tocantins","TO"));
        lista.add(new Cidade("j6EjRT765dAwRvmIMoou","Axixá do Tocantins","TO"));
        lista.add(new Cidade("XQNAOZbrG3yLeyXmpB1a","Babaçulândia","TO"));
        lista.add(new Cidade("SAns7mOCpdB6YOPwjlxT","Bandeirantes do Tocantins","TO"));
        lista.add(new Cidade("T4xuiq2iwE5X8EV8mdNH","Barra do Grota","TO"));
        lista.add(new Cidade("00UVPpveJNws5gFkd1AT","Barra do Ouro","TO"));
        lista.add(new Cidade("zShKqWFT8LPGNeLJuPAq","Barrolândia","TO"));
        lista.add(new Cidade("5MWhwo6IX7FfGDHSFJkt","Bernardo Sayão","TO"));
        lista.add(new Cidade("3CqMzDR0n4M5gzMkk1EA","Bom Jesus do Tocantins","TO"));
        lista.add(new Cidade("S4RPJTHBly7La20sPGay","Brasilândia","TO"));
        lista.add(new Cidade("bRlZ6Nw9NnVp0l3jqZXM","Brasilândia do Tocantins","TO"));
        lista.add(new Cidade("2F3QnQyIHk724Cz2svOm","Brejinho de Nazaré","TO"));
        lista.add(new Cidade("NQTAzgGoTQfBHWvIzQWh","Buriti do Tocantins","TO"));
        lista.add(new Cidade("87saaJ88YHjZ88YXBVTJ","Cachoeirinha","TO"));
        lista.add(new Cidade("imvbtscF8Nj6BuYGOD0A","Campos Lindos","TO"));
        lista.add(new Cidade("yBheW3eTmwfOddBOAWRS","Cana Brava","TO"));
        lista.add(new Cidade("W9pmq0Z6loLQGgJz1SYU","Cariri do Tocantins","TO"));
        lista.add(new Cidade("WC8TLhFoAbPvaMMCBMGi","Carmolândia","TO"));
        lista.add(new Cidade("rPzasfgz5hqCGksJmGN8","Carrasco Bonito","TO"));
        lista.add(new Cidade("wXlk3GsirdbZYeE6gNro","Cartucho","TO"));
        lista.add(new Cidade("HdhFo3AQMpxcXt4HDboJ","Caseara","TO"));
        lista.add(new Cidade("DrFH43vKlBdChEvNrB7g","Centenário","TO"));
        lista.add(new Cidade("yInKXSEOUoyolAJIOmdl","Chapada da Natividade","TO"));
        lista.add(new Cidade("AlZS1QvNkBadnt9Yb6EX","Chapada de Areia","TO"));
        lista.add(new Cidade("7aFEyxAId7C5eF2fmmDX","Cocalândia","TO"));
        lista.add(new Cidade("bQ9nTbS2ymo0EZic2T3B","Cocalinho","TO"));
        lista.add(new Cidade("JnXHBe75VyUU4WRmISyV","Colinas do Tocantins","TO"));
        lista.add(new Cidade("iJtwxP3uZHtaCOEObY3z","Colméia","TO"));
        lista.add(new Cidade("omPjYKc7IJ2NJInhx6iZ","Combinado","TO"));
        lista.add(new Cidade("n4hFJZWbu19TVi6p0loI","Conceição do Tocantins","TO"));
        lista.add(new Cidade("oCDpGjFZtUptf0IcZyrp","Correinha","TO"));
        lista.add(new Cidade("bVKhervjC84Drbpa2tUR","Couto de Magalhães","TO"));
        lista.add(new Cidade("ZA8Em1dXOPmWzHJIgTID","Craolândia","TO"));
        lista.add(new Cidade("lpSuXyxRvzbKlWnwDCI4","Cristalândia","TO"));
        lista.add(new Cidade("8bTRJo72M4zMEK0xyPSN","Crixás","TO"));
        lista.add(new Cidade("QjTweD0JhFmEH4sxkZSi","Crixás do Tocantins","TO"));
        lista.add(new Cidade("gxuzPPJdnR4XI1bMOfTw","Darcinópolis","TO"));
        lista.add(new Cidade("C0vNcg1lOoRF2MhJRv4C","Dianópolis","TO"));
        lista.add(new Cidade("BrJXLSqOnAyJj70r6LCE","Divinópolis do Tocantins","TO"));
        lista.add(new Cidade("Fiy0z3vP2ikoft5unulQ","Dois Irmãos do Tocantins","TO"));
        lista.add(new Cidade("JtWxEf5mpKPhrceeCOh1","Duerê","TO"));
        lista.add(new Cidade("wuiRCKujL1xdMVSHI1rw","Escondido","TO"));
        lista.add(new Cidade("VlQs9kRdNCR80cIZN56O","Esperantina","TO"));
        lista.add(new Cidade("oN7rbnidOm5b3kHqqfOY","Fátima","TO"));
        lista.add(new Cidade("2YUrhr2rYPZhiI2mhgbg","Figueirópolis","TO"));
        lista.add(new Cidade("8aIrxaIQHQeLRw77WvXT","Filadélfia","TO"));
        lista.add(new Cidade("ImUj2sIe3RbwLEsZLhiy","Formoso do Araguaia","TO"));
        lista.add(new Cidade("SVKuH6idH1pbhaUWBOcd","Fortaleza do Tabocão","TO"));
        lista.add(new Cidade("AP3nZnvtBpdepNdpTugh","Goianorte","TO"));
        lista.add(new Cidade("e4UPx5zH7daUaZpqqp6Z","Goiatins","TO"));
        lista.add(new Cidade("9VYz4rkX1g3EeLnJ8UoF","Guaraí","TO"));
        lista.add(new Cidade("YxVqpoYCyZMYB3Zxd1CO","Gurupi","TO"));
        lista.add(new Cidade("VofoClsgZG3QTZdho5Cb","Ilha Barreira Branca","TO"));
        lista.add(new Cidade("RUjcNzkhc0uQ0BwZY8Mt","Ipueiras","TO"));
        lista.add(new Cidade("1MDjhfjs9DxRfWrD2mG2","Itacajá","TO"));
        lista.add(new Cidade("kHXtcuUZBDuWOqW3aQzb","Itaguatins","TO"));
        lista.add(new Cidade("2bh8Fkl9RyvIN5qP5dtm","Itapiratins","TO"));
        lista.add(new Cidade("0cHPpXZnuBAdyaW7qvAs","Itaporã do Tocantins","TO"));
        lista.add(new Cidade("PfNkEs64WYnHRQ9amqGC","Jaú do Tocantins","TO"));
        lista.add(new Cidade("8IA0FYub7GFKldQw0CZ0","Juarina","TO"));
        lista.add(new Cidade("sVscoskgJXtRJGm3t3F8","Jussara","TO"));
        lista.add(new Cidade("w5kLsXNKDfuyT94AOepz","Lagoa da Confusão","TO"));
        lista.add(new Cidade("HCS5qStBgIbC5mYoSgLI","Lagoa do Tocantins","TO"));
        lista.add(new Cidade("UA5Qh61Im7nOq3Xcd7sw","Lajeado","TO"));
        lista.add(new Cidade("elu74hzPz5ckDNlgHAJ0","Lavandeira","TO"));
        lista.add(new Cidade("AO9JrkqFC8SYNTcSADuk","Lizarda","TO"));
        lista.add(new Cidade("86yrk6CBsUSFk8qCiWjr","Luzimangues","TO"));
        lista.add(new Cidade("AxlE0qhMwk5Z2LzTnS3L","Luzinópolis","TO"));
        lista.add(new Cidade("agAXzPACj8I8g4dW1myZ","Marianópolis do Tocantins","TO"));
        lista.add(new Cidade("z47yDmTxMeBR9IeSCwRW","Mateiros","TO"));
        lista.add(new Cidade("6aFf9uXYgrpbmQfobkdG","Maurilândia do Tocantins","TO"));
        lista.add(new Cidade("9NdWWmCHmwUkv3gk3YTS","Miracema do Tocantins","TO"));
        lista.add(new Cidade("BxFy73UNIqeZJ4h4F7fl","Mirandópolis","TO"));
        lista.add(new Cidade("tlQxt6Lc67Lad9dNaSAj","Miranorte","TO"));
        lista.add(new Cidade("zTuNRpzNcdUepSgdhszb","Monte do Carmo","TO"));
        lista.add(new Cidade("7YeydqFFR2HmjiMuO3Qa","Monte Lindo","TO"));
        lista.add(new Cidade("6s3hnCEhyP2xi3WKfwia","Monte Santo do Tocantins","TO"));
        lista.add(new Cidade("nb0myfq1weffaTNFCNj5","Muricilândia","TO"));
        lista.add(new Cidade("gNX5QYuZ4rfGt76il6bX","Natal","TO"));
        lista.add(new Cidade("TBEmkmZNUkQQcUOjkAMx","Natividade","TO"));

        return lista;
    }
}
